### ISSUE TITLE
masc_tagged leads to a decoding error

### ISSUE THREAD

**Issue by mheilman** [nltk/nltk#1015]
The `masc_tagged` corpus cannot be loaded in its entirety due do a decoding error, at least on my machine (python 3.4.3 on OS X) and using the universal tagset option.  (This was originally noticed by @DerrickHiggins.)

This example code triggers the error for me:

```
from nltk.corpus import masc_tagged
[x for x in masc_tagged.tagged_words(tagset='universal')]
```

Here's the traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/ipdb/__main__.py", line 157, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/mheilman/Desktop/tmp.py", line 2, in <module>
    from nltk.corpus import masc_tagged
  File "/Users/mheilman/Desktop/tmp.py", line 3, in <listcomp>
    [x for x in masc_tagged.tagged_words(tagset='universal')]
  File "/usr/local/lib/python3.4/site-packages/nltk/corpus/reader/util.py", line 394, in iterate_from
    for tok in piece.iterate_from(max(0, start_tok-offset)):
  File "/usr/local/lib/python3.4/site-packages/nltk/corpus/reader/util.py", line 291, in iterate_from
    tokens = self.read_block(self._stream)
  File "/usr/local/lib/python3.4/site-packages/nltk/corpus/reader/tagged.py", line 241, in read_block
    for para_str in self._para_block_reader(stream):
  File "/usr/local/lib/python3.4/site-packages/nltk/corpus/reader/util.py", line 564, in read_blankline_block
    line = stream.readline()
  File "/usr/local/lib/python3.4/site-packages/nltk/data.py", line 1095, in readline
    new_chars = self._read(readsize)
  File "/usr/local/lib/python3.4/site-packages/nltk/data.py", line 1322, in _read
    chars, bytes_decoded = self._incr_decode(bytes)
  File "/usr/local/lib/python3.4/site-packages/nltk/data.py", line 1352, in _incr_decode
    return self.decode(bytes, 'strict')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd5 in position 133: ordinal not in range(128)
```

**Comment by stevenbird** [comment]
Thanks for reporting the problem @mheilman. I'm getting the same error. I'll see if anyone who works with MASC can advise.

**Comment by mheilman** [comment]
If I set the encoding in `nltk.corpus.__init__.py`

```
masc_tagged = LazyCorpusLoader(
    'masc_tagged', CategorizedTaggedCorpusReader, r'(spoken|written)/.*\.txt',
    cat_file='categories.txt', tagset='wsj', encoding="ISO-8859-1", sep="_")
```

then it doesn't run into that exception, but I noticed that apostrophes appear as a diacritic (e.g., `('Őll', 'VERB'),`) and maybe a few other things (e.g., `('Ň', 'NOUN')`).  This seems incorrect.  Perhaps the corpus is actually in another encoding than ISO-8859-2.  I'll try to figure out which one that might be, but if you have any suggestions, please let me know.

The ANC page says the original corpus is utf-8 (http://www.anc.org/data/anc-second-release/encoding/), so it's not clear how it got into non-utf-8.

**Comment by mheilman** [comment]
fwiw, `file` says the file that causes the exception is ISO-8859 (it says the same for some of the other files as well).

`interview_nathan_hole.txt:   ISO-8859 text, with very long lines`

**Comment by ksuderman** [comment]
The MASC corpus should be encoded using UTF-8.  Can you give that a try?

**Comment by mheilman** [comment]
Sorry, it seems to not be UTF-8.  Specifically, I tried setting the encoding explicitly to `'utf8'` in the `LazyCorpusLoader` call in `nltk.corpus.__init__.py`, but that leads to a similar error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 133: invalid continuation byte
```

**Comment by stevenbird** [comment]
So it appears that the MASC corpus uses mac-roman encoding. I'd prefer to change that to utf8, rather than change NLTK to specify mac-roman.

**Comment by stevenbird** [comment]
@ksuderman has provided a utf8 version and I've uploaded it to the [NLTK data collection](http://www.nltk.org/nltk_data/), cf https://github.com/nltk/nltk_data/commit/9a81625189c6c70ebb5f9464a20823b5e1e9fde6

@mheilman would you please update your copy (e.g. using `python -m nltk.downloader masc_tagged`) and letting us know if the problem persists?

**Comment by mheilman** [comment]
After downloading the updated zip, I first changed my local nltk checkout so that `nltk.corpus.masc_tagged` is initialized with `encoding="utf8"` instead of `encoding="ascii"`.

Unfortunately, one of the new files seems to be blank (`masc_tagged/spoken/2nd_Gore-Bush.txt`), leading to this error:

```
Traceback (most recent call last):
  File "tmp.py", line 3, in <module>
    foo = [x for x in masc_tagged.tagged_words(tagset='universal')]
  File "tmp.py", line 3, in <listcomp>
    foo = [x for x in masc_tagged.tagged_words(tagset='universal')]
  File "/Users/civisemployee/src/nltk/nltk/corpus/reader/util.py", line 394, in iterate_from
    for tok in piece.iterate_from(max(0, start_tok-offset)):
  File "/Users/civisemployee/src/nltk/nltk/corpus/reader/util.py", line 336, in iterate_from
    assert self._len is not None
AssertionError
```

I tried deleting that file from the archive `~/nltk_data/corpora/masc_tagged.zip` to see if there are any other issues, and unfortunately, after doing so, it still produces a `UnicodeDecodeError`.  Also, running `file` in my terminal still shows a number of the files as "ISO-8859", including the one that causes the decoding error (`masc_tagged/spoken/interview_nathan_hole.txt`).

Thanks for looking into this.

**Comment by ksuderman** [comment]
The two pull requests (#1020 and nltk/nltk_data#29) should fix the problem. I regenerated the files from the original MASC data and I have loaded all the files with nltk as utf-8 files.

**Comment by ksuderman** [comment]
After further investigation I found that one of our annotators manually corrected some of the original files in masc_tagged, which is likely how some of the files got converted to mac-roman.  Let me verify that their edits were not lost before accepting nltk/nltk_data#29

**Comment by ksuderman** [comment]
Done.  I've pushed a new masc_tagged.zip to the PR nltk/nltk_data#29

**Comment by mheilman** [comment]
nltk/nltk_data#29 looks good to me.  The corpus gets read in and, at a glance, the apostrophes and such look right.

Thanks so much for putting this together!

**Comment by stevenbird** [comment]
Thanks @ksuderman and @mheilman. I've merged this PR and updated the index (with updated checksum).
