### ISSUE TITLE
Data access down?

### ISSUE THREAD

**Issue by ensignavenger** [nltk/nltk#1022]
I just spent the whole day learning nltk and creating a demo project and now when trying to download the corpora to text, I am getting: [Errno 104] Connection reset by peer
I found the data on the nltk website and could not download it directly from there, either!

Is there  a server down or somthing?

**Comment by stevenbird** [comment]
@ensignavenger – I'm not able to replicate this problem. Would you please try again, and confirm that you're not behind a firewall or something that could be blocking your access?

**Comment by ensignavenger** [comment]
Sorry, I forgot to update this- I was able to finally get it to work- I think the problem was my high latency satelite Internet connection was probably conflicting with an aggressive connection timeout or somthing similiar on the download server. 

After network conditions improved, I was able to download the data :)  Thanks!
