### ISSUE TITLE
Similarity measures, path_similarity and wup_similarity, potential bug

### ISSUE THREAD

**Issue by iuhaq** [nltk/nltk#1023]
Recently, I measured similarity between two words using NLTK wordnet reader module. I got following strange behavior when I used path_similarity function:

> > > item=wn.synset('item.r.01')
> > > tax=wn.synset('tax.v.02')
> > > print tax.path_similarity(item)
> > > 0.25
> > > print item.path_similarity(tax)
> > > None

Now, my question is, why path_similarity gives different similarity values for same Synsets if I change the order? I am using NLTK 3.0.0.

> > > print nltk.**version**
> > > 3.0.0

I think there is a check missing at the start of path_similarity functions which makes sure that both words belong to same path of speech. Furthermore, original paper talks only about verbs and nouns because it is hard to establish an IS-A relationship for adverbs and adjectives.

Hopefully, this would help you to reproduce the described bug.

thanks,
irfan

**Comment by trinitys** [comment]
path_similarity() across parts of speech is not commutative (by design).
The key to that is the difference in the notion of root for different
synsets. If you look into the code for path_similarity(), you'll notice the
default variable simulate_root=True, that creates a dummy root in the tree
of the taxonomy that allows traversing from one part of speech to another
in the first place. Also notice the call to self._needs_root() which
returns whether a synset needs to be assigned a root. This method acts
differently for wn.synset('tax.v.02') and wn.synset('item.r.01')  and
causes the difference in behavior you're noticing.

**Comment by iuhaq** [comment]
I got it but if I use simulate_root=False then similarity between two verbs will also be None. And this is conflicting with other implementations like WordNet::Similarity. So, similarity between same part of speech is supported but not between different part of speech. For example, WordNet::Similarity gives a similarity value between 'price' and 'tax' as:
price#v#1  tax#v#2  0.333333333333333 
But similarity between 'item.r.01' and 'tax.v.02' is None or negative.

Do you think it is a good idea to compare current NLTK implementation with other renowned implementations like WordNet::Similarity?

Actually, I did perform a comparison between NLTK and WordNet::Similarity on 36 million pairs of words and found some interesting facts. Above mentioned is one of them.

thanks,
irfan

**Comment by stevenbird** [comment]
Ideally NLTK's implementation of similarity would be identical in behaviour to WordNet::Similarity, for a given version of WordNet.

@haqirfan:

Can you please give an example of when the similarity between two verbs is None?

When you write: "similarity between 'item.r.01' and 'tax.v.02' is None or negative" – are you talking about NLTK's version? What do you mean "None or negative"?

**Comment by iuhaq** [comment]
For example, consider two words 'tax' and 'distance'. if I give these two words to WordNet::Similarity and use path similarity with root_node=yes, it returns following values:
tax#v#2  distance#v#1  0.2
tax#v#2  distance#v#2  0.2
tax#v#3  distance#v#2  0.166666666666667
tax#v#3  distance#v#1  0.166666666666667
tax#v#1  distance#v#2  0.142857142857143
tax#v#1  distance#v#1  0.142857142857143
tax#v#4  distance#v#1  0.142857142857143
tax#v#4  distance#v#2  0.142857142857143

tax#n#1  distance#n#5  0.1
tax#n#1  distance#n#6  0.1
tax#n#1  distance#n#1  0.1
tax#n#1  distance#n#3  0.0833333333333333
tax#n#1  distance#n#2  0.0769230769230769
tax#n#1  distance#n#4  0.0769230769230769

tax#v#4  distance#n#6  -1000000
tax#v#1  distance#n#1  -1000000
tax#v#4  distance#n#5  -1000000
tax#n#1  distance#v#2  -1000000
tax#v#1  distance#n#2  -1000000
tax#v#3  distance#n#2  -1000000
tax#v#2  distance#n#4  -1000000
tax#v#4  distance#n#1  -1000000
tax#v#3  distance#n#1  -1000000
tax#v#1  distance#n#5  -1000000
tax#v#4  distance#n#2  -1000000
tax#v#3  distance#n#3  -1000000
tax#v#2  distance#n#5  -1000000
tax#v#4  distance#n#4  -1000000
tax#v#2  distance#n#6  -1000000
tax#v#1  distance#n#4  -1000000
tax#v#2  distance#n#3  -1000000
tax#v#3  distance#n#5  -1000000
tax#n#1  distance#v#1  -1000000
tax#v#3  distance#n#6  -1000000
tax#v#3  distance#n#4  -1000000
tax#v#1  distance#n#6  -1000000
tax#v#2  distance#n#1  -1000000
tax#v#1  distance#n#3  -1000000
tax#v#4  distance#n#3  -1000000
tax#v#2  distance#n#2  -1000000

So, WordNet::Similarity only returns values for same part of speech. And if I use root_node=no then it returns similarity values only for noun part of speech.

Now, when I use NLTK's path similarity function and use simulate_root=False, it returns following values:
Synset('tax.n.01') Synset('distance.n.05') 0.1
Synset('tax.n.01') Synset('distance.n.06') 0.1
Synset('tax.n.01') Synset('distance.n.01') 0.1
Synset('tax.n.01') Synset('distance.n.03') 0.0833333333333
Synset('tax.n.01') Synset('distance.n.02') 0.0769230769231
Synset('tax.n.01') Synset('distance.n.04') 0.0769230769231

Synset('tax.n.01') Synset('distance.v.01') None
Synset('tax.n.01') Synset('outdistance.v.01') None
Synset('tax.v.01') Synset('distance.n.01') None
Synset('tax.v.01') Synset('distance.n.02') None
Synset('tax.v.01') Synset('distance.n.03') None
Synset('tax.v.01') Synset('distance.n.04') None
Synset('tax.v.01') Synset('distance.n.05') None
Synset('tax.v.01') Synset('distance.n.06') None
Synset('tax.v.01') Synset('distance.v.01') None
Synset('tax.v.01') Synset('outdistance.v.01') None
Synset('tax.v.02') Synset('distance.n.01') None
Synset('tax.v.02') Synset('distance.n.02') None
Synset('tax.v.02') Synset('distance.n.03') None
Synset('tax.v.02') Synset('distance.n.04') None
Synset('tax.v.02') Synset('distance.n.05') None
Synset('tax.v.02') Synset('distance.n.06') None
Synset('tax.v.02') Synset('distance.v.01') None
Synset('tax.v.02') Synset('outdistance.v.01') None
Synset('tax.v.03') Synset('distance.n.01') None
Synset('tax.v.03') Synset('distance.n.02') None
Synset('tax.v.03') Synset('distance.n.03') None
Synset('tax.v.03') Synset('distance.n.04') None
Synset('tax.v.03') Synset('distance.n.05') None
Synset('tax.v.03') Synset('distance.n.06') None
Synset('tax.v.03') Synset('distance.v.01') None
Synset('tax.v.03') Synset('outdistance.v.01') None
Synset('tax.v.04') Synset('distance.n.01') None
Synset('tax.v.04') Synset('distance.n.02') None
Synset('tax.v.04') Synset('distance.n.03') None
Synset('tax.v.04') Synset('distance.n.04') None
Synset('tax.v.04') Synset('distance.n.05') None
Synset('tax.v.04') Synset('distance.n.06') None
Synset('tax.v.04') Synset('distance.v.01') None
Synset('tax.v.04') Synset('outdistance.v.01') None

This shows that NLTK does not find any similarity between verb senses of both words which is similar to WordNet::Similarity. Now, if I use simulate_root=True, NLTK returns following:

Synset('tax.v.02') Synset('distance.v.01') 0.2
Synset('tax.v.02') Synset('outdistance.v.01') 0.2
Synset('tax.v.03') Synset('distance.v.01') 0.166666666667
Synset('tax.v.03') Synset('outdistance.v.01') 0.166666666667
Synset('tax.v.01') Synset('outdistance.v.01') 0.142857142857
Synset('tax.v.01') Synset('distance.v.01') 0.142857142857
Synset('tax.v.04') Synset('distance.v.01') 0.142857142857
Synset('tax.v.04') Synset('outdistance.v.01') 0.142857142857

Synset('tax.n.01') Synset('distance.n.01') 0.1
Synset('tax.n.01') Synset('distance.n.05') 0.1
Synset('tax.n.01') Synset('distance.n.06') 0.1
Synset('tax.n.01') Synset('distance.n.03') 0.0833333333333
Synset('tax.n.01') Synset('distance.n.02') 0.0769230769231
Synset('tax.n.01') Synset('distance.n.04') 0.0769230769231

Synset('tax.n.01') Synset('distance.v.01') None
Synset('tax.n.01') Synset('outdistance.v.01') None
Synset('tax.v.01') Synset('distance.n.01') 0.0833333333333
Synset('tax.v.01') Synset('distance.n.02') 0.0909090909091
Synset('tax.v.01') Synset('distance.n.03') 0.0833333333333
Synset('tax.v.01') Synset('distance.n.04') 0.0769230769231
Synset('tax.v.01') Synset('distance.n.05') 0.1
Synset('tax.v.01') Synset('distance.n.06') 0.1

Synset('tax.v.02') Synset('distance.n.01') 0.1
Synset('tax.v.02') Synset('distance.n.02') 0.111111111111
Synset('tax.v.02') Synset('distance.n.03') 0.1
Synset('tax.v.02') Synset('distance.n.04') 0.0909090909091
Synset('tax.v.02') Synset('distance.n.05') 0.125
Synset('tax.v.02') Synset('distance.n.06') 0.125

Synset('tax.v.03') Synset('distance.n.01') 0.0909090909091
Synset('tax.v.03') Synset('distance.n.02') 0.1
Synset('tax.v.03') Synset('distance.n.03') 0.0909090909091
Synset('tax.v.03') Synset('distance.n.04') 0.0833333333333
Synset('tax.v.03') Synset('distance.n.05') 0.111111111111
Synset('tax.v.03') Synset('distance.n.06') 0.111111111111

Synset('tax.v.04') Synset('distance.n.01') 0.0833333333333
Synset('tax.v.04') Synset('distance.n.02') 0.0909090909091
Synset('tax.v.04') Synset('distance.n.03') 0.0833333333333
Synset('tax.v.04') Synset('distance.n.04') 0.0769230769231
Synset('tax.v.04') Synset('distance.n.05') 0.1
Synset('tax.v.04') Synset('distance.n.06') 0.1

This time it returns similarity values for verb senses as well and values are similar with WordNet::Similarity. But the problem is, NLTK also returns similarity value between a verb sense and a noun which is not a scenario in WordNet::Similarity. And more importantly, if I change the order of words in path similarity function for NLTK, it returns completely different values for different part of speech and I do not observe this behavior in WordNet::Similarity. Following are the values NLTK returns when I change word order while calling path similarity function:

Synset('distance.v.01') Synset('tax.v.02') 0.2
Synset('outdistance.v.01') Synset('tax.v.02') 0.2
Synset('outdistance.v.01') Synset('tax.v.03') 0.166666666667
Synset('distance.v.01') Synset('tax.v.03') 0.166666666667
Synset('distance.v.01') Synset('tax.v.04') 0.142857142857
Synset('distance.v.01') Synset('tax.v.01') 0.142857142857
Synset('outdistance.v.01') Synset('tax.v.01') 0.142857142857
Synset('outdistance.v.01') Synset('tax.v.04') 0.142857142857

Synset('distance.n.01') Synset('tax.n.01') 0.1
Synset('distance.n.05') Synset('tax.n.01') 0.1
Synset('distance.n.06') Synset('tax.n.01') 0.1
Synset('distance.n.03') Synset('tax.n.01') 0.0833333333333
Synset('distance.n.02') Synset('tax.n.01') 0.0769230769231
Synset('distance.n.04') Synset('tax.n.01') 0.0769230769231

Synset('distance.v.01') Synset('tax.n.01') 0.0909090909091
Synset('outdistance.v.01') Synset('tax.n.01') 0.0909090909091

Synset('distance.n.01') Synset('tax.v.01') None
Synset('distance.n.01') Synset('tax.v.02') None
Synset('distance.n.01') Synset('tax.v.03') None
Synset('distance.n.01') Synset('tax.v.04') None
Synset('distance.n.02') Synset('tax.v.01') None
Synset('distance.n.02') Synset('tax.v.02') None
Synset('distance.n.02') Synset('tax.v.03') None
Synset('distance.n.02') Synset('tax.v.04') None
Synset('distance.n.03') Synset('tax.v.01') None
Synset('distance.n.03') Synset('tax.v.02') None
Synset('distance.n.03') Synset('tax.v.03') None
Synset('distance.n.03') Synset('tax.v.04') None
Synset('distance.n.04') Synset('tax.v.01') None
Synset('distance.n.04') Synset('tax.v.02') None
Synset('distance.n.04') Synset('tax.v.03') None
Synset('distance.n.04') Synset('tax.v.04') None
Synset('distance.n.05') Synset('tax.v.01') None
Synset('distance.n.05') Synset('tax.v.02') None
Synset('distance.n.05') Synset('tax.v.03') None
Synset('distance.n.05') Synset('tax.v.04') None
Synset('distance.n.06') Synset('tax.v.01') None
Synset('distance.n.06') Synset('tax.v.02') None
Synset('distance.n.06') Synset('tax.v.03') None
Synset('distance.n.06') Synset('tax.v.04') None

Hopefully it would help you. I am using NLTK version 3.0 and WordNet 3.0.0. WordNet::Similarity version 2.05 with WordNet 3.0.0.

You may use WordNet::Similarity's online version at following: http://maraca.d.umn.edu/cgi-bin/similarity/similarity.cgi?word1=tax&senses1=all&word2=distance&senses2=all&measure=path&rootnode=yes

But online version is super slow.

**Comment by acattle** [comment]
The WordNet online link supplied by @haqirfan explicitly results in an error if the parts of speech are different, regardless of order. If this is indeed the expected behaviour, it would be nice if NLTK did the same instead of either failing silently (i.e. returning `None`) or incorrectly succeeding.

Also, if this is the expected behaviour then I'd like to see the documentation changed to reflect this. For example, this excerpt from `Synset.lowest_common_hypernyms()` documentation:
```
:param simulate_root: The various verb taxonomies do not
            share a single root which disallows this metric from working for
            synsets that are not connected. This flag (False by default)
            creates a fake root that connects all the taxonomies. Set it
            to True to enable this behavior. For the noun taxonomy,
            there is usually a default root except for WordNet version 1.6.
            If you are using wordnet 1.6, a fake root will need to be added
            for nouns as well.
```

It's ambiguous as to whether it connects **all** taxonomies or all _verb_ taxonomies.

Personally, I would like to see the ability to connect **all** taxonomies however that then raises the question of whether there should be a single simulated root (all taxonomies linked to a single root regardless of POS) or multiple simulated roots (i.e. all verb taxonomies connected by a simulated root which itself is connected to an additional simulated root that connects various POS)
