### ISSUE TITLE
Cannot use more than a 100 patterns with the RegexpTagger on Python 2.7 (regression from nltk v2.x)

### ISSUE THREAD

**Issue by pombreda** [nltk/nltk#1025]
See the reason here:
https://github.com/nltk/nltk/commit/dd2a827b32900cc6be73b9e45c3b818b7c343e0f#commitcomment-11844004
`re` can have only 100 named groups in Python 2.7.
Taggers that worked with nltk 2.x no longer work with 3.x

**Comment by pombreda** [comment]
Actually even a moderately sized list of regexp quickly creates 100+ named groups

**Comment by pombreda** [comment]
@aboSamoor : the commit that triggered this was yours. Any clue for an alternative way?

**Comment by jnothman** [comment]
Note that it doesn't matter whether the groups are named or numbered. I think you simply need to split this into regexps of 100 expressions. However, one may want to change any non-essential capturing groups in expressions into non-capturing groups.

Another side effect of the above optimisation is that back-references in expressions won't work (e.g. `r'(a|b)c\1'` matches `aca` but not `acb`), although this may not be frequently used in taggers.

**Comment by pombreda** [comment]
@jnothman my tag regexps are actually not complex, though they include some alternations in groups.
I do not use backrefs (who should? ;) )... 

That said, I may easily replace the groups by non-capturing ones, but I cannot split my tagger in multiple taggers to go below the 100 limit, can I?

FWIW, the offending std lib code enforcing the 100 limits can be removed without noticeable side effect. It is gone in Python 3.x

But it cannot be monkey patched easily... and monkey patching the stdlib is not something to take on lightly anyway.

I am surprised there are so few occurrences of this regression found in the wild. I could find only one. 

Here is a trivial failing test highlighting the issue:

``` python
import nltk
patterns = [(str(i), 'NNP',) for i in range(100)]
tagger = nltk.RegexpTagger(patterns)

```

and its output on Python 2.7 and nltk 3.0.3:

``` python
>>> import sys
>>> sys.version
'2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]'
>>> import nltk
>>> nltk.__version__
'3.0.3'
>>> patterns = [(str(i), 'NNP',) for i in range(100)]
>>> tagger = nltk.RegexpTagger(patterns)
[ u'(?P<g0>0)',
  u'(?P<g1>1)',
  u'(?P<g2>2)',
  u'(?P<g3>3)',
  u'(?P<g4>4)',
  u'(?P<g5>5)',
  u'(?P<g6>6)',
  u'(?P<g7>7)',
  u'(?P<g8>8)',
  u'(?P<g9>9)',
  u'(?P<g10>10)',
  u'(?P<g11>11)',
  u'(?P<g12>12)',
  u'(?P<g13>13)',
  u'(?P<g14>14)',
  u'(?P<g15>15)',
  u'(?P<g16>16)',
  u'(?P<g17>17)',
  u'(?P<g18>18)',
  u'(?P<g19>19)',
  u'(?P<g20>20)',
  u'(?P<g21>21)',
  u'(?P<g22>22)',
  u'(?P<g23>23)',
  u'(?P<g24>24)',
  u'(?P<g25>25)',
  u'(?P<g26>26)',
  u'(?P<g27>27)',
  u'(?P<g28>28)',
  u'(?P<g29>29)',
  u'(?P<g30>30)',
  u'(?P<g31>31)',
  u'(?P<g32>32)',
  u'(?P<g33>33)',
  u'(?P<g34>34)',
  u'(?P<g35>35)',
  u'(?P<g36>36)',
  u'(?P<g37>37)',
  u'(?P<g38>38)',
  u'(?P<g39>39)',
  u'(?P<g40>40)',
  u'(?P<g41>41)',
  u'(?P<g42>42)',
  u'(?P<g43>43)',
  u'(?P<g44>44)',
  u'(?P<g45>45)',
  u'(?P<g46>46)',
  u'(?P<g47>47)',
  u'(?P<g48>48)',
  u'(?P<g49>49)',
  u'(?P<g50>50)',
  u'(?P<g51>51)',
  u'(?P<g52>52)',
  u'(?P<g53>53)',
  u'(?P<g54>54)',
  u'(?P<g55>55)',
  u'(?P<g56>56)',
  u'(?P<g57>57)',
  u'(?P<g58>58)',
  u'(?P<g59>59)',
  u'(?P<g60>60)',
  u'(?P<g61>61)',
  u'(?P<g62>62)',
  u'(?P<g63>63)',
  u'(?P<g64>64)',
  u'(?P<g65>65)',
  u'(?P<g66>66)',
  u'(?P<g67>67)',
  u'(?P<g68>68)',
  u'(?P<g69>69)',
  u'(?P<g70>70)',
  u'(?P<g71>71)',
  u'(?P<g72>72)',
  u'(?P<g73>73)',
  u'(?P<g74>74)',
  u'(?P<g75>75)',
  u'(?P<g76>76)',
  u'(?P<g77>77)',
  u'(?P<g78>78)',
  u'(?P<g79>79)',
  u'(?P<g80>80)',
  u'(?P<g81>81)',
  u'(?P<g82>82)',
  u'(?P<g83>83)',
  u'(?P<g84>84)',
  u'(?P<g85>85)',
  u'(?P<g86>86)',
  u'(?P<g87>87)',
  u'(?P<g88>88)',
  u'(?P<g89>89)',
  u'(?P<g90>90)',
  u'(?P<g91>91)',
  u'(?P<g92>92)',
  u'(?P<g93>93)',
  u'(?P<g94>94)',
  u'(?P<g95>95)',
  u'(?P<g96>96)',
  u'(?P<g97>97)',
  u'(?P<g98>98)',
  u'(?P<g99>99)']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/tst/local/lib/python2.7/site-packages/nltk/tag/sequential.py", line 539, in __init__
    self._regexs = re.compile('|'.join('(?P<%s>%s)' % (label, regex) for regex,label in regexps_labels))
  File "/home/me/tst/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/home/me/tst/lib/python2.7/re.py", line 242, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/me/tst/lib/python2.7/sre_compile.py", line 509, in compile
    "sorry, but this version only supports 100 named groups"
AssertionError: sorry, but this version only supports 100 named groups
```

**Comment by pombreda** [comment]
So I was able to get through by refactoring my patterns a bit by merging several smaller patterns in one . A tad uglier and less readable by ok.
Also the performance optimization supposedly gained from this change in handling patterns in 3.x ranges from neutral to minuscule to negative based on a fairly large test suite of mine and is generally insignificant. As the saying goes, premature optimization is the root of ....

@aboSamoor do you recall what was the reason for this change? did you had any profiling showing this was a bottleneck? 

If there is no real benefits to this extra code I would be in favour of reverting to the previous 2.x code that worked fine, was simpler and did not had the issue highlighted here.
@stevenbird would you accept a patch for this?

Note that in my setup, I use the one `re` optimization that works really well for me when there are a lot of patterns: increasing the re cache size to a large enough number (at the cost of using a bit more memory):

``` python
import re
re._MAXCACHE = 100000
```

When using a lot of regex, this works wonders.

**Comment by jnothman** [comment]
I get the impression from #200 that reverting the combination of all expressions is a good idea, but that all expressions should be compiled in the constructor.

**Comment by pombreda** [comment]
Since `re` caches compiled regexes, pre-compiling regex can have a performance benefit only if you create a lot of regexes and use the standard cache value.

That could happen rather quickly with `nltk` of course. Increasing the cache size is an option that keeps the code simpler IMHO. 

In some use, pre-compiling in `__init__` could have an adverse impact if you were to create many taggers objects and have a small/standard cache: each object creation could be impacted.

When there a is a properly sized cache, `re` are compiled on first use and fetched from cache afterwards. 
So the solution is rather usage-specific. 

Another problem with #200 is that there are no tests.

**Comment by jnothman** [comment]
Indeed, I was surprised that there should be such a great speed-up from
pre-compilation. Thanks for clarifying the purpose of the max cache
parameter.

**Comment by stevenbird** [comment]
Thanks @pombreda, @jnothman. I like the suggestion of pre-compiling but not pre-combining the expressions. @pombreda would you be willing to submit a PR for this please? Would it be worth mentioning `re._MAXCACHE` in the RegexpTagger docstring?

**Comment by jnothman** [comment]
I think @pombreda https://github.com/pombreda's point is that
precompilation should be unnecessary with an increased _MAXCACHE. Would it
be rude to just set  re._MAXCACHE = max(re._MAXCACHE, 1000) in locations
where regexps are in high use, so that there is a decent setting out of the
box?

**Comment by jnothman** [comment]
Still, I think that solution (pre-compiling but not pre-combining) should be fine as creating many large taggers at once without ample memory for their patterns seems an unlikely scenario.

**Comment by stevenbird** [comment]
Thanks for clarifying @jnothman. I like your idea to set a larger value for `_MAXCACHE`, assuming there's no penalty. (Regexp objects must be variable in size so I assume it's not a simple question of reserving memory).

Note that other NLTK modules include compilation of regexp parameters, e.g.:
- https://github.com/nltk/nltk/blob/develop/nltk/stem/regexp.py#L46
- https://github.com/nltk/nltk/blob/develop/nltk/chat/util.py#L52
- https://github.com/nltk/nltk/blob/develop/nltk/chunk/regexp.py#L293 (checks that it's not already compiled)

In the case of the regexp tagger, I don't think we need to consider the possibility of the regexps being supplied already compiled by the user (is this incompatible with pickling?)

**Comment by pombreda** [comment]
@jnothman @stevenbird : re setting up `re._MAXCACHE`, this could be done with caution, testing that you are not decreasing it (or may be not changing it at all if it is not the default.`_MAXCACHE` only defines the cache eviction policy (which is a simple dict otherwise) not the size of any preallocated data structure

@stevenbird you wrote:

> I don't think we need to consider the possibility of the regexps being supplied already compiled by the user (is this incompatible with pickling?)

This could be a possibility but it not supported any now.  and a quick test shows that a ccomplie re pickles alright... some magic going on there

**Comment by pombreda** [comment]
@stevenbird you wrote:

> would you be willing to submit a PR for this please? Would it be worth mentioning re._MAXCACHE in the RegexpTagger docstring?

Sure thing. Let me work on this and come back in a few days.

**Comment by ened** [comment]
This issue prevents tests in project scancode from being executed successfully on OS X. Anyone got a fix in sight?

**Comment by pombredanne** [comment]
@ened are you sure? ScanCode runs Travis on Mac and Linux and all tests pass alright: https://travis-ci.org/nexB/scancode-toolkit 
This is why https://github.com/nexB/scancode-toolkit/tree/7b264410bc43133046c9fadf35636d085d72b78b/thirdparty/prod contains a vendored copy of NTLK 2.x .... 
I will eventually upgrade NLTK to v3 in ScanCode at some time, and submit some patch upstream here then. It is true that this temporarily in a minor pain and is in the way of this issue here: https://github.com/nexB/scancode-toolkit/issues/24
Now if you have a build/test issue with scancode on Mac that is a bug to me, nltk or not.... Feel free to file a bug there

**Comment by pombredanne** [comment]
> > @stevenbird you wrote:
> >     would you be willing to submit a PR for this please? Would it be worth mentioning re._MAXCACHE in the RegexpTagger docstring?

I wrote

> Sure thing. Let me work on this and come back in a few days.

I guess I dropped the ball there... ;)

**Comment by pombredanne** [comment]
About the MAXCACHE discussion above, FWIW I use it in scancode here: https://github.com/nexB/scancode-toolkit/blob/d48f396efdd8df44758014866e6b92653f902003/src/commoncode/__init__.py#L26

**Comment by ened** [comment]
@pombredanne Not sure, but that message is popping up once I install scan code using easy_install etc from the repository. Will double check and report there..

**Comment by ened** [comment]
@pombredanne turns out to be environment / usage problem. All fine now. Thanks!

**Comment by pombredanne** [comment]
So I really need to work on this .... Though I am surprised none else faced the issue. I will get a proposed fix this month.

**Comment by pombredanne** [comment]
I verified this fix on the https://github.com/nexb/scancode-toolkit  test suites and all my tests pass with NLTK 3.2 alright.
There is a slight performance decrease for this use case between 2.0b4 and 3.2 but nothing serious.

**Comment by pombredanne** [comment]
This has been fixed, merged, verified and released. Closing now.!
