### ISSUE TITLE
RunTimeWarning while running WSD/Lesk

### ISSUE THREAD

**Issue by hammansamuel** [nltk/nltk#1029]
I run this code, and get the output quoted below

``` python
from nltk.wsd import lesk
sent = 'I went to the bank to deposit my money'
wrd = 'deposit'
print lesk(sent.split(), wrd)
```

``` python
/usr/local/lib/python2.7/dist-packages/nltk-3.0.0-py2.7.egg/nltk/compat.py:475: 
RuntimeWarning: Argument <type 'str'> is not an unicode object. 
Passing an encoded string will likely have unexpected results.
return transliterate(method(self))

Synset('down_payment.n.01')
```

**Comment by jnothman** [comment]
In Python 2, `'x'` means x is a sequence of bytes, not a unicode string. Try `u'I went to the bank...'` and `u'deposit'`.

**Comment by hammansamuel** [comment]
Actually, maybe my example was over-simplified. In my code, the `sent` variable gets data from a file that has unicode characters

**Comment by dimazest** [comment]
Could you update NLTK to the latest version, the `nltk.wsd` code was changed after NLTK 3.0.0.

Does the code like:

``` python
synset = lesk(sent.split(), wrd)  # instead of printing the result, just store it
```

yield the same warning?

Actually, it seems that the warning is raised when the word (`wrd` in your example) contains non-ascii characters, and the synset is being printed. In this case the magic of getting an  ascii string out of a unicode string throws a warning. Could you check what word triggers the warning?

I've tried your example on Python 2.7 but didn't get any warning.

**Comment by dimazest** [comment]
It seems that the problem is in Synset repr https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L963

``` python
@python_2_unicode_compatible
class Synset(_WordNetObject):

    ...

    def __repr__(self):
        return "%s('%s')" % (type(self).__name__, self._name)
```

I can't come up with an example that triggers the warning, but I see why it's triggered. If you show an example that does trigger a warning, I'll be able to fix this behavior.

**Comment by alvations** [comment]
@hwsamuel Ah ha, I think i know what happened. 

Did this error:

```
/usr/local/lib/python2.7/dist-packages/nltk-3.0.0-py2.7.egg/nltk/compat.py:475: 
RuntimeWarning: Argument <type 'str'> is not an unicode object. 
Passing an encoded string will likely have unexpected results.
return transliterate(method(self))

Synset('down_payment.n.01')
```

occur because you did this:

```
from nltk.wsd import lesk
sent = 'I went to the bank to deposit my money'
wrd = 'deposit'
print lesk(sent.split(), wrd)
```

Or did you do something like:

```
from nltk.wsd import lesk
with open('infile.txt', 'r') as fin:
    for sent in fin:
        print lesk(sent.split(), 'deposit')
```

If you have done an `open('infile.txt', 'r')` in python2 the default encoding is not 'utf8' because of strange `str()` representation when you `print`. Try this instead:

```
from nltk.wsd import lesk
import io
with io.open('infile.txt', 'r', encoding='utf8') as fin:
    for sent in fin:
        print lesk(sent.split(), 'deposit')
```

@hwsamuel does the `io.open()` resolve your problem or is the wsd module still creating problems?

**Comment by hammansamuel** [comment]
I did the former, i.e. without opening a file

**Comment by alvations** [comment]
@hwsamuel , use `io.open` and the problems should be resolved. This is a good reference for dealing with text I/O in python: http://stackoverflow.com/questions/5250744/difference-between-open-and-codecs-open-in-python =)

**Comment by hammansamuel** [comment]
The problem does seem to be related to `print`. If I do the following, the program gives the desired output without any errors.

``` python
from nltk.wsd import lesk
sent = 'I went to the bank to deposit my money'
wrd = 'deposit'
lesk(sent.split(), wrd)
```

**Comment by alvations** [comment]
@hwsamuel Possibly, it's a problem with locale , default encoding, or how you control the I/O. Always use the encoding parameter when using `io.open()` and that should minimize encoding issues when dealing with text.
