### ISSUE TITLE
Abney Chunker

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#103]
I have had occasion to use Steven Abney's partial parser (or chunker) and it's really good and really 
fast! It's written in pure C so an actual implementation in Python should be easier. It's been on my 
todo list for a while but I haven't found the time.

There is no real webpage but the documentation is included in the tarball on his webpage below. 
Click on the link called 'CASS'. 

http://www.vinartus.net/spa/

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=520</p>

**Comment by alvations** [comment]
We might have to close this issue unless Steven Abney re-writes the code in C and we understands what i's doing quickly without reading through 60 pages of the documentation =)

> Cass is a partial parser that used to be available from this page. Unfortunately, it no longer compiles under current versions of gcc, and fixing the problem would require a fairly substantial rewrite.

**Comment by stevenbird** [comment]
I agree, thanks @alvations.
