### ISSUE TITLE
Doctests and unicode failures

### ISSUE THREAD

**Issue by fievelk** [nltk/nltk#1042]
If I run, for example, `tokenize/simple.py` from console using python2.7, I get several failures because of unicode `u` prefix:

```
**********************************************************************
File "simple.py", line 21, in __main__
Failed example:
    s.split()
Expected:
    ['Good', 'muffins', 'cost', '$3.88', 'in', 'New', 'York.',
    'Please', 'buy', 'me', 'two', 'of', 'them.', 'Thanks.']
Got:
    [u'Good', u'muffins', u'cost', u'$3.88', u'in', u'New', u'York.', u'Please', u'buy', u'me', u'two', u'of', u'them.', u'Thanks.']
**********************************************************************
```

Is there a way to solve this problem?

**Comment by fievelk** [comment]
I solved it using the following code:

```
if __name__ == '__main__':
    import sys
    import doctest
    from nltk.test import doctest_nose_plugin
    doctest.DocTestSuite(sys.modules['__main__'], checker=doctest_nose_plugin._UnicodeOutputChecker())
```

It seems that NLTK is actually already solving the problem with unicode (see [NLTK Doctests porting notes](http://www.nltk.org/dev/python3porting.html#doctests-porting-notes)), but I suppose that this is only applied when tests are executed "globally", using Tox ([NLTK Testing](https://github.com/nltk/nltk/blob/develop/web/dev/local_testing.rst)) and not when doctests are directly called by command line.

**Comment by kmike** [comment]
You can execute individual tests using tox, e.g.: `tox -e py33 -- nltk.test.unit.test_seekable_unicode_stream_reader`, or run them from the command line like this: `nltk/test/runtests.py nltk.test.unit.test_seekable_unicode_stream_reader`. I think we should remove [these](https://github.com/nltk/nltk/blob/0c6847d59815b2a832167085ed3280e520f07f12/nltk/tokenize/simple.py#L136) lines from individual files - tests are not meant to be run this way.

**Comment by stevenbird** [comment]
Thanks @kmike

**Comment by fievelk** [comment]
Thank you @kmike . I think you are right then about removing doctest imports and tests from individual files.

**Comment by fievelk** [comment]
@kmike @stevenbird : If doctest instructions are not needed in individual modules, I think that the [**Developers Guide**](https://github.com/nltk/nltk/wiki/Developers-Guide) should be consequently updated:

> - run doctest on the module if it is invoked on the command line

**Comment by stevenbird** [comment]
@fievelk, @kmike: I've removed that line from the developers guide.
