### ISSUE TITLE
Minor error in wordnet.py

### ISSUE THREAD

**Issue by peter-the-tea-drinker** [nltk/nltk#1045]
Hi, I noticed a small bug in wordnet.py, in the `all_synsets(pos)` method, line 1515 (note - it doesn't matter in the default case of iterating over all synsets, with no pos requested).

The error: `pos_tag` has been clobbered:

```
       # at the start of the method:
        if pos_tag == ADJ_SAT:
            pos_tag = ADJ
        ...
                    # later on:

                    if pos_tag == ADJ_SAT: # this is never true, because pos_tag is now ADJ
                        if synset._pos == pos_tag:
                            yield synset
```

Fix: use `pos` (which has not been clobbered)

```
       # this bit stays the same
        if pos_tag == ADJ_SAT:
            pos_tag = ADJ
        ...

                if pos in (ADJ_SAT, ADJ): # use `pos`, as it's the original
                        if synset._pos == pos: # test against `pos`
                            yield synset
```

It won't change anything in the default case (iterate over all synsets).

Testing the original, `wn.all_synsets(pos = wn.ADJ)` returns 18,156 synsets, and `wn.all_synsets(pos = wn.ADJ_SAT)` returns 0.

Fix applied: `wn.all_synsets(pos = wn.ADJ)` returns 7,463 synsets, and `wn.all_synsets(pos = wn.ADJ_SAT)` returns 10,693.

Not sure if it's worth fixing - it's possible someone is relying on `wn.all_synsets(pos = wn.ADJ)` returning all adjectives (both ADJ and ADJ_SAT).

**Comment by stevenbird** [comment]
Thanks @peter-the-tea-drinker.
