### ISSUE TITLE
Tokenizers

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#105]
NLTK's word tokenizers aren't as good as they could be (see issue 128 and
issue 376).  We need high performance tokenizer(s) for multiple languages.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=524</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2010-03-12T22:58:44.000Z:</strong></p>

<p>Issue 376 has been merged into this issue.</p>

**Comment by stevenbird** [comment]
We have an interface to the Stanford Tokenizer in `tokenize/stanford.py`.
