### ISSUE TITLE
Where did the NLTK pos_tag model come from?

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1063]
Following up from http://stackoverflow.com/questions/31386224/what-created-maxent-treebank-pos-tagger-english-pickle, there's a question on the origins of `nltk.pos_tag` (https://github.com/nltk/nltk/blob/develop/nltk/tag/__init__.py#L83). 

Possibly, the model is from https://github.com/arne-cl/nltk-maxent-pos-tagger. But there's no reply from https://github.com/arne-cl/nltk-maxent-pos-tagger/issues/1 and we're still not 100% sure how the tagger was trained.

Does anyone know where did the NLTK `pos_tag` come from?

**Comment by stevenbird** [comment]
I remember trying to find that out back when we published the book, and failed, sorry.

**Comment by stevenbird** [comment]
Looking at the [trained model](https://github.com/nltk/nltk_data/blob/gh-pages/packages/taggers/maxent_treebank_pos_tagger.zip) that is used by [pos_tag](https://github.com/nltk/nltk/blob/develop/nltk/tag/__init__.py#L84), I see that it is a [ClassifierBasedPOSTagger](https://github.com/nltk/nltk/blob/develop/nltk/tag/sequential.py#L693) trained on Penn Treebank, using [a variety of contextual features](https://github.com/nltk/nltk/blob/develop/nltk/tag/sequential.py#L726).

**Comment by stevenbird** [comment]
We have adopted a new default POS tagger (https://github.com/nltk/nltk/issues/1148), so this issue is no longer current.
