### ISSUE TITLE
CI errors for twitter module

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1068]
@ewan-klein, @fievelk – there's about a dozen errors showing up with the twitter module (and also in the corpus reader documentation) on the [CI server](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/testReport/). Would you please take a look?

**Comment by fievelk** [comment]
@lrnzcig some of these are the ones we found yesterday.

**Comment by stevenbird** [comment]
Looks ok now.
