### ISSUE TITLE
Language ID module

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#107]
It would be nice to have a language ID module in NLTK.   There are lots of
free implementations out there, most recycling the same couple of ideas:
http://www.let.rug.nl/~vannoord/TextCat/competitors.html

(including some in Python).

I am willing to donate character three-gram data for about 450 languages
assembled by the web crawler I've been running, here:

http://borel.slu.edu/crubadan/index.html

Table of cosine distances:
http://borel.slu.edu/crubadan/table.html

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=532</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2010-04-16T21:09:55.000Z:</strong></p>
<p>The language ID data has been added to NLTK's corpus collection
(nltk_data/corpora/langid), currently item #25 in NLTK's corpus list
(http://nltk.googlecode.com/svn/trunk/nltk_data/index.xml).  We need a corpus reader
that loads the data for an individual language/writing-system into a FreqDist.  We
might also want programmatic access to the code table (table.txt), which contains the
mapping between the internal identifiers and ISO 639-3 codes.
</p>

**Comment by davidsbatista** [comment]
Hi! I've been using NLTK for a while and I would like to contribute to the project. Is this task still necessary? If it is, I don't mind doing it. Are there any code guidelines specific for NLTK?
