### ISSUE TITLE
Why avoid 64bit Python?

### ISSUE THREAD

**Issue by BramVanroy** [nltk/nltk#1079]
I'd like to install NLTK for a new project, but [the installation page](http://www.nltk.org/install.html) asks you to avoid the 64 bit version. Why is that? I'd like to run Python in 64 but to maximize my performance and to allow the use of more RAM.

(Github might not be the best place to ask this question but I couldn't find any _contact_ information on the website)

**Comment by dimazest** [comment]
Could it be because of issues specific to Windows. I use 64 bit python on Linux and Mac and it forks fine.

What parts of NLTK do you plan to use?

**Comment by BramVanroy** [comment]
@dimazest Not sure yet. Considering my domain is syntax, I'll probably use the `treebank` function. But I haven't read into the documentation as much as I should, so I probably could use a lot more functions.

**Comment by stevenbird** [comment]
We advised against 64-bit windows because of no end of problems being reported on the NLTK mailing list, possibly due solely to problems with Python. Please let us know if you can get it to work, and what your configuration is.

**Comment by BramVanroy** [comment]
I'm sorry, I don't entirely get what you mean. Do you mean that a lot of people are reporting problems when using 64 bit Python? Or on 64 bit systems? Or on 64 bit CPUs?

**Comment by stevenbird** [comment]
@BramVanroy please see: https://groups.google.com/forum/#!searchin/nltk-users/64$20bit

**Comment by BramVanroy** [comment]
@stevenbird From what I've gathered in that thread, NLTK  ought to work in 64 bit Python. See [this post](https://groups.google.com/d/msg/nltk-users/HbyhWIXDud0/0ge6rwbCA8AJ). However, it doesn't seem to work perfectly well with some IDEs. Maybe some further investigation is possible to find out the issue? Unfortunately I'm not skilled enough for the task.

**Comment by KyleRaney** [comment]
Possible Solve. no errors so far. working with 64 bit
installed pip, numpy, wheel, pipenv, setuptools, virtualenv, virtualwrapper, NLTK, etc.

pip needs to be 19+ version and python 3+ version

system-> Advanced system settings -> Environment Variables -> EDIT path -> NEW paths

C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\Scripts
C:\Users\USERNAME\AppData\Local\Programs\Python\Python37
C:\Users\USERNAME\AppData\Roaming\Python\Python37\Scripts
C:\Users\USERNAME\AppData\Roaming\Python\Python37

of course these will differ for where ever you installed pip & python and your username
IMPORTANT you do Local and Roaming paths

Hope this helps! seems to work for me
