### ISSUE TITLE
malt.py

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1080]
@alvations, there's some minor issues with `malt.py`. Would you please take a look? It breaks with Python 2, and it has some non PEP-8 formatting (e.g. missing whitespace around operators)

```
  File "./malt.py", line 185
    dir=self.working_dir, mode='w', delete=False) as input_file, \
                                                               ^
SyntaxError: invalid syntax
```

**Comment by alvations** [comment]
@stevenbird I've fixed the problem for `taggedsent_to_conll()` reported on #1049 and PEP8 the `malt.py` and some minor doctest fixes with #1082. I am not having problems with python2. Could you post the error traceback from your machine?

**Comment by alvations** [comment]
I just realized that `with` statements in python2.6 doesn't do multiple inputs. 

```
alvas@ubi:~$ python2.6
Python 2.6.9 (default, Oct 22 2014, 19:56:52) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> with io.open('in.txt', 'r', encoding='utf8') as fin:
...     print fin.read()
... 
After Du died of suffocation, her boyfriend posted a heartbreaking message online: "Losing consciousness in my arms, your breath and heartbeat became weaker and weaker. Finally they pushed you out of the cold emergency room. I failed to protect you."

Li Na, 23, a migrant worker from a farming family in Jiangxi province, was looking forward to getting married in 2015.

>>> with io.open('in.txt', 'r', encoding='utf8') as fin, io.open('in.txt', 'r') as fout:
  File "<stdin>", line 1
    with io.open('in.txt', 'r', encoding='utf8') as fin, io.open('in.txt', 'r') as fout:
                                                       ^
SyntaxError: invalid syntax
>>> 
```

I've fix it so that it's py2.6.x compatible, https://github.com/alvations/nltk/commit/9df9371b55fd3d829e77886d23ef2fff02d2b457

**Comment by stevenbird** [comment]
Thanks @alvations. Please note that we use four-space indentation (recommended by PEP-8).

**Comment by alvations** [comment]
@stevenbird #1084 changed the tabs to four spaces. Sorry about the tabs, it was set on automatically through my IDE.

**Comment by fievelk** [comment]
@stevenbird @alvations 
After merging `develop` I am getting errors for **Python 3.2** and for all **no-deps** environments, relatively to `malt.py`, using `tox`. For example:

```
py32 inst-nodeps:
=============================================
ERROR: Failure: SyntaxError (invalid syntax (malt.py, line 72))
----------------------------------------------------------------------
  File "nltk/nltk/parse/malt.py", line 72
    malt_dependencies = set([u'log4j.jar', u'libsvm.jar', u'liblinear-1.8.jar'])
                                        ^
SyntaxError: invalid syntax
```

---

```
pypy inst-nodeps:
==============================================
ERROR: Failure: ImportError (No module named six)
----------------------------------------------------------------------
  File "nltk/nltk/parse/malt.py", line 12, in <module>
    from six import text_type
ImportError: No module named six
```
- Python 3.2 does not have support for unicode prefix, so it gives an invalid syntax error for `u'log4j.jar'` etc.
- I guess that `six` could be wrapped in a `try/catch` module (as we discussed regarding `twython` in [#1076](https://github.com/nltk/nltk/pull/1076))

**Comment by alvations** [comment]
@fievelk , I could do multiple `try-excepts` whenever `six.text_type()` is used but would that be alright? The code will look a little ugly but it should still work.

**Comment by fievelk** [comment]
@alvations : I couldn't examine your code in detail, but ideally I would directly wrap the first import `from six import text_type`, as it has often been done for `numpy`: 

```
try:
    import numpy
except ImportError:
    pass
```

(Or maybe with a more explanatory message instead of the simple `pass`)

**Comment by alvations** [comment]
@fievelk but that would cause the later code to break without the `six.text_type()` because in py2.x it would be `unicode(text)` and in py3.x it would be `byte(text)`. So lines like these https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py#L188 will end up looking like

```
try:
    input_file.write(text_type(line))
except:
    try:
        input_file.write(unicode(line))
    except:
        input_file.write(byte(line))
```

And for the import, would this be better or should I just pass on the `ImportError`:

```
try:
    from six import text_type
except:
    import warnings
    warnings.warn('The Malt Parser API in NLTK works better with the `six` library')
```

I'm not sure what to write for the warning message.

**Comment by kmike** [comment]
six should be installed automatically now because it is in install_requires, I think we shouldn't do try/except for six.

**Comment by fievelk** [comment]
@kmike `tox` tests are failing in no-deps environment because of six, though. Is there a different way to fix this?

**Comment by alvations** [comment]
@fievelk @kmike Martijn gave an ingenious solution the text_type =)

```
try:
    from six import text_type
except:
    try:
        text_type = unicode # Python 2
    except NameError:
        text_type = str # Python 3
```

But the `six` and `tox` issue will continue for other modules in NLTK. Should I modify the malt.py code and do a pull-request again? Or should the problem be solved with the `tox` side?

**Comment by fievelk** [comment]
Writing this in `malt.py` fixed the errors that I got using `tox`. But I would wait for a possible other option by @kmike , given his previous comment.

```
try:
    from six import text_type
except ImportError:
    pass
```

**Comment by kmike** [comment]
We are installing six in tox (it is in 'deps' section); I have no idea why isn't it working. It should be definitely solved as a part of our test running setup, not as a code change.

**Comment by fievelk** [comment]
@kmike Do you mean the 'deps' section in `tox.ini`? If so, I will also wait to fix `twython` imports, since they have the same problem (see [#1076](https://github.com/nltk/nltk/pull/1076)) and they are included in the deps section as well.

```
deps =
    numpy
    nose >= 1.2.1
    coverage
    text-unidecode
    twython
    six
```

**Comment by alvations** [comment]
@fievelk @kmike did the `tox` tests go through? Should I add try-except for the `six.text_type` import?

**Comment by kmike** [comment]
@alvations no, try/except for six.text_type doesn't sound good. 

six is not installed in nodeps environment because of 2 reasons:
1. we are not installing nltk using `pip install` in tox, so `install_requires` are not processed;
2. six is not in `deps` section of -nodeps environments.

I think we should add six to all -nodeps environments. There are ways to do it without duplicating the same lines again and again; see http://blog.ionelmc.ro/2015/04/14/tox-tricks-and-patterns/ and https://testrun.org/tox/latest/config.html#substitution-for-values-from-other-sections.

(1) is not clear to me - I don't understand why aren't dependencies from `install_requires` installed automatically by tox. It may be a tox bug.

**Comment by alvations** [comment]
#1076 is going ahead with the try-except.

I'm not sure how this works out but possibly `six` is more "natively" python as compared to `twpython` so I shouldn't wrap the import with try-except. I'll wait out for the `tox` issue to be resolved.

**Comment by alvations** [comment]
With the `six` issue resolved, now Malt API should be stable. Would that be an issue "closed"?

**Comment by stevenbird** [comment]
Thanks @alvations
