### ISSUE TITLE
Support for Roget Corpus

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#109]
Migrate the old Roget corpus reader to the new NLTK.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=537</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2010-04-16T20:39:11.000Z:</strong></p>
<p>http://code.google.com/p/nltk/source/browse/trunk/nltk-old/src/nltk/corpus/rogetreader.py
</p>

**Comment by alvations** [comment]
Updates on Roget Corpus at #1187
