### ISSUE TITLE
WittenBellProbDist doesn't support bins=None or bins=freqdist.B()

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#110]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>
2.0b8

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>

&gt;&gt;&gt; from nltk.probability import WittenBellProbDist, FreqDist
&gt;&gt;&gt; fd = FreqDist([&quot;This&quot;, &quot;is&quot;, &quot;This&quot;, &quot;Good&quot;])
&gt;&gt;&gt; WittenBellProbDist(fd)

or

&gt;&gt;&gt; WittenBellProbDist(fd,3)

Traceback (most recent call last):
  File &quot;&lt;pyshell#23&gt;&quot;, line 1, in &lt;module&gt;
    WittenBellProbDist(fd,3)
  File &quot;C:\Python26\lib\site-packages\nltk\probability.py&quot;, line 1208, in
**init**
    self._P0 = self._T / float(self._Z \* (self._N + self._T))
ZeroDivisionError: float division

<b>What is the expected output? What do you see instead?</b>

No errors, and the line:
&lt;WittenBellProbDist based on 3 samples&gt;

<b>Please use labels and text to provide additional information.</b>

I believe the problem is in the **init**:
  if bins == None:
      bins = freqdist.B()
...
  self._Z = bins - self._freqdist.B()

and then:
  if self._N==0: 
    self._P0 = 1.0 / self._Z
  else:
    self._P0 = self._T / float(self._Z \* (self._N + self._T))
so no matter what there is a divide by zero<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=538</p>

**Comment by DJLamar** [comment]
I think I understand the problem here. The code makes no attempt to recognize situations where smoothing is not necessary at all (indicated by bins == None or bins == freqdist.B(), i.e. all possible events have been observed), so the normalization constant comes out to be zero. The proper way to fix the distribution itself would probably be to change 

```
if self._N==0: 
    self._P0 = 1.0 / self._Z
else:
    self._P0 = self._T / float(self._Z * (self._N + self._T))
```

to

```
if self._N==0: 
    self._P0 = 1.0 / self._Z
elif bins is not None and bins > freqdist.B():
    self._P0 = self._T / float(self._Z * (self._N + self._T))
else:
    self._P0 = 0.0
```

and to alter the rest of the distribution so that other frequencies only get divided by self._N and not self._N + self._T. However, I can't really test this because I get a NotImplementedError whenever I actually try to use WittenBellProbDist with this change....

```
Traceback (most recent call last):
  File "ngram.py", line 35, in <module>
    ll += lm.entropy(pl)
  File "/usr/local/lib/python2.7/dist-packages/nltk/model/ngram.py", line 205, in entropy
    e += self.logprob(token, context)
  File "/usr/local/lib/python2.7/dist-packages/nltk/model/ngram.py", line 151, in logprob
    return -log(self.prob(word, context), 2)
  File "/usr/local/lib/python2.7/dist-packages/nltk/model/ngram.py", line 130, in prob
    return self._alpha(context) * self._backoff.prob(word, context[1:])
  File "/usr/local/lib/python2.7/dist-packages/nltk/model/ngram.py", line 133, in _alpha
    return self._beta(tokens) / self._backoff._beta(tokens[1:])
  File "/usr/local/lib/python2.7/dist-packages/nltk/model/ngram.py", line 137, in _beta
    return self[tokens].discount()
  File "/usr/local/lib/python2.7/dist-packages/nltk/probability.py", line 1210, in discount
    raise NotImplementedError()
NotImplementedError
```
