### ISSUE TITLE
Chinese pos tag issue

### ISSUE THREAD

**Issue by richzw** [nltk/nltk#1102]
hi,

I am newbie here, and I try to add POS to Chinese via nltk. However, the output I got seems not well.

```
nltk.tag.pos_tag(word_tokenize(u'客户 表示 自己 有 3 辆 宝马 车 ， 自己 非常 认可 宝马 的 品牌 也 非常 认可 经销店 的 服务'))

[(u'\u5ba2\u6237', 'NN'), (u'\u8868\u793a', '``'), (u'\u81ea\u5df1', ':'), (u'\u6709', ':'), (u'3', 'CD'), (u'\u8f86', 'CD'), (u'\u5b9d\u9a6c', 'CD'), (u'\u8f66', 'CD'), (u'\uff0c', 'CD'), (u'\u81ea\u5df1', 'CD'), (u'\u975e\u5e38', 'CD'), (u'\u8ba4\u53ef', 'CD'), (u'\u5b9d\u9a6c', 'CD'), (u'\u7684', 'CD'), (u'\u54c1\u724c', 'CD'), (u'\u4e5f', 'CD'), (u'\u975e\u5e38', 'CD'), (u'\u8ba4\u53ef', 'CD'), (u'\u7ecf\u9500\u5e97', 'CD'), (u'\u7684', 'CD'), (u'\u670d\u52a1', 'CD')]
```

Could someone help me to figure out the root cause of my codes?

**Comment by alvations** [comment]
The `nltk.pos_tag` is an English POS tagging model. It will not work on Chinese texts.

Currently, I think the only wrapper for Chinese POS tagging in NLTK is from the Stanford NLP:

Following the instructions here: https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software#stanford-tagger-ner-tokenizer-and-parser

Then 

```
>>> from nltk.tag import StanfordPOSTagger
>>> st = StanfordPOSTagger('chinese-distsim.tagger')
>>> st.tag(word_tokenize(u'客户 表示 自己 有 3 辆 宝马 车 ， 自己 非常 认可 宝马 的 品牌 也 非常 认可 经销店 的 服务'))
```

You can also take a look at 
- https://github.com/a33kuo/postagger_zh (a little outdated)
- Rakuten's tools (https://pypi.python.org/pypi/rakutenma)
- ZPar (http://people.sutd.edu.sg/~yue_zhang/doc/doc/joint_seg_tag.html)

**Comment by richzw** [comment]
@alvations, thanks for your answer.

Another question here. I found there was `sinica_treebank` in the `nltk.corpus` and also `tagged_words` were in this `sinica`. Could I use those `tagged_words` as one Chinese tagger?

**Comment by alvations** [comment]
With the Sinica corpus, you could train a bigram tagger, e.g. http://stackoverflow.com/questions/14732465/nltk-tagging-spanish-words-using-a-corpus but note that you should add a backoff unigram tagger to get better accuracy (Note that the code given in the SO example is not complete, it works but not to the best possible model).

**Comment by richzw** [comment]
@alvations Thanks for your help
