### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by stephenry** [nltk/nltk#1106]
Folks,

I am seeing the following error message when attempting to work through the eBook:

Python 3.5.0rc2 (v3.5.0rc2:cc15d736d860, Aug 25 2015, 04:45:41) [MSC v.1900 32 b
it (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > import nltk
> > > nltk.corpus.brown.words()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Users\shenry\AppData\Local\Programs\Python\Python35-32\lib\site-packa
> > > ges\nltk-3.0.4-py3.5.egg\nltk\util.py", line 664, in **repr**
> > >     for elt in self:
> > >   File "C:\Users\shenry\AppData\Local\Programs\Python\Python35-32\lib\site-packa
> > > ges\nltk-3.0.4-py3.5.egg\nltk\corpus\reader\util.py", line 394, in iterate_from
> > >     for tok in piece.iterate_from(max(0, start_tok-offset)):
> > >   File "C:\Users\shenry\AppData\Local\Programs\Python\Python35-32\lib\site-packa
> > > ges\nltk-3.0.4-py3.5.egg\nltk\corpus\reader\util.py", line 291, in iterate_from
> > >     tokens = self.read_block(self._stream)
> > >   File "C:\Users\shenry\AppData\Local\Programs\Python\Python35-32\lib\site-packa
> > > ges\nltk-3.0.4-py3.5.egg\nltk\corpus\reader\tagged.py", line 243, in read_block
> > >     for sent_str in self._sent_tokenizer.tokenize(para_str):
> > >   File "C:\Users\shenry\AppData\Local\Programs\Python\Python35-32\lib\site-packa
> > > ges\nltk-3.0.4-py3.5.egg\nltk\tokenize\regexp.py", line 126, in tokenize
> > >     self._check_regexp()
> > >   File "C:\Users\shenry\AppData\Local\Programs\Python\Python35-32\lib\site-packa
> > > ges\nltk-3.0.4-py3.5.egg\nltk\tokenize\regexp.py", line 121, in _check_regexp
> > >     self._regexp = compile_regexp_to_noncapturing(self._pattern, self._flags)
> > >   File "C:\Users\shenry\AppData\Local\Programs\Python\Python35-32\lib\site-packa
> > > ges\nltk-3.0.4-py3.5.egg\nltk\internals.py", line 55, in compile_regexp_to_nonca
> > > pturing
> > >     return sre_compile.compile(convert_regexp_to_noncapturing_parsed(sre_parse.p
> > > arse(pattern)), flags=flags)
> > >   File "C:\Users\shenry\AppData\Local\Programs\Python\Python35-32\lib\site-packa
> > > ges\nltk-3.0.4-py3.5.egg\nltk\internals.py", line 51, in convert_regexp_to_nonca
> > > pturing_parsed
> > >     parsed_pattern.pattern.groups = 1
> > > AttributeError: can't set attribute

**Comment by mind1m** [comment]
+1, updated to python3.5 and received this error (nltk 3.0.5)

**Comment by ruiEnca** [comment]
+1 I'm getting this error after update to Python 3.5 (NLTK 3.05)

**Comment by laura-burdick** [comment]
+1 Same

**Comment by redrush85** [comment]
+1, os x yosemite, python 3.5, nltk 3.0.5

**Comment by stevenbird** [comment]
I've added Python 3.5 testing to our continuous integration service at https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py35-jenkins,jdk=jdk8latestOnlineInstall/

**Comment by iemelyanov** [comment]
+1 Same

**Comment by stevenbird** [comment]
Well, NLTK passes the Python 3.5 CI server testing, which just means our tests are not comprehensive. Does anyone have time to diagnose this particular problem some more, and report back or submit a PR please?

**Comment by stevenbird** [comment]
I'd appreciate any feedback on my proposed solution in https://github.com/nltk/nltk/commit/7e43ac05c41d5ffcce9197952e1bf46831d08d90

**Comment by stevenbird** [comment]
This should be resolved now.
