### ISSUE TITLE
Reader for Prague Dependency treebanks

### ISSUE THREAD

**Issue by nschneid** [nltk/nltk#1109]
I think there would be substantial demand for a clean Python interface to the Prague treebanks, which are annotated with rich multilayer structures, notably the "tectogrammatical layer" with deep syntactic dependencies. E.g., [PCEDT 2.0](http://ufal.mff.cuni.cz/pcedt2.0/), which annotates the English WSJ corpus as well as its Czech translation. The annotations are stored in XML files which are difficult to understand without script support. As far as I know, all the [software](http://ufal.mff.cuni.cz/pcedt2.0/en/tools.html) for working with these treebanks is based on the command line or Perl.

I'm not sufficiently familiar with the annotation scheme to write code for this myself, but if a contributor can be found I'd be happy to test out and provide feedback on the user-facing API. @obo or @tuetschek might know of somebody who could contribute.

**Comment by stevenbird** [comment]
I agree, it would be great to have this. I'll ask around too.

**Comment by martinpopel** [comment]
I agree a Python interface and NLTK integration would be nice to have.

Note that with [Treex](https://github.com/ufal/treex) you can convert both *.treex.gz (PCEDT) and *.t.gz (PDT) files to YAML:

```
treex --language=cs Read::PDT from=pdt3.0/data/tamw/train-1/cmpr9410_001.t.gz schema_dir=pdt3.0/resources/ Write::YAML to=pdt.yaml

treex Read::Treex from=pcedt2.0/data/00/wsj_0001.treex.gz Write::YAML to=pcedt.yaml
```

Similarly, you can convert it to CONLL-X or [CONLL-U](http://universaldependencies.github.io/docs/format.html) and several other formats, but these cannot contain the tectogrammatical layer.

**Comment by tuetschek** [comment]
Hi,

I don't know if it will be of any use, but we kind of have Python access to
PDT treebanks -- it's experimental (i.e. I am the only one using it) and
it's pretty limited (can't read XML, YAML-serialized Treex files only), but
it works for me. It's here:

https://github.com/ufal/pytreex

I have never used NLTK and don't have the time now to port the code to work
with NLTK and try to parse the original PDT XML or Treex XML files, but I
will be happy to answer questions if anyone does it.

Best,
Ondrej
