### ISSUE TITLE
Add a method returning the content of a corpus as Text object

### ISSUE THREAD

**Issue by stieglma** [nltk/nltk#1117]
During our studies we found it quite useful to have a method returning the words of a corpus wrapped in a text object, such that the concordance view and many other methods can be used.
As suggested from @stevenbird in the pull request #1112 I would propose to add this method to the CorpusReader class, such that it will be available for all corpora.

Here is the code we used in our corpus reader before:

``` python
def text(self, fileids=None):
    """
    :param fileids: A list specifying the fileids that should be used.
    :return: the given file(s) concatenated and wrapped in a Text object of NLTK
    :rtype: Text
    """
    return Text(self.words(fileids))
```

**Comment by stevenbird** [comment]
Is there a strong reason to prefer `some_corpus.text(fileids)` over `Text(some_corpus.words(fileids))`? The proposal is shorter, but it presumes more knowledge on the part of the reader. It also provides a second way to do the same thing, and greater variability in code for no apparent benefit.

**Comment by stieglma** [comment]
You are right, the Text object can also easily be used without the method of the reader (which has to be done anyway if you want something else as Text than the whole corpus (or the via fileids selected parts). The only benefit I see, is that you don't have to import nltk.Text manually, as it will be done by the corpus reader, but that's not really worth it.
The reason why we had this method, was just to provide a faster way to get to the (default) Text object for our corpus, which will be only the case if you know that this method exists. As hardly anybody knows about it, integrating the method doesn't make as much sense as we thought before.

**Comment by stevenbird** [comment]
Thanks for your feedback. I think you're right, so let's not do anything at this stage.
