### ISSUE TITLE
audit NLTK functions with boolean flag parameters

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#112]
There are a number of functions in NLTK that take boolean parameters, e.g. 
- CorpusReader.abspaths(..., include_encoding=False)
- TaggedCorpusReader.tagged_words(..., simplify_tags=False)
- ClusterI.cluster(..., assign_clusters=False)

Guido has stated that one of the Python design principles is to avoid such
function definitions:

http://mail.python.org/pipermail/python-dev/2005-August/055907.html

We should audit existing functions in NLTK that violate this principle, and
decide where it's worth deprecating the flags and adding new method names.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=544</p><hr/><h2>earlier comments</h2>

<p><strong>StevenBird1 said, at 2011-04-10T07:15:48.000Z:</strong></p>

<p>Postponing this to 3.0.
</p>

**Comment by stevenbird** [comment]
Closing, as we don't have capacity to take this on.
