### ISSUE TITLE
JAVA command failed

### ISSUE THREAD

**Issue by bjut-hz** [nltk/nltk#1125]
It raise an OSError when I called Stanford NLP by NLTK stanford interface. 
'''
OSError: Java command failed : ['C:\Program Files (x86)\Java\jdk1.8.0_60\bin\java.exe', u'-mx1000m', '-cp', u'.\stanford-parser.jar;.\stanford-parser-3.5.2-models.jar', u'edu.stanford.nlp.parser.lexparser.LexicalizedParser', u'-model', 'englishPCFG.ser.gz', u'-sentences', u'newline', u'-outputFormat', u'penn', u'-encoding', u'utf8', 'c:\users\hz\appdata\local\temp\tmpkxvhkz']
'''

**Comment by bjut-hz** [comment]
I tried to edit the java_options as follows:
java_options='-Xmx1024m'

It still raise an OSError:
::
Loading parser from serialized file englishPCFG.ser.gz ...  done [0.6 sec].
Parsing file: c:\users\hz\appdata\local\temp\tmpmjgtxb
Parsing [sent. 1 len. 201]: The invention provides an OLED device with improved light out-coupling , which can be manufactured easy and reliable at low costs , which comprises an electroluminescent layer stack -LRB- 2 , 3 , 4 -RRB- on top of a substrate -LRB- 1 -RRB- , where the electroluminescent layer stack -LRB- 2 , 3 , 4 -RRB- comprises an organic light-emitting layer stack -LRB- 3 -RRB- with one or more organic layers sandwiched between a first electrode -LRB- 2 -RRB- facing towards the substrate -LRB- 1 -RRB- and a 10 second electrode -LRB- 4 -RRB- , where the second electrode -LRB- 4 -RRB- comprises a layer stack of at least a transparent conductive protection layer -LRB- 41 -RRB- on top of the organic light-emitting layer stack -LRB- 3 -RRB- , a transparent organic conductive buckling layer -LRB- 42 -RRB- on top of the protection layer -LRB- 41 -RRB- having a glass transition temperature lower than the lowest glass transition temperature of the organic layers within the organic light-emitting layer stack -LRB- 3 -RRB- and a stress inducing layer 15 -LRB- 43 -RRB- on top of the buckling layer -LRB- 42 -RRB- to introduce stress to the buckling layer -LRB- 42 -RRB- .

---

**\*  WARNING!! OUT OF MEMORY! THERE WAS NOT ENOUGH  ***
**\*  MEMORY TO RUN ALL PARSERS.  EITHER GIVE THE    ***
**\*  JVM MORE MEMORY, SET THE MAXIMUM SENTENCE      ***
**\*  LENGTH WITH -maxLength, OR PERHAPS YOU ARE     ***
**\*  HAPPY TO HAVE THE PARSER FALL BACK TO USING    ***
**\*  A SIMPLER PARSER FOR VERY LONG SENTENCES.      ***

---

Sentence has no parse using PCFG grammar (or no PCFG fallback).  Skipping...
Exception in thread "main" edu.stanford.nlp.parser.common.NoSuchParseException
    at edu.stanford.nlp.parser.lexparser.LexicalizedParserQuery.getBestParse(LexicalizedParserQuery.java:398)
    at edu.stanford.nlp.parser.lexparser.LexicalizedParserQuery.getBestParse(LexicalizedParserQuery.java:370)
    at edu.stanford.nlp.parser.lexparser.ParseFiles.processResults(ParseFiles.java:271)
    at edu.stanford.nlp.parser.lexparser.ParseFiles.parseFiles(ParseFiles.java:215)
    at edu.stanford.nlp.parser.lexparser.ParseFiles.parseFiles(ParseFiles.java:74)
    at edu.stanford.nlp.parser.lexparser.LexicalizedParser.main(LexicalizedParser.java:1521)

Traceback (most recent call last):
  File "L:/python/SAO/SAO.py", line 314, in <module>
    sao_system.run('testdata.xls')
  File "L:/python/SAO/SAO.py", line 223, in run
    paser_tree = sao_parser.getParserTree( sentence )
  File "L:/python/SAO/SAO.py", line 87, in getParserTree
    sentences_trees = self.sentsParser( sentence )
  File "L:/python/SAO/SAO.py", line 84, in sentsParser
    return stanford_parser.raw_parse_sents( self.sentsTokenize( sentences ) )
  File "C:\Python27\lib\site-packages\nltk-3.0.4-py2.7.egg\nltk\parse\stanford.py", line 170, in raw_parse_sents
    return self._parse_trees_output(self._execute(cmd, '\n'.join(sentences), verbose))
  File "C:\Python27\lib\site-packages\nltk-3.0.4-py2.7.egg\nltk\parse\stanford.py", line 230, in _execute
    stdout=PIPE, stderr=PIPE)
  File "C:\Python27\lib\site-packages\nltk-3.0.4-py2.7.egg\nltk\internals.py", line 162, in java
    raise OSError('Java command failed : ' + str(cmd))
OSError: Java command failed : ['C:\Program Files (x86)\Java\jdk1.8.0_60\bin\java.exe', u'-Xmx1024m', '-cp', u'.\stanford-parser.jar;.\stanford-parser-3.5.2-models.jar', u'edu.stanford.nlp.parser.lexparser.LexicalizedParser', u'-model', 'englishPCFG.ser.gz', u'-sentences', u'newline', u'-outputFormat', u'penn', u'-encoding', u'utf8', 'c:\users\hz\appdata\local\temp\tmpmjgtxb']

Process finished with exit code 1

**Comment by hoontw** [comment]
The warning message is a big clue. Looks like the sentence being parsed is too long. Personally, I think anyone who writes an English sentence that is 201 words long should be shot, but that's just me.

Do you absolutely have to parse such long sentences? If not, you can filter out long sentences as a preprocessing step, or follow the recommendations in the warning to set the maximum sentence length for Stanford NLP.

**Comment by bjut-hz** [comment]
Thanks for your comment. Thanks to uncertainty of length of sentence to be parsed. I just want to change the size of JVM memory by the command: java -Xmx1024m -Xms1024m -Xmn256m -Xss16m. But it dose not seem to work.

**Comment by hoontw** [comment]
Have you tried running Stanford NLP directly without using nltk? That is, run `C:\Program Files (x86)\Java\jdk1.8.0_60\bin\java.exe -Xmx1024m -cp .\stanford-parser.jar .\stanford-parser-3.5.2-models.jar`. Does it give the same errors? If yes, the parsed sentence is too long and your only options are the recommendations in the warning message.

**Comment by rmalouf** [comment]
I don't think you'll be able to get the stanford parser to deal with sentences that long no matter how much memory you give it.  Depending on your application, though, you might by dividing it into, say, 50 word fragments and parsing them individually.  At any rate, I'm pretty sure this isn't an issue with NLTK.

**Comment by bjut-hz** [comment]
Thanks for you all.

**Comment by manning** [comment]
@rmalouf: Actually, if you give the parser enough memory and time, the Stanford PCFG parser **will** parse sentences that long or longer. I once proved this to someone by parsing a 675 word sentence from a regulatory manual. But it took about 70 gigs of RAM and a few hours ... so not recommended. If you want to parse such sentences, you should use a greedy transition-based parser. I'm not sure whether they're supported in NLTK, but either the shift-reduce constituency parser or the neural network dependency parser provided with the Stanford Parser would be a much better choice.
