### ISSUE TITLE
FreqDist Error

### ISSUE THREAD

**Issue by mindriot78** [nltk/nltk#1128]
Hi, 
total newbie so bear with me :) Despite starting my session with the instruction 'from nltk.book import *', when I try to use the FreqDist function, I keep getting NameError: name 'FreqDist' is not defined. Any thoughts? I'm using version 2.7.6
Thanks a lot!

**Comment by hoontw** [comment]
FreqDist is from a different module. Try using `from nltk.probability import FreqDist`.

**Comment by stevenbird** [comment]
NB https://github.com/nltk/nltk_book/issues/163

**Comment by mindriot78** [comment]
Many thanks to you all.
