### ISSUE TITLE
Adopt abstract base class syntax

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1130]
NLTK has plenty of abstract base classes. Now that Python has support for these, we need to audit the codebase and adopt this syntax.

cf https://docs.python.org/3.0/whatsnew/2.6.html#pep-3119

**Comment by stevenbird** [comment]
Thanks @mrecachinas and @kmike for https://github.com/nltk/nltk/pull/1223. It looks like we have a model that can be applied across the toolkit now.

**Comment by souravsingh** [comment]
@stevenbird Is the issue fixed?

**Comment by gmotzespina** [comment]
@stevenbird it seems that this issue has been fixed, it might be useful to close it.

**Comment by stevenbird** [comment]
Thanks @souravsingh, @gmotzespina!
