### ISSUE TITLE
find the head of a noun phrase for English language

### ISSUE THREAD

**Issue by aliabbasjp** [nltk/nltk#1137]
nltk should have a NP and its head finder, discussed in detail here

http://stackoverflow.com/questions/32654704/finding-head-of-a-noun-phrase-in-nltk-and-stanford-parse-according-to-the-rules

**Comment by stevenbird** [comment]
That's too language- and grammar- specific. Maybe you could switch to using a dependency parser.

**Comment by aliabbasjp** [comment]
At least for English language it should be implemented as its most commonly used language.
