### ISSUE TITLE
Pickled Punkt models need language specific variables

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#114]
Issue #479 highlights the need for language-specific variables in our 
Punkt implementation (e.g. Greek's use of ';' in place of English '?').

Currently the Punkt models in nltk_data/tokenizers/punkt.zip are derived 
using the same default (English-based) variables.

The punkt module needs to incorporate non-default variables as necessary, 
and the pickles need to be reproduced.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=552</p><hr/><h2>earlier comments</h2>

<p><strong>jan.strunk said, at 2010-05-11T14:40:42.000Z:</strong></p>

<p>That's certainly right. Since we only concentrated on the more ambiguous period . in
our original Punkt research and prototype implementation and not on additional
punctuation marks, I do not have any ready-made punctuation sets for the different
languages. I would, however, be happy to reproduce the pickles if knowledgeable
people would provide such localized versions for different languages. I could also
provide such localized variables for German.</p>

**Comment by petr-tik** [comment]
@alexrudnick Have punctuation models been updated yet? If so, can you please close this issue? 

Thanks
