### ISSUE TITLE
krippendorff alpha with MASI distance

### ISSUE THREAD

**Issue by vaskonov** [nltk/nltk#1144]
Hello,

There is a problem with calculating krippendorff alpha with MASI distance.

```
import nltk
from nltk.metrics import masi_distance
data = [['1', 5723, frozenset([2,3])],['2', 5723, frozenset([2,3])]]
task = nltk.metrics.agreement.AnnotationTask(data=data, distance=masi_distance)
print task.alpha()
```

The above fails with error message

```
ret = 1.0 - (self.Do_alpha() / De)
ZeroDivisionError: float division by zero
```

**Comment by jnothman** [comment]
It's not particular to MASI. Try:

nltk.metrics.agreement.AnnotationTask([['1', 5723, 0],['2', 5723, 0]]).alpha()

for the same error.
