### ISSUE TITLE
compat vs six

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1164]
Now that we've added six to the NLTK distribution, some methods in compat, like `python_2_unicode_compatible` should be imported from six instead.

**Comment by kmike** [comment]
`compat.python_2_unicode_compatible` is different from `six.python_2_unicode_compatible`; in six it always uses utf8 and so doesn't work correctly in non-utf8 consoles (Windows?).

**Comment by stevenbird** [comment]
Thanks @kmike – I saw that it was different and wondered if that was just because NLTK's version was a stale copy.
