### ISSUE TITLE
sentiment analysis using nltk

### ISSUE THREAD

**Issue by anupamme** [nltk/nltk#1177]
How can I do sentiment analysis using nltk?

Does nltk 3.1 has inbuilt sentiment analyzer?

If not, I heard it now supports stanford corenlp integration, if this is true then how can it be achieved?

I think it is more like a stackoverflow question but since 3.1 is new I thought this might be better place.

**Comment by ewan-klein** [comment]
The documentation for the new sentiment analysis functionality is still a bit rudimentary, but have a look at:
- New corpora in http://www.nltk.org/howto/corpus.html#categorized-corpora
- Brief examples in http://www.nltk.org/howto/sentiment.html
- Longer examples in http://www.nltk.org/api/nltk.sentiment.html#module-nltk.sentiment.util

**Comment by ewan-klein** [comment]
@anupamme I suggest that if you want to pursue this question further, it would be best to do it on the [NLTK user mailing list](https://groups.google.com/forum/#!forum/nltk-users).
