### ISSUE TITLE
Problems installing nltk

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#118]
What version of NLTK are you using?  (See nltk.2.0b8__version__).  Please only
<b>submit bug reports for the current version.</b>

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
sudo port install python26 (here there are no problems) and then

sudo port install py26-nltk
Password:
Error: Unable to open port: couldn't change working directory to
&quot;/opt/local/var/macports/sources/rsync.macports.org/release/ports/python/py26-nltk&quot;:
no such file or directory
Before reporting a bug, first run the command again with the -d flag to get
complete output.

<b>What is the expected output? What do you see instead?</b>

<b>Please use labels and text to provide additional information.</b>

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=561</p><hr/><h2>earlier comments</h2>
<p><strong>ryandesign.com said, at 2010-07-26T22:45:12.000Z:</strong></p>

<p>Try selfupdating and cleaning the port first:

sudo port selfupdate
sudo port clean py26-nltk

Then try again.</p>

**Comment by stevenbird** [comment]
Outdated issue.
