### ISSUE TITLE
Is generate() coming back? 

### ISSUE THREAD

**Issue by JonathanReeve** [nltk/nltk#1180]
Would really love to see this function back again. The book says it will be reinstated in a later version, but when?

**Comment by alvations** [comment]
+1 .  Given the recent RNN generation from @karpathy (https://github.com/karpathy/char-rnn), it might be very easy to create a `generate()` algorithm but support of any neural net implementation is all very unstable, API changes almost every 2-3 weeks =(

**Comment by JonathanReeve** [comment]
Is there a reason why this function was removed? Just curious.
