### ISSUE TITLE
Getting a wrong synsets

### ISSUE THREAD

**Issue by mhjabreel** [nltk/nltk#1184]
Hi, all,

I have tried to calculate the semantic similarity between "flower" and "stamina", but I have got a wrong result. after checking the reason I have relaised  that the wrong result because the synsets of "stamina" that I have obtained using NLTK are "Stamina" and "Stamen", but when I have searched about this in wordnet I have found only one synset which is "Stamina".

could you please fix this issue ?

Thanks,

Mohammed

**Comment by alvations** [comment]
Thanks @mhjabreel , yes it seems like an error with how the synset was retrieved at https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L1423

NLTK API is fetching a wrong synset for the lemma `stamina`:

``` python
>>> from nltk.corpus import wordnet as wn
>>> wn.synsets('stamen')
[Synset('stamen.n.01')]
>>> wn.synsets('stamina')
[Synset('stamina.n.01'), Synset('stamen.n.01')]
>>> wn.synsets('stamina')[1].definition()
u'the male reproductive organ of a flower'
```

On Princeton's search interface, it fetches only `Synset('stamina.n.01')`, see [here](http://wordnetweb.princeton.edu/perl/webwn?s=stamina&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=)

If we look at the index from the official `lemma_pos_offset_map`, https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L1420, it only returns on synset:

``` python
>>> index = wn._lemma_pos_offset_map
>>> index['stamina']
{u'n': [5032918]}
```

The other synset was introduced later at `get_synset(p, offset)`, https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L1423

**Comment by stevenbird** [comment]
Thanks for the report @mhjabreel and diagnosis @alvations

**Comment by mhjabreel** [comment]
Tanks for your information @alvations, I have made some trace for this and I notice that this tow sysnsests come from the exception file "nouns.exc", as I have checked the WordNet::QueryData code also i guess there is a condition to check the exception files or not when they trying to get the forms.

sub _forms#
{
    # Assume that word is canonicalized, pos is number
    my ($self, $word, $pos) = @_;

```
my $lword = lower($word);
warn "(_forms) WORD=$word POS=$pos\n" if ($self->{verbose});
# if word is in morph exclusion table, return that entry
if ($self->{noload}) {
    # for noload, only load exclusions when needed; we do cache these
    # though because the list is short (40k) and used on repeated recursive
    # calls.
    if (! exists $self->{morph_exc}) {
        $self->loadExclusions();
    }
}
if (defined ($self->{morph_exc}->[$pos]->{$lword})) {
    return ($word, @{$self->{morph_exc}->[$pos]->{$lword}});
}
```

I have modified the function of get sysnsets in NLTK as the following: 

```
def synsets(self, lemma, pos=None, lang='eng', check_exceptions=False):
    """Load all synsets with a given lemma and part of speech tag.
    If no pos is specified, all synsets for all parts of speech
    will be loaded. 
    If lang is specified, all the synsets associated with the lemma name
    of that language will be returned.
    """
    lemma = lemma.lower()

    if lang == 'eng':
        get_synset = self._synset_from_pos_and_offset
        index = self._lemma_pos_offset_map
        if pos is None:
            pos = POS_LIST
        return [get_synset(p, offset)
                for p in pos
                for form in self._morphy(lemma, p, check_exceptions)
                for offset in index[form].get(p, [])]

    else:
        self._load_lang_data(lang)
        synset_list = []
        for l in self._lang_data[lang][1][lemma]:
            if pos is not None and l[-1] != pos:
                continue
            synset_list.append(self.of2ss(l))
        return synset_list

def _morphy(self, form, pos, check_exceptions=False):
    # from jordanbg:
    # Given an original string x
    # 1. Apply rules once to the input to get y1, y2, y3, etc.
    # 2. Return all that are in the database
    # 3. If there are no matches, keep applying rules until you either
    #    find a match or you can't go any further

    exceptions = self._exception_map[pos]
    substitutions = self.MORPHOLOGICAL_SUBSTITUTIONS[pos]

    def apply_rules(forms):
        return [form[:-len(old)] + new
                for form in forms
                for old, new in substitutions
                if form.endswith(old)]

    def filter_forms(forms):
        result = []
        seen = set()
        for form in forms:
            if form in self._lemma_pos_offset_map:
                if pos in self._lemma_pos_offset_map[form]:
                    if form not in seen:
                        result.append(form)
                        seen.add(form)
        return result

    # 0. Check the exception lists
    if check_exceptions:
        if form in exceptions:
            return filter_forms([form] + exceptions[form])

    # 1. Apply rules once to the input to get y1, y2, y3, etc.
    forms = apply_rules([form])

    # 2. Return all that are in the database (and check the original too)
    results = filter_forms([form] + forms)
    if results:
        return results

    # 3. If there are no matches, keep applying rules until we find a match
    while forms:
        forms = apply_rules(forms)
        results = filter_forms(forms)
        if results:
            return results

    # Return an empty list if we can't find anything
    return []
```

now it is getting only stamina

**Comment by stevenbird** [comment]
@mhjabreel sorry for the delay in dealing with this. Thanks for your proposal, which I adopted. However, note that I made `check_exceptions` default to `True`, since this is the current behaviour. There needs to be a bigger case made for changing behaviour, e.g. demonstration that other words are not handled incorrectly as a consequence of turning off this exception checking.

**Comment by mhjabreel** [comment]
@stevenbird Thanks
