### ISSUE TITLE
Open Roget's Thesaurus

### ISSUE THREAD

**Issue by nschneid** [nltk/nltk#1187]
Might be nice to have a way to use this resource in NLTK: https://sites.google.com/site/openrogets/

**Comment by stevenbird** [comment]
I see that @prpole has worked on a Python interface here: https://github.com/prpole/roget-tools

**Comment by prpole** [comment]
Indeed---I didn't know about Open Roget's, but I'm pursuing similar semantic-relatedness measurements using Python. This also does the basic lookup functions, of course. Hoping to clean it up a bit soon.
