### ISSUE TITLE
nltk.tokenize functions `can't set attribute` error

### ISSUE THREAD

**Issue by meticulo3366** [nltk/nltk#1188]
tokenizer fails on all methods and functions and produces `can't set attribute` error

See this to reproduce the following error
[http://www.nltk.org/api/nltk.tokenize.html#module-nltk.tokenize.regexp](http://www.nltk.org/api/nltk.tokenize.html#module-nltk.tokenize.regexp)

`from nltk.tokenize import RegexpTokenizer`
`s = "Good muffins cost $3.88\nin New York.  Please buy me\ntwo of them.\n\nThanks."`
`tokenizer = RegexpTokenizer('\w+|\$[\d\.]+|\S+')`
`tokenizer.tokenize(s)`

> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/regexp.py", line 126, in tokenize
>    self._check_regexp()
>  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/regexp.py", line 121, in _check_regexp
>    self._regexp = compile_regexp_to_noncapturing(self._pattern, self._flags)
>  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/internals.py", line 55, in compile_regexp_to_noncapturing
>    return sre_compile.compile(convert_regexp_to_noncapturing_parsed(sre_parse.parse(pattern)), flags=flags)
>  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/internals.py", line 51, in convert_regexp_to_noncapturing_parsed
>    parsed_pattern.pattern.groups = 1
> **AttributeError: can't set attribute**
## More Thorough Example of the Problem

> from nltk.tokenize import regexp_tokenize, wordpunct_tokenize, blankline_tokenize
> 
> regexp_tokenize(s, pattern='\w+|\$[\d.]+|\S+')
> wordpunct_tokenize(s)
> blankline_tokenize(s)

all produce the same error

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/regexp.py", line 203, in regexp_tokenize
    return tokenizer.tokenize(text)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/regexp.py", line 126, in tokenize
    self._check_regexp()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/regexp.py", line 121, in _check_regexp
    self._regexp = compile_regexp_to_noncapturing(self._pattern, self._flags)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/internals.py", line 55, in compile_regexp_to_noncapturing
    return sre_compile.compile(convert_regexp_to_noncapturing_parsed(sre_parse.parse(pattern)), flags=flags)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/internals.py", line 51, in convert_regexp_to_noncapturing_parsed
    parsed_pattern.pattern.groups = 1
AttributeError: can't set attribute**

**Comment by stevenbird** [comment]
This was fixed in NLTK 3.1. Please upgrade.

**Comment by meticulo3366** [comment]
my requirements document says otherwise...

nltk==3.1
PyMySQL==0.6.6
gspread==0.2.5
pytest==2.7.2
pytest-cov==2.0.0
oauth2client==1.4.12
pyOpenSSL==0.15.1
jellyfish==0.5.1
tldextract==1.6
celery==3.1.18
Beaker==1.7.0
