### ISSUE TITLE
OS X: interactive downloader handles "natural" scrolling option backwards

### ISSUE THREAD

**Issue by alexisdimi** [nltk/nltk#1201]
On OS X, there is a system-wide setting (System Preferences > Trackpad > Scroll and Zoom > Scroll direction: natural) that controls the way scrolling works. "Natural" (the default, I believe) is pinch-like: when the pointer moves down, the text "scrolls up", i.e., the viewport moves toward the start of the content. When "natural" scrolling is disabled, text moves in the opposite direction (in the more familiar Windows and Linux manner).

The nltk downloader has somehow gotten it backwards: With either setting of this system option, lists will scroll in the opposite direction of all other applications.

Environment: OS X Mountain Lion, NLTK 3.0.2, Python 3.4.3 from Anaconda 2.2.0 (x86_64).

**Comment by alvations** [comment]
This issue is unresolved on a OSX with NLTK v3.2.5, Python2/3 installed with pip.
