### ISSUE TITLE
transition based dependency parsers

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#121]
I have code for (state-of-the-art) transition-based dependency parsers which I would love to share with the nltk community.  It is currently licensed as GPL, but I have no problem of changing the license to Apache for the purpose of inclusion in nltk.  Would be nice if you retain my name on the source files.

It needs some work, especially in terms of documentation and fitting it with the nltk corpus readers, before it meets the nltk standards.  I would happily answer any questions regarding the code, but will not have time to do these modifications myself.  

Another potential issue is the use of a binary (cython) extension.  The code includes a .c file that needs to be compiled per-platform in order to work.  Providing a pure-python alternative is possilble, but will be much much slower.

code is available at: 
http://www.cs.bgu.ac.il/~yoavg/software/transitionparser/

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=580</p>

**Comment by no-identd** [comment]
@alexrudnick:

Did you ever actually relicense this?

**Comment by alexrudnick** [comment]
@no-identd  Ahh, this was a migrated issue -- I ran the script that moved all the issues over from Google Code. So I didn't write that text!

It must have been Yoav Goldberg ( @yoavg ) who wrote it! We could ask him if he's still interested!
