### ISSUE TITLE
Is there a built-in TokenMerger?

### ISSUE THREAD

**Issue by jdejoode** [nltk/nltk#1217]
I am using `from ntlk import word_tokenize`. If I'm correct this uses the treebank tokenizer. This results in a lists of tokens. Is there a built-in tokenmerger for these tokens, e.g. if I want to go from a list of tokens to the original text (possible after some list operations), is that possible?

For a comparable idea, cf. https://github.com/cheshire3/cheshire3/blob/develop/cheshire3/tokenMerger.py

**Comment by nschneid** [comment]
Can you give a simple example of the desired behavior? (Would it allow for modification of tokens in the list?) It's not immediately clear to me what the linked code does.

**Comment by jnothman** [comment]
Untokenising like this isn't something you should plan to do in the first
instance. Instead, you need to maintain the tokenisation as standoff
annotations.

**Comment by stevenbird** [comment]
NB #1190

**Comment by jdejoode** [comment]
Thanks for getting back to me. In terms of desired behavior, I was thinking something along the lines of the following pseudocode:

```
from nltk import word_tokenize
tokenized = word_tokenize('This is a simple sentence. Just a sample, a basic one.')
tokenized
['This',
 'is',
 'a',
 'simple',
 'sentence',
 '.',
 'Just',
 'a',
 'sample',
 ',',
 'a',
 'basic',
 'one',
 '.']
 # then do some changes to the list, for instance, replace commas with semi-colons
 from nltk import token_merge
 token_merge(tokenized)
 'This is a simple sentence. Just a sample; a basic one.'
```

So essentially the goal of the tokenmerger would be to track where the spaces are so that tokens can easily be merged again (if the list length is identical) after making changes. This is useful when doing classification tasks. Maybe it would be easier to have a tokenizer that simply also adds list items for spaces? But that would not really work as a tokenizer, then, because easy operations as word counts would have the spaces in there unnecessarily.

Some background: I am classifying `'`'s as single quotation marks or apostrophes. I would like to replace the single quotation marks with double ones and still result with the same text.

**Comment by nschneid** [comment]
If the tokenizer returned offsets into the original string, then for each
position between consecutive tokens you could check whether the original
string contains a space. Would that be sufficient?

**Comment by jnothman** [comment]
(FWIW, I have written such code before where the original untokenised text was not available, for PTB-style quotes:

``` python

PRECEDING_SPACE = re.compile(r" (?=[,\.!?'#:]|'s|'d|'m|'ll|'re|'ve|n't)", re.I)
def detokenize(raw):
    raw = raw.replace("s ' ", "s\0' ")
    raw = raw.replace(' ' + unichr(25) + ' ', "\0'\0")   # Odd fix required here.
    if raw.endswith('``'): raw = raw[0:-2] + '"\0'       # Left immediately followed by a token
    raw = raw.replace('`` ', '"\0').replace("`", "'\0")  # Left
    raw = raw.replace(" ''", '\0"') # Right
    raw = raw.replace(" -- ", " " + unichr(8212) + " ")
    raw = PRECEDING_SPACE.sub('\0', raw).replace('$ ', '$\0')
    return raw
```

)

**Comment by nschneid** [comment]
So there are two possible strategies:
1. Restore whitespace from a pretokenized string. I think this can be done easily if the tokenizer provides offsets (#1190). Not sure if it deserves a special function.
2. Define rules for where spaces should go based on the orthographic conventions of the language (@jnothman's code for English). Useful, for example, if the English tokenized sequence is being generated automatically. This is the inverse of the tokenization problem, sometimes called "detokenizing" or "untokenizing". If this is not already in NLTK, it might be worth having. If anyone wants to add this I'd suggest searching for various existing implementations to see how they work.

**Comment by alvations** [comment]
@nschneid @jnothman Stanford NLP has [one](http://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/process/PTBTokenizer.html) and Moses tokenizer has [several too](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/detokenizer.perl).

A quick hack is to add `-untok` parameter to NLTK's  Stanford tokenizer API at https://github.com/nltk/nltk/blob/develop/nltk/tokenize/stanford.py#L61

**Comment by jdejoode** [comment]
@nschneid Yes, it would work with offsets. It might be a bit cumbersome, but useful for texts that do not fit in memory.

For texts that do fit in memory, I found the following. I guess this would work with a RegexTokenizer?:

```
import re
sample = "This is a text, with some punctuation. I hope this works. If so: 'yes, yes!'"
split_sample = re.split('(\W)', sample)
print split_sample

['This',
 ' ',
 'is',
 ' ',
 'a',
 ' ',
 'text',
 ',',
 '',
 ' ',
 'with',
 ' ',
 'some',
 ' ',
 'punctuation',
 '.',
 '',
 ' ',
 'I',
 ' ',
 'hope',
 ' ',
 'this',
 ' ',
 'works',
 '.',
 '',
 ' ',
 'If',
 ' ',
 'so',
 ':',
 '',
 ' ',
 '',
 "'",
 'yes',
 ',',
 '',
 ' ',
 'yes',
 '!',
 '',
 "'",
 '']
```

This does add `''` empty strings somehow. Not sure why.

Detokenizing is then as easy as:

```
''.join(split_sample)
"This is a text, with some punctuation. I hope this works. If so: 'yes, yes!'"
```

**Comment by jdejoode** [comment]
@jnothman What is the purpose of the snippet you posted?
