### ISSUE TITLE
Translation metrics in Python 2.7

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1218]
The [CI Server](https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py27-jenkins,jdk=jdk8latestOnlineInstall/lastCompletedBuild/testReport/) reports test failures for  `nltk.translate.ribes_score.kendall_tau` and `nltk.translate.ribes_score.spearman_rho`.

**Comment by stevenbird** [comment]
@alvations – would you mind taking a look please?

**Comment by alvations** [comment]
@stevenbird sorry about it, I miss the `from __future__ import division`.

**Comment by stevenbird** [comment]
Thanks @alvations
