### ISSUE TITLE
nltk.corpus.stopwords should return unicode strings

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#122]
The stopword lists are UTF-8 encoded strings:

&gt;&gt;&gt; nltk.corpus.stopwords.words(&quot;swedish&quot;) [14:18]
['f\xc3\xb6r', 's\xc3\xa5', 'till', '\xc3\xa4r']

&gt;&gt;&gt; nltk.corpus.stopwords.words(&quot;russian&quot;) [3:7]
['\xd0\xbd\xd0\xb5', '\xd1\x87\xd1\x82\xd0\xbe', '\xd0\xbe\xd0\xbd', '\xd0\xbd\xd0\xb0']

Much better would be to return them in unicode:

[u'f\xf6r', ...]

[u'\u043d\u0435', ...]

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=583</p>

**Comment by kmike** [comment]
They are returned as unicode in '2and3' branch: https://github.com/kmike/nltk , but the output is incorrect (I think stopwords are decoded using latin1 encoding, not utf8)

**Comment by kmike** [comment]
This is resolved in 2and3 (I've just checked the output for all stopwords languages and it looks correct).
