### ISSUE TITLE
vader_lexicon.txt currently not being included in Python egg

### ISSUE THREAD

**Issue by ewan-klein** [nltk/nltk#1228]
At present, the text file `vader_lexicon.txt` doesn't get included in the Python egg built by NLTK's `setup.py`. Making the following change seems to fix the problem:

```
-    package_data = {'nltk': ['test/*.doctest', 'VERSION']},
+    package_data = {'nltk': ['test/*.doctest', 'VERSION', 'sentiment/vader_lexicon.txt']},
```

Is there a better way of dealing with this?

NB The very specific information inside `vader_lexicon.txt` means that it's not likely to be used by any code other than `vader.py`, which is why it doesn't make a lot of sense to include it in the NLTK data distribution.

**Comment by stevenbird** [comment]
Seems ok to me.

**Comment by jdeitelzweig** [comment]
What file are you making that change to?

**Comment by wangchuan** [comment]
Where to find NLTK's setup.py? My question may be too trivial since I am new to this area. Thanks! @ewan-klein

**Comment by ewan-klein** [comment]
It's in the top-level of the NLTK directory: `https://github.com/nltk/nltk/blob/develop/setup.py`
