### ISSUE TITLE
Adding Japanese tagged & parsed corpora

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#123]
I'd like to see the following two Japanese tagged &amp; parsed corpora added to NLTK corpus set.

NLTK Japanese Corpora 
http://lilyx.net/pages/nltkjapanesecorpus.html
1. KNB Corpus (Annotated blog corpus) 
2. JEITA Public Morphologically Tagged Corpus (in ChaSen format) 

I've already acquired the permissions from the corpus creators and they are freely re-distributable as NLTK corpus samples.

In that page I distribute the raw corpus files along with their corpus reader scripts. And please be noted that availability of these corpora is assumed in the Japanese translation of the NLTK book, to which including these corpora data/readers to NLTK is crucial.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=587</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2010-08-24T04:38:37.000Z:</strong></p>
<p>Thanks -- I'll work on adding the data and corpus readers to NLTK.
</p><p><strong>hagisan said, at 2010-08-29T23:48:01.000Z:</strong></p>
<p>Hi, when are these data and corpus readers expected to added to NLTK? Thanks!</p><p><strong>StevenBird1 said, at 2010-08-30T00:46:28.000Z:</strong></p>
<p>Sorry for the delay.  Some minor issues:
* can we name the corpus reader modules knb.py or knbc.py, and chasen.py? (none of the existing corpus reader modules include "corpus" or "reader" in their name)
* i'd like to avoid putting corpora larger than 10Mb into the repository; for anything much larger than this it would be good to include a subset (see what we've done for Europarl, for example)
* for the zipped corpus distribution files, would you please provide the standard metadata (please see the XML files here: http://code.google.com/p/nltk/source/browse/trunk/#trunk/nltk_data/packages/corpora)
* is there a reason for having so many copyright notices in the corpus (one per file?)

</p><p><strong>hagisan said, at 2010-09-01T15:29:31.000Z:</strong></p>
<p>Thanks for your feedback.

1. It's totally OK to rename them to knbc.py and chasen.py
2. I've created the sampled version of JEITA corpus (which include both samples from Aozora bunko and Project Sugita Genpaku) http://lilyx.net/media/jeita.tar.bz2
3. I've prepared them: http://lilyx.net/media/jeita.xml http://lilyx.net/media/knbc.xml  Do they look OK?
4. In Aozora bunko and Project Sugita Genpaku, each document has to accompany its own copyright notice. I merged all of them into one file (_copyright.html) and included in the tar.bz2 file.

Thanks!
</p><p><strong>StevenBird1 said, at 2010-09-16T04:33:48.000Z:</strong></p>
<p>I have added the corpora and corpus readers.  Some issues with the corpus readers are documented in nltk/test/japanese.doctest (all these tests currently fail).
</p>

**Comment by kmike** [comment]
After merging "2and3" corpus readers should return unicode, not bytes under Python 2.x, so the Japanese corpus readers are OK.

**Comment by brendanpatrickmurphy** [comment]
There are still problems with how POS Tagging works for these corpora. This afternoon, I loaded up JEITA, and called jeita.tagged_words(). The problem is that the second half of each tuple in JEITA doesn't contain a tag that is easy to test against a POS-tagger. The second half of each tuple contains both orthographic information (each word in the corpus has a spelling for each syllabary in Japanese) so a word tagged as a noun won't have the same tag as another word tagged as a noun. This leads to quite a few problems when testing a tagger against the corpus.

**Comment by kmike** [comment]
@brendanpatrickmurphy could you please open an issue for that?

**Comment by brendanpatrickmurphy** [comment]
opened #1384
