### ISSUE TITLE
StanfordParser method error

### ISSUE THREAD

**Issue by goodrahstar** [nltk/nltk#1232]
Hello Team, 
 I am trying to initialise the Stanford parser but getting error on this line. 

parser = stanford.StanfordParser(model_path="C:/Rahul/englishPCFG.ser.gz") 

Traceback (most recent call last):

  File "<ipython-input-41-f65e460c7c4d>", line 1, in <module>
    parser = stanford.StanfordParser(model_path="C:/Rahul/englishPCFG.ser.gz")

  File "C:\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\nltk\parse\stanford.py", line 99, in **init**
    key=lambda model_name: re.match(self._MODEL_JAR_PATTERN, model_name)

TypeError: unorderable types: NoneType() > NoneType()

Kindly help me with this issue.

Thanks

**Comment by alvations** [comment]
The `StanfordParser()` no longer use the direct path to the model tarball because of how the new Stanford Parser is packaged. 

After setting up your python variables as per the instructions on https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software#stanford-tagger-ner-tokenizer-and-parser, you should be able to do the following:

``` python
>>> from nltk.parse.stanford import StanfordParser
>>> parser=StanfordParser(model_path="edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz")
>>> list(parser.raw_parse("the quick brown fox jumps over the lazy dog"))
[Tree('ROOT', [Tree('NP', [Tree('NP', [Tree('DT', ['the']), Tree('JJ', ['quick']), Tree('JJ', ['brown']), Tree('NN', ['fox'])]), Tree('NP', [Tree('NP', [Tree('NNS', ['jumps'])]), Tree('PP', [Tree('IN', ['over']), Tree('NP', [Tree('DT', ['the']), Tree('JJ', ['lazy']), Tree('NN', ['dog'])])])])])])]

>>> from nltk.parse.stanford import StanfordDependencyParser
>>> dep_parser=StanfordDependencyParser(model_path="edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz")
>>> print [parse.tree() for parse in dep_parser.raw_parse("The quick brown fox jumps over the lazy dog.")]
[Tree('jumps', [Tree('fox', ['The', 'quick', 'brown']), Tree('dog', ['over', 'the', 'lazy'])])]
```

Also, please update your NLTK to version 3.1 and above, and take a look at the answer on http://stackoverflow.com/questions/13883277/stanford-parser-and-nltk/34112695#34112695. If none of the solutions on the question is working, please do post the new traceback after trying the solutions on the question.

**Comment by goodrahstar** [comment]
Thanks @alvations .. updating NLTK version resolved the issue.

**Comment by Neha-Baranwal** [comment]
I have tried all the solutions but still getting the same error.

key=lambda model_name: re.match(self._JAR, model_name)

TypeError: unorderable types: NoneType() > NoneType()

**Comment by alvations** [comment]
If you're using Windows, this might help: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9
On linux, maybe this: https://gist.github.com/alvations/e1df0ba227e542955a8a

**Comment by Neha-Baranwal** [comment]
thanks for the suggestion
i have gone through the instruction where StanfordNERTagger works but at the time stanford parser it shows same error

**Comment by alvations** [comment]
Could you show the code and the error that you encounter? I've checked and the instructions on https://gist.github.com/alvations/e1df0ba227e542955a8a#stanford-parser should be correct on the latest version of `nltk`.

**Comment by Neha-Baranwal** [comment]
simply i run 
os.environ['STANFORD_PARSER'] = os.getcwd()+'stanford-parser.jar'
os.environ['STANFORD_MODELS'] = os.getcwd()+'stanford-parser-3.6.0-models.jar'

parser = stanford.StanfordParser(model_path=os.getcwd()+'englishPCFG.ser.gz')
fp= open("D:/authorization analysis/coding for sentiment analysis/Story/Repo/F35.txt", "r").read().strip()

and get the error

runfile('D:/authorization analysis/coding for sentiment analysis/anaphorares.py', wdir='D:/authorization analysis/coding for sentiment analysis')
Traceback (most recent call last):

  File "<ipython-input-12-783b05730c20>", line 1, in <module>
    runfile('D:/authorization analysis/coding for sentiment analysis/anaphorares.py', wdir='D:/authorization analysis/coding for sentiment analysis')

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "D:/authorization analysis/coding for sentiment analysis/anaphorares.py", line 82, in <module>
    parser = stanford.StanfordParser(model_path=os.getcwd()+'englishPCFG.ser.gz')

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\nltk-3.1-py3.5.egg\nltk\parse\stanford.py", line 51, in **init**
    key=lambda model_name: re.match(self._JAR, model_name)

TypeError: unorderable types: NoneType() > NoneType()

**Comment by alvations** [comment]
The model paths and directories you have initialized and passed to the functions are kind of messy. Please read the instructions on https://gist.github.com/alvations/e1df0ba227e542955a8a#stanford-parser **carefully** and you should get it working. 

You're currently not following (i) how the environmental variables are set and (ii) how you initialized the parser object.

You **do not** need any directory/file path to the initialize the parser object (i.e. use the exact same code below to initialize your parser):

``` python
parser=StanfordParser(model_path="edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz")
```

The `edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz` refers to how Stanford CoreNLP has packaged the model inside their `.jar` file not the path to the parser directory.

If it helps, also read the Windows specific instructions **carefully** too: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9

**Comment by Neha-Baranwal** [comment]
Thank
i will do this 
from nltk.parse.stanford import StanfordParser

> > > parser=StanfordParser(model_path="edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz")
> > > list(parser.raw_parse("the quick brown fox jumps over the lazy dog"))
> > > and get same error which you mention
> > > then we proceed further according to your instruction
> > > from nltk.internals import find_jars_within_path
> > > from nltk.parse.stanford import StanfordParser
> > > parser=StanfordParser(model_path="edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz")
> > > parser._classpath
> > > ('/home/alvas/stanford-parser-full-2015-12-09/stanford-parser.jar', '/home/alvas/stanford-parser-full-2015-12-09/stanford-parser-3.6.0-models.jar')
> > > stanford_dir = parser._classpath[0].rpartition('/')[0]
> > > stanford_dir
> > > '/home/alvas/stanford-parser-full-2015-12-09'
> > > parser._classpath = tuple(find_jars_within_path(stanford_dir))
> > > parser._classpath
> > > ('/home/alvas/stanford-parser-full-2015-12-09/ejml-0.23.jar', '/home/alvas/stanford-parser-full-2015-12-09/slf4j-simple.jar', '/home/alvas/stanford-parser-full-2015-12-09/stanford-parser-3.6.0-models.jar', '/home/alvas/stanford-parser-full-2015-12-09/stanford-parser-3.6.0-javadoc.jar', '/home/alvas/stanford-parser-full-2015-12-09/stanford-parser.jar', '/home/alvas/stanford-parser-full-2015-12-09/slf4j-api.jar', '/home/alvas/stanford-parser-full-2015-12-09/stanford-parser-3.6.0-sources.jar')
> > > list(parser.raw_parse("the quick brown fox jumps over the lazy dog"))
> > > but we get error

raceback (most recent call last):

  File "<ipython-input-6-dd781ba0a59e>", line 1, in <module>
    runfile('D:/authorization analysis/coding for sentiment analysis/test.py', wdir='D:/authorization analysis/coding for sentiment analysis')

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "D:/authorization analysis/coding for sentiment analysis/test.py", line 26, in <module>
    list(parser.raw_parse("the quick brown fox jumps over the lazy dog"))

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\nltk-3.2.1-py3.5.egg\nltk\parse\stanford.py", line 132, in raw_parse
    return next(self.raw_parse_sents([sentence], verbose))

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\nltk-3.2.1-py3.5.egg\nltk\parse\stanford.py", line 150, in raw_parse_sents
    return self._parse_trees_output(self._execute(cmd, '\n'.join(sentences), verbose))

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\nltk-3.2.1-py3.5.egg\nltk\parse\stanford.py", line 216, in _execute
    stdout=PIPE, stderr=PIPE)

  File "C:\Users\neha.baranwal\AppData\Local\Continuum\Anaconda3\lib\site-packages\nltk-3.2.1-py3.5.egg\nltk\internals.py", line 134, in java
    raise OSError('Java command failed : ' + str(cmd))

OSError: Java command failed : ['C:\Program Files\Java\jdk1.8.0_101\bin\java.exe', '-mx1000m', '-cp', '', 'edu.stanford.nlp.parser.lexparser.LexicalizedParser', '-model', 'D:/authorization analysis/coding for sentiment analysis/stanford-parser-full-2015-12-09/edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz', '-sentences', 'newline', '-outputFormat', 'penn', '-encoding', 'utf8', 'C:\Users\NEHA~1.BAR\AppData\Local\Temp\tmpfhihakqq']

**Comment by alvations** [comment]
Did you install Java? Please read the github gist from top to bottom, try not to just copy and paste code without knowing what it is =)

Perhaps, github issue isn't the appropriate place to handle your problem because there's nothing wrong with the code. Please bring the discuss to https://groups.google.com/forum/#!forum/nltk-users

**Comment by Neha-Baranwal** [comment]
Yes i have installed java.

thanks a lot
