### ISSUE TITLE
A more robust Penn Treebank corpus reader

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#124]
I have customized my NLTK installation with a new, more robust corpus reader for the full Penn Treebank (both WSJ and Brown portions). This corpus reader recognizes the categorization of portions of the Treebank into genres (news = WSJ, mystery, romance, etc.):

&gt;&gt;&gt; from nltk.corpus import ptb
&gt;&gt;&gt; ptb.categories()
['adventure', 'belles_lettres', 'fiction', 'humor', 'lore', 'mystery', 'news', 'romance', 'science_fiction']
&gt;&gt;&gt; ptb.parsed_sents(categories='science_fiction')[1]
Tree('S', [Tree('NP-SBJ', [Tree('NP', [Tree('NN', ['Self']), Tree('POS', [&quot;'s&quot;])]), Tree('NN', ['integrity'])]), Tree('VP', [Tree('VP', [Tree('VBD', ['was'])]), Tree('CC', ['and']), Tree('VP', [Tree('VBZ', ['is'])]), Tree('CC', ['and']), Tree('VP', [Tree('ADVP-TMP', [Tree('RB', ['ever'])]), Tree('VBD', ['had']), Tree('VP', [Tree('VBN', ['been'])])])]), Tree('.', ['.'])])

Specifically, I have created the class CategorizedBracketParseCorpusReader—a subclass of both CategorizedCorpusReader and BracketParseCorpusReader—because WSJ and Brown articles contain parses and are also grouped into topical categories.

Since this seems like it would be useful to others working with the Treebank, I am posting the changes here; see the attached patch (relative to 2.0b9).<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=589</p><hr/><h2>earlier comments</h2>

<p><strong>StevenBird1 said, at 2010-08-27T05:48:40.000Z:</strong></p>

<p>Thanks Nathan.  Does the user of this corpus reader need to work out what to put in the file allcats.txt?  How would we select just the WSJ section of Penn Treebank (since this is not a "category")?
</p><p><strong>neatnate said, at 2010-08-27T13:15:11.000Z:</strong></p>

<p>Here's my allcats.txt. My understanding is that the WSJ section is the entire 'news' category.</p>

**Comment by keisks** [comment]
Hello, 

I am not sure this is a right place to report, but I found that the ptb corpus reader reads upper-cased directories (and files) but not lower-cased ones. 
https://github.com/nltk/nltk/blob/develop/nltk/corpus/__init__.py

```
ptb = LazyCorpusLoader( # Penn Treebank v3: WSJ and Brown portions
    'ptb', CategorizedBracketParseCorpusReader, r'(WSJ/\d\d/WSJ_\d\d|BROWN/C[A-Z]/C[A-Z])\d\d.MRG',
    cat_file='allcats.txt', tagset='wsj')
```

The PTB at my hand uses all lower cased names for directories and file names including extensions.
It would be great if this reader can allow both upper and lower cased names, though I am not sure this format is intentionally designed or not.

Thanks,

Keisuke

**Comment by dimazest** [comment]
For the time being, you can replace uppercase letters to lowercase in the following expresion

``` python
r'(WSJ/\d\d/WSJ_\d\d|BROWN/C[A-Z]/C[A-Z])\d\d.MRG'
```

and initialize a LazyCorpusLoader object by yourself.

**Comment by keisks** [comment]
Thank you for the comment.
This is exactly what I did. I just wanted to point out, because PTB 3 (LDC99T42) uses lower cases for the names and I wonder why the reader only allows upper cased names.

**Comment by nschneid** [comment]
I think I wrote that regex (see #278), and that the PTB installation I was using had uppercase names. Probably it should be rewritten so it is case-insensitive.

**Comment by MInner** [comment]
this workaround is still required (renaming files): http://stackoverflow.com/a/36935784/232371

**Comment by tastyminerals** [comment]
(bump) same issue and still not resolved, sigh
