### ISSUE TITLE
Add "ll" to nltk.corpus.stopwords.word("english")

### ISSUE THREAD

**Issue by aewhatley** [nltk/nltk#1246]
I think that "ll" should be added to this corpus, as "s" and "t" are already there, and when sentences with contractions such as "they'll" or "you'll" are tokenized, "ll" will be added as a token, and if we filter out stopwords, "ll" should be removed as well.

**Comment by DuyguA** [comment]
I agree as well.

**Comment by petr-tik** [comment]
Good point. Seconded

**Comment by stevenbird** [comment]
@aewhatley: I went to add `ll` to the English stopwords corpus but found that it is already there.

**Comment by alvations** [comment]
Possibly, the user should do something like this:

``` python
>>> from string import punctuation
>>> from nltk import word_tokenize
>>> from nltk.corpus import stopwords
>>> stoplist = stopwords.words('english')
>>> sent = word_tokenize("I'll be back.")
>>> sent
['I', "'ll", 'be', 'back', '.']
>>> "ll" in stoplist
True
>>> "'ll" in stoplist
False
>>> "ve" in stoplist
True
>>> "'ve" in stoplist
False
>>> [word for word in sent if word not in stoplist]
['I', "'ll", 'back', '.']
>>> [word for word in sent if word.strip(punctuation) not in stoplist]
['I', 'back', '.']
```

**Comment by stevenbird** [comment]
@alvations: thanks for a good diagnosis and solution
