### ISSUE TITLE
Tokenization error

### ISSUE THREAD

**Issue by octavian-ganea** [nltk/nltk#1250]
There is an error of processing dots in the tokenizer:
The following code

```
    val ptbt = new PTBTokenizer(
      new StringReader("Tokenization is performed.Parameters can be specified."),
      new CoreLabelTokenFactory(), "")
    while (ptbt.hasNext()) {
      val label = ptbt.next()
      val w = label.originalText()
      println(w)
    }
```

gives "performed.Parameters" as an word. If I put a space after 'performed' it will work, but still, natural text can be messy and omitting spaces after punctuation is very common.

**Comment by alvations** [comment]
@octavian-ganea are you reporting to the correct library? Could you specify which file the code is coming from and we'll see whether we can help you.

**Comment by octavian-ganea** [comment]
@alvations I've tried a simple example starting from this tutorial : http://nlp.stanford.edu/software/tokenizer.shtml

**Comment by alvations** [comment]
@octavian-ganea I think the proper channel for your question is on @stanfordnlp https://github.com/stanfordnlp/CoreNLP instead of NLTK =)

**Comment by octavian-ganea** [comment]
Sorry about this. Just realized the mistake.
