### ISSUE TITLE
Loading jars from custom path.

### ISSUE THREAD

**Issue by goodrahstar** [nltk/nltk#1254]
Hello Team,
 I want to load the stanfor-parser.jar file from my custom defined path. I dont want to set ENV variable for jar locations. Is this possible ? If yes then how?

Thanks,
Rahul

**Comment by alvations** [comment]
Please see https://gist.github.com/alvations/e1df0ba227e542955a8a and http://stackoverflow.com/questions/13883277/stanford-parser-and-nltk/34112695#34112695 

Also, if you're interested, please keep track of #1249 on updates on new Stanford API integration in NLTK.

**Comment by longdt219** [comment]
Use the constructor (just set the path_to_jar and path_to_models_jar) 
Here's the constructor for stanford parser

``` python
def __init__(self, path_to_jar=None, path_to_models_jar=None,
                 model_path='edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz',
                 encoding='utf8', verbose=False,
                 java_options='-mx1000m', corenlp_options=''):
```

**Comment by alvations** [comment]
@goodrahstar did @longdt219's hint and/or the setup examples in the gists work?

**Comment by goodrahstar** [comment]
@alvations yes it worked but with few small tweaks in the code.
Sorry got busy ..... thanks a lot @longdt219 for the response :)
