### ISSUE TITLE
Printing to postscript error

### ISSUE THREAD

**Issue by hack1nt0** [nltk/nltk#1255]
I draw a syntax tree with tree.draw(), which is below:

![2016-01-18 8 56 33](https://cloud.githubusercontent.com/assets/5208653/12391905/0683e8a8-be26-11e5-85f7-fba3b98c1626.png)

But after i save it as a ps file using 'File --> Print to Postscript', I get below:

![2016-01-18 8 58 20](https://cloud.githubusercontent.com/assets/5208653/12391934/3f2fa23c-be26-11e5-9494-36cd0e99427d.png)

So what is wrong with it?? can somebody help me?

**Comment by dimazest** [comment]
Could you please share the code that produces the trees.

**Comment by alvations** [comment]
@hack1nt0 are you still experiencing the error? Could you share the code that you've used to produce the trees and the postscript?

**Comment by shingohu** [comment]
@alvations @dimazest  I have the same question 
we want to show the Tree in html ，so we use the method print_to_file to save the Tree in .ps file，and we convert the .ps file to .png file

the method like this:
TreeView(trees)._cframe.print_to_file('tree1.ps')
os.system('convert tree1.ps tree1.png')

english is ok，but chinese is not show in png file
