### ISSUE TITLE
Reading wordnet error

### ISSUE THREAD

**Issue by JiHongyu** [nltk/nltk#1256]
My environment is Python3.5.1 and nltk3.1. When I executed the second command below, it throws an AssertionError.

``` python
from nltk.corpus import wordnet as wn
wn.synsets('dog')
```

I find that there is a bug in class OpenOnDemandZipFile(data.py) about file reference count.
I modified the member function read() and it worked.

``` python
def read(self, name):
　　assert self.fp is None
　　self.fp = open(self.filename, 'rb')
　　self._fileRefCnt += 1 #my modification
　　value = zipfile.ZipFile.read(self, name)
　　self.close()
　　return value
```

**Comment by alvations** [comment]
@JiHongyu can you post the full traceback for the `AssertionError`? I've tried removing wordnet from my nltk_data directory and then redownloading and tried the import but I didn't get any errors when retrieving synsets.

**Comment by JiHongyu** [comment]
> AssertionError                            Traceback (most recent call last)
> <ipython-input-3-20ebf0cefcd2> in <module>()
> ----> 1 wn.synsets('dog')
> 
> D:\Anaconda3\lib\site-packages\nltk\corpus\util.py in __getattr__(self, attr)
>      97             raise AttributeError("LazyCorpusLoader object has no attribu
> te '__bases__'")
>      98
> ---> 99         self.__load()
>     100         # This looks circular, but its not, since __load() changes our
>     101         # __class__ to something new:
> 
> D:\Anaconda3\lib\site-packages\nltk\corpus\util.py in __load(self)
>      65
>      66         # Load the corpus.
> ---> 67         corpus = self.__reader_cls(root, _self.__args, *_self.__kwargs)
>      68
>      69         # This is where the magic happens!  Transform ourselves into
> 
> D:\Anaconda3\lib\site-packages\nltk\corpus\reader\wordnet.py in __init__(self, r
> oot, omw_reader)
>    1047
>    1048         # Load the lexnames
> -> 1049         for i, line in enumerate(self.open('lexnames')):
>    1050             index, lexname, _ = line.split()
>    1051             assert int(index) == i
> 
> D:\Anaconda3\lib\site-packages\nltk\corpus\reader\api.py in open(self, file)
>     208         """
>     209         encoding = self.encoding(file)
> --> 210         stream = self._root.join(file).open(encoding)
>     211         return stream
>     212
> 
> D:\Anaconda3\lib\site-packages\nltk\data.py in open(self, encoding)
>     503
>     504     def open(self, encoding=None):
> --> 505         data = self._zipfile.read(self._entry)
>     506         stream = BytesIO(data)
>     507         if self._entry.endswith('.gz'):
> 
> D:\Anaconda3\lib\site-packages\nltk\data.py in read(self, name)
>     982         #self._fileRefCnt += 1
>     983         value = zipfile.ZipFile.read(self, name)
> --> 984         self.close()
>     985         return value
>     986
> 
> D:\Anaconda3\lib\zipfile.py in close(self)
>    1608             fp = self.fp
>    1609             self.fp = None
> -> 1610             self._fpclose(fp)
>    1611
>    1612     def _write_end_record(self):
> 
> D:\Anaconda3\lib\zipfile.py in _fpclose(self, fp)
>    1712
>    1713     def _fpclose(self, fp):
> -> 1714         assert self._fileRefCnt > 0
>    1715         self._fileRefCnt -= 1
>    1716         if not self._fileRefCnt and not self._filePassed:
> 
> AssertionError:

The immediate cause is file reference count down to 0 before close the file.

**Comment by JiHongyu** [comment]
Maybe caused by the version of python. It work well on the other computer with python 3.4.

**Comment by alvations** [comment]
@JiHongyu Thanks for reporting this issue. This should be patched by #1301

**Comment by spk921** [comment]
I am using mac and still have a error. 

```

def read(self, name):
    assert self.fp is None
    self.fp = open(self.filename, 'rb')
    self._fileRefCnt += 1
    value = zipfile.ZipFile.read(self, name)
    # Ensure that _fileRefCnt needs to be set for Python2and3 compatible code.
    # Since we only opened one file here, we add 1.
    self.close()
    return value

```

Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
  File "/Users/sangpil_kim/anaconda3/lib/python3.5/site-packages/nltk/downloader.py", line 664, in download  
    for msg in self.incr_download(info_or_id, download_dir, force):  
  File "/Users/sangpil_kim/anaconda3/lib/python3.5/site-packages/nltk/downloader.py", line 543, in incr_download  
    for msg in self.incr_download(info.children, download_dir, force):  
  File "/Users/sangpil_kim/anaconda3/lib/python3.5/site-packages/nltk/downloader.py", line 529, in incr_download  
    for msg in self._download_list(info_or_id, download_dir, force):  
  File "/Users/sangpil_kim/anaconda3/lib/python3.5/site-packages/nltk/downloader.py", line 572, in _download_list  
    for msg in self.incr_download(item, download_dir, force):  
  File "/Users/sangpil_kim/anaconda3/lib/python3.5/site-packages/nltk/downloader.py", line 549, in incr_download  
    for msg in self._download_package(info, download_dir, force):  
  File "/Users/sangpil_kim/anaconda3/lib/python3.5/site-packages/nltk/downloader.py", line 638, in _download_package  
    for msg in _unzip_iter(filepath, zipdir, verbose=False):  
  File "/Users/sangpil_kim/anaconda3/lib/python3.5/site-packages/nltk/downloader.py", line 2039, in _unzip_iter  
    outfile.write(contents)  
OSError: [Errno 22] Invalid argument

**Comment by alvations** [comment]
What is the version of your nltk?

**Comment by spk921** [comment]
My version is 3.2.1 using python3.5 with anaconda3

**Comment by alvations** [comment]
~~Anaconda is still packaging nltk with the old code =(~~ 

My mistake, I didn't look at it carefully while commuting just now. The [context manager solution was reverted](https://github.com/nltk/nltk/commits/develop/nltk/data.py) and the current code in v3.2.1 shipped by `conda` should be correct.

**Comment by spk921** [comment]
I see then I need to use non-conda python3.5 thanks. You may close the issue. Or is there are any thing that I can tune the conda?

**Comment by alvations** [comment]
@spk921 Could you see whether you can replicate these steps?

``` bash
alvas@ubi:~$ cd nltk_data/corpora/
alvas@ubi:~/nltk_data/corpora$ rm wordnet.zip 
alvas@ubi:~/nltk_data/corpora$ rm -r wordnet
alvas@ubi:~/nltk_data/corpora$ cd
alvas@ubi:~$ python3
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.download('wordnet')
[nltk_data] Downloading package wordnet to /home/alvas/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
True
>>> exit()
alvas@ubi:~$ cd nltk_data/corpora/
alvas@ubi:~/nltk_data/corpora$ ls -lah wordnet
total 35M
drwxrwxr-x  2 alvas alvas 4.0K Sep  1 10:06 .
drwxrwxr-x 71 alvas alvas 4.0K Sep  1 10:06 ..
-rw-rw-r--  1 alvas alvas  23K Sep  1 10:06 adj.exc
-rw-rw-r--  1 alvas alvas   85 Sep  1 10:06 adv.exc
-rw-rw-r--  1 alvas alvas  212 Sep  1 10:06 citation.bib
-rw-rw-r--  1 alvas alvas 890K Sep  1 10:06 cntlist.rev
-rw-rw-r--  1 alvas alvas 3.1M Sep  1 10:06 data.adj
-rw-rw-r--  1 alvas alvas 505K Sep  1 10:06 data.adv
-rw-rw-r--  1 alvas alvas  15M Sep  1 10:06 data.noun
-rw-rw-r--  1 alvas alvas 2.7M Sep  1 10:06 data.verb
-rw-rw-r--  1 alvas alvas 805K Sep  1 10:06 index.adj
-rw-rw-r--  1 alvas alvas 159K Sep  1 10:06 index.adv
-rw-rw-r--  1 alvas alvas 4.6M Sep  1 10:06 index.noun
-rw-rw-r--  1 alvas alvas 7.0M Sep  1 10:06 index.sense
-rw-rw-r--  1 alvas alvas 512K Sep  1 10:06 index.verb
-rw-rw-r--  1 alvas alvas  803 Sep  1 10:06 lexnames
-rw-rw-r--  1 alvas alvas 1.6K Sep  1 10:06 LICENSE
-rw-rw-r--  1 alvas alvas  38K Sep  1 10:06 noun.exc
-rw-rw-r--  1 alvas alvas 4.1K Sep  1 10:06 README
-rw-rw-r--  1 alvas alvas  38K Sep  1 10:06 verb.exc
alvas@ubi:~/nltk_data/corpora$ ls -lah wordnet.zip 
-rw-rw-r-- 1 alvas alvas 11M Sep  1 10:06 wordnet.zip
```

I suspect it is not the `nltk.data.OpenOnDemandZipFile` that JiHongyu was referring that is causing your error.

**Comment by spk921** [comment]
Thanks targeting nltk.download('wordnet') done successfully. panlex_lite.zip cause an error for me. Thank you. You may close the issue.
