### ISSUE TITLE
Potential wordnet lemmatization issue

### ISSUE THREAD

**Issue by Fiedzia** [nltk/nltk#1258]
I am not sure if its an issue with wordnet corpus or with nltk or my way of using it, but I've found one case where I am not getting expected result:
~/nltk_data/corpora/wordnet/noun.exc contain this line:
antae anta

where (according to wikipedia) anta is singular and antae plural.
yet this code:

from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()
print(wnl.lemmatize('antae'))

prints antae, not anta.
same goes for antalkalies -> antalkali
but antefixa -> antefix works fine.

Is it a bug (and where?) or I am wrong expecting it to be lemmatized this way?

**Comment by nschneid** [comment]
Interesting...has there been a change for anta/antae between WN 3.0 and 3.1? http://www.golovchenko.org/cgi-bin/wnsearch?q=antae (WN 3.0) gives an error that 'anta' cannot be found, but it apparently lemmatizes 'antae'. http://wordnetweb.princeton.edu/perl/webwn?s=anta&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h= (WN 3.1) has 'anta' but isn't lemmatizing 'antae'.
