### ISSUE TITLE
ImportError: No module named sentiment  for python 2.7 on Windows PC and Anaconda  installation

### ISSUE THREAD

**Issue by Sandy4321** [nltk/nltk#1259]
I use python 2.7 on Windows PC and Anaconda python installation
Pls help run  example from  http://www.nltk.org/howto/sentiment.html 
can not import nltk.sentiment, error comes from `from nltk.sentiment import SentimentAnalyzer`

It gives the error:

```
Traceback (most recent call last):
  Debug Probe, prompt 1, line 1
ImportError: No module named sentiment
from nltk.corpus import subjectivity
Traceback (most recent call last):
  Debug Probe, prompt 2, line 1
ImportError: cannot import name subjectivity
```

but nltk import is ok 

`import nltk` and `NaiveBayesClassifier` import is ok seems to be everything 

```
from nltk.classify import NaiveBayesClassifier
```

but 

```
from nltk.sentiment fails to import 
```

gives 

```
from nltk.sentiment.vader import SentimentIntensityAnalyzer
Traceback (most recent call last):
  Debug Probe, prompt 6, line 1
ImportError: No module named sentiment.vader
```

**Comment by fievelk** [comment]
Hi @Sandy4321. Could you please check which NLTK version you are running? You can do it for example with:

```
python -c 'import nltk; print(nltk.__version__)'
```

or

```
pip freeze | grep nltk
```

The `sentiment` package has been added in **NLTK 3.1**. In case you are using an older version, you can upgrade it using

```
pip install --upgrade nltk
```

**Comment by alvations** [comment]
In `conda`, do:

```
conda update nltk
```

But remember to also update your `python` and `conda` distribution:

```
conda update conda
conda update python
```

**Comment by fievelk** [comment]
@alvations Thank you, I forgot to add Anaconda details.
