### ISSUE TITLE
GermaNet Integration in NLTK

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#126]
We have started a students project to integrate GermNet into NLTK. The interface will provide access functions to GermaNet similar to the access functions available for WordNet. However, there will be 2 main differences:
1.) GermaNet does not provide as much information as WordNet. Thus the API will provide only a subset of the WordNet functions.
2.) GermaNet can not be distributed within NLTK since each user has to apply for a license (free for research and education).

In addition we plan to integrate further German-specific functionality into NLTK, e.g. lemmatisation.  <p>Migrated from http://code.google.com/p/nltk/issues/detail?id=604</p><hr/><h2>earlier comments</h2>

<p><strong>schreon.loeder said, at 2011-05-16T20:48:38.000Z:</strong></p>

<p>The results of the student project mentioned above have been bundled to one zip file (see attachment). 

The introduction is currently under development. You can view it on this public google doc: http://goo.gl/cABPy

The zip file contains:

- the current version of the Germanet Corpus Reader
- the current version of the German Wortschatz Lemmatizer
- technical documentation created via EpyDoc
- the data of Projekt Deutscher Wortschatz the lemmatizer relies on. ATTENTION, the data may not be used for commercial purposes. Please visit http://wortschatz.uni-leipzig.de/ for further information
- doctests

Please note:
- GermaNet Version 5.3 must be obtained manually (NOT the current version 6.0)
- We do not have the permission to distribute the GermaNet XML Files ourselves. But it is possible to obtain a free license for educational and reseach purposes.
- Please see http://www.sfs.uni-tuebingen.de/GermaNet/ for further information on licensing</p>

**Comment by stevenbird** [comment]
The supplied code was not in a format that could be tested and incorporated. Anyone wishing to add this functionality to NLTK should submit a pull request please.
