### ISSUE TITLE
SRL in SENNA

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1260]
Just a quick raincheck. Is there a reason why semantic role labeling (SRL) was left out in the [nltk.tag.senna.py](https://github.com/nltk/nltk/blob/develop/nltk/tag/senna.py)? Is someone working on adding it?

**Comment by stevenbird** [comment]
@aboSamoor – would you please comment on this?

**Comment by aboSamoor** [comment]
Srl could be added to the module, but I am not working on it.

**Comment by stevenbird** [comment]
Thanks @aboSamoor. @alvations – feel free to open a new issue if you think this should be added.
