### ISSUE TITLE
Technical issues in BLEU

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1268]
This is an issue with how BLEU works and not exactly the implementation that causes an error with https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py35-jenkins,jdk=jdk8latestOnlineInstall/492/testReport/junit/(root)/bleu_doctest/bleu_doctest/

---

There are many flaws in the original formulation of BLEU in http://www.aclweb.org/anthology/P02-1040.pdf but there's a big problem that we've all overlooked. 

Equation in section 2.3 in the paper:

```
BLEU = BP * exp (sum (w_n * log(p_n)))
```

where `p_n` is the modified precision calculated with the formula from section 2.1.1 and `w_n` is the corresponding weights as per each order of ngram set by the user. 

Consider the case where the numerator in the `p_n` formula of section 2.1.1 is 0 for every order of ngram. So `log(p_n)` becomes invalid because the logarithm curve is asymptotic at 0 (giving a math domain error).

So if the solution was to simply set `log(p_n) = 0 if p_n == 0 else log(p_n)` then we get into another problem when the sum of all `log(p_n)` is 0 and our `exp(0)` returns 1 which gives perfect BLEU scores for 0 precision. 

The assumption is that BLEU is measured at corpus level so having absolute 0 for all hypothesis-reference pairs for all order of ngram seems ridiculous.

So at segment level, there seem to be multiple ways to overcome that according to http://acl2014.org/acl2014/W14-33/pdf/W14-3346.pdf .

**How should we proceed with the implementation of BLEU in NLTK?**
- Implement the Chen and Cherry (2014) methods and enforce one of the smoothing by default
- If numerator == 0, do the "stupid" smoothing i.e. to add 1 to numerator and denominator (name from http://www.aclweb.org/anthology/D07-1090.pdf)
- Leave it as it is, and use the awkward doctest as an example of how BLEU is inadequate at sentence level

**Comment by alvations** [comment]
Given the `smooth_bleu()` method from https://github.com/alvations/nltk/commit/1ee6ffdb883d4b62ce2e9083bce0e93a32c6a319

For now, the solution seems to be [to allow hard 0 scores](https://github.com/alvations/nltk/commit/a83e7242453b81f587f99d493d93b6e5cb246c8c) and then if users wants to avoid hard 0 scores, he/she should use the `smoothing_method` parameter:

```
>>> from nltk.translate import bleu
>>> ref = 'The candidate has no alignment to any of the references'.split()
>>> hyp = 'John loves Mary'.split()
>>> sentence_bleu([ref], hyp)
0
>>>bleu([ref], hyp, smoothing_method=1)
0.009697196786440506
>>> bleu([ref], hyp, smoothing_method=2)
0.04848598393220253
>>> bleu([ref], hyp, smoothing_method=3)
0.017142384015481196
>>> bleu([ref], hyp, smoothing_method=4)
0.976842555469704
>>> bleu([ref], hyp, smoothing_method=5)
0.006220754638929109
>>> bleu([ref], hyp, smoothing_method=6)
0
```

That should resolve the doctest error on https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py35-jenkins,jdk=jdk8latestOnlineInstall/492/testReport/junit/(root)/bleu_doctest/bleu_doctest/

But is that the most "optimal"/"wanted" solution?

**Comment by hoontw** [comment]
The default interpretation of BLEU depends on what users are hoping to achieve, and also what we want to encourage. Do users want the original but flawed BLEU, or something that is more practical for real world usage?

If the MT community has settled into a certain interpretation of BLEU, we should probably use that. The original BLEU formulation can probably be renamed to something like `bleu_classic` or `bleu_original`.

**Comment by alvations** [comment]
@hoontw I think there's still no consensus as to how to handle sentence-level BLEU yet. But I think the hard 0 implementation is the norm (though not as described as in the paper):

```
alvas@ubi:~$ echo 'The candidate has no alignment to any of the references' > ref.txt
alvas@ubi:~$ echo 'John loves Mary' > hyp.txt
alvas@ubi:~$ ~/mosesdecoder/scripts/generic/multi-bleu.perl 
Use of uninitialized value $ARGV[0] in string eq at /home/alvas/mosesdecoder/scripts/generic/multi-bleu.perl line 8.
usage: multi-bleu.pl [-lc] reference < hypothesis
Reads the references from reference or reference0, reference1, ...
alvas@ubi:~$ ~/mosesdecoder/scripts/generic/multi-bleu.perl ref.txt < hyp.txt
Use of uninitialized value in division (/) at /home/alvas/mosesdecoder/scripts/generic/multi-bleu.perl line 124, <STDIN> line 1.
Use of uninitialized value in division (/) at /home/alvas/mosesdecoder/scripts/generic/multi-bleu.perl line 124, <STDIN> line 1.
Use of uninitialized value in division (/) at /home/alvas/mosesdecoder/scripts/generic/multi-bleu.perl line 124, <STDIN> line 1.
BLEU = 0.00, 0.0/0.0/0.0/0.0 (BP=0.097, ratio=0.300, hyp_len=3, ref_len=10)
```

**Comment by alvations** [comment]
**Would it be okay if we stick with the hard 0 implementation since it's more logical than the original BLEU?** And if users doesn't want the hard zero, then the new smoothing functions can be used.

**Comment by dimazest** [comment]
I would say so. If the original implementation is considered to be outdated then there is no reason to stick to it.

**Comment by alvations** [comment]
For now, it's doing the logical thing to return a hard 0 when there's 0 overlaps for all order of ngrams.
