### ISSUE TITLE
Better documentation for HMM unsupervised training

### ISSUE THREAD

**Issue by a1lu** [nltk/nltk#1277]
I had some problems using unsupervised training for hmms.
The docs say:

```
        :param unlabeled_sequences: the unsupervised training data, a set of
            sequences of observations
        :type unlabeled_sequences: list
```

When i read this i thought about a List [ word_1, ..., word_n ] < a unlabeled sequence > but the correct way is [ (word_1, tag_1),...,(word_n,tag_n) ] < a labeled sequence imo > .
I think we should explain this better to avoid confusion.

**Comment by theaverageguy** [comment]
I would like to fix this.
