### ISSUE TITLE
Weird issue with bleu scores

### ISSUE THREAD

**Issue by spijs** [nltk/nltk#1285]
I discovered a weird issue when trying to calculate bleu scores for individual sentences with evaluation code [https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py](here).
The method that contains the weird behaviour is : `sentence_bleu`
The problem occurs whenever the pn value becomes 1.

When for example calculating the bleu 1 score for the following candidate sentence:
_[this,is,an,example]_
When given two reference sentences:
_[this,is,something]
[this,is,an,example]_

`_modified_precision` correctly gives 1 as an answer, since the sentence is exactly the reference sentence. Then the logarithm gets taken which results in a zero value. This still seems correct. Next all the different p_n's gets summed which in this case is just one zero value. So the sum is still 0.

Then however the following code seems rather odd:
`if sum_s == 0:
        return 0`

This way the resulting bleu-score is 0. I don't understand why this needs to be here.
Without this if-clause, the zero-value correctly gets put in the rest of the formula and a correct 1 is returned.

**Comment by alvations** [comment]
Now this is a wacky bug that has to do with the nature of BLEU and not the implementation ;P

The if [`sum_s == 0: return 0`](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L94) is a hack to handle cases where 0 words in the ngram matches the reference sentences. So that part is correct.

The problem lies with the [summing of the precision scores](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L91):

``` python
    # Calculates the overall modified precision for all ngrams.
    # By sum of the product of the weights and the respective *p_n*
    s = (w * math.log(p_i) if p_i else 0 
         for w, p_i in zip(weights, p_n))
    sum_s = math.fsum(s)
```

In BLEU equation in the [original BLEU paper](http://www.aclweb.org/anthology/P02-1040.pdf) section 2.3:
- Note the `log(p_n)` here, if `p_n == 1`, you will get a 0 although your precision is 1.
- Then note the `exp(sum(w_n * p_n))`, if `sum(w_n * p_n) == 0` meaning that none of the ngrams in the hypothesis appears in the references, it returns a BLEU of 1. 

---

If we do some debugging:

``` python
>>> import math
>>> weights = [0.25] * 4
>>> p_n = [1] * 4
>>> s = [w * math.log(p_i) if p_i else 0 for w, p_i in zip(weights, p_n)]
>>> s
[0.0, 0.0, 0.0, 0.0]
```

So if we do a simple check again for all 0s in `p_n` before we do a `if sum_s == 0: return 0`, it might work:

**In the case that `p_n` are all 0s, we get BLEU=1.0 for 0 precision using the original BLEU formula**

``` python
>>> import math
>>> weights = [0.25] * 4
>>> p_n = [0, 0, 0, 0]
>>> s = [w * math.log(p_i) if p_i else 0 for w, p_i in zip(weights, p_n)]
>>> sum_s = math.fsum(s)
>>> 1.0 * math.exp(sum_s)
1.0
```

**So we would have to add the hack**:

``` python
>>> p_n = [0, 0, 0, 0]
>>> s = [w * math.log(p_i) if p_i else 0 for w, p_i in zip(weights, p_n)]
>>> sum_s = math.fsum(s)
>>> 0 if sum_s == 0 else 1.0 * math.exp(sum_s)
0
```

**But when we add the hack and `p_n` are all 1s, the BLEU=0.0**:

``` python
>>> p_n = [1, 1, 1, 1]
>>> s = [w * math.log(p_i) if p_i else 0 for w, p_i in zip(weights, p_n)]
>>> sum_s = math.fsum(s)
>>> 0 if sum_s == 0 else 1.0 * math.exp(sum_s)
0
```

**So we have to add the "new" hack**:

``` python
>>> p_n = [1, 1, 1, 1]
>>> s = [w * math.log(p_i) if p_i else 0 for w, p_i in zip(weights, p_n)]
>>> sum_s = math.fsum(s)
>>> 0 if sum_s == 0 else 1.0 * math.exp(sum_s)
0
>>> 0 if sum_s == 0 and not sum(p_n) else 1.0 * math.exp(sum_s)
1.0
```

**Comment by spijs** [comment]
Couldn't it be possible to change the code so instead of returning 0 in the else, some kind of zero-counter can be raised. And before the exp, the counter is compared to the n in the n-grams?
That way 0 will only be returned if every p_i is 0. Correct me if I'm wrong

**Comment by alvations** [comment]
@spijs Thanks for reporting the bug! 

But do note that with the patches for #1286 and https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L94, the BLEU implementation in NLTK would NOT be the original BLEU but the most logical choice of implementation

**Comment by alvations** [comment]
Fixed at #1286 ;P

**Comment by alvations** [comment]
Ah, actually, it's not fixed. We cannot simply just to `w * 1` when `p_n == [1, 1, 1, 1]`. Because the exponential comes the sum.

**Comment by alvations** [comment]
@spijs Seems like there's no clean way to mathematically hack the equation since `exp(0)` is required for `BLEU == 1.0`, so it seems like the only way out to cover both `BLEU=0` and `BLEU=1` is to do https://github.com/nltk/nltk/pull/1286/files#diff-de624b4549ea37f3f8480d6734bd475bR94

**Comment by spijs** [comment]
At first glance that seems like a good fix to me.

2016-02-16 18:54 GMT+01:00 alvations notifications@github.com:

**Comment by alvations** [comment]
Does the update above on the problem and the hack makes sense?

**Comment by spijs** [comment]
yeah it's actually about the same solution as what I proposed, but cleaner
:)

2016-02-16 19:09 GMT+01:00 alvations notifications@github.com:

**Comment by alvations** [comment]
As a spillover issue from #1268, #1285, #1288, #1241, #789, #775, #922

After thinking through it, I think the sensible solution is to follow the [mteval-v13a.pl](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v13a.pl#L834) and make the default setting to always smooth the output with our implementation of [SmoothingFunction.method3()](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L476). That way we can get rid fo the ugly hacks to deal with `exp(1)` and `log(0)`.

@ygraham showed that Moses' sentence BLEU is competitive, maybe that's a motivation for our implementation to emulate it. I'm not sure whether whether the paper is referring to `mteval-v13a.pl` as Moses' sentence BLEU though. 

And if the user wants the original Papineni et al. (2002) BLEU, then they should use 

```
chencherry=SmoothingFunction()
sentence_bleu(references, hypothesis, smoothing_function=chencherry.method0)
```

@stevenbird , @hoontw , @dimazest , @karpathy, @kylebgorman, Are we alright with following mteval-v13a.pl on sentence-level BLEU? If so, I'll work on cleaning up the BLEU code and setting the default to emulate mteval-v13a.pl once the new tokenizers PR is merged.

**Comment by kylebgorman** [comment]
I don't have any dogs in this race but I'm going to guess that users generally want and expect mteval compatibility.  But I would greatly prefer the interface to be:

```
sentence_bleu(ref, hyp, smoothing="chen_cherry")
sentence_bleu(ref, hyp, smoothing="bleu")
...
```

etc. I greatly prefer this to @alvations' snippet version.

**Comment by dimazest** [comment]
smoothing can be either a string (for default cases) or a function (if custom method is used).

**Comment by alvations** [comment]
Back to the smoothing issues. 

I've looked at several implementation of BLEU and there's quite some variants.
- `mteval-13a.pl` has an option to get [non-smoothen BLEU](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v13a.pl#L808),  it's the closest to original BLEU description in the Papineni et al. (2002) paper. 
  - There's no indication of how this non-smoothen BLEU handles the `log(0)` and `exp(0)` situations. 
- @alopez solution on [`DREAMT`](https://github.com/alopez/dreamt/tree/master/reranker#L23) seems to follow similar non-smoothing implementation.
- @cmu-mtlab METEOR's solution is to wrap around `mteval-13a.pl`, https://github.com/cmu-mtlab/meteor/blob/master/mt-diff/mt-diff.py
- [`multi-bleu.pl`](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl#L139) looks like an unsmoothen version too.
- @ugermann [`bsbleu.py`](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/bsbleu.py#L82) looks like an unsmoothen version too. 
- `mteval-13a.pl` [default option is to do NIST smoothing](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v13a.pl#L834) like  [method 3 from Chen and Cherry (2014) description](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L470)
- @bhaddow [Promix's implementation](https://github.com/moses-smt/mosesdecoder/blob/master/contrib/promix/bleu.py#L21) is to do +epsilon smoothing like [method 2 from Chen and Cherry](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L470) but they also +epsilon to the denominator
- @odashi mteval BLEU does the +epsilon smoothing on both numerator and denominator. ~~But when it's not smoothing, it returns 0 ["if at least 1 numerator is 0, the score becomes 0"](https://github.com/odashi/mteval/blob/master/src/lib/BLEUEvaluator.cc#L76)~~ It behaves like Lin and Och (2004) when smoothing is set to 1.0. When 'smooth' is set as nonzero, it evaluates whether only 1-gram precision is 0 or not.
- [Moses' MERT implementation of BLEU is doing +1 smoothing](https://github.com/moses-smt/mosesdecoder/blob/master/mert/BleuScorer.h#L97) like Lin and Och (2004), as described in [Chen and Cherry (2014) method 2](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L461)
  - According to @ygraham, the sentence BLEU using +1 smoothing, is the one that has high human correlation together with METEOR in https://www.computing.dcu.ie/~ygraham/grahametal-naacl15.pdf 

Given the different shades of BLEU, would we prefer to set method 2 or method 3 as the default for NLTK's BLEU?

**Comment by odashi** [comment]
Hi, sorry the comment in my mteval tool (as suggested above) looks a misleading.
The code corresponding to the comment "if at least 1 numerator is 0, the score becomes 0" runs after adding smoothing factor for (n>1)-grams.
So my tool behaves similar to Lin and Och (2004), if the "smoothing" option is set as 1.0.

**Comment by alvations** [comment]
@odashi Thanks for the correction! I've updated the previous thread accordingly.

**Comment by alvations** [comment]
From the polls (https://twitter.com/alvations/status/717647857768144896), it seems like most people are using the non-smoothen BLEU which is the root of the wave of BLEU related issues when users use the `bleu()` function on small datasets which results in 0 ngram matches for higher order ngrams. 

Maybe we should add an option to cover `bleu(..., smoothing=None)` or `bleu(..., smoothing=False)`, which is more pythonic in this case?

And for smoothen BLEU, there's a close tie between method 3 NIST smoothing from `mteval-13a.pl` and method 2 from `Moses MERT` +1 smoothing. 

If there's no objection, let's go with method 3 as the default since it's the official script used my WMT.

**Comment by stevenbird** [comment]
@alvations – is this resolved?

**Comment by alvations** [comment]
The smoothing is resolved but to make sure that the fixes are correct, I'll still have to write tests to verify that. Sorry for taking that long to complete this.

**Comment by alvations** [comment]
#1330 and #1488 should resolve this.

**Comment by xsway** [comment]
Is it normal that the result of 
`nltk.translate.bleu_score.sentence_bleu("it is a guide to action".split(), "it is a guide to action".split())` is
0.638943104246272 ? (and not 1.0)

**Comment by alvations** [comment]
~~No, 0.63... is wrong,  it should return 1.0, seems like the f6c0fcdb682493274f23588c32a4070e8834c885 commit broke too many things in BLEU.~~

I've just double check the implementation, it should be correct as of the current. Just that it didn't handle #1634 well enough.

Thanks @xsway for raising the issue. The interface for BLEU should be `bleu([references], hypothesis`, it's because BLEU allows for multiple reference sentences (in the target language) per source language sentence.

```python
>>> import nltk
>>> nltk.translate.bleu_score.sentence_bleu(["it is a guide to action".split()], "it is a guide to action".split())
1.0
```

**Comment by xsway** [comment]
Thanks! I thought that I was doing something weird, but couldn't figure what.
