### ISSUE TITLE
Module not found sentiment_analyzer (Python3.5.2, NLTK3.1)

### ISSUE THREAD

**Issue by njbuch** [nltk/nltk#1289]
This piece of code should, according to my best knowledge, work:

``` python
import nltk.sentiment
nltk.sentiment.util.demo_sent_subjectivity('This is great')
```

c:\users\user\appdata\local\programs\python\python35-32\lib\site-packages\nltk\sentiment\util.py in demo_sent_subjectivity(text)
    598         print('Cannot find the sentiment analyzer you want to load.')
    599         print('Training a new one using NaiveBayesClassifier.')
--> 600         sentim_analyzer = demo_subjectivity(NaiveBayesClassifier.train, True)
    601 
    602     # Tokenize and convert to lower case

c:\users\user\appdata\local\programs\python\python35-32\lib\site-packages\nltk\sentiment\util.py in demo_subjectivity(trainer, save_analyzer, n_instances, output)
    537     :param output: the output file where results have to be reported.
    538     """
--> 539     from sentiment_analyzer import SentimentAnalyzer
    540     from nltk.corpus import subjectivity
    541 

ImportError: No module named 'sentiment_analyzer'

**Comment by fievelk** [comment]
@njbuch Thank you.
The error was in the imports. As stated in the [Package Structure Wiki](https://github.com/nltk/nltk/wiki/Package-Structure), imports from the package should have the form `from nltk.package import name`.

I fixed the problem in #1290.
