### ISSUE TITLE
BrillTagger fails on non-ascii text

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#129]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>
2.0b9

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
Get https://github.com/japerk/nltk-trainer and run &quot;python train_tagger.py --brill mac_morpho&quot;

<b>What is the expected output? What do you see instead?</b>
A successfully trained tagger, with no errors. Instead, get the following output with an exception at the end:
loading nltk.corpus.mac_morpho
51397 tagged sents, training on 51397
training AffixTagger with affix -3 and backoff &lt;DefaultTagger: tag=-None-&gt;
training &lt;class 'nltk.tag.sequential.UnigramTagger'&gt; tagger with backoff &lt;AffixTagger: size=7476&gt;
training &lt;class 'nltk.tag.sequential.BigramTagger'&gt; tagger with backoff &lt;UnigramTagger: size=26085&gt;
training &lt;class 'nltk.tag.sequential.TrigramTagger'&gt; tagger with backoff &lt;BigramTagger: size=15708&gt;
Training Brill tagger on 51397 sentences...
Finding initial useful rules...
    Found 64434 useful rules.
Selecting rules...
Traceback (most recent call last):
  File &quot;train_tagger.py&quot;, line 227, in &lt;module&gt;

  File &quot;/home/jacob/nltk-trainer/nltk_trainer/tagging/training.py&quot;, line 13, in train_brill_tagger
    return trainer.train(train_sents, **kwargs)
  File &quot;/usr/local/lib/python2.6/dist-packages/nltk/tag/brill.py&quot;, line 871, in train
    rule = self._best_rule(train_sents, test_sents, min_score)
  File &quot;/usr/local/lib/python2.6/dist-packages/nltk/tag/brill.py&quot;, line 1017, in _best_rule
    best_rules.sort(key=repr)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 33: ordinal not in range(128)

It appears that the brill tagger sorts rules based on the repr() of the rule, which apparently is assumed to be ascii. I hope there's an equivalent method of sorting that does not require an ascii repr.

This may also be a corpus issue, as I've had no problems training on many of the other corpora, including sinica_treebank and floresta.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=610</p>

**Comment by stevenbird** [comment]
It would be check the new Brill Tagger on non-ascii text (cf https://github.com/nltk/nltk/issues/555).

**Comment by stevenbird** [comment]
Closing, as we don't have capacity to take this on.
