### ISSUE TITLE
NLTK relation extraction

### ISSUE THREAD

**Issue by ghost** [nltk/nltk#1291]
I am trying to extract relations from a text 
the example that is provided in the book uses ieer corpus 
I tried to make it on a single text but it's not working , I am not getting anything
Can anyone help ?

Here is my code :

import nltk
import re
sent = "Barack Obama is the president of America"
tokens = nltk.word_tokenize(sent)
tagged = nltk.pos_tag(tokens)
grammar = r"""
    NP : {<DT|PP\$>?<JJ>_<NN>}
         {<NNP>+}
         {<NN>+}
         }<VBD|IN>+{
  """
cp = nltk.RegexpParser(grammar)
result = cp.parse(tagged)
IN = re.compile(r'._\bin\b(?!\b.+ing)')
headline=["test headline for sentence"]
for i,sent in enumerate(tagged):
    text = nltk.ne_chunk(sent)
    for rel in nltk.sem.relextract.extract_rels('ORG', 'LOC', sent, corpus='ace', pattern=IN):
        print(nltk.sem.rtuple(rel) )

**Comment by alvations** [comment]
Please take a look at https://www.nltk.org/book/ch07.html 

Here's an example:

```python
import nltk
import re

sent = "Barack Obama is the president of America"

# Tokenize and POS tag the sentence 
tokens = nltk.word_tokenize(sent)
tagged_sent = nltk.pos_tag(tokens)

# Chunk the pattern determiner <DT>, 
# followed by noun <NN*> 
# then a prepositional phrase made up of 
# a preposition and proper noun <IN><NNP>+
grammar = "NP: {<DT><NN*>+<IN><NNP>+}"

cp = nltk.RegexpParser(grammar)
print(cp.parse(tagged_sent))
```

[out]:

```
(S
  Barack/NNP
  Obama/NNP
  is/VBZ
  (NP the/DT president/NN of/IN America/NNP))
```
