### ISSUE TITLE
Malt parser not parsing sentences

### ISSUE THREAD

**Issue by Mustufain** [nltk/nltk#1294]
whenever I parse a sentence using malt parser it gives me the following exception:
mp.parse_one(token)

Exception: MaltParser parsing (java -cp D:/Python Files/maltparser-1.8.1\maltparser-1.8.1.jar:D:/Python Files/maltparser-1.8.1\lib\liblinear-1.8.jar:D:/Python Files/maltparser-1.8.1\lib\libsvm.jar:D:/Python Files/maltparser-1.8.1\lib\log4j.jar org.maltparser.Malt -c engmalt.poly-1.7.mco -i C:\Users\MUSTUF~1\AppData\Local\Temp\malt_input.conll.9ck59rmy -o C:\Users\MUSTUF~1\AppData\Local\Temp\malt_output.conll.1j7w_xvw -m parse) failed with exit code 1

**Comment by alvations** [comment]
Are you using Windows? As asked on Stackoverflow, without you telling us what is the code you ran, how you setup the environment, it would be hard for us to help you.

Please follow the instructions on https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software#malt-parser and see whether it works for you. Please also do look at the MaltParser API carefully: http://www.nltk.org/api/nltk.parse.html#module-nltk.parse.malt

Please answer the following question so that we can help you:
- How and where did you download and save the `engmalt.poly-1.7.mco` and `maltparser-1.8.1.jar` files and `maltparser-1.8.1` directory (please give the full path, otherwise do a "print screen" and show where's the path)?
- What is the output of `dir C:\\Users\mustufain\Desktop\Python Files\maltparser-1.8.1\` on the command prompt?
- Do you have `['log4j.jar', 'libsvm.jar', 'liblinear-1.8.jar']` in `C:\\Users\mustufain\Desktop\Python Files\maltparser-1.8.1`?

---

**`TL;DR`** (Only works with `Python3` and work only on your machine, I'm guessing the paths here so it may/may not work):

``` python
import urllib.request
urllib.request.urlretrieve('http://www.maltparser.org/mco/english_parser/engmalt.poly-1.7.mco', 'C:\\Users\mustufain\Desktop\engmalt.poly-1.7.mco')
urllib.request.urlretrieve('http://maltparser.org/dist/maltparser-1.8.1.zip', 'C:\\Users\mustufain\Desktop\maltparser-1.8.1.zip')
zfile = zipfile.ZipFile('C:\\Users\mustufain\Desktop\maltparser-1.8.1.zip')
zfile.extractall('C:\\Users\mustufain\Desktop\maltparser-1.8.1\')
```

Then

``` python
from nltk.parse import malt
mp = malt.MaltParser('C:\\Users\mustufain\Desktop\maltparser-1.8.1\', "C:\\Users\mustufain\Desktop\engmalt.poly-1.7.mco")
mp.parse_one('I shot an elephant in my pajamas .'.split()).tree()
```

**Comment by Mustufain** [comment]
Yes I am using windows I have setup my environment variable by going into my computer properties advanced system protection and then creating a new environmental variable

**Comment by alvations** [comment]
Please show the steps and the PATH that you have set. How did you setup your environment variable. Please shows print-screens like these (http://www.computerhope.com/issues/ch000549.htm) if you're unsure of where you saved your files and which path you're set in your environmental variables. 

Where is the directory located? Where is the `.mco` file located? Have you tired the `TL;DR` answer? Please try that answer and that should solve your problem. 

Also, please do not try to cross-post problems and reply on separated platform, it's getting confusing. Keep it to either github or SO, posting multiple questions will not resolve the problem.
- http://stackoverflow.com/questions/35508230/malt-parser-gives-assertion-error-when-using-it-with-nltk
- http://stackoverflow.com/questions/35528515/malt-parser-gives-an-error-when-parsing-in-nltk
- http://stackoverflow.com/questions/35553897/malt-parser-wont-parse-the-sentences
- http://stackoverflow.com/questions/35490217/error-in-malt-parser-in-python

**Comment by Mustufain** [comment]
![env](https://cloud.githubusercontent.com/assets/17406354/13221190/ffffbef0-d971-11e5-9792-037740477b7f.PNG)

**Comment by Mustufain** [comment]
Here you see I have MALTPARSERHOME and MALT_MODEL environment variable set up.MALTPARSERHOME points to the malt.jar file and MALT_MODEL points to the engmalt-linear-1.7.mco file

**Comment by Mustufain** [comment]
.mco file is located at : D:\Python Files\maltparser-1.7.2
I tried the TL;DR answer it says AttributeError: 'str' object has no attribute 'tag

**Comment by Mustufain** [comment]
dir C:\Users\mustufain\Desktop\Python Files\maltparser-1.8.1\ It says network path was not found

**Comment by alvations** [comment]
Now, we see. You have setup your environment variables wrongly.

You're suppose to point:

`MALT_PARSER` variable to `D:\Python Files\malt-parser-1.7.2\`

and

`MALT_MODEL` variable to an `.mco` file. You can download them from www.maltparser.org/mco/english_parser/engmalt.html, right-click on `engmalt.poly-1.7.mco` and save as. Then set the `MALT_MODEL` variable to the path where you have saved `engmalt.poly-1.7.mco`. 

---

I think you're using an outdated version of NLTK. Please update your NLTK. Download from https://pypi.python.org/pypi/nltk and reinstall.

What is the output of:

``` python
import nltk
print nltk.__version__
```

Please please read the following carefully to know how NLTK interfaces MaltParser, otherwise we can't help much:
- https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software#malt-parser
- http://www.nltk.org/api/nltk.parse.html#module-nltk.parse.malt

---

BTW, did you really try this code in `Python3`:

``` python
import urllib.request
urllib.request.urlretrieve('http://www.maltparser.org/mco/english_parser/engmalt.poly-1.7.mco', 'C:\Users\mustufain\Desktop\engmalt.poly-1.7.mco')
urllib.request.urlretrieve('http://maltparser.org/dist/maltparser-1.8.1.zip', 'C:\Users\mustufain\Desktop\maltparser-1.8.1.zip')
zfile = zipfile.ZipFile('C:\Users\mustufain\Desktop\maltparser-1.8.1.zip')
zfile.extractall('C:\Users\mustufain\Desktop\maltparser-1.8.1\')
from nltk.parse import malt
mp = malt.MaltParser('C:\Users\mustufain\Desktop\maltparser-1.8.1\', "C:\Users\mustufain\Desktop\engmalt.poly-1.7.mco")
mp.parse_one('I shot an elephant in my pajamas .'.split()).tree()
```

Just cut and paste the **FULL** code in the python interpreter, don't just choose the NLTK part. The `urllib.request` part of the code will automatically download and extract it to a the right path and thereafter use the path to setup MaltParser. 

By right, the `malt.MaltParser('C:\\Users\mustufain\Desktop\maltparser-1.8.1\', "C:\\Users\mustufain\Desktop\engmalt.poly-1.7.mco")` line should overwrite all environmental variables since it finds the files before checking the os.environs, see https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py#L62

**Comment by alvations** [comment]
Did any of the solutions work?

**Comment by Mustufain** [comment]
I am using nltk version 3.1

**Comment by Mustufain** [comment]
![error](https://cloud.githubusercontent.com/assets/17406354/13222244/01289f4a-d977-11e5-908b-fa7627cf98ca.PNG)

**Comment by Mustufain** [comment]
This is the path to my jar file:![path](https://cloud.githubusercontent.com/assets/17406354/13222342/7fa0843c-d977-11e5-90b0-853b51a54788.PNG)

**Comment by Mustufain** [comment]
![mco](https://cloud.githubusercontent.com/assets/17406354/13222377/a194e56a-d977-11e5-8cd9-672a3bed93f8.PNG)

**Comment by osamamukhtar11** [comment]
![capture](https://cloud.githubusercontent.com/assets/13291427/13222587/6b2ccd46-d9a2-11e5-9263-b65c16895e56.PNG)
Having similar problem using MaltParser. Parser fails with exit code 1

**Comment by Mustufain** [comment]
![error](https://cloud.githubusercontent.com/assets/17406354/13223724/6bc53b3c-d97d-11e5-9a68-b66b0a6eeac3.PNG)
This is the error I am getting after trying out all the solutions

**Comment by alvations** [comment]
Have you installed Java as per https://java.com/en/download/help/windows_manual_download.xml ? Can you try using MaltParser without NLTK http://www.maltparser.org/userguide.html#startusing ? Until you get the configs right in MaltParser, the NLTK API won't work.

**Comment by Mustufain** [comment]
yes I have java installed

**Comment by alvations** [comment]
I am going to hijack a windows computers and show the setup in print-screens. If the solution don't work for you then, I'm afraid someone else should help the both of you with the problem. My knowledge is limited, so sorry. Please wait for answers from the other devs/users.

First follow these screen shots to

**Install Anaconda + Python + Pip (DO NOT INSTALL NLTK FIRST!!)**

From the link: https://www.continuum.io/downloads#_windows

![screenshot 3](https://cloud.githubusercontent.com/assets/1050316/13226755/7e9eb24a-d993-11e5-9e17-1e383c48696c.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/1050316/13226756/7ebc80fe-d993-11e5-87c9-ba57c9c9edd0.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/1050316/13226758/7eccc112-d993-11e5-88e5-f6491831fbc2.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/1050316/13226757/7ecb32a2-d993-11e5-80ca-539a025d7436.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/1050316/13226759/7ed27260-d993-11e5-8314-0ce16959a6a0.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/1050316/13226760/7ed4c56a-d993-11e5-862f-a4af0d5c1884.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/1050316/13226761/7ee038aa-d993-11e5-902d-6d7440138a26.png)
![screenshot 10](https://cloud.githubusercontent.com/assets/1050316/13226762/7ee18c5a-d993-11e5-96c2-ebbad6dcde7e.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/1050316/13226764/7eec1a3a-d993-11e5-92ed-7c95db7de9c2.png)
![screenshot 12](https://cloud.githubusercontent.com/assets/1050316/13226763/7eea32b0-d993-11e5-91f8-67ea5b7c399d.png)
![screenshot 13](https://cloud.githubusercontent.com/assets/1050316/13226765/7ef4d76a-d993-11e5-8c17-fa0b2cb26939.png)
![screenshot 14](https://cloud.githubusercontent.com/assets/1050316/13226766/7efbba30-d993-11e5-9776-9a50529a2e8b.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/1050316/13226767/7f00a6c6-d993-11e5-8ec4-2204009712f9.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/1050316/13226768/7f0225dc-d993-11e5-857a-7d5d22519d69.png)
![screenshot 17](https://cloud.githubusercontent.com/assets/1050316/13226769/7f08fdee-d993-11e5-8383-55d88c7b3669.png)
![screenshot 18](https://cloud.githubusercontent.com/assets/1050316/13226770/7f12525e-d993-11e5-8046-fe3815c954d2.png)
![screenshot 19](https://cloud.githubusercontent.com/assets/1050316/13226771/7f18744a-d993-11e5-98de-bc1e43a6f896.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/1050316/13226772/7f1a1c00-d993-11e5-80af-7d69f8f692f1.png)
![screenshot 21](https://cloud.githubusercontent.com/assets/1050316/13226773/7f1e59f0-d993-11e5-925e-aa8da60392f6.png)
![screenshot 22](https://cloud.githubusercontent.com/assets/1050316/13226775/7f3996b6-d993-11e5-9f92-0d5d9fb76c58.png)
![screenshot 1](https://cloud.githubusercontent.com/assets/1050316/13226774/7f297074-d993-11e5-8f3d-1b6867277da2.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/1050316/13226776/7f3ca7a2-d993-11e5-950a-41814cedd7a3.png)

---

**Now install Git**

From link: https://git-scm.com/download/win

![screenshot 23](https://cloud.githubusercontent.com/assets/1050316/13226991/b0794ffe-d994-11e5-9e0d-eae013133983.png)
![screenshot 24](https://cloud.githubusercontent.com/assets/1050316/13226992/b07db2ba-d994-11e5-9ee7-3b7cb9fbd16c.png)
![screenshot 25](https://cloud.githubusercontent.com/assets/1050316/13226993/b07e78b2-d994-11e5-9c92-fa7316233345.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/1050316/13226994/b081fdfc-d994-11e5-8794-efc7bfaf5fb7.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/1050316/13226995/b085af10-d994-11e5-82b6-e38e7a606cf3.png)
![screenshot 28](https://cloud.githubusercontent.com/assets/1050316/13226996/b08a126c-d994-11e5-8e56-a8dc62c3ddae.png)
![screenshot 29](https://cloud.githubusercontent.com/assets/1050316/13226997/b08e67ae-d994-11e5-89bc-cb57b9abb5eb.png)
![screenshot 30](https://cloud.githubusercontent.com/assets/1050316/13226998/b093e544-d994-11e5-86eb-2c377a34c164.png)
![screenshot 31](https://cloud.githubusercontent.com/assets/1050316/13226999/b0972a06-d994-11e5-8939-ee572a0989c2.png)
![screenshot 32](https://cloud.githubusercontent.com/assets/1050316/13227000/b09b4974-d994-11e5-89ec-c961392be169.png)
![screenshot 33](https://cloud.githubusercontent.com/assets/1050316/13227001/b09f989e-d994-11e5-8045-8cb2c57b44cc.png)
![screenshot 34](https://cloud.githubusercontent.com/assets/1050316/13227002/b0a44164-d994-11e5-8416-ccbdf36b5c12.png)
![screenshot 35](https://cloud.githubusercontent.com/assets/1050316/13227003/b0a7b498-d994-11e5-8920-3ab0b8bc3ca8.png)
![screenshot 36](https://cloud.githubusercontent.com/assets/1050316/13227004/b0aefa82-d994-11e5-9854-0f59f89b517b.png)
![screenshot 37](https://cloud.githubusercontent.com/assets/1050316/13227005/b0b04f54-d994-11e5-9c5c-95ba835f6044.png)
![screenshot 38](https://cloud.githubusercontent.com/assets/1050316/13227007/b0b81b3a-d994-11e5-8624-a92eba723083.png)
![screenshot 39](https://cloud.githubusercontent.com/assets/1050316/13227006/b0b7ed40-d994-11e5-9971-083b0700db9d.png)
![screenshot 40](https://cloud.githubusercontent.com/assets/1050316/13227008/b0bc4ba6-d994-11e5-9151-219f92a01c9c.png)

---

**Now install NLTK**:

![screenshot 41](https://cloud.githubusercontent.com/assets/1050316/13227121/5d651810-d995-11e5-936e-e3b4642bef74.png)
![screenshot 42](https://cloud.githubusercontent.com/assets/1050316/13227120/5d64d06c-d995-11e5-8ded-04987d597615.png)
![screenshot 43](https://cloud.githubusercontent.com/assets/1050316/13227122/5d68d1b2-d995-11e5-98e1-6c1a9066d009.png)
![screenshot 44](https://cloud.githubusercontent.com/assets/1050316/13227123/5d6d157e-d995-11e5-958b-b82cc0eb8825.png)
![screenshot 45](https://cloud.githubusercontent.com/assets/1050316/13227124/5d70b314-d995-11e5-9307-8c7c32ce6774.png)
![screenshot 46](https://cloud.githubusercontent.com/assets/1050316/13227125/5d747e04-d995-11e5-8850-d5268949b068.png)

---

**Now install Java**

From link: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

![screenshot 47](https://cloud.githubusercontent.com/assets/1050316/13227216/e6061566-d995-11e5-9556-e47804b629d1.png)
![screenshot 48](https://cloud.githubusercontent.com/assets/1050316/13227217/e60a34ca-d995-11e5-96d2-219a9eec7937.png)
![screenshot 49](https://cloud.githubusercontent.com/assets/1050316/13227218/e60baa80-d995-11e5-8514-7b684a6a3c63.png)
![screenshot 50](https://cloud.githubusercontent.com/assets/1050316/13227219/e60f57de-d995-11e5-89b5-bbe53352cbae.png)
![screenshot 51](https://cloud.githubusercontent.com/assets/1050316/13227220/e613fdca-d995-11e5-965e-0414fe1c5e99.png)
![screenshot 52](https://cloud.githubusercontent.com/assets/1050316/13227221/e6176d48-d995-11e5-99bb-eba404af7375.png)

---

Now run the code:

**Comment by Mustufain** [comment]
ok waiting for it

**Comment by alvations** [comment]
Okay after much debugging, the problem lies in how classpath in Java command is OS dependent.

**Comment by Mustufain** [comment]
so what is the solution

**Comment by alvations** [comment]
If you need the solution "right now":

```
pip install -U https://github.com/nltk/nltk/archive/develop.zip
```

Then:

``` python
import urllib.request
import zipfile
urllib.request.urlretrieve(r'http://www.maltparser.org/mco/english_parser/engmalt.poly-1.7.mco', r'C:\Users\Thu\Desktop\engmalt.poly-1.7.mco')
urllib.request.urlretrieve(r'http://maltparser.org/dist/maltparser-1.8.1.zip', r'C:\Users\Thu\Desktop\maltparser-1.8.1.zip')
zfile = zipfile.ZipFile(r'C:\Users\Thu\Desktop\maltparser-1.8.1.zip')
zfile.extractall(r'C:\Users\Thu\Desktop\maltparser-1.8.1')

from nltk.parse import malt
mp = malt.MaltParser(r'C:\Users\Thu\Desktop\maltparser-1.8.1',  r'C:\Users\Thu\Desktop\engmalt.poly-1.7.mco')
mp.parse_one('I shot an elephant in my pajamas .'.split()).tree()
```

[out]:

![screenshot 58](https://cloud.githubusercontent.com/assets/1050316/13228267/4dcac3a4-d99b-11e5-8490-ef45939fc382.png)

**Comment by alvations** [comment]
Patched on #1295.

**Comment by alvations** [comment]
@Mustufain , @osamamukhtar11  did the solution work?

**Comment by osamamukhtar11** [comment]
Unfortunately, it didn't. 😞

**Comment by alvations** [comment]
Did you follow the full solution? Including the steps to setup python and NLTK in powershell and  `pip install -U https://github.com/nltk/nltk/archive/develop.zip` ?

**Comment by osamamukhtar11** [comment]
Yes. Nltk Waa uninstalled and reinstalled successfully.

**Comment by alvations** [comment]
With `pip install -U https://github.com/nltk/nltk/archive/develop.zip` on Windows Powershell? Or using the installer? Please don't use the `.exe` installer, it won't work. And if you're using IDLE, you have to do a lot more setup. Follow the steps to use Conda + Python + NLTK in powershell. 

I've verified that the Conda + Python+Git+Java installation steps, and pip installation for NLTK in powershell works for Windows 10.

**Comment by osamamukhtar11** [comment]
I used pip command.

**Comment by alvations** [comment]
Could you post the traceback error you're getting?  If possible print-screens of why it's not working for you will help us debug the problem better.

**Comment by osamamukhtar11** [comment]
Okay. I will post it as soon as I get to my PC. Thank you very much for
your concern.

**Comment by freytheviking** [comment]
Hello,

I was wondering if we could re-start the "AssertionError" conversation that was started here: 

http://stackoverflow.com/questions/35508230/malt-parser-gives-assertion-error-when-using-it-with-nltk

I followed all the steps, downloaded files, unzipped the files, set up path variables for "MALT_PARSER" and "MALT_MODEL" and even changed the code in the find_maltparser function in malt.py:

![image](https://cloud.githubusercontent.com/assets/16825648/14114554/fa8736a0-f59c-11e5-8963-230ff7be3d75.png)

Still not working though. Below is my simple few lines of code used to create a malt parser object: 

![image](https://cloud.githubusercontent.com/assets/16825648/14114657/64efffb8-f59d-11e5-9890-2eefc44d765e.png)

and the following error:

![image](https://cloud.githubusercontent.com/assets/16825648/14114669/7aece434-f59d-11e5-8714-e5a9b746d19a.png)

Any ideas what I am missing?

**Comment by alvations** [comment]
@freytheviking which link did you use to download the MaltParser? Did you follow the steps on https://gist.github.com/alvations/0ed8641d7d2e1941b9f9 ? 

Try the "cheater" method and see whether it works: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9#step-5a-install-maltparser-the-cheater-way

**Comment by freytheviking** [comment]
@alvations That worked in creating the Malt Parser Object! However, I'm getting another error now :-(:

![image](https://cloud.githubusercontent.com/assets/16825648/14116008/5c4fb384-f5a3-11e5-9c32-474da6380eee.png)

Any quick ideas?

**Comment by alvations** [comment]
That looks like some failure on Java command. Are you using Java 8? How did you install Java? 

Try to check whether MaltParser work on it own (outside of NLTK)?

**Comment by freytheviking** [comment]
@alvations I got it to work. I just had to update nltk. Thanks a lot for the help!

**Comment by alvations** [comment]
Anyone else having the same issue with the updated `nltk` v3.2.1 ? 

@stevenbird Otherwise, i think it's safe to close this =)

**Comment by stevenbird** [comment]
@alvations, thanks for going beyond the call of duty here!
