### ISSUE TITLE
panlex_lite 404 

### ISSUE THREAD

**Issue by henryon** [nltk/nltk#1297]
I am still get error, refer below log.
Any update documents or something else? Thanks 
/usr/local/bin/python2.7 -m nltk.downloader -q all -d /usr/local/share/nltk_data
[nltk_data] Error downloading u'panlex_lite' from
[nltk_data] [nltk_data] pages/packages/corpora/panlex_lite.zip>: HTTP Error
[nltk_data] 404: Not Found

**Comment by alvations** [comment]
Wait for NLTK v3.2 and please see extensive discussion on https://github.com/nltk/nltk/issues/1283
