### ISSUE TITLE
stanford parser setup error

### ISSUE THREAD

**Issue by sat230594** [nltk/nltk#1298]
Hi,
i am using the following code to parse a sentence using stanford parser and for setting the variables

import os
java_path = "C:/Program Files/Java/jdk1.8.0_60"
os.environ['JAVAHOME'] = java_path
os.environ['CLASSPATH'] ='C:\Users\ASUS\Downloads\stanford-parser-full-2015-12-09\stanford-parser-full-2015-12-09'
os.environ['STANFORD_MODELS'] = 'C:\Users\ASUS\Downloads\stanford-parser-full-2015-12-09\stanford-parser-full-2015-12-09'

from nltk.parse.stanford  import StanfordDependencyParser 

dep_parser = StanfordDependencyParser(model_path='edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz' )

sentences = dep_parser.raw_parse_sents(["""

The product was old but it was good.
An excellent product packed very well with a very prompt delivery !
    """])
print (str (sentences))

for line in sentences:
    for sentence in line:
        sentence.draw()

But I am getting the following error

Traceback (most recent call last):
  File "C:/Users/ASUS/PycharmProjects/untitled2/parse.py", line 11, in <module>
    dep_parser = StanfordDependencyParser(model_path='edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz' )
  File "C:\Python34\lib\site-packages\nltk\parse\stanford.py", line 61, in **init**
    key=lambda model_name: re.match(self._MODEL_JAR_PATTERN, model_name)
TypeError: unorderable types: NoneType() > NoneType()

Please help me 

thanks

**Comment by alvations** [comment]
@sat230594 please take a look at: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9

**Comment by alvations** [comment]
@sat230594 are you still having problems after following the instructions from the github gist?
