### ISSUE TITLE
small bugs in nltk.wordnet_app

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#13]
- page_from_reference(href) - href type is 'str' in a docstring but href.word is accessed in the body of the function;
- page_from_reference, line 789: I think it is better not to rely on w being defined there (it leaks from list comprehension but this will gone in python 3);
- get_static_page_by_path, line 834 - the code with 'f=open(..)' is unreachable;

**Comment by stevenbird** [comment]
I agree -- this is a mess, and its not immediately obvious how to fix them.

**Comment by alvations** [comment]
@fcbond is this issue still valid for the latest version of the NLTK API to wordnet?

**Comment by alvations** [comment]
This issue seems to be invalid for the latest WordNet + Open Multilingual WordNet interface.
