### ISSUE TITLE
Last stanford-pos-tagger (2015-12-09) jar problem

### ISSUE THREAD

**Issue by nanarth** [nltk/nltk#1304]
Hello,

First I'm really new to nltk and what i learn is amazing, so really thank you for this great piece of software.

I'm trying to use stanford-pos-tagger, and the last version seems to be currently uncompatible with nltk.

The problem is related in this stackoverflow post:
http://stackoverflow.com/questions/34361725/nltk-stanfordnertagger-noclassdeffounderror-org-slf4j-loggerfactory-in-windo/34916721#34916721

This version needs 2 additional jars in the `CLASSPATH`: slf4j-api and slf4j-simple. The problem is that those jars are not loaded and it is impossible the load those jars without modifying nltk. Why ? because when launching the stanford jar, nltk resets the classpath to keep only one jar: the stanford one, it removes all other jars, even the jars specified in the classpath. Consequently there is no way to add slf4j-api and slf4j-simple to the classpath. 

Is there any particular reason to always reset the classpath? I suppose, classpath is cleared to avoid dependency problems, but since stanford jars used to have no dependencies at all would it be possible to disable this feature. Like proposed here: http://stackoverflow.com/a/34916721/3256942 ?

Have a good day !!!

**Comment by alvations** [comment]
Please take a look at https://gist.github.com/alvations/e1df0ba227e542955a8a

**`TL;D12R`**

On Windows Powershell:

```
set CLASSPATH=%CLASSPATH%;C:\some\path\to\stanford-ner\stanford-ner.jar
set STANFORD_MODELS=%STANFORD_MODELS%;C:\some\path\to\stanford-ner\classifiers
```

Or Linux terminal:

```
export STANFORDTOOLSDIR=/home/some/path/to/stanfordtools/
export CLASSPATH=$STANFORDTOOLSDIR/stanford-ner-2015-12-09/stanford-ner.jar
export STANFORD_MODELS=$STANFORDTOOLSDIR/stanford-ner-2015-12-09/classifiers
```

Then:

``` python
>>> from nltk.internals import find_jars_within_path
>>> from nltk.tag import StanfordNERTagger
>>> st = StanfordNERTagger('english.all.3class.distsim.crf.ser.gz') 
# Note this is where your stanford_jar is saved.
# We are accessing the environment variables you've 
# set through the NLTK API.
>>> print st._stanford_jar
/home/alvas/stanford-ner-2015-12-09/stanford-ner.jar
>>> stanford_dir = st._stanford_jar.rpartition("\\")[0] # windows
# Note in linux you do this instead: 
>>> stanford_dir = st._stanford_jar.rpartition('/')[0] # linux
# Use the `find_jars_within_path` function to get all the
# jar files out from stanford NER tool under the libs/ dir.
>>> stanford_jars = find_jars_within_path(stanford_dir)
# Put the jars back into the `stanford_jar` classpath.
>>> st._stanford_jar = ':'.join(stanford_jars) # linux
>>> st._stanford_jar = ';'.join(stanford_jars) # windows
>>> st.tag('Rami Eid is studying at Stony Brook University in NY'.split())
[(u'Rami', u'PERSON'), (u'Eid', u'PERSON'), (u'is', u'O'), (u'studying', u'O'), (u'at', u'O'), (u'Stony', u'ORGANIZATION'), (u'Brook', u'ORGANIZATION'), (u'University', u'ORGANIZATION'), (u'in', u'O'), (u'NY', u'O')]
```

This was resolved in #1280, #1281, #1292

**Comment by nanarth** [comment]
Thank you very much, sorry for the noise

**Comment by alvations** [comment]
@nanarth did the solution work?

**Comment by ClaudeCoulombe** [comment]
The best thing to do it simply to download the latest version of the Stanford POS tagger where the dependency problem is now fixed (March 2018).

    wget https://nlp.stanford.edu/software/stanford-postagger-full-2017-06-09.zip
