### ISSUE TITLE
[patch] implement span_tokenize() for Treebank word tokenizer

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#131]
The Treebank word tokenizer doesn't implement span_tokenize() yet. This patch adds it and re-implements tokenize() in terms of it. Full disclosure: I did some limited testing to see if performance was affected, and it seems the new method is maybe 25% slower.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=614</p>

**Comment by purohit** [comment]
Could someone please integrate this patch in? I also find it strange that the Treebank word tokenizer doesn't implement span_tokenize. His patch is a great addition.

**Comment by vsocrates** [comment]
Has this been implemented? I don't see it in the documentation, but there isn't any resolution here? Agree that it would be super useful.

**Comment by alvations** [comment]
c.f. #78

**Comment by alvations** [comment]
Resolved in #1710
