### ISSUE TITLE
Stanford NER tagging results differ between JAVA GUI and NLTK

### ISSUE THREAD

**Issue by DerekZH** [nltk/nltk#1311]
Hi there,

For some reason the NER tagging results for my test paragraph differ between JAVA GUI and NLTK's wrapper, even though I used the same trained classifier (english.conll.4class.distsim.crf.ser.gz).  The test sentence I used was:

The studio is super great. **LOCATION LOCATION LOCATION**. 2 blocks from **Union Square**, 1 block from **Chinatown**, right in the middle of restaurants, cafeterias, bars, retail/designer stores. Accessible to bus, train, railcar, hop-on hop-off tour buses.   The place is excellent, the most comfortable bed I have ever stayed at any hotel, (I told **Heather** personally), clean, with all the amenities stated on the listing. Loved it.  **Heather** is always there to help get around town or any other questions you might have.   I would definitely recommend it to my friends and to you, the reader.

The Java GUI picked out all bold instances, while the NLTK wrapper picked out:
great.
LOCATION
LOCATION
LOCATION.
Union
Heather
personally),
listing.
Loved
Heather

Chinatown was not picked out, and there are a few words mistakenly picked out.  A stackoverflow question brought up [the same issue](http://stackoverflow.com/questions/34626555/result-difference-in-stanford-ner-tagger-nltk-python-vs-java).  What is the reason for the difference?  Is there a model parameter that I need to turn on?  

Thank you for any help!

**Comment by alvations** [comment]
Could you post your code in NLTK used to generate the tags? I suspect you did not tokenize your text before feeding it to POS and NER tagger.

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
