### ISSUE TITLE
Cross-Validation support

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#132]
A cross-validation module for all machine learning algorithms would be great. It's a standard procedure to report accuracy/precision/recall after performing cross-validation.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=615</p><hr/><h2>earlier comments</h2>

<p><strong>StevenBird1 said, at 2010-12-22T23:56:58.000Z:</strong></p>

<p>I wonder if there is enough functionality that could be abstracted in order to justify a cross-validation module.  Is there a model we could adapt, perhaps in other machine learning toolkit?  Also, how about discussing the requirements on nltk-dev?</p><p><strong>mcenley said, at 2010-12-23T08:03:28.000Z:</strong></p>

<p>Steven, There should be some functionality for cross validation: k-fold and leave-one-out. You would be a better man to judge "how" to go about it (module or adapting from scikits.learn). It would be great to brainstorm on nltk-dev. Let me know if I should post such a query on nltk-dev.</p>

**Comment by awhillas** [comment]
k-fold and leave-one-out would be handly! What you really want is to give the number of folds to a reader class, which already has the data, and then get an iterator that returns two sentence iterators: one for the leave-one-out sentences and the other for the training folds. The top iterator would rotate the folds.
