### ISSUE TITLE
No module nltk.sentiment

### ISSUE THREAD

**Issue by mattdornfeld** [nltk/nltk#1320]
I'm trying to follow on along with this example http://www.nltk.org/howto/sentiment.html, but there is no nltk.sentiment module. Do I have to install it separately?

**Comment by fievelk** [comment]
@mdornfe1 The `sentiment` package is available since NLTK 3.1, so I think that you probably have an older NLTK release. 

I suggest you to update it and check again. 
You can find installation information here: [Installing NLTK](http://www.nltk.org/install.html)

**Comment by mattdornfeld** [comment]
@fievelk Thanks I fixed it by installing from the git repository. Previously I had installed it from pip. Is the pip package out of date?

**Comment by alvations** [comment]
@mdornfe1 when installing from `pip`. use `pip install -U nltk`. The `-U` parameter would update the repo.
