### ISSUE TITLE
Error in BigramAssocMeasures _contingency?

### ISSUE THREAD

**Issue by melvyniandrag** [nltk/nltk#1323]
Hello, 
Before submitting a pull request I would like to know if this was done deliberately for some reason:

The contingency table in BigramAssocMeasures seems incorrect to me.
When I give a set of identical bigrams, i.e. [(X,X), (X,X), (X,X)] what should the table say?
I think:
n_ii = 3, n_io = 0, n_oi = 0, n_oo = 0.
Instead, we get 3, 1, 1, -1.

This causes the likelihood_ratio and chi_sq tests to fail.

The counts also seem wrong for [(X,X), (X,X), (X,Y)]

In this case we should get the following contingencies:
for (X,X):
2, 1, 0, 0
or
for (X,Y):
1, 2, 0, 0

Bug or feature?

The error[?] is due to word_fd.

**Comment by jnothman** [comment]
It's due to the use of `word_fd` to calculate `n_ix` and `n_xi`, I agree. Go ahead, put together a PR.
