### ISSUE TITLE
Number text representation

### ISSUE THREAD

**Issue by ventice** [nltk/nltk#1325]
Within the framework of the project I am currently working on I have to develop a library that will convert a number to its text representation in Russian and English.
For instance, given the number **1235** the library will output "one thousand two hundred and thirty five" for English and "одна тысяча двести тридцать пять" for Russian.
I can design this library in such a way that it is localizable for any language and language extension grammar files are shipped via nltk_data repository. In the future the reverse process, i.e. parsing of text to number, can also be included within this library which will be a handy tool for discovering numbers in natural language.

Do you think it makes sense to include such a library into NLTK?

**Comment by alvations** [comment]
Maybe you'll fine this helpful: http://pastebin.com/WwFCjYtt 

But i'm not sure whether which module it should go under within NLTK.

**Comment by ventice** [comment]
Looks like I have to make a PR when I have this module ready. For now closing.
