### ISSUE TITLE
Regression in BLEU code

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1328]
It looks like #1319 has caused a new set of regressions.
@josiahwang, @alvations – any input would be appreciated, thanks.

**Comment by alvations** [comment]
@stevenbird I'm recoding the BLEU from scratch with a lot more unit tests. I think that's a more maintainable solution than trying to improve the old one. It will take a while though.

**Comment by alvations** [comment]
@stevenbird I'm checking the cpython code and it seems like the `_normalize` parameter in `fractions.Fraction()` is a new feature that's only available in Python >3.5, https://hg.python.org/cpython/file/3.5/Lib/fractions.py#l187

The default behavior before python 3.5 is to always normalize:  
- https://hg.python.org/cpython/file/2.7/Lib/fractions.py#l163
- https://hg.python.org/cpython/file/3.4/Lib/fractions.py#l168

And it seems like this feature is not backported in older python versions. We've to come up with something else such that the bleu, smoothing and fractions can handle fringe cases.

**Comment by stevenbird** [comment]
I see, thanks @alvations – sorry to hear this is complicated!

**Comment by alvations** [comment]
I've got the `_normalize` parameter to work by overloading the class. And some `try-except` tricks will be needed after the imports to use the overloaded class. 

``` python
try:
    fractions.Fraction(0, 1000, _normalize=False)
    from fractions import Fraction
except TypeError:
    class Fraction(fractions.Fraction):
        def __new__(cls, numerator=0, denominator=None, _normalize=True):
            self = super(Fraction, cls).__new__(cls, numerator, denominator)
            if not _normalize:
                self._numerator = numerator
                self._denominator = denominator
            return self
```

But I think it's best to revert to the BLEU without the `_normalize` first, then write the necessary tests first and patch the code with the overloaded `Fraction` to validate the tests.

**Comment by alvations** [comment]
@stevenbird The CI tests are failing for BLEU again because I think i accidentally merged the code that contains the requires `nltk.compat.Fraction` at https://github.com/nltk/nltk/commit/9b74f56ebe61372cb30bcecf25b28c7b25d5dc87

We should either revert https://github.com/nltk/nltk/commit/9b74f56ebe61372cb30bcecf25b28c7b25d5dc87 or move it forward with #1332. Sorry about the mistake.

**Comment by alvations** [comment]
#1330 and #1488 should resolve this.
