### ISSUE TITLE
NgramModel fails to initialize with specified estimators

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#133]
What version of NLTK are you using?  2.0b9

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
from nltk import *
text = &quot;test&quot;
# Test 1

lmL = NgramModel(1, &quot;test&quot;,nltk.LaplaceProbDist)
# Test 2

lmS = NgramModel(1, &quot;test&quot;,nltk.SimpleGoodTuringProbDist)

<b>What is the expected output? What do you see instead?</b>

Expected:
lmL is initialized to language model using LaPlaceProbDist
Instead:
File &quot;/Library/Python/2.6/site-packages/nltk/model/ngram.py&quot;, line 63, in **init**
    self._model = ConditionalProbDist(cfd, estimator, len(cfd))
  File &quot;/Library/Python/2.6/site-packages/nltk/probability.py&quot;, line 2016, in __init__
    **factory_kw_args)
  File &quot;/Library/Python/2.6/site-packages/nltk/probability.py&quot;, line 884, in **init**
    LidstoneProbDist.**init**(self, freqdist, 1, bins)
  File &quot;/Library/Python/2.6/site-packages/nltk/probability.py&quot;, line 810, in **init**
    'to create it (%d).' % freqdist.N())
ValueError: 
The number of bins in a Laplace distribution (1) must be greater than or equal to
the number of bins in the FreqDist used to create it (4).

Expected:
lmS is initialized to language model using SimplegoodTuringProbDist
Instead:
File &quot;/Library/Python/2.6/site-packages/nltk/model/ngram.py&quot;, line 63, in **init**
    self._model = ConditionalProbDist(cfd, estimator, len(cfd))
  File &quot;/Library/Python/2.6/site-packages/nltk/probability.py&quot;, line 2016, in __init__
    **factory_kw_args)
  File &quot;/Library/Python/2.6/site-packages/nltk/probability.py&quot;, line 1398, in **init**
    'Bins parameter must not be less than freqdist.B()'
AssertionError: Bins parameter must not be less than freqdist.B()
<b>Please use labels and text to provide additional information.</b>

Let me know if I'm doing something wrong. It looks like bins is not getting set when initializing certain estimators? I'm trying this in order to get estimated probs for contexts that are missing in the training set.

All best, thanks,

Peter<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=616</p>

**Comment by alvations** [comment]
This should be outdated given the new Ngram model module #2077 =)
