### ISSUE TITLE
BLEU Issues

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1330]
The BLEU implementation has sort of generated quite a lot of "wack-a-mole" situations where the fringe cases of using BLEU cause errors or unexpected output values from the following issues: #1328 #1288 #1285 #1268 #775 #789 #922 #926 #989 #1172 #1241

To resolve the issues, possibly our best chance is to emulate [`mteval-13a.perl`](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v13a.pl) from @moses-smt. 

As a best practice, it should accompanied with a lot more test cases. 

**Any takers on writing/thinking of test cases?**

Contributors can also try to writing wrapper code or port code to NLTK from the following libraries:
- https://github.com/odashi/mteval
- https://github.com/moses-smt/mosesdecoder/blob/master/mert/sentence-bleu.cpp

**Comment by alvations** [comment]
The "mini-roadmap" would be to:
- #1331: Revert code using `fractions.Fraction._normalize` (from #1319) 
- #1332: Create some sort of `nltk.compat` object to handle `_normalize` parameter in fractions.Fraction for Python < 3.5.
- #1332: Put back the `_normalize` patches in #1319 
- #1332: Write tests with fringe cases 
- #1383 Validate these fringe cases by changing the BLEU implementation accordingly
- #1477 Debug implementation of Chen and Cherry smoothing Method 6. 
- #1488 ~~Write a wrapper for or port `mteval-13a.pl`~~ Read `mteval-13a.pl` outputs and write tests to assert that our implementation corresponds to `mteval-13a.pl`'s implementation.

**Comment by alvations** [comment]
After the mini-roadmap, a wrapper to Moses MERT's BLEU would be great since it's top of the "state-of-art" list in terms of human correlations score as reported in https://www.computing.dcu.ie/~ygraham/graham-acl15.pdf

**Comment by stevenbird** [comment]
+1 to this: "Write a wrapper for or port mteval-13a.pl and write tests to assert that our implementation corresponds to mteval-13a.pl's implementation."

A shortcut would be to save output from `mteval-13a.pl` and test against that.

**Comment by alvations** [comment]
While debugging why Chen and Cherry's method 6 didn't work as expected, it seems like we had an error in the `p_n` indexing at https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L538.

The other smoothing methods were reporting 0.4-ish BLEU scores while method 6 was reporting 0.1801. After changing line [L538](https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L538) to `[0, 1]` instead of `[1, 2]`, the BLEU score further degrades to 0.1546.

From the [paper](http://www.aclweb.org/anthology/W14-3346), method 6 seems to be consistent with other smoothing methods and not showing the big difference we see. I think we have to look more at the implementation so I've updated the "mini-roadmap".

**Comment by alvations** [comment]
@stevenbird I've prepared a dataset taken from WMT15 development set to test against our implementation of BLEUs. Could you help to upload the zipball https://goo.gl/nXjpAF into `nltk_data`? Thanks in advance! Most probably it'll be under the `nltk_data/models/` directory. Then I will integrate our `nltk.translate.bleu_score` doc/unit tests to finish the last step in "fixing BLEU" : 

> Write a wrapper for or port `mteval-13a.pl` and write tests to assert that our implementation corresponds to mteval-13a.pl's implementation.

**Comment by stevenbird** [comment]
@alvations: I've put it in `models/wmt15_eval`.

**Comment by alvations** [comment]
@stevenbird Thanks for added the zipball.

The good news is that our implementation corresponds to `mteval-13a.pl` up to the 4th order of ngram with some floating point discrepancies (possibly also character vs byte-code differences).

**mteval-13a**: `[0.5415, 0.4012, 0.3044, 0.2318, 0.1784, 0.1362, 0.1031, 0.0754, 0.0493]`
**nltk**:            `[0.5385, 0.3992, 0.3035, 0.2317, 0.489, 0.5509, 0.5999, 0.6395, 0.6721]`

But there's something strange happening, with increased order of n-gram, our implementation becomes more optimistic:

``` python
import io

from nltk.data import find
from nltk.translate.bleu_score import modified_precision, brevity_penalty
from nltk.translate.bleu_score import sentence_bleu, corpus_bleu

ref_file = find('models/wmt15_eval/ref.ru')
hyp_file = find('models/wmt15_eval/google.ru')

with io.open(ref_file, 'r', encoding='utf8') as ref_fin:
    with io.open(hyp_file, 'r', encoding='utf8') as hyp_fin:
        # Whitespace tokenize the file.
        # Note: split() automatically strip().
        hypothesis = map(lambda x: x.split(), hyp_fin)
        # Note that the corpus_bleu input is list of list of references.
        references = map(lambda x: [x.split()],ref_fin)
        print corpus_bleu(references, hypothesis, weights=(1.0,))
        print corpus_bleu(references, hypothesis, weights=(1.0/2,)*2)
        print corpus_bleu(references, hypothesis, weights=(1.0/3,)*3)
        print corpus_bleu(references, hypothesis) # default 4-grams.
        print corpus_bleu(references, hypothesis, weights=(1.0/5,)*3)
        print corpus_bleu(references, hypothesis, weights=(1.0/6,)*3)
        print corpus_bleu(references, hypothesis, weights=(1.0/7,)*3)
        print corpus_bleu(references, hypothesis, weights=(1.0/8,)*3)
        print corpus_bleu(references, hypothesis, weights=(1.0/9,)*3)
        print corpus_bleu(references, hypothesis, weights=(1.0/100,)*3)
```

[out]:

```
0.538461538462
0.399178616694
0.303541410857
0.231682569415
0.489024670397
0.550945923714
0.59992009098
0.639487015352
0.672056804752
0.964864967966
```

~~My suspicion is that the smoothing function is overly smoothing.~~ The default for `corpus_bleu` is no smoothing.

**Comment by alvations** [comment]
Ah, found the mistake it's a typo when I simply copied and pasted without changing the order of ngrams:

``` python
        print corpus_bleu(references, hypothesis, weights=(1.0,))
        print corpus_bleu(references, hypothesis, weights=(1.0/2,)*2)
        print corpus_bleu(references, hypothesis, weights=(1.0/3,)*3)
        print corpus_bleu(references, hypothesis) # default 4-grams.
        print corpus_bleu(references, hypothesis, weights=(1.0/5,)*5)
        print corpus_bleu(references, hypothesis, weights=(1.0/6,)*6)
        print corpus_bleu(references, hypothesis, weights=(1.0/7,)*7)
        print corpus_bleu(references, hypothesis, weights=(1.0/8,)*8)
        print corpus_bleu(references, hypothesis, weights=(1.0/9,)*9)
```

mteval-13a: `[0.5415, 0.4012, 0.3044, 0.2318, 0.1784, 0.1362, 0.1031, 0.0754, 0.0493]`
NLTK (no smooth): `[0.5385, 0.3992, 0.3035, 0.2317, 0.1785, 0.1364, 0.1033, 0.0755, 0.0494]`

**Comment by stevenbird** [comment]
Nice work @alvations!
