### ISSUE TITLE
'Text' object has no attribute 'generate'

### ISSUE THREAD

**Issue by SeanPlusPlus** [nltk/nltk#1334]
On page 7 of the hard copy of the book "Natural Language Processing with Python", there is an example of the command:

`>>> text3.generate()`

Using nltk version 3.2 I get the following error:

`AttributeError: 'Text' object has no attribute 'generate'`

The online book [states that this feature will be reinstated in a subsequent version](http://www.nltk.org/book/ch01.html#searching-text).

Which version will this feature be in?

Thanks!

**Comment by ghost** [comment]
I also have this issue and have found nothing to say when it will be reinstated. Very frustrating.

**Comment by alvations** [comment]
`Text.generate()` has been deprecated.
