### ISSUE TITLE
pkg_resources.DistributionNotFound: nltk-contrib==3.1

### ISSUE THREAD

**Issue by adeshgupta** [nltk/nltk#1335]
`Traceback (most recent call last):
  File "/usr/local/bin/nltk-server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: nltk-contrib==3.1
`
While starting the nltk-server with command nltk-server -v 8881 , I get the above error. I have nltk3.1 installed on my ubuntu. Please suggest a solution

**Comment by fysteven** [comment]
Hey, actually I have this problem, too

**Comment by alvations** [comment]
@adeshgupta @fysteven Could you explain how have you installed `nltk` on your machines? 

Also which Ubuntu version are you using? What is the output of this on the command line?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```



It is advisable to use `pip` or `conda` when installing NLTK:

```
pip install -U nltk
```

or with [Anaconda](https://docs.continuum.io/anaconda/install)

```
conda install nltk
```

After `pip` installing, do you still have the problem?

**Comment by alvations** [comment]
@adeshgupta @fysteven please do re-open this issue if you're still having problems with `nltk-contrib` when installing the latest NLTK version.
