### ISSUE TITLE
A probabilistic parsing for CCG

### ISSUE THREAD

**Issue by tanin47** [nltk/nltk#1356]
I'm thinking about implementing a probabilistic parsing for CCG because it might be wanted. It is mentioned in https://github.com/nltk/nltk/wiki/Semantic-Parsing, https://groups.google.com/forum/#!topic/nltk-users/m5rdxSFExF4, and http://stackoverflow.com/questions/26829904/lambda-calculus-representation-in-nltk-ccg
### The API

With semantics:

```
lex = lexicon.fromstring('''
   :- S, NP, N
   She => NP {she} [1.0]
   has => (S\\NP)/NP {\\x y.have(y, x)} [0.5]
   a => NP/N {\\P.exists z.P(z)} [0.6]
   book => N {book}
   ''',
   True)
```

Without semantics:

```
lex = lexicon.fromstring('''
   :- S, NP, N
   She => NP [1.0]
   has => (S\\NP)/NP [1.0]
   a => NP/N
   book => N
   ''',
   False)
```

If `[NUM]` is missing, it means the probability is `1.0`.
### The implementation

A leaf node has been `Token` since #1321 (https://github.com/nltk/nltk/blob/develop/nltk/ccg/lexicon.py#L48). We can simply add a probability field. The probability computation will happen while retrieving a parse. Please note that semantics computation also happens at that stage. Here it is: https://github.com/nltk/nltk/blob/develop/nltk/ccg/chart.py#L261
### Probability computation

I'm a bit out of date in this area, but I think the logarithm of probabilities might make more sense. Because a product of probabilities for a long sentence might become too low to compute. (This probability computation should be refactored in a way that it can be swapped easily)

The results will be sorted based on parses' probabilities.
### Important notes
- There's no probability on the rules. Therefore, if the category assignment (on words) is the same, the probabilities will be equal. This might not make sense. For example, `the weird beautiful woman` might have multiple parses with identical category assignment, but those parses **might** offer different semantics interpretations. Nevertheless, I can add this later. I'll ask Mark Steedman about it.
- There's no such thing as non-probabilistic parsing anymore. That simply means every token's probability is `1.0`.
- This is a part of my master thesis (mentioned here #1313), which is a bit out of date. The end goal is to make the CCG parser work with CCGBank out of the box. Ideally, a user can choose a method to train models from CCGBank. Then, the user can use the parser to parse (probabilistically) an input sentence.

@stevenbird @ewan-klein Would this go along with NLTK's vision/mission? Would it be something we want? Does the API part look ok?

**Comment by stevenbird** [comment]
@tanin47 – sorry for the delay. I think this is promising and worth exploring further. Do you have any proposal about how to estimate the probabilities?

**Comment by tanin47** [comment]
> Do you have any proposal about how to estimate the probabilities?

You mean estimating the prob for each primitive category? If so, then no. I haven't thought of it yet. Let me get back to you on this.

**Comment by mpertierra** [comment]
Any updates on this?

**Comment by tanin47** [comment]
I haven't started on this. Thanks for the ping. I'll estimate the time for this by today.

**Comment by nikhilkul** [comment]
Is this feature coming anytime soon?
