### ISSUE TITLE
ChangeLog date errors

### ISSUE THREAD

**Issue by christophchamp** [nltk/nltk#1357]
Your ChangeLog (https://github.com/nltk/nltk/blob/develop/ChangeLog) appears to have the wrong release dates:

Currently: Version 3.2 2015-03-03
Should be: Version 3.2 2016-03-03

Currently: Version 3.2.1 2015-04-09
Should be: Version 3.2.1 2016-04-09

**Comment by stevenbird** [comment]
Thanks @christophchamp
