### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by abojchevski** [nltk/nltk#1361]
On Travis CI the following error occurs for `Python 3.2.5`
Just by calling `from nltk import download`
Actually it even happens with just `import nltk`

```
Traceback (most recent call last):
  File "/opt/python/3.2.5/lib/python3.2/runpy.py", line 161, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/python/3.2.5/lib/python3.2/runpy.py", line 74, in _run_code
    exec(code, run_globals)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nalaf/download_corpora.py", line 10, in <module>
    from nltk import download
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nltk/__init__.py", line 177, in <module>
    from nltk import ccg, chunk, classify, collocations
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nltk/ccg/__init__.py", line 21, in <module>
    from nltk.ccg.chart import CCGEdge, CCGLeafEdge, CCGChartParser, CCGChart
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nltk/ccg/chart.py", line 338
    if op == u'Leaf':
                   ^
SyntaxError: invalid syntax
```

**Comment by tanin47** [comment]
That's odd. It seems to work on Python 3.5 and 2.7:

```
~ [19:51:19]
$ python3
Python 3.5.1 (default, Jan 22 2016, 08:52:08) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> if u'a' == u'a':
...   print("sdfdsf")
... 
sdfdsf
>>> 
```

and 

```
~ [19:55:40]
$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> if u'a' == u'a':
...   print("SDfsdf")
... 
SDfsdf
>>> 
```

I'll investigate. Maybe something is specific with python 3.2.5

**Comment by tanin47** [comment]
`u'somestring'` is a valid statement for most python versions. The syntax is there in v2+, is removed from 3.0, then is reintroduced again in 3.3.

From https://docs.python.org/release/3.0.1/whatsnew/3.0.html, it says `You can no longer use u"..." literals for Unicode text.`

From https://docs.python.org/release/3.3.0/whatsnew/3.3.html, it says `The u'unicode' syntax is accepted again for str objects.`

I'll find a way to make it compatible to all Python versions.

**Comment by stevenbird** [comment]
We don't support Python 3.0 and 3.1. It's probably time to drop support for 3.2 actually.

**Comment by tanin47** [comment]
Thanks @stevenbird 

@abojchevski I hope you can change the python version. The `u` thing is very strange; Python shouldn't have done this..

**Comment by abojchevski** [comment]
We decided to drop support for Python 3.2 support as well. Thank you for the responses.
