### ISSUE TITLE
FrameNet corpus reader: display sentence with inline target & FE annotations

### ISSUE THREAD

**Issue by nschneid** [nltk/nltk#1370]
Given that lexicographic and full-text annotations are available (#1369), we want a user-friendly way to display them in the console for interactive browsing.

The proposed solution has the following displays:
## Full-text sentence display

Sentences in full-text documents (potentially) contain multiple annotated targets. This display notes which spans are targets and indicates the corresponding annotationSet indices:

```
>>> s
full-text sentence (4097611) in NorthKorea_NuclearCapabilities:


[POS] 14 tags

[POS_tagset] PENN

[text] + [annotationSet]

Therefore , obtaining reliable open source information on such
            ********* ******** ****        ***********
            Getting   Trust    Secr        Information
            [1]       [6]      [5]         [2]

programs is very challenging .
********         ***********
Project          Difficulty
[3] !            [4]
```
- Frame names are truncated to fit the character width of the span.
- Many full-text targets are annotated for the frame only (no FEs; status is `UNANN`). These are indicated with a `!` next to the index.

```
>>> fn.ft_sents()[230]
full-text sentence (4164978) in Fires_1:


[POS] 23 tags

[POS_tagset] PENN

[text] + [annotationSet]

Four people have perished so far in the blazes which the
                 ******** ******        ******
                 Death    Contin        Fire_b
                 [1]      [6]           [2]

government says were started intentionally by arsonists over a
********** ****      *******                  *********
Organizati Stat      Setting                  Arson
[3]        [4]       [7] ?                    [5]

week ago .
```
- Targets annotated with Problem LUs are designated with `?`.
## Frame annotation sentence display

Drilling down in the full-text sentence—or at the top level of a lexicographic exemplar sentence, which only has one target in the first place—we see the full sentence, now with one target and any FEs indicated:

```
>>> s.annotationSet[4]
annotation set (6528787):

[status] MANUAL

[LU] (6573) challenging.a in Difficulty

[frame] (375) Difficulty

[GF] 2 relations

[PT] 2 phrases

[text] + [Target] + [FE] + [Adj]

Therefore , obtaining reliable open source information on such
            ---------------------------------------------------
            Activity

programs is very challenging .
-------- ^^ ---- ***********
         co Degr
 (co=cop, Degr=Degree)
```
- FE names are truncated to fit, with the expansion shown after the sentence in parentheses. The frame name is not shown inline.
- LUs of certain parts-of-speech may be annotated with special FE-extrinsic spans such as `Cop` (copula), `Supp` (support), `Ctrlr` (controller), `Gov` (governor), and `Asp` (aspectual particle). See notes in updated code. For the display, these are lowercased and shown beneath a span indicated with `^` characters to distinguish them from FEs. In the above case, the `Adj` layer of challenging.a contains a `Cop` span, displayed in truncated form as `co`.
  - `X` phrase spans (which generally include the target and its FEs) will not be displayed.
- The underlying information in the display comes from a combination of the `text`, `Target`, `FE`, and `Adj` attributes of the sentence object, and is therefore preceded with `[text] + [Target] + [FE] + [Adj]`.
### Denoted FEs

```
>>> s.annotationSet[2]
annotation set (6528785):

[status] MANUAL

[LU] (12537) information.n in Information

[frame] (1591) Information

[GF] 2 relations

[PT] 2 phrases

[text] + [Target] + [FE]

Therefore , obtaining reliable open source information on such
                               ----------- =========== --------
                               Means_of_ga Information Topic

programs is very challenging .
--------

 (Means_of_ga=Means_of_gathering)
```
- If an FE span includes the target, the overlapping portion is indicated with `=` underlining rather than `*`.
  - There are rare cases in which the FE span and the target span are not identical; these are handled but not shown here. 
### Null instantiations

```
>>> s.annotationSet[1]
annotation set (6528784):

[status] MANUAL

[LU] (7499) obtain.v in Getting

[frame] (179) Getting

[GF] 1 relation

[PT] 1 phrase

[text] + [Target] + [FE]

Therefore , obtaining reliable open source information on such
            ********* -----------------------------------------
                      Theme

programs is very challenging .
--------
         [Recipient:CNI]
```
- NIs are displayed in brackets after the sentence.
### Multiple FE layers

If present, second-layer and even third-layer FE annotations are stored in `.FE2` and `.FE3` attributes, respectively. All FE layers are displayed:

```
>>> fn.ft_sents()[13].annotationSet[6].FE
([(115, 127, 'Place'), (137, 153, 'Product')], {})
>>> fn.ft_sents()[13].annotationSet[6].FE2
([(115, 127, 'Producer')], {})
>>> fn.ft_sents()[13].annotationSet[6]
annotation set (6528894):

[status] MANUAL

[LU] (7523) produce.v in Manufacturing

[frame] (408) Manufacturing

[GF] 2 relations

[PT] 2 phrases

[text] + [Target] + [FE] + [FE2]

However , all countries known to have successfully acquired





nuclear weapons have done so primarily on the basis of





indigenously produced fissile material .
------------ ******** ----------------
Place                 Product
------------
Producer


```
### `UNANN` annotationSets

```
>>> s.annotationSet[3]
annotation set (6528786):

[status] UNANN

[LU] (10724) program.n in Project

[frame] (1158) Project

[GF] 0 relations

[PT] 0 phrases

[text] + [Target] + [FE]

Therefore , obtaining reliable open source information on such



programs is very challenging .
********
```
- Frame annotations with status `UNANN` have a boring display, as they have a target but no FEs.
### Other, Sent layers
- The **Other** layer marks expletive subject spans (`Null`, `Exist`) and relative clause antecedent/relativizer spans (`Ant`, `Rel`). This information can be accessed but is not displayed.
- The **Sent** layer appears to be for flags that help the annotator categorize lexicographic exemplars (e.g., `sense1`, `Metaphor`, `Idiom`, `reexamine`). This information can be accessed but is not displayed.
## POS annotation display

This is always available in `.annotationSet[0]`:

```
>>> s.annotationSet[0]
POS annotation set (6528581) PENN in sentence 4097611:

Therefore , obtaining reliable open source information on such
--------- - --------- -------- ---- ------ ----------- -- ----
rb        , VVG       jj       jj   nn     nn          in jj

programs is  very challenging .
-------- --  ---- ----------- -
nns      VBZ rb   jj          sent
```

**Comment by nschneid** [comment]
Outstanding issue: What to do about LUs with Problem status, which are thus not given an LU definition file (yet may occur in full-text annotation)? Currently displaying the sentence causes warnings and an error:

```
>>> fn.ft_sents()[230]
Duplicate target span (157, 164) in sentence 4097762
Duplicate target span (81, 88) in sentence 4097847
Duplicate target span (201, 208) in sentence 4097847
LU ID not found:  17633
LU ID not found:  17633
LU ID not found:  17633
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nltk/compat.py", line 498, in wrapper
    return method(self).encode('ascii', 'backslashreplace')
  File "/Library/Python/2.7/site-packages/nltk/corpus/reader/framenet.py", line 690, in __repr__
    return self.__str__()
  File "/Library/Python/2.7/site-packages/nltk/compat.py", line 498, in wrapper
    return method(self).encode('ascii', 'backslashreplace')
  File "/Library/Python/2.7/site-packages/nltk/compat.py", line 486, in wrapper
    return transliterate(method(self))
  File "/Library/Python/2.7/site-packages/nltk/corpus/reader/framenet.py", line 688, in __str__
    return self._str()
  File "/Library/Python/2.7/site-packages/nltk/corpus/reader/framenet.py", line 664, in _str
    outstr = _pretty_fulltext_sentence(self)
  File "/Library/Python/2.7/site-packages/nltk/corpus/reader/framenet.py", line 251, in _pretty_fulltext_sentence
    outstr += sent._ascii() # -> _annotation_ascii()
  File "/Library/Python/2.7/site-packages/nltk/corpus/reader/framenet.py", line 392, in _annotation_ascii
    return _annotation_ascii_frames(sent)
  File "/Library/Python/2.7/site-packages/nltk/corpus/reader/framenet.py", line 410, in _annotation_ascii_frames
    overt.append((j,k,aset.LU.frame.name,indexS))
AttributeError: 'NoneType' object has no attribute 'frame'
```

**Comment by nschneid** [comment]
Workaround for Problem LUs: when they are encountered, add a placeholder to the LU index that holds its name and frame. However, the placeholder LU is only accessible by its ID; it is not listed in the frame or searchable by name with `lus()`:

```
>>> s = fn.ft_sents()[230]
>>> s.annotationSet[7].LU
lexical unit (17633): start.v


[frame] Setting_fire(283)

[status] Problem
>>> fn.lu(17633) is s.annotationSet[7].LU
True
>>> fn.lu(17633) in fn.lus()
False
>>> fn.lu(17633) in fn.lus("start.v")
False
>>> 'start.v' in fn.lu(17633).frame.lexUnit.keys()
False
```

In the full-text sentence display, the Problem LU is flagged with `?` as described above.

**Comment by alvations** [comment]
@nschneid Sorry in advance for the multiple comments. 

Are these issues resolved in the overhaul?

 - #1370
 - #1371
 - #1372
 - #1373
 - #1374
 - #1377
 - #1378
 - #1379

Thanks again for the better Framenet interface!!

**Comment by nschneid** [comment]
Closing this issue and #1378, which were addressed by the overhaul. Leaving the other issues open as reminders for future enhancements.
