### ISSUE TITLE
a bug when using StanfordSegmenter in windows

### ISSUE THREAD

**Issue by nsndimt** [nltk/nltk#1375]
nltk version:3.2.1 jdk 1.8.0_77
when using StanfordSegmenter in windows with all arguments set properly,i got an java error message:Could not find or load main class edu.stanford.nlp.ie.crf.CRFClassifier
i manage to figure out the cause:
line 63 in nltk\tokenize\stanford_segmenter.py  
self._stanford_jar = ':'.join(
            [_ for _ in [stanford_segmenter, slf4j] if not _ is None])
should be
self._stanford_jar = ';'.join(
            [_ for _ in [stanford_segmenter, slf4j] if not _ is None])
this is because in linux java -cp option use : to separate while in windos java -cp option use ;

**Comment by alvations** [comment]
@nsndimt Do these instructions on [installing NLTK and Java / Stanford tools](https://gist.github.com/alvations/0ed8641d7d2e1941b9f9) help to resolve your problem?

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
