### ISSUE TITLE
POS-Tagging German text with a ClassifierBasedGermanTagger

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#138]
A classifier based German part-of-speech tagger. It has an accuracy of 96.09% after being trained on 90% of the German TIGER corpus. The tagger extends the NLTK ClassifierBasedTagger and implements a slightly modified feature detector.

In combination with a brill tagger and evaluated on the TIGER corpus it achieves and overall accuracy of 98%. A full evaluation can be found at

http://experimentallabor.de/?p=207

The tagger uses a modified feature detector granting German language features a much higher relevance in the returned feature set. The shape identifier now includes umlauts and scharf s boosting the accuracy up by over 4%.  Further enhancements on the feature set (adding a prefix feature) result in the mentioned accuracy of over 96%.

Full documentation on the modifications can be found at

http://experimentallabor.de/?p=162

The Tagger itself can be found at

https://github.com/ptnplanet/NLTK-Contributions

and is licensed under an Apache 2.0 licence enabling easy use with and within the NLTK.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=624</p>

**Comment by stevenbird** [comment]
@ptnplanet would you like to submit a pull request?
