### ISSUE TITLE
Stanford taggers are slow because they launch the JVM whenever they tag something; launching a Java servlet and communicating via TCP would be faster

### ISSUE THREAD

**Issue by ExplodingCabbage** [nltk/nltk#1390]
As noted at http://stackoverflow.com/questions/23322674/how-to-improve-speed-with-stanford-nlp-tagger-and-nltk, NLTK's wrappers for the Stanford taggers are really slow.

@alvations [suggests](http://stackoverflow.com/a/23322996/1709587) batching operations to get around this, but this isn't always convenient. It would be nice to instead be able to [launch a servlet](http://nlp.stanford.edu/software/crf-faq.shtml#cc) and communicate with it via a socket, like [Dat Hoang's Python wrapper for the NER tagger](https://github.com/dat/stanford-ner) (which doesn't seem to work with the latest version of the Stanford taggers, by the way) used to do.

For my own purposes, I've managed to hack together something that seems to work (and doesn't use NLTK) on the `stanford-ner-2015-04-20` release of the Stanford NER tagger. I need to look into the other Stanford taggers, though, and the differences between versions, before I'll have anything ready to contribute to NLTK. I'll try to get round to that soon.

**Comment by dimazest** [comment]
Please have a look to #1249  it uses Stanford's server new http api and is supposed to be fast.

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
