### ISSUE TITLE
Installed nltk with brew on OSX El Capitan and 'word_tokenize' is not found

### ISSUE THREAD

**Issue by shyamalschandra** [nltk/nltk#1391]
I just went through the example on the main page (http://www.nltk.org/).  What am I missing in terms of dependencies?

```
iMe2 nltk $ python nltk.py 
Traceback (most recent call last):
  File "nltk.py", line 1, in <module>
    import nltk
  File "/Users/iMe2/projects/nltk/nltk.py", line 3, in <module>
    tokens = nltk.word_tokenize(sentence)
AttributeError: 'module' object has no attribute 'word_tokenize'
iMe2 nltk $ 
```

Thanks!

**Comment by alvations** [comment]
Change the name of your script/project to something else other than `nltk.py`. The namespaces are clashing. Please take a look at http://stackoverflow.com/questions/1224741/trying-to-import-module-with-the-same-name-as-a-built-in-module-causes-an-import/1224760#1224760

**Comment by alvations** [comment]
@shyamalschandra did changing the name of your script fix your problem?

**Comment by alvations** [comment]
@shyamalschandra did changing the name of your script fix your problem?

**Comment by stevenbird** [comment]
Thanks @alvations, I'm sure this is the issue.
