### ISSUE TITLE
Are there Stanford text-to-sentence functionality in NLTK?

### ISSUE THREAD

**Issue by oleg-kachan** [nltk/nltk#1395]
Unfortunately have not found one, does it present or not?

**Comment by oleg-kachan** [comment]
Stanford splitter seems to be most accurate open-source solution, so I think it should be added to NLTK, if it's not there yet.

![alt text](http://tech.grammarly.com/static/final-results.png)
http://tech.grammarly.com/blog/posts/How-to-Split-Sentences.html

**Comment by dimazest** [comment]
Please have a look to #1249 it should not be difficult to extend that pull request to split text to sentences.

**Comment by sshtomar** [comment]
NLTK newb here.
We want to write an NLTK wrapper for Stanford sentence boundary detection code. Right?

**Comment by dimazest** [comment]
I think so.

It's actually already implemented (but not merged yet) see https://github.com/nltk/nltk/pull/1249/files#diff-3ddcbc41d8654bc0748b8afb087c55aeR299

**Comment by stevenbird** [comment]
@Autodidact24: we're still waiting for some updates to #1249.
