### ISSUE TITLE
Add support "multiple parsing variants" functionality for Stanford Parser [and custom command-line options]

### ISSUE THREAD

**Issue by oleg-kachan** [nltk/nltk#1396]
Stanford Parser is able to do multiple parsing guesses of the same sentence, each parse variant goes along with its log-probability. This is done via _\- printPCFGkBest n_ option in the command line.

I've implemented this by myself for my project by subclassing StanfordParser, adding a key and updated code to build multiple trees from parser raw output.

If NLTK maintainers and users are interested we can generalize and merge this code.

But, more generally I think we should add support for custom command-line options.

What do you think?

**Comment by dimazest** [comment]
Does their http api support this? It would be nice to add support of several parses to #1249.

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
