### ISSUE TITLE
ResolutionProverCommand (and unify) problem

### ISSUE THREAD

**Issue by pedritomelenas** [nltk/nltk#1397]
I have a problem with the `ResolutionProverCommand`. 

```
h = Expression.fromstring("all x.(P(x) | Q(x))")
t= Expression.fromstring("all x.(-P(x) | -Q(x))")
s = Expression.fromstring("exists x.R(x)")
demostracion=ResolutionProverCommand(s,[h,t])
demostracion.prove()
```

Outputs `True`, which shouldn't be the case. If we print the proof with `print(demostracion.proof())`, we get
[1] {-R(z41)}           A 
[2] {P(z43), Q(z43)}    A 
[3] {-P(z45), -Q(z45)}  A 
[4] {}                  (2, 3) 
As you see, the module thinks that the resolvent of [3] and [4] is the empty clause, which is not. The problem seems to be in `unify`. If we define

```
c=Clause([expr("P(x)"),expr("Q(x)")])
cn=Clause([expr("-P(x)"),expr("-Q(x)")])
```

Then `c.unify(cn)` ouputs [{}], the empy clause.

Am I doing something wrong? The problem does not reproduce neither with Tableau nor with Prover9.

Thank you for your great work!

**Comment by ChenxingLi** [comment]
I also have this problem.

**Comment by alvations** [comment]
@pedritomelenas @ChenxingLi can you post the full code that caused the problem as well as the error traceback so that we understand what is the error and can help you better?

**Comment by pedritomelenas** [comment]
@alvations, thanks for answering. The error is easy to reproduce, just use the last part of my message.
 
The problem is that {(not(A) or B), (A or not(B))} should not yield the empty clause, as this set is not inconsistent. If you are about to compute a resolvent in this case, you either stick to A and not(A), or to B and not(B), and you would get two tautologies ((B or not(B)), (A or not(A)), respectively) but not the empty clause. Semantically, observe that the set is satisfiable (set for instance A=true, B=true), and so you cannot deduce the empty clause.

I hope this helps, if not, when I get back home where I have nltk installed in my laptop I will produce more examples.

Thank you!
Pedro

**Comment by alvations** [comment]
@pedritomelenas Having the code and error traceback would expedite the debugging. Thanks in advance!

**Comment by pedritomelenas** [comment]
There is no error message. The output is not correct. 
Thank you,
Pedro

**Comment by pedritomelenas** [comment]
Here is an example
```
from nltk import *
from nltk.inference.resolution import *
expr = Expression.fromstring
c=Clause([expr("P(x)"),expr("-Q(x)")])
cn=Clause([expr("-P(x)")])
c.unify(cn)
```
and the output is `[{-Q(x)}]`, which is fine.
But then with 
```
c=Clause([expr("P(x)"),expr("-Q(x)")])
cn=Clause([expr("-P(x)"),expr("Q(x)")])
c.unify(cn)
```
the output is `[{}]`, which is not fine.

I hope this helps.
Thank you, 
Pedro
