### ISSUE TITLE
AssertionError: Bins parameter must not be less than freqdist.B()

### ISSUE THREAD

**Issue by lucasrodes** [nltk/nltk#1404]
Hi, 
I have been testing the model package for text classifying and it seems to work very good. However, I have been using `LidstoneProbDist` until now and I would like to test the classifier using `WittenBellProbDist`. Nonetheless, I am getting errors and I couldn't find any reference implementing this estimator.  In particular, I have been using:

```
estimator = lambda fdist, bins: LidstoneProbDist(fdist,10) 
lm = NgramModel(2, train, estimator=estimator)
```

which worked pretty fine. Now, I just changed it into:

```
estimator = lambda fdist, bins: WittenBellProbDist(fdist,10) 
lm[categ] = NgramModel(2, train, estimator=estimator)
```

and I get the error:

```
Traceback (most recent call last):
  File "test7.py", line 43, in <module>
    lm[categ] = NgramModel(N, train, estimator=estimator)
  File "/veu4/usuaris30/speech00/.local/lib/python2.7/site-packages/nltk-2.0.4-py2.7.egg/nltk/model/ngram.py", line 107, in __init__
    self._model = ConditionalProbDist(cfd, estimator, len(cfd))
  File "/veu4/usuaris30/speech00/.local/lib/python2.7/site-packages/nltk-2.0.4-py2.7.egg/nltk/probability.py", line 1957, in __init__
    *factory_args, **factory_kw_args)
  File "test7.py", line 42, in <lambda>
    estimator = lambda fdist, bins: WittenBellProbDist(fdist,10) 
  File "/veu4/usuaris30/speech00/.local/lib/python2.7/site-packages/nltk-2.0.4-py2.7.egg/nltk/probability.py", line 1176, in __init__
    'Bins parameter must not be less than freqdist.B()'
AssertionError: Bins parameter must not be less than freqdist.B()
```

Anyone has an idea? Really apreciate your time.

PS: I am using an old version of NLTK (2.0.4), because I was not able to make the package model work with the current version.; Python 2.7.3 and GNU/Linux.

**Comment by iliakur** [comment]
Hi!

The model package has been significantly overhauled due to a ton of bad bugs in the old version (some of which are related to the error you posted). Please try out the new model package from the corresponding [branch](https://github.com/nltk/nltk/tree/model).

Thanks!

**Comment by lucasrodes** [comment]
Hi, thanks for your comment. I tried it, however I could not find documentation on the internet on how to use it (references are welcome).. In particular, I saw that NgramModel has disappeared and BaseNgramModel has appeared...

Thats basically why I am working with the old version, since I have to submit a work and I am time limited. However, I will try to investigate and play with it in the near future once this particular work is finished.

Cheers

**Comment by iliakur** [comment]
The newest version is still in development, so there's no documentation aside from the source and test code, I'm afraid. On the bright side, the code is designed to be **significantly** easier to understand than the old version, so ideally you shouldn't have to worry about sinking in too much time. That being said, all suggestions for how to improve the code and tests are very welcome!

Check out the following folders/files:
- [`nltk/model`](https://github.com/nltk/nltk/tree/model/nltk/model) All files in this folder have to do with the new ngram model. `counter.py` is by far the most important one there, though `ngram.py` is also worth a read.
- I have tried to give a walk-through of how to use the module in [`nltk/test/model.doctest`](https://github.com/nltk/nltk/blob/model/nltk/test/model.doctest). Note that if you try the steps listed in this file in IPython or Jupyter, the print outputs may look different.
