### ISSUE TITLE
bad display of Portuguese example on website page

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#141]
Using current version of NLTK: 2.0b9

On this website page, the Portuguese text is messed up:
http://nltk.googlecode.com/svn/trunk/doc/howto/portuguese_en.html

I took a look at the HTML source. There are two problems with it:
(1) the encoding is ASCII(?!): &lt;?xml version=&quot;1.0&quot; encoding=&quot;ascii&quot; ?&gt;
(2) the entity numbers are wrong. 

For example, this line:

&lt;span class=&quot;pysrc-output&quot;&gt;ptext1: Mem&amp;#151;rias P&amp;#151;stumas de Br&amp;#135;s Cubas (1881)&lt;/span&gt;

should read:

&lt;span class=&quot;pysrc-output&quot;&gt;ptext1: Mem&amp;#243;rias P&amp;#243;stumas de Br&amp;#225;s Cubas (1881)&lt;/span&gt;

I could fix this for you. For instance, I could attach a file where these problems were cleaned up. Just let me know.

Later on the page, there are cases like these:
['o', 'amor', 'da', 'gl\xf3ria', 'era', 'a', 'coisa', 'mais', ...

There are undoubtedly more user-friendly ways to display these strings, but I'm still investigating.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=637</p><hr/><h2>earlier comments</h2>

<p><strong>StevenBird1 said, at 2011-03-07T00:10:45.000Z:</strong></p>

<p>Thank you.  Corrections to the source file would be welcome:
http://nltk.googlecode.com/svn/trunk/nltk/nltk/test/portuguese_en.doctest
</p><p><strong>alanf333 said, at 2011-03-11T01:13:25.000Z:</strong></p>

<p>Replacement of part of the text should be straightforward. However, as I was investigating this, I ran into an error. Executing this line:

ptext1.concordance('olhos')

caused this output:

>>> ptext1.concordance('olhos')
Building index...
Displaying 25 of 138 matches:
De pé , à cabeceira da cama , com os olhos estúpidos , a boca entreaberta , a t
orelhas . Pela minha parte fechei os olhos e deixei - me ir à ventura . Já agor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python26\Lib\site-packages\nltk\text.py", line 314, in concordance
    self._concordance_index.print_concordance(word, width, lines)
  File "C:\Python26\Lib\site-packages\nltk\text.py", line 189, in print_concorda
nce
    print left, word, right
  File "C:\Python26\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xf5' in position 1
: character maps to <undefined>

Apparently, the second character in the third line that would be listed in the concordance for the word 'olhos' is causing a problem. I'll report this as a separate bug.</p><p><strong>alanf333 said, at 2011-03-11T17:24:43.000Z:</strong></p>

<p>Back to the core issue: I'm not sure that simply changing the doctest file will be enough to fix the display on the website unless the XML processing instruction that specifies an ASCII encoding is changed. How is the doctest file being processed to produce the (X)HTML for the website?</p><p><strong>alanf333 said, at 2011-07-17T16:20:03.000Z:</strong></p>

<p>I let this thread drop in March because I was busy with classwork, but now I have some time to revisit it. How would I convert the doctest file to html in order to verify the output? Is there some way I can control the XML processing instruction that specifies an ASCII encoding?</p><p><strong>alanf333 said, at 2011-07-17T16:27:02.000Z:</strong></p>

<p>Note that when one runs the output, the actual runtime display for ptext1 and ptext2 (Windows Vista/Python 2.6/NLTK 2.0b9), as opposed to the way the display is depicted in the HTML, is fine:

>>> from nltk.examples.pt import *
*** Introductory Examples for the NLTK Book ***
Loading ptext1, ... and psent1, ...
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
ptext1: Memórias Póstumas de Brás Cubas (1881)
ptext2: Dom Casmurro (1899)
ptext3: Gênesis
ptext4: Folha de Sau Paulo (1994)
>>> ptext2
<Text: Dom Casmurro (1899)></p>

**Comment by kmike** [comment]
I think the root of the issue is weird portugese_en.doctest encoding. This file is converted to standard utf8 here: https://github.com/kmike/nltk/commit/4e1c4d27dd27700f98500409c3eedcc5024b9486

**Comment by paulproteus** [comment]
I've looked on the web at http://nltk.googlecode.com/svn/trunk/doc/howto/portuguese_en.html and the problem remains. Is it as simple as regenerating that page? (What process controls the generation of those? Since the project no longer uses svn, the appearance of 'svn/trunk' in the URL is troubling.)

**Comment by alexrudnick** [comment]
Hey Asheesh @paulproteus! I think this bug is stale now...

@kmike Closing this because portuguese_en.doctest has been converted to utf-8. (also, we don't have the current doctests up on the web anymore, right? ...)

**Comment by pquentin** [comment]
@alexrudnick Did you forget to close this issue? If not, is there anything else to do?

**Comment by alexrudnick** [comment]
@pquentin I think we're good! Thanks for the bump!
