### ISSUE TITLE
pip download-cache unavailable

### ISSUE THREAD

**Issue by fievelk** [nltk/nltk#1414]
Users that use `pip 8.0.0` and above experience the following issue (especially while running `tox` tests):

```
no such option: --download-cache
ERROR: InvocationError: '/path/nltk/.tox/py34/bin/pip install --download-cache=/path/nltk/.tox/_download scipy scikit-learn'
```

Since `pip 6.0` the `--download-cache` flag used to be deprecated, but could still be used. On the contrary, newer versions of `pip` are not backward compatible with regard to this flag.

**6.0 (2014-12-22)**:

> - **DEPRECATION** `pip install --download-cache` and `pip wheel --download-cache` command line flags have been deprecated and the functionality removed. Since pip now automatically configures and uses it’s internal HTTP cache which supplants the `--download-cache` the existing options have been made non functional but will still be accepted until their removal in pip v8.0. For more information please see https://pip.pypa.io/en/latest/reference/pip_install.html#caching

**8.0.0 (2016-01-19):**

> - **BACKWARD INCOMPATIBLE** Remove the --download-cache which had been deprecated and no-op'd in 6.0.

Since two years passed since the `--download-cache` flag has been deprecated, I suggest to completely remove it from `tox.ini`.

**Comment by stevenbird** [comment]
Thanks @fievelk!
