### ISSUE TITLE
aline breaks in Python 2.7

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1418]
There's a character encoding issue for `metrics.aline` in Python 2.7, as reported by our [CI server](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/testReport/).

**Comment by stevenbird** [comment]
@geoffbacon – would you please take a look at this?

**Comment by fievelk** [comment]
Please refer to the [NLTK Testing](http://www.nltk.org/dev/local_testing.html#writing-tests) guide:

> - Do not write doctests that has non-ascii output (they are not supported in
>   Python 2.x). Incorrect::
> 
> ```
> >>> greeting
> u'Привет'
> ```
> 
>  The proper way is to rewrite such doctest as unittest.
