### ISSUE TITLE
Stanford parser breaks UTF-8 characters

### ISSUE THREAD

**Issue by fluhus** [nltk/nltk#1424]
[This line](https://github.com/nltk/nltk/blob/develop/nltk/parse/stanford.py#L219) `stdout = stdout.replace(b'\xa0',b' ')` breaks 2-byte characters such as 0xc3 0xa0 (à).

To reproduce (python 3):

``` python
stanford.StanfordNeuralDependencyParser().raw_parse("aàa")
```

I got:

```
Traceback (most recent call last):
  File "pipeline_verbal.py", line 19, in <module>
    parser.raw_parse("aàa")
  File "/home/amit/tools/anaconda3/lib/python3.5/site-packages/nltk/parse/stanford.py", line 132, in raw_parse
    return next(self.raw_parse_sents([sentence], verbose))
  File "/home/amit/tools/anaconda3/lib/python3.5/site-packages/nltk/parse/stanford.py", line 150, in raw_parse_sents
    return self._parse_trees_output(self._execute(cmd, '\n'.join(sentences), verbose))
  File "/home/amit/tools/anaconda3/lib/python3.5/site-packages/nltk/parse/stanford.py", line 221, in _execute
    stdout = stdout.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 3: invalid continuation byte
```

I believe a more specific character sequence should be used instead of '\xa0'.
Also, it would be helpful to have a comment above those lines, that explains why they are necessary. That would make debugging easier.

Thanks!

**Comment by dimazest** [comment]
Consider using the code proposed in #1249 It uses web api and should work fine with unicode.

**Comment by fluhus** [comment]
Thanks, but I am getting errors with your proposed code, even with a simple basic use. I can post them on your pull request thread if you want.

So until the new implementation is stabilized, maybe it's possible to fix this one. I'd do it myself if I knew what that code was supposed to do.

**Comment by dimazest** [comment]
Could you share the error.

**Comment by ghost** [comment]
What is the different between lexical and neural, I means, in encoding. 

When I call raw_parse of `StanfordDependencyParser`, it works fine, even a bit slow. But when I call `StanfordNeuralDependencyParser`, the error shows: 
`UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 0: invalid start byte`

**Comment by Kaleidophon** [comment]
I am also having this problem. Is there any solution to it available yet?

**Comment by elvinsophus** [comment]
I don't know what this replacement is for but it shouldn't have been done before decoding the string, because some characters does contain "\xa0" like what I encountered handling some Chinese texts. I exchanged the decoding and replacement lines and it worked.

**Comment by Kaleidophon** [comment]
It worked for me when I was working on a `latin-1` encoded corpus, I then changed every tool involved to work with `latin-1`. But now I am working with a `utf-8` corpus again and it's breaking once more. I am still looking if I forgot to change the encoding at one point, but I feel it's the Dependency Parse and that it should work with `utf-8` out of the box.

**Comment by Kaleidophon** [comment]
Furthermore: I am also working with Stanford's PoS-Tagger and Named-Entity-Tagger and they work just fine.

**Comment by Kaleidophon** [comment]
I compared the code in those classes and I don't really understand why, but if I turn Lines 218 + 219 into comments, it runs without a problem. What are those two lines supposed to do in the first place?

https://github.com/nltk/nltk/blob/develop/nltk/parse/stanford.py#L219

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
