### ISSUE TITLE
not sure bug in tag.perceptron.py

### ISSUE THREAD

**Issue by phymr** [nltk/nltk#1427]
I'm not sure whether there are some bugs in def _get_features(self, i, word, context, prev, prev2) , def train(self, sentences, save_loc=None, nr_iter=5) and def tag(self, tokens), i hope you to check them. 
I think prev, prev2 in train(self, sentences, save_loc=None, nr_iter=5) are wrong.
I guess prev is referred to tag of i-2 word and prev2 is referred to tag of i-1 word because of prev, prev2 = self.START, so the codes in def _get_features(self, i, word, context, prev, prev2): add('i-1 tag', prev) should be add('i-1 tag', prev2), add('i-2 tag', prev2) should be add('i-2 tag', prev), add('i tag+i-2 tag', prev, prev2) should be add('i-1 tag+i-2 tag', prev2, prev), add('i-1 tag+i word', prev, context[i]) should be add('i-1 tag+i word', prev2, context[i]),
codes in train(self, sentences, save_loc=None, nr_iter=5): prev2 = prev  prev = guess should be prev = prev2  prev2 = guess
codes in tag(self, tokens): prev2 = prev  prev = tag should be prev = prev2 prev2 = tag
I'm really not sure my wether my opionion is right, please check it, thank you.

**Comment by rmalouf** [comment]
It looks like `prev` is the tag of word i-1 and `prev2` is the tag of word i-2 in both `train` and `_get_features`.  Can you be more specific about where you see the inconsistency?

**Comment by alvations** [comment]
There shouldn't be any error in the code for the perceptron tagger. 

The `prev2` refers to the i-2 tag feature and `prev` refers to the i-1 tag feature as defined at https://github.com/nltk/nltk/blob/develop/nltk/tag/perceptron.py#L259

The confusion may come from the fact that when the [`START` was initialized](https://github.com/nltk/nltk/blob/develop/nltk/tag/perceptron.py#L129) with:

```python
START = ['-START-', '-START2-']
# some more code...
prev, prev2 = self.START
```

But that's the same as declaring the variables in the natural order of the tags, i.e.

```python
START = ['-START2-', '-START-']
# some more code...
prev2, prev = self.START
```

And the most important part is that as we move allow the tokens/tags, the `prev2` takes the value `prev` and the `prev` takes the value of the current tag, 

```
# We move forward in the tokens 
# And the i-2 th is forgotten and it takes the value of i-1 th 
prev2 = prev 
# And the i-1 th takes the value of the current tag.
prev = tag
```

More importantly it's consistent during training and tagging/testing at 
 
 - https://github.com/nltk/nltk/blob/develop/nltk/tag/perceptron.py#L159
 - https://github.com/nltk/nltk/blob/develop/nltk/tag/perceptron.py#L198

If we step through the sliding window, where the cells in the tables are the values and the header row is the variable:

| Step | `prev2` | `prev` | `tag` | 
|:----:|:----:|:----:|:----:|
| 0 | w_i-2 | w_i-1 | w_i | 
| 1 | w_i-1 | w_i | w_i+1 | 

We see that from step 0 -> 1: 

 - `prev2` takes on the value of `prev` , i.e. `prev2 = prev` 
 - `prev` takes on the value of `tag`, i.e. `prev = tag`

**Comment by alvations** [comment]
@phyhwj Does the previous post resolve the confusion?
