### ISSUE TITLE
Vectorizer using Skipgrams

### ISSUE THREAD

**Issue by HimaVarsha94** [nltk/nltk#1428]
Can we have a vectorizer which uses skipgrams? I often use it in my projects and it would be great if it is implemented already in nltk.util. I would be happy to contribute.

**Comment by stevenbird** [comment]
+1

What would be the interface?
NB http://www.nltk.org/api/nltk.html#nltk.util.skipgrams

**Comment by alvations** [comment]
Maybe we shouldn't implement our own skipgram vectorizer, since [`gensim` has one that's optimized and coded in cython](https://github.com/RaRe-Technologies/gensim/blob/master/gensim/models/word2vec_inner.pyx) and the python version is also at: https://github.com/RaRe-Technologies/gensim/blob/master/gensim/models/word2vec.py#L111

**Comment by HimaVarsha94** [comment]
What if for instance, TfidfVectorizer can either work with ngrams or skipgrams based on the argument passed? (maybe add another word in 'analyzer' to accomondate skipgrams? )

**Comment by alvations** [comment]
@HimaVarsha94 are you looking for something like this:

``` python
>>> import functools
>>> from nltk.util import skipgrams
>>> from nltk import word_tokenize
>>> from sklearn.feature_extraction.text import CountVectorizer
>>> text = [word_tokenize(line.strip()) for line in open('test.txt', 'r')]
>>> text
[['This', 'is', 'a', 'text', 'block', 'start', '.'], ['This', 'is', 'the', 'end', '.']]

# Example of a bigram with k=2 skips.
>>> skipper = functools.partial(skipgrams, n=2, k=2)
>>> list(skipper(text[0]))
[('This', 'is'), ('This', 'a'), ('This', 'text'), ('is', 'a'), ('is', 'text'), ('is', 'block'), ('a', 'text'), ('a', 'block'), ('a', 'start'), ('text', 'block'), ('text', 'start'), ('text', '.'), ('block', 'start'), ('block', '.'), ('start', '.')]
>>> list(skipper(text[1]))
[('This', 'is'), ('This', 'the'), ('This', 'end'), ('is', 'the'), ('is', 'end'), ('is', '.'), ('the', 'end'), ('the', '.'), ('end', '.')]

# Example of a trigram with k=2 skips.
>>> skipper = functools.partial(skipgrams, n=3, k=2)
>>> list(skipper(text[0]))
[('This', 'is', 'a'), ('This', 'is', 'text'), ('This', 'is', 'block'), ('This', 'a', 'text'), ('This', 'a', 'block'), ('This', 'text', 'block'), ('is', 'a', 'text'), ('is', 'a', 'block'), ('is', 'a', 'start'), ('is', 'text', 'block'), ('is', 'text', 'start'), ('is', 'block', 'start'), ('a', 'text', 'block'), ('a', 'text', 'start'), ('a', 'text', '.'), ('a', 'block', 'start'), ('a', 'block', '.'), ('a', 'start', '.'), ('text', 'block', 'start'), ('text', 'block', '.'), ('text', 'start', '.'), ('block', 'start', '.')]
>>> list(skipper(text[1]))
[('This', 'is', 'the'), ('This', 'is', 'end'), ('This', 'is', '.'), ('This', 'the', 'end'), ('This', 'the', '.'), ('This', 'end', '.'), ('is', 'the', 'end'), ('is', 'the', '.'), ('is', 'end', '.'), ('the', 'end', '.')]

# Initialize the vectorizer with the skipgram analyzer.
>>> vectorizer = CountVectorizer(analyzer=skipper)
# Fit the text into the vectorizer.
>>> vectorizer.fit(text)
CountVectorizer(analyzer=<functools.partial object at 0x7f7eed5865d0>,
        binary=False, decode_error=u'strict', dtype=<type 'numpy.int64'>,
        encoding=u'utf-8', input=u'content', lowercase=True, max_df=1.0,
        max_features=None, min_df=1, ngram_range=(1, 1), preprocessor=None,
        stop_words=None, strip_accents=None,
        token_pattern=u'(?u)\\b\\w\\w+\\b', tokenizer=None,
        vocabulary=None)
>>> vectorizer.vocabulary_
{('is', 'text', 'block'): 24, ('a', 'text', '.'): 15, ('This', 'text', 'block'): 9, ('text', 'block', 'start'): 29, ('This', 'is', 'a'): 4, ('This', 'is', 'block'): 5, ('a', 'text', 'block'): 16, ('is', 'block', 'start'): 22, ('is', 'the', '.'): 26, ('text', 'start', '.'): 30, ('is', 'text', 'start'): 25, ('This', 'the', '.'): 10, ('This', 'is', 'text'): 7, ('a', 'block', 'start'): 13, ('text', 'block', '.'): 28, ('This', 'is', '.'): 3, ('a', 'start', '.'): 14, ('This', 'end', '.'): 2, ('This', 'a', 'text'): 1, ('is', 'a', 'block'): 19, ('is', 'end', '.'): 23, ('a', 'text', 'start'): 17, ('the', 'end', '.'): 31, ('This', 'the', 'end'): 11, ('is', 'a', 'start'): 20, ('is', 'a', 'text'): 21, ('is', 'the', 'end'): 27, ('This', 'is', 'end'): 6, ('This', 'is', 'the'): 8, ('a', 'block', '.'): 12, ('This', 'a', 'block'): 0, ('block', 'start', '.'): 18}
```

Note that we need the `functools.partial` so that we can initialize the `skipgrams()` function with the `kwargs` parameters.

**Comment by HimaVarsha94** [comment]
Similar, yes. Would that be a good idea?

**Comment by alvations** [comment]
@HimaVarsha94 do note that when we vectorize the corpus in the method presented above, our `k` skip-distance is fixed. But in the original [word2vec code](https://github.com/Kylepoore/word2vec/blob/master/word2vec.c#L464) and [gensim](https://github.com/RaRe-Technologies/gensim/blob/master/gensim/models/word2vec.py#L127), the k value is randomized for each position (`k` is referred to as `b` in the word2vec code).

If we're trying to achieve the same vectorization as in gensim or word2vec, using `sklearn` vectorizers would have restricted the "randomness" of the `b` variable.

~~To achieve some sort of randomized `b`, you have to use something like:~~

``` python
>>> import random
>>> import functools
>>> from nltk.utils import skipgrams
>>> window_size = 3
>>> skipper = functools.partial(skipgrams, n=window_size, k=random.randint(1,window_size))
```

~~Still the randomization above is at sentence level and not at the token level. Getting randomized `b` / `k` variable at the token level would require some overhaul in the `skipgram()` function itself.~~

After looking at the gensim and word2vec code carefully, the `skipgram()` implemented according to Guthrie et al. (2006) is a little different from the definition used to implement word2vec skipgram. Also, it's a little different from the skipgram definition from https://www.tensorflow.org/versions/r0.7/tutorials/word2vec/index.html where there're `(context, target)` pairs given a sentence.

**Comment by HimaVarsha94** [comment]
@alvations Thank you so much for the prompt replies. I am a newbie and I am still figuring it out. 
I understand that using this will restrict the randomness as you suggested. As you pointed out, the skipgram model implemented in Word2Vec is different from nltk.utils skipgrams. But when we use [TfidfVectorizer](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/feature_extraction/text.py#L1106) with n-grams, we give a range from which the corresponding n-gram range to be taken from based on our dataset. So, for example I know that I have a key-word pair with some skipped distance between them. We can fix the skipgram range as above (maybe by using [skipgrams](http://www.nltk.org/api/nltk.html#nltk.util.skipgrams)) and use the sklearn vectorizers? Maybe this issue should be asked in sklearn rather than nltk.

**Comment by alvations** [comment]
1. If the aim is to vectorize a sentence given a different analyzer than the ones provided in `sklearn` then I would say the `functools` trick with `nltk.util.skipgrams` and `sklearn` vectorizer would be good. 
2. But if the aim is to produce `skipgram` as like the ones for `word2vec` then it's a different notion of `skipgram` and sentence vectorization. 

I would say the first is possible and easy and you would just need to clean up the example code in the post above and write tests =)

The second (writing skipgram for word2vec), it's a different thing and I would say interfacing gensim would be more appropriate.

**Comment by HimaVarsha94** [comment]
@alvations Thank you.

**Comment by ingridxx** [comment]
@alvations Thanks so much for the code. I'm using it to count the frequency of skip-grams and it's working really well. However, I tried filtering out the stop words but for some reason it won't work.
All I changed is this line:
`vectorizer = CountVectorizer(analyzer=skipper, stop_words = 'english')`

But it doesn't do anything. Any insight will be greatly appreciated!!

**Comment by alvations** [comment]
The line `vectorizer = CountVectorizer(...)` only initialize the vectorizer, you have to `.fit()` the input text to create the vectorizer according to the skipgrams that are in the text, e.g. 

```python
import functools
from nltk.util import skipgrams
from nltk import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
text = [['This', 'is', 'a', 'text', 'block', 'start', '.'], ['This', 'is', 'the', 'end', '.']]

skipper = functools.partial(skipgrams, n=2, k=2)

vectorizer = CountVectorizer(analyzer=skipper, stop_words='english')
vectorizer.fit(text)
print(vectorizer.vocabulary_)
```

[out]:

```
{('This', 'is'): 2, ('This', 'a'): 0, ('This', 'text'): 3, ('is', 'a'): 12, ('is', 'text'): 15, ('is', 'block'): 13, ('a', 'text'): 7, ('a', 'block'): 5, ('a', 'start'): 6, ('text', 'block'): 19, ('text', 'start'): 20, ('text', '.'): 18, ('block', 'start'): 9, ('block', '.'): 8, ('start', '.'): 17, ('This', 'the'): 4, ('This', 'end'): 1, ('is', 'the'): 16, ('is', 'end'): 14, ('is', '.'): 11, ('the', 'end'): 22, ('the', '.'): 21, ('end', '.'): 10}
```

But do note the discussions in the comments above, esp. if you're going to use "skipgrams" for deep learning word2vec purposes.
