### ISSUE TITLE
word_tokenize doesn't tokenize "»"

### ISSUE THREAD

**Issue by mwess** [nltk/nltk#1434]
Hi all,
we tried to use nltk for the part-of-speech tagging of german texts and in some of them the french quotation marks "»" and "«" are used for quotation instead of " " ", the normal (or standard) quotation mark.

As an example consider the following sentence:

»Now that I can do.«

This is tokenized:
nltk.word_tokenize("»Now that I can do.«")

and yields:

['»Now', 'that', 'I', 'can', 'do.«']

instead of:

['»' , 'Now', 'that', 'I', 'can', 'do', '.', '«']

Can this be fixed?

Best regards.

Edit: Minor fix.

**Comment by alvations** [comment]
c.f. #1682
