### ISSUE TITLE
Can I navigate through large amounts of semantic terrain? (May be an enhancement, may be user education, user education is welcome)

### ISSUE THREAD

**Issue by JonathanHayward** [nltk/nltk#1438]
I wrote in http://stackoverflow.com/questions/38525854/how-can-i-ask-the-nltk-to-have-synonyms-be-connected-to-nearby-terms-rather-tha :

> I am working on an NLTK project, intended in principle to be like a standard thesaurus but (quasi-)continuous. To take one example, there are dozens of entries connected with books, including both religious classics and ledgers.
> 
> I tried fiddling with some terms, but I seemed to get just a smaller slice of the pie by doing that. (A "ledger" result contained "daybook" but the substances was a much smaller collection than one would find by reading a book.) The discussion of "synsets" in the documentation seem to imply both that you can find terms close to an existing terms, but the synsets are like islands, or see such to me.
> 
> What (if any) means are there to say something like "I want all words with a high match score above XYZ threshold" or "I want to match the n closest related terms." The documentation looks like this is possible, with a really nice way of calculating a proximity score between two words, but don't see how to adjust the threshold or alternately how to request the n closest matches.
> 
> What are my best bets here?

I've gotten one reply, basically asking what I meant:

> Hm I don't really follow your project. What exactly are you trying to achieve? Are you just looking for (near)synonyms? 

I responded:

> I'm trying to do something like [Visual Thesaurus](https://www.visualthesaurus.com/). In other words, you start with one term, and you can navigate to other terms with increasingly different meanings. The equivalent for roads and terrain is that you can drive on paved roads and go from the state of Washington to Florida, or California to New York, traversing only paved roads (no Jeep 4x4 needed). Imagine a much sparser graph of roads where Illinois roads wouldn't take you out, and there were actually [no fewer than] two or three connected components. (Can you see why I'd like a much denser graph?)

I'd like to request an enhancement of a de-partitioning of synonym terrain, or pointing me to another technology that covers the terrain with a web of roads, or explaining to me what I am missing here and failing to recognize something that NLTK has down cold.

Thanks,
[C.J.S. Hayward](https://CJSHayward.com)

**Comment by stevenbird** [comment]
@JonathanHayward: you might like to look into word embeddings using gensim. Here's a starting point: https://github.com/nltk/nltk/blob/991f2cd1e31f7c1ad144589ab4d2c76bee05aa7b/nltk/test/gensim.doctest
