### ISSUE TITLE
[SMT] IBM Model 1 Smoothing EM

### ISSUE THREAD

**Issue by choltz95** [nltk/nltk#1439]
State of the art word alignment involves controlling the amount of over-fitting EM does on the training set by heuristically, or through some Bayesian methods initializing prior probabilities on model parameters and doing smoothing.

I would like to work on this if possible.

Relevant papers:
http://www.aclweb.org/anthology/P00-1056
http://www.aclweb.org/anthology/P04-1066
http://www.cs.rochester.edu/~gildea/pubs/riley-gildea-tr10.pdf

**Comment by alvations** [comment]
Please feel free to add to the codebase in `nltk.translate.ibm1.py` and do a pull request and we can review it before merging. 

Do look at the [contribution guidelines](https://github.com/nltk/nltk/blob/develop/CONTRIBUTING.md) about how to start contributing. Happy hacking!
