### ISSUE TITLE
[SMT] HMM Word Alignment

### ISSUE THREAD

**Issue by choltz95** [nltk/nltk#1440]
IBM models 1-5 are implemented. Are there any plans to implement the HMM word alignment model?

I would like to work on this if possible

Related papers:
http://www.aclweb.org/anthology/C96-2141

**Comment by alvations** [comment]
Similar to the #1439, please feel free to add to the codebase in `nltk.translate` and do a pull request and we can review it before merging.

Depending on your liking you can either send 2 pull requests for #1439 and #1440 or you could send a single one that adds both functionality.

Do look at the contribution guidelines about how to start contributing. Happy hacking!
