### ISSUE TITLE
NLTK Installation Failure

### ISSUE THREAD

**Issue by winswinnie** [nltk/nltk#1441]
Hi all, I am completely new to the use of NLTK and Python, and I would really appreciate some help on the basics.  I currently have Python 2.7 installed on the OSX El Captain.  When I key in 

> sudo pip install -U nltk
> "SyntaxError: invalid syntax"

as advised by the website.  That is what I kept on getting, which means I could not install NLTK by any means. 

I shall be grateful for any advice/comments.  Thanks in advance guys!

**Comment by choltz95** [comment]
The pip program should be run from the command line, not the Python interpreter.

**Comment by winswinnie** [comment]
@choltz95 Hi, thanks a lot for the information.  May I clarify where to find the command line? Are you referring to the one in Python Launcher? I tried to type there but seems like it wouldn't support any manual changes.

**Comment by nschneid** [comment]
http://blog.teamtreehouse.com/introduction-to-the-mac-os-x-command-line

**Comment by stevenbird** [comment]
Thanks @choltz95, @nschneid
