### ISSUE TITLE
Contributing stopwords for Slovene

### ISSUE THREAD

**Issue by ajdapretnar** [nltk/nltk#1446]
I've tried to find the proper folder/file to contribute my list of Slovenian stopwords to, but after an extensive search I wasn't able to find anything.
Where is the proper folder to submit the list of stopwords to and what is the desired format?
Thanks!

**Comment by stevenbird** [comment]
Please open an issue here: https://github.com/nltk/nltk_data and include the list of stopwords, one per line.
