### ISSUE TITLE
Problem installing NLTK data on mac

### ISSUE THREAD

**Issue by jnandigam** [nltk/nltk#1448]
Hi,

I am not able to install NLTK data from NLTK Downloader. I have Python 3.5.2 and NLTK 3.2.1.

A screenshot of NLTK Downloader with the error message is attached.

Any help is very much appreciated. Thank you very much.

![screen shot 2016-08-06 at 8 47 09 pm](https://cloud.githubusercontent.com/assets/1740553/17459814/a254a904-5c17-11e6-9e93-52073a28d034.png)

**Comment by stevenbird** [comment]
Looks like you might be behind a firewall. You can download packages directly here:
http://www.nltk.org/nltk_data/
