### ISSUE TITLE
NLTK 3.2.1: Deprecated Warning with Python 3.5.2

### ISSUE THREAD

**Issue by AdriG83** [nltk/nltk#1463]
Hi,
I'm learning Python.
For my first program in Python, I downloaded Chatterbot 0.4.6 that contained nltk module. 

This program doesn't work because of nltk/decorators.py generates a Deprecated Warning (inspect.getargspec). I installed last version of NLTK with the process explained in the website www.nltk.org but I have the same problem.
This is the result when I try to run the program Chatterbot 0.4.6:

Warning (from warnings module):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/decorators.py", line 59
    regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

Can you help me?

**Comment by fievelk** [comment]
ChatterBot solved the problem (see gunthercox/ChatterBot#292).
We still need to check it.
