### ISSUE TITLE
NLTK fails to find the Java file

### ISSUE THREAD

**Issue by AlexYoung757** [nltk/nltk#1476]
when i use stanford word segmenter ,  here is code :
import nltk
from nltk.tokenize.stanford_segmenter import StanfordSegmenter

segmenter = StanfordSegmenter(
    path_to_jar = "./stanford_segmenter/stanford-segmenter-3.6.0.jar", 
    path_to_sihan_corpora_dict = "./stanford_segmenter/data", 
    path_to_model = "./stanford_segmenter/data/pku.gz", 
    path_to_dict = "./stanford_segmenter/data/dict-chris6.ser.gz")

sentence = u"这里是斯坦福分词器测试"

result = segmenter.segment(sentence)
print result

the error as follows :
NLTK was unable to find the java file!
Use software specific configuration paramaters or set the JAVAHOME environment variable.

i have set the javehome enviroment , but it also doesn't work

**Comment by yooper** [comment]
You have to set JAVA_HOME, not JAVAHOME

``` bash
JAVA_HOME=/opt/java/jre1.8.0_45/bin/java
```

If your code cannot find the Stanford files, then you are using the wrong relative path. Try using the absolute paths.

**Comment by alvations** [comment]
Thanks @yooper for the instructions to setup JAVA.

@AlexYoung757 , did @yooper's answer resolve your problem?

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
