### ISSUE TITLE
Cannot import nltk after installation

### ISSUE THREAD

**Issue by mmuppidi** [nltk/nltk#1479]
The package is installed in `/Library/Python/2.7/lib/python/site-packages` but I cannot import nltk. Please advice

**Comment by iliakur** [comment]
Do you use virtualenv? How do you run python? I'm guessing you are on MacOS, is that right?

**Comment by mmuppidi** [comment]
Thanks for responding. I don't use virtualenv. Yes I am on Mac.

**Comment by iliakur** [comment]
Thanks for the responses. How do you invoke python?
Could you try starting up a session and post the output of the following:

```
import sys
sys.path
```

**Comment by alvations** [comment]
@mmuppidi did you resolve your installation issues? 

On a Mac, you can either try [Anaconda](https://docs.continuum.io/anaconda/install): 

```
conda install nltk
```

Or if you would like to install `nltk` such that the user can use it without messy setup, you could try:

```
pip install --user nltk
```
