### ISSUE TITLE
CategorizedCorpusReader categories() when using fileids and the document has only one category

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#148]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>

'2.0b9'

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>

from nltk.corpus import reuters
reuters.categories()[:5]
['acq', 'alum', 'barley', 'bop', 'carcass']
reuters.fileids()[:5]
['test/14826', 'test/14828', 'test/14829', 'test/14832', 'test/14833']
reuters.categories('test/14826')
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/usr/lib/python2.5/site-packages/nltk-2.0b9-py2.5.egg/nltk/corpus/reader/api.py&quot;, line 338, in categories
    return sorted(set.union(_[self._f2c[d] for d in fileids]))
TypeError: union() takes exactly one argument (0 given)
reuters.categories(['test/14826'])
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/usr/lib/python2.5/site-packages/nltk-2.0b9-py2.5.egg/nltk/corpus/reader/api.py&quot;, line 338, in categories
    return sorted(set.union(_[self._f2c[d] for d in fileids]))
TypeError: union() takes exactly one argument (0 given)
reuters.categories(['test/14826',''])
['trade']
reuters.categories(['test/14826','test/14828'])
['grain', 'trade']

<b>What is the expected output? What do you see instead?</b>

List of categories for a text document

List of categories for the document 

<b>Please use labels and text to provide additional information.</b>

it seems to be a problem with categories in CategorizedCorpusReader, when a fileid is passed and it has only one Categorie, set.union throw the error.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=659</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2011-08-08T09:51:25.000Z:</strong></p>
<p>This is not a problem in Python 2.6, but shows up in Python 2.5 (and NLTK is supposed to work for Python 2.5).
</p>

**Comment by alvations** [comment]
This set union issue should have been resolved in the later Python > 2.7 and 3.x versions. 

```python
>>> from nltk.corpus import reuters
>>> reuters.categories()[:5]
[u'acq', u'alum', u'barley', u'bop', u'carcass']
>>> reuters.fileids()[:5]
['test/14826', 'test/14828', 'test/14829', 'test/14832', 'test/14833']
>>> reuters.categories('test/14826')
[u'trade']

```


The union should work now (python 2.7/3.x) with empty or single object:

```
>>> set.union(set([]))
set([])
>>> set.union(set([1]))
set([1])
```
