### ISSUE TITLE
intent parser from sentence

### ISSUE THREAD

**Issue by armsmani** [nltk/nltk#1483]
I want to create a ChatBot, and I'm planning on using the NLTK libs for parsing the messages from the user, but **how can I detect the user's intent.** like below

Hello!                           -> greeting
Hi <chatbot's name>   -> greeting
Tell me the weather      -> weather
Is it raining?                  -> weather

Is there any option to identify intent action by using NLTK?

**Comment by fievelk** [comment]
Hi @armsmani. 
This space is meant to be used to report issues about the NLTK codebase.

I think your question should be asked in the [NLTK-users](https://groups.google.com/forum/#!forum/nltk-users) forum, where you could receive more support by other NLTK users.
