### ISSUE TITLE
ipipan corpus not found and NKJP

### ISSUE THREAD

**Issue by fievelk** [nltk/nltk#1484]
Running `tox -e py35` I get the following error:

```
ERROR: Failure: LookupError (
**********************************************************************
  Resource 'corpora/ipipan' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
```

But the `ipipan` corpus is not available on nltk_data:

```
>>> nltk.download('ipipan')
[nltk_data] Error loading ipipan: Package 'ipipan' not found in index
```

I know there are several open issues and references to this corpus and `nkjp`:
- #913 (Issue: ipipan module looks dead)
- #844 (Pull Request: NKJP Corpus Reader)
- nltk/nltk_data#17 (Pull Request: NKJP corpus on nltk_data)
- [National Corpus of Polish](https://groups.google.com/forum/#!topic/nltk-dev/VMMCXejQJMQ) (on NLTK-dev)

@stevenbird 
What should we do with ipipan and NKJP modules? They are currently breaking `python3.5` tests and nltk_data does not have corpora for them.

Also note: I do not know why tests with previous python versions do not automatically break.

**Comment by alvations** [comment]
This should be resolved since these datasets no longer exist on `nltk_data` =)
