### ISSUE TITLE
Fix Penn Treebank corpus reader please

### ISSUE THREAD

**Issue by tastyminerals** [nltk/nltk#1487]
Following the [nltk docs on corpus API](http://www.nltk.org/howto/corpus.html), I wanted to use nltk to parse a copy of full Penn Treebank corpus. I unzipped the required directories "brown" and "wsj" into `/home/tastyminerals/nltk_data/corpora/ptb` dir as was stated in the docs. The unzipped files were all lowercased and I had to rename them because ptb corpus reader expects them to be all in uppercase (this issue was [reported](https://github.com/nltk/nltk/issues/124) btw).

After that I am trying to extract a parse tree from a particular file. Using, again, the example from the docs.

```
from nltk.corpus import treebank, ptb
treebank.parsed_sents('wsj_0003.mrg')[0])   # notice lowecase filename
> Tree('S', [Tree('S-TPC-1', [Tree('NP-SBJ', [Tree('NP', [Tree('NP'...
```

Works well, for the sample treebank included with nltk.
However, trying to perform the same operation with **ptb** fails.

```
ptb.parsed_sents('WSJ_0003.MRG')[0])  # notice the uppercase because we had to rename them
> No such file or directory: '/home/tastyminerals/nltk_data/corpora/ptb/WSJ_0003.MRG'
```

Well of course there is no such file, the file is in `ptb/WSJ/00/WSJ_0003.MRG`.
Why does **ptb** is not aware of the Penn Treebank directory structure? Moreover, why is it case sensitive in the first place? This needs to be fixed. The docs also need to be updated accordingly.

**Comment by stevenbird** [comment]
I would be happy to review a PR for a full treebank corpus reader – long overdue to have proper support!
