### ISSUE TITLE
Enhanced version of Bioreaderr in nltk_contrib

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#149]
Hi
An enhanced version of bioreader in nltk_contrib [http://code.google.com/p/nltk/source/browse/trunk#trunk%2Fnltk_contrib%2Fnltk_contrib%2Fbioreader] directory is available at https://bitbucket.org/jagan/bioreader.
Code clean up and implimentation of coding standards are done 

Jaganadh G<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=661</p><hr/><h2>earlier comments</h2>

<p><strong>StevenBird1 said, at 2011-04-08T13:26:40.000Z:</strong></p>

<p>Thanks.  Would you please describe what the extra files are for?  Also, please remember to use "new style" Python classes.
</p><p><strong>jaganadhg said, at 2011-04-08T14:43:05.000Z:</strong></p>

<p>Dear Stevan
The extra files are programs which I used for testing the program. Now I removed the files from bitbucket. I will impliment the "new style" Python class soon. If possible I will finish it by this week end. </p><p><strong>jaganadhg said, at 2011-04-08T15:33:53.000Z:</strong></p>

<p>Dear Stevan 
Just incorporated the "new style" Python class and also dome some minor corrections in the API documentation

Jaganadh G</p>

**Comment by kmike** [comment]
migrated to https://github.com/nltk/nltk_contrib/issues/6
