### ISSUE TITLE
Bug when drawing trees.

### ISSUE THREAD

**Issue by david-codeq** [nltk/nltk#1491]
When I draw and show a fairly large tree, it stays on the screen for a few seconds, then gives an error, which, when running with "python x.py" or "ipython x.py" in python 2 shows this:

```
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

When running with ipython with python 3, it shows this, and sometimes stays on the screen for a while while printing these errors to the terminal:

```
2016-11-01 12:19:09.788 python[9215:152385] CALayer position contains NaN: [0 nan]
```
When using ipython's qtconsole, the kernel quits after a short time.

I have a Macbook Pro running Sierra; this pattern holds with both Python 2.7.12 and Python 3.5.2

A small script to reproduce:

```

from nltk.tree import Tree
s = "This is a rather long sentence whose tree may or may not stay on the screen for long."
parse_tree = "(S1 (S (NP (DT This)) (VP (VBZ is) (NP (NP (DT a) (ADJP (RB rather) (JJ long)) (NN sentence)) (SBAR (WHNP (WP$ whose) (NN tree)) (S (VP (VP (MD may)) (CC or) (VP (MD may) (RB not) (VP (VB stay) (PP (IN on) (NP (DT the) (NN screen))) (PP (IN for) (ADJP (JJ long)))))))))) (. .)))"
the_tree = Tree.fromstring(parse_tree)
the_tree.draw()
```

Run with:
`python file_name.py`
or
`ipython file_name.py`

**Comment by guydepauw** [comment]
I can't reproduce the error with this script, but I am getting the same error message while trying

`nltk.app.chartparser()`

`libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by david-codeq** [comment]
Hmm, @guydepauw , but if you use the script I posted, it just prints the tree fine? Or what?

**Comment by SilentFlame** [comment]
@guydepauw 

If you compile the above as a python file it throws the error.
But when you execute all the commands on `command line python` everything works fine.

Donno the reason but yeah it is there.

**Comment by david-codeq** [comment]
@SilentFlame that isn't my experience. I get the error with command line python too. Also with ipython, and with jupyter qtconsole.

**Comment by guydepauw** [comment]
@david-codeq yep exactly
@SilentFlame and it works fine on command line and as a script

Could you guys check if `nltk.app.chartparser()` is working for you? I found this thread because of the reference to `libc++abi.dylib`. There could be a common solution for it.

**Comment by david-codeq** [comment]
@guydepauw  I get no error when typing `nltk.app.chartparser()` in the REPL and then just waiting.

**Comment by Yevgnen** [comment]
Similar issue here after `nltk.download()` using matplotlib `MacOSX` backend.
