### ISSUE TITLE
Add download directory to nltk.data.path

### ISSUE THREAD

**Issue by ghost** [nltk/nltk#1495]
**Issue:**
If user adds a new path. data not found error is raised while including data later. and user has to explicitly append path with nltk.data.path.append('/path/to/data')

**What does the feature do?**
Add the path entered on NLTK GUI in download directory, if it does not exist already.

**Comment by alvations** [comment]
I hope this demonstration would help you.

Firstly, by default `nltk` would save the `nltk_data` on your default home path:

```python
$ echo `PWD` # current path.
/Users/liling.tan
$ ls nltk_data/
chunkers/   grammars/   misc/       mt_eval/    stemmers/   tokenizers/
corpora/    help/       models/     sentiment/  taggers/
$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.data.path
['/Users/liling.tan/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']
>>> exit()
```

So let's move the `nltk_data` to another path and we see that it doesn't find the directory:

```python
liling.tan@ASRHQ289:~$ mv nltk_data/ new_nltk_data_path/
liling.tan@ASRHQ289:~$ ls ne
network-gpu-info/   new_nltk_data_path/ 
liling.tan@ASRHQ289:~$ ls new_nltk_data_path/
chunkers/   grammars/   misc/       mt_eval/    stemmers/   tokenizers/
corpora/    help/       models/     sentiment/  taggers/
liling.tan@ASRHQ289:~$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.data.path
['/Users/liling.tan/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']
>>> from nltk.corpus import wordnet as wn
>>> wn.synsets('dog')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nltk/corpus/util.py", line 99, in __getattr__
    self.__load()
  File "/Library/Python/2.7/site-packages/nltk/corpus/util.py", line 64, in __load
    except LookupError: raise e
LookupError: 
**********************************************************************
  Resource u'corpora/wordnet' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/Users/liling.tan/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

To add your custom path where you save the `nltk_data`, you can simply use `nltk.data.path.append()` since `nltk.data.path` is simply a list =)

```python
$ ls new_nltk_data_path/
chunkers/   grammars/   misc/       mt_eval/    stemmers/   tokenizers/
corpora/    help/       models/     sentiment/  taggers/
$ python
>>> import nltk
>>> nltk.data.path
['/Users/liling.tan/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']
>>> from nltk.corpus import wordnet as wn
>>> wn.synsets('dog')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nltk/corpus/util.py", line 99, in __getattr__
    self.__load()
  File "/Library/Python/2.7/site-packages/nltk/corpus/util.py", line 64, in __load
    except LookupError: raise e
LookupError: 
**********************************************************************
  Resource u'corpora/wordnet' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/Users/liling.tan/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

# Here, we add the custom path and its works =)
>>> nltk.data.path.append('/Users/liling.tan/new_nltk_data_path') 
>>> from nltk.corpus import wordnet as wn
>>> wn.synsets('dog')
[Synset('dog.n.01'), Synset('frump.n.01'), Synset('dog.n.03'), Synset('cad.n.01'), Synset('frank.n.02'), Synset('pawl.n.01'), Synset('andiron.n.01'), Synset('chase.v.01')]

```

**Comment by iliakur** [comment]
What I did on my linux box is create a symlink to my custom data location. This should made life much easier with loading data. Not really a "solution", but a bit of a fix.

**Comment by alvations** [comment]
@pshkrjshnde Did @Copper-Head suggestion and the demo helped you resolve your problem?

**Comment by ghost** [comment]
@Copper-Head @alvations I knew that already. What I was trying to suggest was instead of adding the path in the code separately, is it possible to append the path to the original path.
Something like paths.txt contains certain fixed paths that nltk looks into by default. Add the new path to paths.txt
```
//original paths.txt

path/to/look/1
path/to/look/2
```
```
//new paths.txt

path/to/look/1
path/to/look/2
new/path/to/look/
```

nltk.data.path = read paths from paths.txt

**Comment by alvations** [comment]
@pshkrjshnde I'm not sure whether using an additional text file for `nltk_data` path is more user-friendly than just appending to the `nltk.data.path`. Possibly, adding the `NLTK_DATA` environmental variable would be more appropriate, e.g.

```
$ export NLTK_DATA=/home/alvas/some_path/nltk_data
$ python 
>>> import nltk
>>> nltk.data.path
['/home/alvas/some_path/nltk_data', '/home/alvas/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']
```


Maybe something like http://stackoverflow.com/a/36383314/610569 that tries to automagically search for `nltk_data` (but it assumes that directory named `nltk_data` must be the `nltk_data` meant for `nltk`).

**Comment by sarancruzer** [comment]
[nltk_data] Downloading package punkt to /home/saravanan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "codevector.py", line 37, in <module>
    tok_corp = [nltk.word_tokenize(sent,'utf-8') for sent in corpus]
  File "codevector.py", line 37, in <listcomp>
    tok_corp = [nltk.word_tokenize(sent,'utf-8') for sent in corpus]
  File "/home/saravanan/.local/lib/python3.5/site-packages/nltk/tokenize/__init__.py", line 128, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/home/saravanan/.local/lib/python3.5/site-packages/nltk/tokenize/__init__.py", line 94, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/home/saravanan/.local/lib/python3.5/site-packages/nltk/data.py", line 834, in load
    opened_resource = _open(resource_url)
  File "/home/saravanan/.local/lib/python3.5/site-packages/nltk/data.py", line 952, in _open
    return find(path_, path + ['']).open()
  File "/home/saravanan/.local/lib/python3.5/site-packages/nltk/data.py", line 673, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  Searched in:
    - '/home/saravanan/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/nltk_data'
    - '/usr/lib/nltk_data'
    - ''
**********************************************************************
