### ISSUE TITLE
Is NLTK FrameNet support frozen at FN version 1.5?

### ISSUE THREAD

**Issue by arpieb** [nltk/nltk#1506]
In #719 there was a question regarding support for newer versions of FrameNet beyond 1.5, yet there didn't appear to be any resolution although the issue is closed.  Is there a way to load newer versions of FrameNet (I have 1.7 burning a hole on my hard drive)?

Thanks!

**Comment by nschneid** [comment]
Most of the functionality should work if you substitute the 1.7 files under nltk_data/corpora/framenet/framenet_v15. I have beta-quality code with new functionality that I'm hoping to release soonish now that 1.7 is released.

**Comment by nschneid** [comment]
Downloading FrameNet 1.7 is supported as of #1556.
