### ISSUE TITLE
nltk.data.path not working

### ISSUE THREAD

**Issue by kanelloc** [nltk/nltk#1507]
```
import nltk
nltk.data.path.append('nltk_data')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk.classify.util
from nltk.classify import NaiveBayesClassifier
```

I am trying to change path but i continues to search at home location of nltk data... any idea why?

**Comment by alvations** [comment]
You should be using the full path to the `nltk_data`. Please take a look at http://stackoverflow.com/a/36383314/610569 and http://stackoverflow.com/a/22987374/610569

**Comment by alvations** [comment]
@kanelloc did the answers from the SO posts resolve your issue?

**Comment by kanelloc** [comment]
Sorry for the delay.
If you copy/paste the nltk_data folder from home to a project for some reason `nltk.data.append`doesn't work.The solution was:
1)`mkdir nltk_data` inside the project
2)use `nltk.download()` with file path the file path from 1)
3) `ntlk.data.append` worked now
Thank you very much
