### ISSUE TITLE
panlex_lite is failing

### ISSUE THREAD

**Issue by bmayerornl** [nltk/nltk#1517]
As has been reported previously I am having panlex_lite fail. 

I downloaded the zip file manually (wget) and unzip manually the error I get from this is:
$ unzip panlex_lite.zip 
Archive:  panlex_lite.zip
warning [panlex_lite.zip]:  76 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [panlex_lite.zip]:  reported length of central directory is
  -76 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
   skipping: panlex_lite/db.sqlite   need PK compat. v4.5 (can do v2.1)
   creating: panlex_lite/
  inflating: panlex_lite/README.txt  

note:  didn't find end-of-central-dir signature at end of central dir.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

**Comment by alvations** [comment]
c.f. #1253 

It's just that the webhost from panlex.org is rather slow and you have to have uninterrupted internet connection for at least 30 mins (can take up to 1-2hours if their site is busy) to complete the download.

**Comment by stevenbird** [comment]
Please try again and open a new issue if there is still a problem.
