### ISSUE TITLE
Coding error in using Stanford parser for Chinese!

### ISSUE THREAD

**Issue by wangjin0818** [nltk/nltk#1518]
Hi, there! Greetings!

I find that when using nltk import the Stanford parser for Chinese. It returns me an error. Here is my code:
```
# -*- coding:utf-8 -*-
import os
from nltk.parse import stanford 

os.environ['STANFORD_PARSER'] = os.path.join('stanford-parser-full', 'stanford-parser.jar')
os.environ['STANFORD_MODELS'] = os.path.join('stanford-parser-full', 'stanford-parser-3.6.0-models.jar')
java_path = "C:\\Program Files\\Java\\jdk1.8.0_73\\bin\\java.exe"
os.environ['JAVAHOME'] = java_path

string = '俄罗斯 希望 伊朗 没有 制造 核武器 计划'.decode('utf-8')
parser = stanford.StanfordParser(model_path='edu/stanford/nlp/models/lexparser/chineseFactored.ser.gz')
result = list(parser.parse(string.split()))

print(result)
```

And the return msg:

Traceback (most recent call last):
  File "E:\workspaces\python\tinker\stanford_parser.py", line 27, in <module>
    result = list(parser.parse(string.split()))
  File "C:\Anaconda2\lib\site-packages\nltk\parse\api.py", line 45, in parse
    return next(self.parse_sents([sent], *args, **kwargs))
  File "C:\Anaconda2\lib\site-packages\nltk\parse\stanford.py", line 120, in parse_sents
    cmd, '\n'.join(' '.join(sentence) for sentence in sentences), verbose))
  File "C:\Anaconda2\lib\site-packages\nltk\parse\stanford.py", line 224, in _execute
    stdout = stdout.decode(encoding)
  File "C:\Anaconda2\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 161-162: invalid continuation byte

Then, I checked the code. I find the following code in function _execute() in stanford.py:

```
stdout = stdout.replace(b'\xc2\xa0',b' ')
stdout = stdout.replace(b'\xa0',b' ')
```

I thought that the problem is here. b' ' cannot be decoded by utf-8. So, I change the code to:

```
if not encoding == 'utf8':
      stdout = stdout.replace(b'\xc2\xa0',b' ')
      stdout = stdout.replace(b'\xa0',b' ')
```

It works well!

**Comment by alvations** [comment]
This is an issue with how your terminal environment is setup. Not the NLTK code ;P

First try set locale to UTF8 on the terminal:

```
$ export LC_ALL=en_US.UTF-8
$ export LANG=en_US.UTF-8
$ export LANGUAGE=en_US.UTF-8
```

Then change your script you're using an outdated way to initialize an utf8 string do this instead. I think, there's no need to decode a string in python3:

```
string = u'俄罗斯 希望 伊朗 没有 制造 核武器 计划' # For python2
string = '俄罗斯 希望 伊朗 没有 制造 核武器 计划' # For python3
```

Then rerun your script without the replace and see whether you still get the error.

----

On windows, i wouldn't know the exact steps to setup your environment for utf8. Instead of printing out the result to console, try writing your output to file instead:

```
with open('output.txt', 'w', encoding='utf8') as fout:
    fout.write(str(result))
```

**Comment by wangjin0818** [comment]
Thanks for answering. My OS is windows 10. I set environment by,
```
set LC_ALL=en_US.UTF-8
set LANG=en_US.UTF-8
set LANGUAGE=en_US.UTF-8
```

Here is my environ variable:

#envKKPRbc_Cmdilne=
#envTSLOGRBCShellExt6100=425107680
#envTSLOGsss6100=425108320
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\aaaa\AppData\Roaming
asl.log=Destination=file
CCHZPATH=C:\CTEX\CTeX\cct\fonts
CCPKPATH=C:\CTEX\CTeX\fonts\pk\modeless\cct\dpi$d
CLASSPATH=.;C:\Program Files\Java\jdk1.8.0_73\lib;C:\Program Files\Java\jdk1.8.0_73\lib\dt.jar;C:\Program Files\Java\jdk1.8.0_73\lib\tools.jar
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-DQ6PN2H
ComSpec=C:\WINDOWS\system32\cmd.exe
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
CUDA_PATH_V7_5=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\aaaa
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_73
JRE_HOME=C:\Program Files\Java\jdk1.8.0_73\jre
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ALL=en_US.UTF-8
LOCALAPPDATA=C:\Users\aaaa\AppData\Local
LOGONSERVER=\\DESKTOP-DQ6PN2H
MEmuHyperv_Path=D:\Program Files\Microvirt\MEmuHyperv
MEmu_Path=D:\Program Files\Microvirt
NUMBER_OF_PROCESSORS=8
NVCUDASAMPLES7_5_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v7.5
NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v7.5
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\libnvvp;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\jdk1.8.0_73\bin;C:\Program Files\Java\jdk1.8.0_73\jre\bin;C:\Anaconda2;C:\Anaconda2\Scripts;C:\Anaconda2\Library\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\CTEX\UserData\miktex\bin;C:\CTEX\MiKTeX\miktex\bin;C:\CTEX\CTeX\ctex\bin;C:\CTEX\CTeX\cct\bin;C:\CTEX\CTeX\ty\bin;C:\CTEX\Ghostscript\gs9.05\bin;C:\CTEX\GSview\gsview;C:\CTEX\WinEdt;C:\Users\aaaa\bin\Sencha\Cmd\6.1.1.76/..;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
ShellLaunch{A81BA54B-CCFE-4204-8E79-A68C0FDFA5CF}=ShellExt
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\aaaa\AppData\Local\Temp
TMP=C:\Users\aaaa\AppData\Local\Temp
USERDOMAIN=DESKTOP-DQ6PN2H
USERDOMAIN_ROAMINGPROFILE=DESKTOP-DQ6PN2H
USERNAME=wangjin
USERPROFILE=C:\Users\aaaa
VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\WINDOWS

Unfortunately, it still get the error.

**Comment by alvations** [comment]
@wangjin0818 Did you managed to get the issue resolved? Could you tell us how you fixed it to help us improve `nltk`?

**Comment by wangjin0818** [comment]
This issue is caused by '\xa0' cannot be decoded by utf8. In utf8, the non-breaking space '\xa0' is equal to '\xc2\xa0'. Therefore, just replace '\xc2\xa0' will be OK.

So, I suggest to remove below code in ```stanford.py```:
```
stdout = stdout.replace(b'\xa0',b' ')
```

It works well now~. And, the issue can be closed.

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
