### ISSUE TITLE
Web Corpus

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#152]
How about we make a corpus which downloads new data from the web? I know Project Gutenberg is ridiculously easy to access using Python, how about I start with that?

Is it a requirement for corpus data to be tagged? I was thinking I could add other sources and use wordnet for tagging...<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=664</p>

**Comment by sethbuzz** [comment]
What is the extent of nltk's use of Project Gutenberg data? I'm going to be working on a PG project this summer and could easily package text up for nltk's use as well.
