### ISSUE TITLE
whitespace in corenlp_options in nltk.parse.stanford causes OSError

### ISSUE THREAD

**Issue by dblandan** [nltk/nltk#1523]
I needed to keep punctuation, so I added corenlp_options='-ouputFormatOptions includePunctuationDependencies' when creating an instance of a dependency parser.

Because corenlp_options is appended to cmd, the Popen fails.  Changing `cmd.append(self.corenlp_options)` to `cmd.extend(self.corenlp_options.split())` would fix the issue.

Edit:
The Neural Dependency Parser has a default corelnp_options that contains whitespace, and it works fine.  note that because it uses += to extend, that there is no whitespace inserted between user-defined options and default options.  

I don't know why NDP runs fine with whitespace in corenlp_options and StanfordDependencyParser does not.

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.

**Comment by darshmgandhi** [comment]
This issue hasn't yet been resolved.
