### ISSUE TITLE
NoneType() < bool() error when doing pretty format of nltk decision tree classifier in python3

### ISSUE THREAD

**Issue by ShraddhaSurana** [nltk/nltk#1524]
<classifier>.pretty_format() works fine with Python2. But this is the error I get with python3:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-629-dc64618292e3> in <module>()
----> 1 classifier.pretty_format()

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/classify/decisiontree.py in pretty_format(self, width, prefix, depth)
     84             return '%s%s %s\n' % (prefix, '.'*n, self._label)
     85         s = ''
---> 86         for i, (fval, result) in enumerate(sorted(self._decisions.items())):
     87             hdr = '%s%s=%s? ' % (prefix, self._fname, fval)
     88             n = width-15-len(hdr)

TypeError: unorderable types: NoneType() < bool()

**Comment by jonititan** [comment]
This issue also applies to .pseudocode()  

It is because there is a None which cannot be sorted in Python 3.
Line 86 
`        for i, (fval, result) in enumerate(sorted(self._decisions.items())):`

and Line 108
`        for (fval, result) in sorted(self._decisions.items()):`

in classify/decisiontree.py

If I understood better why None gets assigned as a key on a node I could submit a patch to address this.

**Comment by GerhardKa** [comment]
Why there might be a None as a node:
You might have features that don't apply (e.g. 'next_word_in_a_sentence', when at the end of a sentence).

Similarly, .pretty_format() and .pseudocode() also crash w/ TypeError when you have features with boolean values (e.g. 'Is there an adjective in this sentence?' - True/False?)

From what I see, there is not really a need to sort decisions in a special order, so one quick solution might be removing the sorting process. Or just casting the non-string values to strings to keep printing feature values in alphabetic order (possibly marking them as non-strings?).

**Comment by GerhardKa** [comment]
Was my explanation clear enough and will there be a patch?
Would love to hear that.

**Comment by GerhardKa** [comment]
@ShraddhaSurana : After having added a deterministic sort order routine to the decision tree output functions, this issue can be closed now.

**Comment by ShraddhaSurana** [comment]
Hi,

I haven't used this feature for a while now.. so do close it if you seem
fit.

Thanks,
