### ISSUE TITLE
Circular imports between probability, text and utils modules

### ISSUE THREAD

**Issue by sr-murthy** [nltk/nltk#1526]
I am running into circular import problems while preparing a PR to add some functionality to `nltk/text.py` - specifically, I am trying to write a new class `TextFreqDist` in `nltk/probability.py`, which extends `FreqDist` with some custom features, such as ignoring non-alphanumeric characters. I want to use `nltk.text.Text` in `nltk/probability.py`, but this leads to an import error:

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-2-16ae48a68ad9> in <module>()
    ----> 1 import nltk
          2 from nltk.text import Text
          3 from nltk.probability import TextFreqDist
          4 import nltk.corpus

    /Users/srm/Documents/sandeep/cst/dev/nltk/nltk/__init__.py in <module>()
        112 # Import top-level functionality into top-level namespace
        113 
    --> 114 from nltk.collocations import *
        115 from nltk.decorators import decorator, memoize
        116 from nltk.featstruct import *
    
    /Users/srm/Documents/sandeep/cst/dev/nltk/nltk/collocations.py in <module>()
         35 from nltk.compat import iteritems
         36 
    ---> 37 from nltk.probability import FreqDist
         38 from nltk.util import ngrams
     39 from nltk.metrics import ContingencyMeasures, BigramAssocMeasures, TrigramAssocMeasures
    
    /Users/srm/Documents/sandeep/cst/dev/nltk/nltk/probability.py in <module>()
         48 from functools import reduce
         49 from nltk import compat
    ---> 50 from nltk.text import Text
         51 from nltk.compat import Counter
         52 
    
    /Users/srm/Documents/sandeep/cst/dev/nltk/nltk/text.py in <module>()
         22 import re
         23 
    ---> 24 from nltk.probability import FreqDist, LidstoneProbDist
         25 from nltk.probability import ConditionalFreqDist as CFD
         26 from nltk.util import tokenwrap, LazyConcatenation
    
    ImportError: cannot import name 'FreqDist'

Would it be possible to restructure the package `__init__.py` to avoid these issues?

**Comment by sr-murthy** [comment]
I can deal this specific issue by avoid importing `nltl.text.Text` in `nltk/probability.py`, but I was wondering whether anyone else has had such issues.

**Comment by stevenbird** [comment]
Yes, the solution to this problem is to have more specific imports. Sorry I don't know of any way to organise `__init__.py` to avoid it.
