### ISSUE TITLE
Broken link prevents 'pip install nltk' from working

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#153]
<b>Please identify your OS version and what is being installed (NLTK code,</b>
<b>NLTK data, some dependent package, ...)</b>

Ubuntu 10.04, NLTK v 2.0.1rc1.

<b>What problem did you encounter with installation?</b>

'pip install nltk' fails with the following error:

  HTTP error 404 while getting http://nltk.googlecode.com/files/nltk-2.01rc1.tar.gz (from http://www.nltk.org/download)
  Could not install requirement nltk because of error HTTP Error 404: Not Found
Could not install requirement nltk because of HTTP error HTTP Error 404: Not Found for URL http://nltk.googlecode.com/files/nltk-2.01rc1.tar.gz (from http://www.nltk.org/download)

Did you find any fixes?  Please suggest ways to improve our installation instructions.

The problem is that the link to http://nltk.googlecode.com/files/nltk-2.0.1rc1.tar.gz is broken on nltk.org, where it is pointing instead to http://nltk.googlecode.com/files/nltk-2.01rc1.tar.gz (note the two missing periods).

The fix is to install with 'pip install http://nltk.googlecode.com/files/nltk-2.0.1rc1.tar.gz', but obviously what you really need to do is fix the link on the site.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=665</p>

**Comment by kmike** [comment]
Isn't this fixed? I think the NLTK was not uploaded to pypi for 2.0.1rc1; there is no mentions of 'http://www/nltk.org/download' in setup.py now and 'pip install nltk' works fine (it installs nltk from pypi).
