### ISSUE TITLE
How to use Dictionary as training data

### ISSUE THREAD

**Issue by hemangmehta** [nltk/nltk#1542]
Hi,

I have list of categories and it's synonyms in below format

> (["nsf","insufficent funds","nonsufficient funds"],"overdraft fees"),
> (["atms","withdraws"],"atm fees"),
> (["late payment","late fees"],"late payment fees")
> (["food", "hotel", "cafe"], "restaurant")

How can i train classifier, so that if i will classify `atms` it should return me `atm fees`
for
nsf -> overfraft fees
food -> restaurant

how to solve this problem ?

**Comment by stevenbird** [comment]
@hemangmehta: sorry, this is not a valid issue. You can post to nltk-users or stackoverflow.
