### ISSUE TITLE
There is no easy way to add new synsets/lemmas to the wordnets

### ISSUE THREAD

**Issue by fcbond** [nltk/nltk#1548]
It would be good if it were possible to e.g., create a new synset named company and add the words into it.

for example: 
Synsets: company_synonyms

words to be added:
tata consultancy ser

**Comment by mayank-20-nayyar** [comment]
The idea is quite cool and i would like to work on it. As i aim to wish my first contribution to NLTK (but having worked on NLTK for long ) can any of the the core contributors guide me where to begin. It would be great opportunity for me to take up this issue. 
Thanks in advance.

**Comment by dimazest** [comment]
Hi, I would be happy to help you.

Did you check out the source code of NLTK and run the tests? That's usually a good starting point.

Do you have an idea of the API? What would be the methods you add to NLTK? I guess, it's also important to be able to share the new definitions, as essentially wordnet is extended.

**Comment by stevenbird** [comment]
@fcbond is this proposed for local customisations to the WordNet database, via a new API? And would it include adding content and relations to existing synsets? Would it be better to have people contribute directly to one of the original WordNets perhaps?

**Comment by alvations** [comment]
@fcbond here's a wild idea but maybe it's worth the effort to have a new API that maps WN into a [networkx](http://networkx.readthedocs.io/en/stable/) graph structure. And additional synsets/lemmas can be treated as nodes with different edges.
