### ISSUE TITLE
nltk.classify.decisiontree.demo() fails on 2.0.1rc1

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#155]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>
&gt;&gt;&gt; nltk.**version**
'2.0b9'
on Mac with Python 2.7.1

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
Running the Decision Tree demo (nltk.classify.decisiontree.demo()) fails on 2.0.1rc1 but runs fine on 2.0b9.

<b>What is the expected output? What do you see instead?</b>
Below I show the correct output from nltk 2.0b9 and the error with 2.0.1rc1:
###### 

Python 2.7.1 (r271:86882M, Nov 30 2010, 10:35:34) 
[GCC 4.2.1 (Apple Inc. build 5664)] on darwin
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; import nltk
&gt;&gt;&gt; nltk.**version**
'2.0b9'
&gt;&gt;&gt; nltk.classify.decisiontree.demo()
Training classifier...
best stump for   5000 toks uses endswith(vowel)=False err=0.2556
best stump for   1802 toks uses has(y)=False         err=0.3152
best stump for   1612 toks uses startswith(k)=False  err=0.3033
...
    if has(k) != False: 
      if count(m) == 2: return 'male'
      if count(m) != 2: return 'female'
###### 
###### 

Python 2.7.1 (r271:86882M, Nov 30 2010, 10:35:34) 
[GCC 4.2.1 (Apple Inc. build 5664)] on darwin
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; import nltk
&gt;&gt;&gt; nltk.**version**
'2.0.1rc1'
&gt;&gt;&gt; nltk.classify.decisiontree.demo()
Training classifier...
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/classify/decisiontree.py&quot;, line 281, in demo
    binary_names_demo_features)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/classify/util.py&quot;, line 182, in names_demo
    classifier = trainer( [(features(n), g) for (n,g) in train] )
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/classify/decisiontree.py&quot;, line 276, in f
    return DecisionTreeClassifier.train(x, binary=True, verbose=True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/classify/decisiontree.py&quot;, line 156, in train
    feature_names, labeled_featuresets, feature_values, verbose)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/classify/decisiontree.py&quot;, line 256, in best_binary_stump
    fname, fval, labeled_featuresets)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/classify/decisiontree.py&quot;, line 245, in binary_stump
    default = DecisionTreeClassifier(neg_fdist.max())
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/probability.py&quot;, line 283, in max
    self._max_cache = max([(a,b) for (b,a) in self.items()])[1] 
ValueError: max() arg is an empty sequence
###### 

<b>Please use labels and text to provide additional information.</b>
I haven't debugged this issue, I upgraded from 2.0b9 to 2.0.1rc1 this morning. I have already filed http://code.google.com/p/nltk/issues/detail?id=667 but I don't think these are related.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=668</p>

**Comment by denzilc** [comment]
Is there a fix to this? I confirm this issue too.

**Comment by kmike** [comment]
I'm closing this in favor of more recent ticket (#297).
