### ISSUE TITLE
word_tokenizer and Spanish

### ISSUE THREAD

**Issue by bargri** [nltk/nltk#1558]
I would like to have a word_tokenizer that works with Spanish. For example, this code:

`import nltk
from nltk.tokenize import word_tokenize
sentences = "¿Quién eres tú? ¡Hola! ¿Dónde estoy?"
spanish_sentence_tokenizer = nltk.data.load('tokenizers/punkt/spanish.pickle')
sentences = spanish_sentence_tokenizer.tokenize(sentences)
for s in sentences:
    print([s for s in vword_tokenize(s)])`

gives the following:

`['¿Quién', 'eres', 'tú', '?']
['¡Hola', '!']
['¿Dónde', 'estoy', '?']`

 but I would have expected the following instead:

`['¿' ,'Quién', 'eres', 'tú', '?']
['¡' ,'Hola', '!']
['¿' ,'Dónde', 'estoy', '?']`

**Comment by alvations** [comment]
C.f. #1214, there are quite a few alternative tokenizers in NLTK =)

E.g. using NLTK port of @jonsafari [toktok tokenizer](https://github.com/jonsafari/tok-tok):

```python
>>> import nltk
>>> nltk.download('perluniprops')
[nltk_data] Downloading package perluniprops to
[nltk_data]     /Users/liling.tan/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
True
>>> nltk.download('nonbreaking_prefixes')
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /Users/liling.tan/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
True
>>> from nltk.tokenize.toktok import ToktokTokenizer
>>> toktok = ToktokTokenizer()
>>> sent = u"¿Quién eres tú? ¡Hola! ¿Dónde estoy?"
>>> toktok.tokenize(sent)
[u'\xbf', u'Qui\xe9n', u'eres', u't\xfa', u'?', u'\xa1Hola', u'!', u'\xbf', u'D\xf3nde', u'estoy', u'?']
>>> print " ".join(toktok.tokenize(sent))
¿ Quién eres tú ? ¡Hola ! ¿ Dónde estoy ?

>>> from nltk import sent_tokenize
>>> sentences = u"¿Quién eres tú? ¡Hola! ¿Dónde estoy?"
>>> [toktok.tokenize(sent) for sent in sent_tokenize(sentences, language='spanish')]
[[u'\xbf', u'Qui\xe9n', u'eres', u't\xfa', u'?'], [u'\xa1Hola', u'!'], [u'\xbf', u'D\xf3nde', u'estoy', u'?']]

>>> print '\n'.join([' '.join(toktok.tokenize(sent)) for sent in sent_tokenize(sentences, language='spanish')])
¿ Quién eres tú ?
¡Hola !
¿ Dónde estoy ?
```

If you hack the code a little and add `u'\xa1'` in https://github.com/nltk/nltk/blob/develop/nltk/tokenize/toktok.py#L51 , you should be able to get:

```
[[u'\xbf', u'Qui\xe9n', u'eres', u't\xfa', u'?'], [u'\xa1', u'Hola', u'!'], [u'\xbf', u'D\xf3nde', u'estoy', u'?']]
```

**Comment by bargri** [comment]
Thanks for your quick reply. I did as you directed but toktok isn't installed. What else do I need to do?

`>>> import nltk
nltk.download('perluniprops')
>>> nltk.download('perluniprops')
[nltk_data] Downloading package perluniprops to
[nltk_data]     /Users/barry/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
True
>>> nltk.download('nonbreaking_prefixes')
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /Users/barry/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
True
>>> from nltk.tokenize.toktok import ToktokTokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named toktok`

**Comment by alvations** [comment]
Please update your NLTK (but i think the toktok tokenizer is not in the official release, i.e. master branch yet).

```
pip install -U nltk
```

Please wait for the next version release to use the toktok Tokenizer. 

----

Meanwhile, if you urgently need to use the toktok tokenizer, it should reside in the development branch :

```
pip install -U https://github.com/nltk/nltk/archive/develop.zip
```

Note that the development branch is not an official release, it is subjected to unattested bugs. If you just need the ToktokTokenizer, you can get it directly from the source file at https://github.com/nltk/nltk/blob/develop/nltk/tokenize/toktok.py (it should be quite independent from NLTK, since it's made up of some clean regex substitutions)

**Comment by bargri** [comment]
Ok thanks! When I use this tokeniser I still get unexpected behaviour:

> ['¿', 'Quién', 'eres', 'tú', '?']
> ['¡Hola', '!']
> ['¿', 'Dónde', 'estoy', '?']

Notice '¡Hola'. This is an issue with toktok.pl. I have reported an issue here: https://github.com/jonsafari/tok-tok/issues/2

**Comment by alvations** [comment]
Please look at #1559 and jonsafari/tok-tok#1 .
