### ISSUE TITLE
panlex_lite installation

### ISSUE THREAD

**Issue by Nishkarshk** [nltk/nltk#1560]
Hello All,

I know this issues is raised in other threads as well, sorry for a new threads as i did not got answer of what i am looking for 

System : Mac,
OS        : OS X, 13F1911
Python Version : 3.5.2
Nltk Version : 3.2.1

Downloaded all packages. Command Used
python3
>>>import nltk
>>>nltk.download()

panlex_lite download get stuk

Tried downloading few time
Tried downloading panlex_lite.zip independently

In both of the above cases got a file of 2.34 GB

When i replaced the corrupted file in nltk_data/corpora/ folder

tried >>>nltk.download() again no luck

Tried with zip file and also after unzipping it

output of suggested code 
import zipfile
>>> plzip = '/Users/nishkarsh/nltk_data/corpora/panlex_lite.zip'
>>> [zifo.CRC for zifo in zipfile.ZipFile(plzip).infolist()]
[0, 448887900, 3816634357]

The python popup is showing out of date only.

![screen shot 2016-12-27 at 3 32 19 pm](https://cloud.githubusercontent.com/assets/24789485/21497371/7846273e-cc4a-11e6-9ba6-fd0e077bd4bc.png)

![screen shot 2016-12-27 at 3 38 27 pm](https://cloud.githubusercontent.com/assets/24789485/21497389/8bb7b396-cc4a-11e6-958f-593df41ceedd.png)

Can any one plz help the way forward

**Comment by stevenbird** [comment]
@kamholz: would you please advise?

**Comment by kamholz** [comment]
@stevenbird panlex_lite was recently regenerated. Probably the checksum in the index.xml is wrong. How can we make sure it's always up to date?

**Comment by iranianpep** [comment]
I had the same issue. I used `nltk.download('all')` and got timeout error at `panlex_lite`

**Comment by stevenbird** [comment]
I've made the panlex corpus point to a dated version (currently `panlex_lite-20170401.zip`) and updated the checksums. Please try again, and open a new issue if the problem persists.
