### ISSUE TITLE
Non-standard calculation of (Shannon) entropy in NgramModel

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#157]
This applies to 2.01rc1 at least.

The code for calculating the entropy of a text in regard to the learned n-gram model calculates the entropy as the sum of the negative log-probabilities.

/trunk/nltk/nltk/model/ngram.py  line 133:
133:             e += self.logprob(token, context)

Shouldn't this be:
e += self.prob(token, context) \* self.logprob(token, context)
Shannon entropy is the -1 \times the sum of the product of the probability and the log-probability.

This could be re-implemented to call the probability calculation function only once by doing:
token_prob = self.prob(token, context)
e += token_prob \* -log(token_prob, 2)<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=672</p><hr/><h2>earlier comments</h2>

<p><strong>rico.sennrich@gmx.ch said, at 2011-07-21T16:02:23.000Z:</strong></p>

<p>for "weighting" each log probability, you don't want to use the model probability, but the "true" probability, which we don't know.

A common approximation is to add all log probabilities of a text together, then divide the result by the number of tokens in the text.

source: http://en.wikipedia.org/wiki/Cross-entropy</p>

**Comment by kmike** [comment]
I don't know if the issue is valid, but making this change would be backwards incompatible, so it is better to figure it out before NLTK 3.

**Comment by alexrudnick** [comment]
Taking a look at J&M (2nd edition, page 117); rico.sennrich seems to be on the right track...

**Comment by alexrudnick** [comment]
OK, taking a look at that formula and the current code for entropy in ngram.py, I'm pretty convinced that the code does what the formula does.

I'm going to go ahead and close this issue -- pretty sure it's a non-problem! Happy to re-open it if we disagree.
