### ISSUE TITLE
cant use nltk functions in parallel programs 

### ISSUE THREAD

**Issue by ghost** [nltk/nltk#1576]
when I want to use nltk stemmer and lemmatizer in a multithreaded program only one thread works fine and other ones throw this exception : 

Exception in thread 2:
Traceback (most recent call last):
  File "C:\Users\Danial\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Danial\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:/iaun/0_Tez/141095-TFATOwithdiscriminative/01/11_MultiThreadedDoctTermInfo.py", line 21, in myfunc
    lemma = lemmatizer.lemmatize(stem)
  File "C:\Users\Danial\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\stem\wordnet.py", line 40, in lemmatize
    lemmas = wordnet._morphy(word, pos)
  File "C:\Users\Danial\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\corpus\util.py", line 99, in __getattr__
    self.__load()
  File "C:\Users\Danial\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\corpus\util.py", line 73, in __load
    args, kwargs  = self.__args, self.__kwargs
AttributeError: 'WordNetCorpusReader' object has no attribute '_LazyCorpusLoader__args'

**Comment by dimazest** [comment]
Try to import nltk inside of a worker function. In your case it should be `myfunc`.

**Comment by stevenbird** [comment]
Thanks @dimazest.
Is this now resolved @danitiger33?

**Comment by lasit19** [comment]
Hey, I am having the similar issue. Is there any way to solve this error? I have tried importing nltk locally and tried the solution on this [page](https://stackoverflow.com/questions/27433370/what-would-cause-wordnetcorpusreader-to-have-no-attribute-lazycorpusloader/27437149#27437149)

thanks in advance!!!!

**Comment by ndvbd** [comment]
Any news here?  Is NLTK thread safe?

**Comment by purificant** [comment]
It would help to have a minimal reproducible test case for this issue.

**Comment by ndvbd** [comment]
@purificant simply to run wordnet synsets in multiple threads, generate these annoying problems.

**Comment by spearsem** [comment]
Is there any progress on this? I am running into this when using pytest-xdist to parallelize a series of pytest unit tests. In a module, I import wordnet, and that module is used for several parallelized tests. At the pytest-xdist level, I have no control over sequestering this into an isolated function to be called in each worker thread.

**Comment by ndvbd** [comment]
I solved it by wrapping the wn.synsets(word) with a lock:
```

from threading import Lock
synset_lock = Lock() 
synset_lock.acquire()
all_sysnets = list(wn.synsets(word))
synset_lock.release()
```

**Comment by spearsem** [comment]
@ndvbd in the context of parallel unit test execution with pytest-xdist, this does not appear to work. I placed the import of wordnet into a session-level pytest fixture, and then made all the relevant functions accept the module itself as an argument, such as:

```
synset_lock = Lock()  # multiprocessing.Lock for pytest-xdist

def get_synset(word, pos, wordnet):
    synset_lock.acquire()
    all_synsets = list(wordnet.synsets(word, pos=pos)
    synset_lock.release()
    return all_synsets
```

and then a test file will use the fixture

```
@pytest.fixture(scope='session')
def threadsafe_wordnet():
    nltk.download('wordnet')
    from nltk.corpus import wordnet
    wordnet.ensure_loaded()
    return wordnet
```

such as

```
@pytest.mark.parametrize('word', ['dog', 'cat', 'bat'])
def test_wordnet(threadsafe_wordnet, word):
    assert len(get_synsets(word, pos=threadsafe_wordnet.NOUN, threadsafe_wordnet)) >= 1
```

I found that if I don't wrap the import of wordnet inside a pytest fixture like this, I can't even get pytest to proceed past the test collection phase. It seems to choke immediately at the first attempt to import my module where I am importing wordnet and calling `nltk.download`.

Even after getting it to proceed past module imports, this fixture approach creates all kinds of crazy issues with parallel test execution, ranging from unexplainable deadlocks, crashing test workers, and errant attempts to re-download wordnet (even though it is verifiable installed in the nltk data folder being used by all the tests).

I feel very much at a loss of what else to try.

**Comment by vcnwafor** [comment]
Please I am having the same issue using nltk in multithread.


`
from typing import List

from nltk.corpus import wordnet
def get_synonyms(sentence: str) -> List[str]:
    last_word = sentence.replace(".", "").split(" ")[-1].lower()

    synonyms = [
        lm.name().replace("_", " ")
        for syn in get_synsets(last_word)
        for lm in syn.lemmas()
    ]
    return list(set(synonyms))


def get_antonyms(sentence: str) -> List[str]:
    last_word = sentence.replace(".", "").split(" ")[-1].lower()

    antonyms = [
        lm.antonyms()[0].name().replace("_", " ")
        for syn in get_synsets(last_word)
        for lm in syn.lemmas()
        if lm.antonyms()
    ]
    return list(set(antonyms))`
