### ISSUE TITLE
Tokenize `xml_escape` tests are failing

### ISSUE THREAD

**Issue by fievelk** [nltk/nltk#1577]
Tests for `tokenize.util.xml_escape` are currently failing, see [Jenkins CI test](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/TOXENV=py27-jenkins,jdk=jdk8latestOnlineInstall/testReport/nltk.tokenize/util/xml_escape).

**Comment by stevenbird** [comment]
@alvations – would you please look into this?

**Comment by stevenbird** [comment]
@alvations – looks like we still have this error on the [CI server](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/TOXENV=py35-jenkins,jdk=jdk8latestOnlineInstall/testReport/nltk.tokenize/util/xml_escape/)

**Comment by stevenbird** [comment]
Thanks @alvations
