### ISSUE TITLE
Corpus Reader failures

### ISSUE THREAD

**Issue by fievelk** [nltk/nltk#1596]
@alvations #1593 seems to have broken tests: [Jenkins CI failures][1].

[1]: https://nltk.ci.cloudbees.com/job/nltk/639/testReport/

**Comment by alvations** [comment]
@fievelk as for the Python2 tests, I think it has to do with how the tests are carried out. I'll leave that to you. If it's otherwise, i'll look into it.

For the Python3 tests, I've just updated the index on `nltk_data`. Is there anyway to force run a build? Other than creating fake PRs (which I don't hope we do ;P)?

**Comment by fievelk** [comment]
@alvations Regarding `nltk_data` changes, you can run tests on your platform using `tox` (see [NLTK Testing][1]). You can simply run the `tox` command from within the NLTK root folder and it will run tests for python 2.7, 3.4, 3.5 and also tests that are usually intended to be run on Jenkins, our CI platform.
If you want to exclude Jenkins tests you can run `tox -e py27,py34,py35`.

Please note that, currently, CI tests are only supposed to be a safety net for us, so that we can decide whether new PRs should be merged or not. In general, [NLTK contribution guidelines][2] ask contributors to run tests on their machine before submitting a new PR (unless this is marked as Work In Progress, which means that it is not ready to be merged yet). 

EDIT: Jenkins tests will also download all nltk data contents from scratch, so this could actually help you with your tests. You can run jenkins tests using `tox -e py27-jenkins,py34-jenkins,py35-jenkins`. You can find jenkins-related commands in `jenkins.sh`.

[1]: http://www.nltk.org/dev/local_testing.html
[2]: https://github.com/nltk/nltk/blob/develop/CONTRIBUTING.md

**Comment by fievelk** [comment]
@alvations Regarding python 2 tests, could you please elaborate further? What do you mean when you say that test failures might have to do with how tests are carried out?

**Comment by alvations** [comment]
@fievelk thanks for the tips on testing. The errors occurring in Python2 is because of the use of `python_2_unicode_compatible`. And I'm not sure but on my machine, tox tests run fine. Let me retry and see what's wrong.

**Comment by stevenbird** [comment]
Thanks for the fixes @alvations
