### ISSUE TITLE
MWAPPDB corpus fails build tests

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1606]
The CI server reports an [error](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/TOXENV=py35-jenkins,jdk=jdk8latestOnlineInstall/testReport/nltk.test.unit.test_corpora/TestMWAPPDB/test_entries/) with the `mwa_ppdb` corpus.

**Comment by alvations** [comment]
@stevenbird sorry about the test failures on `mwa_ppdb`. It seems like it's not reading the `.zip` file correctly. Maybe we should remove all the `mwa_ppdb` code for now.
