### ISSUE TITLE
Rewritten readability tests from nltk_contrib

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#161]
Hi,

I wanted to use readability tests from nltk_contrib package. The code does not meet my requirements (like choosing between Dutch and English) and I have rewritten it.

I put it there so others could use the work as well. Maybe it could become a part of official nltk package? I would like to edit it so it meets the code standard of nltk.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=677</p><hr/><h2>earlier comments</h2>

<p><strong>alex.rudnick said, at 2011-05-24T06:34:59.000Z:</strong></p>

<p>Thanks for submitting updates!

Could you outline the changes you made? Improvements are always welcome!

Are you interested in contributing this as part of nltk_contrib? (could it maybe be merged in to the existing readability package, or would you prefer it to be separate?)</p><p><strong>izidor.matusov said, at 2011-05-24T06:58:19.000Z:</strong></p>

<p>I made these changes:
 1) The original readability tests module of nltk_contrib contains code which is not related to readability tests. That code was removed.
 2) Repaired a few lines so the code actually runs in the current version of Python.
 3) Removed support for Dutch
 4) Polished interface
 5) Rewritten code, so pylint does not nag so much.

Yes, I am interested. It could be merged but there are many radical changes so it could be a problem for someone who uses the previous readability package.</p>

**Comment by kmike** [comment]
I think this should be migrated to https://github.com/nltk/nltk_contrib repository.

**Comment by kmike** [comment]
Migrated to https://github.com/nltk/nltk_contrib/issues/5.
