### ISSUE TITLE
Expose _synset_from_pos_and_offset as a public method

### ISSUE THREAD

**Issue by ExplodingCabbage** [nltk/nltk#1618]
Two reasons for this:

1. Given that http://stackoverflow.com/a/27145655/1709587 has thousands of views and 6 upvotes, it seems that people are already using it. Pragmatism suggests that it should therefore be exposed publicly; it's not good to have a notionally-private-but-public-in-practice part of an API.
2. The fact that NLTK chooses to expose the `offset()` of synsets via a public method means that there's currently no philosophy of hiding the (ugly! awful! fragile!) offset-based data structure of WordNet, and given that offset information is being exposed, looking up a synset by offset (perhaps the single most basic offset-related task you'd ever want to do, more fundamental than wanting to know a given synset's offset) seems like something that NLTK should support and is an odd gap in the current API.

Precisely because of point 1, the old `_`-prefixed method should remain too to preserve backwards compatibility, at least until the next major release.

**Comment by alvations** [comment]
I haven't update the `pywsd` code for some time but here's some other functions that people playing around with WordNet might also like: https://github.com/alvations/pywsd/blob/master/pywsd/utils.py
