### ISSUE TITLE
Update omw data

### ISSUE THREAD

**Issue by ExplodingCabbage** [nltk/nltk#1619]
It's definitely at least a little out of date (or perhaps was incomplete at the time of being added into NLTK); per http://compling.hss.ntu.edu.sg/omw/, there is a Romanian (language code 'ron') WordNet that is part of OMW but it's not part of NLTK's OMW corpus:

```
>>> nltk.corpus.wordnet.langs()
['eng', 'als', 'arb', 'bul', 'cat', 'cmn', 'dan', 'ell', 'eus', 'fas', 'fin', 'fra', 'glg', 'heb', 'hrv', 'ind', 'ita', 'jpn', 'nno', 'nob', 'pol', 'por', 'qcn', 'slv', 'spa', 'swe', 'tha', 'zsm']
```

**Comment by stevenbird** [comment]
@fcbond – do you have plans for updating the NLTK version?

**Comment by ekaf** [comment]
Omw 1.4 was added in #2899.
