### ISSUE TITLE
Re-organizing and refactoring nltk/test

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1628]
I suggest that we do some refactoring/reorganizing of `nltk/test/`. Currently the `*.doctest` files are on the `nltk/test` mixed with the `tox` and CI config files and scripts. 

Possibly, this would be a better organization:

```
nltk
    /test
        /doctests
            *.doctest
        /unittests
            *.py
        /ipynbs
           *.ipynb
        # all other files for tox and CI
```

@stevenbird @fievelk any suggestions?

**Comment by dimazest** [comment]
I like the idea, maybe it worth moving the test folder out of the nltk package.

**Comment by fievelk** [comment]
I agree, I think these are good ideas. 
I don't have enough time at the moment, so I encourage contributors to work on it if they can. Otherwise I will try to work on it as soon as possible.

**Comment by stevenbird** [comment]
I also like the idea of cleaning up the test directory. I'm not so keen on moving it, unless there is some benefit. Let's keep in mind the need to build the NLTK howtos (which come from the doctest files).
