### ISSUE TITLE
Instal/Upgrade to 2.01rc1 using easy_install fails

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#163]
The version I am using is irrelevant, I am attempting to Upgrade to 2.01rc1

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
easy_install -U nltk

<b>What is the expected output? What do you see instead?</b>
I expected an easy installation, I got a 404 Not Found error.

Searching for nltk
Reading http://pypi.python.org/simple/nltk/
Reading http://nltk.sf.net/
Reading http://www.nltk.org/
Reading http://nltk.org/
Reading http://www.nltk.org/download
Best match: nltk 2.01rc1
Downloading http://nltk.googlecode.com/files/nltk-2.01rc1.tar.gz
error: Can't download http://nltk.googlecode.com/files/nltk-2.01rc1.tar.gz: 404 Not Found

<b>Please use labels and text to provide additional information.</b>
OMG, WTF, HELP, NTLK

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=684</p><hr/><h2>earlier comments</h2>
<p><strong>kmike84 said, at 2011-07-13T22:52:41.000Z:</strong></p>
<p>This looks similar to http://code.google.com/p/nltk/issues/detail?id=534 . 

The following works for me on Debian Squeeze (unlike pip install nltk):

pip install http://pypi.python.org/packages/source/n/nltk/nltk-2.0.1rc1.tar.gz
</p>

**Comment by stevenbird** [comment]
Use pip instead.
