### ISSUE TITLE
StanfordPnOSTagger failed to tag the underscore

### ISSUE THREAD

**Issue by dongfang91** [nltk/nltk#1632]
Please see the python code below:

from nltk.tag.stanford import StanfordPOSTagger

english_postagger = StanfordPOSTagger('./models/english-left3words-distsim.tagger', './stanford-postagger.jar')
english_postagger.java_options='-mx4096m'

print english_postagger.tag(['_'])

Here is my result:
[(u'', u'SYM')]

The underscore just disappeared. I checked the code, that's because in function "parse_output(self, text, sentences = None)", the code "word_tags = tagged_word.strip().split(self._SEPARATOR)" would delete all "_SEPARATOR" which is underscore based on the result of StandfordTagger.

One suggestion, probably we can use this line of code instead:  
word_tags = tagged_word.strip().rsplit(self._SEPARATOR,1)

**Comment by ludens11** [comment]
where should i put those code to fix underscore issue?

**Comment by dimazest** [comment]
Please create a pull request. https://help.github.com/articles/creating-a-pull-request/

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
