### ISSUE TITLE
easy_install fails on Fedora 14 (x86_64)

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#164]
Hello,

easy_install fails with the recent download links. However it works fine with regular source installation of nltk.

[gsever@ccn Desktop]$ sudo easy_install nltk
[sudo] password for gsever: 
install_dir /usr/lib/python2.7/site-packages/
Searching for nltk
Reading http://pypi.python.org/simple/nltk/
Reading http://nltk.sf.net/
Reading http://www.nltk.org/
Reading http://nltk.org/
Reading http://www.nltk.org/download
Best match: nltk 2.01rc1
Downloading http://nltk.googlecode.com/files/nltk-2.01rc1.tar.gz
error: Can't download http://nltk.googlecode.com/files/nltk-2.01rc1.tar.gz: 404 Not Found

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=687</p>

**Comment by stevenbird** [comment]
We now support pip.
