### ISSUE TITLE
FreqDist.N() is extremely inefficient

### ISSUE THREAD

**Issue by sim642** [nltk/nltk#1640]
I am currently using NLTK to train and apply a model based on conditional probabilities. For this I'm using `ConditionalProbDist` constructed from a `ConditionalFreqDist`. During the use of the trained model I noticed extreme slowness for what should simply be arithmetics on conditional probabilities and started to investigate.

A quick profiling run revealed that most (over 99%) of my program's time was being spent evaluating `FreqDist.N()`. A probability distribution used for a `ConditionalProbDist`, such as `MLEProbDist`, calls `FreqDist.freq(sample)`, which in turn is calling `FreqDist.N()` to calculate the probability. The implementation of `FreqDist.N()` looks like:
```python
    def N(self):
        return sum(self.values())
```

The alarming part in there is the `sum` which iterates over the entire frequency distribution. This causes an innocent `FreqDist.freq(sample)` call, which is supposed to be a trivial division of two numbers that could be an O(1) operation, turn into an O(n) operation. When using conditional probability distributions to model anything sufficiently big (e.g. n-grams), such distribution will contain a massive number of `FreqDist`s, each one itself containing a massive number of values, slowing a program relying on this down by multiple orders of magnitude as every single probability calculation iterates through the entire distribution, a completely unnecessary and wasteful operation.

All of which leads to some questions:

* Is there a reason `FreqDist.N()` is implemented this way?
* Why wouldn't a `FreqDist` simply keep track of its `N` so such lookup would be constant?

**Comment by vthorsteinsson** [comment]
See also https://github.com/nltk/nltk/issues/1665 which suggests a fix that would at least make POS tagging much quicker.

**Comment by stevenbird** [comment]
Resolved.
