### ISSUE TITLE
Adding Github topics 

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1644]
Github introduced topic tags to tag repositories: https://github.com/blog/2309-introducing-topics

It'll be great if we add at least `nltk`, `nlp`, `python`  tags to the repository..

**Comment by fievelk** [comment]
I agree. I think we could also use `machine learning`, for example.

**Comment by stevenbird** [comment]
@alvations: are you able to do this directly? Let me know if you need extra permissions.

**Comment by alvations** [comment]
@stevenbird I can't add the topics directly. Possibly only owners and repo admins can do it. But it can be easily added on the main page https://github.com/nltk/nltk just below the `NLTK Source http://nltk.org/` header.

**Comment by stevenbird** [comment]
@alvations: sorry for the delay. I've given you more privileges – are you able to do it yourself now?

**Comment by alvations** [comment]
@stevenbird It looks like only repo owner can add the topics. I don't see the topics adding on my end on https://github.com/nltk/nltk but I could see it on my fork though: https://github.com/alvations/nltk

**Comment by nschneid** [comment]
@stevenbird You should be able to do this at https://github.com/nltk/nltk right under where it says "NLTK Source".

**Comment by stevenbird** [comment]
Done, thanks. Please let me know if there's any others.

**Comment by alvations** [comment]
Great! Thanks @stevenbird !
