### ISSUE TITLE
nltk data download error 503: first byte time out.

### ISSUE THREAD

**Issue by jinxuan** [nltk/nltk#1647]
I'm using `python -m nltk.downloader all` to download the nltk data.  But face a lot of following errors.

> [nltk_data]    | Error downloading u'cmudict' from
> [nltk_data]    |     <https://raw.githubusercontent.com/nltk/nltk_data
> [nltk_data]    |     /gh-pages/packages/corpora/cmudict.zip>:   HTTP
> [nltk_data]    |     Error 503: first byte timeout

> [nltk_data]    | Error downloading u'moses_sample' from
> [nltk_data]    |     <https://raw.githubusercontent.com/nltk/nltk_data
> [nltk_data]    |     /gh-pages/packages/models/moses_sample.zip>:
> [nltk_data]    |     HTTP Error 503: first byte timeout

Python version is 2.7.12. nltk version is 3.2.2. On Ubuntu 16.04

**Comment by gmarmstrong** [comment]
Related to nltk/nltk_data#66. Both issues were submitted on the same day by different users, and I cannot replicate the issue now, so I imagine this was a temporary server outage.

**Comment by alvations** [comment]
This seems to temporary down-age from github. Related to but not similar cause as #1787

**Comment by alvations** [comment]
@stevenbird Hmmm, it looks like Github is doing it again, limiting bandwidth and it's causing CI to fail =( https://nltk.ci.cloudbees.com/job/pull_request_tests/799/PYV=2.7.14,jdk=jdk8latestOnlineInstall/console

**Comment by zxiiro** [comment]
We're experiencing this issue as well.

**Comment by alvations** [comment]
This is due to GitHub outage. Please try again and monitor https://status.github.com/messages

**Comment by lehmus** [comment]
Experiencing this issue today, every time I try to run

>nltk.download('all')

Even though Github status page states that all systems are fully operational. Fortunately I can circumvent the issue by downloading the packages separately, ie.

>nltk.download(['stopwords', 'punkt']).
