### ISSUE TITLE
Porting several stemming algorithms to NLTK

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1648]
`whoosh` has a couple of great things that we can port to NLTK, other than the porter stemmer, there are:

 - [Paice-Husk stemming ](https://bitbucket.org/mchaput/whoosh/src/e344fb64067e45d47ec62dc65a75a50be51264a7/src/whoosh/lang/paicehusk.py?at=default&fileviewer=file-view-default) 
 - [Lovin stemmer](https://bitbucket.org/mchaput/whoosh/src/e344fb64067e45d47ec62dc65a75a50be51264a7/src/whoosh/lang/lovins.py?at=default&fileviewer=file-view-default)

This will be an easy port since the original implementation is in Python. Simply port the code, write some tests and document the functions appropriately, put the module in `nltk/nltk/stem/` and do a pull-request =)

Any takers?

**Comment by stevenbird** [comment]
+1

**Comment by bora-pajo** [comment]
+1

**Comment by jaehoonhwang** [comment]
Hi, can I try this one?

**Comment by alvations** [comment]
@jaehoonhwang Sure! Try porting the stemmers one at a time and then do a PR and if you need help, we can guide you through it =)

Start with https://github.com/nltk/nltk/blob/develop/CONTRIBUTING.md

**Comment by ayushmandey97** [comment]
Hey, are there any more enhancements required for this? Would be happy to help.
