### ISSUE TITLE
nltk.MaxentClassifier.train can't optimize with scipy 0.9.0

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#165]
NLTK Version: 2.0.1rc1

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
1. Install scipy 0.9.0.
2. The demo reproduces the problem:

import nltk.classify.maxent
nltk.classify.maxent.demo()

The problem is not unique to the demo. It holds whenever nltk.MaxentClassifier.train is called using one of the scipy algorithms. Everything works fine with the other algorithms, or with scipy 0.8.0.

<b>What is the expected output? What do you see instead?</b>

The demo should train and assess a names classifier. Instead, it displays &quot;Grad eval #0&quot; and never moves off of that.

<b>Please use labels and text to provide additional information.</b>

I'm running Python 2.6.6, and I was trying with the corresponding &quot;2.6&quot; versions of numpy and scipy.

I'm on a Mac.

I eventually settled on NumPy 1.4.1 and SciPy 0.8.0, which seem to do well together and get along with NLTK. NumPy 1.5.1 works with SciPy 0.8.0, but it delivers a lot of deprecation warnings.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=688</p><hr/><h2>earlier comments</h2>
<p><strong>leon@dcs.shef.ac.uk said, at 2011-07-14T14:55:26.000Z:</strong></p>
<p>I'm sometimes seeing this with NumPy 1.3.0, SciPy 0.7.0 in both NLTK 2.0b9 and the current revision (2.0.1rc1 r8802):

Training classifier
training: 1326 test: 200
Grad eval #0
/usr/lib/python2.6/dist-packages/numpy/lib/utils.py:108: DeprecationWarning: rmatvec is deprecated
  warnings.warn(str1, DeprecationWarning)
/usr/lib/python2.6/dist-packages/numpy/lib/utils.py:108: DeprecationWarning: matvec is deprecated
  warnings.warn(str1, DeprecationWarning)
  norm of gradient = 1.76242441379e-14
Function eval # 0
  dual is  0.0
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 0
         Function evaluations: 1
         Gradient evaluations: 1
</p>

**Comment by kmike** [comment]
scipy.maxentropy is deprecated and we decided to drop support for it in nltk.MaxentClassifier
