### ISSUE TITLE
Unable to find stanford-postagger.jar on CI server

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1658]
The CI server reports that NLTK cannot find the Stanford POS tagger:
https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/TOXENV=py27-jenkins,jdk=jdk8latestOnlineInstall/testReport/nltk.tag/stanford/StanfordPOSTagger/

Cf. http://stackoverflow.com/questions/34726200/nltk-was-unable-to-find-stanford-postagger-jar-set-the-classpath-environment-va

**Comment by alvations** [comment]
This requires the same hack from https://gist.github.com/alvations/e1df0ba227e542955a8a. I think a more principled way to handle this is to complete #1249 and then wrap the new stanford API in StanfordPOSTagger, StanfordNETagger, StanfordDependencyParser, StanfordParser and StanfordTokenizer

**Comment by stevenbird** [comment]
Thanks @alvations. But I noticed a problem in `jenkins.sh`,
 and hope this resolves the problem (https://github.com/nltk/nltk/commit/f3a40c5ee4f7a7d7f455aa758fba99a44949332e).

**Comment by stevenbird** [comment]
Problem solved [except for Python 2.7](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/TOXENV=py27-jenkins,jdk=jdk8latestOnlineInstall/testReport/nltk.tag/stanford/StanfordPOSTagger/).

**Comment by stevenbird** [comment]
Mysteriously resolved for Python 2.7 as well.
