### ISSUE TITLE
easy_install NLTK 2.0.1rc1 Source failed on Ubuntu 11.04

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#166]
sudo easy_install http://nltk.googlecode.com/files/nltk-2.0.1rc1.tar.gz
Downloading http://nltk.googlecode.com/files/nltk-2.0.1rc1.tar.gz
Processing nltk-2.0.1rc1.tar.gz
Running nltk-2.0.1rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5pV7AU/nltk-2.0.1rc1/egg-dist-tmp-bJdL7r
Traceback (most recent call last):
  File &quot;/usr/bin/easy_install&quot;, line 9, in &lt;module&gt;
    load_entry_point('distribute==0.6.15', 'console_scripts', 'easy_install')()
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 1906, in main
    with_ei_usage(lambda:
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 1887, in with_ei_usage
    return f()
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 1910, in &lt;lambda&gt;
    distclass=DistributionWithoutHelpCommands, **kw
  File &quot;/usr/lib/python2.7/distutils/core.py&quot;, line 152, in setup
    dist.run_commands()
  File &quot;/usr/lib/python2.7/distutils/dist.py&quot;, line 953, in run_commands
    self.run_command(cmd)
  File &quot;/usr/lib/python2.7/distutils/dist.py&quot;, line 972, in run_command
    cmd_obj.run()
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 363, in run
    self.easy_install(spec, not self.no_deps)
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 578, in easy_install
    return self.install_item(None, download, tmpdir, deps, True)
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 633, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 823, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 1100, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py&quot;, line 1089, in run_setup
    run_setup(setup_script, args)
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/sandbox.py&quot;, line 29, in run_setup
    lambda: execfile(
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/sandbox.py&quot;, line 70, in run
    return func()
  File &quot;/usr/lib/python2.7/dist-packages/setuptools/sandbox.py&quot;, line 31, in &lt;lambda&gt;
    {'**file**':setup_script, '**name**':'**main**'}
  File &quot;setup.py&quot;, line 13, in &lt;module&gt;
  File &quot;/tmp/easy_install-5pV7AU/nltk-2.0.1rc1/nltk/**init**.py&quot;, line 92, in &lt;module&gt;

  File &quot;/tmp/easy_install-5pV7AU/nltk-2.0.1rc1/nltk/yamltags.py&quot;, line 1, in &lt;module&gt;
ImportError: No module named yaml

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=691</p><hr/><h2>earlier comments</h2>
<p><strong>notbot said, at 2011-07-11T01:26:11.000Z:</strong></p>

<p>Try installing PyYAML first:

easy_install PyYAML

or 

pip install PyYAML</p><p><strong>jingle.yeah said, at 2011-07-11T02:13:43.000Z:</strong></p>

<p>done, my fault, thanks:)
在 2011-7-11 上午9:27， <nltk@googlecode.com>写道：

Source failed on Ubuntu 11.04</p><p><strong>kmike84 said, at 2011-07-13T22:54:12.000Z:</strong></p>

<p>I believe it is a duplicate of http://code.google.com/p/nltk/issues/detail?id=508 , and it is not your fault ;)</p><p><strong>bobobo1618 said, at 2011-08-08T01:40:34.000Z:</strong></p>

<p>Perhaps we should get NLTK into the Ubuntu repos?</p><p><strong>alex.rudnick said, at 2011-08-08T02:09:25.000Z:</strong></p>

<p>It's actually in Ubuntu already!

http://packages.ubuntu.com/natty/python-nltk

It looks like it's a bit out of date, though: 2.0b9 is about a year old.</p>

**Comment by kmike** [comment]
https://github.com/nltk/nltk/commit/cc1a3c792e3e6e9908118e83185a92665be9ccbb ?

**Comment by kmike** [comment]
I think this should be closed.

**Comment by alexrudnick** [comment]
Yes! Thanks :)
