### ISSUE TITLE
Speed up FreqDist.N()

### ISSUE THREAD

**Issue by vthorsteinsson** [nltk/nltk#1665]
The function FreqDist.N(), defined in probability.py, performs a sum of all contained values every time it is called. FreqDist inherits from collections.Counter, and instances of it often contain large collections, for instance all distinct unigrams in a text in the case of the TnT tagger. The N() function may thus have to iterate over tens or hundreds of thousands of values to yield its total count. This means that as is, it should be used with care. However, other commonly used functions, such as FreqDist.freq(), call N() - not once but twice per call!

This can easily be optimized and will yield much faster execution. One way to do it is to add a function to FreqDist:

```
def freeze_N(self):
    """ Freezes the total item count N() at its current value, making its retrieval MUCH faster """
    n = self.N()
    self.N = lambda: n

```
...and then call the freeze_N() function for instance after training but before POS tagging new text. In my TnT tagging use case, this simple modification increased tagging speed by 5x.

Other solutions are possible, but in any case, the current behavior is extremely and unnecessarily slow.

**Comment by vthorsteinsson** [comment]
...and, by the way, by adding the same optimization to ConditionalFreqDist.N() I was able to get a further 1.8x speedup on the TnT tagging use case. The cumulative speed gain is about 9x - in my case from just over 200 seconds on a 100,000-sentence training run followed by tagging of 200 test sentences, down to 23 seconds.

The function added to ConditionalFreqDist is as follows:

```
    def freeze_N(self):
        """ Freeze the total number of sample outcomes at the current value """
        for fdist in self.values():
            fdist.freeze_N()
        n = self.N()
        self.N = lambda: n

```

**Comment by vthorsteinsson** [comment]
I have submitted a PR addressing this: https://github.com/nltk/nltk/pull/1680

**Comment by stevenbird** [comment]
Resolved.
