### ISSUE TITLE
Speed up TnT tagger with simple modification

### ISSUE THREAD

**Issue by vthorsteinsson** [nltk/nltk#1666]
In the TnT tagger, in the function _tagword(), there is this piece of code:

```
        if word in self._wd.conditions():
            self.known += 1
```
self._wd.conditions() returns list(self.keys()), which is a list of all distinct words encountered during training - often tens of thousands, sometimes hundreds of thousands. The if statement searches linearly through this list, taking O(N) time. A simpler, equivalent, much quicker and more readable version would be:

```
        if word in self._wd:
            self.known += 1
```
...since self._wd is derived from a dict, anyway.

**Comment by vthorsteinsson** [comment]
I have submitted a PR addressing this: https://github.com/nltk/nltk/pull/1680

**Comment by stevenbird** [comment]
Thanks @vthorsteinsson
