### ISSUE TITLE
nltk.translate.gleu_score problems

### ISSUE THREAD

**Issue by goodmami** [nltk/nltk#1667]
I see a few possible issues with the gleu_score implementation.

1. It doesn't allow multiple references, despite the [docstring saying it does](https://github.com/nltk/nltk/blob/develop/nltk/translate/gleu_score.py#L72). This is either a code or a doc issue. Can anyone clarify which?

2. I don't see why there is no `corpus_gleu()` function. The Wu et al. 2016 paper states (emphasis added):

   >According to our experiments, GLEU score correlates quite well with the BLEU metric **on a corpus level** but does not have its drawbacks for our per sentence reward objective

   So I would think there's a way to calculate this for the corpus. Maybe just `min(corpus_precision, corpus_recall)`, or alternatively the average of sentence-level GLEU scores?

3. The name GLEU is unfortunate; there are at least 2 other GLEUs that predate the 2016 paper:
   * Mutton et al. (2007) "GLEU: Automatic Evaluation of Sentence-Level Fluency" http://anthology.aclweb.org/P/P07/P07-1044.pdf
   * Napoles et al. (2015) "Ground Truth for Grammatical Error Correction Metrics" http://www.aclweb.org/anthology/P/P15/P15-2097.pdf

   Maybe the Wu et al. 2016 paper will choose a different name if they publish outside of arXiv? But for NLTK, would `google_bleu` or `gnmt_bleu` be less likely to step on toes?

I'd be happy to submit a PR when the above issues get resolved.

**Comment by alvations** [comment]
@goodmami I'll try to answer some of the questions:

> It doesn't allow multiple references, despite the docstring saying it does. This is either a code or a doc issue. Can anyone clarify which?

It's a docstring problem. It doesn't take multiple references because the GMNT paper didn't account for multiple references. 

> I don't see why there is no corpus_gleu() function. The Wu et al. 2016 paper states (emphasis added):
> 
> According to our experiments, GLEU score correlates quite well with the BLEU metric on a corpus level but does not have its drawbacks for our per sentence reward objective
>
> So I would think there's a way to calculate this for the corpus. Maybe just min(corpus_precision, corpus_recall), or alternatively the average of sentence-level GLEU scores?

Yes, this was unclear because they were using GLEU to do some sort of reinforcement learning (I would call it nbest reranking) at the decoder, so it must have been something at sentence level. 

As for the corpus level, I don't think it's `min(corpus_precision, corpus_recall)`, the reinforcement learning part wouldn't make sense then. the sentences would have been read in mini-batches. so the closest it gets to `corpus_precision`/`corpus_recall` is `minibatch_precision`/`minibatch_recall`. 

But since it's taking the min at every sentence during the reinforcement learning,  I think the macro-average of sentence level might be more viable. 

I have no idea how they calculate correlations though, p-value?


> The name GLEU is unfortunate; there are at least 2 other GLEUs that predate the 2016 paper:
? 
> Mutton et al. (2007) "GLEU: Automatic Evaluation of Sentence-Level Fluency"  http://anthology.aclweb.org/P/P07/P07-1044.pdf
>
> Napoles et al. (2015) "Ground Truth for Grammatical Error Correction Metrics" 
http://www.aclweb.org/anthology/P/P15/P15-2097.pdf
>
> Maybe the Wu et al. 2016 paper will choose a different name if they publish outside of arXiv? But for NLTK, would google_bleu or gnmt_bleu be less likely to step on toes?

Cool! I didn't know there's other GLEU =) 

Then I agree, the name in NLTK should be changed.

**Comment by goodmami** [comment]
Ok, thanks @alvations. Maybe we should contact an author of the paper to get a more precise description of the metric before modifying the implementation?

And the docstring problem was not as bad as I thought. It was just the plural `references` instead of `reference`. (I misinterpreted `list(str)` as the type to mean a list of strings rather than a list of tokens.) Anyway, I corrected the plural, added a note about the single-reference limitation, and fixed an unrelated copy-paste docstring bug on the return value (it currently says it returns the `CHRF score`). Pull request here: https://github.com/nltk/nltk/pull/1668

So maybe let's wait to (a) rename the module and (b) possibly add multi-reference or corpus metrics until after we've heard back from someone on the project or have seen an official implementation.

**Comment by goodmami** [comment]
Just summarizing what Mike Schuster (2nd author on Wu et al. 2016) said on an nltk-dev thread:

Nothing special for multiple-references; suggests using the max score:
* Q:
   > [...] Are we correct in assuming that GLEU does not provide any similar special formulation for multiple references?
* A:
   > Yes, there is nothing special for multiple references (we used the GLEU score before we were using multiple references). I would use the reference with the highest score in this case.

Corpus GLEU is not just the macro-average:
* Q:
  > [...] is the corpus-level GLEU just the mean of the sentence-level scores?
* A:
  > For the corpus, we just add up the two statistics n_match and n_all = max(n_all_output, n_all_target) for all sentences, then calculate gleu_score = n_match / n_all, so it is *not* just a mean of the sentence gleu scores (in our case, longer sentences count more, which I think makes sense as they are more difficult to translate).

"GLEU" name was used internally and team was not aware of previous instances. Fate uncertain? At least we should be clear about which "GLEU" we are using, which I think we are.
* Q:
  > Is there a finalized name for the metric? "GLEU" has been used [...] (e.g., http://anthology.aclweb.org/P/P07/P07-1044.pdf) [...].
* A:
  > Wow, we didn't know about this -- this is unfortunate! We first called it internally Google-BLEU which became GLEU -- I am not sure what is the best to do in this case. Maybe just reference the paper to make clear which GLEU score it is?
