### ISSUE TITLE
Unseen token error in nltk.model.NgramModel.entropy

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#167]
NLTK version 2.0b9

I'm attempting to compute the entropy of a piece of text with respect to a given model and there seems to be an issue with unseen tokens (even when an estimator is used for the model).

from nltk.model import NgramModel
from nltk.corpus import brown
from nltk.probability import WittenBellProbDist

estimator = lambda fdist, bins: WittenBellProbDist(fdist,0.2)
lm = NgramModel(3, brown.words(categories='news'), estimator)

sent = &quot;this is a sentence with the word aardvark&quot;.split()
lm.entropy(sent)

Traceback (most recent call last):
  File &quot;&lt;pyshell#28&gt;&quot;, line 1, in &lt;module&gt;
    lm.entropy(&quot;this is a sentence with the word aardvark&quot;.split())
  File &quot;C:\Python26\lib\site-packages\nltk\model\ngram.py&quot;, line 133, in entropy
    e += self.logprob(token, context)
  File &quot;C:\Python26\lib\site-packages\nltk\model\ngram.py&quot;, line 98, in logprob
    return -log(self.prob(word, context), 2)
  File &quot;C:\Python26\lib\site-packages\nltk\model\ngram.py&quot;, line 79, in prob
    return self._alpha(context) \* self._backoff.prob(word, context[1:])
  File &quot;C:\Python26\lib\site-packages\nltk\model\ngram.py&quot;, line 82, in prob
    &quot;context %s&quot; % (word, ' '.join(context)))
TypeError: not all arguments converted during string formatting

An exception is not raised (and a value is returned) if the entropy is computed using the same sentence but with 'aardvark' removed, which leads me to believe it's an error with unseen tokens. However, my understanding is that the model should be equipped to handle unseen tokens as indicated by the estimator.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=694</p><hr/><h2>earlier comments</h2>

<p><strong>SilaiSantai said, at 2011-07-29T11:23:30.000Z:</strong></p>

<p>I am having the exact same problem (though I use a LidstoneProbDist as my estimator). I also looked at it and it seems that it is unable to handle unseen words in the text.

This would seem to be a major issue for the NgramModel method as it is not much use if it cannot handle unseen words.</p><p><strong>SilaiSantai said, at 2011-07-29T12:20:45.000Z:</strong></p>

<p>The fix written here:

http://code.google.com/p/nltk/issues/detail?id=673&can=1&q=ngrammodel

Solves the issue it seems. At least now it yields a result.</p>

**Comment by paulproteus** [comment]
It would be nice if someone can attempt to reproduce this bug.

If it is still an issue, it seems like a reasonably good first bug for someone new to NLTK to solve.

**Comment by alexrudnick** [comment]
The _particular_ problem that ssingh.math saw seems to have been fixed along with #158, so this works with a LidstoneProbDist, but it's still breaking for me with a WittenBellProbDist.

I'm pretty sure WittenBellProbDist is broken, though. If you don't pass a "bins" parameter, it will always set its "Z" field to 0 and then try to divide by that.

**Comment by stevenbird** [comment]
@Copper-Head would you please confirm if this issue is current?

**Comment by iliakur** [comment]
@stevenbird we can close this now!

**Comment by stevenbird** [comment]
Thanks @Copper-Head
