### ISSUE TITLE
u201c and u201d should also be considered as open

### ISSUE THREAD

**Issue by clouds56** [nltk/nltk#1675]
nltk.word_tokenize("The unicode 201C and 201D “LEFT(RIGHT) DOUBLE QUOTATION MARK” is also OPEN_PUNCT and CLOSE_PUNCT.")

# result:
['The',
 'unicode',
 '201C',
 'and',
 '201D',
 '“LEFT',
 '(',
 'RIGHT',
 ')',
 'DOUBLE',
 'QUOTATION',
 'MARK”',
 'is',
 'also',
 'OPEN_PUNCT',
 'and',
 'CLOSE_PUNCT',
 '.']

note: there's word '“LEFT' and 'MARK”', which is unexpected.
(And also u+2018 and u+2019)

**Comment by stevenbird** [comment]
:+1:

**Comment by alvations** [comment]
@clouds56 Good catch!

It's a little tricky to fix it though. The original treebank tokenizer that `word_tokenize` wraps didn't get the u+2018 and u+2019 split either =(

```
$ wget https://web-beta.archive.org/web/20110604022401/http://www.cis.upenn.edu/~treebank/tokenizer.sed
--2017-04-10 18:20:35--  https://web-beta.archive.org/web/20110604022401/http://www.cis.upenn.edu/~treebank/tokenizer.sed
Resolving web-beta.archive.org... 207.241.224.26
Connecting to web-beta.archive.org|207.241.224.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘tokenizer.sed’

tokenizer.sed                                   [ <=>                                                                                      ]   2.15K  --.-KB/s    in 0s      

2017-04-10 18:20:37 (48.9 MB/s) - ‘tokenizer.sed’ saved [2204]

$ cat test.txt 
The unicode 201C and 201D “LEFT(RIGHT) DOUBLE QUOTATION MARK” is also OPEN_PUNCT and CLOSE_PUNCT.

$ sed -f tokenizer.sed test.txt 
The unicode 201C and 201D “LEFT ( RIGHT ) DOUBLE QUOTATION MARK” is also OPEN_PUNCT and CLOSE_PUNCT . 
```

Without changing how `TreebankWordTokenizer` works, to fix this, we might have to  duck_typing the `TreebankWordTokenizer`object and also lump in with the chervon fix ( c.f. #1437, specifically https://github.com/nltk/nltk/pull/1437#issuecomment-234164667)
