### ISSUE TITLE
How to use texttiling with emails?

### ISSUE THREAD

**Issue by NervousEnergy1979** [nltk/nltk#1679]
I want to tile the email text below into the 5 sections LOGISTICS, INTRO, BODY, OUTRO, POST EMAIL DISCLAIMER

```
email = """    From: X
    To: Y                             (LOGISTICS)
    Date: 10/03/2017

    Hello team,                       (INTRO)

    Some text here representing
    the body                          (BODY)
    of the text.

    Regards,                          (OUTRO)
    X

    *****DISCLAIMER*****              (POST EMAIL DISCLAIMER)
    THIS EMAIL IS CONFIDENTIAL
    IF YOU ARE NOT THE INTENDED RECIPIENT PLEASE DELETE THIS EMAIL"""

tt = TextTilingTokenizer(demo_mode=False)
tiles = tt.tokenize(email)
```

But when I run the code above, I get the same string back in list form, and un-tiled in any way. I have tried using several parameters in TextTilingTokenizer, including (w=2, k=10, similarity_method=0, stopwords=None, smoothing_method=[0], smoothing_width=2, smoothing_rounds=1, cutoff_policy=1, demo_mode=False), but nothing seems to work. Can anyone please advise?

**Comment by stevenbird** [comment]
Sorry @killerT1992 this is not an appropriate issue. Please post on nltk-users or on stackoverflow.
