### ISSUE TITLE
Punkt fails on Python 3.2 due to english.pickle error

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#169]
I am using 3.0.1, as I am testing it with Python 3. With Python 3.1, I have no issues using the Punkt tokeniser. With Python 3.2 however, it gives me this delicious error.

[nltk_data] Downloading package 'punkt' to /home/brendan/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
Traceback (most recent call last):
  File &quot;/home/brendan/qa/lib/python3.2/site-packages/apertium_quality-0.2-py3.2.egg/apertium/quality/corpora.py&quot;, line 86, in **init**
    self.tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
  File &quot;/home/brendan/qa/lib/python3.2/site-packages/nltk/data.py&quot;, line 594, in load
    resource_val = pickle.load(_open(resource_url))
  File &quot;/home/brendan/qa/lib/python3.2/site-packages/nltk/data.py&quot;, line 673, in _open
    return find(path).open()
  File &quot;/home/brendan/qa/lib/python3.2/site-packages/nltk/data.py&quot;, line 455, in find
    raise LookupError(resource_not_found)
LookupError: 

---

  Resource 'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource: &gt;&gt;&gt;
  nltk.download().
  Searched in:
    - '/home/brendan/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'

---

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/home/brendan/qa/bin/aq-wikicrp&quot;, line 9, in &lt;module&gt;
    load_entry_point('apertium-quality==0.2', 'console_scripts', 'aq-wikicrp')()
  File &quot;/home/brendan/qa/lib/python3.2/site-packages/apertium_quality-0.2-py3.2.egg/apertium/quality/frontend/corpus_extractor.py&quot;, line 23, in main
    ui = UI()
  File &quot;/home/brendan/qa/lib/python3.2/site-packages/apertium_quality-0.2-py3.2.egg/apertium/quality/frontend/corpus_extractor.py&quot;, line 15, in **init**
    self.corpus = CorpusExtractor()
  File &quot;/home/brendan/qa/lib/python3.2/site-packages/apertium_quality-0.2-py3.2.egg/apertium/quality/corpora.py&quot;, line 90, in **init**
    self.tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
  File &quot;/home/brendan/qa/lib/python3.2/site-packages/nltk/data.py&quot;, line 594, in load
    resource_val = pickle.load(_open(resource_url))
ValueError: invalid literal for int() with base 10: '1165\nI14\nsVsutezo\np1166\nI4\nsVbilling\np1167\nI32\nsVshouting\np1168\nI34\nsVholdings\np1169\nI44\nsVtatum\np1170\nI8\nsVoil-pipeline\np1171\nI32\nsVsubside\np1172\nI32\nsVprovincially\np1173\nI32\nsVarmand\np1174\nI2\nsVbrea'

I'm guessing that the pickle was pickled with Python 3.1, and thus needs to be repickled for Python 3.2. 

On a sidenote, is there a specific reason that this file _must_ be a pickle and not just an ordinary Python file?

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=696</p>

**Comment by achimnol** [comment]
I discovered a similar problem in the _latest master_ branch when I tried to use the same punkt tokenizer, and monkey-patched it like this.
I'm not sure this will change the semantic/intention of the code, but it looks working fine.

``` diff
diff --git a/nltk/data.py b/nltk/data.py
index 0dc9369..e396c0a 100644
--- a/nltk/data.py
+++ b/nltk/data.py
@@ -627,7 +627,7 @@ def load(resource_url, format='auto', cache=True, verbose=False,
     if format == 'raw':
         resource_val = opened_resource.read()
     elif format == 'pickle':
-        resource_val = pickle.load(opened_resource)
+        resource_val = pickle.load(opened_resource, encoding='iso-8859-1')
     elif format == 'yaml':
         import yaml
         resource_val = yaml.load(opened_resource)
```

**Comment by kmike** [comment]
I think the reason is that pickled Punkt tokenizer available in nltk_data was trained on byte strings, and implicit byte strings fail under Python 3.x. Other pickled data installable with nltk.download (e.g. POS taggers) also has this issue. 

We can't just apply this patch to NLTK because "encoding" parameter is Python3-only. Also, it may be the case that different pickled models use different encodings (because they were trained on different corpora) so hardcoded iso-8869-1 may break other models. 

On the other hand, re-training NLTK models on unicode corpora should fix the issue both under Python 2.x and 3.x, but it may break older NLTK releases.

So +1 for conditionally providing an encoding in pickle.load (`if compat.PY3:`), but we'd better figure out how to do this per-model.

Another option is to create ..-unicode versions of all pickled models.

**Comment by alexrudnick** [comment]
How bad do we think it would be if we updated the models by training them on Unicode text? That would break some older installs, but only if they re-download the data.

If somebody has some stable app that depends on loading the data, hopefully they won't go pulling data updates very often? Maybe if we just announce to the users list that the data is going to change soon, then people can update their code?

**Comment by kmike** [comment]
I'm worried about this because if we replace current models with Unicode models, there would be no way to get the data usable with NLTK < 3.0, and there may be valid reasons to use older NLTK (it may be a pinned dependency; NLTK book is for NLTK 2.0; Python 2.5 is not supported in NLTK3).

**Comment by stevenbird** [comment]
I think we have three options here: retrain the punkt models on Unicode text, re-encode the existing trained models, or do model-specific decoding (perhaps using a lookup table so we know which character encoding to use for each model).

**Comment by dougalg** [comment]
Would it be unreasonable to create -unicode versions of all the models and then have NLTK3 load those, leaving the old pickles for old versions of NLTK? I think it makes sense to try to move forward to an all unicode implementation if possible just for consistency's sake alone. I think it makes more sense than using model-specific decoding, as then we'd have a clear standard moving forward.

**Comment by stevenbird** [comment]
Right, I would prefer to have all models using utf8 (whether we retrain, or convert existing models). Model-specific decoding would be less desirable. Yes, we should leave existing models around.

**Comment by stevenbird** [comment]
@jskda would you go ahead and convert the existing Punkt models to utf8 please, then repickle them in Python 3 using protocol 2, then test.

**Comment by stevenxxiu** [comment]
This line works with the re-pickled files on my branch, using latin-1 to decode (https://github.com/jskda/nltk_data/tree/gh-pages-repickle), give them a try:
self.tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

**Comment by paulproteus** [comment]
Looks like per https://github.com/nltk/nltk_data/tree/gh-pages/packages/tokenizers this may already be fixed? If so, would love to see this issue get closed.

**Comment by stevenbird** [comment]
Yes, this is resolved. See https://github.com/nltk/nltk/pull/470
