### ISSUE TITLE
IBM-3 Model is too slow

### ISSUE THREAD

**Issue by lixin4ever** [nltk/nltk#1695]
Hi,

    Recently, I want to use IBM Model3 in nltk for word alignment. 
    However, the running time is really unaffordable 
    (e.g., for training over 100 aligned sentences, 4 hours are needed per iteration). 
    Is there anybody encounter the same problem?

    p.s: IBM-2 and IBM-1 only cost a few seconds on the same machine.

**Comment by alvations** [comment]
@lixin4ever yes, the IBM models in NLTK was meant for education purposes. Possibly a reimplementation with `numpy` and `scipy` would help speed things up. 

Anyone up for a challenge?

**Comment by lixin4ever** [comment]
Thanks for your response @alvations

**Comment by mayowaosibodu** [comment]
@lixin4ever @alvations  Did you eventually figure out a more efficient way to build language translation models? I was working with the IBM Model 3 for a 10k+ sentence corpus and had to stop the process after 21 hours of my computer's fan blowing intensely (16 GB RAM)- It's a new computer and I'm not ready to replace it just yet.

Any other libraries which prove efficient for building Statistical Machine Translation models?

**Comment by alvations** [comment]
Try http://www.statmt.org/moses/ and for just alignments, see https://github.com/alvations/usaarhat-repo/blob/master/Align-A-Line.md
