### ISSUE TITLE
Conditional Random Field implementation in nltk

### ISSUE THREAD

**Issue by iamrachitajain** [nltk/nltk#1703]
I have been trying to implement crf for my word prediction algorithm but the pycrfsuite- binding for crfsuite and sklearn-pycrfsuite the wrapper for pycrfsuite are not at all flexible in terms of the data input for training. A complete implementation of the algorithm in nltk will be appreciated.

**Comment by stevenbird** [comment]
@iamrachitajain – I'm not convinced we should replicate this functionality in pure Python, as it will probably be too slow to be useful.
