### ISSUE TITLE
Debug output in PunktSentenceTokenizer

### ISSUE THREAD

**Issue by SanketDG** [nltk/nltk#1704]
In reference to https://github.com/nltk/nltk/commit/b3e2b410eb0031b52ae05e9d35fe275dbe8098cd, there is a print statement in the middle of nowhere, is this intended?

**Comment by SanketDG** [comment]
https://github.com/nltk/nltk/blob/develop/nltk/tokenize/punkt.py#L1072

**Comment by alvations** [comment]
@SanketDG Thanks for catching this! Yes, it shouldn't be there.
