### ISSUE TITLE
Mac OS 10.7 Lion: Installation does not work

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#172]
I installed the NLTK on Mac OS 10.6 without problems. After the OS upgrade to 10.7 Lion the installation did not work any longer and reinstalling didn't solve the problem either.

Since I am new to Python I would appreciate any hints how to get back to a working NLTK environment.

Any information to that end is highly appreciated.

Peter Buchmann<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=705</p><hr/><h2>earlier comments</h2>

<p><strong>pranava.madhyastha said, at 2011-08-07T05:34:37.000Z:</strong></p>

<p>Can you please paste the error that you are getting? 

Have you updated the XCode too? If you don't install xcode tons of stuff will break. </p><p><strong>pbuchmann said, at 2011-08-07T07:04:29.000Z:</strong></p>

<p>With the newly installed XCode it is possible to install NLTK. Thank you fro your support and keep up the good work! Regards from Zurich, Switzerland</p><p><strong>tiago.henriques said, at 2011-08-16T16:48:52.000Z:</strong></p>

<p>installing inside a virtualenv with "pip install nltk" fails on a brand new install of Mac OS X 10.7 Lion with this error:

 IOError: [Errno 2] No such file or directory: '/Users/myuser/.virtualenvs/nltk/build/nltk/setup.py'

following a tip from another user in Issue 534, I tried installing with "pip install http://pypi.python.org/packages/source/n/nltk/nltk-2.0.1rc1.tar.gz", but got an import error complaining about a missing yaml module.

After installing PyYAML with "pip install pyyaml", I was able to successfully install NLTK with "pip install http://pypi.python.org/packages/source/n/nltk/nltk-2.0.1rc1.tar.gz".</p>

**Comment by kmike** [comment]
I think this is also resolved by https://github.com/nltk/nltk/commit/cc1a3c792e3e6e9908118e83185a92665be9ccbb
