### ISSUE TITLE
We need to make Verbnet more consumable

### ISSUE THREAD

**Issue by chnsh** [nltk/nltk#1721]
Hello,

As things are today, in Verbnet, one can only access lemmas directly in a list. However, other aspects of verbnet like Frames are merely pretty printed and that is not really usable.

I have written code to generate a list of syntax(es) within a verbnet frame within Verbnet.py, does it make sense for the NLTK community as a whole? If yes, I shall create a pull request.

example output for verbnet class -> 9.1:
`[[{'pos': 'NP', 'modifiers': ['Agent']}, {'pos': 'VERB', 'modifiers': []}, {'pos': 'NP', 'modifiers': ['Theme']}, {'pos': 'PREP', 'modifiers': ['+loc']}, {'pos': 'NP', 'modifiers': ['Destination']}], [{'pos': 'NP', 'modifiers': ['Agent']}, {'pos': 'VERB', 'modifiers': []}, {'pos': 'NP', 'modifiers': ['Theme']}, {'pos': 'NP', 'modifiers': ['Destination', '+adv_loc']}]]`

**Comment by nschneid** [comment]
I haven't used the VerbNet API before, but it looks like it defines the following methods:

## Machine-friendly methods

    classids(lemma, wordnetid, fileid, classid)
    lemmas(classids)
    longid(shortid)
    shortid(longid)
    vnclass(fileid_or_classid)
    wordnetids(classid)
    
## Human-friendly methods

    pprint(vnclass)
    pprint_description(vnframe, indent)
    pprint_frame(vnframe, indent)
    pprint_members(vnclass, indent)
    pprint_semantics(vnframe, indent)
    pprint_subclasses(vnclass, indent)
    pprint_syntax(vnframe, indent)
    pprint_themroles(vnclass, indent)

I agree that there should be a machine-readable way to access the data that can be pretty-printed. In the [FramenetCorpusReader](https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/framenet.py), our strategy was to have methods return objects that can be pretty-printed for easy browsing but also contain structured data. Is such a strategy worth pursuing here?

**Comment by chnsh** [comment]
Yes, it is definitely a good idea. I found the verbnet API unusable because of the way it is right now.
It let's me access members(lemmas) but the usability ends there

**Comment by nschneid** [comment]
Sure, go ahead and take a stab at it!

**Comment by nschneid** [comment]
CC @dhwang90

**Comment by chnsh** [comment]
Yes, I'll start ASAP. Thanks!

**Comment by chnsh** [comment]
I have created a pull request #1731.

**Comment by chnsh** [comment]
Can anyone please look into this?

**Comment by nschneid** [comment]
This looks like it adds useful functionality, but I don't have time do a proper code review. @stevenbird, what do you suggest?

**Comment by stevenbird** [comment]
@chintanshah24 sorry for the delay; @nschneid thanks for your feedback

**Comment by alvations** [comment]
Patched in #1731
