### ISSUE TITLE
Setuptools fails to work for NLTK under Cygwin 1.7

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#173]
Under Cygwin 1.7 (the current version, which uses Python 2.6.5), the Python setuptools fail to install NLTK, where they succeed with other packages.

To reproduce: Install a default Cygwin 1.7, though for convenience add &quot;wget&quot; from the &quot;Web&quot; section, then try:

$ wget http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
$ sh setuptools-0.6c11-py2.7.egg
$ easy_install nltk
Searching for nltk
Reading http://pypi.python.org/simple/nltk/
Reading http://nltk.org/
Reading http://www.nltk.org/download
Reading http://nltk.sf.net/
Best match: nltk 2.0.1rc1.macosx-10.6-x86-64
Downloading http://pypi.python.org/packages/any/n/nltk/nltk-2.0.1rc1.macosx-10.6-x86_64.tar.gz#md5=f3c8c67ac388cda567d669880192d6f0
Processing nltk-2.0.1rc1.macosx-10.6-x86_64.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-0hW3C4/nltk-2.0.1rc1.macosx-10.6-x86_64.tar.gz

This is under 64-bit Windows 7 as the host OS. Perhaps setuptools is using the wrong information in selecting a source package to download? The 2.0b8 source archive works perfectly when built using setup.py as described in the &quot;install from source&quot; instructions.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=706</p><hr/><h2>earlier comments</h2>

<p><strong>bobobo1618 said, at 2011-08-08T01:39:36.000Z:</strong></p>

<p>Sounds like a problem with the Cygwin python more than anything. I'll have a look next time I boot into Windows.</p>

**Comment by stevenbird** [comment]
I expect this issue is stale.
