### ISSUE TITLE
Stanford Tagger Doesn't Remove File on Failure

### ISSUE THREAD

**Issue by jamesmf** [nltk/nltk#1733]
When using NLTK with a Stanford tagger, a temp file is written out and passed on the command line to Java. Only upon successful completion of the tagging does the file get removed. Can we wrap a try: finally: around the call to ensure the file gets removed? If not, can we create a method for specifying the location of the temp file so the user can ensure its removal?

https://github.com/nltk/nltk/blob/develop/nltk/tag/stanford.py#L103

**Comment by alvations** [comment]
Since there is the new API for Stanford CoreNLP at `nltk.parse.corenlp.py` I think the better solution is to wait till @dimazest updates the API with the protobuf support as discussed in #1249 and then all other Stanford API (POS, NER, tokenizer, segmenter) should wrap around the CoreNLP.

**Comment by jamesmf** [comment]
Makes sense - I read through that earlier and saw it was just merged. Is there already ongoing work to make the other Stanford models use the new CoreNLP API?

**Comment by dimazest** [comment]
I don't plan to work on the other modules, but adding new should be relatively easy.

The current parser is also a tokenizer, check out https://github.com/nltk/nltk/blob/develop/nltk/parse/corenlp.py#L302

**Comment by alvations** [comment]
@dimazest Cool! I just realized the nice mixin: [`class GenericCoreNLPParser(ParserI, TokenizerI)`](https://github.com/nltk/nltk/blob/develop/nltk/parse/corenlp.py#L179). 

**What if we just do this at `nltk.tokenize.stanford.py`?**:

```python
from nltk.parse.corenlp import CoreNLPParser as StanfordCoreNLPTokenizer
```

----

BTW, what should be the canonical way to start the `CoreNLPServer` server? 

I've been using this but I suspect I'm abusing `global`.

```python
>>> from nltk.parse.corenlp import *
>>> global server
>>> server = CoreNLPServer()
>>> server.start()
```

**Comment by dimazest** [comment]
Maybe we should not distinguish between a parser and a tokenizer for CoreNLP. The idea being, if you want to use CoreNLP, then using one module should be enough.

Regarding the cacnonical way of starting the server:
1. Start the CoreNLP by yourself
2. If you want to start it within a python session, use:
    ``` python
     with CoreNLPServer() as server:
         # pass server.url to the parser.
     ```
3. If you can't use a context manager (for example, when you start a server in a doctest, use .start(). But I strongly discourage such usage.

The reason I don't really like starting corenlp within python is that corenlp takes a lot of parameters, and it is difficult to provide a reliable and flexible CoreNLPServer.

**Comment by alvations** [comment]
I agree with starting the corenlp server outside of python. It's a little too messy to start it inside the context manager, even in doctest.

@fievelk would starting the corenlp server like this https://github.com/nltk/nltk/pull/1735/commits/057d3c5ede9e61db9cd6590e005a9f3fcaf667a2 be overloading the CI server?

@dimazest to load the depparse from `english_UD.gz`, it seems to require quite a lot of resource. Is that normal? Any suggestions on what's the `-mx*g` to set for the jenkins test? 

----

The `spacy` approach to starting a model is one-size-fits-all and everyone uses the default model and then the advance users can use other "special settings". 

Just thinking about the design of how users should interface `nltk.parse.corenlp`:

 1. Stick with the old interface, one class per task
    - i.e. `nltk.tag.CoreNLPTagger`, `nltk.tag.CoreNLPPOSTagger`, `nltk.tag.CoreNLPNERTagger`, `nltk.tokenize.CoreNLPTokenizer`, `nltk.tokenize.CoreNLPSegmenter`

 2. Everything packed under the `nltk.parse.CoreNLPParser` and then access the annotations as attributes, but this will only be possible with the default CoreNLPParser settings used for English, e.g. 
    
```python
from nltk.parse.corenlp import CoreNLPParser
nlp = CoreNLPParser()
sent = 'This is a foo bar sentence.'
parsed_sent = np.parse(sent)
parsed_sent.parses() # Returns list of nltk.tree.Tree
parsed_sent.tags() # Returns list of tuple of string (Token, Tag)
parsed_sent.ner() # Returns list of tuple of string (Token, Tag)
parsed_sent.words() # Returns list of string (Tokens)
parsed_sent.lemmas() # Returns list of string (Lemma)
```

**Comment by dimazest** [comment]
I've set `-mx` to 2 gb, as it was failing with lower values.

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
