### ISSUE TITLE
Anyway to install latest version on Windows XP SP3?

### ISSUE THREAD

**Issue by ohenepee** [nltk/nltk#1741]
Tried installing via the Windows Installer `nltk-3.2.4.win32.exe` at PyPI, and get this error when I launch the downloaded executable... "<PATH-TO-FILE>...not a valid win32 application".

I believe this has to do with the build system or compiler used, So is there any other way?

Windows XP SP3
Python 2.7.13

**Comment by alvations** [comment]
Have you tried this: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9 ?

**Comment by alvations** [comment]
@ohenepee Just checking in on this issue, have you resolved the installation issue? Did https://gist.github.com/alvations/0ed8641d7d2e1941b9f9 help? 

Do you need more help on the installation?

**Comment by ohenepee** [comment]
No it didn't... Anaconda seems to be using a more modern compiler/installer that doesn't work on Windows XP... I've moved beyond this issue anyway... I just used a low-RAM-usage Linux ditro for my old PC (specifically AntiX Linux)
