### ISSUE TITLE
importerror cannot import name punktwordtokenizer

### ISSUE THREAD

**Issue by ThajunNajaah** [nltk/nltk#1744]
My current version of nltk is 3.2.4,, I couldn't import punckt word tokenizer through this,
here is my result.
 `>>> from nltk.tokenize import PunktWordTokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name PunktWordTokenizer`

**Comment by alvations** [comment]
The punkt tokenizer is a sentence tokenizer, i.e. to split string (normally a document or paragraph) into list of strings (sentences). For word tokenizer, use the `TreebankWordTokenizer` or `word_tokenize`
