### ISSUE TITLE
Error 403 when connecting to corenlp hosted locally

### ISSUE THREAD

**Issue by f0lie** [nltk/nltk#1758]
Hello,

When I started up a server via my terminal and tried to connect to it with a python client, I got 403 errors. The odd part was that my browser could connect to the server without problems.

I found out that my issue was in my proxy. When my client tried to connect to connect to 'http://localhost:9000' it passed the url to my work's proxy. The proxy didn't recognize url and returned a 403 error.

This issue didn't affect my browser because my browser was using a pac file which excluded localhost from the proxy. Since I was connecting directly to the proxy via environment variables, my terminal was running into issues.

The solution was to set `trust_env` to False. This makes the client connect without using proxy. The client would refuse to import any environment variables.

```
nlp = nltk.parse.corenlp.CoreNLPParser("http://localhost:9000")
nlp.session.trust_env = False
```
I am guessing most people setup their corenlp server locally. Maybe there could be some sort of warning. The class could check if there is a proxy url and if the session is pointed to a local host, then warn users that issues may happen. Maybe a more isolated way is to catch 403 exceptions, check the proxy url and localhost, and then raise a exception with advice.

I managed to fix the issue but I am posting an issue to help others in the same boat.

Thanks,

**Comment by dimazest** [comment]
Another solution could be to reset the `HTTP_PROXY` environmental variable.

I like the idea of giving an advice. I'll think about it. It is probably worth including into the yet-to-be-written  documentation.

**Comment by f0lie** [comment]
If the documentation and API is an ongoing process, I could write some doc strings and redo some of the API. I am using CoreNLP API a lot for my project so I have opportunity to improve things.

**Comment by dimazest** [comment]
That would be great!

**Comment by f0lie** [comment]
Alright. For some reason, the current app only allows "officially" parsing and tokenization. There are a lot of other features than just that. So I'll add that.


I'll also try to add caching since the server responds with json of parse, tokenization, and etc. It's wasteful to call the api for one thing, then call the same api for another thing when you could just save the response.

**Comment by dimazest** [comment]
There was some successful effort to add more functionality, check https://github.com/nltk/nltk/pull/1735

I would also suggest to split the work to several pull request, so they are easier to discuss and accept.

**Comment by f0lie** [comment]
Alright, I'll redo the commits I did. I think I jammed all of the features into one branch.

**Comment by f0lie** [comment]
Also, I found another solution.

Put `export NO_PROXY='localhost'` also `export no_proxy='localhost`.

This makes it so that requests doesn't use the proxy for localhost.

**Comment by soap-tastes-ok** [comment]
Wow thank you you saved my life!
I was stuck on this for a while!
