### ISSUE TITLE
Sentiwordnet

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#177]
What data set would you like to have added to NLTK? 
I would like to see a corpus reader for Sentiwordnet. 
http://sentiwordnet.isti.cnr.it/
As far as i can see it is available for research purposes but sent only after individual registration. I am assuming some form of agreement can be reached. 
Anyway, it would be nice to atleast see a feature that picks up their txt file and converts it.  I have a script that converts the data to mongodb. Will try to write one for nltk corpus integration.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=712</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2011-08-26T12:54:39.000Z:</strong></p>
<p>This would be a welcome contribution, even if it is not possible to get permission to redistribute Sentiwordnet with the NLTK Corpus Collection.  Please see the Corpus HOWTO for information about the design of the corpus readers.

</p>

**Comment by josepvalls** [comment]
Any updates on this? Any guidelines on how could I proceed to the implementation?
How could this be incorporated into NLTK: https://github.com/robert-jm/twit-ranker/blob/master/sentiwordnet.py

**Comment by ewan-klein** [comment]
The corpus can now be downloaded without registration, and is licensed under CC BY 3.0, which makes it easier to proceed. Assuming that the NLTK distro of the corpus were to be correctly attributed, we could possibly request that the license holders waive the requirement that attribution also be given in derivative works in the form of sentiment detection tools built using the corpus.

**Comment by stevenbird** [comment]
The SentiWordNet corpus was added in https://github.com/nltk/nltk_data/commit/d8a6eff7ec065293c9bbe30f8348550b8442a2ef

**Comment by stevenbird** [comment]
I've pushed Christopher Potts SentiWordNet corpus reader to a new branch https://github.com/nltk/nltk/tree/sentiwordnet

There's an error in the initialiser; @jskda would you please take a look?

```
>>> from nltk.corpus import sentiwordnet as swn
>>> swn.senti_synsets()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sb/git/nltk/nltk/corpus/util.py", line 99, in __getattr__
    self.__load()
  File "/Users/sb/git/nltk/nltk/corpus/util.py", line 67, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by stevenbird** [comment]
This problem is resolved in https://github.com/nltk/nltk/commit/76187b5ad6fc0d8e4880791510f4cb7c44523e10

**Comment by stevenbird** [comment]
Merged with develop branch in https://github.com/nltk/nltk/commit/b4386729c0459f2cdf4f8b08cab00b3cf49b720d

**Comment by cgpotts** [comment]
I'm delighted that the code I wrote for reading SentiWordNet is being added to NLTK! ---Chris
