### ISSUE TITLE
Link for implemenation details is broken for PerceptronTagger

### ISSUE THREAD

**Issue by luerhard** [nltk/nltk#1774]
Hey,
the link for the implemenation details in the docstring of nltk.tag.perceptron.AveragedPerceptron and  nltk.tag.perceptron.AveragedPerceptron seems to be broken (it is the same link, namely: http://spacy.io/blog/part-of-speech-POS-tagger-in-python/). Can anyone give me a hint to anthoer source with the same contents?

(Link found on http://www.nltk.org/_modules/nltk/tag/perceptron.html)

**Comment by alvations** [comment]
@habet700 Thanks for raising this. The link to the old spacy blog is 404, the new link is at https://explosion.ai/blog/part-of-speech-pos-tagger-in-python

**Comment by luerhard** [comment]
The link needs to be changed in Line 104 as well :)

**Comment by alvations** [comment]
Resolved in #1777. Thanks @habet700 again for reporting this!
