### ISSUE TITLE
Double quotes not correctly handled in TreebankTokenizer

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#178]
According to the official Penn Treebank Tokenization page at http://www.cis.upenn.edu/~treebank/tokenization.html, double quotes (&quot;) should be changed to doubled single forward- and backward- quotes (`` and ''). However, nltk.word_tokenize() or (TreebankTokenizer) does not follow this rule. 

&gt;&gt;&gt;  nltk.word_tokenize('He went to the &quot;Concert for Hope&quot; yesterday.')
['He',
 'went',
 'to',
 'the',
 '&quot;',
 'Concert',
 'for',
 'Hope',
 '&quot;',
 'yesterday',
 '.']

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=713</p>

**Comment by PanderMusubi** [comment]
Master at the moment results in

```
>>> nltk.word_tokenize('He went to the "Concert for Hope" yesterday.')
['He', 'went', 'to', 'the', '``', 'Concert', 'for', 'Hope', "''", 'yesterday', '.']
```

**Comment by stevenbird** [comment]
Thanks @PanderMusubi. It looks like this issue is no longer current.
