### ISSUE TITLE
WordNet jcn (Jiang & Conrath) returns 1e+300 score

### ISSUE THREAD

**Issue by tastyminerals** [nltk/nltk#1780]
Wordnet `wn.jcn_similarity` method returns `1e+300` similarity score when identical synsets are compared.
For example:
```
from nltk.corpus import wordnet as wn
from nltk.corpus import wordnet_ic as wic
bnc = wic.ic('ic-bnc-add1.dat')
wn.jcn_similarity(Synset('haircloth.n.01'), Synset('haircloth.n.01'), bnc)
``` 
results in `1e+300` score.

**Comment by campionfellin** [comment]
@tastyminerals 

This seems to be the correct functionality. In `wordnet.py` we have this code in the `jcn_similarity` function:

```
if self == other:   
    return _INF
```

Where `_INF` is defined earlier as:

```
#: Positive infinity (for similarity functions)
_INF = 1e300
```

This seems to be correct, because if they are the same synset, they should be "infinitely" similar to each other.
