### ISSUE TITLE
How to not split certain special characters

### ISSUE THREAD

**Issue by AdamMiltonBarker** [nltk/nltk#1782]
Hi guys, in my program I am using nltk.word_tokenize(pattern) (Python), before doing this I have replaced some strings in pattern with their Entity name ie: 

`pattern = "I like cakes" becomes "I like <FOOD>"`

When I tokenise this becomes:

`[u'I', u'like', u'<', u'FOOD', u'>']`

I need the result of tokenizing to be:

`[u'I', u'like', u'<FOOD>']`

Only with those two characters in the instance where there are entities, the rest works perfectly. Is there any way to do this please?

Thanks in advance.

**Comment by alvations** [comment]
I think There's no straightforward way to "protect" special words using the `nltk.word_tokenize()` function (at least not yet). 

But you can easily "post-process" the tokens, e.g.

```python
from nltk import word_tokenize

def protect_tokenize(s):
    re.sub(r'\<\s([A-Z].*)\s\>', r'<\1>', ' '.join(word_tokenize(s)))

sent = "I like <FOOD>"
protect_tokenize(sent)
```

See https://regex101.com/r/1oBGsD/1 for explanation of the regex used above.

**Comment by AdamMiltonBarker** [comment]
Thanks buddy that was spot on!
