### ISSUE TITLE
Broken link on FAQ page

### ISSUE THREAD

**Issue by curusarn** [nltk/nltk#1788]
on [FAQ page](https://github.com/nltk/nltk/wiki/FAQ) 
in section "13. How did NLTK start?"
link ["this plan"](http://code.google.com/p/nltk/source/browse/trunk/nltk-old/doc/technical/proposal/proposal.tex) leads to a google.code page that says: 

"There was an error getting resource 'source':

401: Anonymous users does not have storage.objects.get access to object google-code-archive/v2/code.google.com/nltk/project.json."

screenshot:
![screenshot](https://user-images.githubusercontent.com/10132717/28619069-089be71c-7207-11e7-8928-07e3b24c7fac.png)

Best regards.

**Comment by SahilAgarwal321** [comment]
This is showing on all resources of code.google.com right now. It will probably be rectified in a while.
