### ISSUE TITLE
wordnet demo fails

### ISSUE THREAD

**Issue by TimFH** [nltk/nltk#1789]
Using nltk.3.2.4 with phython 3.6:

In [17]: pdb
Automatic pdb calling has been turned ON

In [18]: from nltk.corpus.reader.wordnet import demo

In [19]: demo()
loading wordnet
done loading
getting a synset for go
move.v.15 v verb.competition
['move', 'go']
have a turn; make one's move in a game
['Can I go now?']
[Synset('zap.n.01')]
[Synset('zap.v.01'), Synset('zap.v.02'), Synset('nuke.v.01'), Synset('microwave.v.01')]
Navigations:

<LOTS MORE STUFF, AND THEN>

AttributeError                            Traceback (most recent call last)
<ipython-input-21-00cf94af4371> in <module>()
----> 1 demo()

/Applications/anaconda3/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py in demo()
   2116     print(S('gin.n.1').substance_holonyms())
   2117 
-> 2118     print(L('leader.n.1.leader').antonyms())
   2119     print(L('increase.v.1.increase').antonyms())
   2120 

/Applications/anaconda3/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py in lemma(self, name, lang)
   1244         # cannot simply split on first '.',
   1245         # e.g.: '.45_caliber.a.01..45_caliber'
-> 1246         separator = SENSENUM_RE.search(name).start()
   1247         synset_name, lemma_name = name[:separator+3], name[separator+4:]
   1248         synset = self.synset(synset_name)

AttributeError: 'NoneType' object has no attribute 'start'
> /Applications/anaconda3/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py(1246)lemma()
   1244         # cannot simply split on first '.',
   1245         # e.g.: '.45_caliber.a.01..45_caliber'
-> 1246         separator = SENSENUM_RE.search(name).start()
   1247         synset_name, lemma_name = name[:separator+3], name[separator+4:]
   1248         synset = self.synset(synset_name)

ipdb> SENSENUM_RE
re.compile('\\.\\d\\d\\.')
ipdb> name
'leader.n.1.leader'
ipdb> SENSENUM_RE.search(name)
ipdb>

**Comment by campionfellin** [comment]
Hey, I'm new to this, but I think I found and solved the issue. Please let me know how I can actually commit the code for you guys.

Near the beginning of the file, line 115 for me, we need to change the regex that we define to this: 
`SENSENUM_RE = re.compile(r'\.[\d]+\.')`

and the lemma method should be changed to this:

<img width="694" alt="screen shot 2017-07-31 at 10 35 41 pm" src="https://user-images.githubusercontent.com/11984923/28806922-a0793156-7640-11e7-96cf-2291f1dfc31d.png">

Note that the changes are in lines 1247-1252 in my case

**Comment by campionfellin** [comment]
Hey @alvations can I verify this myself? If so, how? I'd love to get a PR in if possible.

**Comment by alvations** [comment]
@campionfellin It's a little unclear what is the question/issue here. I've added the `pleaseverify` tag just so that we can track or ask for more input from other developers/users that are having the same problem. 

Is it right that you're facing this error where the WordNet corpus interface demo threw an `AttributeError` as such?

```python
>>> import nltk
>>> nltk.corpus.reader.wordnet.demo()
loading wordnet
done loading
getting a synset for go
move.v.15 v verb.competition
[u'move', u'go']
have a turn; make one's move in a game
[u'Can I go now?']
[Synset('zap.n.01')]
[Synset('zap.v.01'), Synset('zap.v.02'), Synset('nuke.v.01'), Synset('microwave.v.01')]
Navigations:
[]
[Synset('travel.v.03')]
[]
[Lemma('atomic_warhead.n.01.nuke')]
[Lemma('atomization.n.02.atomization')]
[Lemma('atomization.n.02.atomisation')]
[]
[Synset('canis.n.01'), Synset('pack.n.06')]
[Synset('flag.n.07')]
[Synset('meal.n.01')]
[Synset('banquet.n.02'), Synset('bite.n.04'), Synset('breakfast.n.01'), Synset('brunch.n.01'), Synset('buffet.n.02'), Synset('dinner.n.01'), Synset('lunch.n.01'), Synset('mess.n.04'), Synset('nosh-up.n.01'), Synset('picnic.n.03'), Synset('ploughman's_lunch.n.01'), Synset('potluck.n.01'), Synset('refection.n.01'), Synset('square_meal.n.01'), Synset('supper.n.01'), Synset('tea.n.02')]
[Synset('writer.n.01')]
[Synset('ambrose.n.01'), Synset('bach.n.01'), Synset('barber.n.01'), Synset('bartok.n.01'), Synset('beethoven.n.01'), Synset('bellini.n.01'), Synset('berg.n.02'), Synset('berlioz.n.01'), Synset('bernstein.n.01'), Synset('bizet.n.01'), Synset('blitzstein.n.01'), Synset('bloch.n.01'), Synset('borodin.n.01'), Synset('boulez.n.01'), Synset('brahms.n.01'), Synset('britten.n.01'), Synset('bruch.n.01'), Synset('bruckner.n.01'), Synset('byrd.n.01'), Synset('cage.n.03'), Synset('chavez.n.01'), Synset('cherubini.n.01'), Synset('chopin.n.03'), Synset('copland.n.01'), Synset('corelli.n.01'), Synset('couperin.n.01'), Synset('coward.n.02'), Synset('czerny.n.01'), Synset('debussy.n.01'), Synset('delibes.n.01'), Synset('delius.n.01'), Synset('donizetti.n.01'), Synset('dowland.n.01'), Synset('dukas.n.01'), Synset('dvorak.n.01'), Synset('elgar.n.01'), Synset('enesco.n.01'), Synset('falla.n.01'), Synset('franck.n.01'), Synset('gershwin.n.02'), Synset('glinka.n.01'), Synset('gluck.n.01'), Synset('gounod.n.01'), Synset('grainger.n.01'), Synset('grieg.n.01'), Synset('halevy.n.01'), Synset('handel.n.01'), Synset('handy.n.01'), Synset('haydn.n.01'), Synset('hindemith.n.01'), Synset('honegger.n.01'), Synset('humperdinck.n.01'), Synset('ibert.n.01'), Synset('ives.n.01'), Synset('joachim.n.01'), Synset('joplin.n.02'), Synset('kachaturian.n.01'), Synset('kern.n.01'), Synset('khachaturian.n.01'), Synset('lambert.n.02'), Synset('lasso.n.01'), Synset('ledbetter.n.01'), Synset('lehar.n.01'), Synset('liszt.n.01'), Synset('lloyd_webber.n.01'), Synset('loewe.n.01'), Synset('lully.n.02'), Synset('macdowell.n.01'), Synset('mahler.n.01'), Synset('massenet.n.01'), Synset('mendelssohn.n.01'), Synset('menotti.n.01'), Synset('meyerbeer.n.01'), Synset('milhaud.n.01'), Synset('monteverdi.n.01'), Synset('moore.n.01'), Synset('mozart.n.01'), Synset('mussorgsky.n.01'), Synset('nielsen.n.01'), Synset('offenbach.n.01'), Synset('orbison.n.01'), Synset('palestrina.n.01'), Synset('piston.n.01'), Synset('porter.n.04'), Synset('poulenc.n.01'), Synset('prokofiev.n.01'), Synset('puccini.n.01'), Synset('purcell.n.01'), Synset('rachmaninoff.n.01'), Synset('rameau.n.01'), Synset('ravel.n.01'), Synset('reich.n.03'), Synset('respighi.n.01'), Synset('rimsky-korsakov.n.01'), Synset('rodgers.n.01'), Synset('romberg.n.01'), Synset('rossini.n.01'), Synset('rubinstein.n.02'), Synset('saint-saens.n.01'), Synset('satie.n.01'), Synset('schnabel.n.01'), Synset('schonberg.n.01'), Synset('schubert.n.01'), Synset('schumann.n.01'), Synset('schumann.n.02'), Synset('scriabin.n.01'), Synset('segovia.n.01'), Synset('sessions.n.01'), Synset('shostakovich.n.01'), Synset('sibelius.n.01'), Synset('smetana.n.01'), Synset('sondheim.n.01'), Synset('sousa.n.01'), Synset('strauss.n.01'), Synset('strauss.n.02'), Synset('strauss.n.03'), Synset('stravinsky.n.01'), Synset('sullivan.n.05'), Synset('tallis.n.01'), Synset('taylor.n.01'), Synset('tchaikovsky.n.01'), Synset('telemann.n.01'), Synset('thomson.n.01'), Synset('varese.n.01'), Synset('vaughan_williams.n.01'), Synset('verdi.n.01'), Synset('villa-lobos.n.01'), Synset('vivaldi.n.01'), Synset('wagner.n.02'), Synset('walton.n.01'), Synset('weber.n.05'), Synset('weill.n.01'), Synset('wolf.n.02')]
[Synset('professor.n.01')]
[Synset('crew.n.01')]
[Synset('leg.n.03'), Synset('tabletop.n.01'), Synset('tableware.n.01')]
[Synset('meal.n.01')]
[Synset('hydrogen.n.01'), Synset('oxygen.n.01')]
[Synset('gin_and_it.n.01'), Synset('gin_and_tonic.n.01'), Synset('martini.n.01'), Synset('pink_lady.n.01')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 2118, in demo
    print(L('leader.n.1.leader').antonyms())
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1246, in lemma
    separator = SENSENUM_RE.search(name).start()
AttributeError: 'NoneType' object has no attribute 'start'
```

And the changes you're proposing is to change how the lemmas are read in [the function that loads the Wordnet lemmas](https://github.com/alvations/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L1242).

To do some it is to change the `SENSENUM_RE` regex at https://github.com/alvations/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L115 to this

```
SENSENUM_RE = re.compile(r'\.[\d]+\.')
```


P/S: In the future, please try to present the code in [markdown format](https://help.github.com/articles/creating-and-highlighting-code-blocks/) so that it's more readable =)

**Comment by alvations** [comment]
Now that's a strange bug =) (Related to #1724)

Partly because all lemmas should be indexed with double digits from Princeton WordNet but I think your proposed solution is right to use `[\d]+` to capture the lemma number instead of enforing the double digit. 

Please feel free to create a PR and someone will review it before it's merged. 

Thank you for raising this issue!

**Comment by campionfellin** [comment]
Hey @alvations yes, I am getting the same error. I will go ahead and create a PR, but before I do so, do you think that the `leadingZero = int(name[separator+1]) == 0` logic is correct? I realize that this, with the if/else will only work for single digit numbers and the numbers 00-09. For example, I don't believe it would work if you had something like `meal.n.10` or `meal.n.001`

**Comment by alvations** [comment]
@campionfellin sorry for replying late. I think there isn't any synsets with more than 99+ lemmas in WordNet (but I could be wrong). So assuming leading zeros should be correct.  

We might have to run more checks / write better test to test out the lemma numbers though. 
(Related to #1724)

**Comment by campionfellin** [comment]
@alvations Let's close this issue, as the PR has been merged.
