### ISSUE TITLE
nltk.download()

### ISSUE THREAD

**Issue by visonforcoding** [nltk/nltk#1790]
403 Forbiden

same result as i  open https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml with browser

**Comment by alvations** [comment]
Please see #1787

**Comment by kirankotari** [comment]
#1792 A workaround could be found on this thread

**Comment by alvations** [comment]
Please see #1787
Let's consolidate the same problem to #1787 so that we don't end up tracking the same bug on the different issues.
