### ISSUE TITLE
NlTK downloading corpus using nltk.download() giving 403 error

### ISSUE THREAD

**Issue by datNurd** [nltk/nltk#1791]
I've tried downloading punkt corpus using nltk.download() as well as manually from http://www.nltk.org/nltk_data/ both are giving me a 403 forbidden, Varnish cache server error.

**Comment by usakey** [comment]
#1787 A workaroud could be found on this thread.

**Comment by datNurd** [comment]
Even the solution/work around in #1787 giving a 403 response. Even that did not work for me.

**Comment by usakey** [comment]
@pnikhilvarma try below zip file solution rather than the `Downloader` one:

```
export PATH_TO_NLTK_DATA=/home/username/nltk_data/
wget https://github.com/nltk/nltk_data/archive/gh-pages.zip
unzip gh-pages.zip
mv nltk_data-gh-pages $PATH_TO_NLTK_DATA
# add below code
mv $PATH_TO_NLTK_DATA/nltk_data-gh-pages/packages/* $PATH_TO_NLTK_DATA/
```

**Comment by kirankotari** [comment]
#1792  A workaround could be found on this thread.

**Comment by alvations** [comment]
Please see #1787
Let's consolidate the same problem to #1787 so that we don't end up tracking the same bug on the different issues.
