### ISSUE TITLE
nltk.download() pointing to wrong url

### ISSUE THREAD

**Issue by kirankotari** [nltk/nltk#1792]
1. the packages are not loading for the following url: https://raw.githubusercontent.com/nltk/nltk_data
HTTP 403 Error

2. After changing the server index to http://www.nltk.org/nltk_data/
still each package pointing to 'https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/abc.zip'
which is giving HTTP 403 Error

**Comment by kirankotari** [comment]
As I can't change the package url which is loading from the web. I am using the following code to solve my problem
in `downloader.py` line no. 619
use this: 
info.url = 'http://www.nltk.org/nltk_data/packages/corpora/'+info.url.split('/')[-1]
infile = urlopen(info.url)

**Comment by alvations** [comment]
Please see #1787 
Let's consolidate the same problem to #1787 so that we don't end up tracking the same bug on the different issues.

**Comment by kirankotari** [comment]
I am getting the following error on 
wget https://github.com/nltk/nltk_data/archive/gh-pages.zip

ERROR: cannot verify github.com's certificate, issued by `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA':
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.

**Comment by kirankotari** [comment]
With my solution one of the package is not available on 'http://www.nltk.org/nltk_data/packages/corpora/'
moses_sample.zip
