### ISSUE TITLE
Adding appropriate message to LazyCorpusLoader for nltk.download

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1793]
Following up on #1787, it would be great if the users download specific corpora / models instead of abusing `nltk.download('all')`. 

@alexisdimi gave a good suggestion to warn the user with the appropriate package to download when an error is raised at model/data loading. 

For corpora,  this can be easily patched with specific details to the warning on the `LazyCorpusLoader` object, when loading the corpus at https://github.com/nltk/nltk/blob/develop/nltk/corpus/util.py#L67

**Comment by gbrova** [comment]
+1

Possibly related, it would also be great to have an easy and consistent way to programmatically check whether a package exists and download it if it's missing. 

For example, `nltk.data.find('tokenizers/punkt')` will search, but`nltk.download('tokenizers/punkt')` errors out with "not found in index". Also, searching for other packages like `nltk.data.find('sentiment/vader_lexicon')` (and other variants I could think of) doesn't find the package even when it's already downloaded. 

Happy to spend a couple hours on this as my first NLTK bug, but I'm not super familiar with the codebase so let me know if you have thoughts about how to approach it.

**Comment by alvations** [comment]
@gbrova the updated error message should include the instruction of how to download the packaged =)

Resolved in #1806
