### ISSUE TITLE
Babelfish Translation Does Not Support Encoding

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#180]
VERSION: 2.0.1rc1

&gt;&gt;&gt; import nltk
# t is a variable containing some greek text

&gt;&gt;&gt; t
u'\u0397 \u0395\u03c4\u03b1\u03b9\u03c1\u03b5\u03af\u03b1'
# it doesnt like the unicode string

&gt;&gt;&gt; nltk.misc.babelfish.translate(t, 'greek', 'english')
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/home/dwisong/opt/lib/python2.7/site-packages/nltk/misc/babelfish.py&quot;, line 108, in translate
    params = urllib.urlencode(params)
  File &quot;/usr/lib/python2.7/urllib.py&quot;, line 1282, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0397' in position 0: ordinal not in range(128)
# so, i thought i could just encode it to utf-8.. however, what i get back is not translated greek

&gt;&gt;&gt; nltk.misc.babelfish.translate(t.encode('utf-8'), 'greek', 'english')
'\xce \x97 \xce \x95 \xcf \x84 \xce\xb1\xce \xb9 \xcf \x81 \xce[M]\xce\xaf\xce\xb1'
# but, if you implement the babelfish encoding parameter 'ei' through a code change that i made adding an encoding= option to the translate function

&gt;&gt;&gt; translate(t.encode('utf-8'), 'greek', 'english', encoding='utf-8')
'The company'
# CODE FOLLOWS

def translate(phrase, source, target, encoding=''):
    &quot;&quot;&quot;
    Use babelfish to translate phrase from source language to target language.
    It's only guaranteed to work if 'english' is one of the two languages.

```
@raise BabelizeError: If an error is encountered.
&quot;&quot;&quot;

phrase = clean(phrase)
try:
    source_code = __languages[source]
    target_code = __languages[target]
except KeyError, lang:
    raise ValueError, &quot;Language %s not available&quot; % lang

params = {'doit': 'done',
          'tt': 'urltext',
          'urltext': phrase,
          'lp': source_code + '_' + target_code}

if encoding:
    params['ei'] = encoding

params = urllib.urlencode(params)
try:
    response = urllib.urlopen('http://babelfish.yahoo.com/translate_txt', params)

except IOError, what:
    raise BabelizerIOError(&quot;Couldn't talk to server: %s&quot; % what)

html = response.read()
for regex in __where:
    match = regex.search(html)
    if match: break
if not match: raise BabelfishChangedError(&quot;Can't recognize translated string.&quot;)
return clean(match.group(1))
```

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=718</p>

**Comment by godisball** [comment]
Babel> who are you?
Babel> run
Please specify a language first (type 'languages' for a list).
Babel> greek
Babel> run
0> who are you?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nltk/misc/babelfish.py", line 175, in babelize_shell
    for count, new_phrase in enumerate(babelize(phrase, 'english', language)):
  File "/Library/Python/2.7/site-packages/nltk/misc/babelfish.py", line 126, in babelize
    phrase = translate(phrase, next, flip[next])
  File "/Library/Python/2.7/site-packages/nltk/misc/babelfish.py", line 106, in translate
    if not match: raise BabelfishChangedError("Can't recognize translated string.")
nltk.misc.babelfish.BabelfishChangedError: Can't recognize translated string.

how can i work out it? thx:)))

**Comment by kmike** [comment]
You can't because Babelfish online translation service is shut down and nltk.misc.babelfish requires it.

**Comment by godisball** [comment]
oh..i got it .....thank u
