### ISSUE TITLE
NLTK looking for Python -32

### ISSUE THREAD

**Issue by KEAppleby** [nltk/nltk#1803]
First, my apologies if this isn't the correct venue to ask this question -- if it's not, I would appreciate suggestions as to where to ask it.  Also, my apologies if this is a duplicate question....I attempted to search for it in previous dialogs but with no luck.

I've installed Python 3.5, 32-bit since it appears NLTK only interfaces with this version.  When I try to install NLTK (following the link on the NLTK home page),  I get a message that it requires Python -32 and can't find it in the registry.

My understanding from poking around on-line is that the installer is looking for Python with an extension of -32.  In looking in HKEY_CURRENT_USERS in the registry, it appears that, except for the first line in the registry,  references to -32 are there.  Example:
[HKEY_CURRENT_USER\Software\Python\PythonCore]

[HKEY_CURRENT_USER\Software\Python\PythonCore\3.5-32]

[HKEY_CURRENT_USER\Software\Python\PythonCore\3.5-32\Help]

and many more....

I also found some leftover references to Python 3.4 (installed previously and deleted) in the HKEY_LOCAL_MACHINE portion of the registry with no reference to -32:
[HKEY_LOCAL_MACHINE\SOFTWARE\Python]

[HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore]

[HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.4]

[HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.4\Modules]

Python 3.5 is the only version installed on my machine.  Questions:
1.  Are the leftover references to 3.4 in LOCAL_MACHINE causing problems?
2.  If not, are the -32 references in the right place (CURRENT_USER)?

As you might imagine, I don't want to mess with the registry unless I'm sure I'm going the right direction.

Thanks.

Karen

**Comment by alvations** [comment]
@KEAppleby does the instructions on https://gist.github.com/alvations/0ed8641d7d2e1941b9f9 help to resolve your installation issue?

**Comment by KEAppleby** [comment]
YES!  Thank you.

Karen Appleby



________________________________

**Comment by alvations** [comment]
Resolved by external documentation but I agree that documentation for Windows installation could be better. Let's open a separate issue to track that. 

Closing issue in preparation for v3.2.5
