### ISSUE TITLE
PCFG should infer uniform probability for unspecified probabilities

### ISSUE THREAD

**Issue by uriva** [nltk/nltk#1812]
If one has 10 RHS elements in a PCFG production rule, it is quite cumbersome to calculate the probabilities for each one to get it to be uniform.

Also it is quite common that I want to make a certain rhs less probable than others, in which case I would have wanted to give only probability for that one rule, and let the others be uniform on the remainder of the probability.

Would such a pull request be merged? Does this make sense? Is something in the works?

**Comment by alvations** [comment]
@uriva thank you for suggesting the feature/fix. 

Could you explain the problem/suggestion further with some code and sample inputs/outputs?

It's a little unclear what you're proposing. 

Is it also related to #1811 ?

**Comment by uriva** [comment]
It might make the other issue easier to implement but it isn't directly related.

I mean that if I have

A ->  b1 | b2 | b3 | b4 | b5 | b6

In a PCFG, I have to divide 100/6 then assign this probability manually to each one of the rhs possibilities.

Then if I just add another rhs possibility I have ruined everything and need to recompute.

This is all due to the demand that the probabilities add up to 1.

All these problems would be solved also if NLTK would support a WCFG. 

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
