### ISSUE TITLE
Better installation instructions for Windows

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1817]
Windows users faces issues when installing NLTK. 
We should have better documentation to install and use NLTK in Windows. 

Anyone up to write some extended documentation and improve the [nltk webpage](https://github.com/nltk/nltk.github.com) ?

**Comment by campionfellin** [comment]
Hey @alvations I can probably do this. Do you know what the common installation issues are? I can write up detailed instructions for Windows 7 and Windows 10 and maybe an FAQ for common issues.

**Comment by alvations** [comment]
I'm not exactly sure how people are using Python / Anaconda in NLTK but I've been referring people to https://gist.github.com/alvations/0ed8641d7d2e1941b9f9 but there should be a documentation more canonical on NLTK.

**Comment by campionfellin** [comment]
Hmm, that documentation looks pretty thorough to me. I'll leave this and let someone who has more experience using NLTK on windows work on the documentation.

**Comment by alvations** [comment]
Hopefully, documentation for installation should be much better when #2170 is merged. 

Please do re-open the issue if anyone wants to improve the Windows related installation instructions =)
