### ISSUE TITLE
Unable to finish downloading book files -- download crashes on reuters file

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#182]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>

2.0.1rc1

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>

import nltk
nltk.download()

NLTK Downloader appears

Select &quot;book&quot; in &quot;Collections&quot; tab

Click Download button

Download proceeds all right until &quot;Downloading package 'reuters'&quot;

Download stops -- error message: &quot;Error with downloaded zip file&quot;

<b>What is the expected output? What do you see instead?</b>

Expect to see Download completed; see error message instead: &quot;Error with downloaded zip file&quot;

When I click Cancel button to close the Downloader, I get the following exception: 

/Library/Python/2.6/site-packages/nltk/**init**.py:658: DeprecationWarning: object.**new**() takes no parameters
showing info http://nltk.googlecode.com/svn/trunk/nltk_data/index.xml
Exception in Tkinter callback
Traceback (most recent call last):
  File &quot;/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-tk/Tkinter.py&quot;, line 1410, in **call**
  File &quot;/Library/Python/2.6/site-packages/nltk/downloader.py&quot;, line 1525, in _download
    return self._download_threaded(*e)
  File &quot;/Library/Python/2.6/site-packages/nltk/downloader.py&quot;, line 1788, in _download_threaded
    assert self._download_msg_queue == []
AssertionError
True

<b>Please use labels and text to provide additional information.</b>

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=727</p><hr/><h2>earlier comments</h2>
<p><strong>ranju@b-eagles.com said, at 2011-11-10T09:36:50.000Z:</strong></p>

<p>I upgraded to python 2.7 and getting the same error.
But for me it is a different file, brown_tei.zip.

When I try to unzip the file using 7zip, I get an error.
When I look at the code, the error is rightly being thrown when the file is being unzipped.

Does this mean that there are some files which are corrupt on the nltk server?</p><p><strong>waynev said, at 2011-11-16T06:23:51.000Z:</strong></p>

<p>I'm getting the same error with Python 2.7.2, nltk 2.0b9 on Windows 7 32 bit.
But I'm getting the error on the file conll2002.zip
This .zip file appears to be invalid, since if I try to open it with Windows, it fails with the message "The compressed (zipped) folder ...\conll2002.zip is invalid"</p><p><strong>waynev said, at 2011-11-17T04:30:54.000Z:</strong></p>

<p>However, Python 2.6.6, nltk 2.0b9 on Windows Vista SP 2 32 bit works fine.</p>

**Comment by destec** [comment]
I think i've got the solution. You can download all the data from [http://nltk.org/nltk_data/](http://nltk.org/nltk_data/), then you dont need to extract the zip files. Just run `nltk.download()` again.

**Comment by stevenbird** [comment]
I expect this issue is stale.
