### ISSUE TITLE
Construct nltk.translate.PhraseTable and a language model

### ISSUE THREAD

**Issue by alexeyev** [nltk/nltk#1823]
Hi! Thanks for the cool library!

I'm trying to build a toy end-to-end machine translation example with NLTK.

Just wondering if there is a simple way to build a language model and, most importantly, a PhraseTable for feeding into a StackDecoder (given my own parallel corpus)?

If not, could you please provide me with ideas on a fast and simple way to do it?

Thanks in advance.

**Comment by SundusJ** [comment]
I want to build a SMT model in python. Can anyone gives me the idea of doing it with parallel corpus?
