### ISSUE TITLE
Skip downloader.py input() prompts when no TTY attached

### ISSUE THREAD

**Issue by edmorley** [nltk/nltk#1825]
In heroku/heroku-buildpack-python#444 an `EOFError: EOF when reading a line` was raised after an nltk_data download failed and downloader.py prompted with "Error installing package. Retry? [n/y/e]".

Whilst that prompt can be suppressed by passing `--quiet`:
https://github.com/nltk/nltk/blob/3.2.4/nltk/downloader.py#L679-L688
...doing so means losing useful debugging information.

What would be great is if either:
(a) The `input()` would be skipped if no TTY were attached
(b) There was an additional `--no-prompt` option, in addition to `--quiet`, so users who want the more verbose output can still keep it

Many thanks :-)

**Comment by edmorley** [comment]
**STR:**
1) `pip install nltk==3.2.4`
2) `python2 -m nltk.downloader -d 'nltk_data' 'zzzzzz' | sed "s/^/       /"`

**Expected:**
Error message shown about non-existent package.

**Actual:**
Command hangs until a ctrl+c, since it's stuck at the prompt.

**Comment by alvations** [comment]
The command is hanging because there Python is expecting the user to respond to a prompt, so the `| sed ...` isn't executed. 

```
$ python -m nltk.downloader -d nltk_data zzz 
[nltk_data] Error loading zzz: Package 'zzz' not found in index
Error installing package. Retry? [n/y/e]
```

**Comment by edmorley** [comment]
Yup I realise, see the OP for what is being requested here.

**Comment by alvations** [comment]
Would the [`--exit-on-error` option](https://github.com/nltk/nltk/blob/3.2.4/nltk/downloader.py#L2258) be sufficient?

```
$ python -m nltk.downloader -d nltk_data zzz --exit-on-error
[nltk_data] Error loading zzz: Package 'zzz' not found in index
$
```

Actually, `--quiet` also exits on error:

```
$ python -m nltk.downloader -d nltk_data zzz --quiet
[nltk_data] Error loading zzz: Package 'zzz' not found in index
$
```

Both `--exit-on-error` and `--quiet` keeps the prompt.  Or should something like `--skip-on-error` be implemented?

Or should it be that `--quiet` returns no prompt, add another arguments to keep the prompt?
