### ISSUE TITLE
How to train a LM with my own corpus?I can not find an example anywhere

### ISSUE THREAD

**Issue by yangbisheng2009** [nltk/nltk#1827]

**Comment by alvations** [comment]
@yangbisheng2009 The language model functionality has not been officially been merged to the `nltk`, the contribution from @Copper-Head went stale. It'll be good if someone can pick it up and revive it but for now, there's no one actively working on the language model functionality

The code for language modelling resides in https://github.com/nltk/nltk/tree/model/nltk/model

**Comment by iliakur** [comment]
@yangbisheng2009 @alvations is it ok to close this now that the lm stuff has been merged?

**Comment by alvations** [comment]
Thanks @Copper-Head!! Using the docs in the code, I've also put up https://www.kaggle.com/alvations/n-gram-language-model-with-nltk (just in case anyone is interested).
