### ISSUE TITLE
max_depth and min_depth goes in a recursive infinite loop for certain lemmas in wordnet

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#183]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>
2.0.1rc1

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
# includes

from collections import defaultdict
from nltk.corpus import wordnet as wn
import nltk
# does not work

syn=wn.synset(&quot;localize.v.03&quot;)
print syn.max_depth()
print syn.min_depth()
# works

syn=wn.synset(&quot;localize.v.02&quot;)
print syn.max_depth()
print syn.min_depth()

<b>What is the expected output? What do you see instead?</b>
expect to see an integer with the maximum distance to the root hypernym and the minimum distance to the root hypernym for max_depth and min_depth respectively

I am getting
RuntimeError: maximum recursion depth exceeded in cmp

<b>Please use labels and text to provide additional information.</b>

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=729</p><hr/><h2>earlier comments</h2>
<p><strong>jordanbg said, at 2011-12-27T17:51:11.000Z:</strong></p>

<p>I can't reproduce this error - is this using WordNet 3.0?

>>> from nltk.corpus import wordnet as wn
>>> syn=wn.synset("localize.v.03")
>>> syn.min_depth()
6
>>> syn.max_depth()
6
>>> syn.hypernyms()
[Synset('restrict.v.02')]
>>> syn.instance_hypernyms()
[]</p><p><strong>gmatty said, at 2012-01-04T00:24:56.000Z:</strong></p>

<p>This is using wordnet 3.0. It seems to be following  restrict back to localize and from localize back to restrict.</p><p><strong>jordanbg said, at 2012-01-04T01:44:24.000Z:</strong></p>

<p>Hmm ... this does not seem consistent with my copy of WN 3.0.  Could you send me your index.verb file?  If I had a WordNet that had a loop, I could make sure this didn't happen.
</p><p><strong>gmatty said, at 2012-01-11T04:29:29.000Z:</strong></p>

<p>No problem. I've attached the index.verb file.</p>

**Comment by stevenbird** [comment]
Has there been any resolution?

**Comment by kmike** [comment]
I can't reproduce this issue either (WN is obtained using nltk.download).
