### ISSUE TITLE
NBC most informative features method does not report features that are always present in a label and not in the other class.

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#184]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>

2.0b8 (naivebayes.py 2063). 2063 is the present version.

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>

import nltk
labeled_featuresets = [({'viagra': True}, 'spam'), 
                       ({'hello': True}, 'ok')]
classifier = nltk.NaiveBayesClassifier.train(labeled_featuresets)
classifier.show_most_informative_features()

This just writes &quot;Most Informative Features&quot;

<b>What is the expected output? What do you see instead?</b>

Apart from &quot;Most Informative Features&quot; I would expect to see 'viagra' and 'hello' listed. 

<b>Please use labels and text to provide additional information.</b>

I seems to be an issue with the use of the .samples method line 134 and 165 in nltk/nltk/classify/naivebayes.py.

Another example is: 

labeled_featuresets = [({'viagra': True, 'casino': True}, 'spam'), 
                           ({'viagra': True}, 'spam'), 
                           ({'hello': True}, 'ok')]
classifier = nltk.NaiveBayesClassifier.train(labeled_featuresets)
classifier.show_most_informative_features()

This lists only:

Most Informative Features
                  casino = None               ok : spam   =      1.5 : 1.0

Instead of 

```
              viagra = None               ok : spam   =      4.5 : 1.0
               hello = True               ok : spam   =      4.5 : 1.0
               hello = None             spam : ok     =      3.3 : 1.0
              viagra = True             spam : ok     =      3.3 : 1.0
              casino = True             spam : ok     =      2.0 : 1.0
              casino = None               ok : spam   =      1.5 : 1.0
```

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=730</p>

**Comment by fnielsen** [comment]
Note a feature with value None is problematic. Here is an example with full feature set:

labeled_featuresets = [
      ({'viagra': True, 'buy': True, 'hi': False}, 'spam'), 
      ({'viagra': True, 'buy': False, 'hi': False}, 'spam'), 
      ({'viagra': False, 'buy': False, 'hi': True}, 'ok')]
classifier = nltk.NaiveBayesClassifier.train(labeled_featuresets)
classifier.show_most_informative_features()

The result is

Most Informative Features
                     buy = False              ok : spam   =      1.4 : 1.0

**Comment by jayvdb** [comment]
Should something be done about using None values?
An exception?
