### ISSUE TITLE
Bug in NLTK with Python3.5

### ISSUE THREAD

**Issue by ghost** [nltk/nltk#1850]
I used tutorial from book http://www.nltk.org/book/ch07.html
```
sent = 'Google is best company'
sent = nltk.corpus.treebank.tagged_sents()
r = nltk.ne_chunk(sent)
```
and got

>          183 
>          184 def simplify_pos(s):
>     --> 185     if s.startswith('V'): return "V"
>          186     else: return s.split('-')[0]
>          187 
> 
> AttributeError: 'tuple' object has no attribute 'startswith'

**Comment by stevenbird** [comment]
`ne_chunk` requires a tagged sentence. Please read the docs.
