### ISSUE TITLE
How to get the full Penn Treebank?

### ISSUE THREAD

**Issue by bofinbabu** [nltk/nltk#1855]
Any ideas to get the Penn Treebank?

I've checked the LDC site. The price is too high that I can't afford it. 

I want it for the purpose of Semantic Role Labelling.

**Comment by alvations** [comment]
@bofinbabu NLTK has several subset of the PTB corpus, `brown`, `switchboard` and `ptb` (sample) but for the full corpus please contact ldc@ldc.upenn.edu .

----

If I'm not wrong, the [Penn Treebank](https://catalog.ldc.upenn.edu/ldc99t42) should be free under the **LDC User Agreement for Non-Members** for academic purposes. Please contact ldc@ldc.upenn.edu for the details.

**Comment by bofinbabu** [comment]
Thanks sent them a mail
