### ISSUE TITLE
ElementTree.ParseError: not well-formed 

### ISSUE THREAD

**Issue by cdraper-CS** [nltk/nltk#1858]
I am getting a similar issue to #1832 

```
bash-4.3# /opt/conda/envs/py27/bin/python -m nltk.downloader wordnet
Traceback (most recent call last):
  File "/opt/conda/envs/py27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/conda/envs/py27/lib/python2.7/runpy.py", line 72, in _run_code
...
  File "/opt/conda/envs/py27/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/opt/conda/envs/py27/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

The diagnostics you asked for in that ticket
[out.txt](https://github.com/nltk/nltk/files/1383914/out.txt)
 (index.xml) are attached

**Comment by alvations** [comment]
The `index.xml` file should work fine, even from the `out.txt` you've attached there's no error. 
The strange thing is ETree breaks at the first character (at line 1 column 0).

Which OS are you on?
Which Python version are you using? 

```
>>> import sys
>>> print(sys.version)
2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
```

**Comment by cdraper-CS** [comment]
Building in an alpine-based Docker container, alpine release 3.6.2

python:
```
2.7.14 |Anaconda, Inc.| (default, Oct 13 2017, 10:47:14)
[GCC 7.2.0] 
```

**Comment by cdraper-CS** [comment]
fwiw I get the same error using the same python on my Mac OSX 10.11.6, and with python 2.7.12

**Comment by cdraper-CS** [comment]
OK... it seems to be a problem with nltk 3.0.0 - if I upgrade to 3.2.5, I can download it.

**Comment by alvations** [comment]
@cdraper-CS Thanks for reporting this, yes, 3.0.0 is badly outdated. 
Great to know that it was a version problem =)

Does upgrading the NLTK and/or anaconda on the alphine-docker resolve the problem in Docker too?

**Comment by stevenbird** [comment]
Thanks @cdraper-CS and @alvations
