### ISSUE TITLE
Inconsistient behavior of wordnet/synset/shortest_path_distance

### ISSUE THREAD

**Issue by dtldarek** [nltk/nltk#186]
# Issue

I observed inconsistient behavior of wordnet/synset/shortest_path_distance: for both (dog,cat) and (bat, cat) it returns 4 while the shortest path distance found by the script below are as follows:
[Synset('dog.n.01'), Synset('domestic_animal.n.01'), Synset('domestic_cat.n.01'), Synset('cat.n.01')]  # size 4
[Synset('bat.n.01'), Synset('placental.n.01'), Synset('carnivore.n.01'), Synset('feline.n.01'), Synset('cat.n.01')] # size 5
# Python version: Python 2.7.2+
# NLTK version: @version: 2.0b9
# The script

``` python
#!/usr/bin/python

import nltk
from nltk.corpus import wordnet as wn

def shortest(thing1, thing2, diff):
    print "shortest(%s, %s, %d):"%(thing1, thing2, diff)                           
    thing1s = wn.synsets(thing1)
    thing2s = wn.synsets(thing2)
    distance = min([d for d in [x.shortest_path_distance(y) for x in thing1s for y in thing2s if x != y] if d != None])
    def dfs(goal, path, bound):
        last = path[-1]
        if bound == 0:
            if goal == last:
                print path
        else:
            for x in last.hypernyms():
                path.append(x)
                dfs(goal, path, bound-1)
                path.pop()
            for x in last.hyponyms():
                path.append(x)
                dfs(goal, path, bound-1)
                path.pop()
    for start in thing1s:
        for end in thing2s:
            dfs(end, [start], distance + diff)
    print

shortest('dog', 'cat',  0)  
shortest('dog', 'cat', -1) 
shortest('bat', 'cat',  0)  
shortest('bat', 'cat', -1) 
```
# The output:

``` python
shortest(dog, cat, 0):
[Synset('dog.n.01'), Synset('canine.n.02'), Synset('carnivore.n.01'), Synset('feline.n.01'), Synset('cat.n.01')]
[Synset('dog.n.01'), Synset('canine.n.02'), Synset('carnivore.n.01'), Synset('feline.n.01'), Synset('big_cat.n.01')]
[Synset('dog.n.03'), Synset('chap.n.01'), Synset('male.n.02'), Synset('man.n.01'), Synset('guy.n.01')]

shortest(dog, cat, -1):
[Synset('dog.n.01'), Synset('domestic_animal.n.01'), Synset('domestic_cat.n.01'), Synset('cat.n.01')]

shortest(bat, cat, 0):
[Synset('bat.n.01'), Synset('placental.n.01'), Synset('carnivore.n.01'), Synset('feline.n.01'), Synset('cat.n.01')]
[Synset('bat.n.01'), Synset('placental.n.01'), Synset('carnivore.n.01'), Synset('feline.n.01'), Synset('big_cat.n.01')]

shortest(bat, cat, -1):
#nothing
```

**Comment by stevenbird** [comment]
Would you mind looking at our implementation of shortest path distance to see why there is a difference?

**Comment by dtldarek** [comment]
I have read through the code after submitting the issue. The most probable cause is because nltk's algorithm searches only for path of the form /\ (meaning going to root and back), and my algorithm can find path of the form /\/\/\/ etc. (because it's just a simple dfs). First sentence of the documentation says that "Returns the distance of the shortest path linking the two synsets (if one exists)." and that does not qualify on the shape of the path (even if there is a description of the algorithm below). In the example it happens that dog is a domestic animal, but cat is not, however, some special cats called domestic cats are domestic animals, so the path has the shape dog / domestic animal \ domestic cat / cat. 

Knowing what I know now (after reading the algorithm's code) I am not sure I would post the issue here. Still naming shortest_path_distance an entirely different algorithm (which in fact probably runs faster and can sometimes be a substitute for the real shortest path) makes me fell uneasy -- one shouldn't do that! It is not my choice what to do with it (maybe the majority of nltk users do want present version), I can only voice my concerns (for those that are careless enough that they do not read the algorithm's code before using it), and this is what I am doing right now (and I dodged the issue and moved on long time ago, so my concerns are only superficial).

**Comment by mrmechko** [comment]
Has anyone thought further about this issue? I am implementing `shortest_path` for a `scala` interface to WordNet and I am wondering if `shortest_hypernym_path` is 'good-enough' to compare to most implementations.
