### ISSUE TITLE
TextTiling not support python 3

### ISSUE THREAD

**Issue by talbaumel** [nltk/nltk#1861]
In line 315 `clip = min(max(len(scores)/10, 2), 5)` you should wrap this value with a `int` because python 3 division type is float.

Thanks

**Comment by alvations** [comment]
Related #965 #1537 and https://github.com/nltk/nltk/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20texttiling 

I think this is a long standing bug that hasn't been fixed and the fix could be pretty simple. Let's try to patch this by the next release ;P

**Comment by zorroblue** [comment]
I would like to work on this :)

**Comment by e5pecial** [comment]
https://github.com/nltk/nltk/pull/1863
This bug was fixed :)

**Comment by alvations** [comment]
@e5pecial Thanks for the note!

@zorroblue Thank you for your interest, if you're up to contribute on something else, you can try browsing the `goodfirstbug` tag: https://github.com/nltk/nltk/labels/goodfirstbug . Or if you're interested to work on the related issues, there's #965 and #1537.

Resolved in #1863
