### ISSUE TITLE
TreebankWordTokenizer.span_tokenize() throws Exceptions for corner case strings

### ISSUE THREAD

**Issue by yibinlin** [nltk/nltk#1865]
This comes from one of the sentence in my work. I have created https://github.com/nltk/nltk/pull/1864 as a fix.

to reproduce:

```
>>> from nltk.tokenize import TreebankWordTokenizer
>>> s = '''I said, "I'd like to buy some ''good muffins" which cost $3.88\\n each in New (York)."'''
>>> TreebankWordTokenizer().span_tokenize(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/nltk/tokenize/treebank.py", line 167, in span_tokenize
    return align_tokens(tokens, text)
  File "/usr/local/lib/python2.7/site-packages/nltk/tokenize/util.py", line 232, in align_tokens
    raise ValueError('substring "{}" not found in "{}"'.format(token, sentence))
ValueError: substring "``" not found in "I said, "I'd like to buy some ''good muffins" which cost $3.88\n each in New (York).""
```

Also I have a question - I am not sure why the pull request check didn't run? The error seems to be here: https://nltk.ci.cloudbees.com/job/pull_request_tests/TOXENV=py27-jenkins,jdk=jdk8latestOnlineInstall/lastBuild/console 

It looks like I did something terribly wrong somewhere. This is my first pull request to nltk, could anyone help? Thank you!

**Comment by alvations** [comment]
Thanks again @yibinlin ! 

Resolved in #1864
