### ISSUE TITLE
UnicodeEncodeError when chunking non-ASCII text

### ISSUE THREAD

**Issue by jgarbers** [nltk/nltk#1877]
I've encountered a UnicodeEncodeError when chunking text that includes non-ASCII characters, using Python 2.7.12 and NLTK 3.2.5. As a new user of NLTK, there may be some subtleties when working with Unicode that I'm not sensitive to yet, but here's a sample bit of code that demonstrates the problem:

```
import nltk

text = u"You may have heard of Ren\xe9 Descartes."
tagged = nltk.pos_tag(nltk.word_tokenize(text))
entities = nltk.chunk.ne_chunk(tagged)
print entities
```

When run, this code reports an error at the chunking line above, ending with the report
```
 File "/Users/jeffgarbers/.virtualenvs/nlplay/lib/python2.7/site-packages/nltk/chunk/named_entity.py", line 104, in _feature_detector   
  'word+nextpos': '{0}+{1}'.format(word.lower(), nextpos),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)
```

It seems that the error goes away if the format strings in lines 104-106 of _named_entity.py_ are changed to Unicode (_u'word+nextpos'_, for example), although I don't know if such a fix has other implications. 

I'd much appreciate any suggestions anyone might offer. Thanks!

**Comment by nschneid** [comment]
In Python 2.7, I think the issue is that `format()` is being called with non-ASCII Unicode arguments on a non-Unicode string. Should be `u'{0}+{1}'.format(...)`. (The current code is not a problem for Python 3.)

**Comment by alvations** [comment]
@jgarbers Thank you for catching that!

@nschneid yes, `str.format()` is problematic for unicode in Python2

From https://docs.python.org/2/library/string.html#format-string-syntax , it seems like `format()` is implicitly having the `!s` [argument which should have been optional](https://github.com/python/cpython/blob/2.7/Lib/string.py#L616)

But in any case, `u'{}'.format()` resolves the problem =)

```python
>>> u'电脑'
u'\u7535\u8111'

>>> x = u'电脑'

>>> '{}'.format(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

>>> u'{}'.format(x)
u'\u7535\u8111'
```

**Comment by alvations** [comment]
I think there are 2 solutions to this, we use the `unicode_literals` and support the move to  only maintain Python3 eventually and change everything to unicode for the `ne_chunk` function:

```
from __future__ import unicode_literals
```

Or add the `u'...'` flag to each string in `nltk/chunk/named_entity.py`.

But doing so would have this quirky properly that changes the type of the input into an unicode, even though the format input could have been an ascii `str` type, e.g.

```
>>> x = 'a'
>>> type(x)
<type 'str'>

>>> y = u'{}'.format(x)
>>> type(y)
<type 'unicode'>
```

@stevenbird @nschneid any preference?

**Comment by Ch0ronomato** [comment]
I added a super simple PR for this: https://github.com/nltk/nltk/pull/1906

Any feedback on how to proceed? If this isn't the best fix, let me know and I will address it.

**Comment by gdavoianb** [comment]
@IanSchweer, sorry, but the problem still occurs in Python 2 (I'm using the latest version of `nltk`).
