### ISSUE TITLE
Identifying chemical entities with OSCAR4

### ISSUE THREAD

**Issue by mariehane** [nltk/nltk#1878]
I'm interested in hearing whether this is something you would be interested in adding.

[OSCAR4](https://bitbucket.org/wwmm/oscar4/wiki/Home) is an open source software toolkit for identifying chemical entities in a text. It also includes a tokeniser. 
The accompanying publication is here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3205045.

**Comment by stevenbird** [comment]
Please give the rationale for adding another library to nltk. What does it enable that is not possible otherwise.

**Comment by alvations** [comment]
@stevenbird OSCAR4 and CheBI would have added chemical/medical NLP capabilities to NLTK which is sorely lacking in most NLP tools. E.g. when tokenizing medical names:

```
>>> word_tokenize('2-(14-hydroxypentadecyl)-4-methyl-5-oxo-2,5-dihydrofuran-3-carboxylic acid')
['2-', '(', '14-hydroxypentadecyl', ')', '-4-methyl-5-oxo-2,5-dihydrofuran-3-carboxylic', 'acid']
```

The main corpus from CheBI would have provided a good gazetteer for most NLP task too.

----

@mariehane thank you for your suggestion but would you be interested in writing the API and port the related tools into Python? If so, I think this would be a good extension of NLTK. But do note from the looks of the code, it looks like a task that might take a significant amount of effort to port =(

OSCAR4 is a Java project so it requires some dedicated effort to port the related tools and corpus reader to NLTK, like what we did with Stanford API.

Although I think CheBI ontology (https://www.ebi.ac.uk/chebi/ ) would be a good resource to add but it must come with a compatible Python API to read and link the ontology, like what was done with WordNet. And it may require more complex graphical data structure that `networkx` might provide

Note that the APIs and ports of tools should come with documentation and tests that fits the continuous integration on NLTK too.

**Comment by mariehane** [comment]
@alvations thank you for responding to @stevenbird's question. 

I would be interested in porting it myself since I would use it for my work. Starting with CheBI. 
I'll look into it in a couple of months when I hopefully have some downtime. What I'm most vary of is whether it matches the design/intention of NLTK.

Do you mean something specific by '... that fits the continuous integration on NLTK too'?

**Comment by alvations** [comment]
@mariehane you can do a pull-request whenever the corpus/tokenizer/tools you've written for CheBI and OSCAR4 is ready and there should be at least one reviewer guiding you.

Before the writing anything, please take a look at https://github.com/nltk/nltk/blob/develop/CONTRIBUTING.md and that'll provide you with the details to setup your environment for the contribution as well as setting up the continuous testing environment. 

Looking forward to the contribution ;P

**Comment by svjan5** [comment]
Hi @mariehane,
Do you any update on this? It would be great if you could share something for using OSCAR4 tokenizer in python. 

Thanks
