### ISSUE TITLE
moses.tokenize(sent, escape), same result when escape =True and escape = False (French data)

### ISSUE THREAD

**Issue by jb6** [nltk/nltk#1893]
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import csv
import nltk

from nltk.tokenize.moses import MosesTokenizer

moses = MosesTokenizer(lang='fr')
sent = "Le télétravail n'aura pas d'effet sur ma vie"
print (moses.tokenize(sent, False))

>>>> ['Le', 'télétravail', 'n&apos;', 'aura', 'pas', 'd&apos;', 'effet', 'sur', 'ma', 'vie']

print (moses.tokenize(sent, True))
>>>>>['Le', 'télétravail', 'n&apos;', 'aura', 'pas', 'd&apos;', 'effet', 'sur', 'ma', 'vie']

and I would like to have this result : 
['Le', 'télétravail', 'n' ', 'aura', 'pas', 'd'', 'effet', 'sur', 'ma', 'vie']

(python3)

**Comment by alvations** [comment]
Which version of NLTK are you using? 

```python
>>> import nltk
>>> nltk.__version__
'3.2.5'
>>> from nltk.tokenize.moses import MosesTokenizer
>>> moses = MosesTokenizer(lang='fr')
>>> sent = "Le télétravail n'aura pas d'effet sur ma vie"
>>> print (moses.tokenize(sent, escape=False))
['Le', 'télétravail', "n'", 'aura', 'pas', "d'", 'effet', 'sur', 'ma', 'vie']
>>> print (moses.tokenize(sent, escape=True))
['Le', 'télétravail', 'n&apos;', 'aura', 'pas', 'd&apos;', 'effet', 'sur', 'ma', 'vie']
```

`escape` is the last argument in the `tokenize()` function. When you don't use explicit keyword arguments, i.e. `moses.tokenize(sent, True)`, the True there is setting the second argument to True, i.e. `agressive_dash_splits=True` instead of `escape=True`

See https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L332

```
    def tokenize(self, text, agressive_dash_splits=False, return_str=False, escape=True):
        """
        Python port of the Moses tokenizer.
        """
```

**Comment by jb6** [comment]
You were right @alvations  thanks ! Since I am using python through conda, I thought the nltk package was updated, but it was its 3.2.4 version. Now it works using nltk 3.2.5 and python2.7 👍 output [u'Le', u't\xe9l\xe9travail', u"n'", u'aura', u'pas', u"d'", u'effet', u'sur', u'ma', u'vie'] and with a print I get the tokens I wanted:  
Le
télétravail
n'
aura
pas
d'
effet
sur
ma
vie
For the French stopwords I opened an issue, but no reply yet (n'/d' etc. should also be perceived as stop words, not just letters d/n etc).https://github.com/tilwing/StopWords/issues/1

**Comment by stevenbird** [comment]
Thanks @alvations
