### ISSUE TITLE
POS tagger for tamil language

### ISSUE THREAD

**Issue by abuvanth** [nltk/nltk#1894]

**Comment by alvations** [comment]
@abuvanth Thanks for raising an issue. Just like to clarify and ask what is the issue about =)

- Is this a feature request?
- Are you going to contribute a Tamil POS tagger model to NLTK?

If it's the latter, please take a look at https://github.com/nltk/nltk/blob/develop/CONTRIBUTING.md

Please do a pull request once it's ready and someone will review and take a look at it =)
