### ISSUE TITLE
Object Score in Sentiment Score Calculation???

### ISSUE THREAD

**Issue by kmr0877** [nltk/nltk#1897]
I tried calculating the pos_score(),neg_score() and obj_score() for each word in a sentence.Now my question is to estimate the sentiment score of the sentence do we just consider pos and neg values of all values and based on the avg value we then conclude whether a sentence is positive or negative else should we consider the object value as well???
I couldn't find much resources online to conclude the answer.It would be of great help if someone can help me with this.
Thanks in advance
Cheers

**Comment by alvations** [comment]
@kmr0877 There are some resources on what NLTK provides with regards to sentiment analysis and resources, please see:

 - http://www.nltk.org/howto/twitter.html
 - https://github.com/nltk/nltk/blob/develop/nltk/tokenize/casual.py#L268
 - http://www.nltk.org/howto/sentiment.html
 - http://www.nltk.org/howto/sentiwordnet.html
 - http://www.nltk.org/howto/corpus.html (`opinion_lexicon` section)

Hope it helps.

**Comment by kmr0877** [comment]
yeah i just wanted to check if someone passed with my problem before... appreciate your effort mate!!!
cheers
