### ISSUE TITLE
BllipParser: AttributeError: 'str' object has no attribute 'decode' on Python 3.5

### ISSUE THREAD

**Issue by acattle** [nltk/nltk#1920]
When calling next(BllipParser.parse()) on Python 3.5, I receive the following error:

File "/home/andrew/.local/lib/python3.5/site-packages/nltk/parse/bllip.py", line 169, in parse
    _ensure_ascii(sentence)
  File "/home/andrew/.local/lib/python3.5/site-packages/nltk/parse/bllip.py", line 101, in _ensure_ascii
    word.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'

Related to https://github.com/nltk/nltk/issues/507

NLTK v3.2.5
Python v3.5.2
OS: Ubuntu (16.04.3) running on WSL (16299.125)

**Comment by EgorNemchinov** [comment]
Hey!
There are indeed differences since in Python 3 strings are no longer bytes arrays.
This problem might be solved by changing decode() to encode(), since they both check whether it's an _ascii_ string.

May I solve this?

**Comment by interrogator** [comment]
So nobody ever solved this? Currently I have to wrap words in a dummy class with a decode method that does nothing. I'd love to remove that from my code.

**Comment by interrogator** [comment]
Here is the traceback, happens when I use Bllip's `parse_one`:

```python
~/venv/3.7/lib/python3.7/site-packages/nltk-3.4.4-py3.7.egg/nltk/parse/api.py in parse_one(self, sent, *args, **kwargs)
     70     def parse_one(self, sent, *args, **kwargs):
     71         """:rtype: Tree or None"""
---> 72         return next(self.parse(sent, *args, **kwargs), None)

~/venv/3.7/lib/python3.7/site-packages/nltk-3.4.4-py3.7.egg/nltk/parse/bllip.py in parse(self, sentence)
    182         :rtype: iter(Tree)
    183         """
--> 184         _ensure_ascii(sentence)
    185         nbest_list = self.rrp.parse(sentence)
    186         for scored_parse in nbest_list:

~/venv/3.7/lib/python3.7/site-packages/nltk-3.4.4-py3.7.egg/nltk/parse/bllip.py in _ensure_ascii(words)
    103     try:
    104         for i, word in enumerate(words):
--> 105             word.decode('ascii')
    106     except UnicodeDecodeError:
    107         raise ValueError(

AttributeError: 'str' object has no attribute 'decode'

```
