### ISSUE TITLE
Windows installation problem

### ISSUE THREAD

**Issue by liujinliang01** [nltk/nltk#1923]
I have been stuck at the installation stage. Could anybody help please?
The error message I get is "Python version -32 required which was not found in the registry." 

When I run the register.py script, I get a "file not found" error. No clue which file it is looking for.
And besides, I wonder what NLTK is looking for in the registry?  

My environment is Win7, Python 3.5.0, and NLTK 3.2.5. Installpath and Python path in in the "environment variables" and Python can be directly invoked at any directory.

**Comment by chrishna1** [comment]
Give a try to conda. Didn't you find anything helpful on googling your error?

**Comment by alvations** [comment]
@chrishna1 please check if this helps: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9

**Comment by liujinliang01** [comment]
Thank you very much for your kind reply, and Merry Christmas and Happy New Year to you!
But the link you sent me is broken. Any other options? Thank you again.
love
Jim





At 2017-12-27 16:36:30, "alvations" <notifications@github.com> wrote:


@chrishna1 please check if this helps: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9

**Comment by alvations** [comment]
@liujinliang01 please check the link again, it's working: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9

There's also a short version on just NLTK installation for windows users on: https://www.kaggle.com/alvations/getting-nltk-installed-for-windows-users

See also: https://docs.anaconda.com/anaconda/install/windows

Hope the links help.

**Comment by liujinliang01** [comment]
Thank you very much for your kind help. But the first link is still broken to me in China. The 2nd link opens, but I cannot find a solution to my problem. The 3rd link opens but is not helpful. I have tried Conda, and Anaconda. No luck.
My problem is still "Python verion -32 is required which is not found in the registry". 
My environment is "nltk-3.2.5.win32.exe", Win 10 Family, Python 3.5.0. 
 
Thank you very much again.
Love
Jim

**Comment by alvations** [comment]
Maybe you're behind a firewall that disable pip install? If you're installing it in a company or institution/university. Please contact your administrator to check whether you're behind some firewall. 

The installer for Windows is unreliable. Installing it using powershell with `pip` is the preferred method.

Could you install other libraries using `pip`? E.g. `pip install tensorflow`
Or using conda after installing anaconda? `conda install sklearn`

**Comment by liujinliang01** [comment]
Thank you very much for your quick response. 
I cannot believe that I succeeded, just on the verge of giving up, with the help of  an instruction written by a Chinese postgraduate who is working an NLP project. He fumbled for quite some time and succeeded. The trick is just to use pip to install NLTK. 
I just hope that the good guys behind Python and NLTK make it more user friendly for Windows users. 
Thank you again. 


love
Jim






At 2018-01-03 13:00:59, "alvations" <notifications@github.com> wrote:


Maybe you're behind a firewall that disable pip install?

Could you install other libraries using pip? E.g. pip install tensorflow

Or using conda after installing anaconda? conda install sklearn

**Comment by liujinliang01** [comment]
As a token of my gratitude to kind people like chrishna1 and alvations who took the trouble to respond to my request even during the Christmas and New Year holiday period, I must publish the solution to my problem which maybe helpful to others:

1. install Python 3.5.0, which is supported by the latest NLTK 3.2.5. I downgraded from Python 3.6.4 to 3.5.0 to comply with the NLTK requirement.
2. set "path" in the Windows environment variables. Then you should be able to execute python.exe under any directory in the command prompt.
3. download the tar.gz pip file from https://pypi.python.org/pypi/pip, and unzip the downloaded file.
4. at the command prompt, cd into the dir where the unzipped pip file is, and run "python setup.py install". Then set the path variable for pip in the Windows environment variables.Then you should be able to execute pip.exe under any directory in the command prompt. 
5. Launch the IDLE, and run "import nltk", and then "nltk.download()"
6. In th NLTK downloader window, choose "book / Everything used in the NLTK book", and then click the "download" button near the bottom left. Voila!

**Comment by hilaloytun** [comment]
Hi @liujinliang01 
thank you very much for your post; I followed the steps, but it didn't work for me... Do you think should I remove Python first (now I'm using 3.6.4 version) and download Python 3.6.4 again?

**Comment by alvations** [comment]
The instructions on https://gist.github.com/alvations/0ed8641d7d2e1941b9f9 should work if you **don't** use the . exe file.

**Comment by liujinliang01** [comment]
HI, I have forgotten what I did then. It was a very frustrating experience and I was on the verge of giving up. That is all I remember. I don't want to go back and re-live that experience.
Even now, I have still not succeeded in getting matplotlib up and running though my Python is working. 
Python is a poweful language with the many libraries. But I really don't like this kind of bitter sweet experience and I sincerely hope that the Python community will do something to address this high threshhold.




At 2018-03-16 06:10:51, "hilaloytun" <notifications@github.com> wrote:


Hi @liujinliang01
thank you very much for your post; I followed the steps, but it didn't work for me... Do you think should I remove Python first and download 3.6.4?

**Comment by hilaloytun** [comment]
Hi, thanks for the comment. 
Actually it appeared that it was my fault, because I had there different versions of Python, and I had to import nltk to 3.6.4, but I was using 3.2.5 all the time.

But maybe I can add here a method that really helped me. in cmd
py -3 -m pip install nltk
and then I could see If it installed nltk...
