### ISSUE TITLE
nist.py regexp breaks in py27

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1926]
Our CI server [reports](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/TOXENV=py27-jenkins,jdk=jdk8latestOnlineInstall/testReport/nose.failure/Failure/runTest/) error `nothing to repeat` on line https://github.com/nltk/nltk/blob/develop/nltk/tokenize/nist.py#L110

@alvations: would you mind having a look at this please?

**Comment by alvations** [comment]
Hmmm... It's a little strange that the error doesn't happen locally:

```python
>>> import re
>>> from nltk.corpus import perluniprops
>>> from six import text_type
>>> pup_symbol = text_type(''.join(set(perluniprops.chars('Symbol')))) 
>>> symbol_regex = re.sub(r'[]^\\-]', r'\\\g<0>', pup_symbol)
>>> re.compile(u"({s})".format(s=symbol_regex))
<_sre.SRE_Pattern object at 0x35d9930>
```

Let me take a closer look.

**Comment by alvations** [comment]
Looks like there's a `[]` missing in the compiled regex but it still doesn't throw the error. 

```python
>>> sent = 'this is a foo' + pup_symbol[1] +'sentence.'
>>> patt =  re.compile(u"({s})".format(s=symbol_regex))
>>> patt.sub(' \\1 ', sent)
u'this is a foo\u2604sentence.'
>>> patt =  re.compile(u"([{s}])".format(s=symbol_regex))
>>> patt.sub(' \\1 ', sent)
u'this is a foo \u2604 sentence.'

```

**Comment by alvations** [comment]
Argh, github.com is doing strange thing with bad wifi... Reverting the latest https://github.com/nltk/nltk/commit/052cc88295d122834b7a21e1c73fdceb23130d8f and doing a fresh PR.
