### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by boralprophecy** [nltk/nltk#1943]
```
import nltk

train_sents = [('', "The/at Fulton/np-tl County/nn-tl Grand/jj-tl Jury/nn-tl said/vbd Friday/nr an/at investigation/nn of/in Atlanta's/np$ recent/jj primary/nn election/nn produced/vbd ``/`` no/at evidence/nn ''/'' that/cs any/dti irregularities/nns took/vbd place/nn ./.")]

unigram_tagger = nltk.UnigramTagger(train_sents)

```
While running this code, got the following error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\MachineSense\Anaconda3\lib\site-packages\nltk\tag\sequential.py", line 345, in __init__
    backoff, cutoff, verbose)
  File "C:\Users\MachineSense\Anaconda3\lib\site-packages\nltk\tag\sequential.py", line 292, in __init__
    self._train(train, cutoff, verbose)
  File "C:\Users\MachineSense\Anaconda3\lib\site-packages\nltk\tag\sequential.py", line 181, in _train
    tokens, tags = zip(*sentence)
ValueError: not enough values to unpack (expected 2, got 1)
```

Using Windows 10, Python 3.6.2

**Comment by sks4903440** [comment]
@boralprophecy UnigramTagger takes a list of tagged sentences of type list(list(tuple(str, str))) as its first argument. You are giving train_sents of type list(tuple(str,str)).

**Comment by boralprophecy** [comment]
Yes you are right. Thank you.

**Comment by dolyha** [comment]
![image](https://user-images.githubusercontent.com/26044805/39769228-d111bf7e-5315-11e8-9e2e-a7a99ae64e6e.png)


![image](https://user-images.githubusercontent.com/26044805/39769260-de2ab3be-5315-11e8-96b8-d84758b80e03.png)

**Comment by Diriba01** [comment]
When running on anaconda python 3.7.4 with spyder 4.0, opencv 4.2.0 on window the error occurred says ValueError: not enough values to unpack (expected 2, got 1). Please help me how to solve. The problem is on line:  sequence_type, sequence_name = video_path.split(".avi")[0].split("/")[-2:]

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset_path", type=str, default="UCF-101", help="Path to UCF-101 dataset")
    opt = parser.parse_args()
    print(opt)

    time_left = 0
    video_paths = glob.glob(os.path.join(opt.dataset_path, "*", "*.avi"))
    for i, video_path in enumerate(video_paths):
        sequence_type, sequence_name = video_path.split(".avi")[0].split("/")[-2:]
        sequence_path = os.path.join(f"{opt.dataset_path}-frames", sequence_type, sequence_name)

        if os.path.exists(sequence_path):
            continue

        os.makedirs(sequence_path, exist_ok=True)

        # Extract frames
        for j, frame in enumerate(
            tqdm.tqdm(
                extract_frames(video_path, time_left),
                desc=f"[{i}/{len(video_paths)}] {sequence_name} : ETA {time_left}",
            )
        ):
            frame.save(os.path.join(sequence_path, f"{j}.jpg"))

**Comment by Tchouanga12** [comment]
help with this error please
  File "main.py", line 245, in <module>
    main()
  File "main.py", line 241, in main
    infer_on_stream(args, client)
  File "main.py", line 122, in infer_on_stream
    n, c, h, w = infer_network.load_model(args.model, args.device, 2, 1, cur_request_id, args.cpu_extension)
ValueError: not enough values to unpack (expected 4, got 2)
