### ISSUE TITLE
present is spelled wrong - causes issue at least on line 535

### ISSUE THREAD

**Issue by lukedorney** [nltk/nltk#1946]
https://github.com/nltk/nltk/blob/2d925b8816842630f40dc2ca562131ef1161bfc2/nltk/stem/snowball.py#L406

**Comment by alvations** [comment]
Thanks @lukedorney for catching this!

@LBenzahia it looks like that code is introduced in https://github.com/nltk/nltk/commit/ca00be97c8c88dac726e8ae6c16d601f89fd6db8#diff-5b448b9df2c61fb49cef650029974907 . 

Could you take a look at it? Thank you in advance!

**Comment by somnathrakshit** [comment]
Opened a PR at #1950.
