### ISSUE TITLE
Tweet Tokenizer - preserve_case does not lowercase always 

### ISSUE THREAD

**Issue by gkaramanolakis** [nltk/nltk#1952]
When the preserve_case argument of TweetTokenizer is set to True we should expect that it lowercases examples like 'Ok' or 'A' but it doesn't.

**Comment by alvations** [comment]
[`preserve_case`](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/casual.py#L291) is supposed to keep the original capitalization of the input if it already there. By default, it's set to True. E.g. 

```python
>>> from nltk.tokenize.casual import TweetTokenizer
>>> tt = TweetTokenizer()
>>> tt.tokenize("OK, I've to go")
['OK', ',', "I've", 'to', 'go']
>>> tt.tokenize("A, I've to go")
['A', ',', "I've", 'to', 'go']
>>> tt.tokenize("A, I've to go A")
['A', ',', "I've", 'to', 'go', 'A']
```

If it's set to False, it will start lowercasing everything except for emoticons, see https://github.com/nltk/nltk/blob/develop/nltk/tokenize/casual.py#L308. E.g. :

```
>>> from nltk.tokenize.casual import TweetTokenizer
>>> tt = TweetTokenizer()
>>> tt.tokenize("OK, I've to go")
['OK', ',', "I've", 'to', 'go']
>>> tt.tokenize("A, I've to go")
['A', ',', "I've", 'to', 'go']
>>> tt.tokenize("A, I've to go A")
['A', ',', "I've", 'to', 'go', 'A']
>>> tt = TweetTokenizer(preserve_case=False)
>>> tt.tokenize("A, I've to go A")
['a', ',', "i've", 'to', 'go', 'a']
>>> tt.tokenize("A, I've to go OK")
['a', ',', "i've", 'to', 'go', 'ok']
```

To get lowercase, use `preserve_case=False`.
