### ISSUE TITLE
NLTK installation error

### ISSUE THREAD

**Issue by swanstro** [nltk/nltk#1959]
I am trying to install nltk on my work computer. I have admin access, but I keep getting the following error. Clearly I am doing something wrong or there is a permission issue I need to resolve, but I am not sure what. I would be grateful for any tips/advice.
<img width="698" alt="nltk_error" src="https://user-images.githubusercontent.com/26263982/36337597-02c3c7a0-1357-11e8-962f-d0fc3d8e40f4.png">

**Comment by alvations** [comment]
On Mac OSX, try these instruction.

## First install `pip`

either through:

```
sudo easy_install pip
```

Or using homebrew: 

```
brew install python
```

(See https://stackoverflow.com/q/17271319/610569)


## [Optionally] Install and create virtual environment

See http://docs.python-guide.org/en/latest/dev/virtualenvs/


## Install for user. 

```
pip install --user nltk 
```

**Comment by alvations** [comment]
@swanstro did the installation above helped you to install `nltk` successfully?

**Comment by swanstro** [comment]
Thank you so much for this tip, @alvations --I will be at my office computer tomorrow and will try it!

**Comment by swanstro** [comment]
@alvations -- it worked!  many thanks for your help.  I didn't need to create a virtual environment--the

 pip install --user nltk

worked perfectly.
