### ISSUE TITLE
Improve word tokenizer on balanced opening double quotes

### ISSUE THREAD

**Issue by PanderMusubi** [nltk/nltk#1969]
The following example:

    #!/usr/bin/env python3
    import nltk
    text = 'He said: "No!" He said: "No!" and walked away.\nHe said: “No!” and walked away.\n\nHe asked: "Really?" He asked: "Really?" and walked away.\nHe asked: „Really?” and walked away. He asked: „Really?” and walked away.'
    paragraphs = nltk.LineTokenizer().tokenize(text)
    for paragraph in paragraphs:
        sentences = nltk.tokenize.sent_tokenize(paragraph)
        for sentence in sentences:
            for word in nltk.tokenize.word_tokenize(sentence):
                print(word)

has output:

    He
    said
    :
    ``
    No
    !
    ''
    He
    said
    :
    ``
    No
    !
    ''
    and
    walked
    away
    .
    He
    said
    :
    “
    No
    !
    ”
    and
    walked
    away
    .
    He
    asked
    :
    ``
    Really
    ?
    ''
    He
    asked
    :
    ``
    Really
    ?
    ''
    and
    walked
    away
    .
    He
    asked
    :
    „Really
    ?
    ”
    and
    walked
    away
    .
    He
    asked
    :
    „Really
    ?
    ”
    and
    walked
    away
    .

should split two times `„Really` into `„` and `Really`.

(The current version of nltk has already fixed the issue with “No from https://github.com/nltk/nltk/issues/494 )

**Comment by alvations** [comment]
@PanderMusubi yes, the `“` has been patched together with the chevron fix at https://github.com/nltk/nltk/blob/develop/nltk/tokenize/__init__.py#L105

Adding the lower double quotes there should achieve the same, e.g. from #1974

```python
>>> from nltk import word_tokenize
>>> text = 'He asked: „Really?” and walked away. He asked: „Really?” and walked away.'
>>> word_tokenize(text)
['He', 'asked', ':', '„', 'Really', '?', '”', 'and', 'walked', 'away', '.', 'He', 'asked', ':', '„', 'Really', '?', '”', 'and', 'walked', 'away', '.']
```

Just like to double check the `„` is only a starting quote, right? Would it ever be used as a closing quote?

**Comment by alvations** [comment]
For the double quotes, I think it's clear that we should pad with spaces. #1974 should have patched this. @PanderMusubi would this issue be resolved?

**Comment by PanderMusubi** [comment]
Sorry for the late reply. Confirmed that it works. Thanks very much for fixing this.
