### ISSUE TITLE
Trivial typos in book

### ISSUE THREAD

**Issue by ekembi** [nltk/nltk#1972]
All these mistakes are in the book located at the URL: http://www.nltk.org/book/ and the pages under it.

Typo in Preface:
In ch00.html, "the remaining time of time to" should be "the remaining amount of time"

   Chapter 3:
replacet

   Chapter 4:
"ph.d..n.01" should be "ph.d.n.01", because paragraph says it has four periods, not five.

Strange end of paragraph: ".. doctest-ignore:" 

Chapter 5:  
"a feature of Brown tabs", shouldn't "tabs" be "tags".
", basestring), " extra trailing comma in code example in chapter 4? I'm not sure if this is a mistake, I might just not understand the comma at the end.

    Section 2.8:
"use" should be "to use" in "probably more instructive use the tagged_words". (2.8 , in http://www.nltk.org/book/ch05.html)

    Section 4.1:
Shouldn't they escape the dot in the regular expression "(r'^-?[0-9]+(.[0-9]+)?$', 'CD'),  # cardinal numbers" The regular expression seems to general, it will match 3d3, 3Z3 not just the usual 3.3.

In "(Note that 1 describes a way partially automate such work.)"  "partially automate" should be "to partially automate".

**Comment by alvations** [comment]
@ekembi Thanks for raising this issues! They should be reported to https://github.com/nltk/nltk_book =)

**Comment by ekembi** [comment]
https://github.com/nltk/nltk_book/issues/210
I finished reporting it on the nltk_book page, just now.
