### ISSUE TITLE
missing bibliography info

### ISSUE THREAD

**Issue by ekembi** [nltk/nltk#1973]
Missing bibliography:
http://www.nltk.org/book/bibliography.html
The page is empty except for a heading saying "Bibliography".

**Comment by alvations** [comment]
@ekembi Thanks for raising this issues! They should be reported to https://github.com/nltk/nltk_book =)

**Comment by ekembi** [comment]
https://github.com/nltk/nltk_book/issues/209

I finished reporting it ot the nltk_book page, just now.

**Comment by ekembi** [comment]
It is already reported in nltk_book. I am closing this issue (because it is a duplicate).
