### ISSUE TITLE
span_tokenize rtype should be standardized

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1980]
Currently, there are different Tokenizer classes having the `span_tokenize()` function that returns a mix of generator/list outputs:

| Tokenizer | rtype |
|:-|:-|
|[CharTokenizer](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/simple.py#L68)| generator|
|[LineTokenizer](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/simple.py#L123)| generator|
|[StringTokenizer](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/api.py#L75) | generator|
|[RegexpTokenizer](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/regexp.py#L133) | generator |
|[PunktSentenceTokenizer](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/punkt.py#L1273)|  list | 
|[TreebankWordTokenizer](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/treebank.py#L147)| list |

`span_tokenize` rtype should be standardized, either all list or all generator. Related tests should be standardized too. 

Question raised comes from https://stackoverflow.com/questions/49290827/span-tokenize-gives-generator-object-as-output

**Comment by pulkitmaloo** [comment]
Can I work on this?

**Comment by pulkitmaloo** [comment]
Please review PR #1983 
I have converted all rtypes to generator and updated unit test cases for TreebankWordTokenizer

**Comment by alvations** [comment]
Thanks @pulkitmaloo for the PR! I've reviewed it and it looks good. 

We'll just let leave PR up for a while and see whether there's any strong objections on returning generators instead of list.

**Comment by pulkitmaloo** [comment]
Also, I didn't find any unit tests for Tokenizer classes except for TreebankWordTokenizer, should I work on it?

**Comment by alvations** [comment]
Sure! If you would like to write some tests for the other Tokenizer classes, that'll be great! 

But usually, people only use `RegexpTokenizer`,  `PunktSentenceTokenizer` and `TreebankWordTokenizer`.

**Comment by tomaarsen** [comment]
This has been solved in #1983. I've not seen any objections for using generators. Closing now.
