### ISSUE TITLE
Wrong BLEU scores?

### ISSUE THREAD

**Issue by nabihach** [nltk/nltk#1984]
I see strange (and possibly wrong) behaviour of the BLEU implementation in NLTK version 3.2.5 (I am using Ubuntu 16.04, Python 3.5.2). Here are my logs:
```
>>> from nltk.translate.bleu_score import sentence_bleu
>>> sentence_bleu([['a', 'b', 'c', 'd']], ['aa', 'bb', 'cc', 'd'], weights=(0,1))
1.0
>>> sentence_bleu([['how', 'are', 'you', 'x']], ['aaa', 'bbb', 'ccc', 'x'], weights=(0,1))
1.0
>>> sentence_bleu([['how', 'are', 'you', '??']], ['aaa', 'bbb', 'ccc', '??'], weights=(0,1))
1.0
```
Can someone help me understand what's going on here?
Thanks.

EDIT:
Testing with cumulative BLEU scores also yields unexpected results:
```
>>> sentence_bleu([['how', 'are', 'you', '??']], ['aaa', 'bbb', 'ccc', '??'], weights=(0.5,0.5))
0.5
```
It seems that there are bugs when using n-th order BLEU scores with no n-gram overlaps.

**Comment by alvations** [comment]
Please see https://github.com/nltk/nltk/pull/1844#issue-144280278
