### ISSUE TITLE
Zipfile as corpus raises exception unless subdirectory is appended to filename

### ISSUE THREAD

**Issue by meldavis** [nltk/nltk#1986]
Unable to use a zipfile as a corpus unless a subdirectory is appended to the zipfile name.  A root name like 'twitter_samples.zip' will raise an exception.  But 'twitter_samples.zip/twitter_samples/' will work.

Using python 3.6.4, NLTK 3.2.5, Windows.

#### Fails with exception
```
from nltk.corpus.reader import TwitterCorpusReader
TwitterCorpusReader(root='twitter_samples.zip', fileids="twitter_samples/negative_tweets.json")
```
#### This works
```
TwitterCorpusReader(root='twitter_samples.zip/twitter_samples/', fileids="negative_tweets.json")
```

## Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Apps\Tools\python\conda3\envs\nlp\lib\site-packages\nltk\corpus\reader\twitter.py", line 74, in __init__
    CorpusReader.__init__(self, root, fileids, encoding)
  File "C:\Apps\Tools\python\conda3\envs\nlp\lib\site-packages\nltk\corpus\reader\api.py", line 82, in __init__
    root = ZipFilePathPointer(zipfile, zipentry)
  File "C:\Apps\Tools\python\conda3\envs\nlp\lib\site-packages\nltk\compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Apps\Tools\python\conda3\envs\nlp\lib\site-packages\nltk\data.py", line 506, in __init__
    (zipfile.filename, entry))
OSError: Zipfile 'C:\\Projects\\mfd\\nlp\\twitter_samples.zip' does not contain '.'
```

**Comment by fanjin-z** [comment]
@meldavis @alvations I think the problem lies in here:
https://github.com/nltk/nltk/blob/a8446adace93893332d42ff0f564343748b7f83c/nltk/data.py#L491

If entry is empty(which it is in our case), it add a dot to entry, causing unintended error later. Here is an error showcase:
```
import os
import sys
entry = ''
entry = normalize_resource_name(entry, True, '/').lstrip('/')
entry
```
out
```
'.'
```

A simple fix could be changing this line:
https://github.com/nltk/nltk/blob/a8446adace93893332d42ff0f564343748b7f83c/nltk/data.py#L494
to
```
if entry != '.'
```

Shall I create a PR to fix it?

**Comment by meldavis** [comment]
This is still broken.   The fix did remove the exception; however, now the corpus fails to return any data.  

## Example using Twitter Corpus
### Appending a subdirectory to the zip filename
``` python
from nltk.corpus.reader import TwitterCorpusReader
c = TwitterCorpusReader(root='twitter_samples.zip/twitter_samples/', fileids="negative_tweets.json")
print(c.abspaths())
print(c.fileids())
```
This correctly reports
 ```
[ZipFilePathPointer('D:\\Projects\\corpus\\twitter_samples.zip', 'twitter_samples/negative_tweets.json')]
['negative_tweets.json']
```

### Using a zipfile as a corpus root produces no data
```
c = TwitterCorpusReader(root='twitter_samples.zip', fileids="twitter_samples/negative_tweets.json")
print(c.abspaths())
print(c.fileids())
```
This incorrectly reports an empty set: 
```
[]
[]
```
