### ISSUE TITLE
How to run Stanford postagger to listen to port 9000 so we can use it from NLTK?

### ISSUE THREAD

**Issue by ndvbd** [nltk/nltk#1989]
How to run Stanford postagger to listen to port 9000 so we can use it from NLTK, without running the Java jar each time (and leave the loaded model in memory, to save time)

**Comment by dimazest** [comment]
If I understand you correctly, you need to start CoreNLP server. Refer to https://stanfordnlp.github.io/CoreNLP/cmdline.html

Once the server is running, you can tag sequnces https://github.com/nltk/nltk/blob/develop/nltk/parse/corenlp.py#L363

**Comment by dimazest** [comment]
Also, consider using https://github.com/stanfordnlp/python-stanford-corenlp

**Comment by ndvbd** [comment]
@dimazest,
Thanks. This is the page that I was looking for:  https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

**Comment by dimazest** [comment]
yeah, i meant to link to the corenlp-server page, my mistake
