### ISSUE TITLE
Using CoreNLPPOSTagger.tag returns list of tuples in a different size than the input

### ISSUE THREAD

**Issue by ndvbd** [nltk/nltk#1990]
Using CoreNLPPOSTagger.tag returns list of tuples in a different size than the input

This happens for example when the input contain some *space* elements: ' '

The tagger simply ignores the spaces and don't return then. This creates difficulties in correlating the output to the input...

**Comment by alvations** [comment]
Could you provide an example input, the core NLP output and your expected output?

**Comment by ndvbd** [comment]
The input to the CoreNLPPOSTagger.tag is:` ['The', ' ', 'boy', ' ', 'walks', ' ', 'well', '.']`

The output is:` [(u'The', u'DT'), (u'boy', u'NN'), (u'walks', u'VBZ'), (u'well', u'RB'), (u'.', u'.')]`

So the length of the input differs from the length of the output. The spaces tokens are ignored. I think it's better programming to keep the lengths the same, because it allows easier correlation between an input element to output element.

**Comment by dimazest** [comment]
I would suggest to look into CoreNLP documentation and try to get desired behavior directly, without using NLTK's interface.

**Comment by alvations** [comment]
@nadavb  Please try the following with NLTK v3.3. 

Please use the new `CoreNLPParser` interface.

First update your NLTK:

```
pip3 install -U nltk
```

Then still in terminal:

```
wget http://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip
unzip stanford-corenlp-full-2018-02-27.zip
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -preload tokenize,ssplit,pos,lemma,ner,parse,depparse -status_port 9000 -port 9000 -timeout 15000 &

python3
```

Finally, start Python:

```python3
>>> from nltk.parse import CoreNLPParser
>>> parser = CoreNLPParser(url='http://localhost:9000')
>>> list(parser.parse(['house', ')', 'is', 'in', 'York', 'Avenue']))
[Tree('ROOT', [Tree('S', [Tree('NP', [Tree('NN', ['house']), Tree('-RRB-', ['-RRB-'])]), Tree('VP', [Tree('VBZ', ['is']), Tree('PP', [Tree('IN', ['in']), Tree('NP', [Tree('NNP', ['York']), Tree('NNP', ['Avenue'])])])])])])]

>>> tagger = CoreNLPParser(url='http://localhost:9000', tagtype='ner')
>>> tokens = 'Rami Eid is studying at Stony Brook University in NY'.split()
>>> tagger.tag(tokens)
[('Rami', 'PERSON'), ('Eid', 'PERSON'), ('is', 'O'), ('studying', 'O'), ('at', 'O'), ('Stony', 'ORGANIZATION'), ('Brook', 'ORGANIZATION'), ('University', 'ORGANIZATION'), ('in', 'O'), ('NY', 'STATE_OR_PROVINCE')]

>>> from nltk.parse import CoreNLPParser
>>> tagger = CoreNLPParser(url='http://localhost:9000', tagtype='pos')
>>> text = 'The boy walks well . '.split()
>>> tagger.tag(text)
[('The', 'DT'), ('boy', 'NN'), ('walks', 'VBZ'), ('well', 'RB'), ('.', '.')]
```

**Comment by alvations** [comment]
Closing the issue as resolved for now =)
Please open if there's further issues.
