### ISSUE TITLE
Why nltk uses "CoreNLPTokenizer(url='http://localhost:9000').tokenize(s) == expected

### ISSUE THREAD

**Issue by bayou3** [nltk/nltk#1991]
Why it uses url='http://localhost:9000', what does it has any matter with Tokenizer??
It always raises errors when I run it. This code is from /python3.6/site-packages/nltk/tokenize/stanford.py. 
What I want to do is to tokenize a normal Engltish sentence. I follow the codes of "stanford.py", but it always always pops up errors. How to fix it ?

**Comment by dimazest** [comment]
`CoreNLPTokenizer` in NLTK uses CoreNLP via REST API.

Refer to https://stanfordnlp.github.io/CoreNLP/corenlp-server.html for instructions on how to start the server. Once it's running, `CoreNLPTokenizer` will work.

**Comment by alvations** [comment]
Hope the following helps.

In terminal, start the server:

```
wget http://nlp.stanford.edu/software/stanford-corenlp-full-2016-10-31.zip
unzip stanford-corenlp-full-2016-10-31.zip && cd stanford-corenlp-full-2016-10-31
    
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer \
    -preload tokenize,ssplit,pos,lemma,parse,depparse \
    -status_port 9000 -port 9000 -timeout 15000
```

In Python:

```python
>>> from nltk.parse.corenlp import CoreNLPParser
>>> stanford = CoreNLPParser(url='http://localhost:9000')
>>> stanford.tokenize('This is a foo bar sentence.')
<generator object GenericCoreNLPParser.tokenize at 0x11490beb8>
>>> list(stanford.tokenize('This is a foo bar sentence.'))
['This', 'is', 'a', 'foo', 'bar', 'sentence', '.']
```

**Comment by alvations** [comment]
@bayou3 did you get the NLTK's API to Stanford CoreNLP to work with the code in the previous comment?

**Comment by alvations** [comment]
Closing the issue as resolved for now =) 
Please open if there's further issues.
