### ISSUE TITLE
ROUGE Score for NLTK not found

### ISSUE THREAD

**Issue by 53X** [nltk/nltk#1992]
I don't think that there is an inbuilt function in nltk for calculating the ROUGE Score between two different pieces of text. The ROUGE Score has been introduced in this paper :    
                            http://www.aclweb.org/anthology/W04-1013

**Comment by alvations** [comment]
@53X Thanks for the suggestion! Yes, that'll be a sort of easy score to code. If you're up for the challenge, feel free to contribute and create a PR for the ROUGE score =)

Don't worry about breaking the code, there'll be reviews and edits to be made after you've submit a PR before it's merged.

**Comment by 53X** [comment]
@alvations  , I am taking it

**Comment by alvations** [comment]
Looking forward to the contribution =)

**Comment by tamirbennatan** [comment]
Out of curiosity - was this contribution ever made?

**Comment by 53X** [comment]
@tamirbennatan  I am working on it . Will make the PR in 2 - 3 days

**Comment by 53X** [comment]
@alvations , Do i need to code up ROUGE- W score ?  I haven't actually come across any of it's applications . I guess ROUGE - L ,S ,N are the most used ones . Please correct me if I am wrong.

**Comment by alvations** [comment]
Start with any ROUGE score, extending it the others, whether it's W or not should be easy.

**Comment by djokester** [comment]
Is this implemented already or can I work on this?

**Comment by purificant** [comment]
@djokester See https://github.com/nltk/nltk/pull/2045 and https://github.com/nltk/nltk/pull/2074

**Comment by alvations** [comment]
Would be great if anyone wants to poke at the ROUGE scores again =)

**Comment by d-kleine** [comment]
Still no ROUGE score implemented in nltk, both PRs rejected. Is there any chance we could get ROUGE implemented sometime soon?
