### ISSUE TITLE
Weighted Longest Common Subsequence forROUGE metric in nltk.translate

### ISSUE THREAD

**Issue by 53X** [nltk/nltk#1993]
Probably NLTK doesn't have any inbuilt function for finding the Longest Common Subsequence between two pieces of texts .

**Comment by alvations** [comment]
Yes, but native python does =) https://docs.python.org/3/library/difflib.html#difflib.SequenceMatcher.find_longest_match

**Comment by 53X** [comment]
@alvations , the link you provided answers the Longest-Common-substring problem but not the Longest-Common -Subsequence problem. In the **Longest-Common -Subsequence , if we have 2 strings ----  " police killed the gunman" and " police kill the gunman" , then the answer should be " police the gunman**"

**Comment by alvations** [comment]
@53X whoops sorry. Just took a look at the ROGUE paper carefully. 

The O(mn) solution from https://www.geeksforgeeks.org/longest-common-subsequence/ and https://rosettacode.org/wiki/Longest_common_subsequence#Python would help. 

Don't think the substring is needed, but if needed, something like this https://www.geeksforgeeks.org/printing-longest-common-subsequence/ would work.

**Comment by alvations** [comment]
Here's an implementation to unify the weighted and normal LCS function for the ROGUE metric. You can use this as a reference.

```python
def f(k):
    return k**0.5
    
def rogue_lcs(X, Y, weighted=True):
    m, n = len(X), len(Y)
    
    # Initialize the c-table
    c_table = [[0]*(n+1) for i in range(m+1)]
    # Initialize the w-table
    w_table = [[0]*(n+1) for i in range(m+1)]
    
    for i in range(m+1):
        for j in range(n+1):
            if i == 0 or j == 0:
                continue
            # The length of consecutive matches at 
            # position i-1 and j-1
            elif X[i-1] == Y[j-1]:
                # Increment would be +1 for normal LCS
                k = w_table[i-1][j-1]
                increment = f(k+1) - f(k) if weighted else 1
                # Add the increment
                c_table[i][j] = c_table[i-1][j-1] + increment
                w_table[i][j] = k + 1
            else:
                if c_table[i-1][j] > c_table[i][j-1]:
                    c_table[i][j] = c_table[i-1][j]
                    w_table[i][j] = 0 # no match at i,j
                else:
                    c_table[i][j] = c_table[i][j-1]
                    w_table[i][j] = 0 # no match at i,j
    return c_table[m][n]

x  = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
y1 = ['A', 'B', 'C', 'D', 'H', 'I', 'K']
y2 = ['A', 'H', 'B', 'K', 'C', 'I', 'D']

print(rogue_lcs(x, y1, weighted=False))
print(rogue_lcs(x, y2, weighted=False))
print(rogue_lcs(x, y1, weighted=True))
print(rogue_lcs(x, y2, weighted=True))
```

[out]:

```
4
4
2.0
4.0
```

Hope it helps.

**Comment by alvations** [comment]
As for `SKIP2()` function, `nltk` has the `nltk.skipgrams`, e.g. 

```python
from nltk import skipgrams

s1 = 'police killed the gunman'.split()
list(skipgrams(s1, n=2, k=len(s1))) # bigrams with C(4,2) combinations.
```


[out]:

```
[('police', 'killed'),
 ('police', 'the'),
 ('police', 'gunman'),
 ('killed', 'the'),
 ('killed', 'gunman'),
 ('the', 'gunman')]
```

**Comment by alvations** [comment]
@53X Just checking in on the ROGUE implementation. Do you need some help on it?

**Comment by stevenbird** [comment]
@53X ping

**Comment by 53X** [comment]
@alvations  Sorry I was having my exams...... I am almost done with ROUGE though  :)

**Comment by 53X** [comment]
@alvations  please check out this !!!!! .A weighted LCS is needed for the ROUGE-W score instead of a normal LCS.
