### ISSUE TITLE
Please move the default download directory "$HOME/nltk_data" to a less intrusive location

### ISSUE THREAD

**Issue by fanjin-z** [nltk/nltk#1997]
I really don't like the way that nltk assert its default download location to home directory. I have to change the download path and add 'nltk.data.path.append('/less/intrusive/path/')' every time. In my opinion, a software should never take creating a folder in home directory as default option. I think '$HOME/.local/share/nltk_data'  is a better substitute.

There is similar [discussion](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1575053) about these issue in SNAP.

**Comment by alvations** [comment]
@Fnjn I think this issue with snapd and NLTK is a little different. The XDG Base Directory Specification is for user-specific data, e.g. things like logfile, temporary save points, etc. 

But for NLTK, the `nltk_data` directory doesn't contain user specific data (read/write) but resource data (mostly read-only) for NLP purposes. That way, hiding the `nltk_data` under a `$HOME/.*` might not be a good idea esp. when some OS specifically hide these `.*` directories by default and users looking into the data may not find it at first sight.

For an alternative non-intrusive directory, I suggest that users can use `/usr/local/share/nltk_data` , which is by default already added in the list of default path for the `nltk.data` to look, https://github.com/nltk/nltk/blob/develop/nltk/data.py#L87 : 

```
>>> import nltk
>>> nltk.download('stopwords', download_dir='/usr/local/share/')
[nltk_data] Downloading package stopwords to
[nltk_data]     //usr/local/share/somewhere...
[nltk_data]   Unzipping corpora/stopwords.zip.
True
>>> exit()
$ ls /usr/local/share/corpora/
stopwords/     stopwords.zip
```

**Comment by fanjin-z** [comment]
I think `/usr/local/share` is not a good idea either. The ownership and group of `/usr/local/*` is root & root by default, so its hard for users (esp. those using shared servers) to download to this location. 

Another workaround may be supporting `NLTK_DATA_PATH` (contains customized nltk_data path) in a setting py file, so that users don't need to add 'nltk.data.path.append('/customized/nltk/data/path/')' to their scripts every time.

**Comment by alvations** [comment]
As an environmental variable, that's already available in NLTK, see https://github.com/nltk/nltk/blob/develop/nltk/data.py#L88 =)

**Comment by fanjin-z** [comment]
Thanks, this works. I add your solution to a [related stackoverflow question](https://stackoverflow.com/a/49608594/7329044).
