### ISSUE TITLE
Create a new repo for GPL extensions to NLTK

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#2003]
cf #2000, #1781.

**Comment by no-identd** [comment]
Shouldn't this refer to LGPL extensions, and **not** GPL extensions? Also, note that the linking exception in the LGPL mentioned here:

https://github.com/nltk/nltk/issues/2000#issuecomment-380171248

can behave a bit trickier than you might expect at first, especially when it comes to interpreted languages:

https://softwareengineering.stackexchange.com/questions/179084/is-there-a-modified-lgpl-license-that-allows-static-linking

https://opensource.stackexchange.com/questions/1579/when-is-my-project-a-derivative-work-in-an-interpreted-language
