### ISSUE TITLE
Jaro-Winkler Distance in nltk.metrics.distance

### ISSUE THREAD

**Issue by znd4** [nltk/nltk#2006]
Hi, I think it would be awesome to have [Jaro Winkler Distance](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance) implemented in nltk.metrics.distance. I'd love to take a crack at it if there's no one currently working on it. There are a number of projects online implementing this, but NLTK seems like the right larger project that should have this implemented.

**Comment by 53X** [comment]
Working on it currently . I will make the PR soon . :smile:

**Comment by 53X** [comment]
@zdog234 , @alvations  , @stevenbird  I made the PR [here](https://github.com/nltk/nltk/pull/2044)

**Comment by alvations** [comment]
Thanks again @53X for the contribution! Resolved in #2044
