### ISSUE TITLE
module 'nltk' has no attribute 'data'

### ISSUE THREAD

**Issue by gabeorlanski** [nltk/nltk#2012]
Hello. I am getting this error just from importing stopwords:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-12-9cf149ae136d> in <module>()
        1 from collections import Counter
        2 from nltk.tokenize import word_tokenize
    ----> 3 from nltk.corpus import stopwords
        4 search_stemmed = [stemmer.stem(x) for x in ["art","pen","marker"]]
        5 
    
    C:\Anaconda3\lib\site-packages\nltk\__init__.py in <module>()
        135 from nltk.translate import *
        136 from nltk.sem import *
    --> 137 from nltk.stem import *
        138 
        139 # Packages which can be lazily imported
    
    C:\Anaconda3\lib\site-packages\nltk\stem\__init__.py in <module>()
        27 from nltk.stem.isri import ISRIStemmer
        28 from nltk.stem.porter import PorterStemmer
    ---> 29 from nltk.stem.snowball import SnowballStemmer
        30 from nltk.stem.wordnet import WordNetLemmatizer
        31 from nltk.stem.rslp import RSLPStemmer
    
    C:\Anaconda3\lib\site-packages\nltk\stem\snowball.py in <module>()
        30 
        31 from nltk import compat
    ---> 32 from nltk.corpus import stopwords
        33 from nltk.stem import porter
        34 from nltk.stem.util import suffix_replace, prefix_replace
    
    C:\Anaconda3\lib\site-packages\nltk\corpus\__init__.py in <module>()
        64 from nltk.tokenize import RegexpTokenizer
        65 from nltk.corpus.util import LazyCorpusLoader
    ---> 66 from nltk.corpus.reader import *
        67 
        68 abc = LazyCorpusLoader(
    
    C:\Anaconda3\lib\site-packages\nltk\corpus\reader\__init__.py in <module>()
        54 """
        55 
    ---> 56 from nltk.corpus.reader.plaintext import *
        57 from nltk.corpus.reader.util import *
        58 from nltk.corpus.reader.api import *
    
    C:\Anaconda3\lib\site-packages\nltk\corpus\reader\plaintext.py in <module>()
        21 from nltk.corpus.reader.api import *
        22 
    ---> 23 class PlaintextCorpusReader(CorpusReader):
        24     """
        25     Reader for corpora that consist of plaintext documents.  Paragraphs
    
    C:\Anaconda3\lib\site-packages\nltk\corpus\reader\plaintext.py in PlaintextCorpusReader()
        40     def __init__(self, root, fileids,
        41                  word_tokenizer=WordPunctTokenizer(),
    ---> 42                  sent_tokenizer=nltk.data.LazyLoader(
        43                      'tokenizers/punkt/english.pickle'),
        44                  para_block_reader=read_blankline_block,
    
    AttributeError: module 'nltk' has no attribute 'data'

Removing the import of stopwords gets rid of the error. I have tried reinstalling nltk and redownloading all of the stuff but I still get the error.

**Comment by gabeorlanski** [comment]
It took using `nltk,download('all') and restarting the jupyter notebook to fix

**Comment by benileo** [comment]
What is the cause of this issue?

**Comment by sunnynm** [comment]
Had the same issue, make sure you completely restart jupyter for it to take effect. May have to uninstall and reinstall nltk if the above method doesn't work.

**Comment by jinwanseo** [comment]
1. Completely delete the package through pip uninstall nltk.
2. Reinstall the package via pip install -U nltk.
3. Turn off the Jupiter notebook (IDE) completely and run it again.
4. Let's run it again.
5. If it still doesn't work, it's a problem that can occur because the nltk package failed SSL authentication when trying to download the punkt resource, so I reinstall the certificate in the same way as below.

/Applications/Python\ 3.x/Install\ Certificates.command
