### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by navkant** [nltk/nltk#2019]
![screen shot 2018-05-14 at 11 06 53 pm](https://user-images.githubusercontent.com/25250253/40013591-8da3d942-57cb-11e8-88ac-1a09c7052910.png)
Hi guys,

Please help me with this. I do not firewall ON on my system.

**Comment by alvations** [comment]
Are you using a Python 3.6 and Mac OSX? If so, take a look at 

 - https://github.com/nltk/nltk/issues/1425#issuecomment-372016707
 - https://github.com/nltk/nltk/issues/1961#issuecomment-367207040

**Comment by navkant** [comment]
thanks, it worked

**Comment by LemmaEOF** [comment]
I'm on Python 3.7 and Mac OS X, and I'm still having this issue. The pointer is at `_ssl.c:748` instead of `_ssl.c:777` for me. I've done the the Install Certificates.command and no luck.

**Comment by stevenbird** [comment]
Please use Python 3.6.

**Comment by LemmaEOF** [comment]
Thank you!

**Comment by alvations** [comment]
@stevenbird I think it's around time to play catchup with Python on CI again =)

**Comment by stevenbird** [comment]
@alvations yes, you're right...

**Comment by stevenbird** [comment]
See #2072
