### ISSUE TITLE
Potential license incompatibility

### ISSUE THREAD

**Issue by hyandell** [nltk/nltk#2022]
The https://github.com/nltk/nltk/blob/79ef1cfb4c5dcc8543c465aba8b34aa0878e738b/nltk/corpus/reader/sinica_treebank.py file says that it is CC-NC-SA. Looking at Apache's License guidance ( https://www.apache.org/legal/resolved.html ) they flag both CC-NC and CC-SA code as being problematic with the Apache license.  [that page is for Apache projects, but may be of value here]

CC-NC-SA is also on the FSF's not-compatible list: https://www.gnu.org/licenses/license-list.en.html

**Comment by stevenbird** [comment]
The corpus sample is CC-NC-SA. The corpus reader is Apache.

**Comment by hyandell** [comment]
Thank you - my apologies for being confused by the comment; I see what it is saying now.

**Comment by stevenbird** [comment]
Thanks @hyandell - I've edited the text to make this clear.
