### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by abhirupnandy** [nltk/nltk#2030]
I'm facing a 503 error whenever I'm trying to download WordList.
![screenshot from 2018-05-28 13-15-31](https://user-images.githubusercontent.com/39028831/40603425-7708b9d8-6279-11e8-98a2-5a8ca847bbd3.png)
I tried downloading the file from the website. The problem still remains the same.

**Comment by stevenbird** [comment]
This is not a problem with NLTK but with your network connection... this is discussed on the nltk-users mailing list.
