### ISSUE TITLE
METEOR score for MT in nltk not present

### ISSUE THREAD

**Issue by 53X** [nltk/nltk#2041]
Introduction of **METEOR score for MT** could be done in nltk as it is better than most of the available  scoring metrics for MT. This score was introduced in the following paper : 

**https://www.cs.cmu.edu/~alavie/papers/BanerjeeLavie2005-final.pdf**

**Comment by 53X** [comment]
If this issue is good to go , I can make the PR real quick  :)

**Comment by alvations** [comment]
Yes, having METEOR would be good. But do note that it's a little harder than it looks =)

**Comment by 53X** [comment]
No problem , I am taking it  :)

**Comment by alvations** [comment]
Thanks in advance! Try to finish the ROUGE first. I think that's more test-able and maintainable =)

**Comment by 53X** [comment]
Yeah sure :)

**Comment by hecoding** [comment]
Hi! This issue is now 2 months old, so it's like to know the status of the implementation @53X self-assigned 🙂

**Comment by 53X** [comment]
I have already implemented this locally @hecoding.  It is just a matter of time till I make a PR. Actually I have made a PR on another issue. So to reduce reviewer's load I am waiting for my current PR to be merged. Thanks for your concern.

**Comment by hecoding** [comment]
Many thanks for your work! That's great news, we'll be waiting for your implementation.
Have a good day.

**Comment by apeterswu** [comment]
Curious about whether METEOR is released now? Thanks.

**Comment by aman2304** [comment]
Any updates on the METEOR PR?
