### ISSUE TITLE
TER Metric for MT not present 

### ISSUE THREAD

**Issue by 53X** [nltk/nltk#2046]
TER metric for machine translation is not present in nltk. TER Metric has been introduced in [here](https://www.cs.umd.edu/~snover/pub/amta06/ter_amta.pdf)

**Comment by 53X** [comment]
If this issue is good to go then I am taking it

**Comment by alvations** [comment]
BTW, here's a working version https://gist.github.com/alvations/989dacca76c820c48ef18c4637515b39
