### ISSUE TITLE
Following Stanford parser import warning yields an error

### ISSUE THREAD

**Issue by uriva** [nltk/nltk#2048]
If I init the parser using this import:
`from nltk.parse.stanford import StanfordDependencyParser`
I get:

> .local/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: The StanfordParser will be deprecated
> Please use nltk.parse.corenlp.StanforCoreNLPParser instead.

But this import:
`from nltk.parse.corenlp import StanfordCoreNLPParser`

Gives the following error:

> ----> 1 from nltk.parse.corenlp import StanfordCoreNLPParser
> 
> ImportError: cannot import name 'StanfordCoreNLPParser'
> 

version: nltk 3.3

**Comment by stevenbird** [comment]
Thanks for reporting this @uriva
