### ISSUE TITLE
Masi Distance Doc_test Error 

### ISSUE THREAD

**Issue by 53X** [nltk/nltk#2049]
Running the **doctest** on **masi_distance** in *nltk.metrics.distance* gives the doctest error as follows:

    Failed example:
        masi_distance(set([1, 2]), set([1, 2, 3, 4]))
    Expected:
        0.665
    Got:
        0.335

**Comment by 53X** [comment]
`0.665` is most probably the `masi_similarity = 1-masi_distance` between the given sets.

**Comment by 53X** [comment]
@alvations what do u think about this

**Comment by alvations** [comment]
~Yes, from first look, it looks like distance and similarity is mixed up.~ Let me relook at the old Passonneau paper and the implementation after I figure out what went from on CI #2044

**Comment by alvations** [comment]
Looks like the function docstring isn't documented properly too =(
**But the implementation is right. No error here.**

In NLTK:

```python
def masi_distance(label1, label2):
    """Distance metric that takes into account partial agreement when multiple
    labels are assigned.
    >>> from nltk.metrics import masi_distance
    >>> masi_distance(set([1, 2]), set([1, 2, 3, 4]))
    0.665
    Passonneau 2006, Measuring Agreement on Set-Valued Items (MASI)
    for Semantic and Pragmatic Annotation.
    """

    len_intersection = len(label1.intersection(label2))
    len_union = len(label1.union(label2))
    len_label1 = len(label1)
    len_label2 = len(label2)
    if len_label1 == len_label2 and len_label1 == len_intersection:
        m = 1
    elif len_intersection == min(len_label1, len_label2):
        m = 0.67
    elif len_intersection > 0:
        m = 0.33
    else:
        m = 0

    return 1 - len_intersection / len_union * m
```

From the paper, the MASI is a weighted jaccard similarity 

```
masi_similarity = jaccard * monotonicity
```

The original MASI formula is for the similarity, c.f. [Passonneau (2006)](http://www.cs.columbia.edu/nlp/papers/2006/passonneau_06.pdf):

> MASI ranges from 1, when two sets are identical, to 0, when they are disjoint. . It has two terms which weight different aspects of set comparison: MASI = J*M. The Jaccard (1908) metric (the J term) is used to weight the differences in size of two sets, independent of whether sets are monotonic. The M term is for monotonicity, and penalizes a case like Figure 3 more heavily than Figure 2. 

So the masi_distance ` 1 - len_intersection / len_union * m` is right.

BTW, the monotonicity part of the code looks correct too but we can afford to give it better variable names and use more human-readable set function, e.g. :

```python
If set(P) == set(Q):
    montonicity = 1
elif set(P).issubset(set(Q)) or set(Q).issubset(set(P)):
    monotonicity = 0.67
elif set(P).intersection(Q): 
    monotonicity = 0.33
else:
    monotonicity = 0
```

----

Working through the example:

```python
>>> P = set([1,2])
>>> Q = set([1,2,3,4])
>>> P.issubset(Q)
True
>>> M = monotonicity = 0.67  # Since P.issubset(Q)
>>> J = jaccard = len(P.intersection(Q)) / len(P.union(Q))
>>> M * J        # MASI similarity
0.335
>>> 1 - M * J   # MASI distance
0.667
```

**Comment by 53X** [comment]
```
def masi_distance(label1, label2):
    """Distance metric that takes into account partial agreement when multiple
    labels are assigned.
    >>> from nltk.metrics import masi_distance
    >>> masi_distance(set([1, 2]), set([1, 2, 3, 4]))
    0.665
    Passonneau 2006, Measuring Agreement on Set-Valued Items (MASI)
    for Semantic and Pragmatic Annotation.
    """

    len_intersection = len(label1.intersection(label2))
    len_union = len(label1.union(label2))
    len_label1 = len(label1)
    len_label2 = len(label2)
    if len_label1 == len_label2 and len_label1 == len_intersection:
        m = 1
    elif len_intersection == min(len_label1, len_label2):
        m = 0.67
    elif len_intersection > 0:
        m = 0.33
    else:
        m = 0

    return 1 - len_intersection / len_union * m


```
@alvations , I had a look at this code ( which u posted earlier) but didn't understand the purpose of the second **elif** which calculates monotonicity,m. If the first **elif** is true then there is no reason to have the second **elif**. The bottomline being that the second **elif** is never encoutered.  I guess the error lies here.

**Comment by alvations** [comment]
The implementation is right as explained above, closing this issue to clean up the issue tracker. Do feel free to re-open if there's further problems on it =)
