### ISSUE TITLE
nltk.help.upenn_tagset should allow returning strings and not just print them

### ISSUE THREAD

**Issue by ubershmekel** [nltk/nltk#205]
I wanted to write the explanations for parts of speech to a file but I couldn't because the default behavior just prints to the console.

In the mean time I used this work around:

```
>>>tagdict = nltk.data.load('help/tagsets/upenn_tagset.pickle')
>>>tagdict['JJ']
('adjective or numeral, ordinal', 'third ill-mannered pre-war regrettable oiled
calamitous first separable ectoplasmic battery-powered participatory fourth stil
l-to-be-named multilingual multi-disciplinary ... ')
```

Not that it's too difficult, it's just that the API in python does usually allow both options (eg pprint.pformat vs pprint.pprint).

I can add the patch if it's welcome.

**Comment by stevenbird** [comment]
How would the book need to be changed?  In chapter 5 there are some places where nltk.help is mentioned.  Would these just need to be changed to, e.g.: ">>> print nltk.help.upenn_brown_tagset('NN.*')"?  If so, this is fine, and we just need to leave this issue open until the book is fixed (or else open another issue for that).  Thanks.

**Comment by ubershmekel** [comment]
There might be some more to be done here as I see some suffixes aren't handled (eg "JJ-HL"). 

I'm curious if this help API should return the constructed help string or something like the tuple (tag, definition, examples).

**Comment by stevenbird** [comment]
Is the suffix problem you mentioned an issue with the code or the data?

How about we add a new function that returns these tuples, instead of modifying the existing function?

**Comment by ubershmekel** [comment]
Well, there's problem with the data and the code imo. These suffixes need to be added:

```
fixes = {
    'FW': 'foreign',
    'NC': 'citations',
    'HL': 'headlines',
    'TL': 'titles'
    }
```

And the code should split on hyphens. I used the following to have it just work...

```
tagdict = nltk.data.load('help/tagsets/brown_tagset.pickle')
tagdict_b = nltk.data.load('help/tagsets/upenn_tagset.pickle')
tagdict_c = nltk.data.load('help/tagsets/claws5_tagset.pickle')




fixes = {
    'FW': 'foreign',
    'NC': 'citations',
    'HL': 'headlines',
    'TL': 'titles'
    }


def explain_one(part):
    """
    http://alias-i.com/lingpipe-3.9.3/docs/api/com/aliasi/corpus/parsers/BrownPosParser.html

    Each tag consists of a base tag and optional modifiers. This parser removes 
    all of the modifiers. The modifiers include multiple tags separated by plus-signs
    (eg. EX+BEZ), multiple tags concatenated in the case of negation (eg. BEZ*),
     the prefix modifier FW- for foreign words (e.g. FW-JJ), the suffix modifier -NC for citations (e.g. NN-NC),
     the suffix -HL for words in headlines (e.g. NN-HL-TL in titles (e.g. NNS-TL).
    """
    # Doesn't work because it only prints: nltk.help.upenn_tagset('JJ')
    if part is None:
        return 'Unidentified'
    if part in tagdict:
        data = tagdict[part]
    elif part in tagdict_b:
        data = tagdict_b[part]
    elif part in tagdict_c:
        data = tagdict_c[part]
    else:
        if part in fixes:
            return fixes[part]
        return '?'

    return data[0]



def part_explained(part):
    result = explain_one(part)
    if result == '?':
        multi = part.split('-')
        return ' '.join([explain_one(i) for i in multi])
    else:
        return result
```

I think adding a different function would be great (like pprint has 2 functions).

**Comment by jalbalah** [comment]
Just use this, which returns a string. Solved my same issue.
```
>>> tags = nltk.data.load('help/tagsets/upenn_tagset.pickle')
>>> tags['NN']
```
