### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'tagtype'

### ISSUE THREAD

**Issue by ImanoWilliams** [nltk/nltk#2051]
Hello, 
I got "TypeError: __init__() got an unexpected keyword argument 'tagtype'" when calling 

`parser = CoreNLPParser(url='http://localhost:9000', tagtype='pos')`

I am using NLTK 3.3 and CORENLP 3.9.1

It seems to work when I have `parser = CoreNLPParser(url='http://localhost:9000')`

**Comment by alvations** [comment]
@ImanoWilliams What is your python version? Might be that your NLTK version is out-of-sync. What's your output for:

```
python -c "import nltk; print(nltk.__version__)"
python2 -c "import nltk; print(nltk.__version__)"
python3 -c "import nltk; print(nltk.__version__)"

which python
which python2
which python3

which pip
which pip2
which pip3
```
-----

**Comment by ImanoWilliams** [comment]
@alvations, I had it resolved. I restarted the python console in PyDev Eclipse.
