### ISSUE TITLE
Exception while parsing using stanford parser

### ISSUE THREAD

**Issue by uriva** [nltk/nltk#2058]
```
from nltk.parse.stanford import StanfordParser

parser = StanfordParser(
    path_to_jar="./stanford-corenlp-full-2018-02-27/stanford-corenlp-3.9.1.jar",
    path_to_models_jar="./stanford-corenlp-full-2018-02-27/stanford-corenlp-3.9.1-models.jar")

parser.parse(['house', ')', 'is', 'in', 'York', 'Avenue'])
```

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-9-cac4347e364b> in <module>()
> ----> 1 parser.parser.parse(['house', ')', 'is', 'in', 'York', 'Avenue'])
> 
> ~/.local/lib/python3.6/site-packages/nltk/parse/api.py in parse(self, sent, *args, **kwargs)
>      43         """
>      44         if overridden(self.parse_sents):
> ---> 45             return next(self.parse_sents([sent], *args, **kwargs))
>      46         elif overridden(self.parse_one):
>      47             return (tree for tree in [self.parse_one(sent, *args, **kwargs)] if tree is not None)
> 
> ~/.local/lib/python3.6/site-packages/nltk/parse/stanford.py in parse_sents(self, sentences, verbose)
>     120         ]
>     121         return self._parse_trees_output(self._execute(
> --> 122             cmd, '\n'.join(' '.join(sentence) for sentence in sentences), verbose))
>     123 
>     124     def raw_parse(self, sentence, verbose=False):
> 
> ~/.local/lib/python3.6/site-packages/nltk/parse/stanford.py in _parse_trees_output(self, output_)
>      91                     blank = True
>      92                 else:
> ---> 93                     res.append(iter([self._make_tree('\n'.join(cur_lines))]))
>      94                     cur_lines = []
>      95             else:
> 
> ~/.local/lib/python3.6/site-packages/nltk/parse/stanford.py in _make_tree(self, result)
>     291 
>     292     def _make_tree(self, result):
> --> 293         return Tree.fromstring(result)
>     294 
>     295 
> 
> ~/.local/lib/python3.6/site-packages/nltk/tree.py in fromstring(cls, s, brackets, read_node, read_leaf, node_pattern, leaf_pattern, remove_empty_top_bracketing)
>     626                         cls._parse_error(s, match, open_b)
>     627                     else:
> --> 628                         cls._parse_error(s, match, 'end-of-string')
>     629                 label, children = stack.pop()
>     630                 stack[-1][1].append(cls(label, children))
> 
> ~/.local/lib/python3.6/site-packages/nltk/tree.py in _parse_error(cls, s, match, expecting)
>     677             offset = 13
>     678         msg += '\n%s"%s"\n%s^' % (' '*16, s, ' '*(17+offset))
> --> 679         raise ValueError(msg)
>     680 
>     681     #////////////////////////////////////////////////////////////
> 
> ValueError: Tree.read(): expected 'end-of-string' but got ')'
>             at index 113.
>

**Comment by alvations** [comment]
Please use the new `CoreNLPParser` interface.

First update your NLTK:

```
pip3 install -U nltk
```

Then still in terminal:

```
wget http://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip
unzip stanford-corenlp-full-2018-02-27.zip
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -preload tokenize,ssplit,pos,lemma,ner,parse,depparse -status_port 9000 -port 9000 -timeout 15000 &

python3
```

Finally, start Python:

```python3
>>> from nltk.parse import CoreNLPParser
>>> parser = CoreNLPParser(url='http://localhost:9000')
>>> list(parser.parse(['house', ')', 'is', 'in', 'York', 'Avenue']))
[Tree('ROOT', [Tree('S', [Tree('NP', [Tree('NN', ['house']), Tree('-RRB-', ['-RRB-'])]), Tree('VP', [Tree('VBZ', ['is']), Tree('PP', [Tree('IN', ['in']), Tree('NP', [Tree('NNP', ['York']), Tree('NNP', ['Avenue'])])])])])])]
```

**Comment by alvations** [comment]
Closing the issue as resolved for now =) 
Please open if there's further issues.
