### ISSUE TITLE
Not able to import nltk 

### ISSUE THREAD

**Issue by Priyansh2** [nltk/nltk#2061]
I am trying to import nltk in python2.7 interpreter but it throw this :- ![screenshot from 2018-07-12 00-59-09](https://user-images.githubusercontent.com/13703438/42595117-d2d4fdae-856e-11e8-99e1-07b8b2f9628a.png). I am curious why module "sklearn" have a problem while importing nltk. Any help is appreciated. The importing problem present in both version of python i.e 2.7 and 3.4. 
EDIT1:- I have tried reinstalling both "nltk" and "sklearn" module for both python2 and 3 but it still shows this error.

**Comment by 53X** [comment]
@Priyansh2 , what I understood from my limited knowledge is that your error is not an` ImportError` but rather an `AttributeError`and thus my suggestion would be to run `nltk.download()`  and make sure that all the submodules are downloaded.

@alvations , @stevenbird please throw some light here.

**Comment by Priyansh2** [comment]
@53X for doing `nltk.download()`, first  i have to `import nltk` but i'm not able to do that as shown in screenshot.

**Comment by 53X** [comment]
OOPS ... sorry my bad =) . Thanx for pointing that out @Priyansh2 . Did u try changing the version of Python? Did your` pip install nltk` run successfully?

**Comment by Priyansh2** [comment]
@53X  yes, i checked with python3 but still the same error. Even i tried the alternative way of downloading nltk stuff as written in [this](http://www.nltk.org/data.html#command-line-installation).

**Comment by alvations** [comment]
In that same directory what's the output of

```
$ python
>>> import os 
>>> os.listdir()
```

**Comment by Priyansh2** [comment]
@alvations When i give it the path of current working directory as you told it gives me this :-  [`'dup.txt', 'code_mixed-lyrics_bogie.csv', 'cm_line_map.py', 'Shabdanjali', 'IAA', 'classifier.pyc', 'model.pickle', 'code_mixed-out2.csv', 'full_reduplication.py', 'data', 'test', 'syllable_count.py', 'file_iaa.txt', 'li_and_back_transliteration.py', 'devnagari_word_list', 'english_word_list.txt', 'diff.py', 'verb_reduplicated_words3.txt', 'classifier.py', 'final_data', 'extract_data.py', 'new_songs_annotation', 'third_annotation', 'syll.py', 'English-Hindi', 'reduplicated_words2.txt', 'sota_transliterated', 'clean_romanized', 'hindi_word_list.txt', 'cm_lb_songs', 'corpus.txt', 'reduplicated_words.txt', 'tagging_songs1.py', 'word_list_gen.py', 'EW_features.py', 'all_files.txt', 'mod_all_files.txt', 'Final Hindi MWE Dataset', 'duplicate_removal.py', 'UW_Hindi_Dict_20131003', 'hindi_dict_extract.py', 'hindi-tokenizer', 'non_code_mixed.csv']
`

**Comment by Priyansh2** [comment]
@alvations @53X I am able to import nltk only if I run any python2/3 command with 'sudo'. That's very strange to me as it never happened before. I am closing this issue. Thank you all for your support :D
