### ISSUE TITLE
ConditionalFreqDist keys are mutated on call to plot

### ISSUE THREAD

**Issue by rmNULL** [nltk/nltk#2063]
### Brief
`ConditionalFreqDist` modifies the conditions(keys) when a non-existing key 
is passed as a `conditions` keyword argument to `tabulate()`/`plot()`.

Look at an
### Example  
![nltk-condist](https://user-images.githubusercontent.com/8173131/42654522-7dd6451a-8636-11e8-993a-fd10889dc211.png)

This undocumented behaviour appears a bug to me.

---

### Why is this happening to me ? 
**Note**,  please do correct(my blabbering).
The culprits behind this behaviour hide in [plot](https://github.com/nltk/nltk/blob/ecced11335a8942beeab4ed9020eb93f18457d10/nltk/probability.py#L1859) and [tabulate](https://github.com/nltk/nltk/blob/ecced11335a8942beeab4ed9020eb93f18457d10/nltk/probability.py#L1903) (forgive for stating the obvious). 

As `ConditionalFreqDist` is inherited from `defaultdict`, when we do a `self[c]`(links above), 
new key is created as a side-effect. This can be seen in an example below.

![default-dict](https://user-images.githubusercontent.com/8173131/42655543-1b815644-863a-11e8-89c2-01ee3e29eb8f.png)

__Thank You__

**Comment by irisxzhou** [comment]
Hello, I'm a new contributor to open source projects and I would like to work on this bug. :)

**Comment by rmNULL** [comment]
This was fixed and merged, closing.   Thanks @irisxzhou
