### ISSUE TITLE
Too many dependencies in conda-forge feedstock

### ISSUE THREAD

**Issue by buhrmann** [nltk/nltk#2066]
Hi, I've already created an issue on https://github.com/conda-forge/nltk-feedstock, but my suspicion is that that repo is not actively monitored by anyone, which is why I post this here too.

It seems that in the latest update of the feedstock too many unnecessary dependencies have been added, I suspect by accident. E.g. all of the following have been added as hard dependencies suddenly:

- gensim
- numpy
- python-crfsuite
- scikit-learn
- scipy
- matplotlib
- pyparsing
- twython
- requests

This leads to huge conda environments, including Qt etc.

The workaround is to install using pip instead, which leads to an environment 500MB smaller.

Just in case nobody's noticed...

**Comment by alvations** [comment]
@buhrmann Thanks for bringing this issue to our attention!

I'm not very sure how it works in conda land but do you know whether 

 - `nltk-feedstock` is something used by `anaconda` or (mini) `conda`, 
 - Who packages `nltk-feedstock`?  
 - And possibly why they used the `pip install nltk[all]` idiom to include all dependencies? 

@conda-forge-admin @pmlandwehr any clues?

**Comment by jnothman** [comment]
Conda-forge is a community packaging project, i.e. not maintained by
Continuum IO. But it is certainly a popular channel!

https://github.com/conda-forge/nltk-feedstock/blob/master/recipe/meta.yaml
says @pmlandwehr is the recipe maintainer.

Extra requirements were added here, apparently without comment or pull
request:
https://github.com/conda-forge/nltk-feedstock/commit/e400e09fbde3d0064bc5bb326c06fd506d00b982

**Comment by alvations** [comment]
Thanks @jnothman! I think depends on the purpose, if the package wants to achieve the "all-batteries included" purpose, then I guess 500MB is not much an issue. I suppose most of it might have been taken by `scipy`. 

I guess it's up to @pmlandwehr's decision whether to trim the extra dependencies ;P

**Comment by jnothman** [comment]
Hmmm... I think conda-forge would rather see this as a decision that the package maintainers should be involved in. NLTK is clear that it has minimal required external dependencies, and I think that's how conda-forge should supply it to users. Certainly, that would be consistent with the Anaconda NLTK package which depends only on things like Python, six, tk and sqlite.

I think 500MB is a serious violation of expectations in some contexts.

**Comment by alvations** [comment]
I didn't know `anaconda` only ships with minimal dependencies =)
Then @pmlandwehr and https://github.com/conda-forge/nltk-feedstock should follow try that.

**Comment by frankier** [comment]
Well anaconda is batteries included, but there's miniconda which doesn't come with the kitchen sink. The problem is Conda doesn't support square bracket type dependencies. The reasonable compromise at the moment would be to supply nltk with just minimal dependencies and an nltk-all metapackage. Then if people want something in-between they have to do it manually. There's a proposal now: https://github.com/conda/conda/issues/7502

**Comment by stevenbird** [comment]
Closing inactive issue.
