### ISSUE TITLE
Supporting Python3.7 

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#2072]
Python 3.7.0 had been shipped in June 2018, [PEP537](https://www.python.org/dev/peps/pep-0537/), I think it's better to pre-empt the end-of-life for Python 3.6 than to wait for user uptake and rush for a build. 

I think we're safe to have a tentative support for 3.7 later this Dec 2018 when 3.6.8 is shipped. End of life for Python 3.6 is Dec 2012 =)

This should help when porting code https://docs.python.org/3/whatsnew/3.7.html

It would be good if NLTK supports Python3.7 and the CI should be updated accordingly. 

Any brave soul?

**Comment by purificant** [comment]
Now that CI is fully running and passing on 3.7 is there anything else that needs to be done in order to 'officially' support 3.7 for the library? Other than updating docs and specifying versions for pypi.
