### ISSUE TITLE
issue while executing eliminiting proper noun

### ISSUE THREAD

**Issue by nandanii** [nltk/nltk#2075]
file not found at wordsEng.txt
![screenshot from 2018-08-04 16-40-02](https://user-images.githubusercontent.com/42090227/43675889-457e4bf0-9805-11e8-99bb-cd6af85d212d.png)

**Comment by alvations** [comment]
@nandanii Sorry I think this is not an issue related to NLTK specifically. I don't think we have any resource with filename `wordsEng.txt` in NLTK.

**Comment by alvations** [comment]
Closing `off-topic` issues to clean up the issue tracker. Please feel free to reopen or create PR if you find that the data/resource is coming from NLTK and causing the error.
