### ISSUE TITLE
TreebankWordTokenizer span_tokenize still throwing exception for some corner-cases

### ISSUE THREAD

**Issue by gkucsko** [nltk/nltk#2076]
very similar to #1865, there are still unhandled inputs to TreebankWordTokenizer that will cause span_tokenize to throw:
```
>>> from nltk.tokenize import TreebankWordTokenizer
>>> s = u"\'\'good muffins\""
>>> list(TreebankWordTokenizer().span_tokenize(s))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/tokenize/treebank.py", line 198, in span_tokenize
    for tok in align_tokens(tokens, text):
  File "nltk/tokenize/util.py", line 258, in align_tokens
    raise ValueError('substring "{}" not found in "{}"'.format(token, sentence))
ValueError: substring "''" not found in "''good muffins""
```
a working fix could be:
```
line 190 in tokenize.treebank.py:
matched = [m.group() for m in re.finditer(r"\`\`|(?<!^)\'\'|^\'\'(?=\s)|\"", text)]
```
i don't like the extra look arounds, but at least this wouldn't change anything about the current implementation. happy to submit a merge req if it's helpful!

**Comment by gkucsko** [comment]
@alvations (in regards to https://github.com/nltk/nltk/pull/1864#issuecomment-411657125)
thanks, agreed. due to the substitutions this will probably never work reliably. close this as won't fix?

**Comment by alvations** [comment]
If the current `span_tokenize()` is really buggy, we might want to deprecate it back to the `NotImplementedError` until a better solution. Meanwhile, we can leave this open because someone might be able to find some way to fix this smartly =)
