### ISSUE TITLE
sent_tokenize fails to seperate sentences that have no space after fullstop.

### ISSUE THREAD

**Issue by py-ranoid** [nltk/nltk#2082]
```
In [2]: nltk.sent_tokenize('Mary had little lamb.Mary had a little lamb')
Out[2]: ['Mary had little lamb.Mary had a little lamb']
```

**Comment by alvations** [comment]
c.f. https://github.com/nltk/nltk/pull/2081 

> This regex should not be made there are many cases of X.Y where X.Y is a token by itself.
> IMHO, since the Punkt sentence tokenizer is statistical, there shouldn't be regex hacks put in to determine how sentences should break.

Possibly users should clean their sentences before putting it through `sent_tokenize` =)

**Comment by alvations** [comment]
@py-ranoid A possible fix would be to retrain the punkt models on wikipedia and then re-submitting a PR with the models to https://github.com/nltk/nltk_data.

Otherwise, I think it's a `wontfix` for now =(

**Comment by MaryDongsn** [comment]
try 
import re
w1 = re.sub(r'([a-z])\.([A-Z])', r'\1. \2', w1)

**Comment by theorist17** [comment]
Isn't r'([a-z])\.([A-Z])' should be r'([a-z])\.([A-Z])'? First one would change "high AHI values" into "high. AHI values" for example.
