### ISSUE TITLE
sent_tokenize fails on sentence ending in smart quotes

### ISSUE THREAD

**Issue by AlJohri** [nltk/nltk#2085]
>In June, Trump’s 2020 campaign manager, Brad Parscale, called for Sessions to be fired and “end the Mueller investigation.”
>U.S. attorneys are prosecuting Manafort on charges of failing to pay taxes on millions he made from his work for a Russia-friendly Ukrainian political party and then lying to get loans when the cash stopped coming in.

![screen shot 2018-08-16 at 1 28 02 pm](https://user-images.githubusercontent.com/2790092/44224644-0d2cc800-a159-11e8-8ee0-9c2f803e887c.png)

resolution for now:

```
text = text.replace('“', '"').replace('”', '"')
```

would be great if this was supported OOB

**Comment by alvations** [comment]
c.f. #2082 

Since Punkt sentence tokenizer is a statistical model, we shouldn't be adding pre-/post-regex hacks to the the model. I suggest that we retrain the models. But it might require some pre-cursor issue, e.g. https://github.com/nltk/nltk/issues/2008

**Comment by alvations** [comment]
@AlJohri A possible fix would be to retrain the punkt models on wikipedia and then re-submitting a PR with the models to https://github.com/nltk/nltk_data.

Otherwise, I think it's a `wontfix` for now =(
