### ISSUE TITLE
nltk.corpus.reader.wordnet.WordNetError: line '01593254 v 0104

### ISSUE THREAD

**Issue by sivabushan** [nltk/nltk#2086]
While loading the application, im facing the  below error, 
ValueError: invalid literal for int() with base 10: 'v' During handling of the above exception, another exception occurred:
This happens when im trying to load wordnet. Please help me how to resolve this. Thank you

**Comment by alvations** [comment]
Please check whether your wordnet file is corrupted, in terminal/command prompt, do this:


```
$ cd ~
$ cd nltk_data/corpora/
$ md5sum wordnet.zip 
b3f38606f626e54c6f060548546f71f0  wordnet.zip
```

If the number is different, please rm the zip and redownload the wordnet data file:

```
$ cd nltk_data/corpora/
$ rm -rf wordnet
$ rm wordnet.zip
$ python3 -m nltk.downloader wordnet
```

**Comment by wishforgood** [comment]
I have come up with the same problem, the md5 value is checked to be correct. I have tried several lines of data, but all failed. The error messages are various: "not enough value to unpack"(for ARRANTIES, EXPRESS,OR \n) or "ValueError: invalid literal for int() with base 10:"(for "@", "+", etc.). I have also tried to get a older version of nltk on python3 but also faced the same problem. It seems like the data format is not correct, how can I find the corresponding data?

**Comment by wishforgood** [comment]
I have figured out my problem. I used nltk.corpus.reader.wordnet.synset_from_pos_and_offset(), but the offset number has zeros in the beginning. I didn't notice it and it turned out that the offset number was recognized to be an octal number. Therefore the wrong line was input to the function.
