### ISSUE TITLE
Hindi and Hinglish stop-words

### ISSUE THREAD

**Issue by TrigonaMinima** [nltk/nltk#2087]
Hi,
I am working with [Hinglish](https://en.wikipedia.org/wiki/Hinglish) data. While exploring the text corpus, I wanted to remove the stopwords from the data. There were none for the Hinglish. So, I created one big stopwords list for Hinglish. I have basically used the English one from NLTK plus transliterated hindi words. I also have one having just Hindi stopwords. I wanted them to be accessible to others as well

I was wondering whether it's okay if I create a pull having the hindi and hinglish stopwords.

**Comment by alvations** [comment]
Thank you for proposing the hinglish and hindi stopwords. Please do continue the conversation on adding the stopwords on https://github.com/nltk/nltk_data 

(Do note that the issues on `nltk_data` gets handled slower because it involves some book-keeping of datasets)

**Comment by sid22** [comment]
Hey @TrigonaMinima , have you made any list for Hinglish data?

**Comment by TrigonaMinima** [comment]
Yeah, but it's not uploaded here. I have opened another issue in the https://github.com/nltk/nltk_data repo as mentioned by alvations, but I haven't received any response there.

**Comment by oldmcdonalds** [comment]
Hey @TrigonaMinima, any luck on this?

**Comment by TrigonaMinima** [comment]
@aakashgupta0205 here's the stopword list - https://github.com/TrigonaMinima/HinglishNLP/blob/master/data/assets/stop_hinglish

**Comment by mohsin651** [comment]
Alright, thank you!

**Comment by ajayraho** [comment]
https://www.kaggle.com/datasets/prxshetty/stop-words-hinglish
