### ISSUE TITLE
Zipfile as corpus fails unless a subdirectory is appended to the filename

### ISSUE THREAD

**Issue by meldavis** [nltk/nltk#2090]
I am adding another issue because I could not reopen #1986.

Issue #1986 is still broken.   The fix did remove the exception; however, now the corpus fails to return any data.    Note that this issue applies to all corpus; I am using the Twitter Corpus as an example.

The issue is using a zip file as a corpus fails, unless a subdirectory is appended to the zip's filename.
Example: ```twitter_samples.zip``` will fail; but ```twitter_samples.zip/twitter_samples/``` will work.

Python: 3.7.0
NLTK: 3.3.0
OS: Windows 10 x64

### Appending a subdirectory to the zip filename
``` python
from nltk.corpus.reader import TwitterCorpusReader
c = TwitterCorpusReader(root='twitter_samples.zip/twitter_samples/', fileids="negative_tweets.json")
print(c.abspaths())
print(c.fileids())
```
This correctly reports
 ```
[ZipFilePathPointer('D:\\Projects\\corpus\\twitter_samples.zip', 'twitter_samples/negative_tweets.json')]
['negative_tweets.json']
```

### Using a zipfile as a corpus root produces no data
```
c = TwitterCorpusReader(root='twitter_samples.zip', fileids="twitter_samples/negative_tweets.json")
print(c.abspaths())
print(c.fileids())
```
This incorrectly reports an empty set: 
```
[]
[]
```

**Comment by purificant** [comment]
@meldavis Proposed fix is here: https://github.com/nltk/nltk/pull/2176

**Comment by stevenbird** [comment]
Resolved
