### ISSUE TITLE
concordance method - bug?

### ISSUE THREAD

**Issue by luckybook2018** [nltk/nltk#2095]
Hello,

I noticed that when I use concordance method, it always only searches up to 25.  It was not the case before. Not sure if this has something to do with the new release? To give a concrete example, when I did text2.concordance('affection'), it used to return "Display 25 of 79 matches" (I did this in Spring). Now it only returns "Display 25 of 25 matches"). I tried text2.concordance('the'), text2.concordance('the'), etc (i.e., those stop words), it all gave me "Display 25 of 25 matches'). Just to be more clear, it is the search, not the display issue I raise here. Could someone look into this? Thank you so much.

**Comment by alvations** [comment]
@luckybook2018 this issue should have been fixed by #2026  in the bleeding edge branch.

If you want it to be resolved now, you can try the bleeding edge version with the following:

```
pip3 install -U https://github.com/nltk/nltk/archive/develop.zip 
```

Otherwise waiting for the next version is the other option.
