### ISSUE TITLE
nltk.collocations.QuadgramAssocMeasures() is missing

### ISSUE THREAD

**Issue by BLKSerene** [nltk/nltk#2100]
nltk.collocations only import BigramAssocMeasures and TrigramAssocMeasures from nltk.metrics, and QuadgramAssocMeasures is left out.

**Comment by alvations** [comment]
Thanks @BLKSerene for raising this! 

Try this (for now):

```
from nltk.metrics.association import QuadgramAssocMeasures
```

Meanwhile wait for a quick patch in the next version before you can do:

```
from nltk.collocations import QuadgramAssocMeasures
```

----

Yeah, that's a gotcha that has been [quite a while](https://stackoverflow.com/questions/34230592/nltk-quadgram-collocation-finder) and it's an easy fix. Lets do that.

**Comment by bharatr21** [comment]
@alvations @BLKSerene is this issue still open? And if the CI related issues are fixed, I'm going for this

**Comment by alvations** [comment]
Thanks @Bharat123rox ! Forgot about this after we tried to fix the CI some time ago.
