### ISSUE TITLE
No module named corenlp

### ISSUE THREAD

**Issue by getamu** [nltk/nltk#2106]
After following the steps,
when I run 
`from nltk.parse.corenlp import CoreNLPDependencyParser`
I am still getting 
`No module named corenlp`
I downloaded the corenlp 3.9.1 from https://stanfordnlp.github.io/CoreNLP/
Kindly reply

**Comment by alvations** [comment]
What is your NLTK version?

```
print(nltk.__version__)
```

Please upgrade your NLTK, you would need v3.3 and above for `nltk.parse.corenlp` to work properly.

```
pip3 install -U nltk
```

Please read this for more details on how to use the CoreNLP API in NLTK: https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK
