### ISSUE TITLE
How to get all the words under a lexname (lexical filename) from nltk wordnet

### ISSUE THREAD

**Issue by suman101112** [nltk/nltk#2110]
Explanation with the help of Example: 
`lexical_filename = Synset('muscle.n.01').lexname() `
The output is `noun.body`

I want to **extract all the words and synsets** under the lexical filename **noun.body**

**Comment by nschneid** [comment]
I don't know if there's a direct way to do this in the API, but you could do this indirectly (and perhaps inefficiently) by iterating over all synsets and filtering by lexname.

**Comment by alvations** [comment]
@suman101112 , try:

```python
>>> from itertools import chain
>>> from nltk.corpus import wordnet as wn
>>> noun_lemmas_in_wordnet = set(chain(*[ss.lemma_names() for ss in wn.all_synsets(pos='n')]))
```

please see https://stackoverflow.com/a/33538878/610569 for more details.

**Comment by suman101112** [comment]
Thank you.


Regards,

Suman D.

**Comment by xandyxor** [comment]
sorry
but I think it just lists all the words from NLTK 

(Almost equivalent  to 
```python 
i for i in wn.words()
```
)
not  Select by lexname
```python
def fun(lexname='verb.motion')
''' List all words from verb.motion '''
```
