### ISSUE TITLE
Kabyle tokenization/morphosyntactic processing

### ISSUE THREAD

**Issue by MohammedBelkacem** [nltk/nltk#2111]
I'm using nltk to generate a morph-syntactic analysis for the Kabyle language. I developed scripts for tokenization and use perceptron algorithm. I wrote a morpho-syntactic corpora and wish to share with a public licence.

Please how can I share algorithms and this corpora within nltk?

**Comment by stevenbird** [comment]
@belkacem77 thanks for telling us about this work. It's unfortunate but we don't have developer capacity to process and maintain code that is just for a single language like this. Ironically, one reason for this is that I am also working on endangered languages. Anyway, NLTK does not need to be the distribution channel... it is not hard to create your own repository and maintain it. Sorry about this.
