### ISSUE TITLE
cls vs self in classmethods

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#2115]
There are several instances of `@classmethod` that doesn't have `cls` as the first argument:

```
nltk/test/unit/lm/test_vocabulary.py:20: [C0202(bad-classmethod-argument), NgramModelVocabularyTests.setUpClass] Class method setUpClass should have 'cls' as first argument
nltk/corpus/reader/mte.py:47: [C0202(bad-classmethod-argument), MTEFileReader._word_elt] Class method _word_elt should have 'cls' as first argument
nltk/corpus/reader/mte.py:51: [C0202(bad-classmethod-argument), MTEFileReader._sent_elt] Class method _sent_elt should have 'cls' as first argument
nltk/corpus/reader/mte.py:55: [C0202(bad-classmethod-argument), MTEFileReader._para_elt] Class method _para_elt should have 'cls' as first argument
nltk/corpus/reader/mte.py:59: [C0202(bad-classmethod-argument), MTEFileReader._tagged_word_elt] Class method _tagged_word_elt should have 'cls' as first argument
nltk/corpus/reader/mte.py:78: [C0202(bad-classmethod-argument), MTEFileReader._tagged_sent_elt] Class method _tagged_sent_elt should have 'cls' as first argument
nltk/corpus/reader/mte.py:82: [C0202(bad-classmethod-argument), MTEFileReader._tagged_para_elt] Class method _tagged_para_elt should have 'cls' as first argument
nltk/corpus/reader/mte.py:86: [C0202(bad-classmethod-argument), MTEFileReader._lemma_word_elt] Class method _lemma_word_elt should have 'cls' as first argument
nltk/corpus/reader/mte.py:93: [C0202(bad-classmethod-argument), MTEFileReader._lemma_sent_elt] Class method _lemma_sent_elt should have 'cls' as first argument
nltk/corpus/reader/mte.py:97: [C0202(bad-classmethod-argument), MTEFileReader._lemma_para_elt] Class method _lemma_para_elt should have 'cls' as first argument
nltk/parse/bllip.py:203: [C0202(bad-classmethod-argument), BllipParser.from_unified_model_dir] Class method from_unified_model_dir should have 'cls' as first argument
```

c.f. [PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments) and [What is the 'cls' variable used for in Python classes?](https://stackoverflow.com/questions/4613000/what-is-the-cls-variable-used-for-in-python-classes)

> **Function and Method Arguments**
>
>Always use self for the first argument to instance methods.
>
>Always use cls for the first argument to class methods.
>
>If a function argument's name clashes with a reserved keyword, it is generally better to append a single trailing underscore rather than use an abbreviation or spelling corruption. Thus class_ is better than clss. (Perhaps better is to avoid such clashes by using a synonym.)

It'll take some refactoring to fix these but there are some instance of mixing `@classmethod` and `self` usage but it's not clear which is the idiomatic convention we should follow, e.g. https://stackoverflow.com/questions/52305191/using-self-vs-cls-to-access-variable-in-unittest

Any suggestion?

**Comment by aquatiko** [comment]
I would like to solve this issue, but as much as I know self and cls don't have any technical differences, does it?

**Comment by gmotzespina** [comment]
I think this issue was solved, it might be good to close the issue
