### ISSUE TITLE
Artifacts from Python <=2.6  

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#2120]
There are some artifacts from Python <=2.6 which is irrelevant today in Python 2.7 and Python 3.x, **should we remove them?**

Pylint caught one of them at https://github.com/nltk/nltk/blob/develop/nltk/decorators.py#L27

> nltk/nltk/decorators.py:30: [E0401(import-error), ] Unable to import 'sets'

```python
try:
    set
except NameError:
    from sets import Set as set
```

See also: https://stackoverflow.com/a/38042101/610569

**Are there other artifacts from Python <=2.6 that anyone has noticed?**

**Comment by purificant** [comment]
Python 2.6 is not officially supported, so in my view remove any code that only exists to support older versions such as <= 2.6
