### ISSUE TITLE
Adding Good turing and Add -n Smoothing

### ISSUE THREAD

**Issue by sahitpj** [nltk/nltk#2124]
Apart from the existing 2 smoothing algorithms already present, I think the add -n smoothing and the Good turing smoothing can be added

**Comment by iliakur** [comment]
Hmm, by "add-n smoothing" do you mean Lidstone/Laplace? or absolute discounting (of which Kneser-Ney is a particular case)?

The former is already present (should be importable...). The latter you are welcome to add, just like good-turing.

I personally don't have the time in the foreseeable future to do this. Unfortunately.

I'll gladly help review submissions!

**Comment by sahitpj** [comment]
Thanks @Copper-Head Will shortly create a pull request for that

**Comment by sahitpj** [comment]
@Copper-Head For the GoodTuring Smoothing, i think we need to add a function which counts the no of n-grams which have a particular count. Should I add it to the smoothing function, or should I can I add it to the Language Model object itself, as a generalized func

**Comment by iliakur** [comment]
I would say keep it more localized to the GT model, wouldn't wanna burden the LM object with too much functionality. If at some point we need to reuse it, we can consider factoring it out somehow
