### ISSUE TITLE
How to distinguish adverbs of manner from other adverbe categories

### ISSUE THREAD

**Issue by kamihamiha123** [nltk/nltk#2133]
Is theire a way to have more detailed pos tagging that specifies which type of adverbes, adjectives it is (manner, frequency, time, etc.) ?

**Comment by alvations** [comment]
@kamihamiha123 The model is trained on the WSJ that has the standard Penn Treebank tagset, so it's not possible for the `pos_tag` function to generate any other tag outside of what it's trained on.  See details: https://github.com/nltk/nltk/issues/1783#issuecomment-317174189

To have other tagsets, you would first require a tagged corpus of the required tagset and train your own model. 

If it's alright, we'll close this issue. But feel free to create a Pull-Request if you would like to contribute a corpus with the finer-grained tags or a pre-trained model implemented with the finer-grained tags based on some publication.
