### ISSUE TITLE
nltk error

### ISSUE THREAD

**Issue by abhisri7635** [nltk/nltk#2143]
import nltk
nltk.download('Stopwords')
[nltk_data] Error loading Stopwords: <urlopen error [WinError 10054]
[nltk_data]     An existing connection was forcibly closed by the
[nltk_data]     remote host>

**Comment by purificant** [comment]
Try with lowercase `stopwords` and check that you can access  https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml from your system.

**Comment by alvations** [comment]
@abhisri7635 Could we check whether you're still having the problem?

**Comment by vinaykumar0409** [comment]
I have similar problem 
>>> import nltk
>>> nltk.download('punkt')
[nltk_data] Error loading punkt: <urlopen error [WinError 10054] An
[nltk_data]     existing connection was forcibly closed by the remote
[nltk_data]     host>
False
>>>

**Comment by krishnaspeakz** [comment]
I'm still facing this issue can anyone help me with this

**Comment by tomaarsen** [comment]
@krishnaspeakz 
Some users, particularly those who are using the "Jio" internet provider, have experienced this issue. They seemed to have been able to resolve it by connecting to mobile hotspot temporarily while downloading NLTK data, or by changing some DNS settings.

There's a bit more info here, perhaps it'll help: https://github.com/nltk/nltk/issues/3146
