### ISSUE TITLE
python 3.7 compatibility PEP 479

### ISSUE THREAD

**Issue by purificant** [nltk/nltk#2148]
There are several places in the code base that result in `RuntimeError: generator raised StopIteration` when executed with python 3.7+.

This happens because [PEP 479](https://www.python.org/dev/peps/pep-0479/) made a change to generators: when [StopIteration](https://docs.python.org/3/library/exceptions.html#StopIteration) is raised inside a generator, it is replaced with [RuntimeError](https://docs.python.org/3/library/exceptions.html#RuntimeError) when the exception is about to bubble out of the generator.
This behaviour is not backwards compatible and was slowly introduced with this [transition plan](https://www.python.org/dev/peps/pep-0479/#transition-plan).

In python 3.6 the code emits a non-silent deprecation warning, but starting with python 3.7 it becomes a runtime error.

Code changes are necessary to enable python 3.7 compatibility for PEP 479.

**Comment by purificant** [comment]
Several amends merged as part of https://github.com/nltk/nltk/pull/2153

**Comment by alvations** [comment]
All patched up for Py3.7? The CI tests pass =) 

Thanks @purificant for all the work!

**Comment by purificant** [comment]
Thanks @alvations for your help. I think we can close this for now as no further known changes are needed. In the future if there are any python 3.7 issues with `RuntimeError: generator raised StopIteration` we can reference this issues.

**Comment by ChrisIsKing** [comment]
I'm facing this issue when using `nltk.AnnotationTask().kappa()`

**Comment by GavinAbercrombie** [comment]
Same issue with AnnotationTask
