### ISSUE TITLE
testsuite failure in ccg.doctest (python 2.6.6)

### ISSUE THREAD

**Issue by slattarini** [nltk/nltk#215]
The following example in ccg.doctest:

   for parse in parser.nbest_parse("you prefer that cake".split(),1):
       chart.printCCGDerivation(parse)
       for parse in parser.nbest_parse("that is the cake which you prefer".split(), 1):
           chart.printCCGDerivation(parse) # doctest: +NORMALIZE_WHITESPACE

is failing with python 2.6.6, since the expected and produced outputs differ as follows:

``` diff
--- exp   2012-02-11 17:48:17.000000000 +0100
+++ got   2012-02-11 17:48:12.000000000 +0100
@@ -1,7 +1,7 @@
      you    prefer      that   cake 
      NP   ((S\NP)/NP)  (NP/N)   N   
-         --------------------->B
-              ((S\NP)/N)
+                      -------------->
+                            NP
          --------------------------->
                    (S\NP)
     --------------------------------<
@@ -23,4 +23,6 @@
           ------------------------------------------------------------->
                                      (S\NP)
     -------------------------------------------------------------------<
-            
+                                     S
+
+
```

**Comment by stevenbird** [comment]
Yes, we're aware of this problem, and are continuing to fix the doctests.
