### ISSUE TITLE
Import terrible slow

### ISSUE THREAD

**Issue by RochaOwng** [nltk/nltk#2155]
Hi, my code is taking sooo long after I used "nltk.downlod()".
Now, when I use import nltk it tooks more than a minute

Anyone?

**Comment by alvations** [comment]
@RochaOwng Which OS are you using? What is the NLTK version you're using?  What is the output of the following:

```python
>>> import platform
>>> platform.platform()
'Darwin-17.7.0-x86_64-i386-64bit'

>>> import nltk
>>> nltk.__version__
'3.3'
```

Could you explain what is taking more than a minute? Is downloading the data taking time or is it opening of the GUI after you call `nltk.download()`? `nltk.download()` usually fire up the GUI quite quickly. 

Are you using an unrestricted network, e.g. your home internet? Or are you using a work/school network? Perhaps your network is under some proxy and it takes a while to reach the github index. Please check with your network administrator if the problem persist.

**Comment by RochaOwng** [comment]
@alvations I'm using Windows 10 64bit, and the NLTK version is 3.3
The task what is taking more than a minute is the "import nltk"
I've downloaded the packages (all of them, is that a problem?), And when I import nltk I got this. I don't think it's a problem with my network, because I should be able to code offline, right? Also, I've run into my home and in my enterprise ..

Thank you

**Comment by alvations** [comment]
What machine are you running this on? Are you using IDLE? How did you install NLTK, through conda? Or like this, e.g. https://gist.github.com/alvations/0ed8641d7d2e1941b9f9 ?

**Comment by purificant** [comment]
Just to confirm that import is the culprit, what is the output of these commands?
```
$ python --version
$ python -m timeit "import nltk"
```

**Comment by alvations** [comment]
@RochaOwng are you still having speed issues with NLTK? If not, could we mark the issue as resolved and close it?

**Comment by atobe** [comment]
It's notably slow to import on my machine and I use quite a few packages to have the basis for comparison. It is the only one that shifts me out of interactiveland into thinking...I am waiting for this to load, and when I'm importing it as part of a script or waiting for tests to run that starts to grate.

I'm on a Mac, here's my data:

```
Python 3.5.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:11:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.
...
In [6]: nltk.__version__
Out[6]: '3.3'

In [7]: platform.platform()
Out[7]: 'Darwin-17.7.0-x86_64-i386-64bit'

python --version
Python 3.5.5 :: Anaconda, Inc.
```
I think this is a fair representation of my user experience:

```
time python -c 'import nltk'

real	0m1.902s
user	0m1.004s
sys	0m0.327s

time python -c 'import nltk'

real	0m1.221s
user	0m0.993s
sys	0m0.202s

time python -c 'import nltk'

real	0m1.181s
user	0m0.978s
sys	0m0.193s
```
And therefore I suspect timeit is measuring warm performance:
```
python -m timeit "import nltk"
10 loops, best of 3: 0.57 usec per loop
```
Contrast with numpy for instance:

```
time python -c 'import numpy'

real	0m0.315s
user	0m0.226s
sys	0m0.067s
```
I tried both conda and pip installs of version 3.3 with much the same results.

Now this machine has an SSD, but for kicks I created a ramdisk to compare:

```
$ hdid -nomount ram://2097152
/dev/disk2          	                               	
$ diskutil erasedisk APFS "mypy" /dev/disk2
Started erase on disk2
...
$ cd /Volumes/mypy/
/Volumes/mypy $ conda create -p /Volumes/mypy/mypy -m python=3.5 
/Volumes/mypy $ conda activate /Volumes/mypy/mypy
(/Volumes/mypy/mypy) $ /Volumes/mypy $ which pip
/Volumes/mypy/mypy/bin/pip
(/Volumes/mypy/mypy) $ /Volumes/mypy $ pip install nltk
Installing collected packages: six, nltk
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:30:03) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__file__
'/Volumes/mypy/mypy/lib/python3.5/site-packages/nltk/__init__.py'
>>> import six
>>> six.__file__
'/Volumes/mypy/mypy/lib/python3.5/site-packages/six.py'
>>> 
(/Volumes/mypy/mypy) $ /Volumes/mypy $ time python -c 'import nltk'
real	0m0.569s
user	0m0.453s
sys	0m0.095s
(/Volumes/mypy/mypy) $ /Volumes/mypy $ time python -c 'import nltk'
real	0m0.616s
user	0m0.503s
sys	0m0.094s
(/Volumes/mypy/mypy) $ /Volumes/mypy $ time python -c 'import nltk'
real	0m0.565s
user	0m0.470s
sys	0m0.083s
(/Volumes/mypy/mypy) $ /Volumes/mypy $ pip install numpy\
...
(/Volumes/mypy/mypy) $ /Volumes/mypy $ time python -c 'import numpy'
real	0m0.288s
user	0m0.406s <~ hmm, multicore??
sys	0m0.169s
```
Note how the times are more compressed for nltk than numpy. I take that to mean nltk is reading from the disk a lot more.

Happily putting the environment into ramdisk makes development pleasant again, but it's one hell of a workaround.

I don't know the situation with nltk 3, but the argument used to be 'the toplevel has to load everything to maintain compatibility with the book'. Is this still true?

FWIW I would be happy to use more explicit imports, e.g. from ntlk.featstruct import *, but that still seems to import the whole package.

I tried with and without some of the taggers installed via nltk.download() but that didn't seem to make much of a difference.

Oh and SSD vs ramdisk for just starting python:

```
(py35) $ /Users/atobe $ time python -c 'print(1)'
real	0m0.062s
real	0m0.058s
real	0m0.067s

(/Volumes/mypy/mypy) $ time python -c 'print(1)'
real	0m0.043s
real	0m0.039s
real	0m0.038s
```

**Comment by alvations** [comment]
@atobe Out of curiosity what's your Mac hardward specs (system information)? 

Is the same happening if you don't use Anaconda? Do you get the same experience when you import spacy/gensim/sklearn in Anaconda?

----

For me, hardware:

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	16 GB
```

OS, Python, NLTK:

```
$ python3
Python 3.6.4rc1 (v3.6.4rc1:3398dcb14f, Dec  5 2017, 00:58:30) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> import nltk
>>> nltk.__version__
'3.3'
>>> platform.platform()
'Darwin-17.7.0-x86_64-i386-64bit'
```

Time:

```
$ time python -c 'import nltk'

real	0m0.492s
user	0m0.279s
sys	0m0.170s

$ time python -c 'import nltk'

real	0m0.448s
user	0m0.275s
sys	0m0.153s

$ time python -c 'import nltk'

real	0m0.462s
user	0m0.282s
sys	0m0.161s
```

**Comment by purificant** [comment]
@atobe thank you for providing test data from your experiments

It is interesting that you are seeing much higher import times for nltk compared to numpy. I get somewhat different results on Ubuntu with various python versions installed through pyenv.

For comparison, this is representative on my system, for nltk:
```
$ time python -c 'import nltk'

real    0m0.279s
user    0m0.500s
sys     0m0.476s

$ time python -c 'import nltk'

real    0m0.290s
user    0m0.446s
sys     0m0.541s

$ time python -c 'import nltk'

real    0m0.292s
user    0m0.493s
sys     0m0.495s
```

for numpy:
```
$ time python -c 'import numpy'

real    0m0.155s
user    0m0.329s
sys     0m0.521s

$ time python -c 'import numpy'

real    0m0.165s
user    0m0.335s
sys     0m0.521s

$ time python -c 'import numpy'

real    0m0.160s
user    0m0.308s
sys     0m0.546s
```

While nltk numbers are higher the difference is not as big as in your tests.

I attempted the same on python 3.5, 3.6 and 3.7 in fresh virtual environments with just nltk and numpy installed through pip. There appears to be about 10% performance improvement when using 3.7, there weren't any noticeable differences between 3.5 and 3.6. This could be explained by [performance improvements](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-perf) in the CPython implementation of python 3.7.

When trying the same with anaconda3-5.3.0 I get roughly 50% worse real time results for nltk but better results for numpy. This may explain your use case.

The reason for using `timeit` module is that it focuses on just the code execution without including the rest of the ecosystem of the interpreter which can vary for various environments and python implementations.

**Comment by stevenbird** [comment]
@alvations, @purificant: thanks for your input. Closing as it is inactive.
