### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by Bogdanrasputin** [nltk/nltk#2158]
I am trying to run this code:
```
import nltk
nltk.download()
```
but I am getting this issue:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:726)>

**Comment by alvations** [comment]
@Bogdanrasputin We'll need some extra information to help you with the problem. 

- Which OS are you using? Are you using a Mac? 
- Which NLTK version are you using.

Do take a look at https://github.com/nltk/nltk/issues/2029#issuecomment-392426356 and see whether that resolve your problem.

**Comment by Bogdanrasputin** [comment]
I am working on a mac, python version 2.7. NLTK version 3.3

**Comment by Bogdanrasputin** [comment]
Fixed it by opening `Install Certificates.command` in the python application folder. Thanks :)
