### ISSUE TITLE
Unable to find "/usr/share/nltk_data" when adding binary and data files.

### ISSUE THREAD

**Issue by csarta** [nltk/nltk#2159]
I get this error when I try to create an executable of a python3 file with pyinstaller. 
Precisely I get:

> 38 INFO: PyInstaller: 3.4
> 38 INFO: Python: 3.6.6
> 39 INFO: Platform: Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
> 39 INFO: wrote /home/user/Documents/py_stuff/chatBotV3/broize.spec
> 40 INFO: UPX is not available.
> 41 INFO: Extending PYTHONPATH with paths
> ['/home/user/Documents/py_stuff/chatBotV3',
>  '/home/user/Documents/py_stuff/chatBotV3']
> 42 INFO: checking Analysis
> 42 INFO: Building Analysis because Analysis-00.toc is non existent
> 42 INFO: Initializing module dependency graph...
> 43 INFO: Initializing module graph hooks...
> 44 INFO: Analyzing base_library.zip ...
> 2756 INFO: running Analysis Analysis-00.toc
> 2787 INFO: Caching module hooks...
> 2793 INFO: Analyzing /home/user/Documents/py_stuff/chatBotV3/broize.py
> 3285 INFO: Processing pre-safe import module hook   six.moves
> 4363 INFO: Processing pre-find module path hook   distutils
> 5352 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
> 5725 INFO: Processing pre-find module path hook   site
> 5725 INFO: site: retargeting to fake-dir '/home/user/.local/lib/python3.6/site-packages/PyInstaller/fake-modules'
> 9893 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
> 13100 INFO: Loading module hooks...
> 13100 INFO: Loading module hook "hook-numpy.core.py"...
> 13194 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
> 13194 INFO: Loading module hook "hook-encodings.py"...
> 13253 INFO: Loading module hook "hook-xml.py"...
> 13254 INFO: Loading module hook "hook-certifi.py"...
> 13255 INFO: Loading module hook "hook-pkg_resources.py"...
> 13466 INFO: Processing pre-safe import module hook   win32com
> 13673 INFO: Loading module hook "hook-pydoc.py"...
> 13673 INFO: Loading module hook "hook-lib2to3.py"...
> 13674 INFO: Loading module hook "hook-sqlite3.py"...
> 13724 INFO: Loading module hook "hook-sysconfig.py"...
> 13733 INFO: Loading module hook "hook-cryptography.py"...
> 13924 INFO: Loading module hook "hook-pytest.py"...
> 14535 INFO: Loading module hook "hook-distutils.py"...
> 14535 INFO: Loading module hook "hook-nltk.py"...
> Unable to find "/usr/share/nltk_data" when adding binary and data files.

**Comment by alvations** [comment]
Before compiling your executable with pyinstaller, try to set the `NLTK_DATA` environmental variable first. E.g. 

```
export NLTK_DATA=/home/user/nltk_data
```

**Comment by dnm1977** [comment]
Does not work for me.

**Comment by Steven-AA** [comment]
same problem for windows.

**Comment by lkfo415579** [comment]
same problem for linux(ubuntu) with newest pyinstaller, setuptool and nltk.

**Comment by lkfo415579** [comment]
pyinstaller downgrade back to 3.3, problem solved.

**Comment by bleuest** [comment]
Same problem for windows.

**Comment by BLKSerene** [comment]
I've met the same issue here. The problem is that the hook in PyInstaller 3.4 does not check whether paths in `nltk.data.path` exist before adding them to the `datas`. [This PR](https://github.com/pyinstaller/pyinstaller/pull/3897) and [this PR](https://github.com/pyinstaller/pyinstaller/pull/3973) would fix this but both ones haven't been merged yet (as of my writing).

PyInstaller 3.3 works just because the new NLTK hook was added in PyInstaller 3.4, so there's no hook provided for `nltk_data` in 3.3, but that means you need to include `nltk_data` in the package manually if your app needs the data. Otherwise, some data might be missing for you packaged app.

**Comment by aced125** [comment]
Hoping these pull requests get merged soon as I'm having the same issue.

**Comment by Nomiluks** [comment]
Hey, I am using development version of `PyInstaller == 3.5.dev0+b54a15d72e`. But I guess this issue is still not resolved yet. I am still getting this error.


`Unable to find "/home/user/anaconda2/envs/matching/nltk_data" when adding binary and data files.`

I have also updated the NLTK_DATA =  `/home/user/nltk_data`

Any suggestions ?

**Comment by ArihantKumarSeraogi** [comment]
Are you guys not going to fix it the issue still persists

**Comment by AndrasPataki** [comment]
Hello guys. I solved the problems editing the pyinstaller nltk-hook. After much research, I decided to go it alone in the code structure. I solved my problem by commenting on the lines:
`datas=[]`

`'''for p in nltk.data.path:
    datas.append((p, "nltk_data"))'''`

`hiddenimports = ["nltk.chunk.named_entity"]`

What's more, you need to rename the file: pyi_rth__nltk.cpython-36.pyc to pyi_rth_nltk.cpython-36.pyc . This file have 1 more underline. Warning with the python version.

**Comment by Diyago** [comment]
Issue still persists

**Comment by seplveda** [comment]
> Issue still persists

Still persists, but @AndrasPataki approach still works, just find _hook-nltk.py_ and edit. 
In my case the path was: 'C:\anaconda3\envs\opt\Lib\site-packages\PyInstaller\hooks'. 

works: **INFO: Building EXE from EXE-00.toc completed successfully.**

**Comment by PasaOpasen** [comment]
> > Issue still persists
> 
> Still persists, but @AndrasPataki approach still works, just find _hook-nltk.py_ and edit.
> In my case the path was: 'C:\anaconda3\envs\opt\Lib\site-packages\PyInstaller\hooks'.
> 
> works: **INFO: Building EXE from EXE-00.toc completed successfully.**

what should I edit? my file is 


import nltk
from PyInstaller.utils.hooks import collect_data_files

# add datas for nltk
datas = collect_data_files('nltk', False)

# loop through the data directories and add them
for p in nltk.data.path:
    datas.append((p, "nltk_data"))

# nltk.chunk.named_entity should be included
hiddenimports = ["nltk.chunk.named_entity"]

**Comment by puddlejumper90** [comment]
Nothing works lol. I have tried everything on this feed. Anyone else solves the windows issue?

**Comment by Doctor-Venom** [comment]
This problem may be related to the path, I faced the same problem when I was running pyinstaller from a path that contains whitespaces ' ', brackets '[' ']' , and curly brackets '{' '}'... and the folder I was adding was in the same path. But when I moved my project directory to the root of  C:\ drive and ran the same pyinstaller command it worked with no problems.
