### ISSUE TITLE
Maybe the corpus_bleu method is wrong

### ISSUE THREAD

**Issue by weiyinfu** [nltk/nltk#2160]
The wrong file is nltk.translate.bleu_score.py.
I think the implementation of corpus_bleu is wrong .
When we calculate the corpus bleu,we need to take every sentence into consideration.
Assume that a corpus has 3 sentences and each sentence's word appear time is 2/5,3/6,4/8 (Here we only consider the unigram).
And all of the corpus' appear time is (2+3+4)/(5+6+8)=9/19.
If the above description is right, the implementation of the `corpus_bleu` is wrong.
Here is part of the code in `corpus_bleu`
```python
    # Iterate through each hypothesis and their corresponding references.
    for references, hypothesis in zip(list_of_references, hypotheses):
        # For each order of ngram, calculate the numerator and
        # denominator for the corpus-level modified precision.
        for i, _ in enumerate(weights, start=1):
            p_i = _modified_precision(references, hypothesis, i)
            p_numerators[i] += p_i.numerator
            p_denominators[i] += p_i.denominator

        # Calculate the hypothesis length and the closest reference length.
        # Adds them to the corpus-level hypothesis and reference counts.
        hyp_len = len(hypothesis)
        hyp_lengths += hyp_len
        ref_lengths += _closest_ref_length(references, hyp_len)

        # Calculate corpus-level brevity penalty.
    bp = _brevity_penalty(ref_lengths, hyp_lengths)
    # Collects the various precision values for the different ngram orders.
    p_n = [Fraction(p_numerators[i], p_denominators[i])
           for i, _ in enumerate(weights, start=1)]

```

The problem is that : The `Fraction` class will automatically simplify the fraction.
In the above example, Fraction(4/8) will become 1/2,and Fraction(3,6) will become 1/2.
So the final result will become :(2+1+1)/(5+2+2)=4/9. It is defenitely different from the above result.
I think the above method is right.
The main code is 
```python
            p_i = _modified_precision(references, hypothesis, i)
            p_numerators[i] += p_i.numerator
            p_denominators[i] += p_i.denominator
```
The `_modified_precision` method returns a `Fraction` and the numerator and denominator is wrong .
As as new bee in nlp,maybe I am wrong.Hoping someone can answer my question.

**Comment by alvations** [comment]
@weiyinfu BLEU score is basically a product of the fractions of the no. of overlaps between the hypothesis (machine translated sentences) and their respective reference sentences (human translations). Thus the use of `Fraction` object is quaintly apt. 

![](https://ibin.co/4KMc8zb1ZSwH.png)

Lets start reading the code from the `corpus_bleu()` function at https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L104

```python
def corpus_bleu(list_of_references, hypotheses, weights=(0.25, 0.25, 0.25, 0.25),
                smoothing_function=None, auto_reweigh=False):
```


The input arguments are:
 - `list_of_references` = List of references sentences per hypothesis sentence in the corpus
 - `hypotheses` = List of hypothesis (machine translated sentences)
 - `weights` = `w_n` in the BLEU formula
 - ` smoothing_function` = Smoothing functions as proposed by Chen and Cherry (2014); unique to NLTK, by default no smoothing function is used. 
 - `auto_reweigh` = Automatically reweigh the weights uniformly if the length of the hypothesis sentence is less than 4 and the default weights are used; unique to NLTK feature too, by default `auto_reweigh` is not used. 

----

Looking at the `p_n` formula we see that it's a fraction where the numerators are the ngram overlaps between hypotheses and the reference sentences. So we should keep tabs of the numerators and denominators 

```python
    # Before proceeding to compute BLEU, perform sanity checks.

    p_numerators = Counter()  # Key = ngram order, and value = no. of ngram matches.
    p_denominators = Counter()  # Key = ngram order, and value = no. of ngram in ref.
    hyp_lengths, ref_lengths = 0, 0

    assert len(list_of_references) == len(hypotheses), "The number of hypotheses and their reference(s) should be the same "
```

To compute the summation in equation (3) above, we must first find the numerators and denominators in equation (1) for each order of ngram, thus the loop here, https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L168:

```python
    # Iterate through each hypothesis and their corresponding references.
    for references, hypothesis in zip(list_of_references, hypotheses):
        # For each order of ngram, calculate the numerator and
        # denominator for the corpus-level modified precision.
        for i, _ in enumerate(weights, start=1):
            p_i = modified_precision(references, hypothesis, i)
            p_numerators[i] += p_i.numerator
            p_denominators[i] += p_i.denominator

        # Calculate the hypothesis length and the closest reference length.
        # Adds them to the corpus-level hypothesis and reference counts.
        hyp_len = len(hypothesis)
        hyp_lengths += hyp_len
        ref_lengths += closest_ref_length(references, hyp_len)
```

When iterating through the weights, we see that it's calling `modified_precision` with the `i` that ranges from `1-4` by default if there are 4 weight values set. That is when the ngram overlaps for equation (1) is computed from 1-grams to 4-grams.

```python
for i, _ in enumerate(weights, start=1):
            p_i = modified_precision(references, hypothesis, i)
```

If we look at the `modified_precision` function, https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L216 , it simply goes through all hypothesis and reference sentence to compute equation (1).

```python
def modified_precision(references, hypothesis, n)
     # Extracts all ngrams in hypothesis
    # Set an empty Counter if hypothesis is empty.
    counts = Counter(ngrams(hypothesis, n)) if len(hypothesis) >= n else Counter()
    # Extract a union of references' counts.
    # max_counts = reduce(or_, [Counter(ngrams(ref, n)) for ref in references])
    max_counts = {}
    for reference in references:
        reference_counts = Counter(ngrams(reference, n)) if len(reference) >= n else Counter()
        for ngram in counts:
            max_counts[ngram] = max(max_counts.get(ngram, 0),
                                    reference_counts[ngram])

    # Assigns the intersection between hypothesis and references' counts.
    clipped_counts = {ngram: min(count, max_counts[ngram])
                      for ngram, count in counts.items()}

    numerator = sum(clipped_counts.values())
    # Ensures that denominator is minimum 1 to avoid ZeroDivisionError.
    # Usually this happens when the ngram order is > len(reference).
    denominator = max(1, sum(counts.values()))

    return Fraction(numerator, denominator, _normalize=False)
```

I hope the explanation above and the comments in the code helps =)

**Comment by weiyinfu** [comment]
I understand your idea absolutely. The problem occurs at the last sentence of the `modified_precision`.Because `modified_precision` returns a `Fraction`, the return result will lose information.
Assume that numerator=2,denominator=4,`modified_precision` will return Fraction(1,2).
When we add them together, things goes wrong.
```python
            p_i = modified_precision(references, hypothesis, i)
            p_numerators[i] += p_i.numerator
            p_denominators[i] += p_i.denominator
```
In the formulas of bleu ,I cannot see the simplification of the fraction.

**Comment by alvations** [comment]
@weiyinfu The `_normalize=False` argument would have kept the numerator and denominator as they are:

```
>>> from fractions import Fraction
>>> x = Fraction(4,10)

>>> x.numerator
2
>>> x.denominator
5

>>> x = Fraction(4,10, _normalize=False)
>>> x.numerator
4
>>> x.denominator
10

```

**Comment by weiyinfu** [comment]
Yes,you're right.This is just what I wanted. I understand .Thank you.

My NLTK version is not the newest.
```
Name: nltk
Version: 3.2
Summary: Natural Language Toolkit
Home-page: http://nltk.org/
Author: Steven Bird
Author-email: stevenbird1@gmail.com
License: Apache License, Version 2.0
Location: c:\anaconda\lib\site-packages
Requires:
```
This version is released at 3,March,2016.
The `_normalize=False` is added about two years ago.
So it's a version problem.
Thank you for your reply.
