### ISSUE TITLE
Wordnet: synset_from_sense_key returns the wrong Synset

### ISSUE THREAD

**Issue by hlumin** [nltk/nltk#2171]
https://github.com/nltk/nltk/blob/15e7f74874cf562a44747957f006cf30869a15cd/nltk/corpus/reader/wordnet.py#L1532

**Issue**: synset_from_sense_key does not always return the correct Synset.

**Example**:

```python
sense_key = 'deal%1:10:00::'

synset_from_lemma = wn.lemma_from_key(sense_key).synset()
synset_from_key = wn.synset_from_sense_key(sense_key)

print(synset_from_lemma)
print(synset_from_key)
```
outputs

```
Synset('bargain.n.01')
Synset('deal.n.09')
```
While the same Synset should be returned by both

**Source of the issue**: It seems synset_from_sense_key directly concatenates the lemma name contained in the sense key to the newly created Synset ID, while the correct synset could be using an ID with a different main lemma.

**Comment by begab** [comment]
As an additional note, the above issue can also result in a `WordNetError` being thrown in certain cases. There are 5 example sense keys to reproduce the error:
`problematic_sense_keys = 'remain%2:42:05:: put%2:31:13:: minister%2:41:12:: long%2:37:02:: aim%2:32:09::'.split()`

**Comment by zhengyaogu** [comment]
Is this bug fixed? I am trying to use this method for my project.

**Comment by HSalaberri** [comment]
Looks like this issue persists:

**Example**

`sense_key = 'leader%1:18:00::::'

synset_from_lemma = wn.lemma_from_key(sense_key).synset()
synset_from_key = wn.synset_from_sense_key(sense_key)

print(synset_from_lemma)
print(synset_from_key)`

**Output**

`Synset('leader.n.01')
Synset('drawing_card.n.02')`

Both synsets should be the same, instead, `synset_from_sense_key` returns the synset corresponding to the second sense of leader as a noun, which has sense key `leader%1:06:00::` not  `leader%1:18:00::::`.
