### ISSUE TITLE
documation issue with pos_tag

### ISSUE THREAD

**Issue by shaked210** [nltk/nltk#2177]
in the `nltk.help.upenn_tagset('PRP$')` there is a spell issue:
PRP$: pronoun, possessive
    her his mine my our ours their **thy** your

suppose to be they

**Comment by jnothman** [comment]
"they" is not possessive. "thy" is, albeit archaic.

**Comment by jnothman** [comment]
"they" becomes "their" when possessive.
"thou" becomes "thy" when possessive.

**Comment by shaked210** [comment]
You right my mistake :)
