### ISSUE TITLE
wordnet (value error)

### ISSUE THREAD

**Issue by rajarameshmamidi** [nltk/nltk#2189]
Hi All,

i am using nltk 3.3 and python 3.6 versions
i am getting valueerror when i tried below code. can some one help me to rectify this error.

![value_error](https://user-images.githubusercontent.com/42936846/48935202-d2db7f80-ef2c-11e8-8c95-2bf76363cecb.PNG)

Thanks,
raja

**Comment by purificant** [comment]
Hi @rajarameshmamidi,

The first parameter to [synset()](https://github.com/nltk/nltk/blob/1bdc1bb60867bf81db7f370a12cd21e729391777/nltk/corpus/reader/wordnet.py#L1327) should be of the form `go.v.21`, `travel.v.01`,`dog.n.01` or `'dense.s.03'`. You are seeing an error because of incorrect input. For your specific example, try `motorcar.n.1`.

Also try method `synsets`, notice the plural `s` at the end. For example:
```python
>>> from nltk.corpus import wordnet as wn
>>> wn.synsets('motorcar')
[Synset('car.n.01')]
```

**Comment by rajarameshmamidi** [comment]
Thank you purificant.... now it's working with above code.

**Comment by rajarameshmamidi** [comment]
Hi purificant,

i have a doubt on below code. i am trying to view the text from gutenberg ('chesterton-thursday.txt'). but when i run.., the output is not displaying from beginning ... and it is displaying somewhere from middle.....could you please let me know why it is happening?

import nltk
text = nltk.corpus.gutenberg.raw('chesterton-thursday.txt')
print(text)

import nltk
text = nltk.corpus.gutenberg.raw('chesterton-thursday.txt')
sents = nltk.sent_tokenize(text)
print(sents)

Thanks,
Raja

**Comment by purificant** [comment]
@rajarameshmamidi I see full text of `chesterton-thursday.txt` in both raw and sentence tokenized forms.

```python
>>> import nltk
>>> text = nltk.corpus.gutenberg.raw('chesterton-thursday.txt')
>>> len(text)
320525
```

Which is the same as 
```bash
$ wc --bytes ~/nltk_data/corpora/gutenberg/chesterton-thursday.txt 
320525 ~/nltk_data/corpora/gutenberg/chesterton-thursday.txt
```

**Comment by rajarameshmamidi** [comment]
But when i try in my IDE... it's not showing all information. i have attached the screenshot of the output.
![omitting](https://user-images.githubusercontent.com/42936846/49144631-dd7a8800-f323-11e8-8859-a989d8e5d082.PNG)

**Comment by purificant** [comment]
> But when i try in my IDE... it's not showing all information. i have attached the screenshot of the output.
> ![omitting](https://user-images.githubusercontent.com/42936846/49144631-dd7a8800-f323-11e8-8859-a989d8e5d082.PNG)

@rajarameshmamidi Truncated output is likely a feature of your IDE and not related to NLTK. I recommend you check out the documentation for the "Python Shell" in your IDE and the phrase that you've highlighted in the screenshot.

**Comment by alvations** [comment]
@rajarameshmamidi have you got all the problems resolved regarding your question? 
For more information on the `wordnet` module, please take a look at http://www.nltk.org/howto/wordnet.html 

Thanks @purificant for helping to explain the solutions! 
 
Closing this for now. Feel free to reopen if there's more issues/problems you've find with the wordnet module.
