### ISSUE TITLE
Using REPP Tokenizer on Windows

### ISSUE THREAD

**Issue by BLKSerene** [nltk/nltk#2192]
The [doc](https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software#repp-tokenizer) gives instructions for Linux and Mac users, but what about Windows?

**Comment by alvations** [comment]
Unfortunately, REPP doesn't support Windows officially. Even in Linux some distro has issue, see #1985 

Please use this instead https://github.com/delph-in/pydelphin/blob/develop/delphin/repp.py

-----

On a side note we should deprecate REPP since `pydelphin` has a full python implementation.

**Comment by BLKSerene** [comment]
Thanks a lot.
