### ISSUE TITLE
TreebankWordDetokenizer or MosesDetokenizer?

### ISSUE THREAD

**Issue by BLKSerene** [nltk/nltk#2201]
According to Issue #2000, the Moses Tokenizer has been removed out of NLTK since the incompatibility of its licence, but the docstring of nltk.tokenize.treebank.TreebankWordDetokenizer says it's a "Python port of the Moses detokenizer". (or Moses Tokenizer's adapted version of TreebankWordDetokenizer?)

```
def tokenize(self, tokens, convert_parentheses=False):
        """
        Python port of the Moses detokenizer.

        :param tokens: A list of strings, i.e. tokenized text.
        :type tokens: list(str)
        :return: str
        """
```
Should this detokenizer be also removed?

**Comment by jnothman** [comment]
AFAIK, it depends how the port was done. You can port the functionality
without violating GPL, but you can't port by looking at the code...

**Comment by alvations** [comment]
It's a typo, it's not a port from Moses. Sorry, I got lazy and copy and pasted docstring ;P

It should be quite obvious from the code that the `TreebankWordDetokenizer` had used no regexes from Moses. It's simply undoing the regexes from the `TreebankWordTokenizer.tokenize()`.

----

To be clear, no part of Moses' port / code stays in NLTK after #2000 and the `sacremoses` code is maintain separately from `nltk`. Regarding license of `sacremoses` please contact maintainer(s) on their repo issue tracker.
