### ISSUE TITLE
Include/port SyllabiPy (which includes LegaliPy) for Syllable Tokenization

### ISSUE THREAD

**Issue by no-identd** [nltk/nltk#2203]
See here for the project by @henchc:

https://github.com/henchc/syllabipy

Here for the project homepage:

http://syllabipy.com/

And here for the research paper both originate from:
https://escholarship.org/uc/item/13c6h2z2

See PDF page 44 (document page 31) for a schematic of how it works.

Incorporating this would definitely require some refactoring (throwing out util.py to make the tokenizer freely chosable, for example) and properly abstracting the current hardcoding. @Yomguithereal seems to have already done this for their port of it into their Talisman library:

https://github.com/Yomguithereal/talisman/tree/master/src/tokenizers/syllables

However, Talisman uses Javascript - otherwise I'd just suggest including most of Talisman (albeit not all, since Talisman itself uses NLTK, so that'd become a tad bit too recursive.😉) in NLTK. 😉

Both Talisman & SyllabiPy/LegaliPy use the MIT license, which should have compatibility.

**Comment by henchc** [comment]
Thanks, @no-identd , I'm happy to work on this over the next week or two. I'll refactor it best I can and make a PR, if you'd help me refine it further beyond that I'd appreciate it.

**Comment by no-identd** [comment]
Huh. Didn't expect that! Very nice! Thanks! I'll try, but unfortunately, I lack the time to definitely commit to that - I've already barely had the time to open this issue. 

Also, and I only bring up since you replied here, on a somewhat off-topic, somewhat on-topic notion, which, a suggestion:
You might want to take a look at #2202. I suspect the tokenizer I suggested there there could improve your scansion project a lot. :)

**Comment by alvations** [comment]
Should be resolving soon when #2205 is merged =)

Thanks @henchc and @no-identd !

**Comment by juliangilbey** [comment]
Hi @henchc and @alvations and @no-identd,

Is there any intention to one day incorporate LegaliPy as well?  I've just come across another library (a distant dependency of the current Spyder) which is still depending on syllabipy because of LegaliPy.

Best wishes, Julian

**Comment by henchc** [comment]
Hi @juliangilbey , I wanted to make a PR for this but never got around to it. Coincidentally, I actually have some time this week so let me see if I can get one started in the next day or so. I'll @ you on the thread.

**Comment by henchc** [comment]
Made PR here: https://github.com/nltk/nltk/pull/2652

**Comment by juliangilbey** [comment]
Thanks @henchc !

**Comment by no-identd** [comment]
@juliangilbey the PR recently got merged! Does that help with your Spyder issue?

**Comment by juliangilbey** [comment]
Hi @no-identd Sorry about ridiculously slow response - thanks so much for doing this! I'll take a look now.

**Comment by tomaarsen** [comment]
I believe this has been appropriately implemented now! I'll close this accordingly.
