### ISSUE TITLE
nltk.download() does not open graphical interface

### ISSUE THREAD

**Issue by alexisdimi** [nltk/nltk#221]
On a fresh install of 2.0.01rc4, the downloader opens in text mode instead of launching the graphical interface. I could fix the problem in nltk/downloader.py:

@@ -169,7 +169,7 @@
     from Tkinter import Tk, Frame, Label, Entry, Button, Canvas, Menu, IntVar
     from tkMessageBox import showerror
     from nltk.draw.table import Table
-    from nltk.draw import ShowText
-    from nltk.draw.util import ShowText
  except:
     TKINTER = False
     TclError = ValueError

It seems that nltk.draw used to import \* from draw.cfg, which passed along ShowText.

**Comment by sandeep-yadav-sky** [comment]
how to open downloader.py file?
