### ISSUE TITLE
nltk  affects lower() function

### ISSUE THREAD

**Issue by gocen** [nltk/nltk#2213]
When I import nltk, lower() function doesn't work fine. For example:

s="What's the best way to archive GIF's?  I zip them"
print(s.lower())

output: what's the best way to archive gIf's? I zip them

It doesn't lowercase 'I' character. Why?

**Comment by alvations** [comment]
I can't replicate the problem. 

```python
$ python3
Python 3.6.4rc1 (v3.6.4rc1:3398dcb14f, Dec  5 2017, 00:58:30) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> s = "What's the best way to archive GIF's? I zip them"
>>> s.lower()
"what's the best way to archive gif's? i zip them"
>>> import nltk
>>> s.lower()
"what's the best way to archive gif's? i zip them"
>>> nltk.__version__
'3.4'
```

Could you show the code that you've ran, so that we can try to replicate the problem? Which NLTK and Python version are you using?

**Comment by gocen** [comment]
I use python 2.7. My coding is:

`mustafa@mustafa-SVF1521ZSTB:~$` python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> s="What's the best way to archive GIF's?  I zip them"
>>> s.lower()
"what's the best way to archive gIf's?  I zip them"
>>> nltk.__version__
'3.4'`

**Comment by gocen** [comment]
`mustafa@mustafa-SVF1521ZSTB:~$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> s="What's the best way to archive GIF's?  I zip them"
>>> s.lower()
"what's the best way to archive gIf's?  I zip them"
>>> 
`

**Comment by purificant** [comment]
Not able to reproduce. In a newly created venv with nltk 3.4 installed:

```
$ python
Python 2.7.15 (default, Nov 27 2018, 13:50:28) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> s="What's the best way to archive GIF's? I zip them"
>>> s.lower()
"what's the best way to archive gif's? i zip them"
```

**Comment by gocen** [comment]
My problem still continue in python2. I don't know the reason but now I'm using python3. It's fine

**Comment by purificant** [comment]
> My problem still continue in python2. I don't know the reason but now I'm using python3. It's fine

It's a good idea to use python 3 given the ticking of https://pythonclock.org/

If we can reproduce your issue with legacy python reliably I am sure we can get it resolved, but so far we haven't been able to do that.

**Comment by gocen** [comment]
I formatted my computer. Now, python2 also works fine. I can't reproduce the problem too.

**Comment by alvations** [comment]
Thanks @purificant for verifying! 
@gocen Glad that it worked out =)
