### ISSUE TITLE
Fixing comma and colon errors in TreebankTokenizer

### ISSUE THREAD

**Issue by desilinguist** [nltk/nltk#222]
I am attaching new versions of treebank,py and tokenize.doctest that correctly handle commas and colons when followed by numbers etc. even though the sed script doesn't. I should have done a pull request but I don't have the time to do that right now. This should fix some of the last remaining errors.

**Comment by desilinguist** [comment]
Here's the fixed treebank.py and new tokenize.doctest: https://gist.github.com/1826944

**Comment by xim** [comment]
There's no rush in making the modification, we have the patience to wait for you to make a pull request :)

**Comment by desilinguist** [comment]
Alright, you win! I did the pull request :)
