### ISSUE TITLE
Treebank detokenizer parenthesis issue

### ISSUE THREAD

**Issue by Dobatymo** [nltk/nltk#2220]
Python version: Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
NLTK version: 3.4

Parentheses in the input are not correctly detokenized.

```python
from nltk.tokenize.treebank import TreebankWordTokenizer, TreebankWordDetokenizer
t = TreebankWordTokenizer()
d = TreebankWordDetokenizer()
d.detokenize(t.tokenize("Hello (world)"))
```
Output: `'Hello (world )'` (notice the space)

**Comment by ciaochiaociao** [comment]
same here
