### ISSUE TITLE
Get raw sentences

### ISSUE THREAD

**Issue by rpinquie** [nltk/nltk#2234]
How can I get a list of raw sentences from a piece of text after using sentence splitting 'ssplit' ?

**Comment by alvations** [comment]
There's no `ssplit` function in NLTK. Please do take a look at https://www.nltk.org/book/ch03.html

E.g.

```python
import nltk
from nltk import sent_tokenize

nltk.download('popular', quiet=True)

text = "This is a string with multiple sentences. Yes there are two sentences."
sent_tokenize(text)
```

**Comment by alvations** [comment]
Closing issue as resolved. Please re-open if the issue is still relevant/unresolved.
