### ISSUE TITLE
Plot methods don't return Axes object

### ISSUE THREAD

**Issue by nick-ulle** [nltk/nltk#2239]
The `.plot()` methods on `FreqDist` and `ConditionalFreqDist` currently return `None`. This makes it difficult to customize the resulting plot.

In addition, returning `None` here is counterintuitive to users coming from other scientific computing packages. As an example, Matplotlib, Pandas, and Seaborn, all typically return an `Axes` object from their plotting methods.

I propose changing the `.plot()` methods to return an `Axes` object.

**Comment by alvations** [comment]
#2240 should have fixed the plots from `nltk.probability`

But there's a few more in NLTK, for reference:

```
$ grep matplotlib nltk/**/*.py
nltk/app/__init__.py:        from matplotlib import pylab
nltk/app/__init__.py:            "nltk.app.wordfreq not loaded " "(requires the matplotlib library)."
nltk/app/wordfreq_app.py:from matplotlib import pylab
nltk/draw/dispersion.py:        from matplotlib import pylab
nltk/draw/dispersion.py:            'The plot function requires matplotlib to be installed.'
nltk/draw/dispersion.py:            'See http://matplotlib.org/'
nltk/parse/dependencygraph.py:        from matplotlib import pylab
nltk/sentiment/util.py:        import matplotlib.pyplot as plt
nltk/sentiment/util.py:            'The plot function requires matplotlib to be installed.'
nltk/sentiment/util.py:            'See http://matplotlib.org/'
nltk/tbl/demo.py:    Note: requires matplotlib
nltk/tbl/demo.py:    import matplotlib.pyplot as plt
nltk/tokenize/texttiling.py:    from matplotlib import pylab
```

**Comment by tomaarsen** [comment]
8c759729d3a1d03fd724c96c6d82c38382ef2e82 should have solved the last of these. (At least, for commonly accessed plots)
