### ISSUE TITLE
singledispatch dependency not needed for Python >= 3.4

### ISSUE THREAD

**Issue by BLKSerene** [nltk/nltk#2242]
The `singledispatch` dependency (introduced in #2077) is only used in `lm/vocabulary.py` (though I might be missing something), and it is only needed for Python 2.6 - 3.3 (it has become a part of the built-in library `functools` since 3.4), so I suppose that this dependency should be inlcuded for Python < 3.4 only in `setup.py` with `'singledispatch; python_version < "3.4"'`.

**Comment by iliakur** [comment]
I have no time these days to deal with this myself, but you're welcome to open a PR for it!!

**Comment by BLKSerene** [comment]
OK, I'll do this, open #2243.
