### ISSUE TITLE
Making dispersion_plot faster / leaner / more readable

### ISSUE THREAD

**Issue by dlukes** [nltk/nltk#2247]
I noticed that the data preparation part of `nltk.draw.dispersion_plot` does repeated passes over the data and allocates some of the intermediate results, which seems unnecessary:

https://github.com/nltk/nltk/blob/39d8eeb2f249ad67d11300d97971f972039bdc63/nltk/draw/dispersion.py#L33-L52

I also find the nested listcomp which creates the `points` and then the `list(zip(*...))` idiom hard to read, though I admit this may be subjective. But more to the point, these seem like an unnecessarily convoluted way of going about generating `x` and `y`, which are then used for plotting.

Is there any particular reason for doing it this way that I may be missing/unaware of? If not, would you be generally open to a pull request along the following lines (replacing the snippet above)?

```python
words_dict = {word.casefold() if ignore_case else word: y_i
              for y_i, word in enumerate(reversed(words))}
x, y = [], []
for x_i, token in enumerate(text):
    token = token.casefold() if ignore_case else token
    y_i = words_dict.get(token)
    if y_i is not None:
        x.append(x_i)
        y.append(y_i)
```

Using the following sample data, `%%timeit` tells me it's about 400 ms (former snippet) vs 300 ms (latter snippet), but YMMV of course :)

```python
from nltk.corpus import inaugural
text = inaugural.words()
words = ["America", "duties", "citizen", "values"]
ignore_case = False
```

**Comment by dlukes** [comment]
(I should perhaps clarify: the speedup gain is not my main motivation here, I realize it's not that big of a difference. I initially started digging around this code because I want students to tinker with it in a class setting, so that they get more comfortable reading and customizing existing code, and found the data preparation part of the function somewhat hard to read for no clear benefit to my mind. But perhaps I'm just not seeing it :) )

**Comment by stevenbird** [comment]
Probably too late for you to be useful, sorry. We always welcome pull requests and do our best to process them quickly.

**Comment by dlukes** [comment]
No worries, maybe some other time then :)
