### ISSUE TITLE
Enhancement: K means clusterer random seed initialization

### ISSUE THREAD

**Issue by tenuretech** [nltk/nltk#2248]
I would like to have the option to initialize the random seed of the K-means clusterer in an easier manner, to allow reproducibility of the results.

**Comment by okz12** [comment]
The KMeansClusterer can take a random number generator (rng) and use it for sampling. You can set the seed of the rng before passing it to the clusterer. Using Python's built-in rng:

```
rng = random.Random()
rng.seed(123)
clusterer = KMeansClusterer(num_means = 5, distance = euclidean_distance, rng = rng)
```

More information: https://www.nltk.org/_modules/nltk/cluster/kmeans.html#KMeansClusterer
