### ISSUE TITLE
text.generate

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#2251]
Look into reinstating ```text.generate()``` now that the language model package ```lm``` is available.

cf https://github.com/nltk/nltk/commit/73f7e7b9ec301c39dc11035f138a27feb3c436cf#diff-f5cb9102f911e93ca5fefa00b56a1e3f

**Comment by stevenbird** [comment]
@Copper-Head: do you have any advice here, or perhaps time to look into this please?

**Comment by iliakur** [comment]
The impression I got from skimming the old (deleted) method is that it was a wrapper around `model.generate`. Is that correct?

I'm not sure what all the trigram model checking was about, but for a starter we could maybe have `text.generate` have the same interface as `model.generate`. Does that sound reasonable? If yes, I could find time to add it.

**Comment by stevenbird** [comment]
Thanks @Copper-Head, that would be great. Yes, same interface, except ``num_words=100`` to preserve the behaviour published in the book: https://www.nltk.org/book/ch01.html#searching-text

**Comment by iliakur** [comment]
This can be closed.

**Comment by stevenbird** [comment]
Thanks Ilya
