### ISSUE TITLE
It still isn't working for me I have tried all of the above ones and yet I still get

### ISSUE THREAD

**Issue by ajaykumar-br** [nltk/nltk#2252]
It still isn't working for me I have tried all of the above ones and yet I still get 
"module 'nltk' has no attribute 'internals' "

_Originally posted by @ajaykumar-br in https://github.com/nltk/nltk/issues/1961#issuecomment-473650946_

**Comment by stevenbird** [comment]
Sorry, we do not have capacity to do more here.
