### ISSUE TITLE
How to generate alignments using MMseqs2 tool 

### ISSUE THREAD

**Issue by Akurathi** [nltk/nltk#2261]
We have seen your MMseqs2 tool in GitHub. It's really interesting. We are trying to run this tool and try to generate alignments to predict contacts using tools such as CCMpred/FreeContact. We didn't find the correct command to generate an .aln file from the dataset and protein fasta file as the input. It would be a great help if you guide us in the right way.

**Comment by alvations** [comment]
Hi @Akurathi , the [MMseqs2 ](https://github.com/soedinglab/MMseqs2) isn't maintained by NLTK. 

Perhaps @soedinglab and/or @milot-mirdita and @martin-steinegger can help you with the too =)

**Comment by martin-steinegger** [comment]
@alvations thank you!
