### ISSUE TITLE
https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

### ISSUE THREAD

**Issue by DillipNLP** [nltk/nltk#2262]
Hi All,
Hope You are doing well. 
while i am trying to download(in my office laptop) nltk download () from python prompt. its showing below error.
 a connection party didn't  properly responded after a period of time.

Can you please suggest me ... what could be possibilities issue.

Regards
Dillip

![image](https://user-images.githubusercontent.com/49390723/55719288-7da39480-5a1b-11e9-8371-8709da378b10.png)

**Comment by alvations** [comment]
@DillipNLP  Please check whether you have permissions and proxy set properly on your machine.

You might need to setup proxy, e.g. 

```python
>>> import nltk
>>> nltk.set_proxy('http://proxy.example.com:3128' ('USERNAME', 'PASSWORD'))
>>> nltk.download('popular')
```

Please refer to http://www.nltk.org/data.html for details.

P/S: Seems like you're using Firefox, you can check the proxy settings on Firefox as such: https://www.howtogeek.com/293213/how-to-configure-a-proxy-server-in-firefox/
