### ISSUE TITLE
Incorrect quotation labelling

### ISSUE THREAD

**Issue by EricWiener** [nltk/nltk#2269]
When running the following code:

```python
import nltk
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer

nltk.download('averaged_perceptron_tagger')

lemmatizer = WordNetLemmatizer()

tokens = ['is', 'the', 'other', 'equal', 'protection', 'and', 'criminal', 'do', 'you', 'set', 'forth', 'the', 'whole', 'history', 'of', 'this', 'problem', 'or', 'is', 'there', 'any', 'place', 'that', 'this', 'must', 'have', 'a', 'considerable', 'history', 'to', 'strike', 'does', 'it', 'not']

# returns list of tuples (word, tag) - penn bank style
tagTuples = nltk.pos_tag(tokens)

print(tagTuples)
```

I get the results:
```
[('is', 'VBZ'), ('the', 'DT'), ('other', 'JJ'), ('equal', 'JJ'), ('protection', 'NN'), ('and', 'CC'), ('criminal', 'JJ'), ('do', 'VBP'), ('you', 'PRP'), ('set', 'VB'), ('forth', "''"), ('the', 'DT'), ('whole', 'JJ'), ('history', 'NN'), ('of', 'IN'), ('this', 'DT'), ('problem', 'NN'), ('or', 'CC'), ('is', 'VBZ'), ('there', 'EX'), ('any', 'DT'), ('place', 'NN'), ('that', 'IN'), ('this', 'DT'), ('must', 'MD'), ('have', 'VB'), ('a', 'DT'), ('considerable', 'JJ'), ('history', 'NN'), ('to', 'TO'), ('strike', 'NN'), ('does', 'VBZ'), ('it', 'PRP'), ('not', 'RB')]
```
Note the word and tag tuple `('forth', "''")`.

'forth' in this context is being returned as a quotation mark "''". I believe this is a bug. I ran into this issue on my local computer, but just tested it out on Google Colab and recieved the same results.

**Comment by alvations** [comment]
The POS tagger is statistical, so the output depends totally on the model that it's trained on =)

The expected input to the POS tagger should be a tokenized sentence without lemmatization, since that's the dataset that it was trained on, and it relies on the context tokens (without lemmatization) to work properly, see https://www.nltk.org/_modules/nltk/tag/perceptron.html#PerceptronTagger

Do take a look at https://www.kaggle.com/alvations/basic-nlp-with-nltk

**Comment by EricWiener** [comment]
Thanks so much for the response! I'll close the issue as this isn't a bug. 

The link you shared helped a ton. I hadn't lemmatized, but I did remove punctuation from the tokens. I will make sure to leave that in. Thanks!
