### ISSUE TITLE
AttributeError: type object 'scipy.interpolate.interpnd.array' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by MariusVB** [nltk/nltk#2276]
Getting this error when importing NLTK:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-1d2184025e54> in <module>
----> 1 import nltk

~/miniconda3/lib/python3.7/site-packages/nltk/__init__.py in <module>
    127 # Import top-level functionality into top-level namespace
    128 
--> 129 from nltk.collocations import *
    130 from nltk.decorators import decorator, memoize
    131 from nltk.featstruct import *

~/miniconda3/lib/python3.7/site-packages/nltk/collocations.py in <module>
     38 from nltk.util import ngrams
     39 # these two unused imports are referenced in collocations.doctest
---> 40 from nltk.metrics import ContingencyMeasures, BigramAssocMeasures, TrigramAssocMeasures
     41 from nltk.metrics.spearman import ranks_from_scores, spearman_correlation
     42 

~/miniconda3/lib/python3.7/site-packages/nltk/metrics/__init__.py in <module>
     37 from nltk.metrics.segmentation import windowdiff, ghd, pk
     38 from nltk.metrics.agreement import AnnotationTask
---> 39 from nltk.metrics.association import (
     40     NgramAssocMeasures,
     41     BigramAssocMeasures,

~/miniconda3/lib/python3.7/site-packages/nltk/metrics/association.py in <module>
     28 
     29 try:
---> 30     from scipy.stats import fisher_exact
     31 except ImportError:
     32 

~/miniconda3/lib/python3.7/site-packages/scipy/stats/__init__.py in <module>
    365 from __future__ import division, print_function, absolute_import
    366 
--> 367 from .stats import *
    368 from .distributions import *
    369 from .morestats import *

~/miniconda3/lib/python3.7/site-packages/scipy/stats/stats.py in <module>
    171 from scipy._lib._util import _lazywhere
    172 import scipy.special as special
--> 173 from . import distributions
    174 from . import mstats_basic
    175 from ._stats_mstats_common import _find_repeats, linregress, theilslopes, siegelslopes

~/miniconda3/lib/python3.7/site-packages/scipy/stats/distributions.py in <module>
      8 from __future__ import division, print_function, absolute_import
      9 
---> 10 from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
     11                                     rv_frozen)
     12 

~/miniconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py in <module>
     14 import warnings
     15 
---> 16 from scipy.misc import doccer
     17 from ._distr_params import distcont, distdiscrete
     18 from scipy._lib._util import check_random_state

~/miniconda3/lib/python3.7/site-packages/scipy/misc/__init__.py in <module>
     66 from numpy import who as _who, source as _source, info as _info
     67 import numpy as np
---> 68 from scipy.interpolate._pade import pade as _pade
     69 from scipy.special import (comb as _comb, logsumexp as _lsm,
     70         factorial as _fact, factorial2 as _fact2, factorialk as _factk)

~/miniconda3/lib/python3.7/site-packages/scipy/interpolate/__init__.py in <module>
    173 from __future__ import division, print_function, absolute_import
    174 
--> 175 from .interpolate import *
    176 from .fitpack import *
    177 

~/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in <module>
     30 from . import _ppoly
     31 from .fitpack2 import RectBivariateSpline
---> 32 from .interpnd import _ndim_coords_from_arrays
     33 from ._bsplines import make_interp_spline, BSpline
     34 

~/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpnd.cpython-37m-x86_64-linux-gnu.so in init scipy.interpolate.interpnd()

**My setup is:**
Python version 3.7.3
NLTK version 3.4.1
Cython 0.29.7
Scipy 1.2.1

**Comment by alvations** [comment]
Did you install `scipy` before or after you install `Cython`?

Try this:

```
pip uninstall Scipy
pip install --user -U Cython --force-reinstall
pip install --user -U Scipy 
pip install --user -U nltk --force-reinstall
```

**Comment by alvations** [comment]
@MariusVB did the reinstall resolve the `scipy` vs `cython` problem?

**Comment by MariusVB** [comment]
I did not reinstall, but the problem has disappeared. Might have been after a conda update.
