### ISSUE TITLE
nltk.pos_tag EOFError on nltk 3.4/python3.7

### ISSUE THREAD

**Issue by clayscode** [nltk/nltk#2281]
Hi, Currently getting the following error when trying to use the pos_tag function in nltk version 3.4/Python3.7 running on Arch Linux. Any idea what the issue might be/how to fix it? Thanks! 

`In [7]: nltk.pos_tag(["who","are","you"])
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-7-11accc8eac78> in <module>
----> 1 nltk.pos_tag(["who","are","you"])

~/.local/lib/python3.7/site-packages/nltk/tag/__init__.py in pos_tag(tokens, tagset, lang)
    159     :rtype: list(tuple(str, str))
    160     """
--> 161     tagger = _get_tagger(lang)
    162     return _pos_tag(tokens, tagset, tagger, lang)
    163

~/.local/lib/python3.7/site-packages/nltk/tag/__init__.py in _get_tagger(lang)
    105         tagger.load(ap_russian_model_loc)
    106     else:
--> 107         tagger = PerceptronTagger()
    108     return tagger
    109

~/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py in __init__(self, load)
    144                 find('taggers/averaged_perceptron_tagger/' + PICKLE)
    145             )
--> 146             self.load(AP_MODEL_LOC)
    147
    148     def tag(self, tokens):

~/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py in load(self, loc)
    224         '''
    225
--> 226         self.model.weights, self.tagdict, self.classes = load(loc)
    227         self.model.classes = self.classes
    228

~/.local/lib/python3.7/site-packages/nltk/data.py in load(resource_url, format, cache, verbose, logic_parser, fstruct_reader, encoding)
    872     elif format == 'pickle':
    873         print(opened_resource)
--> 874         resource_val = pickle.load(opened_resource)
    875     elif format == 'json':
    876         import json

EOFError: Ran out of input
`

**Comment by clayscode** [comment]
Actually, should I raise this in nltk_data? nltk_data/taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle seems to be empty on install.

**Comment by alvations** [comment]
@clayscode Just like to check, is it because the unzipping didn't kick in when you download the dataset.

What's the output on your machine for the following code?

```python
>>> import nltk
>>> nltk.download('averaged_perceptron_tagger', force=True)
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/liling.tan/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
```

**Comment by clayscode** [comment]
`>>> import nltk`
`>>> nltk.download('averaged_perceptron_tagger',force=True)`
`[nltk_data] Downloading package averaged_perceptron_tagger to`
`[nltk_data]     /home/clay/nltk_data...`
`[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.`
`True`
`>>> nltk.pos_tag(["Who","Are","You"])`
`[('Who', 'WP'), ('Are', 'VBP'), ('You', 'PRP')]`

I feel silly now. Apologies, I thought I downloaded the tagger data, but apparently not. Thanks for the help!
