### ISSUE TITLE
Treebank detokenizer fails to undo quote conversion

### ISSUE THREAD

**Issue by Dobatymo** [nltk/nltk#2295]
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
NLTK version: 3.4.1

Quotes `"` are converted to ` `` ` or `''` by the treebank tokenizer. The detokenizer is supposed to revert its regexes but fails to do so for these quotes. The space is lost also.

```python
>>> from nltk.tokenize.treebank import TreebankWordTokenizer, TreebankWordDetokenizer
>>> tmp = TreebankWordTokenizer().tokenize('How "are" you?')
>>> tmp
['How', '``', 'are', "''", 'you', '?']
>>> TreebankWordDetokenizer().tokenize(tmp)
'How``are"you?'
```

**Comment by alvations** [comment]
Verifying bug. Yes this is particular to the detokenization of quotes. 

```python
>>> from nltk.tokenize.treebank import TreebankWordTokenizer, TreebankWordDetokenizer
>>> text = 'How "are" you?'
>>> t = TreebankWordTokenizer() 
>>> d = TreebankWordDetokenizer()
>>> t.tokenize(text)
['How', '``', 'are', "''", 'you', '?']
>>> d.detokenize(t.tokenize(text))
'How``are"you?'
>>> text = 'How are you?'
>>> d.detokenize(t.tokenize(text))
'How are you?'
```

Most probably caused by https://github.com/nltk/nltk/blob/develop/nltk/tokenize/treebank.py#L286 and https://github.com/nltk/nltk/blob/develop/nltk/tokenize/treebank.py#L335
