### ISSUE TITLE
TreebankWordTokenizer [BUG]

### ISSUE THREAD

**Issue by stefanondisponibile** [nltk/nltk#2303]
Looks like there's a broken regexp on Treebank's `PUNCTUATION` patterns:

```
([^\.])(\.)([\]\)}>"\']*)\s*$
```
should `"` be escaped?

**Comment by alvations** [comment]
Escaping the `\"` would make it more consistent in the 3rd regex group and makes it a proper regex that's consistent with PCRE. Now the PCRE (not Python) reading of the regex is different. https://regex101.com/r/0sxDUh/4 :

> 
> 3rd Capturing Group ([\]\)}>"\']*)
> Match a single character present in the list below [\]\)}>"\']*
> * Quantifier — Matches between zero and unlimited times, as many times as possible, giving back as needed (greedy)
> \] matches the character ] literally (case sensitive)
> \) matches the character ) literally (case sensitive)
> }>" matches a single character in the list }>" (case sensitive)
> \' matches the character ' literally (case sensitive)

When it should be https://regex101.com/r/0sxDUh/5 :

> 3rd Capturing Group ([\]\)}>\"\']*)
> Match a single character present in the list below [\]\)}>\"\']*
> * Quantifier — Matches between zero and unlimited times, as many times as possible, giving back as needed (greedy)
> \] matches the character ] literally (case sensitive)
> \) matches the character ) literally (case sensitive)
> }> matches a single character in the list }> (case sensitive)
> \" matches the character " literally (case sensitive)
> \' matches the character ' literally (case sensitive)



----

But the regex works as expected in Python without the escaping though =)

```python 
import re
pattern, substitute = re.compile('([^\.])(\.)([\]\)}>"\']*)\s*$'), r'\1 \2\3 '
x = pattern.sub(substitute, '"This is the end of sentence."')
print(x)

pattern, substitute = re.compile('([^\.])(\.)([\]\)}>"\']*)\s*$'), r'\1 \2\3 '
y = pattern.sub(substitute, '"This is the end of sentence."')
print(y)

print(x == y)
```

[out]:

```

"This is the end of sentence ." 
"This is the end of sentence ." 
True
```
