### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by dschaehi** [nltk/nltk#2304]
A correct documentation could be for example: Combining method 4 with the match interpolation of method 5 (cf. http://acl2014.org/acl2014/W14-33/pdf/W14-3346.pdf)

https://github.com/nltk/nltk/blob/39d8eeb2f249ad67d11300d97971f972039bdc63/nltk/translate/bleu_score.py#L635-L640

**Comment by alvations** [comment]
Thanks @dschaehi! Good catch on the documentation, that docstring is describing method 6 and copied and pasted partially.

Yes, the documentation you suggested is correct =)

> Smoothing method 7:
> Combining method 4 with the match interpolation of method 5.

**Comment by alvations** [comment]
@dschaehi if it's alright, lets keep the issue open until a pull-request is made to fix the docs =)

**Comment by dschaehi** [comment]
Sure :-)

**Comment by dschaehi** [comment]
The documentation has been changed by @stevenbird in commit 199e764, but it is still not correct. It should be methods 4 and 5

**Comment by morrme** [comment]
looks like this was corrected? 
https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L634

**Comment by dschaehi** [comment]
Yes, I can close it now.
