### ISSUE TITLE
can't load with symlink

### ISSUE THREAD

**Issue by ORESoftware** [nltk/nltk#2306]
For whatever reason this command:

```bash
export NLTK_DATA=/nltk_data
python3 -m nltk.downloader all
```

but for some reason it went into `/root/nltk_data` (it did *not* honor the env variable)

So I symlinked it:

```bash
ln -sf /root/nltk_data /nltk_data
```

but it couldn't handle the symlinks which took me a while to figure out, so I just had to do this:

```bash
cp -r /root/nltk_data /nltk_data
```

the cp is slow, but more importantly it took awhile to figure out that symlinked dir wouldn't work :(  Maybe this is a python problem.

**Comment by alvations** [comment]
@ORESoftware what is the output of these commands on your system? 

I suspect NLTK might be defaulting to $HOME directory because of directory permissions.

```
$ ls -lah /

$ ls -lah /nltk_data

$ ls -lah $HOME

$ ls -lah $HOME/nltk_data
```

**Comment by stevenbird** [comment]
Inactive; closed
