### ISSUE TITLE
Error Downloading Punkt "W/python.stderr: [nltk_data] Error loading punkt: <urlopen error [Errno 7] No address     [nltk_data]     associated with hostname>"

### ISSUE THREAD

**Issue by Jbiloki** [nltk/nltk#2308]
I am using the module chaquopy to use python on android and am trying to install nltk dependencies. Upon calling the nltk.download("punkt") I get the following error:

```
W/python.stderr: [nltk_data] Error loading punkt: <urlopen error [Errno 7] No address
    [nltk_data]     associated with hostname>
```

I was unable to find an error matching here or on stackoverflow.

**Comment by alvations** [comment]
Does your machine have internet access?

**Comment by sanket099** [comment]
Did you find the solution to this?
 if yes, can you please share it

**Comment by Emma-o** [comment]
The error occurs because there are no permissions to use the internet on the device.
Add:
   < uses-permission >
     android: name = "android.permission.INTERNET">
   </  uses-permission  >
< uses-permission >
     android: name = "android.permission.ACCESS_NETWORK_STATE">
  </  uses-permission  >
**In manifest**
