### ISSUE TITLE
wordnet morphy features with french words

### ISSUE THREAD

**Issue by Vonisoa** [nltk/nltk#2309]
Hi , I saw this from nltk wordnet documentation:

```
from nltk.corpus import wordnet as wn 
print(wn.morphy('dogs'))
```
And we get `dog`.

If I want to use this feature for french words, how should I do it?

**Comment by alvations** [comment]
Unfortunately, the morphy algorithm only works for English and there isn't a lemmatizer in NLTK. Maybe you should look for an alternative lemmatizer for French, perhaps https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer

**Comment by ekaf** [comment]
The morphy algorithm may be applied to languages that have a short list of endings, but it seems less well suited to latin languages like French, which need richer conjugation dictionaries.
So this is an open research question, which cannot be resolved here, and I suggest closing this issue.
