### ISSUE TITLE
Different bleu scores in Google colab and Jupyter notebook

### ISSUE THREAD

**Issue by sanjita-suresh** [nltk/nltk#2327]
I am trying get Bleu score for a list of 1000 English sentences and their references.
sample sentence is as below,
```
prediction_en = 'A man in an orange hat presenting something'
reference_en= 'A man in an orange hat starring at something'
```
Used code,
```
from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import SmoothingFunction
smoother = SmoothingFunction()

sentence_bleu(reference_en, prediction_en , smoothing_function=smoother.method4)
```
For this I am getting a Bleu score of ``` 0.768521``` in google colab but I am getting ``` 1.3767075064676063e-231``` score in jupyter notebook without smoothing and with smoothing ``` 0.3157039```  

Can you please help me what and where I am going wrong?

**Comment by sanjita-suresh** [comment]
This was due to different versions of nltk

**Comment by alvations** [comment]
Beyond what is implemented and whether it's the "canonical" version of BLEU that stood the "test of time" and everyone should follow. Out of curiosity, given your data, which score are you expecting?
