### ISSUE TITLE
TreebankWordDetokenizer fails to reattach comma

### ISSUE THREAD

**Issue by amadanmath** [nltk/nltk#2328]
For tokenisation, the commit https://github.com/nltk/nltk/pull/223/commits/2414f9f2d99402e64e6cb5b2b3a26df94f6b8837 introduced an exception for commas and colons, stating that a comma can be a token in its own right (insert a space before and after it) if it is not followed by a digit, presumably in order to ensure 30,000,000 and 12:59 remain a single token.

However, when _detokenisation_ was added, I don't think the reverse of that rule makes sense:

```
(
    re.compile(r'\s([:,])\s([^\d])'),
    r'\1 \2',
)  # Keep right pad after comma/colon before non-digits.
```

("Remove a space before the comma, as long as it is not followed by a space and a digit.")

If it were followed by a digit in the tokenisation, it would not have gained an intervening space: 30,000,000 remained 30,000,000, so `\s([:,])\s` already doesn't match (no need to restrict `[^\d]`).

On the other hand, if the pre-tokenised original had a comma, space and a digit, then a space would have been inserted before the comma, because the space between the comma and a digit qualified as a non-digit. However, in reverse, that space does not get deleted:

```
from nltk.tokenize.treebank import *
"From those 100, 10 were selected,"      # => 'From those 100, 10 were selected.'
TreebankWordTokenizer().tokenize(_)      # => ['From', 'those', '100', ',', '10', 'were', 'selected', '.']
TreebankWordDetokenizer().detokenize(_)  # => 'From those 100 , 10 were selected.'
```

Notice the comma not being restored to the normal position. I believe the reverse rule should simply say that if a comma is all by its lonesome, smush it with the previous token:

```
(re.compile(r'\s([:,])\s'), r'\1 ')
```

or maybe even this, in case the comma is the last token:

```
(re.compile(r'\s([:,])'), r'\1')
```

**Comment by tomaarsen** [comment]
I believe this has been resolved since:
```python
>>> from nltk.tokenize import TreebankWordDetokenizer, TreebankWordTokenizer   
>>> string = "From those 100, 10 were selected,"
>>> tokenized = TreebankWordTokenizer().tokenize(string)
>>> tokenized
['From', 'those', '100', ',', '10', 'were', 'selected', ',']
>>> TreebankWordDetokenizer().detokenize(tokenized)
'From those 100, 10 were selected,'
```
So I'll close this.
