### ISSUE TITLE
ConditionalFreqDist plot has three bugs

### ISSUE THREAD

**Issue by llr104** [nltk/nltk#2330]
`
def plot(self, *args, **kwargs):
        """
        Plot the given samples from the conditional frequency distribution.
        For a cumulative plot, specify cumulative=True.
        (Requires Matplotlib to be installed.)

        :param samples: The samples to plot
        :type samples: list
        :param title: The title for the graph
        :type title: str
        :param conditions: The conditions to plot (default is all)
        :type conditions: list
        """
        try:
            from matplotlib import plt
        except ImportError:
            raise ValueError(
                'The plot function requires matplotlib to be installed.'
                'See http://matplotlib.org/'
            )

        cumulative = _get_kwarg(kwargs, 'cumulative', False)
        percents = _get_kwarg(kwargs, 'percents', False)
        conditions = _get_kwarg(kwargs, 'conditions', sorted(self.conditions()))
        title = _get_kwarg(kwargs, 'title', '')
        samples = _get_kwarg(
            kwargs, 'samples', sorted(set(v for c in conditions
                                          if v in self
                                          for v in self[c]))
        )  # this computation could be wasted
        if "linewidth" not in kwargs:
            kwargs["linewidth"] = 2

        for condition in conditions:
            if cumulative:
                freqs = list(self[condition]._cumulative_frequencies(samples))
                ylabel = "Cumulative Counts"
                legend_loc = 'lower right'
                if percents:
                    freqs = [f / freqs[len(freqs) - 1] * 100 for f in freqs]
                    ylabel = "Cumulative Percents"
            else:
                freqs = [self[condition][sample] for sample in samples]
                ylabel = "Counts"
                legend_loc = 'upper right'
            # percents = [f * 100 for f in freqs] only in ConditionalProbDist?
            kwargs['label'] = "%s" % condition
            ax.plot(freqs, *args, **kwargs)

        ax.legend(loc=legend_loc)
        ax.grid(True, color="silver")
        ax.set_xticks(range(len(samples)), [text_type(s) for s in samples], rotation=90)

        if title:
            ax.set_title(title)
        ax.set_xlabel("Samples")
        ax.set_ylabel(ylabel)
        plt.show()

        return ax`

**must modify this:**

`
def plot(self, *args, **kwargs):
        """
        Plot the given samples from the conditional frequency distribution.
        For a cumulative plot, specify cumulative=True.
        (Requires Matplotlib to be installed.)

        :param samples: The samples to plot
        :type samples: list
        :param title: The title for the graph
        :type title: str
        :param conditions: The conditions to plot (default is all)
        :type conditions: list
        """
        try:
            import matplotlib.pyplot as plt
        except ImportError:
            raise ValueError(
                'The plot function requires matplotlib to be installed.'
                'See http://matplotlib.org/'
            )

        cumulative = _get_kwarg(kwargs, 'cumulative', False)
        percents = _get_kwarg(kwargs, 'percents', False)
        conditions = _get_kwarg(kwargs, 'conditions', sorted(self.conditions()))
        title = _get_kwarg(kwargs, 'title', '')
        samples = _get_kwarg(
            kwargs, 'samples', sorted(set(v for c in conditions
                                          if c in self
                                          for v in self[c]))
        )  # this computation could be wasted
        if "linewidth" not in kwargs:
            kwargs["linewidth"] = 2

        ax = plt.gca()
        for condition in conditions:
            if cumulative:
                freqs = list(self[condition]._cumulative_frequencies(samples))
                ylabel = "Cumulative Counts"
                legend_loc = 'lower right'
                if percents:
                    freqs = [f / freqs[len(freqs) - 1] * 100 for f in freqs]
                    ylabel = "Cumulative Percents"
            else:
                freqs = [self[condition][sample] for sample in samples]
                ylabel = "Counts"
                legend_loc = 'upper right'
            # percents = [f * 100 for f in freqs] only in ConditionalProbDist?
            kwargs['label'] = "%s" % condition
            ax.plot(freqs, *args, **kwargs)

        ax.legend(loc=legend_loc)
        ax.grid(True, color="silver")
        ax.set_xticks(range(len(samples)))
        ax.set_xticklabels([text_type(s) for s in samples], rotation=90)

        if title:
            ax.set_title(title)
        ax.set_xlabel("Samples")
        ax.set_ylabel(ylabel)
        plt.show()

        return ax`

**Comment by stevenbird** [comment]
Thanks @llr104: would you please submit a proper bug report? There is no information above.
