### ISSUE TITLE
OSError: Java command failed when using stanford parser example (Standford Tagger2018)

### ISSUE THREAD

**Issue by lacls** [nltk/nltk#2340]
Hi,

I am trying to run the stanford parser example. E.g.
`create_train_data_restaurant(fn_train, args.out_dir+args.word_idx, args.out_dir, args.StanfordPOSTag_dir, args.domain,'Train', sent_len, sent_num)`

executing the last command results with an error:

raise OSError('Java command failed : ' + str(cmd))

`OSError: Java command failed : ['/usr/bin/java', '-mx1000m', '-cp', 'stanford-postagger-full/stanford-postagger.jar', 'edu.stanford.nlp.tagger.maxent.MaxentTagger', '-model', 'stanford-postagger-full/models/english-left3words-distsim.tagger', '-textFile', '/var/folders/dm/1gjd_wh55fn_qy6bmsh17c340000gn/T/tmpess89s0u', '-tokenize', 'false', '-outputFormatOptions', 'keepEmptySentences', '-encoding', 'utf8']`

Thank you!

**Comment by alvations** [comment]
Please avoid using the `StandfordPOSTagger` object, use the `CoreNLP*` objects instead, see https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK

**Comment by lacls** [comment]
> Please avoid using the `StandfordPOSTagger` object, use the `CoreNLP*` objects instead, see https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK

Thank you a bunch!
