### ISSUE TITLE
LookupError:    NLTK was unable to find stanford-parser\.jar! Set the CLASSPATH   environment variable.

### ISSUE THREAD

**Issue by lacls** [nltk/nltk#2344]
I did follow this article for Stanford Parser:
https://gist.github.com/alvations/e1df0ba227e542955a8a 
My error code:
```
from nltk.internals import find_jars_within_path
from nltk.parse.stanford import StanfordDependencyParser
dep_parser=StanfordDependencyParser(model_path="edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz")
stanford_dir = dep_parser._classpath[0].rpartition('/')[0]
# or in windows comment the line above and uncomment the one below:
#stanford_dir = st._stanford_jar.rpartition("\\")[0]
stanford_jars = find_jars_within_path(stanford_dir)
st.stanford_jar = ':'.join(stanford_jars)
```
And I did google many topics for solving but it didn't help me at all. Thank you for your help!

**Comment by alvations** [comment]
Please avoid using the StandfordPOSTagger object, use the CoreNLP* objects instead, see https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK

The gist on https://gist.github.com/alvations/e1df0ba227e542955a8a is badly outdated, sorry about that. Please don't follow that.

**Comment by lacls** [comment]
Sweet, this gives me a good solution <3. Have a gorgeous day.
