### ISSUE TITLE
Saving a language model

### ISSUE THREAD

**Issue by anetschka** [nltk/nltk#2345]
Hi there,
I am wondering how I can save a trained language model (KneserNeyInterpolated, or anything that is derived from the base LanguageModel class), The api does not seem to exhibit a save()-function and pickling didn't work. Any hints?
Cheers,
a

**Comment by iliakur** [comment]
There's currently no functionality to save a model. When I was writing the module I didn't have time to add it.

For now, you could try saving the parts of the model, i.e. the vocabulary and the counts, then set those on an instantiated model class. Python's pretty flexible after all :)

Let me know if this is clear or if I should make an example.

**Comment by anetschka** [comment]
I close this since I figured out how this works. Sorry for bothering.

**Comment by alvations** [comment]
@Copper-Head @anetschka for that you can use Python 3.6 and/or [`dill`](https://dill.readthedocs.io/en/latest/dill.html), take a look at the example on https://www.kaggle.com/alvations/n-gram-language-model-with-nltk =)

**Comment by iliakur** [comment]
@anetschka would you mind sharing how you got it to work? I'm slammed with other stuff right now, but have carved out some time next month to do some NLTK work and it would be extremely helpful to have your stuff as a starting point.

Of course feel free to also open a PR yourself with the functionality implemented, I'll gladly review it :)

**Comment by anetschka** [comment]
@alvations Hi! Nice to see you here. I actually tried installing dill, but it won't build on Windows and since I am on a virginal machine right now, I didn't want to setup a completely new Ubuntu subsystem there. 
@Copper-Head The problem was actually with my desktop security application. It blocked Python from writing output files to my working directory. As I said, sorry for bothering. So, pickling seems to kind of work. 

BUT ... 

I trained a larg-ish fourgram model, stored it in a file and loaded it (with pickle.load()). Everything looks ok:

`model.score('Satz', ['ein']) #outputs 0.0006745536557628261`

However, when I increase context size, I get a ZeroDivisionError (picture attached). prefix_counts.N() seems to return 0. Is it incorrect usage or something else?

Best, a

![error](https://user-images.githubusercontent.com/17731067/61726785-86259e00-ad72-11e9-8d9e-2889ea1870a8.PNG)

**Comment by iliakur** [comment]
Is this KneserNeyInterpolated by any chance? If so, it might be related to #2332, which is what I'll be looking into soon.

If it's not too much work, could you send me a minimal example to reproduce this? Would help a lot with testing :)

**Comment by anetschka** [comment]
Илья, привет, yes, it's KNI. I will today see what I can get out of this in terms of debugging and verifying that the problem is related only to KNI. Will let you know if I make progres on this by updating this comment.

EDIT @Copper-Head:

Maybe I have found the bug. Analysing the code and the errors I got, it seemed to me that the smoothing classes are not instantiated properly and, therefore, calls to their properties result in errors. Something went wrong with your metaclass handling etc. I have – on my local version – changed the constructor of InterpolatedLanguageModel to the following:

![constructor](https://user-images.githubusercontent.com/17731067/61786014-2e884080-ae0d-11e9-8dec-34b13545a4b7.PNG)

This is still not very elegant. Maybe it's better to get rid of the metaclasses (if possible?) and select the smoothing method with the help of plain enums.

However, this change seems to work, I verified this using the following test script.

![testscript](https://user-images.githubusercontent.com/17731067/61786297-a8b8c500-ae0d-11e9-93b1-b1cfb8b7e18f.PNG)

ANOTHER EDIT:

Maybe what I wrote above is unnecessary, but I am not sure because sometimes I also got len(self.vocab) == 0, resulting in a division by zero exception. 

There certainly is an issue with the functions **alpha** and **gamma** in the KneserNey class. In the case of OOVs (contexts that are not recorded by the NgramCounter) we have a FreqDist with 0 samples and 0 outcomes so that `prefix_counts.N()` results in 0, throwing an exception.

The problem is aggravated by the recursive method calls that the class executes. If I enter:

`
print(model.logscore('UNK', ['UNK', 'UNK']))
`

I might at some point actually get a unigram probability for UNK, but since at first we try to retrieve counts for:

`
('UNK', 'UNK', 'UNK')
`

we will inevitably get an exception: Printing the 'context' property in **alpha_gamma** will produce:

`('UNK', 'UNK', 'UNK')`
`('UNK', 'UNK')`
`('UNK')`

Right now, I circumvented this by:

`if prefix_counts.N() == 0:`
            `return 0.0`

in **alpha** and something similar in **gamma**, but I think that this really kills the whole idea of smoothing. So the exception needs to be caught and another kind of estimation implemented for sequences of UNK.

ANOTHER EDIT: 

I have implemented some changes to my local version of the module:

1. Extended NgramCounter to return the number of higher-order (n > 1) of ngrams, since according to my understanding of KN-Smoothing this information is needed. counts.N(2) now returns the number of occurrencies for bigrams. This is how we prevent division by zero in the gamma method.
2. Changed the recursive method call in model.unmasked_score() so that only non-zero probabilities are used. This is done to avoid 0 (logscore of -inf) values in the output.

@Copper-Head Could you, please, check whether any of this makes sense? I am still not entirely sure that all this is correct, but if you approve of my proposal, I am ready to fork the repo and eventually make a pull request.

**Comment by iliakur** [comment]
Thanks for investigating this so thoroughly!

I can unfortunately only get back to you about it in several weeks as I'm in crunch-time. I've been responding so far in the hopes that the fix is easy, but your results so far suggest I'll need to put some thought into this, so I'll have to make time for that.

I have a quick question: do you replace any words with "UNK" in your training data? It's generally considered good practice to do that to words that don't occur frequently enough. Have a look at the docs for the Vocabulary class:

```python
>>> from nltk.lm import Vocabulary
>>> help(Vocabulary)
```

This should help a bit with all those zeros for unseen contexts. It will also make your model generalize a bit better and not just memorize the training data.

**Comment by iliakur** [comment]
@anetschka I believe I fixed the problem with zero division errors in #2363 . Could you confirm when you get a chance (it's in the `develop` branch, hasn't been released yet).

If it's fixed for you too and you're able to save the model, feel free to close this issue.

If you're itching to contribute to NLTK, I would be very grateful for an example of saving and loading a model in the module docstrings somewhere. Probably `__init__.py` makes the most sense.

**Comment by anetschka** [comment]
@Copper-Head  I confirm that the problem is solved. What did you change (just curious)? I can add a line on pickling the model to the docs, but I think it's easiest if you do this yourself.

**Comment by iliakur** [comment]
@anetschka take a look at this and the lines below it (comment and everything):
https://github.com/nltk/nltk/pull/2363/files#diff-5b55c076da263ed96c145ce90d6cd5f9R79

No worries re docs, I'll add an example in the next couple of months.
