### ISSUE TITLE
"kern" (v) in nltk.corpus.wordnet is antonymous to itself!

### ISSUE THREAD

**Issue by ndo3** [nltk/nltk#2350]
^ that is pretty much it. I am trying to build a graph based on wordnet's verb structure, and when I'm building antonymous relationship between antonymous words, it basically says "kern" is antonymous to "kern", which I assume is a bug based on the dictionary definitions of "kern".

Any help would be much appreciated! :)

**Comment by stevenbird** [comment]
Yes, kern.v.01 is the antonym of kern.v.02.
http://wordnetweb.princeton.edu/perl/webwn?o2=&o0=1&o8=1&o1=1&o7=1&o5=&o9=&o6=&o3=&o4=&s=kern&i=6&h=001000000#c
