### ISSUE TITLE
WordNet lemmas do not contain non-zero causes() and entailments()

### ISSUE THREAD

**Issue by ndo3** [nltk/nltk#2351]
Hey! I have been trying to look for the causes() and entailments() relationship between verbs like in the WordNet documentation by Christiane Fellbaum, but those functions return no non-empty lists given any lemma. Based on Christiane's documentation, Lemma('kill').causes() should return a list that contains at least one element, 'die'. Is this an unimplemented feature of NLTK WordNet, or is it a bug?

Thanks! :)

**Comment by ndo3** [comment]
@alvations hey! Sorry I am new to posting issues on Github/NLTK Github page haha so er am I supposed to do anything with the `pleaseverify` tag? thanks

**Comment by alvations** [comment]
@ndo3 no worries, the tag is just for any contributors, esp. the WordNet API contributors, to check if the issue raise is a bug or something else. Basically the `pleaseverify` tag is a "call to check" for other contributors, sometimes we use `goodfirstbug` too if it looks like an easy fix. 

In this case, for this issue, a good way to get faster response from fellow contributors is to show the code lines that are lacking in the code base and check the raw files from WN to see whether those relations exists.

**Comment by ekaf** [comment]
While this issue is real, it is only a particular case of issue #1970.
