### ISSUE TITLE
tqdm dependency

### ISSUE THREAD

**Issue by iliakur** [nltk/nltk#2361]
It's imported in the `util` module, but not listed in the requirements. Somehow the tox tests pass, but when I tried running the unit tests for the LM module I had to install the package to get them to run.

@alvations what am I missing?

**Comment by alvations** [comment]
Ah that must have sneaked through from https://github.com/nltk/nltk/pull/2337

The `develop` branch should have added the dependency https://github.com/nltk/nltk/blob/develop/setup.py#L107 

But you're right the requirement is missing for local tests, https://github.com/nltk/nltk/blob/develop/requirements-test.txt .

**Comment by alvations** [comment]
Seems like this is the thing breaking the CI too. Not just local tests. 

Sorry about it. Moving the imports inside the parallelization function should let the local tests pass. #2370

**Comment by stevenbird** [comment]
Thanks @alvations!
