### ISSUE TITLE
 for features, labels in training_data:       2     x.append(features)       3     y.append(label)       4 x = np.array(x).reshape(-1, IMG_SIZE, IMG_SIZE, 1)  ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by tommieezpark** [nltk/nltk#2369]
Does anyone know why I got this error while running that piece of code?

**Comment by alvations** [comment]
Thank you @tommieezpark for raising the issue. We'll need a little more information to help you with the issue. 

 - Could you post the code before the error happen? 

- Is the code coming from somewhere, e.g. the NLTK book or some examples on the web? If so, where did you get it from?

- Which version of NLTK are you using? Which Python version are you using?

- Which OS are you using to run the code snippet?
