### ISSUE TITLE
CoreNLPServer occasionally raises 'Could not connect to the server.' error even when rerunning with context manager.

### ISSUE THREAD

**Issue by kkawabat** [nltk/nltk#2372]
I am running a batch script to generate constituency parse trees for text files in a directory using CoreNLPServer:

```
from nltk.tokenize import sent_tokenize
from nltk.parse import CoreNLPParser
from nltk.parse.corenlp import CoreNLPServer

parent_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
_STANFORD_CORENLP_PATH = os.path.join(parent_path, "stanford-corenlp-full-2018-10-05")
_jars = (
    os.path.join(_STANFORD_CORENLP_PATH, "stanford-corenlp-3.9.2.jar"),
    os.path.join(_STANFORD_CORENLP_PATH, "stanford-corenlp-3.9.2-models.jar"),
)

def get_text_metrics_bulk(input_dir):
    text_metric_dict_list = []
    file_list = sorted(os.listdir(input_dir))
    with CoreNLPServer(*_jars):
        constituency_parser = CoreNLPParser()
        for i, file in enumerate(file_list):
            with open(os.path.join(input_dir, file), 'r') as ifile:
                text = ' '.join([line.strip() for line in ifile.readlines()])

            parse_trees = []
            for sentence in sent_tokenize(text):
                parse_trees.append(next(constituency_parser.raw_parse(sentence)))
return parse_trees
```

The script works fine most of the time except occasionally there would be hiccups where CoreNLP [raises 'Could not connect to the server.' error](https://github.com/nltk/nltk/blob/289f560fe4b58c25a842e4c5b1a1c820af4a840e/nltk/parse/corenlp.py#L153) This is the response I get from the coreNLP server when when I send a request: 
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=49585): Max retries exceeded with url: /live (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c3c972dd8>: Failed to establish a new connection: [Errno 111] Connection refused'))
`

When this error occurs I will have to manually kill the java process in the system monitor before I can rerun the script again. I am a bit confused because I thought using a context manager `with CoreNLPServer(*_jars):` would kill the process automatically in this situation. For now I just placed a` self.stop()` before the error raise to stop needing to automatically kill the process.

**Comment by dimazest** [comment]
That's interesting, it should stop, that's the point of the context manager.

As it seems that you process more than a handful of documents, I suggest to start CoreNLP Java process in a separate shell and point CoreNLPParser() to it.

Btw, are you running several instances of your script in parallel? `constituency_parser = CoreNLPParser()` will always connect to one, independently on what port `CoreNLPServer(*_jars)` is running.

**Comment by kkawabat** [comment]
No, I am not running it in parallel except for when this error occurs in which case I would have an extra CoreNLPServer running in the background but this would just result in the error above.  

Currently I am testing the script on a folder with just two files each with 9 sentence each so I don't think it's an issue with too many documents (maybe too many sentences?). 

Could this issue be caused by:
```
for sentence in sent_tokenize(text):
                parse_trees.append(next(constituency_parser.raw_parse(sentence)))
```
running asynchronously thus overloading the server ? I will try the seperate shell work around and see if that helps. Thanks.

**Comment by kkawabat** [comment]
I think the problem was that I was killing the script through pycharm interface and this does not trigger __exit__() for the context manager thus the server continues to run. It is not an issue with `corenlp` but with the IDE. Here is a [proposed fix](https://stackoverflow.com/questions/45199817/stopping-a-python-process-so-that-context-managers-still-call-exit-in-windo) if someone else is having this issue.
