### ISSUE TITLE
problem with pos_tag and the cardinal "zero"

### ISSUE THREAD

**Issue by behunter957** [nltk/nltk#2374]
in the following code, first sentence tagging unexpectedly tags "zero" as 'NN', second sentence tagging correctly tags "zero" as 'CD'

def preprocess(sent):
	sent = nltk.word_tokenize(sent)
	sent = nltk.pos_tag(sent)
	return sent

sentence = """my social security number is nine one three seven four four six five zero definitely."""
sent = preprocess(sentence)
print(sent)
sentence = """my social security number is nine one three seven four four six zero five definitely."""
sent = preprocess(sentence)
print(sent)

**Comment by alvations** [comment]
Yes the POS tagger in NLTK is stochastic so there won't be an easy fix to get the perfect tags most of the time. 

Maybe take a look at https://stackoverflow.com/q/30821188/610569
