### ISSUE TITLE
Breakdown edit_distance so as to see how many operations of each type are required?

### ISSUE THREAD

**Issue by Crista23** [nltk/nltk#2375]
Is it possible that in addition to getting the output of edit_distance metric to also get statistics regarding how many insertions, substitutions, deletions are required to transform string s1 into s2?

**Comment by stevenbird** [comment]
It would not be difficult to modify the code to report this. However, I don't see a strong case for providing it in NLTK.

**Comment by Crista23** [comment]
Thanks for your reply. Can you please point out what needs to be changed? Thanks!
