### ISSUE TITLE
CI instructions are out of date

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#2412]
http://www.nltk.org/dev/jenkins.html should now refer to https://www.travis-ci.org/nltk/nltk

**Comment by aditya-hari** [comment]
>The URL of our current instance is https://jenkins.shiningpanda.com/nltk/  
 
Is that what is outdated and needs to be changed?

**Comment by aditya-hari** [comment]
@stevenbird Where exactly are these changes to be made?
