### ISSUE TITLE
Automatic import of open italian book database from Liber Liber

### ISSUE THREAD

**Issue by luigiusai** [nltk/nltk#2439]
It would be really amazing if you could insert a command to automatically configure NLTK for use with a language, for instance Italian, already configured to import all the repository of italian books from Liber Liber, whose books are freely accessible to the public with no fee.
This way it would be easier for an italian to analize and learn since the very beginning, instead of having to learn a lot about the english configuration and so on.
For instance, on the python shell you type: set lang=it (this works for every language)
and NLTK already autoimport italian tokenizer, italian parser, italian books and so on.
Thank you

**Comment by stevenbird** [comment]
Out of scope, sorry
