### ISSUE TITLE
Strip Diacritics 

### ISSUE THREAD

**Issue by MohammadModallal** [nltk/nltk#2450]
I have a plain text in the Arabic language with diacritics. How to get the clean text by removing the diacritics from the input texts.
Example:
  Input  ="الْعَرَبِيةُ"
  output ="العربية"

**Comment by srhrshr** [comment]
I believe this method per https://stackoverflow.com/a/518232 should work?
```
def strip_accents(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')

>>> input ="الْعَرَبِيةُ"
>>> expected_output = "العربية"
>>> if strip_accents(input) == expected_output:
...     print("expectation = reality!")
expectation = reality!
```
