### ISSUE TITLE
nltk.metrics.distance.jaro_similarity returns lower values than it should

### ISSUE THREAD

**Issue by michael-veksler** [nltk/nltk#2459]
Jaro similarity is supposed to give the same results if the strings are reversed:

```
from nltk.metrics import distance as dist
a='rureiter'
b='enreiter'
print("regular={}, reversed={}".format(dist.jaro_similarity(a, b), dist.jaro_similarity(a[::-1], b[::-1])))
```
The code above prints `regular=0.722222222222, reversed=0.833333333333`.

In fact, manual pen-and-paper examination shows that the correct similarity metric, in both cases 
is 0.833333333333:

Separate the strings into prefix and suffix:
```
a = 'ru' + 'reiter'
b = 'en' + 'reiter'
```
The suffixes of `a` and `b` are equal. Because the suffixes are equal, and the prefixes have nothing in common between them, then the expected values are `matches == 6`  and `transpositions == 0`. With these values:

```
a = 'ru' + 'reiter'
b = 'en' + 'reiter'
matches = 6
transpositions = 0
print(
            1
            / 3
            * (
                matches / len(a)
                + matches / len(b)
                + (matches - transpositions // 2) / matches
            )
        )
```
The above code, unlike nltk, gives the correct answer of 0.8333333333333333 .

The issue lies in the fact that the current implementation does not try to minimize the number of transpositions in its algorithm, contrary to its documentation:

> The Jaro distance between is the min no. of single-character transpositions
>     required to change one word into another

The implementation simply finds the first occurrence of each character of the first string (`a`) in the second string (`b`). This order of matching does not guarantee that the match will be optimal.  In this example, the match is:
The first character of `a`  is "r", and is matched against the third character of `b`. From that point, the suffix "reiter" can't be matched in full. Worse, the next match of `a` is character "e" which is matched against the first character of `b`. This matching makes a transposition:

```
r u r e i t e r
 \  _/    
  \/    
  /\   
 /  | 
e n r e i t e r
```
Later, things get even worse. The last "e" of `a` gets matched against the middle "e" of `b`:
```
r u r e i t e r
 \  _/     /
  \/    __/
  /\   /
 /  | /
e n r e i t e r
```
This matching causes more transpositions, for no reason.

A correct Jaro algorithm should find the minimum value of transposition possible.

With `matches=6`, and `transpositions=4` the result is 0.722222222222 .

Note that `transpositions=4` because the list of matched indices of the second string is sorted, while the first is not. Before sorting:
```
flagged_1 = [0, 3, 4, 5, 6] 
flagged_2 = [2, 0, 4, 5, 3] 
```
After sorting:
```
flagged_1 = [0, 3, 4, 5, 6] 
flagged_2 = [0, 2, 3, 4, 5]  # 4 different entries
```

**Comment by anantvir** [comment]
Can you please provide some reference where it states that Jaro similarity remains the same even when strings are reversed ?
I checked multiple resources online and tried your example by hand and it seems to me that it's not necessary for Jaro distance to be same if strings are reversed.

**Comment by michael-veksler** [comment]
I agree with your comment, after finally reading the 1990 paper:
> "AN APPLICATION OF THE FELLEGI-SUNTER MODEL OF RECORD LINKAGE TO THE 1990 U.S. DECENNIAL CENSUS" by W E Winkler

For now, this paper is the closest I could get to the original Jaro paper, but it is still lacking. According to the paper it is difficult to tell if comparing equal length strings s1 and s2 should or should not give the same result as comparing reversed strings. There are other references, which only interpret the paper, that talk about getting the minimal transposition count, which lead to my assumption, but I could not verify if they are backed by the original paper.

The Wikipedia page does not describe the algorithm in a way that can be reproduced. Unfortunately, the Winkler paper is only slightly clearer, with a lot ways to interpret it. It does not quite explain how "_assigned characters_" are selected, from the pool of "_Characters in common_".  

Two things are clear:
1. The number of transpositions (**t** in Wikipedia) depends on the pairs of assigned character, like nltk implements. The unclear part is how matching characters become assigned characters. I'll try to get a copy of the Jaro paper, in order to clarify.
2. The weights of the algorithm ( 1/3 * m / len(s1) + 1/3 * m / len(s2) + 1/3 * (m - t) / m) should be parametric, individually, rather than all being hardcoded to 1/3. The paper says "For **presently matching** applications, w1, w2, and w_t are arbitrarily set to 1/3. 

**For now, I think it is safe to close this issue, unless I find a contradictory evidence in the original Jaro paper**.

**Comment by tomaarsen** [comment]
Thank you for the detailed description. Feel free to let us know if you do indeed find evidence that our jaro implementation is wrong. For now I'll heed your advice and close this issue.

**Comment by OneCoderMillionBugs** [comment]
It may be late, but anyway: in Jaro’s original work (pp. 103-108) nothing is said about reverse versions of strings or about the optimal number of transpositions. And if we manually calculate the example given in this issue, following the logic from the original work, then the answer will converge with the answer of the nltk function.

PS in case if someone is interested in reading the original work: https://books.google.com/books?id=XBmM6GzgRAwC&ots=GP85_uUMES&dq=Jaro%2C%20M.%20A.%20(1978)%2C%20%22UNIMATCH%3A%20A%20Record%20Linkage%20System%2C%20User%27s%20%20Manual%2C%22%20Washington%2C%20DC%3A%20U.S.%20Bureau%20of%20the%20Census&lr&hl=en&pg=PA103#v=onepage&q&f=false
