### ISSUE TITLE
Danish sentence tokenizer fails to split on newline

### ISSUE THREAD

**Issue by grofte** [nltk/nltk#2460]
When sentences are terminated with a newline rather than .!? the tokenizer fails to split. If it's wrong in Danish, it is probably wrong in a bunch of other languages. 

nltk version 3.4.5
Python version 3.6.9
Ubuntu Linux 18.04

```python
import nltk 
sent_tokenizer = nltk.data.load('tokenizers/punkt/danish.pickle')
text = """Den normale kropstemperatur er 37,0ºC, når den måles i endetarmen; temperaturen er lavere, når den måles i f.eks. øret eller munden
Feber defineres som kernetemperatur over 38°C målt i endetarmen
De allerfleste sygdomme med feber er harmløse og helbreder sig selv. Det gælder f.eks. forkølelser og andre virussygdomme
I nogle tilfælde kan feberen skyldes alvorlige infektioner, som f.eks. hjernehindebetændelse (meningitis), blodforgiftning (sepsis) og nyrebækkenbetændelse (pyelonefritis)
"""
print(sent_tokenizer.tokenize(text))
```

```
['Den normale kropstemperatur er 37,0ºC, når den måles i endetarmen; temperaturen er lavere, når den måles i f.eks. øret eller munden\nFeber defineres som kernetemperatur over 38°C målt i endetarmen\nDe allerfleste sygdomme med feber er harmløse og helbreder sig selv.', 'Det gælder f.eks. forkølelser og andre virussygdomme\nI nogle tilfælde kan feberen skyldes alvorlige infektioner, som f.eks. hjernehindebetændelse (meningitis), blodforgiftning (sepsis) og nyrebækkenbetændelse (pyelonefritis)']
```

**Comment by gpiat** [comment]
This is intentional, as it is common for e-mails and other such text formats to introduce line break characters mid-sentence. The accepted solution is to pre- or post- split your text into newline delimited chunks if you know that line breaks are sentence delimiters. Alternatively, you can create a class that extends `nltk.tokenize.punkt.PunktLanguageVars` and then assign an instance to `sent_tokenizer._lang_vars`.

To anyone reading: if this comment has inspired you to create the aforementioned class, I'd love to know about it, please answer in this thread if you can.

**Comment by grofte** [comment]
Okay, when I said wrong I meant that it was inconsistent with the behaviour I observed for the English version. That is how I remember it anyway.

**Comment by tomaarsen** [comment]
> 
> 
> Okay, when I said wrong I meant that it was inconsistent with the behaviour I observed for the English version. That is how I remember it anyway.

@grofte 
I'm afraid you are misremembering.
```python
import nltk
sent_tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
text = """The normal body temperature is 37.0ºC when measured in the rectum; the temperature is lower when measured in e.g. ear or mouth
Fever is defined as the core temperature above 38 ° C measured in the rectum
The vast majority of diseases with fever are harmless and heal themselves. This applies to e.g. colds and other viral diseases
In some cases, the fever may be due to serious infections, such as meningitis, sepsis and pelvic inflammatory disease (pyelonephritis) 
"""
print(sent_tokenizer.tokenize(text))
```
produces
```python
['The normal body temperature is 37.0ºC when measured in the rectum; the temperature is lower when measured in e.g.', 
'ear or mouth\nFever is defined as the core temperature above 38 ° C measured in the rectum\nThe vast majority of diseases with fever are harmless and heal themselves.', 
'This applies to e.g.',
'colds and other viral diseases\nIn some cases, the fever may be due to serious infections, such as meningitis, sepsis and pelvic inflammatory disease (pyelonephritis)']
```

Which are not split by newline.

As @gpiat mentioned, these sentences should be split beforehand or afterwards.

Note, if you're looking for a solution in NLTK itself, adding `\n` to the `sent_end_chars` in a subclass of `PunktLanguageVars`, and then passing an instance of that subclass as `lang_vars` to a `PunktSentenceTokenizer` instance does *not* work, as the regexes are seemingly not built to have a whitespace sentence end character.

**Comment by gpiat** [comment]
Line breaks have not been considered sentence delimiters [since at least 2012](https://groups.google.com/g/nltk-dev/c/2eH630nHONI?pli=1).

> adding `\n` to the `sent_end_chars` in a subclass [...] does _not_ work

Indeed, the regex [`_period_context_fmt`](https://github.com/nltk/nltk/blob/e4444c9b15762e6d86f5f6c4f5faadb87632c72a/nltk/tokenize/punkt.py#L265) basically defines the end of a sentence as a group of characters including a sentence-ending-character and punctuation or a whitespace. It implicitly does not support single-character sentence delimiters.

**Comment by grofte** [comment]
I am embarrassed by how poorly I reported this issue. And I found out why I got the expected number of lines with English. I used the Danish text which has the abbreviation "f.eks." multiple times. And it split on those. 

But I learnt something about sentence splitting. Thank you very much everyone (and writing better issues but I swear I am much better at that now than I was in Nov 2019).

**Comment by stevenbird** [comment]
(FYI part of the design of Punkt and probably other sentence segmenters is to treat the task as a classification problem, to make a binary judgement as to whether any instance of [.?!] is sentence-ending.)
