### ISSUE TITLE
jaccard_distance does not match the data formula

### ISSUE THREAD

**Issue by liubo12** [nltk/nltk#2475]
from nltk.metrics.distance import jaccard_distance
I think the jaccard_distance  does not match the data formula, the jaccard_distance might be:

    return len(label1.intersection(label2)) / len(
        label1.union(label2)
    )

but the source code is :

    return (len(label1.union(label2)) - len(label1.intersection(label2))) / len(
        label1.union(label2)
    )

**Comment by jnothman** [comment]
Jaccard distance is the complement of jaccard similarity

**Comment by acharles7** [comment]
`jaccard_distance = 1 - jaccard_similarity`

**Comment by tomaarsen** [comment]
I believe this has been resolved. I'll close it.
