### ISSUE TITLE
POS tagger crashes when text starts with a white space.

### ISSUE THREAD

**Issue by jeromemassot** [nltk/nltk#2483]
Dear NLTK team,

the POS parsing crashes when the text starts with one (or several) white space(s). The problem occurs in the normalize() call.

/usr/local/lib/python3.6/dist-packages/nltk/tag/perceptron.py in normalize(self, word)
    238         elif word.isdigit() and len(word) == 4:
    239             return '!YEAR'
--> 240         elif word[0].isdigit():
    241             return '!DIGITS'
    242         else:

IndexError: string index out of range

I guess that testing the length() of the word could solve the issue.
lstriping the input text is not a correct one, as for many reasons, the text has to be preserved untouched by ntlk.

Best regards

Jerome

**Comment by maayanorner** [comment]
Hey, I do not see a unit tests for it, where should it be implemented? It seems to me that the most logical location is unit/test_tag.py but I am not familiar enough with the project yet.

**Comment by fievelk** [comment]
This can be reproduced, for example, with the following code:
```python
from nltk.tag.perceptron import PerceptronTagger

tagger = PerceptronTagger(load=False)
[tagger.normalize(w) for w in ['', 'is', 'a', 'beautiful', 'day']]
```

The code above produces the following output:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-29-a7ae37b09fb1> in <module>
----> 1 [tagger.normalize(w) for w in ['', 'is', 'a', 'beautiful', 'day']]

<ipython-input-29-a7ae37b09fb1> in <listcomp>(.0)
----> 1 [tagger.normalize(w) for w in ['', 'is', 'a', 'beautiful', 'day']]

nltk/nltk/tag/perceptron.py in normalize(self, word)
    278         elif word.isdigit() and len(word) == 4:
    279             return "!YEAR"
--> 280         elif word[0].isdigit():
    281             return "!DIGITS"
    282         else:

IndexError: string index out of range
```

Hi @jeromemassot . What kind of result would you expect from the `normalize` method on an empty string? Could you please provide some examples?
