### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by thalesmello** [nltk/nltk#2490]
I'm looking forward to upgrade my Python to 3.8, and I was expecting to see the bug fixes mentioned in #2359 .

However those are currently only available in master.

Any plan to upgrade the package available in PyPI?

**Comment by stevenbird** [comment]
We're waiting for this: https://github.com/nltk/nltk/pull/2432

**Comment by stevenbird** [comment]
3.5b1 is released, supporting Python 3.8
