### ISSUE TITLE
Reading a CFG from string with escaped single and double quotes in terminals results in failure

### ISSUE THREAD

**Issue by sajal2692** [nltk/nltk#2491]
As mentioned in the topic title, reading a grammar string which contains productions with escaped single and/or double quotes in the terminals on the RHS results in different ValueErrors.

Example A:
The following code:
```
grammar = CFG.fromstring("""
            S -> A
            A -> 'manager\'s, discount'
            """)
```
raises:
```
   raise ValueError('Expected a nonterminal, found: ' + string[pos:])
ValueError: Expected a nonterminal, found: , discount'
```

Example B:
The following code:
```
grammar = CFG.fromstring("""
            S -> A
            A -> "\"manager\'s discount\""
            """)
```
raises:
```
    raise ValueError('Unterminated string')
ValueError: Unterminated string
```

The reason for this is as follows:
The regex pattern `_TERMINAL_RE = re.compile(r'( "[^"]+" | \'[^\']+\' ) \s*', re.VERBOSE)` used by the helper function `def _read_production` in https://www.nltk.org/_modules/nltk/grammar.html does not account for escaped single or double quote characters.

Proposed solution:
For the case when a terminal is enclosed with single quotes, modifying the regex to ` r'( "[^"]+" | \'([^\']|[\\\'])+\' ) \s*'` should enable it to account for escaped single quotes. Something similar can be done for the case with double quotes in the regex.

**Comment by sajal2692** [comment]
Update: It seems like the regex in the proposed solution is incorrect. 

A possible solution is to a word boundary assertion as: `r'( "[^"]+" | \'([^\']|[\\\']\b)+\' ) \s*'`, though this also needs more testing. I'll get back here if I can figure something out.

**Comment by sajal2692** [comment]
Update: The following regex seems to cover both cases: 
` _TERMINAL_REGEX = re.compile(r"(([\"\']) (?:\\\2|.)+?\2) \s*", re.VERBOSE)`

**Comment by tomaarsen** [comment]
The real reason that 
```python
string_cfg = """
    S -> A
    A -> 'manager\'s, discount'
"""
CFG.fromstring(string_cfg)
```
fails is because Python absorbs the `\` itself:
```python
>>> print(repr(string_cfg))
"\n    S -> A\n    A -> 'manager's discount'\n"
```
Note the lack of `\` before the `'`. It is absorbed because it is not needed according to Python.
Your first two suggested regexes do work, but only because they greedily match `'manager's discount'`, while the current and last regex (correctly) only match `'manager'`.

So the problem here is actually that Python converts `'manager\'s discount'` to `'manager's discount'`, at which point the program rightfully complains.

This is not to say that there is some unsolvable issue here. It's just not a bug that nltk should fix. Instead, it is (perhaps) unexpected behaviour by Python. I suggest using one of the following strings instead, which work correctly:
```python
grammar = CFG.fromstring("""
    S -> A
    A -> "manager's discount"
""")
```
or
```python
grammar = CFG.fromstring("""
    S -> A
    A -> "manager\'s discount"
""")
```
or
```python
grammar = CFG.fromstring("""
    S -> A
    A -> \"manager\'s discount\"
""")
```
If it were up to me, this issue could be closed.

- Tom Aarsen

---

(Here's a sample program I used for testing, if you're interested)
```python
from nltk.grammar import CFG

def get_grammar(cfg):
    print("String CFG:")
    print(repr(cfg))
    grammar = CFG.fromstring(cfg)
    print("Read grammar:")
    print(grammar, "\n" * 3)

# The first three work, the last one fails. As is the expected result.
get_grammar("""
    S -> A
    A -> "manager's discount"
""")

get_grammar("""
    S -> A
    A -> "manager\'s discount"
""")

get_grammar("""
    S -> A
    A -> \"manager\'s discount\"
""")

get_grammar("""
    S -> A
    A -> 'manager\'s discount'
""")
```

Which outputs:
```
String CFG:
'\n    S -> A\n    A -> "manager\'s discount"\n'
Read grammar:
Grammar with 2 productions (start state = S)
    S -> A
    A -> "manager's discount"



String CFG:
'\n    S -> A\n    A -> "manager\'s discount"\n'
Read grammar:
Grammar with 2 productions (start state = S)
    S -> A
    A -> "manager's discount"



String CFG:
'\n    S -> A\n    A -> "manager\'s discount"\n'
Read grammar:
Grammar with 2 productions (start state = S)
    S -> A
    A -> "manager's discount"



String CFG:
"\n    S -> A\n    A -> 'manager's discount'\n"
Traceback (most recent call last):
  File "[removed]\nltk\nltk\grammar.py", line 1449, in read_grammar
    productions += _read_production(line, nonterm_parser, probabilistic)
  File "[removed]\nltk\nltk\grammar.py", line 1375, in _read_production
    raise ValueError("Unterminated string")
ValueError: Unterminated string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[removed]/nltk/nltk_2491.py", line 30, in <module>
    """)
  File "[removed]/nltk/nltk_2491.py", line 8, in get_grammar
    grammar = CFG.fromstring(cfg)
  File "[removed]\nltk\nltk\grammar.py", line 558, in fromstring
    input, standard_nonterm_parser, encoding=encoding
  File "[removed]\nltk\nltk\grammar.py", line 1452, in read_grammar
    (linenum + 1, line, e)) from e
ValueError: Unable to parse line 3: A -> 'manager's discount'
Unterminated string
```
