### ISSUE TITLE
Clarify author, copyright and license on stopword corpus and fix link

### ISSUE THREAD

**Issue by fnielsen** [nltk/nltk#2501]
Looking at https://www.nltk.org/nltk_data/ I see that the Stopwords Corpus as no specified author, copyright or license and the download link is no longer working.

I am wondering whether author, copyright or license could be specified as it would be interesting to include such data in Wikidata. Wikidata is Creative Commons Zero, so if there is any "non-zero" CC license it will not work.

In case it is CC0, I am wondering whether the individual lists are frozen or version changes might happen.

**Comment by stevenbird** [comment]
I'm sorry, these lists come from diverse sources, including old sources with no author, copyright, or license. There's no obvious way to clarify this now I'm afraid.
