### ISSUE TITLE
'schools' is not stemmed to 'school' by Lancaster stemmer

### ISSUE THREAD

**Issue by psranga** [nltk/nltk#251]
The root cause seems to be that the __isAcceptable() in lancaster.py requires either the second or third letter to be vowel if the first letter is a consonant.

'sch' breaks this rule.  This also prevent words like 'scholastic', 'schooners', 'schooling' etc from being stemmed.

I made a tiny edit to treat 'sch' as a special case (since 'sch' is a single sound (phoneme?)).

Works for me. I'll let the Powers That Be decide if this should make it to the world at large.

lines 290 and 291 below are what I added. The length check with -2 is to treat 'sch' as equivalent to one letter.

274     def __isAcceptable(self, word, remove_total):
275         """Determine if the word is acceptable for stemming.
276         """
277         word_is_acceptable = False
278         # If the word starts with a vowel, it must be at least 2
279         # characters long to be stemmed
280         if word[0] in "aeiouy":
281             if (len(word) - remove_total >= 2):
282                 word_is_acceptable = True
283         # If the word starts with a consonant, it must be at least 3
284         # characters long (including one vowel) to be stemmed
285         elif (len(word) - remove_total >= 3):
286             if word[1] in "aeiouy":
287                 word_is_acceptable = True
288             elif word[2] in "aeiouy":
289                 word_is_acceptable = True
290             elif (word[0:3] == 'sch') and ((len(word) - 2) - remove_total >= 3):
291                 word_is_acceptable = True
292         return word_is_acceptable

**Comment by stevenbird** [comment]
Can you demonstrate that this is an error in our port of the Lancaster Stemmer?  The NLTK implementation should be faithful to the original, even it if has errors.  If the port is faithful, then the known errors can be listed in the documentation for the stemmer (i.e. by updating its docstring).

**Comment by psranga** [comment]
Hi Steven: Good points.

This seems to be a problem with the port. The Perl and Java versions linked at http://www.comp.lancs.ac.uk/computing/research/stemming/Links/implementations.htm both produce 'school' for schools.

**Comment by stevenbird** [comment]
Thanks.  I invite a patch that brings the NLTK port (more) into line with the original code.  I.e. no hacks -- a third party should have an easier time seeing the correspondence between the original and the port.

**Comment by psranga** [comment]
Hi steven: Based on my cursory examination of the perl port, the python program is implementing the __isAcceptable function the same as the python version. The diff is probably elsewhere.

I don't have time at present to look into this in more detail. I am closing this issue for now. Will send a patch if I figure it out.

**Comment by psranga** [comment]
Hi steven: Based on my cursory examination of the perl port, the python program is implementing the __isAcceptable function the same as the python version. The diff is probably elsewhere.

I don't have time at present to look into this in more detail. I am closing this issue for now. Will send a patch if I figure it out.

**Comment by psranga** [comment]
Hi steven: Based on my cursory examination of the perl port, the python program is implementing the __isAcceptable function the same as the python version. The diff is probably elsewhere.

I don't have time at present to look into this in more detail. You can close this issue for now. Will send a patch if I figure it out.

**Comment by psranga** [comment]
Hi steven: Based on my cursory examination of the perl port, the python program is implementing the __isAcceptable function the same as the python version. The diff is probably elsewhere.

I don't have time at present to look into this in more detail. You can close this issue for now. Will send a patch if I figure it out.
