### ISSUE TITLE
https://nltk.org SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by jayvdb** [nltk/nltk#2516]
https://nltk.org (https) is a redirect to https://www.nltk.org/ , however it shows a cert error.

The cert is only valid for "shortener.secureserver.net, www.shortener.secureserver.net"

**Comment by tomaarsen** [comment]
I believe the former doesn't work anymore? Regardless, no cert errors to be found anymore. I'll close this.
