### ISSUE TITLE
Difficulty installing NLTK

### ISSUE THREAD

**Issue by sophiamelanson** [nltk/nltk#2518]
Hello,

I keep getting this error when I attempt to intall NLTK:

![NLTK](https://user-images.githubusercontent.com/62572582/77363845-d3a34200-6d29-11ea-9afb-0625aa67b652.png)

What do I do to resolve this problem?

Thanks very much,
Sophia

**Comment by stevenbird** [comment]
Please see the installation instructions:
https://www.nltk.org/install.html
