### ISSUE TITLE
install NLTK 

### ISSUE THREAD

**Issue by Hanadyma** [nltk/nltk#2525]
Last login: Sat Apr  4 17:02:21 on ttys000
hanadys-mbp:~ hanadyahmed$ import nltk
-bash: import: command not found
hanadys-mbp:~ hanadyahmed$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named nltk
>>>

**Comment by Hanadyma** [comment]
What is the problem pls?

**Comment by Hanadyma** [comment]
why could not import nltk?

**Comment by fievelk** [comment]
Hi @Hanadyma . Did you follow the instructions on [Installing NLTK](https://www.nltk.org/install.html)?

From the instructions:
> NLTK requires Python versions 3.5, 3.6, 3.7, or 3.8

while you seem to be trying to import the package on Python 2.7.

**Comment by Hanadyma** [comment]
Thank you so much , I think I installed Python 3.8. I will check it again.
Thank you so much
My best
Hanady
