### ISSUE TITLE
Import NLTK error in Python2.7

### ISSUE THREAD

**Issue by baskarmac** [nltk/nltk#2534]
I have Installed NLTK and when i try to import it is throwing the below error

import NLTK

File "/jupyter/local/lib/python2.7/site-packages/nltk/probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
                                          ^
SyntaxError: invalid syntax

Collecting nltk
Requirement already satisfied: joblib in /jupyter/lib/python2.7/site-packages (from nltk) (0.14.1)
Requirement already satisfied: click in /jupyter/lib/python2.7/site-packages (from nltk) (7.1.1)
Requirement already satisfied: tqdm in /jupyter/lib/python2.7/site-packages (from nltk) (4.45.0)
Requirement already satisfied: regex in /jupyter/lib/python2.7/site-packages (from nltk) (2020.4.4)
Installing collected packages: nltk
Successfully installed nltk-3.5
You are using pip version 10.0.0b2, however version 20.1b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  File "/jupyter/local/lib/python2.7/site-packages/nltk/probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
                                          ^
SyntaxError: invalid syntax

Please help.

**Comment by andycee** [comment]
Same here

**Comment by stevenbird** [comment]
Python 2.7 is no longer supported.

**Comment by samuelpetroline** [comment]
Is there any way to make it work with 2.7? Any version that still suports it?

**Comment by alvations** [comment]
You can try `pip install nltk==3.4.5` or versions before https://pypi.org/project/nltk/#history
