### ISSUE TITLE
Why does TreebankWordDetokenizer() work in console but not when called from a script?

### ISSUE THREAD

**Issue by bikegirl** [nltk/nltk#2535]
Recreating the error:
`python3`
`import nltk`
`from nltk.tokenize.treebank import TreebankWordDetokenizer`

I call a script called hpff_hpcanon_analysis.py and point_mutual_info.py that have these three imports at the top of the .py file and I get the following error:
<img width="905" alt="tbdetok1" src="https://user-images.githubusercontent.com/31639520/80567452-d34a3680-89ba-11ea-8d47-e72b41d1fedd.png">
<img width="718" alt="tbdetok2" src="https://user-images.githubusercontent.com/31639520/80567650-3fc53580-89bb-11ea-911d-59072a831022.png">

If I work in the terminal I can use the TreebankWordDetokenizer tool.  But if I call a script with this import at the top of the file it gives an import error `ImportError: cannot import name 'TreebankWordDetokenizer'`

I have used `pip install -U nltk` to update nltk and all requirements satisfied.  Any insight is much appreciated.

**Comment by stevenbird** [comment]
Strange! I wonder if your terminal vs your script pick up a different version of python, with different versions of NLTK installed?

**Comment by bikegirl** [comment]
Yes!  I forgot to update this.  When I'm in the console I work within an virtenv that has all the packages I need, but when I run the shell script on our servers I forget that it's self contained, it uses whatever the default python it has with whatevers been installed (which is nothing b/c we're not allowed to install anything on the servers hence me working in a virtenv).  So I ended up adding `source <virtenv_name>/bin/activate` to the top of the shell script and now I can use the treebank tokenizer woo hoo!
