### ISSUE TITLE
UnigramTagger cutoff documentation

### ISSUE THREAD

**Issue by r-r-r** [nltk/nltk#254]
The UnigramTagger documentation suggests that only values with less than cutoff are ignored however values less than equal are.

**Comment by xim** [comment]
http://nltk.github.com/_modules/nltk/tag/sequential.html#ContextTagger

Documentation and code comments say «Only include contexts that we've seen at least **cutoff** times» – the code, however (in _train), includes contexts if `hits > cutoff`.

I guess this should be `hits >= cutoff` according to the doc (if I'm not just reading the code wrong?)

Should we change the doc or the code? Changing the code is easier, but potentially changes results from the taggers...
