### ISSUE TITLE
Contraction does not work for the word 'ill' and wrongly converting it into 'I will'

### ISSUE THREAD

**Issue by vsaifi** [nltk/nltk#2552]
Input: He is to step down at the end of the week due to **ill** health
Output: He is to step down at the end of the week due to **I will** health

Have a look at below sample code:

#!pip install contractions
import contractions

text = He is to step down at the end of the week due to ill health
contractions.fix(text)
print(text)

> He is to step down at the end of the week due to I will health

**Comment by iliakur** [comment]
@vsaifi could you please explain why you aren't opening this issue in [the contractions](https://github.com/kootenpv/contractions) package?

**Comment by vsaifi** [comment]
@iliakur Thanks for the link, it my bad. I'm going to issue it over there

**Comment by iliakur** [comment]
No problem, glad to help :) Don't forget to close this issue ;)

**Comment by vsaifi** [comment]
Closing the issue as it belongs to contractions library, and so should be logged in the [contractions](https://github.com/kootenpv/contractions) package.
