### ISSUE TITLE
WordNet: Loop in hyponyms hierarchy

### ISSUE THREAD

**Issue by GiovanniGabbolini** [nltk/nltk#2565]
Hello,

navigating the hierarchy of hyponyms I end up in a loop:

```
>>> from nltk.corpus import wordnet as wn
>>> synset=wn.synset('restrain.v.01'); print(synset)
Synset('restrain.v.01')
>>> synset=synset.hyponyms()[3]; print(synset)
Synset('inhibit.v.04')
>>> synset=synset.hyponyms()[2]; print(synset)
Synset('restrain.v.01')
>>> synset=synset.hyponyms()[3]; print(synset)
Synset('inhibit.v.04')
>>> synset=synset.hyponyms()[2]; print(synset)
Synset('restrain.v.01')
....
```

Is this meant to be?

nltk Version: 3.4.5 on Python 3.7

Giovanni

**Comment by ekaf** [comment]
Issue #2314 includes fixes for the same problem in the "tree" and "closure" functions,.But the present issue  is different, because it is about manual navigation in the hyponyms(), one level at a time, so it can only  be fixed by patching the WordNet database.
