### ISSUE TITLE
Calling LancasterStemmer with language causes "ValueError: The rule e is invalid"

### ISSUE THREAD

**Issue by forgetso** [nltk/nltk#2569]
As LancasterStemmer inherits from StemmerI, it is possible to call it with a language as so:

`ls = LancasterStemmer('english')`

This causes the following ValueError:

```
ne 218, in stem
    self.parseRules()
  File "/home/user/anaconda3/envs/uniqueness/lib/python3.8/site-packages/nltk/stem/lancaster.py", line 199, in parseRules
    raise ValueError("The rule {0} is invalid".format(rule))
ValueError: The rule e is invalid

```
This is because the rule tuple is passed in from the parent class and the rules do not fit the valid_rule regex on line 192.

`        valid_rule = re.compile("^[a-z]+\*?\d[a-z]*[>\.]?$")
`

A workaround is to call the stemmer without setting the language.

`ls = LancasterStemmer()`

**Comment by dannysepler** [comment]
hi, @forgetso! i'm a newbie contributor to nltk, lookin for a fun issue to get crackin on. out of curiosity, i was looking at the statement `As LancasterStemmer inherits from StemmerI, it is possible to call it with a language as so` -- are you sure about this? `StemmerI` has no `__init__` constructor of its own, and only the `SnowballStemmer` child class has "language" as a positional argument in its constructor

I think the behavior seems ... I guess expected? The first kwarg to the SnowballStemmer is `rule_tuple`, so it seems that the Stemmer interpreted "english" as a "rule_tuple" which corresponds to the ValueError that you posted

**Comment by forgetso** [comment]
Hi Danny, that makes sense. I guess this can be closed.
