### ISSUE TITLE
Hack to keep NLTK's "tokenize" module fails 

### ISSUE THREAD

**Issue by amirdaaee** [nltk/nltk#2573]
in decorators.py file line 24:
`sys.path = [p for p in sys.path if  "nltk" not in p]`
causes an error while importing nltk when there are other objects than strings in the path variable(such as pathlib.Posixpath)
this issue can be solved simply just by replacing the above code with:
`sys.path = [p for p in sys.path if (type(p) == str and "nltk" not in p)]`

**Comment by iliakur** [comment]
Perhaps simpler to read:

```python
[p for p in sys.path if "nltk" not in str(p)]
```
