### ISSUE TITLE
Cannot import all translation modules

### ISSUE THREAD

**Issue by weissercn** [nltk/nltk#2584]
Some submodules under translate are implemented and described in the documentation, but cannot be imported and used. 

import nltk
nltk.translate.gleu_score.corpus_gleu

fails with this error:
AttributeError: module 'nltk.translate' has no attribute 'gleu_score'

**Comment by weissercn** [comment]
I proposed a fix user pull request #2585

**Comment by mohammedayub44** [comment]
I get the same error. Guess this has not been released yet.

**Comment by tomaarsen** [comment]
This works now. If I run the following snippet:
```python
import nltk
nltk.translate.gleu_score.corpus_gleu()
```
Then the output I get is:
```python
TypeError: corpus_gleu() missing 2 required positional arguments: 'list_of_references' and 'hypotheses'
```
In short, you can use the function like this.

---

However, it's probably recommended to use something like this:
```python
from nltk.translate.gleu_score import corpus_gleu, sentence_gleu
```

Alternatively, you can import the `sentence_gleu` alias using either:
```python
from nltk.translate import gleu
```
or
```python
from nltk import gleu
```
In both of these cases, `gleu` is an alias for `sentence_gleu` from `nltk/translate/gleu_score.py`.

I'll close this as it seems to be resolved now.

- Tom Aarsen
