### ISSUE TITLE
TreebankTokenizer test failures

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#259]
Currently TreebankTokenizer tests are failing:

```
File "/Users/kmike/svn/nltk/nltk/tokenize/treebank.py", line 38, in nltk.tokenize.treebank.TreebankWordTokenizer
Failed example:
    TreebankWordTokenizer().tokenize(s)
Expected:
    ['Good', 'muffins', 'cost', '$', '3.88', 'in', 'New', 'York.',
    'Please', 'buy', 'me', 'two', 'of', 'them', '.', 'Thanks', '.']
Got:
    ['Good', 'muffins', 'cost', '$', '3.88', 'in', 'New', 'York.', 'Please', 'buy', 'me', 'two', 'of', 'them.', 'Thanks', '.']
```

That's because "them.". 
There are 2 ways to fix this issue:

a) update test and remove "The only periods to be treated as separate tokens are those appearing at the end of a line." comment from a docstring.

b) partially restore old behavior (see https://github.com/kmike/nltk/commit/c2e6c551d6db1c1a9d4416906aa06d89a743961f)

I have absolutely no idea what is better and what is the intended behavior. (b) is implemented in the commit above.

**Comment by stevenbird** [comment]
I've updated the docstring to reflect current behaviour, in https://github.com/nltk/nltk/commit/e051f7f61517ddf551e3a04203255b496d899cc6
