### ISSUE TITLE
Move from nose to pytest or nose2

### ISSUE THREAD

**Issue by dannysepler** [nltk/nltk#2590]
https://nose.readthedocs.io/en/latest/ -- nose is on life support. I personally prefer pytest, but nose2 may also be considered. Has this been discussed very much yet?

**Comment by iliakur** [comment]
I've been wanting to propose switching to pytest, but I was hesitant to rip the rug from under the feet of people used to the older setup just for the sake of my convenience.

However, this situation with nose EOL may be a good excuse to take the leap. +1 from me.
