### ISSUE TITLE
Unigram scores incorrectly computed for Kneser-Ney smoothing causing high perplexities 

### ISSUE THREAD

**Issue by osmanio2** [nltk/nltk#2599]
The unigram scores in KneserNey smoothing introduced in this commit https://github.com/nltk/nltk/commit/2759b03d85983fedd29b646380c713c3f4ccff66 are computed as a uniform distribution over the vocabulary, which is clearly not how any variant of KneserNey computes it. 

https://github.com/nltk/nltk/blob/5023d6b933ef1a5b1f25fba1d5ed11a8a43a47e4/nltk/lm/smoothing.py#L47

**Comment by iliakur** [comment]
Hi @osmanio2, thanks for raising this!

When I implemented the interpolated smoothing I referenced the Chen & Goodman 1995 paper. If I understood the [kenlm paper](https://www.aclweb.org/anthology/P13-2121.pdf) correctly, they also represent the unigram distribution as uniform over the vocabulary.

However, I'm afraid I haven't had time to keep up with the state of the art on this front. Could you share some references that I can take a look at to get an updated understanding?

**Comment by osmanio2** [comment]
@iliakur  Thank you for replying. There are many different implementation when it comes to approximating unigram distributions:
- https://nlp.stanford.edu/~wcmac/papers/20050421-smoothing-tutorial.pdf
- http://www.foldl.me/2014/kneser-ney-smoothing/
- https://en.wikipedia.org/wiki/Kneser%E2%80%93Ney_smoothing

However, the current code **does not follow** the implementation in the [kenlm paper](https://www.aclweb.org/anthology/P13-2121.pdf) because here: https://github.com/nltk/nltk/blob/ca357e5cdcdb137f40c45346bb8bfea618dd863f/nltk/lm/models.py#L76-L78
that calls the unigram scores which is just `1.0 / len(self.vocab)`, whereas the paper interpolates between a unigram distribution and a uniform distribution.

**Comment by iliakur** [comment]
Thanks for the links! After a quick skim I wasn't able to find anything about how they compute unigram scores when there's really no preceding context present, all of them talk about replacing raw unigram probabilities with *continuation probabilities* (the hallmark of Kneser-Ney), but none talk about the base recursive case.

However, I was able to find the place in the kenlm paper where they explicitly show that they're interpolating unigram scores with the uniform distribution over vocabulary, that convinces me that we should change the implementation.

Would you have time/interest to tackle it? No problem if not, I've accumulated a bit of a backlog of things to fix up in the code, so will likely dive into it soon.
