### ISSUE TITLE
Tagset documentation

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#26]
Make sure each tagged corpus has its tagset documented in its README file.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=45</p>

**Comment by paulproteus** [comment]
Hey @alexrudnick , can you clarify: would this mean adding more docs to e.g. "nltk.help.brown_tagset"?

**Comment by alvations** [comment]
The `nltk.help` includes documentation of the tagsets.

``` python
>>> import nltk.help
>>> nltk.help.brown_tagset()
>>> nltk.help.claws5_tagset()
>>> nltk.help.upenn_tagset()
```

@paulproteus, I think [@alexrudnick was referring to adding the tagset information to the corpora themselves](https://web.archive.org/web/20101224062054/http://code.google.com/p/nltk/issues/detail?id=45), possibly something like this (that is not implemented yet).

``` python
>>> from nltk.corpus import brown
>>> brown.tagset() # which will print `nltk.help.brown_tagset()`
```

@stevenbird is there a list of corpora in NLTK sorted by which annotations they have?

**Comment by stevenbird** [comment]
@alvations: no, there's no such list unfortunately.

**Comment by stevenbird** [comment]
This is a great idea but we don't have resources to do it anytime soon, so I'm closing it.
