### ISSUE TITLE
Link to "Whoosh" library in AUTHORS.md throws 404

### ISSUE THREAD

**Issue by tomaarsen** [nltk/nltk#2601]
Hello,

The link to `Whoosh` library on [line 280 of AUTHORS.md](https://github.com/nltk/nltk/blame/develop/AUTHORS.md#L280), throws a 404 exception.
This is the link that is used: https://bitbucket.org/mchaput/whoosh/wiki/Home

Perhaps either https://github.com/whoosh-community/whoosh or https://github.com/mchaput/whoosh works as a good replacement, assuming the reference to Whoosh should be kept at all.

**Comment by stevenbird** [comment]
Thanks @CubieDev
