### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException when training a MaltParser

### ISSUE THREAD

**Issue by yyz159756** [nltk/nltk#2602]
I follow the guide in this url:https://cl.lingfil.uu.se/~nivre/research/parseme_lab.html

I want to try to train a parser soI ran a command: java -jar -Xmx2g D:\env\maltParser\maltparser-1.8.1\maltparser-1.8.1.jar  -c en-parser -m learn -i E:\data\UD_English-GUM-master\en_gum-ud-train.conllu.

but then cmd output like this following:
-----------------------------------------------------------------------------
                          MaltParser 1.8.1
-----------------------------------------------------------------------------
         MALT (Models and Algorithms for Language Technology) Group
             Vaxjo University and Uppsala University
                             Sweden
-----------------------------------------------------------------------------

Started: Sun Sep 13 17:19:25 CST 2020
  Transition system    : Arc-Eager
  Parser configuration : Nivre with allow_root=true, allow_reduce=false and enforce_tree=false
  Oracle               : Arc-Eager
  Data Format          : file:/E:/data/en-parser/conllx.xml
Exception in thread "main" java.lang.NullPointerException
        at org.maltparser.parser.algorithm.nivre.ArcEagerOracle.predict(ArcEagerOracle.java:30)
        at org.maltparser.parser.BatchTrainer.parse(BatchTrainer.java:47)
        at org.maltparser.parser.SingleMalt.oracleParse(SingleMalt.java:222)
        at org.maltparser.parser.SingleMaltChartItem.process(SingleMaltChartItem.java:128)
        at org.maltparser.core.flow.FlowChartInstance.process(FlowChartInstance.java:200)
        at org.maltparser.Engine.process(Engine.java:63)
        at org.maltparser.MaltConsoleEngine.maltParser(MaltConsoleEngine.java:99)
        at org.maltparser.MaltConsoleEngine.startEngine(MaltConsoleEngine.java:76)
        at org.maltparser.Malt.main(Malt.java:18)

It remainded me there is a NullPointerExceptionin thread.

But I ran a command: java -jar D:\env\maltParser\maltparser-1.8.1\maltparser-1.8.1.jar. It can produce correct output:
-----------------------------------------------------------------------------
                          MaltParser 1.8.1
-----------------------------------------------------------------------------
         MALT (Models and Algorithms for Language Technology) Group
             Vaxjo University and Uppsala University
                             Sweden
-----------------------------------------------------------------------------

Usage:
   java -jar maltparser-1.8.1.jar -f <path to option file> <options>
   java -jar maltparser-1.8.1.jar -h for more help and options

help                  (  -h) : Show options
-----------------------------------------------------------------------------
option_file           (  -f) : Path to option file
-----------------------------------------------------------------------------
verbosity            *(  -v) : Verbosity level
  debug      - Logging of debugging messages
  error      - Logging of error events
  fatal      - Logging of very severe error events
  info       - Logging of informational messages
  off        - Logging turned off
  warn       - Logging of harmful situations
-----------------------------------------------------------------------------

Documentation: docs/index.html

Can someone give me a direction to solve this problem?

**Comment by tomaarsen** [comment]
I don't see how this is related to NLTK. Closing this now.
