### ISSUE TITLE
Impossible to save SVM classifier (solution inside)

### ISSUE THREAD

**Issue by dchaplinsky** [nltk/nltk#261]
At the moment it's impossible to pickle SVM classifier because it relies on C implementation and pickle is raising an error if you try it.

However I worked out the solution:

``` python

    classifier = SvmClassifier.train(feats)

    write_model(classifier._model, "svn_model.txt")
    fix_model("svn_model.txt")

    classifier._model = None
    with open("classifier.pickle", 'wb') as f:
        pickle.dump(classifier, f)

```

where fix_model routine is referring to this:
https://bitbucket.org/wcauchois/pysvmlight/issue/3/write_model-creates-model-which-is#comment-1470562

Loading is pretty straightforward too:

``` python
with open("models/classifier.pickle", 'r') as f:
    classifier = pickle.load(f)

classifier._model = read_model("svn_model.txt")

```

both read_model and write_model can be found in original pysvmlight package

**Comment by dcampbell24** [comment]
Might a better solution be to wrap the svmlight library with ctypes?

**Comment by dchaplinsky** [comment]
Yeah, probably, as original bindings are reason of often segfaults.

But this will definitely require more work than proposed idea.

**Comment by kmike** [comment]
nltk.classify.svm is no longer in NLTK.
