### ISSUE TITLE
download issue of nltk

### ISSUE THREAD

**Issue by mchanitlu** [nltk/nltk#2611]
pip3 install nltk
Processing /Users/chanlu/Library/Caches/pip/wheels/ff/d5/7b/f1fb4e1e1603b2f01c2424dd60fbcc50c12ef918bafc44b155/nltk-3.5-py3-none-any.whl
Requirement already satisfied: joblib in /usr/local/lib/python3.8/site-packages (from nltk) (0.17.0)
Collecting regex
  Using cached regex-2020.9.27.tar.gz (690 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/site-packages (from nltk) (4.50.2)
Requirement already satisfied: click in /usr/local/lib/python3.8/site-packages (from nltk) (7.1.2)
Building wheels for collected packages: regex
  Building wheel for regex (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-install-kns0dngq/regex/setup.py'"'"'; __file__='"'"'/private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-install-kns0dngq/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-wheel-r8jsu98t
       cwd: /private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-install-kns0dngq/regex/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-3.8
  creating build/lib.macosx-10.15-x86_64-3.8/regex
  copying regex_3/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/regex
  copying regex_3/regex.py -> build/lib.macosx-10.15-x86_64-3.8/regex
  copying regex_3/_regex_core.py -> build/lib.macosx-10.15-x86_64-3.8/regex
  copying regex_3/test_regex.py -> build/lib.macosx-10.15-x86_64-3.8/regex
  running build_ext
  building 'regex._regex' extension
  creating build/temp.macosx-10.15-x86_64-3.8
  creating build/temp.macosx-10.15-x86_64-3.8/regex_3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c regex_3/_regex.c -o build/temp.macosx-10.15-x86_64-3.8/regex_3/_regex.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for regex
  Running setup.py clean for regex
Failed to build regex
Installing collected packages: regex, nltk
    Running setup.py install for regex ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-install-kns0dngq/regex/setup.py'"'"'; __file__='"'"'/private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-install-kns0dngq/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-record-04g_xr2i/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/regex
         cwd: /private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-install-kns0dngq/regex/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.8
    creating build/lib.macosx-10.15-x86_64-3.8/regex
    copying regex_3/__init__.py -> build/lib.macosx-10.15-x86_64-3.8/regex
    copying regex_3/regex.py -> build/lib.macosx-10.15-x86_64-3.8/regex
    copying regex_3/_regex_core.py -> build/lib.macosx-10.15-x86_64-3.8/regex
    copying regex_3/test_regex.py -> build/lib.macosx-10.15-x86_64-3.8/regex
    running build_ext
    building 'regex._regex' extension
    creating build/temp.macosx-10.15-x86_64-3.8
    creating build/temp.macosx-10.15-x86_64-3.8/regex_3
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c regex_3/_regex.c -o build/temp.macosx-10.15-x86_64-3.8/regex_3/_regex.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-install-kns0dngq/regex/setup.py'"'"'; __file__='"'"'/private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-install-kns0dngq/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sl/w8b8rbg577z9c1j9mk6lf6tr0000gn/T/pip-record-04g_xr2i/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/regex Check the logs for full command output.

*****I don't know why I cannot download nltk. Thank you for your help***

**Comment by dplefevre** [comment]
The error says that you're missing xcrun, a Mac utility. You might not have installed it or it could be missing or outdated as a result of updating your OS.

This might help you: https://www.studytonight.com/post/solved-mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun

Edit: Funnily enough, this issue cropped up for me as well right after I first wrote this comment, though unrelated to this library. I had to install Xcode from the app store to resolve it.

**Comment by bryanekong** [comment]
I use a windows device and I have this issue also, any suggestions?

**Comment by tomaarsen** [comment]
Perhaps you can install the problematic package on its own first? i.e.:
```
pip install -U regex
```
`-U` for "Upgrade"

**Comment by bryanekong** [comment]
thank you for that. A different solution worked for me. I am working on a python 2 project and the last version of regex compatible with Python 2.7 is [2021.3.17] (https://pypi.org/project/regex/2021.3.17/). Installed it with pip install regex==2021.3.17
