### ISSUE TITLE
bug in ntlk.word_tokenize

### ISSUE THREAD

**Issue by onetruffle** [nltk/nltk#2613]
The word `cannot` is split into `can` and `not`, when it shouldn't be.

To reproduce -  
1. Install `nltk` using pip.
2. Download as little as possible for `word_tokenize` to work (I think `punkt` is enough).
3. Run the following using the python REPL (only the first line, without the `>`).
```
> import nltk.word_tokenize("cannot")
['can', 'not']
```

**Comment by tomaarsen** [comment]
@altaway 
This *is* the expected result. `word_tokenize()` uses `NLTKWordTokenizer().tokenize()` under the hood, which applies several contractions. These are some of the contractions:
https://github.com/nltk/nltk/blob/385fb3f22031ebfa87b5c5571f32008f967264fa/nltk/tokenize/destructive.py#L13-L29

To see some of these in action, run the following code:
```python
from nltk.tokenize import word_tokenize

for word in ["cannot", "would've", "gimme", "gonna", "lemme", "wanna", "don't", "they'll", "it's"]:
    print(word.ljust(8), "->", word_tokenize(word))
```
Which outputs:
```python
cannot   -> ['can', 'not']
would've -> ['would', "'ve"]
gimme    -> ['gim', 'me']
gonna    -> ['gon', 'na']
lemme    -> ['lem', 'me']
wanna    -> ['wan', 'na']
don't    -> ['do', "n't"]
they'll  -> ['they', "'ll"]
it's     -> ['it', "'s"]
```

The `NLTKWordTokenizer` is described as `The NLTK tokenizer that has improved upon the TreebankWordTokenizer.`. This `TreebankWordTokenizer` specifically has this contraction as a main selling point of the implementation.

**Comment by onetruffle** [comment]
I'll remember this, thanks.
