### ISSUE TITLE
[wiki] SENNA binary link is outdated

### ISSUE THREAD

**Issue by ermik** [nltk/nltk#2622]
On this page: 
https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software 

The link to SENNA toolkit is no longer accessible. It was most likely taken from [here](https://www.nec-labs.com/research-departments/machine-learning/machine-learning-software/Senna) where it also leads nowhere.

The only other place I found this distribution author's website: https://ronan.collobert.com/senna/

**Comment by tomaarsen** [comment]
I've updated the wiki with the new link. Thank you. Sorry for the delay.
