### ISSUE TITLE
Can we delete CoreNLP test code? (It's currently skipped)

### ISSUE THREAD

**Issue by dannysepler** [nltk/nltk#2631]
This originally was part of https://github.com/nltk/nltk/pull/2629, but it's probably best to wait and let folks chat about it.

- https://github.com/nltk/nltk/pull/1942 first marked it as skipped, and here's the relevant comment: `skipped all corenlp tests since we're dropping official support after stanford release their official python wrapper`
- Original implementation: https://github.com/nltk/nltk/pull/1249

cc @alvations @dimazest

**Comment by stevenbird** [comment]
@dannysepler happy to go ahead with your suggestion, if you're happy to submit a PR? Thanks.
