### ISSUE TITLE
WordNetLemmatizer does not lemmatize "matroids"

### ISSUE THREAD

**Issue by MarioKrenn6240** [nltk/nltk#2638]
```
from nltk.stem import WordNetLemmatizer
wnl=WordNetLemmatizer()
print(wnl.lemmatize('matroids'))
```

returns "matroids", but should return "matroid".

**Comment by goodmami** [comment]
This is because *matroid* is not in WordNet. From the docstring for `WordNetLemmatizer`:

> Lemmatize using WordNet's built-in morphy function.
> Returns the input word unchanged if it cannot be found in WordNet.

For example:

```python
>>> from nltk.corpus import wordnet as wn
>>> wn.synsets('matrix')
[Synset('matrix.n.01'), Synset('matrix.n.02'), Synset('matrix.n.03'), Synset('matrix.n.04'), Synset('matrix.n.05'), Synset('matrix.n.06')]
>>> wn.synsets('matroid')
[]
>>> from nltk.stem import WordNetLemmatizer
>>> wnl = WordNetLemmatizer()
>>> wnl.lemmatize('matrices')
'matrix'
>>> wnl.lemmatize('matroids')
'matroids'
>>> wnl.lemmatize('foobars')
'foobars'
```

**Comment by MarioKrenn6240** [comment]
Perfect, thank you goodmami!
Is there a way that we add words to the WordNet database?

**Comment by goodmami** [comment]
I don't think we should hold our breath for a new release of the Princeton WordNet, but you can try raising an issue for the [English WordNet](https://github.com/globalwordnet/english-wordnet), which is an actively-developed fork. The next release is probably in April (going by precedent). The NLTK doesn't load the English WordNet but you might try [Wn](https://github.com/goodmami/wn/) (disclaimer: I'm the author). Unfortunately, though, Wn does not have a lemmatizer (yet?).

**Comment by goodmami** [comment]
@MarioKrenn6240 if this is resolved, maybe you could close the issue?
