### ISSUE TITLE
NLTK and pattern.en incorrectly classifying some proper nouns

### ISSUE THREAD

**Issue by pmi123** [nltk/nltk#2639]
I am using nltk and pattern.en to analyze some text. In a test run, I used the text from Little Red Riding Hood. I noticed that pattern.en did recognize 'Little', 'Red', and 'Hood' as proper nouns (probably due to capitalization?), but 'Riding' was seen as a verb and not part of the proper noun 'Little Red Riding Hood'.

For example, the sentence in the story:

`text = "Little Red Riding Hood, was so long until the large, large trough was quite full."
`
was tagged as

`[('"', '"'), ('Little', 'NNP'), ('Red', 'NNP'), ('Riding', 'VBG'), ('Hood', 'NNP'), (',', ','), ('was', 'VBD'), ('so', 'RB'), ('long', 'RB'), ('until', 'IN'), ('the', 'DT'), ('large', 'JJ'), (',', ','), ('large', 'JJ'), ('trough', 'NN'), ('was', 'VBD'), ('quite', 'RB'), ('full', 'JJ'), ('.', '.')]
`

My code:

```
import nltk
from pattern.en import tag
tagged_text = tag(text)
```
Is this just a problem with the pattern.en, or am I assuming nltk should do something it doesn't? If the latter, how do I improve on the rendering of proper nouns so 'Riding' is tagged in this instance as a NNP and not a VBG so it is not converted to 'rid'?

A final question for the linguists in the crowd. Why is the lemma of 'riding' 'rid', and not 'ride'? 

Thanks!

Mark

**Comment by 12mohaned** [comment]
You can use the following code, it does works.
`from nltk.tokenize import word_tokenize`
`text = "Little Red Riding Hood, was so long until the large, large trough was quite full."`
`nltk.pos_tag(word_tokenize(text))`

[('Little', 'JJ'), ('Red', 'NNP'), ('Riding', 'NNP'), ('Hood', 'NNP'), (',', ','), ('was', 'VBD'), ('so', 'RB'), ('long', 'RB'), ('until', 'IN'), ('the', 'DT'), ('large', 'JJ'), (',', ','), ('large', 'JJ'), ('trough', 'NN'), ('was', 'VBD'), ('quite', 'RB'), ('full', 'JJ'), ('.', '.')]

**Comment by tomaarsen** [comment]
This code:
```python
import nltk
from pattern.en import tag
tagged_text = tag(text)
```
only uses `pattern`'s tagging. 

Mohaned's answer is right. I'll close this as resolved accordingly.

Also, the lemma of 'riding' ought to be 'ride', but no lemmatization algorithm is flawless, and seemingly it failed here.
