### ISSUE TITLE
babelfish translator service is gone

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#265]
I've recently ported nltk.misc.babelfish to py3 and fixed #180 only to realize that today tests begin to fail again :) 

There is no longer http://babelfish.yahoo.com/translate_txt -  it redirects to http://www.microsofttranslator.com/ which is an another translator service with different API. See http://blogs.msdn.com/b/translation/archive/2012/05/30/welcoming-yahoo-babel-fish-users.aspx

**Comment by hlongmore** [comment]
I noticed this while going through the [nltk book](http://nltk.googlecode.com/svn/trunk/doc/book/ch01.html), and started working on a version of babelize that would be able to use the Microsoft version of babelfish, or translate.google.com.  Both options have issues.

The MS version requires an access token, and thus an [Azure account](http://msdn.microsoft.com/en-us/library/hh454950), or the addition of another dependency such as selenium, unless I'm missing some other available option.

The Google version probably also requires something such as selenium, though it may be possible to get it to work by sending a different User-Agent through subclassing [UrlOpener or FancyUrlOpener](http://docs.python.org/library/urllib.html#url-opener-objects), or by setting the headers of a [urllib2.Request object](http://docs.python.org/library/urllib2.html#urllib2.Request).  I haven't gotten around to trying either of these options yet, but I'm guessing there is enough Javascript in the returned result to require selenium.

**Comment by kmike** [comment]
I believe Google provide Translate API that is not free; scraping translate.google.com is possibly a ToS voilation.

**Comment by hlongmore** [comment]
Yes, there is a for-fee API, and after checking https://developers.google.com/translate/v2/terms and https://developers.google.com/terms/, I agree, scraping translate.google.com is likely a ToS violation.  Though the terms apply to those using the Google APIs, and it could be argued that if one is not a Google API consumer, they never agreed to the terms, my guess is that goes against the intent of providing the API in the first place.

**Comment by lusy** [comment]
It's really a pity that babelfish is broken and that both Google and Microsoft APIs don't seem to be ok to use in this case... 
But aren't there other options? For example I've just stumbled upon this API here: http://frengly.com/translationAPI, however, it doesn't seem to be that good either, because it requires username and password :/

**Comment by kmike** [comment]
There is http://api.yandex.ru/translate/ that doesn't require authorization according to API docs and ToS.

Example: http://translate.yandex.net/api/v1/tr.json/translate?lang=en-ru&text=To+be,+or+not+to+be%3F&text=That+is+the+question.

It is Russian-specific though; it can translate Russian <-> English, Deutsch, Polish, Ukrainian and Turkish. I personally think this may be OK for an example but if better alternatives exist we should explore them.

**Comment by lusy** [comment]
Hm, let us keep our eyes open then.. :)

**Comment by maxwillzq** [comment]
So we have no solution till today?
Thanks

**Comment by stevenbird** [comment]
No, we do not.  But you can experience the same thing here: http://translationparty.com/

**Comment by tttthomasssss** [comment]
Is this issue in scope for the near future or won't likely to be fixed anytime soon?

**Comment by stevenbird** [comment]
I'm not aware of a good, free translation API. We probably need to remove this (broken) functionality.

**Comment by ironico** [comment]
Hello, 
u can use MyMemory is free and anonymous for 100 request/day or 1000 request/day with a valid email.
I made a python function for that, if you are interested u can find it here: 
http://www.gennarovarriale.it/python-funzione-per-traduzione-testi

**Comment by kmike** [comment]
Hi @ironico,

Thanks for a link. I personally think that
1. it is not robust to rely on third-party API in NLTK, and 
2. babelize_shell was fun but not very useful.

Also, 100 requests/day limit is easy to exceed, esp. the way it was used in NLTK (even 1000 requests/day could be quite low for such purposes). So I'd vote -1 for restoring this functionality using a different online service.

**Comment by ironico** [comment]
@kmike absolutely agree.
I proposed my solution only for testing, not for an integration in NLTK.
-1 for me too ;)

**Comment by maxwillzq** [comment]
We can not find stable solution for this function? Thanks

**Comment by stevenbird** [comment]
@maxwillzq - as @kmike also points out, we can't rely on a third-party API and also be stable
