### ISSUE TITLE
Synset._needs_root returns None for pos other than noun and verb

### ISSUE THREAD

**Issue by snrore** [nltk/nltk#2651]
`Synset._needs_root` returns None for pos other than noun and verb. I think it is a bit strange for `Synset._needs_root` to return a boolean for noun and verb, but None for any other part of speech.

![image](https://user-images.githubusercontent.com/35712574/103341379-c9e70180-4a54-11eb-90ae-e6f35364d449.png)

This causes Synset.path_similarity, and Synset.wup_similarity to not work for parts of speech other than noun, and verb.  
If `Synset._needs_root` returns `True` instead, then `Synset.path_similarity` and `Synset.wup_similarity` will work for other parts of speech.

Should these methods work for other parts of speech?

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/pull/2650

**Comment by snrore** [comment]
![image](https://user-images.githubusercontent.com/35712574/103614452-a01b5800-4ef6-11eb-9efb-ddc4976d0f7b.png)
![image](https://user-images.githubusercontent.com/35712574/103614582-ea043e00-4ef6-11eb-886d-d7b61bab7b1a.png)

Here is an example showing that wup_similarity, path_similarity, and lch_similarity return none for adjectives.

**Comment by goodmami** [comment]
Your proposed fix in #2654 seems reasonable to me, but note that the Princeton WordNet does not have any hypernyms defined for the other parts of speech (`a` adjectives, `r` adverbs, `s` adjective satellites), so the similarity metrics (which rely on hypernym paths) wouldn't be very informative for them.

**Comment by snrore** [comment]
Thanks! I didn't know that. It's Interesting! Even though there is no hypernyms for other parts of speech, I still think it makes sense to make this change.  The similarity functions returns a value when going from `noun` to (`a`,`r`,`s`), but return `None`, when going from (`a`,`r`,`s`) to noun.
