### ISSUE TITLE
Wordnet 503 error

### ISSUE THREAD

**Issue by ibarrien** [nltk/nltk#2656]
Attempting to download wordnet from nltk produced a 503 error earlier today around 10am PST.
Did anyone else experience this and was there a resolution?
Error detail snippets:

import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Error downloading 'wordnet' from
[nltk_data]     <https://raw.githubusercontent.com/nltk/nltk_data/gh-...
[nltk_data]     pages/packages/corpora/wordnet.zip>:   HTTP Error 503:
[nltk_data]     between bytes timeout

Other nltk packages like perceptron tagger seemed to work.

**Comment by goodmami** [comment]
@ibarrien have you tried again recently? HTTP error 503 is generally a temporary situation where the server is down or overloaded. Do you consistently get 503 for the wordnet corpus and not for other corpora?

**Comment by ibarrien** [comment]
Hello, thank you for the follow-up! It is working again; it was a transient error. One follow-up question: is it an "ok" practice to download wordnet once, re-use the downloaded copy, and look for an update periodically? E.g. how often is wordnet substantially updated ? [apologies if vague]

**Comment by goodmami** [comment]
> One follow-up question: is it an "ok" practice to download wordnet once, re-use the downloaded copy, and look for an update periodically? E.g. how often is wordnet substantially updated ?

Normally when you download a package it is stored in the `nltk_data` directory in your home folder, and it is reused by successive processes. If you call `nltk.download('wordnet')` in your script and the file is already downloaded, it will print a message like "Package wordnet is already up-to-date!". If you see a different message, you can try to force a download (add the `force=True` argument to the function call), but please do *not* force a download each time the script is run, as it eats up the NLTK's bandwidth quota (see #1787 for context), and also makes your scripts run slowly. The wordnet data packaged by the NLTK is the Princeton WordNet 3.0 and is unlikely to change. If you want newer versions of wordnet data, you might also try https://github.com/goodmami/wn (disclaimer: I'm the author).

> It is working again; it was a transient error.

Thanks for the quick response. Feel free to close the issue.

**Comment by ibarrien** [comment]
excellent, thanks for the tips. closing now.
