### ISSUE TITLE
NaiveBayes returning worst label for all classifications

### ISSUE THREAD

**Issue by jlark** [nltk/nltk#266]
I'm running the following trivial code to test the classifier:
import nltk.classify.util
from nltk.classify import NaiveBayesClassifier
from nltk.corpus import movie_reviews
def word_feats(words):
    return dict([(word, True) for word in words])

negids = movie_reviews.fileids('neg')
posids = movie_reviews.fileids('pos')
negfeats = [(word_feats(movie_reviews.words(fileids=[f])), 'neg') for f in negids]
posfeats = [(word_feats(movie_reviews.words(fileids=[f])), 'pos') for f in posids]
negcutoff = len(negfeats)_3/4
poscutoff = len(posfeats)_3/4
trainfeats = negfeats[:negcutoff] + posfeats[:poscutoff]
testfeats = negfeats[negcutoff:] + posfeats[poscutoff:]
print 'train on %d instances, test on %d instances' % (len(trainfeats), len(testfeats))
classifier = NaiveBayesClassifier.train(trainfeats)
print 'accuracy:', nltk.classify.util.accuracy(classifier, testfeats)
classifier.show_most_informative_features()

print "running test classification"
test_features = word_feats("this movie was magnificent and outstanding to begin with")
print classifier.classify(test_features)
probdist = classifier.prob_classify(test_features)
for sample in probdist.samples():
        print "%s : %s"%(sample, probdist.prob(sample))

which out puts

D:\content\processing\categorization>python code_document_classify_use.py
train on 1500 instances, test on 500 instances
accuracy: 0.728
Most Informative Features
             magnificent = True              pos : neg    =     15.0 : 1.0
             outstanding = True              pos : neg    =     13.6 : 1.0
               insulting = True              neg : pos    =     13.0 : 1.0
              vulnerable = True              pos : neg    =     12.3 : 1.0
               ludicrous = True              neg : pos    =     11.8 : 1.0
             uninvolving = True              neg : pos    =     11.7 : 1.0
                  avoids = True              pos : neg    =     11.7 : 1.0
              astounding = True              pos : neg    =     10.3 : 1.0
             fascination = True              pos : neg    =     10.3 : 1.0
                 idiotic = True              neg : pos    =      9.8 : 1.0
running test classification
neg
neg : 0.589362761207
pos : 0.410637238793

based on the most usefull features function the sample text I'm using
("this movie was magnificent and outstanding to begin with")

should return pos not neg. I've tested with other samples:
"this movie was outstanding  and magnificent to begin with outstanding and vulnerable"

I still get 
running test classification
neg
neg : 0.589362761207
pos : 0.410637238793

if having the word magnificent  makes the classifier to tag   15.0 : 1.0 pos over neg. I'm very shocked that neg would have a higher probablity.

Alp

**Comment by rsennrich** [comment]
your input for word_feats should be a list of words (as in trainfeats), not a string (as in test_features).

**Comment by jlark** [comment]
I'm sorry if it wasn't obvious but I am passing a list of features in 

test_features = word_feats("this movie was magnificent and outstanding to begin with")

words_feats function encodes the string as a feature list.

**Comment by rsennrich** [comment]
the output of word_feats() is a dictionary; the input should be a list of words, like this:

test_features = word_feats(['this', 'movie', 'was', 'magnificent', 'and', 'outstanding', 'to', 'begin', 'with'])

**Comment by jlark** [comment]
Ok. That was embarrassing. Looks like I was passing in the features for classification incorectly.
