### ISSUE TITLE
Incorrect tagging of a phrase

### ISSUE THREAD

**Issue by fukanchik** [nltk/nltk#2662]
```
tok=nltk.word_tokenize("define and formalize a common starting application for graph data")
tags=nltk.pos_tag(tok)
print(tags)
```
produces
```
[('define', 'NN'), ('and', 'CC'), ('formalize', 'VB'), ('a', 'DT'), ('common', 'JJ'), ('starting', 'VBG'), ('application', 'NN'), ('for', 'IN'), ('graph', 'NN'), ('data', 'NNS')]
```
"define" here is marked as "NN" which I think means "noun" while I expect it to be "VB", same as "formalize".

I am not sure if this phrase is a proper english though. I found it in some marketing materials.

**Comment by stevenbird** [comment]
Yes it should be a verb, probably not covered well by the training data... we don't deal with every tagging error here.
