### ISSUE TITLE
nltk.translate.sentence_bleu function not working 

### ISSUE THREAD

**Issue by MBadriNarayanan** [nltk/nltk#2669]
For sentences of length less than 4, sentence_bleu is not being calculated properly. If length is less than 4, BLEU value is greater than 1. Refer image below
![Bleu_Score](https://user-images.githubusercontent.com/58718023/109692397-7b69f680-7bae-11eb-8a5c-dc3ab9e5507a.png)

**Comment by suyuzhang** [comment]
Use `auto_reweigh=True` is work for me.

**Comment by tomaarsen** [comment]
Resolved in #2681, thank you for reporting.
