### ISSUE TITLE
The sem package cannot handle unicode strings

### ISSUE THREAD

**Issue by heatherleaf** [nltk/nltk#267]
The sem package seems to require that all arguments are of type str, not unicode:

$ grep -n 'isinstance' sem/*py | grep '\bstr\b'
sem/drt.py:844:        if isinstance(item, str):
sem/drt.py:864:        if isinstance(item, str):
sem/evaluate.py:77:        if isinstance(elem, str):
sem/evaluate.py:113:            if isinstance(val, str) or isinstance(val, bool):
sem/evaluate.py:137:            if isinstance(val, str):
sem/evaluate.py:450:        if isinstance(varex, str):
sem/glue.py:34:        if isinstance(meaning, str):
sem/glue.py:41:        if isinstance(glue, str):
sem/glue.py:578:        if isinstance(meaning, str):
sem/glue.py:585:        if isinstance(glue, str):
sem/linearlogic.py:30:        assert isinstance(name, str)
sem/logic.py:87:        assert isinstance(name, str), "%s is not a string" % name
sem/logic.py:206:        return isinstance(other, BasicType) and str(self) == str(other)
sem/logic.py:271:    assert isinstance(type_string, str)
sem/logic.py:1748:    assert isinstance(expr, str), "%s is not a string" % expr
sem/logic.py:1759:    assert isinstance(expr, str), "%s is not a string" % expr
sem/logic.py:1770:    assert isinstance(expr, str), "%s is not a string" % expr

This has the effect that we cannot parse an FCFG grammar from a unicode string.

**Comment by turicas** [comment]
Related to #299.

**Comment by kmike** [comment]
This should be fixed in 2and3.
