### ISSUE TITLE
Issue about BLEU smoothing method 4

### ISSUE THREAD

**Issue by OpenSource-fan** [nltk/nltk#2676]
NLTK3.5 implements smoothing method 4 proposed in the paper [https://www.aclweb.org/anthology/W14-3346/ ].
However, we suspect that the implementation is incorrect. The code at https://github.com/nltk/nltk/blob/d0f54c29b3f65ea13dd6e824e08eb9f193bcb958/nltk/translate/bleu_score.py#L582-L585 is problematic.
This leads to the p_n[i] greater than 100% in some case. When hyp_len < 4 in 4-gram, p_n[i] can be assigned with a percentage number that is much greater than 100% (or even > 500%).
In fact, the p_n[i] should not be greater than 100%.
The correct implementation is p_n[i] = (1 / incvnt) / p_i.denominator in line585.

**Comment by stevenbird** [comment]
Thanks @anonymityBoy. Would you please submit a pull request?

**Comment by stevenbird** [comment]
Thanks @anonymityBoy... can I trouble you to add a regression test or two [here](https://github.com/nltk/nltk/blob/develop/nltk/test/bleu.doctest) please?

**Comment by OpenSource-fan** [comment]
Sure. I have added.
