### ISSUE TITLE
[Question] How can we use do unsupervised document tagging with NLTK?

### ISSUE THREAD

**Issue by neel04** [nltk/nltk#2677]
Hello everyone!

I wished to use the `HiddenMarkovModelTrainer` from NLTK to try to do **fully** unsupervised document tagging of a low resource language. Apparently, from an S.O answer, we need to feed tuples of `states` and `symbols`.

Assuming that it refers to the ground labels, isn't that a semi-supervised approach? can we do a fully supervised and local approach with NLTK?

if that is indeed possible, can someone clarify what exactly `states` and `symbols` are?

**Comment by stevenbird** [comment]
Sorry, this is not the place. Please use stackoverflow.
