### ISSUE TITLE
How to obtain the universal POS for tokens when using Stanford CoreNLP?

### ISSUE THREAD

**Issue by ShangwenWang** [nltk/nltk#2695]
When using the original NLTK package, we can obtain the universal POS via using the following demo commend:
`parsed_results = nltk.pos_tag(nltk.word_tokenize(sentence), tagset='universal')`

While the tutorial in this project to achieve the same target using _Stanford CoreNLP_ is:
`pos_tagger = CoreNLPParser(url='http://localhost:9000', tagtype='pos')`
`list(pos_tagger.tag('What is the airspeed of an unladen swallow ?'.split()))`

However, this could not return the universal result. I'd like to know to achieve my goal. Anybody can help me?

**Comment by stevenbird** [comment]
We're dropping support for the CoreNLP now that it has its own Python interface.
