### ISSUE TITLE
urlopen error [Errno 60] Operation   timed out

### ISSUE THREAD

**Issue by srinath116** [nltk/nltk#2705]
[nltk_data] Error loading stopwords: <urlopen error [Errno 60]
[nltk_data]     Operation timed out>
[nltk_data] Error loading words: <urlopen error [Errno 60] Operation
[nltk_data]     timed out>

getting the above error when tried to do nltk.download('all)

**Comment by bs004** [comment]
either use nltk.download('all')
or your machine dows not have internet access

**Comment by tomaarsen** [comment]
Unable to reproduce this issue - I assume your machine didn't have internet access at the time. Let us know if the problem returns.

**Comment by narayanaroyalgithub** [comment]
i got the same problem with good network connection

**Comment by b-hemanth** [comment]
I am LAN-ned into a Gigabit connection and able to reproduce this. I presume OP like a few other StackOverflow commenters is on JioFiber, where some mildly sophisticated network security checks are failing and causing the download to time out. But I'm able to switch to a slower different network and run the download with no trouble. If the ISP won't allow `nltk.download` to run, that might require messing with ssl verification in the connection and/or proxies.

**Comment by tomaarsen** [comment]
I think so too, yes. I've read more reports that Jio is unable to load raw.githubusercontent.com, which is what NLTK uses to host its data. For example, Jio users seem to be unable to access https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/tokenizers/punkt.xml

**Comment by regunath** [comment]
indeed its a jiofiber issue, switching to mobile hotspot solved the issue.

**Comment by unrealnerd** [comment]
> I think so too, yes. I've read more reports that Jio is unable to load raw.githubusercontent.com, which is what NLTK uses to host its data. For example, Jio users seem to be unable to access https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/tokenizers/punkt.xml

Switching VPN to different country also worked using jio.

**Comment by Rohith1218** [comment]
so any solution?

**Comment by sarathsomana** [comment]
Using Cloudflare DNS seems to resolve this issue.
