### ISSUE TITLE
Do you provide a object.inv file for sphinx documentation link?

### ISSUE THREAD

**Issue by rodrigorenie** [nltk/nltk#2707]
I've seen that you provide documentation on readthedocs and I'm building a software (for academic pourposes) that uses NLTK and I'm documenting it using Sphinx. I'd like to cross reference your documentation using sphinx.ext.intersphinx. But for that, I need to configure the location of the object.inv file in your documentation. Do you provide it? Thanks.

**Comment by stevenbird** [comment]
@rodrigorenie, please see https://github.com/nltk/nltk.github.com/blob/master/objects.inv
