### ISSUE TITLE
FreqDist Relative Frequencies (Corpus Linguistics)

### ISSUE THREAD

**Issue by IngoKl** [nltk/nltk#2717]
`FreqDist` is a very useful tool for corpus linguists trying to generate frequency tables. However, in many cases, relative frequencies (i.e., normalized frequencies) are desired in these cases. 

There are two common ways of doing this: Either the frequency of an item is divided by the total number of items (e.g., words), or the frequency is normalized to something like "X per million." This allows us to compare frequencies between corpora of different sizes.

I believe that this could be a useful addition to the `FreqDist` that is relatively straightforward to implement. If I haven't overlooked this functionality and if there's interest, I'd be happy to work on a PR.

**Comment by tomaarsen** [comment]
@IngoKl 
> However, in many cases, relative frequencies (i.e., normalized frequencies) are desired in these cases.

To my knowledge, this functionality is captured under subclasses of `ProbDistI`, such as `UniformProbDist`. See the source here:
https://github.com/nltk/nltk/blob/33ac28cfcad288c611c5901faa9ebc799e7c95dd/nltk/probability.py#L590-L595

If this isn't exactly what you are after, there are 14 or so other implementations of `ProbDistI` that all implement `prob` which returns the probability for a given range, and more.

Potentially this solves your issue - and potentially you still feel like this should *also* be implemented under `FreqDist`. In that case, allowing a method that takes as an optional argument a subclass of `ProbDistI` will make for some nice customisability in the exact frequency probablility you are after.
(Assuming that others agree that this method should be implemented)

**Comment by IngoKl** [comment]
> @IngoKl
> 
> > However, in many cases, relative frequencies (i.e., normalized frequencies) are desired in these cases.
> 
> To my knowledge, this functionality is captured under subclasses of `ProbDistI`, such as `UniformProbDist`. See the source here:
> https://github.com/nltk/nltk/blob/33ac28cfcad288c611c5901faa9ebc799e7c95dd/nltk/probability.py#L590-L595
> 
> If this isn't exactly what you are after, there are 14 or so other implementations of `ProbDistI` that all implement `prob` which returns the probability for a given range, and more.
> 
> Potentially this solves your issue - and potentially you still feel like this should _also_ be implemented under `FreqDist`. In that case, allowing a method that takes as an optional argument a subclass of `ProbDistI` will make for some nice customisability in the exact frequency probablility you are after.
> (Assuming that others agree that this method should be implemented)

Thank you for pointing this out! I'll have a closer look at `ProbDistI` and its subclasses and see if/how a solution within `FreqDist` would still make sense.

**Comment by stevenbird** [comment]
> Potentially this solves your issue - and potentially you still feel like this should also be implemented under FreqDist. 

The only use case I can think of here is to initialise a ProbDist from a FreqDist, which is already straightforward and does not require special support.
