### ISSUE TITLE
TweetTokenizer wrongly tokenizes emoticons

### ISSUE THREAD

**Issue by huberemanuel** [nltk/nltk#2724]
For the following sentence "it's a:::person" the TweetTokenizer output is:
`["it's", 'a', '::', ':p', 'erson']`

Where the expected output should be:
`["it's", 'a', ':::', 'person']`

**Comment by 12mohaned** [comment]
The tricky part of this text is it's a::**:p**erson. 

The tokeniser recognise :p as a regular expression for an emoji and not as a character in person, so it did its job of recognising emojis.

**Comment by tomaarsen** [comment]
It would be quite tricky to recognise when the output ought to be e.g. `[':::', 'person']`, and when it should be `['::', ':p', 'erson']`. I'm open to accepting PR's for this, but I'm hesitant to label this as a bug, and suspect that we will not try to fix this.
I'll close this for the time being.
