### ISSUE TITLE
Add suffix "acion" to Spanish SnowballStemmer

### ISSUE THREAD

**Issue by smorantg2** [nltk/nltk#2725]
Hi, 

I'm a native Spanish speaker and I've noticed words with suffix "acion" don't get stemmed. (You got right the plural version "aciones", but not the singular one)

Please, add suffix "acion" to Spanish SnowballStemmer

Thank you for your work!

**Comment by marcog222** [comment]
Hola, sabes cómo puedo cargar archivos en español con nltk y que python tome en cuenta los acentos y ñ, y no los sustituya por caracteres extraños como estos: 'prÃ³logo\n\, podrÃ¡s, mÃ¡s, asÃ\xad, Â¿quÃ© podÃ\xada ,estÃ©ril , mÃ\xado

**Comment by dannysepler** [comment]
hi! i am _not_ a native spanish speaker, but i did notice that we have `ación` (which looks like `aci\xF3n` in the code) as an option in the SpanishStemmer. We do not have `aciónes` though.

Are these related and should we have different combinations of this? Or are these not actually related?

(EDIT: Realized we happen to have `uciones` but not `ucion`, yet we have `ución` but not `uciónes`. Perhaps there's something similar going on there?)

**Comment by dannysepler** [comment]
also, the code is [here](https://github.com/nltk/nltk/blob/develop/nltk/stem/snowball.py) and should be pretty simple to change (just make sure to add to both `__step1_suffixes` and the `stem` function)

**Comment by mastdev** [comment]
Hi,
I want to join the open-source community. Can I work on this issue?
