### ISSUE TITLE
SemCorCorpusReader 

### ISSUE THREAD

**Issue by nschneid** [nltk/nltk#273]
Currently `nltk.corpus.semcor` uses an `XMLCorpusReader`, which provides an interface to the raw tokens but not to the semantic annotations. A more useful corpus reader would, at minimum, expose the annotations stored in XML attributes for each token. Ideally it would also link to WordNet objects loaded via `nltk.corpus.wordnet`.

**Comment by nschneid** [comment]
From looking at the code a bit it seems the solution would be to implement an alternative to `ChunkedCorpusReader` that is an `XMLCorpusReader` subclass. In the SemCor files the chunks are actually single words and underscore-joined multiwords, and each chunk has a POS tag, WordNet lemma, sense number, and lexical synset ID associated with it. (POS tags are not available for the individual parts of multiwords.)

**Comment by nschneid** [comment]
Also, named entities not listed in WordNet are tagged. So there are really two kinds of chunks.

**Comment by stevenbird** [comment]
Resolved by https://github.com/nltk/nltk/pull/282
