### ISSUE TITLE
Importing words throws numpy deprecation warning

### ISSUE THREAD

**Issue by ihawn** [nltk/nltk#2735]
Warning: 

DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps

**Comment by tomaarsen** [comment]
NLTK does not use `np.float` directly, only `np.float32` and `np.float64`. 
It seems your warning came from scikit-learn, as `max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps` can be found [here](https://github.com/scikit-learn/scikit-learn/blob/0fb307bf39bbdacd6ed713c00724f8f871d60370/sklearn/linear_model/_least_angle.py#L1379) in that repo.

**Comment by purificant** [comment]
I wonder if `gaac.py` line 51 could be the culprit
