### ISSUE TITLE
Use Graphviz for Wordnet graph visualisations

### ISSUE THREAD

**Issue by ekaf** [nltk/nltk#2738]
Currently, NLTK can draw the tree of hypernyms of one sense of "person" at a time, but it would be difficult to merge those trees into one graphic like the following interesting "Figure 1: Hypernyms of the word person (all senses)", extracted from the article "WordNet and Prolog: why not?",  Julian-Iranzo and Saenz-Perez, 2019 Conference of the International Fuzzy Systems Association and the European Society for Fuzzy Logic and Technology (EUSFLAT 2019).

![person-dot](https://user-images.githubusercontent.com/4782556/123507839-0abe7c80-d66c-11eb-8691-5909fa987436.png)

However, it turns out that the authors used a pretty simple approach: collect the set of edges of this graph, print that set in the format expected by the "dot" program from the "graphviz" package, and then rely on "dot" to draw the graph.

The same approach is quite easy to implement in NLTK, since a few NLTK modules (api, chart, dependencygraph) already interface with the "dot" program. Wouldn'it be nice to have this kind of more powerful graphical capabilities available for Wordnets also?

**Comment by tomaarsen** [comment]
Implemented in 8f91325, thank you for the idea and contribution!
