### ISSUE TITLE
Add pre-commit hooks?

### ISSUE THREAD

**Issue by dannysepler** [nltk/nltk#2744]
Generally curious if we've given thought into this. A lot of repos are now using pre-commit hooks to keep code nice and consistent.

- We could dip our toes in the water with some of these https://github.com/pre-commit/pre-commit-hooks -- they generally don't change the code much

The following two are noisier to set up but I really like them both:
- [Pyupgrade](https://github.com/asottile/pyupgrade/)
- [isort](https://github.com/PyCQA/isort/issues)

**Comment by iliakur** [comment]
I'm in favor, especially for auto-formatting like `isort` and `black`. I haven't used `pyupgrade`, can't say if its noisiness is worth it.

I think if you search the google group there's a thread about this as well.

**Comment by tomaarsen** [comment]
I've personally used this as well, and support the inclusion of this in NLTK. In particular I like the idea of an auto-formatter, but If that's a bridge too far (for now?), then I can recommend the `trailing-whitespace` trimmer from https://github.com/pre-commit/pre-commit-hooks.

**Comment by dannysepler** [comment]
thanks both! i see the [relevant post](https://groups.google.com/g/nltk-dev/c/G7Iz-bjWtqk/m/DMw58fQqAQAJ) in the google group but do not have permissions to post to it?

i agree with your point, Tom. We can start with lighter ones like `trailing-whitespace` and perhaps also `end-of-file-fixer`, document how to do pre-commit stuff for contributors, and then do a noisier one if it goes okay?

**Comment by stevenbird** [comment]
@iliakur would you be interested in managing this? What permissions would you need?

**Comment by iliakur** [comment]
I'm interested, but wary of the commitment. My first-born is 3 weeks old and I won't be able to reliably find time to look into this for a few more weeks, maybe even more.

**Comment by stevenbird** [comment]
@dannysepler I like your suggestion
