### ISSUE TITLE
travis-ci.org no longer runs builds

### ISSUE THREAD

**Issue by purificant** [nltk/nltk#2749]
![travis_ci_org_eol](https://user-images.githubusercontent.com/4669013/126481562-e9d7475f-3c1f-499c-9416-c04b8514d793.png)
The above message is currently displayed on https://travis-ci.org/github/nltk/nltk

travis-ci.org no longer runs ci pipeline for nltk, they suggest migrating to travis-ci.com
At the time of writing there are no CI builds running for latest pull requests and merges.

Possible courses of action:
1. Migrate from travis-ci.org to travis-ci.com
2. Use github actions to run CI pipeline and builds

**Comment by tomaarsen** [comment]
Continuous Integration is now handled through GitHub Actions instead of Travis CI.
