### ISSUE TITLE
Suggestions and discussions regarding `pre-commit`

### ISSUE THREAD

**Issue by tomaarsen** [nltk/nltk#2775]
Hello!

Now that `pre-commit` has been in place since #2753, we should take a moment to reflect on it, and consider whether we want to remove or add certain hooks to it. This issue will be a place for hook suggestions and discussions.

Previously, discussion about `pre-commit` has occurred in #2744.
WIthin this issue, the following hooks were mentioned:
- [PyUpgrade](https://github.com/asottile/pyupgrade/): A hook to automatically upgrade syntax for newer verions of Python. I like the sound of this one.
- [isort](https://github.com/PyCQA/isort): Import sorting. I like the sound of this one.
- [black](https://github.com/psf/black): Python formatter, implemented if #2774 gets merged.

Beyond these, the `pre-commit` team has provided some more hooks, which can be found [here](https://github.com/pre-commit/pre-commit-hooks). Some of them I find particularly interesting, such as:
- `debug_statements`: Check for debugger imports and py37+ `breakpoint()` calls in python source.
- `no-commit-to-branch`: Protect specific branches from direct checkins.
- Hooks that attempt to load specific files to verify syntax. (`check-xml`, `check-yaml`, `check-toml`, `check-json`)

Some other hooks provided by the `pre-commit` team have niche uses, but might be nice, such as:
- `check-case-conflict`: Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
- `check-merge-conflict`: Check for files that contain merge conflict strings.

Other custom hooks I've used myself are:
- [Bandit](https://github.com/PyCQA/bandit): For security vulnerabilities. Might not be very applicable for nltk.
- [mypy](https://github.com/pre-commit/mirrors-mypy): Add type hints ([PEP 484](https://www.python.org/dev/peps/pep-0484/)) (e.g. `def func(n: int) -> bool`) and statically check correctness of these type hints. I like this one, but it might require solving a bunch of warnings before it can be incorporated into `pre-commit`.
- [pylint](https://github.com/PyCQA/pylint): Very interesting if you're very interested in improving code quality, but this hook will only pass if there are no warnings, meaning that a developer can only push their commit if all warnings are resolved. Currently, there are roughly 15000 warnings.
- [codespell](https://github.com/codespell-project/codespell): Points out potential spelling errors in code comments, with the option to automatically resolve them. Interesting, but often marks correct words as incorrect.

Once again, this issue is meant for suggestions and discussion, so feel free to voice your opinions and recommendations. Together we can figure out what works best for nltk and its contributors.

**Comment by dannysepler** [comment]
Love this. I think you chose some great hooks to chat about.

Input coming from my time enabling various pre-commit hooks at my company: I believe that whoever adds a pre-commit should also be responsible for linting the whole repository with it in the same merge request. Contributors found it odd to have hooks modify code not pertaining to their diffs, and reviewers found it hard to review diffs which had linting changes.

If it's okay with you, I'd maybe consider either running black on the whole repo now, or reverting that diff until you can.

Happy to talk through my thoughts on each hook individually either here or on slack!

**Comment by tomaarsen** [comment]
> Input coming from my time enabling various pre-commit hooks at my company: I believe that whoever adds a pre-commit should also be responsible for linting the whole repository with it in the same merge request. 
> 
> If it's okay with you, I'd maybe consider either running black on the whole repo now, or reverting that diff until you can.

I agree wholeheartedly. I'd like to point your attention to #2773. In this PR, I ran `black` over the whole codebase, while asking the question of *"should we add black to pre-commit?"*. This then caused #2774. So, at no point did we have `black` in pre-commit while the codebase itself was not blacked. 

In the future, I recommend the following strategy:
* Follow the regular git flow, forking, creating your own branch, etc.
* Add the new functionality to `pre-commit` by modifying `.pre-commit-config.yaml`.
* Run `pre-commit` on *all files* to ensure that the entire codebase will be updated from that point onwards:
```
pre-commit run --all-files
```
 * Update/resolve warnings if they require manual changes. (e.g. formatting warnings that can't be automatically resolved)
   This prevents developers from being blocked from committing because something they didn't write can't pass the `pre-commit` verifications.
 * Run tests to ensure that nothing big broke. (e.g. via tox, pytest)
 * Give all changes a manual look-over. A lot of these hooks are fairly consistent, but most *can* fail to give incorrect results in some situations. For example, `black` failed in a few situations too.
 * Commit all of the changes - i.e. the updated `.pre-commit-config.yaml` and the updated codebase.
 * Create a PR for this addition, and be ready to assist in merge conflicts if possible, as you're destined to get some with different PR's when updating the entire codebase.

**Comment by dannysepler** [comment]
Oh gosh that's so embarrassing, thank you for correcting me!!

**Comment by dannysepler** [comment]
Coming back to this, I'm most excited about "pyupgrade" and "isort" personally.

"mypy" is also great, but you're right that it requires work to enable. If we plan on add type-hinting to nltk though, it may be easier to add mypy before so that we don't have to re-annotate things later.

**Comment by tomaarsen** [comment]
I quickly ran `mypy` over the `nltk` folder, which resulted in:
```diff
-Found 134 errors in 58 files (checked 345 source files)
```
(Note, I believe it's common for fixing an error to result in more errors for `mypy`)

If I run `mypy` with `--strict` (which disallows functions that do not have typing information, etc.), then `mypy` outputs:
```diff
-Found 16848 errors in 326 files (checked 345 source files)
```
Ouch. That's a lot of improvements yet to be made.

---

I'll  have a look at what `pyupgrade` would do to `nltk`.

Oh, one last thing, if we're going to add hooks one-by-one, then let's do so sequentially. As in, not create a bunch of different PR's based on the same one develop head, as that will result in merge conflict hell. So, we should create a pre-commit hook PR after the previous one has been merged.

**Comment by tomaarsen** [comment]
`pyupgrade` seems to be a nice addition to modernize the NLTK codebase somewhat. It seems to err on the side of caution, only modifying where its sure we'll be happy with the results. I've created the above PR to add it to pre-commit, like suggested.

On another note, @iliakur mentioned [here](https://github.com/nltk/nltk/pull/2774#issuecomment-892528031) that pre-commit hooks ought to be added to the CI as well. This can supposedly be done with [pre-commit.ci](https://pre-commit.ci/), which mentions adding `ci:` section to `.pre-commit-config.yaml`. In my opinion this is definitely an interesting option.

**Comment by dannysepler** [comment]
pre-commit ci would be awesome, i haven't used that before. don't forget that the author [offered to help us](https://github.com/nltk/nltk/pull/2747) if we ever need help with implementation details!

one thing to also consider is using the `.git-blame-ignore-revs` feature as described [here](https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame) to ignore these commits as we're making them. that said, the feature is a bit misleading in that github for instance [doesn't honor this feature yet](https://github.community/t/support-ignore-revs-file-in-githubs-blame-view/3256) in its git blame (which is how i use git blame). so i'm okay not using this as well

**Comment by tomaarsen** [comment]
@dannysepler If I understood that blogpost correctly, then it proposes the inclusion of a file in the root directory called `.git-blame-ignore-revs`, so that users can use `git blame --ignore-revs-file .git-blame-ignore-revs <file>`.
However, I don't know if `git blame` is commonly used, and less so if people would actually use `git blame --ignore-revs-file .git-blame-ignore-revs <file>`.
That said, if someone has the time to collect all (recent-ish) commits that apply some mass formatting, or just formatting in general, and place those hashes in such a file, then I'm sure it would be appreciated.

I'm also copy pasting this from a comment over at #2777, as it pertains to pre-commit:
> Something i learned recently, a lot of calls of dictionary `.keys()` is unnecessary. there's a funky pre-commit hook that undoes this https://github.com/mxr/unkey -- but i think we could also just call this hook on the whole nltk repo without actually adding it to pre-commit

I'd like to hear thoughts on this. Should we run it over the codebase, and if so, should it be added to pre-commit? Perhaps some would argue that it increases readability of those who don't know that `min({2:3, 1:4}.keys())` is equivalent to `min({2:3, 1:4})`.

**Comment by tomaarsen** [comment]
> On another note, @ iliakur mentioned [here](https://github.com/nltk/nltk/pull/2774#issuecomment-892528031) that pre-commit hooks ought to be added to the CI as well. This can supposedly be done with [pre-commit.ci](https://pre-commit.ci/), which mentions adding `ci:` section to `.pre-commit-config.yaml`. In my opinion this is definitely an interesting option.

I've just found out it's also possible to simply add 
```yaml
  - uses: pre-commit/actions@v2.0.0
```
to `steps` in a GitHub Actions .yml file. Perhaps this can simply be added to the `cache_nltk_data` job in our https://github.com/nltk/nltk/blob/develop/.github/workflows/ci.yaml. 
See https://github.com/mxr/unkey/blob/master/.github/workflows/pre-commit.yml for an example of this.

**Comment by tomaarsen** [comment]
I think we've exhausted this discussion - I think our `pre-commit` is looking good (already).
