### ISSUE TITLE
Communication between NLTK team

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#2776]
I would like to resume our use of slack for communication between members of the NLTK team (nltk.slack.com). To participate, please [email me](mailto:steven.bird@cdu.edu.au), so I can email an invitation, thanks.

@iliakur @tomaarsen @dannysepler @purificant

**Comment by tomaarsen** [comment]
Sounds good, I've sent you an email just now.

**Comment by purificant** [comment]
I've sent an email when the issue was first opened, and another when it was closed. Not sure if this is still relevant? @stevenbird

**Comment by stevenbird** [comment]
Sorry @purificant I don't see any emails from you. Would you please resend and include your github id so I can search my email for it?

**Comment by purificant** [comment]
Done, thanks!

**Comment by stevenbird** [comment]
Ah, no, still nothing.
steven.bird@cdu.edu.au
