### ISSUE TITLE
Can't find nltk.examples module

### ISSUE THREAD

**Issue by lailacampos** [nltk/nltk#2783]
I'm trying to follow the instructions at [Examples for Portuguese Processing](http://www.nltk.org/howto/portuguese_en.html) but trying to import from `nltk.examples.pt` gives me the following error:
`ModuleNotFoundError: No module named 'nltk.examples'`

Is there an alternative way to import all portuguese corpora? Is there a list somewhere listing all of them?
Do I need to import by id from `nltk.corpus`?

Thank you in advance

**Comment by tomaarsen** [comment]
The `examples` folder was removed from NLTK. If you are interested in the examples that were present under `nltk.examples.pt`, you can have a look at them [here](https://github.com/nltk/nltk/blob/173f32929ff22e6f42d03e6a73d1fac86e95f20d/nltk/examples/pt.py).

Unlike the examples, the portuguese corpora are still present, e.g.: `machado`, `mac_morpho` and `floresta`. 
They can be imported just like the book suggests, from the `Reading corpora` section onwards. 

So, in short, the section up to `Reading Corpora` on [Examples for Portuguese Processing](https://www.nltk.org/howto/portuguese_en.html) is deprecated, and beyond that point everything should still work.

---

The `examples` folder was removed in 7c2a65da4d2b97d99f2a11384d00fac00cd6d598 back in 2014. As a result, people are unable to follow [this](https://www.nltk.org/howto/portuguese_en.html) part of the book. Furthermore, the removal has previously caused issues with doctests, as we have tests that rely on importing `examples.pt`:
https://github.com/nltk/nltk/blob/eeece6ca5bb2d8c26b6821db6f46d63e90823818/nltk/test/portuguese_en.doctest#L21-L32

`setup_module` from `portuguese_en_fixt` skips all tests from `portuguese_en.doctest` with this:
https://github.com/nltk/nltk/blob/eeece6ca5bb2d8c26b6821db6f46d63e90823818/nltk/test/portuguese_en_fixt.py#L1-L4

So, perhaps it would be a good idea to reintroduce `examples.pt`? To allow the tests again, and to allow users to follow the book again. Note that we still have other files very similar to the deleted `pt.py`, such as [nltk/book.py](https://github.com/nltk/nltk/blob/develop/nltk/book.py).

**Comment by lailacampos** [comment]
I see. I will import directly from nltk.corpus then.
Thank you.

**Comment by stevenbird** [comment]
Thanks @tomaarsen
