### ISSUE TITLE
NLTK installation failed

### ISSUE THREAD

**Issue by snagpal1932** [nltk/nltk#2796]
![image](https://user-images.githubusercontent.com/88143204/132080065-cbec8e76-252a-4654-b7fa-fb31b0bc29e8.png)

**Comment by purificant** [comment]
Please make sure that you can access [https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/comtrans.zip](https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/comtrans.zip) from your machine and in python.

Example code to verify that python can access the necessary data:
```python
from  urllib.request import urlopen
response = urlopen('https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/comtrans.zip')
print(response.status, response.reason)
```

or from linux command line:
```sh
wget https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/comtrans.zip
```

**Comment by stevenbird** [comment]
Thanks @purificant
