### ISSUE TITLE
How to create a custom model for a trigram tagger?

### ISSUE THREAD

**Issue by mmargegaj** [nltk/nltk#2797]

**Comment by mmargegaj** [comment]
I did try the following custom model:
```
from nltk.tag.sequential import TrigramTagger
trimodel = {
		((), 'te'): 'folje', (('folje',), 'kisha'): 'folje', (('folje',), 'fituar'): 'folje',
	}
tritagger = TrigramTagger(model=trimodel)
print(tritagger.tag(['te', 'kisha', 'fituar']))
```

but output was:
```[('te', 'folje'), ('kisha', 'folje'), ('fituar', None)]```

**Comment by tomaarsen** [comment]
@margegaj24 
I recommend using a list of tagged sents as a `train` parameter instead, like so:

```python
from nltk.tag.sequential import TrigramTagger, BigramTagger, DefaultTagger, UnigramTagger
from nltk.corpus import brown

# Get all but the last 100 of the tagged sentences, and last 100 tagged sentences respectively
train = brown.tagged_sents()[:-100]
test = brown.tagged_sents()[-100:]

def_tagger = DefaultTagger('NN')
uni_tagger = UnigramTagger(train, backoff=def_tagger)
bi_tagger = BigramTagger(train, backoff=uni_tagger)
tri_tagger = TrigramTagger(train, backoff=bi_tagger)

accuracy = tri_tagger.evaluate(test)
print(f"Accuracy: {accuracy * 100:.4f}% between 100 test sentences")
```

However, if you want to use a model, then the format is:
```python
{
    ((prev_prev_tag, prev_tag), tok_string): tok_tag,
    ...
}
```

I can easily observe the model that was trained in the top-most example by printing `tri_tagger._context_to_tag`. This allows me to quickly give you an example, such as this:
```python
{
    ...
    (('VBN', 'CC'), 'counted'): 'VBN',
    (('VBN', 'CC'), 'damaged'): 'VBN',
    (('VBN', 'CC'), 'entered'): 'VBN',
    ...
}
```

Important to keep in mind, the key is a *tuple* of a *tuple* of the 2 previous **tags** (not the tokens, but their tags!), and then the token for the current word. The value for this key is then the tag. So, in my last example, if we are tagging, and we encounter the token `entered`, while the previous two tokens were tagged as `VBN` and `CC` respectively, *only then* will `entered` be tagged as `VBN`.

I hope that's clear.

**Comment by mmargegaj** [comment]
So it doesn't take into consideration the previous token strings at all? Only the previous tokens tags, right?

**Comment by tomaarsen** [comment]
@margegaj24 That's exactly it, yes.

**Comment by mmargegaj** [comment]
There is no other way to take the token strings into consideration, except passing sentences as train parameter?

P.S I am asking because I want to create taggers for Albanian language which is not available in nltk.

**Comment by tomaarsen** [comment]
NLTK supplies many different Taggers which work in different ways. Perhaps there is one that better suits your needs:
https://github.com/nltk/nltk/blob/fb2e2f21728b4dc0df710a00ec59d0a3797d769e/nltk/tag/__init__.py#L70-L92

Beyond that, perhaps StackOverflow is a better place for questions like these.
