### ISSUE TITLE
xfst interface

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#28]
Add an interface to the Xerox Finite State Toolkit.
There are Python bindings for xfst; can we redistribute this code?

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=73</p>

**Comment by alvations** [comment]
Possibly, @vchahun wrapper could be appropriate port for nltk: https://github.com/vchahun/pyxfst to add to `nltk.parse`.

Volunteers?

**Comment by stevenbird** [comment]
Closing, as we don't have capacity to take this on.
