### ISSUE TITLE
Possible problems with both the Pk and WindowDiff computations

### ISSUE THREAD

**Issue by samblasiak** [nltk/nltk#280]
In the current Pk computation, `prob_miss = n_miss / n_considered_seg` should be `prob_miss = n_miss / (n_considered_seg - n_same)`. Similarly,  the computation for prob_false_alarm should be `prob_false_alarm = n_false_alarm / n_miss`.
In the Beeferman et. al. paper, the second formula in section 8.1 computes the same value as the first formula. The prob_miss and prob_false_alarm are conditional probabilities, so should not be estimated by dividing by the total number of considered segments

The current windowdiff function computes the sum of abs(# boundaries ref - # boundaries test) but should actually be the sum of  1[abs(# boundaries ref - # boundaries test)>0]. In the windowdiff paper, the sentence  immediately preceding Equation 1 in section 3 make the formula clearer.

The fixes for these are easy, and I can contribute them if you let me.

**Comment by xim** [comment]
I haven't looked into the code yet, don't know if @DavidDoukhan accounted for these factors somehow. But I'd love to see the fixes as a pull request, if you'd be willing to make it one? ^_^

**Comment by samblasiak** [comment]
Sure, I can do that.
I'm new to git, so it may take me a little while to figure everything out.

**Comment by kmike** [comment]
As for windowdiff, it seems that the version in NLTK is a weighted version of the windowdiff metric. Later in paper:

> We explored a weighted version of this metric, in which the penalty is weighted by the difference |ri −ai|. However, the results of the simulations were nearly identical with those of the non-weighted version of WindowDiff, so we do not consider the weighted version further.

So I think the windowdiff metric is valid, but the documentation may be better, and there is a question if it should be default. While in the original paper the unweighted version is used, in further papers it is not uncommon to refer to weighted version of windowdiff (e.g. http://www.researchgate.net/publication/4302298_On_Evaluation_Methodologies_for_Text_Segmentation_Algorithms ). On the other side, WinPR paper ( http://www.aclweb.org/anthology-new/N/N12/N12-1038.pdf ) argues that "The comparison (>0) is sometimes forgotten, which produces strange values".

**Comment by DavidDoukhan** [comment]
In my point of view, NLTK WindowDiff is not weighted.
I think there are 2 bugs in the implementation:

for i in range(len(seg1) - k):
should be corrected to for i in range(len(seg1) - k + 1):

and the result wd should be returned divided by len(seg1) - k + 1

I can do the corresponding pull request

2013/1/17 Mikhail Korobov notifications@github.com

> As for windowdiff, it seems that the version in NLTK is a weighted version
> of the windowdiff metric. Later in paper:
> 
> We explored a weighted version of this metric, in which the penalty is
> weighted by the difference |ri -ai|. However, the results of the
> simulations were nearly identical with those of the non-weighted version of
> WindowDiff, so we do not consider the weighted version further.
> 
> So I think the windowdiff metric is valid, but the documentation may be
> better, and there is a question if it should be default. While in the
> original paper the unweighted version is used, in further papers it is not
> uncommon to refer to weighted version of windowdiff (e.g.
> http://www.researchgate.net/publication/4302298_On_Evaluation_Methodologies_for_Text_Segmentation_Algorithms). On the other side, WinPR paper (
> http://www.aclweb.org/anthology-new/N/N12/N12-1038.pdf ) argues that "The
> comparison (>0) is sometimes forgotten, which produces strange values".
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/280#issuecomment-12363575.

## 

David Doukhan

**Comment by DavidDoukhan** [comment]
I confirm the first bug:

In [7]: windowdiff('0000', '0001', 4)
Out[7]: 0

In [8]: windowdiff('0000', '0010', 4)
Out[8]: 0

I guess these two calls should return the same result....

2013/1/17 David Doukhan david.doukhan@gmail.com

> In my point of view, NLTK WindowDiff is not weighted.
> I think there are 2 bugs in the implementation:
> 
> for i in range(len(seg1) - k):
> should be corrected to for i in range(len(seg1) - k + 1):
> 
> and the result wd should be returned divided by len(seg1) - k + 1
> 
> I can do the corresponding pull request
> 
> 2013/1/17 Mikhail Korobov notifications@github.com
> 
> > As for windowdiff, it seems that the version in NLTK is a weighted
> > version of the windowdiff metric. Later in paper:
> > 
> > We explored a weighted version of this metric, in which the penalty is
> > weighted by the difference |ri -ai|. However, the results of the
> > simulations were nearly identical with those of the non-weighted version of
> > WindowDiff, so we do not consider the weighted version further.
> > 
> > So I think the windowdiff metric is valid, but the documentation may be
> > better, and there is a question if it should be default. While in the
> > original paper the unweighted version is used, in further papers it is not
> > uncommon to refer to weighted version of windowdiff (e.g.
> > http://www.researchgate.net/publication/4302298_On_Evaluation_Methodologies_for_Text_Segmentation_Algorithms). On the other side, WinPR paper (
> > http://www.aclweb.org/anthology-new/N/N12/N12-1038.pdf ) argues that
> > "The comparison (>0) is sometimes forgotten, which produces strange values".
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/280#issuecomment-12363575.
> 
> ## 
> 
> David Doukhan

## 

David Doukhan

**Comment by DavidDoukhan** [comment]
2013/1/17 David Doukhan david.doukhan@gmail.com

> I confirm the first bug:
> 
> In [7]: windowdiff('0000', '0001', 4)
> Out[7]: 0
> 
> In [8]: windowdiff('0000', '0010', 4)
> Out[8]: 0
> 
> I guess these two calls should return the same result....

Should return 1 instead of 0

> 2013/1/17 David Doukhan david.doukhan@gmail.com
> 
> > In my point of view, NLTK WindowDiff is not weighted.
> > I think there are 2 bugs in the implementation:
> > 
> > for i in range(len(seg1) - k):
> > should be corrected to for i in range(len(seg1) - k + 1):
> > 
> > and the result wd should be returned divided by len(seg1) - k + 1
> > 
> > I can do the corresponding pull request
> > 
> > 2013/1/17 Mikhail Korobov notifications@github.com
> > 
> > > As for windowdiff, it seems that the version in NLTK is a weighted
> > > version of the windowdiff metric. Later in paper:
> > > 
> > > We explored a weighted version of this metric, in which the penalty is
> > > weighted by the difference |ri -ai|. However, the results of the
> > > simulations were nearly identical with those of the non-weighted version of
> > > WindowDiff, so we do not consider the weighted version further.
> > > 
> > > So I think the windowdiff metric is valid, but the documentation may be
> > > better, and there is a question if it should be default. While in the
> > > original paper the unweighted version is used, in further papers it is not
> > > uncommon to refer to weighted version of windowdiff (e.g.
> > > http://www.researchgate.net/publication/4302298_On_Evaluation_Methodologies_for_Text_Segmentation_Algorithms). On the other side, WinPR paper (
> > > http://www.aclweb.org/anthology-new/N/N12/N12-1038.pdf ) argues that
> > > "The comparison (>0) is sometimes forgotten, which produces strange values".
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/280#issuecomment-12363575.
> > 
> > ## 
> > 
> > David Doukhan
> 
> ## 
> 
> David Doukhan

## 

David Doukhan

**Comment by kmike** [comment]
As for "weighted/unweighted": this is a terminology issue, but ftp://ftp.cs.toronto.edu/pub/gh/Marathe-MSc-paper.pdf - consider "weighted/unweighted" based on presence of ">0" clause (I read the original windowdiff paper the same way).

You're correct that the result shoud we divided! 

I don't understand though why we need len(seg1) - k + 1. In the paper i is in range `[1, .., N-k]` (and I assume they use 1-based indices for ref and hyp); in NLTK i is in range `[0, ..., N-k-1]` (and slicing uses 0-based indices).

**Comment by kmike** [comment]
FYI: there are many metrics (including windowdiff) implemented in Python as a MIT-licensed package here: https://github.com/cfournie/segmentation.evaluation/tree/master/src/python/main

**Comment by DavidDoukhan** [comment]
I agree with your remark about weighted/unweighted variants of WindowDiff.
NLTK's implementation refers to the weighted variant, and we should
explicit this information.

Concerning the value to be used to divide:

consider we have a segmentation length of 5 units (len(seg1))
A spanning window of 4 units (k=4)
Two comparisons will be done : N - K + 1 = 2
And I guess this is the number that should be used to divide.

2013/1/17 Mikhail Korobov notifications@github.com

> FYI: there are many metrics (including windowdiff) implemented in Python
> as a MIT-licensed package here:
> https://github.com/cfournie/segmentation.evaluation/tree/master/src/python/main
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/280#issuecomment-12366211.

## 

David Doukhan

**Comment by DavidDoukhan** [comment]
I did a pull request to fix these issues.
Let me know about it.

2013/1/17 David Doukhan david.doukhan@gmail.com

> I agree with your remark about weighted/unweighted variants of WindowDiff.
> NLTK's implementation refers to the weighted variant, and we should
> explicit this information.
> 
> Concerning the value to be used to divide:
> 
> consider we have a segmentation length of 5 units (len(seg1))
> A spanning window of 4 units (k=4)
> Two comparisons will be done : N - K + 1 = 2
> And I guess this is the number that should be used to divide.
> 
> 2013/1/17 Mikhail Korobov notifications@github.com
> 
> > FYI: there are many metrics (including windowdiff) implemented in Python
> > as a MIT-licensed package here:
> > https://github.com/cfournie/segmentation.evaluation/tree/master/src/python/main
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/280#issuecomment-12366211.
> 
> ## 
> 
> David Doukhan

## 

David Doukhan

**Comment by cfournie** [comment]
> > FYI: there are many metrics (including windowdiff) implemented in Python as a MIT-licensed package here: https://github.com/cfournie/segmentation.evaluation/tree/master/src/python/main

You are certainly welcome to use my WindowDiff implementation.

**Comment by DavidDoukhan** [comment]
Concerning the Pk metric, I may have provide a 100% misunderstood implementation.
According to the original paper (section 8.1) http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.43.9557&rep=rep1&type=pdf , the Pk should provide a penalty of about 0.5 to all degenerated segmentations (empty, full, randomized).

With the implementation I did:
print pk('1000' \* 100, '1' \* 400, 2)
print pk('1000' \* 100, '0' \* 400, 2)
r = list('1000' \* 100)
N.random.shuffle(r)
print pk('1000' \* 100, r, 2)

gives:
0.565323082141
0.0615636836452
0.177323006765

which seems false.

Using the explainations of http://homepages.inf.ed.ac.uk/jmoore/papers/slt2010.pdf in section 2.
I managed to obtain a much simpler implementation of the Pk having the same properties.

I may propose a fix in the next few hours
Sorry about that

**Comment by stevenbird** [comment]
The issues with WindowDiff were resolved in https://github.com/nltk/nltk/commit/160070fe2b46aa6fff1ec5a93924af4c957d2bcc
The issues with Pk are still unresolved.

**Comment by maraujo** [comment]
Hello Guys,
We do we have an possible fix in the next nltk commits? I'd really enjoy to use this metrics my lab research.
Here is a stackoverflow link:
http://stackoverflow.com/questions/24456056/python-nltk-windowdiff-and-pk-vs-python-segeval-windowdiff-and-pk
Thanks.
