### ISSUE TITLE
usage function: repair or drop?

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#2807]
Do we need to support this usage method?
https://github.com/nltk/nltk/blob/develop/nltk/util.py#L40

Here's a discussion of it's shortcomings:
https://github.com/nltk/nltk/pull/2801#discussion_r706567025

**Comment by stevenbird** [comment]
My preference is to drop anything non-essential when it is consuming scarce human resources to maintain.

**Comment by dannysepler** [comment]
I prefer dropping too. Especially since it's not used in actual source code, and since python has a builtin `help()` function which seems super similar!

**Comment by tomaarsen** [comment]
`usage` does seem like it's just a weaker `help()`. As far as I'm concerned, we can drop it.
It might be "proper" to change it to e.g.
```python
def usage(obj, selfname="self"):
    warnings.warn("nltk.usage(obj) is deprecated; use help(obj).", PendingDeprecationWarning)
    help(obj)
```
for the time being. 

However, do note that the warning will only be displayed if Python is ran with e.g. a `-Wd` flag to show warnings.
Then in some future version, we'll just remove the function all-together.
