### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [nltk/nltk#2809]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by purificant** [comment]
In the short term, you can reach me on purificant@tutanota.com and I'll share the details with the team. Thank you.

**Comment by purificant** [comment]
@JamieSlome Please see https://github.com/nltk/nltk/blob/develop/SECURITY.md which now contains an email address that you can use.
