### ISSUE TITLE
RegexpTagger fails to handle exception.

### ISSUE THREAD

**Issue by 12mohaned** [nltk/nltk#2817]
There is a bug in the RegexpTagger. It fails to handle exception in case of missing tag or regular expression. 

```
    def __init__(self, regexps, backoff=None):
        """ """
        super().__init__(backoff)
        try:
            self._regexps = [
                (
                    re.compile(regexp),
                    tag,
                )
                for regexp, tag in regexps
            ]
        except Exception as e:
            raise Exception(
                "Invalid RegexpTagger regexp:", str(e), "regexp:", regexp, "tag:", tag
            ) from e
```

The problem that both regexp and tag are not defined anywhere in the class, which is weird because it implies that the user should be notified with the missing tag or regular expression which is missing!. 

The possible solutions from POV are: 

- Simply remove the regexp and tag variables from the exception messae. 
- Check for the length of each tuple in the list and throw exception if length of one tuple is not two.

Maybe the Exception should be more meaningful like, "RegexpTagger expects tuple of size two(regexp, tag).

**Comment by stevenbird** [comment]
I think it is useful to catch regexp compilation errors and report them in this way. I think the situation you describe can only happen if an empty list of regexps is passed to the initialiser.

We do not systematically check the type or internal structure arguments passed to NLTK functions.

**Comment by 12mohaned** [comment]
I completely agree, but it is irrelevant to use un-defined variables. Also there is different cases where this behaviour can happens. For example, regexps = [(r'^-?[0-]', 'CD'), (r'(The|the|A|a|An|an)$', 'AT'), (r'.*able$',)], where the list contains a tuple that does not have a corresponding tag or vice versa.
