### ISSUE TITLE
WordNetLemmatizer in nltk.stem module

### ISSUE THREAD

**Issue by Beliefuture** [nltk/nltk#2818]
What's the parameter of WordNetLemmatizer.lemmatize() in nltk.stem module?
Turn to the document, what are the candidate value of the parameter **'pos'**?
![image](https://user-images.githubusercontent.com/62245023/134791412-1ff85ba5-5eb9-4859-a3f1-3b48bdd5a6fa.png)
The default value is 'Noun'. But use the function pos_tag() to get the pos of the word, the value appears to come from several options.

**Comment by tomaarsen** [comment]
This is indeed not particularly clear from the documentation. 
The `pos` parameter is `NOUN` by default, imported from here:
https://github.com/nltk/nltk/blob/277711ab1dec729e626b27aab6fa35ea5efbd7e6/nltk/corpus/reader/wordnet.py#L66

With other words, it is `"n"` by default.
Other valid options are `ADJ`, `ADJ_SAT`, `ADV` and `VERB`, which can be imported and used like so:
```python
>>> from nltk.corpus import wordnet as wn
>>> from nltk.stem import WordnetLemmatizer
>>> WordNetLemmatizer().lemmatize("boxing", wn.VERB)
"box"
```
However, feel free to simply use one of `"a", "s", "r", "n", "v"`.

**Comment by Beliefuture** [comment]
@tomaarsen Thanks for your reply. But when I use the function `pos_tag()` to get the pos of the word, the value appears to be several options below:

![image](https://user-images.githubusercontent.com/62245023/134829284-04f06d67-3d4d-41ae-a1af-d90ca58f9d95.png)

Does `WordNetLemmatizer().lemmatize(word, pos)` only support the 5 types: `ADJ, ADJ_SAT, ADV, NOUN, VERB`? Does this affect the accuracy because of the less option to choose from?

Moreover, does removing the punctuation between sentences first affect the result of `pos_tag()`? I sometimes find it can not specify the punctuation connected with the last word in the sentence.

**Comment by tomaarsen** [comment]
@Beliefuture Indeed, by default `pos_tag` returns tags from https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html, while `WordNetLemmatizer().lemmatize(word, pos)` uses Princeton University's WordNet, which uses `ADJ, ADV, NOUN, VERB`. I believe that the NLTK implementation has added support for `ADJ_SAT`.

That is why the tags from `pos_tag` and `WordNetLemmatizer().lemmatize` don't "match". 

However, you can specify another tagset:
```python
        >>> from nltk.tag import pos_tag
        >>> from nltk.tokenize import word_tokenize
        >>> pos_tag(word_tokenize("John's big idea isn't all that bad."), tagset='universal')
        [('John', 'NOUN'), ("'s", 'PRT'), ('big', 'ADJ'), ('idea', 'NOUN'), ('is', 'VERB'),
        ("n't", 'ADV'), ('all', 'DET'), ('that', 'DET'), ('bad', 'ADJ'), ('.', '.')]
```
Perhaps in this way you can map the tags to the values that `lemmatize` wants. (Assuming that you're attempting to tokenize and then lemmatize every token in your input)

As for your last question, I'm not 100% sure. However, `pos_tag` uses the PerceptronTagger by default, and that tagger does take into account the tags of previous words.
