### ISSUE TITLE
emojis are not tokenized very well

### ISSUE THREAD

**Issue by fcbond** [nltk/nltk#2829]
Maybe add something like this as a pre or post processing step?

It might make sense to download the emoji list and store it as part of the build, so people do not need to load the emojis module, ...

```
import emoji
from emoji import unicode_codes
import re


EMOJI_UNICODE = unicode_codes.EMOJI_UNICODE['en']
emojis = sorted(EMOJI_UNICODE.values(), key=len, reverse=True)
print (emojis, sep='\n')
emoji_regexp = f"({'|'.join(re.escape(u) for u in emojis)})"
EMOJI_XL = re.compile(rf"\B({emoji_regexp})", flags=re.UNICODE)
EMOJI_XR = re.compile(rf"({emoji_regexp})\B", flags=re.UNICODE)
EMOJI_WL = re.compile(rf"(\w)({emoji_regexp})", flags=re.UNICODE)
EMOJI_WR = re.compile(rf"({emoji_regexp})(\w)", flags=re.UNICODE)
EMOJI_REGEX = re.compile(rf"({emoji_regexp})", flags=re.UNICODE)

def split_emoji(text):
    text = EMOJI_REGEX.sub(r' \1 ', text)
    text = text.replace('  ', ' ')
    return text

test =  "🤔 🙈 me así, se😌 ds 💕👭👙 hello 👩🏾‍🎓 emoji hello 👨‍👩‍👦‍👦 how are 😊 you today🙅🏽🙅🏽"
#test = "They are going to start a direct flight soon😠"

print(test)

print(split_emoji(test))
```

**Comment by tomaarsen** [comment]
I'm in favor of this, as long as it doesn't make the tokenization considerably slower. I don't think it would have to. 
Perhaps a good place for it would be to include it in the TweetTokenizer? The regexps for those are defined [here](https://github.com/nltk/nltk/blob/a31de6c687165afe64a490053c73c8e0b20ff6db/nltk/tokenize/casual.py#L146).

I would also prefer not having additional dependencies for this, but perhaps the dependency allows us to automatically update to newer emoji lists. After all, they're up to v14.0 now, and will continue updating.

**Comment by tomaarsen** [comment]
I believe #2843 has significantly improved Emoji tokenization (for TweetTokenizer), so I'll close this accordingly. Feel free to let it be known if there is still some issue with Emoji tokenization that was overlooked.
