### ISSUE TITLE
word_tokenize splits Pokémon into "pok" and 'émon"

### ISSUE THREAD

**Issue by SeeTwoDev** [nltk/nltk#2837]
This is without specifying a language, so i assume english by default.

Is there a workaround to this?

**Comment by 12mohaned** [comment]
Maybe you are using an old version. The word_tokenize tokenize Pokémon into ['Pokémon'], without splitting it into two words. Try to update to the recent NLTK version. Or provide more context. For example, the sentence that contains the word. 

Regards.

**Comment by tomaarsen** [comment]
Like @12mohaned, I am unable to reproduce this issue. 
```python
>>> import nltk
>>> nltk.word_tokenize("Pokémon")
['Pokémon']
>>> nltk.sent_tokenize("Pokémon") 
['Pokémon']
```

Perhaps you could post your NLTK version:
```python
>>> import nltk
>>> nltk.__version__
3.6.4
```

**Comment by tomaarsen** [comment]
If you experience this issue again, then feel free to respond or make a new issue, but I'll close this for the time being, as we cannot reproduce this.
