### ISSUE TITLE
text.generate() causes AssertionError

### ISSUE THREAD

**Issue by Shkryob** [nltk/nltk#285]
To replicate:

---

import nltk
from nltk.book import *
text1.generate()

What is shown:

---

Building ngram index...

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    text1.generate()
  File "C:\Program Files\Python\lib\site-packages\nltk\text.py", line 382, in generate
    self._trigram_model = NgramModel(3, self, estimator)
  File "C:\Program Files\Python\lib\site-packages\nltk\model\ngram.py", line 81, in __init__
    assert(isinstance(pad_left, bool))
AssertionError

To fix:

---

in file https://github.com/nltk/nltk/blob/master/nltk/text.py in line 383 please _change_:
self._trigram_model = NgramModel(3, self, estimator)
_to_:
self._trigram_model = NgramModel(3, self, estimator=estimator)

Thank you for your time!

**Comment by smicky** [comment]
Thanks for the fix! Using nltk data in reading Natural Language Processing with Python, by Bird et al.

**Comment by stevenbird** [comment]
This was a bug in nltk 2.0.2. The next version is coming out any day now.  In the meantime, you could try overwriting your copies of these files:
https://github.com/nltk/nltk/blob/master/nltk/model/ngram.py
https://github.com/nltk/nltk/blob/master/nltk/text.py

**Comment by jagatsastry** [comment]
Thanks Steven. I restarted the python interpreter (after editing the files) and it started working. 
And thanks a ton for the book and the toolkit.
