### ISSUE TITLE
nltk 3.6.4 is "yanked" on PyPI

### ISSUE THREAD

**Issue by asishm-wk** [nltk/nltk#2850]
nltk 3.6.4 is currently yanked on PyPI. I don't see any issues except discussing why it was yanked. I see #2833 is tagged as critical but it does not have any references to the release being yanked from PyPI.

It may be helpful to pin something explaining the issue until a new release is pushed.

![image](https://user-images.githubusercontent.com/81247426/136394357-349d67dd-24d5-40d0-b20c-ccf64e382cdc.png)

**Comment by tomaarsen** [comment]
That is indeed the reason that the release has been yanked. I've pinned the issue for now. I'll post an update there. Thank you!
There should be a new release in the coming weeks. Let me know if it's sufficient. I'll close this under the assumption that it is.

**Comment by asishm-wk** [comment]
sounds good, thank you!

**Comment by purificant** [comment]
It's a precaution specifically for users who may upgrade to 3.6.4 without using the latest version of `regex` package. So long as you have an up to date regex, it's fine. The next release will enforce the minimal `regex` version.
