### ISSUE TITLE
Add `CITATION.cff` file to repository 

### ISSUE THREAD

**Issue by Joozty** [nltk/nltk#2874]
Github has a built-in support for citation. Can you please consider adding  CITATTION.cff file to your repository so we can easy cite your work?

Info:
https://citation-file-format.github.io/
https://twitter.com/natfriedman/status/1420122675813441540?lang=en

**Comment by tomaarsen** [comment]
Oooh, very interesting. I wasn't aware that this functionality was added. For the time being, https://github.com/nltk/nltk#citing can be used, but I'd love to get the `CITATION.cff` in.

**Comment by tomaarsen** [comment]
This might be slightly trickier than I had hoped. The `CITATION.cff` file requires a `version` parameter, which states "The version of the software". This would need to be updated for every release. It's not the end of the world, but it's not ideal either...

https://github.com/citation-file-format/citation-file-format/blob/1.1.0/README.md#software-citation-metadata-required

**Comment by stevenbird** [comment]
We already have to update the version [in two places](https://github.com/nltk/nltk/blob/develop/RELEASE-HOWTO.txt#L16), so adding a third doesn't particularly bother me.
