### ISSUE TITLE
Using the latest Wordnet 2021 version

### ISSUE THREAD

**Issue by ekaf** [nltk/nltk#2885]
Open English Wordnet 2021 (https://github.com/globalwordnet/english-wordnet) was recently released in a format compatible with NLTK:

https://john.mccr.ae/oewn2021/english-wordnet-2021.zip

It can work out-of-the-box with NLTK's wordnet.py module, by just replacing nltk_data/corpora/wordnet. However, a few thousand problems have already been reported in 3 issues: (https://github.com/globalwordnet/english-wordnet/issues/773#issue-1046786129, https://github.com/globalwordnet/english-wordnet/issues/774#issue-1047054055 and https://github.com/globalwordnet/english-wordnet/issues/777#issue-1052949347). In particular, no parser would be able to separate the examples  from the definitions.

An alternative package with fewer problems is available from the X-englishwordnet project (https://github.com/x-englishwordnet/wndb):

https://x-englishwordnet.github.io/wndb/xewn_compat.zip

This package has quoted examples, and only half the sense number instability, compared with the official package. So the dilemma is which package to use: the official or the alternative?

Open English Wordnet has anounced that support for this legacy database format will be discontinued sometime in the future,
and recommends using the XML format instead. However, this appears to have the same sense stability problems as the WNDB format used by NLTK.

**Comment by ekaf** [comment]
Since https://github.com/globalwordnet/english-wordnet/issues/777#issue-1052949347 was recently solved, the only problem remaining is the sense ordering. So the difference between the candidate packages is not so big now, and the safest choice might be to use the official package at https://john.mccr.ae/oewn2021/english-wordnet-2021.zip

**Comment by ekaf** [comment]
OEWN 2021 is now supported through https://github.com/nltk/nltk/pull/2860

**Comment by LifeIsStrange** [comment]
@ekaf So are there remaining problems with OEWN 2021 support ? 
Has this been solved ? " the only problem remaining is the sense ordering"

**Comment by ekaf** [comment]
The present issue is closed because the problem is not in NLTK support, but in OEWN 2021 itself, as explained in the issues cited above (globalwordnet/english-wordnet#773 (comment), globalwordnet/english-wordnet#774 (comment)), which are still open.
