### ISSUE TITLE
Articles-about-NLT

### ISSUE THREAD

**Issue by DanielBorgesOliveira** [nltk/nltk#2887]
Hi guys,

There are some broken links in the articles wiki page [https://github.com/nltk/nltk/wiki/Articles-about-NLTK](https://github.com/nltk/nltk/wiki/Articles-about-NLTK).
I suggest repairing the links and I would like to ask if it is possible to send me the articles.

Thank you very much.

**Comment by tomaarsen** [comment]
> I would like to ask if it is possible to send me the articles.

Whenever I encounter broken links, my go-to is to look for an Internet Archive, e.g. https://archive.org/. Within the search option, I select "Search archived web sites", and I paste in the now broken link, e.g. https://aclweb.org/anthology-new/W/W08/W08-0208.pdf.

Doing so gives me: https://web.archive.org/web/*/https://aclweb.org/anthology-new/W/W08/W08-0208.pdf

Here I can select between 45 snapshots of this website. If I select one from e.g. 2011, then it gives me the following .pdf file: https://web.archive.org/web/20110411234725/https://aclweb.org/anthology-new/W/W08/W08-0208.pdf

Hopefully this method helps in recovering some of the original resources. 

That all said - it would be wonderful if these links can be fixed somehow, but I fear that most of these pages simply aren't hosted on those websites anymore.

**Comment by mohit-marathe** [comment]
Hello @tomaarsen! I have found all the working links except one in the articles wiki page. Now how do I fix those? I don't have git access to edit the wiki page. I tried forking this whole project but it is not forking the wiki page.

**Comment by tomaarsen** [comment]
I must say that I'm not really sure. I've not interacted with the wiki frequently. However, when I go there, I see an option to "Clone this wiki locally", and it's accompanied with the following url: `https://github.com/nltk/nltk.wiki.git`. That said, I'm not sure it's possible to open a Pull Request for a wiki page. 

If it's just one link that you would like to see fixed, then perhaps you can just create an comment or issue with the location of the broken URL and the fixed URL, so I can have a look at it.

**Comment by mohit-marathe** [comment]
Thanks for the quick response, @tomaarsen ! Yeah I have checked it there is no option to make a PR for a wiki page. 
And there are 8 broken links out of which I have found 7 working links. So should I raise an issue for this?

**Comment by tomaarsen** [comment]
Yes please!

**Comment by mohit-marathe** [comment]
Hey @tomaarsen, here is the issue I created. Please see to it. Thanks!
https://github.com/nltk/nltk/issues/3076

**Comment by tomaarsen** [comment]
Closed via #3076. Thank you @mohit-marathe for the fixes!
