### ISSUE TITLE
Link to book in python documentation wrong

### ISSUE THREAD

**Issue by 0-wiz-0** [nltk/nltk#2891]
Not sure if this is a bug in the documentation or in the DNS/web server setup.
The python documentation for nltk says:
```
    Steven Bird, Ewan Klein, and Edward Loper (2009).
    Natural Language Processing with Python.  O'Reilly Media Inc.
    http://nltk.org/book
```
but this link does not work, `https://www.nltk.org/book/` does.

**Comment by dannysepler** [comment]
You're right, thanks! We recently revamped our website, and this must have slipped through the cracks. Not to worry, it's an easy fix :)
