### ISSUE TITLE
nltk.corpus.gutenberg help fails if punkt corpus is not downloaded

### ISSUE THREAD

**Issue by joneill87** [nltk/nltk#2911]
## The Issue

It seems that the call to help on the nltk.corpus.gutenberg module has an undocumented dependency on the nltk.corpus.punkt module. It is currently not possible to view the help info on the gutenberg module without downloading punkt.

This appears to be specific to the PlaintextCorpusReader class. No error is thrown when loading the movie_reviews corpus.

## Expected Behaviour

The help information should be available without requiring the user to install any additional packages.

## Steps to reproduce:

Fresh installation of nltk (v3.6.5) (python 3.9)

Run the corpora installer using nltk.download(), install the `gutenberg` package

```python
from nltk.corpus import gutenberg

help(gutenberg)
```

This command fails with an error message saying that the punkt pacakge needs to be downloaded. Downloading and installing `punkt` using the interactive downloader works around the issue.

<pre>
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
/var/folders/wk/0l_k_m5j0cj5bbw8pbsb0v8m0000gn/T/ipykernel_4380/396642451.py in <module>
      1 from nltk.corpus import gutenberg
      2 
----> 3 help(gutenberg)

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_sitebuiltins.py in __call__(self, *args, **kwds)
    101     def __call__(self, *args, **kwds):
    102         import pydoc
--> 103         return pydoc.help(*args, **kwds)

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py in __call__(self, request)
   2000     def __call__(self, request=_GoInteractive):
   2001         if request is not self._GoInteractive:
-> 2002             self.help(request)
   2003         else:
   2004             self.intro()

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py in help(self, request)
   2059             else: doc(str, 'Help on %s:', output=self._output)
   2060         elif isinstance(request, Helper): self()
-> 2061         else: doc(request, 'Help on %s:', output=self._output)
   2062         self.output.write('\n')
   2063 

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py in doc(thing, title, forceload, output)
   1778     try:
   1779         if output is None:
-> 1780             pager(render_doc(thing, title, forceload))
   1781         else:
   1782             output.write(render_doc(thing, title, forceload, plaintext))

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py in render_doc(thing, title, forceload, renderer)
   1771             object = type(object)
   1772             desc += ' object'
-> 1773     return title % desc + '\n\n' + renderer.document(object, name)
   1774 
   1775 def doc(thing, title='Python Library Documentation: %s', forceload=0,

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py in document(self, object, name, *args)
    471         try:
    472             if inspect.ismodule(object): return self.docmodule(*args)
--> 473             if inspect.isclass(object): return self.docclass(*args)
    474             if inspect.isroutine(object): return self.docroutine(*args)
    475         except AttributeError:

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py in docclass(self, object, name, mod, *ignored)
   1323             signature = None
   1324         if signature:
-> 1325             argspec = str(signature)
   1326             if argspec and argspec != '()':
   1327                 push(name + argspec + '\n')

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py in __str__(self)
   3068         render_kw_only_separator = True
   3069         for param in self.parameters.values():
-> 3070             formatted = str(param)
   3071 
   3072             kind = param.kind

/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py in __str__(self)
   2593                 formatted = '{} = {}'.format(formatted, repr(self._default))
   2594             else:
-> 2595                 formatted = '{}={}'.format(formatted, repr(self._default))
   2596 
   2597         if kind == _VAR_POSITIONAL:

/usr/local/lib/python3.9/site-packages/nltk/data.py in __repr__(self)
    907 
    908     def __repr__(self):
--> 909         self.__load()
    910         # This looks circular, but its not, since __load() changes our
    911         # __class__ to something new:

/usr/local/lib/python3.9/site-packages/nltk/data.py in __load(self)
    893 
    894     def __load(self):
--> 895         resource = load(self._path)
    896         # This is where the magic happens!  Transform ourselves into
    897         # the object by modifying our own __dict__ and __class__ to

/usr/local/lib/python3.9/site-packages/nltk/data.py in load(resource_url, format, cache, verbose, logic_parser, fstruct_reader, encoding)
    748 
    749     # Load the resource.
--> 750     opened_resource = _open(resource_url)
    751 
    752     if format == "raw":

/usr/local/lib/python3.9/site-packages/nltk/data.py in _open(resource_url)
    874 
    875     if protocol is None or protocol.lower() == "nltk":
--> 876         return find(path_, path + [""]).open()
    877     elif protocol.lower() == "file":
    878         # urllib might not use mode='rb', so handle this one ourselves:

/usr/local/lib/python3.9/site-packages/nltk/data.py in find(resource_name, paths)
    581     sep = "*" * 70
    582     resource_not_found = f"\n{sep}\n{msg}\n{sep}\n"
--> 583     raise LookupError(resource_not_found)
    584 
    585 

LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/Users/jack/nltk_data'
    - '/usr/local/Cellar/jupyterlab/3.2.4/libexec/nltk_data'
    - '/usr/local/Cellar/jupyterlab/3.2.4/libexec/share/nltk_data'
    - '/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
</pre>

**Comment by tomaarsen** [comment]
Hello!

Thank you for the detailed report. Upon downloading `punkt`, the output starts with:
```
Help on LazyCorpusLoader in module nltk.corpus.util object:

gutenberg = class PlaintextCorpusReader(nltk.corpus.reader.api.CorpusReader)
 |  gutenberg(root, fileids, word_tokenizer=WordPunctTokenizer(pattern='\\w+|[^\\w\\s]+', gaps=False, discard_empty=True, flags=re.UNICODE|re.MULTILINE|re.DOTALL), sent_tokenizer=<nltk.tokenize.punkt.PunktSentenceTokenizer object at 0x000001292AAA6F70>, para_block_reader=<function read_blankline_block at 0x000001292AACA790>, encoding='utf8')
 |
 |  Reader for corpora that consist of plaintext documents.  Paragraphs
 |  are assumed to be split using blank lines.  Sentences and words can
 |  be tokenized using the default tokenizers, or by custom tokenizers
 |  specified as parameters to the constructor.
 |
 |  This corpus reader can be customized (e.g., to skip preface
 |  sections of specific document formats) by creating a subclass and
 |  overriding the ``CorpusView`` class variable.
 |
 |  Method resolution order:
 |      PlaintextCorpusReader
 |      nltk.corpus.reader.api.CorpusReader
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, root, fileids, word_tokenizer=WordPunctTokenizer(pattern='\\w+|[^\\w\\s]+', gaps=False, discard_empty=True, flags=re.UNICODE|re.MULTILINE|re.DOTALL), sent_tokenizer=<nltk.tokenize.punkt.PunktSentenceTokenizer object at 0x000001292AAA6F70>, para_block_reader=<function read_blankline_block at 0x000001292AACA790>, encoding='utf8')
 |      Construct a new plaintext corpus reader for a set of documents
 |      located at the given root directory.  Example usage:
 |
 |          >>> root = '/usr/local/share/nltk_data/corpora/webtext/'
 |          >>> reader = PlaintextCorpusReader(root, '.*\.txt') # doctest: +SKIP
 |
 |      :param root: The root directory for this corpus.
 |      :param fileids: A list or regexp specifying the fileids in this corpus.
 |      :param word_tokenizer: Tokenizer for breaking sentences or
 |          paragraphs into words.
 |      :param sent_tokenizer: Tokenizer for breaking paragraphs
 |          into words.
 |      :param para_block_reader: The block reader used to divide the
 |          corpus into paragraph blocks.
```
Here, it already becomes possible to see why `punkt` is required. It's due to this line:
```
 |  __init__(self, root, fileids, word_tokenizer=WordPunctTokenizer(pattern='\\w+|[^\\w\\s]+', gaps=False, discard_empty=True, flags=re.UNICODE|re.MULTILINE|re.DOTALL), sent_tokenizer=<nltk.tokenize.punkt.PunktSentenceTokenizer object at 0x000001292AAA6F70>, para_block_reader=<function read_blankline_block at 0x000001292AACA790>, encoding='utf8')
```
This line prints out the default value for all parameters, and in particular for `sent_tokenizer`. Printing out this value requires the `PunktSentenceTokenizer` instance to be loaded. Doing so will trigger the NLTK Lazy Loader, which will complain that the Punkt Tokenizer is not downloaded. 

Although I recognise that this is somewhat annoying, I don't see a quick and easy fix for this, given the severity of the issue (or lack thereof). The help function will continue to want to print out the default values (unless perhaps it takes some parameter to not print this?), and printing the PunktSentenceTokenizer instance will simply trigger the lazy loader. 

With other words, I'm afraid I'll just have to recommend doing `python -m nltk.downloader punkt` or 
```python
import nltk
nltk.download("punkt")
```
After which you should no longer experience issues.

**Comment by joneill87** [comment]
Thanks for the quick reply. I think you're right; any attempt to fix the issue would probably raise more problems than it solved. As it stands the error message is clear so the impact is minimal. Closing.
