### ISSUE TITLE
Add CI tests for Python 3.10

### ISSUE THREAD

**Issue by tomaarsen** [nltk/nltk#2913]
Hello!

Python 3.10 is no longer a glimmer far into the future, and we should start supporting it. The first step in doing so is adding 3.10 to the CI tests, and mentioning that NLTK works for Python 3.10 in our documentation throughout the project.

- Tom Aarsen

**Comment by purificant** [comment]
May need to look into refactoring gensim codebase, we are currently locked to version <4

**Comment by tomaarsen** [comment]
@purificant Gensim is exclusively used in this file: https://github.com/nltk/nltk/blob/develop/nltk/test/gensim.doctest
So, we can also remove the dependency if we want, as no code in NLTK relies on it. We could then keep the dependency in CI locked to < 4, and in the future we can refactor the doctest to allow for gensim > 4. Another option is to deprecate fully, and remove gensim.doctest too.

**Comment by purificant** [comment]
gensim <4 appears incompatible with py310, at least in my recent attempts to pass the CI here: https://github.com/purificant/nltk/runs/4467436202 it is failing to build / install.

Because of the above, it seems the only two options are to refactor and relax <4 version lock or deprecate the test entirely?

**Comment by tomaarsen** [comment]
I agree that those seem like the only options. Judging by the gensim.doctest, the functionality seems quite useful. Perhaps we can attempt a refactor of gensim.doctest? 
Another option is to remove the gensim dependencies, even from the CI, which should let the tests pass automatically due to https://github.com/nltk/nltk/blob/develop/nltk/test/gensim_fixt.py.
