### ISSUE TITLE
In CI, refresh `nltk_data` cache if the hash of `index.xml` differs from the cached hash

### ISSUE THREAD

**Issue by tomaarsen** [nltk/nltk#2916]
Rather than simply caching `nltk_data` until the cache expires and it's forced to re-download the entire `nltk_data`, we should perform a check on the `index.xml` which refreshes the cache if it differs from some previous cache.

I would advise doing this in the same way that it's done for `requirements.txt`:
https://github.com/nltk/nltk/blob/59aa3fb88c04d6151f2409b31dcfe0f332b0c9ca/.github/workflows/ci.yaml#L103

i.e. with `${{ hashFiles('...') }}` using a downloaded `index.xml` from https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml. Alternatively, with some other hash function.

### References:
* HashFiles documentation: https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles

---

- Tom Aarsen

**Comment by 404-P4rziv4L** [comment]
Hey @tomaarsen, I would like to try working on this problem. Could I be assigned?

**Comment by tomaarsen** [comment]
Sure!

**Comment by 404-P4rziv4L** [comment]
I'm a little confused with this as it's my first issue where I'm handling CI. Could you provide me with some resources where I could read up a little to understand the problem better? @tomaarsen

**Comment by tomaarsen** [comment]
The GitHub CI is a bit of a fickle beast, simply because (seemingly) the only way to test the performance of it, is to push a commit to GitHub and observe it there. You can't easily test it locally. 
That said, the documentation of GitHub Actions as a whole is here: https://docs.github.com/en/actions. Furthermore, https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py seems like a really nice resource. Beyond that, we use https://github.com/actions/cache for caching. There's some examples here: https://github.com/actions/cache/blob/main/examples.md#python---pip. As you can see, the `hashFiles` function is used on a specific file as a part of the cache "key". With other words, if the file changes, then the key changes, and then it can't find a cache, and it won't use a cache. However, the result of the next action will be stored in the cache using the key, allowing future runs to use the cache. This is essentially what we want, except not with a `requirements.txt`, but with the index.xml contents from https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml. (This is a core `nltk_data` file that specifies which packages exist in `nltk_data`, alongside some information like checksums and package size. If `nltk_data` is updated, then this file is also going to be updated).

An option might be to prepend a "regular" GitHub action step that fetches `index.xml` before the `nltk_data` caching step. The `index.xml` contents or hash might be placed in some variable (not sure how - haven't done that before I believe), allowing the caching step to use the index.xml contents to create a cache key.

I hope that helps a bit.

**Comment by tomaarsen** [comment]
I can access the GitHub Action caches via the UI now, so this should no longer be needed.
