### ISSUE TITLE
Potential accidental capture of loop variable in Boxer

### ISSUE THREAD

**Issue by tomaarsen** [nltk/nltk#2918]
Hello!

Within the last list comprehension in this return statement, the `cond` value will always take the value of the last element of `conds`:
https://github.com/nltk/nltk/blob/4a130f1cdf642327378a4387b319cd2df6f79287/nltk/sem/boxer.py#L533-L537

This seems like it would be unexpected or undesired behaviour.

For those unaware of what I'm talking about, a Python implementation detail causes the following:
```python
int_list = [1, 2, 3, 4, 5]
functions = [
    lambda: print(i) 
    for i in int_list
]
for func in functions:
    func()
```
outputs
```
5
5
5
5
5
```
while one might expect
```
1
2
3
4
5
```

I don't have the time to look into this now, and I'm not sure if this affects many people, so that's why I'll just write it as an issue instead. This probably isn't the highest priority issue, by the way.

- Tom Aarsen

**Comment by gokulnathselvaraj27** [comment]
i would like to contribute
