### ISSUE TITLE
nltk-3.5 build fails in docker and python 2.7.18 due to regex-2022.1.18

### ISSUE THREAD

**Issue by sjurgis** [nltk/nltk#2931]
Sorry I'm not super familiar with this ecosystem, but just noticed my docker build on GCP fails with this message:

```
regex_3/_regex.c:755:15: error: ‘Py_UCS1’ undeclared (first use in this function); did you mean ‘Py_UCS4’?
```

Unsure if this exactly correct source of error so full log attached
[scratch_9.txt](https://github.com/nltk/nltk/files/7900938/scratch_9.txt)

Looking at regex releases there was new one yesterday - https://pypi.org/project/regex/#history

My previous build just yesterday was using regex-2021.11.10

Perhaps there was a DOS fix released as part of https://github.com/nltk/nltk/issues/2929 ?

Dockerfile:
```
FROM --platform=linux/amd64 python:2.7.18 as deps

# Fix build errors on MacOS Apple M1 chip
RUN export CFLAGS="-I /opt/homebrew/opt/openssl/include"
RUN export LDFLAGS="-L /opt/homebrew/opt/openssl/lib"
RUN export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
RUN export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1

RUN pip install --upgrade pip
RUN pip install grpcio
RUN pip install nltk
```

**Comment by sjurgis** [comment]
Looking at regex latest commit messages, [this one](https://github.com/mrabarnett/mrab-regex/commit/227163df1b66a616e20a7f04424860540573949c) stands out:
```
 Dropped support for Python 2 and remove all references to Python <3.6, the earliest supported version.
```
Yikes

**Comment by tomaarsen** [comment]
Hello!

It appears that you are using Python 2.7 based on your logs, which include the line:

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
```

As a result, it makes sense that you are now experiencing these issues, as regex was updated yesterday (as you mentioned) to remove Python 2 functionality: https://github.com/mrabarnett/mrab-regex/commit/227163df1b66a616e20a7f04424860540573949c. With other words: I recommend that you lock `regex` to `< 2022.1.18`, as versions of `regex` before that version should still work with Python 2.7. I hope that helps!

Note, I reckon that this can be done with:
```
...

RUN pip install --upgrade pip
RUN pip install grpcio
RUN pip install "regex<2022.1.18"
RUN pip install nltk
```

Hope this helps!

**Comment by sjurgis** [comment]
Thanks that worked. Tho correct syntax is:

```
RUN pip install "regex<2022.1.18"
```

**Comment by tomaarsen** [comment]
Wonderful! I've updated my comment to reflect that, in case some people find this and quickly copy-paste before reading your message. 
Glad to hear that it works now. I'll close this accordingly. Feel free to let us know if there's more issues, as always.
