### ISSUE TITLE
Potential bug in sentence tokenizer since 3.6.6

### ISSUE THREAD

**Issue by radcheb** [nltk/nltk#2934]
We use `nltk` tokenizer `tokenizers/punkt/english.pickle` to split relatively long text into sentences.
After we upgrading to 3.6.6, we noticed at least one change in the tokenizer results which looks rather like a bug
Given this simple text example:
```
1. This is R .
2. This is A .
3. That's all
```

We expect those sentences:
```json
[
  "1.", 
  "This is R .",
  "2.", 
  "This is A .",
  "3.",
  "That's all"
]
```
However since `3.6.6` we got these sentences:
```json
[
  "1.", 
  "This is R .\n2.", 
  "This is A .",
  "3.",
  "That's all"
]
```

This may looks very insignificant but may has some effect on sensible transformer-based nlp models...

Here is the whole code to reproduce it:
```python
import nltk

text = """1. This is R .
2. This is A .
3. That's all"""

tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
tokenizer.tokenize(text)
```

**Comment by 12mohaned** [comment]
I believe this is not a bug, the problem is in the text. 
For the below test cases, it does work perfectly.

```
import nltk

text1 = """1. This is Right .
2. This is A .
3. That's all"""

text2 = """1. This is Good .
2. This is Amazing .
3. That's all"""

tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
tokenizer.tokenize(text1)
tokenizer.tokenize(text2)
```
output:- 
['1.', 'This is Right .', '2.', 'This is A .', '3.', "That's all"]
['1.', 'This is Good .', '2.', 'This is Amazing .', '3.', "That's all"]

Quick analysis:
The reason behind such unexpected output is that the tokenizer recognizes the R in "1. This is R . 2." as a character rather than a word, so for the tokenizer "R ." does not mark sentence boundary, so it appends white space and "2. ".

Another example mentioned in the Punkt sentence Tokenizer class  is 
```
text = '''
    Punkt knows that the periods in Mr. Smith and Johann S. Bach
    do not mark sentence boundaries.  And sometimes sentences
    can start with non-capitalized words.  i is a good variable
    name.
    ... '''
The above text demonstrates that "." does not always mark sentence boundaries.
```
Regards.

**Comment by griverorz** [comment]
This is only to document that I have also come across a similar change. One of our unit tests noticed that the sentence tokenizer produces different results after 3.6.5. In particular:

```
>>> nltk.__version__
'3.6.5'
>>> tokenizer.tokenize("This... That")
['This... That']
>>> tokenizer.tokenize("This. . . That")
['This.', '.', '.', 'That']
```

While in the newer versions:
```
>>> nltk.__version__
'3.6.6'
>>> tokenizer.tokenize("This... That")
['This... That']
>>> tokenizer.tokenize("This. . . That")
['This.', '. . That']
```

**Comment by 12mohaned** [comment]
Tagging @tomaarsen  @stevenbird to check this issue, and whether it is a bug or not.

> I believe this is not a bug, the problem is in the text. For the below test cases, it does work perfectly.
> 
> ```
> import nltk
> 
> text1 = """1. This is Right .
> 2. This is A .
> 3. That's all"""
> 
> text2 = """1. This is Good .
> 2. This is Amazing .
> 3. That's all"""
> 
> tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
> tokenizer.tokenize(text1)
> tokenizer.tokenize(text2)
> ```
> 
> output:- ['1.', 'This is Right .', '2.', 'This is A .', '3.', "That's all"] ['1.', 'This is Good .', '2.', 'This is Amazing .', '3.', "That's all"]
> 
> Quick analysis: The reason behind such unexpected output is that the tokenizer recognizes the R in "1. This is R . 2." as a character rather than a word, so for the tokenizer "R ." does not mark sentence boundary, so it appends white space and "2. ".
> 
> Another example mentioned in the Punkt sentence Tokenizer class is
> 
> ```
> text = '''
>     Punkt knows that the periods in Mr. Smith and Johann S. Bach
>     do not mark sentence boundaries.  And sometimes sentences
>     can start with non-capitalized words.  i is a good variable
>     name.
>     ... '''
> The above text demonstrates that "." does not always mark sentence boundaries.
> ```
> 
> Regards.

**Comment by davidmezzetti** [comment]
Adding another similar example in 3.6.5 vs 3.6.6

```python
>>> import nltk
>>> nltk.__version__
'3.6.5'
>>> from nltk import sent_tokenize
>>> sent_tokenize("this is a test. . new sentence.")
['this is a test.', '.', 'new sentence.']
```

```python
>>> import nltk
>>> nltk.__version__
'3.6.6'
>>> from nltk import sent_tokenize
>>> sent_tokenize("this is a test. . new sentence.")
['this is a test. . new sentence.']
```

It would be greatly appreciated if a ruling could be made on whether this is a bug or the new desired functionality. I understand this isn't perfect grammatical English but it seems like splitting in these cases is more desirable than not. In my case, I'll be left with 3 options (I expect there are others in that same boat). 

1.) Accept that this is the new standard and update unit tests and expected functionality to match this
2.) Put in some sort of regex hack to work around this change before calling sent_tokenize
3.) Pin the dependency to <= 3.6.5

**Comment by tomaarsen** [comment]
I recognize that that is far from optimal. These were definitely not intentional changes.
