### ISSUE TITLE
ConditionalFreqDist.__add__ is quadratic time-ish

### ISSUE THREAD

**Issue by leifwalsh** [nltk/nltk#2938]
https://github.com/nltk/nltk/blob/3f74ac55681667d7ef78b664557487145f51eb02/nltk/probability.py#L2067-L2068

Because `conditions()` is a list:

https://github.com/nltk/nltk/blob/3f74ac55681667d7ef78b664557487145f51eb02/nltk/probability.py#L1901-L1911

The `not in` operator on line 2068 is linear time, so the whole loop is quadratic.

Within `__add__`, converting `conditions()` on each object into a `set()` makes that operation faster, but also means you can subtract the sets as the thing to loop over on line 2067 and skip that `not in` check completely.

**Comment by tomaarsen** [comment]
Well spotted. I'm surprised this wasn't the original implementation, also because on line 2063 we (again) call self.conditions(), while this value isn't cached to be efficient. I'll have a look whether I can optimize this (and the other relevant methods). Thanks for opening this!

**Comment by tomaarsen** [comment]
I've included it in a small PR with a bunch of tiny changes I wrote the other month.
