### ISSUE TITLE
word_tokenize raises IndexError if . is in beginning of text in 3.6.6 but not in 3.6.2

### ISSUE THREAD

**Issue by Filco306** [nltk/nltk#2942]
**Example: **

If I run the code below with `nltk==3.6.6`, I get an `IndexError`

```python3
s = " . Hello my name is John"
word_tokenize(s)
```

However, running it in `nltk==3.6.2` works just fine. 

I have switch to nltk 3.6.2 for now, but perhaps this should be fixed?

**Comment by tomaarsen** [comment]
Hello! This is indeed a bug. It has been resolved already, luckily! NLTK version 3.6.7 has solved this issue.

I would very much recommend upgrading to NLTK 3.6.7:
```
pip install -U nltk
```
(or similar with anaconda)

See #2925 for more information. (Other similar issues: #2921, #2925, #2927)

I hope this helped! Apologies for the inconvenience.

**Comment by Filco306** [comment]
Hello again, 

No problem! Thank you for the answer :)

**Comment by tomaarsen** [comment]
Gladly! Good luck with your projects!
