### ISSUE TITLE
WordNet 31 cannot be loaded

### ISSUE THREAD

**Issue by sunjiao123sun** [nltk/nltk#2951]
To whom it may concern,

I have been trying to follow the tutorial here and use WordNet 31 in my project: https://www.nltk.org/howto/wordnet.html.
My environment is
`Python 3.10.0; 
nltk version: 3.7
`
While `from nltk.corpus import wordnet31 as wn31` can work, but when I try to do `wn31.get_version()`, it shows that `OSError: No such file or directory: '/Users/sunjiao/nltk_data/corpora/wordnet/index.sense'`, which means that it is using wordnet instead of wordnet31 to index. I wonder if you could help me out on this?

Btw, i have post a screenshot below, thanks a lot!

<img width="1309" alt="Screen Shot 2022-02-21 at 9 21 32 PM" src="https://user-images.githubusercontent.com/13916284/155068082-fa399970-99cd-4e50-82c3-8dd32df93355.png">

**Comment by sunjiao123sun** [comment]
Also, when I do `wn31`, it will give me `<WordNetCorpusReader in '.../corpora/wordnet31' (not loaded yet)>`. i wonder if it means that the wordnet31 is not supported yet! 

Any guidance would be much appreciated!! thanks!

**Comment by ekaf** [comment]
This problem is a bug, due to the fact that the recent wordnet update is not yet prepared to handle zipped nltk_data packages. 
It is fixed in #2946, but in the meantime, you could just unzip wordnet31.zip in the nltk_data/corpora folder, and everything should work as intended.

**Comment by sunjiao123sun** [comment]
thanks a lot ekaf! i have figured it out as well!

For other people's info -- I went to the nltk_data/corpora folder, deleted the wordnet package, and unzipped the wordnet31.zip under the same directory! Just as @ekaf said :)) I really appreciate it!

**Comment by ekaf** [comment]
Thanks @sunjiao123sun! But unzipping the package just bypasses the problem, which remains unsolved for those users who want to preserve space by keeping their data packages zipped.
A solution is to use a LazyCorpusLoader class to read the "index.sense" file, as line 1220 does in the wordnet.py update proposed in #2946.
So this issue remains until an adequate fix is merged.
