### ISSUE TITLE
edit_distance_align wrong results

### ISSUE THREAD

**Issue by yzhaoinuw** [nltk/nltk#2954]
I'm using NLTK 3.7. When running the `edit_distance_align` example (copied below) in pull request #2257, I get a different and wrong result
```
edit_distance_align("fubar", "foobar")
[(0, 0), (1, 1), (2, 2), (3, 3), (3, 4), (4, 5), (5, 6)]
```
The move from (3, 4) to (3, 3) is wrong, which corresponds to an insertion, "fubar" -> "fubbar". According to the pull request post below, the expected path is `[(0, 0), (1, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6)]` 

> Created this for feature/issue #2221, a minimum edit-distance based alignment of two strings. The implementation reuses edit_distance functions in nltk.metrics but adds backtrace to be able to recover the original strings with minimum distance mappings.
> 
> E.g., 'f', 'bar' will align in 'fubar' and 'foobar'.
> 
> `print(edit_distance_align('fubar', 'foobar'))`
> 
> > [(0, 0), (1, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6)]
> > NB: 0 is a null/stop index
> 
> The mapping from first string to second printed out:
> 
> ```
> s1 = '_fubar'
> s2 = '_foobar'
> print([(s1[x[0]], s2[x[1]]) for x in edit_distance_align('fubar','foobar')])
> ```
> 
> > [('_', '_'), ('f', 'f'), ('f', 'o'), ('u', 'o'), ('b', 'b'), ('a', 'a'), ('r', 'r')]

**Comment by Miguelvs23** [comment]
Hey, can I work on this issue?

**Comment by tomaarsen** [comment]
Feel free! I'm not certain that the description by @yzhaoinuw is fully correct however. Couldn't the mentioned move correspond to an insertion like: "fubar" -> "fuobar"? I'm not certain.

**Comment by Miguelvs23** [comment]
Yes, I was checking and testing, however the results I get from the code are 
[('_', '_'), ('f', 'f'), ('u', 'o'), ('b', 'o'), ('b', 'b'), ('a', 'a'), ('r', 'r')]
[(0, 0), (1, 1), (2, 2), (3, 3), (3, 4), (4, 5), (5, 6)]

This as it is, indicates a mapping f->f, u->o, b->o, which are the first 3 substitutions that must be made with respect to the levenshtein distance. Then, the fourth event is an insertion, but as the letter b is also on fubar, the algorithm uses this position to make an insertion b->b, that is why the 5th mapping is (3,4). The rest of the letters are mapped to each other. 

Consider the example changing the b in fubar for a t, the results are 
[('_', '_'), ('f', 'f'), ('u', 'o'), ('t', 'o'), ('a', 'b'), ('a', 'a'), ('r', 'r')]
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (4, 5), (5, 6)]
As there is no b in fubar, the insertion is made on the 6th mapping, where you can map the 'a' in futar to both the substitution of a 'b' in foobar, and the insertion of an 'a' after this 'b'. Thus, both mappings are 'a'->'b' and 'a'->'a', with index positions (4,4) and (4,5)

**Comment by Miguelvs23** [comment]
@yzhaoinuw is this what you meant? Or maybe the pull request was not correct, let me know to keep digging

**Comment by yzhaoinuw** [comment]
Hi @Miguelvs23 and @tomaarsen, thank you for looking into my issue. My problem with the move `(3, 3), (3, 4)` in `[(0, 0), (1, 1), (2, 2), (3, 3), (3, 4), (4, 5), (5, 6)]` is that it is an illegal move. If we write out the entire edit distance table (substitution cost equals 1, which is the default of `edit_distance_align()`),
|            | \# | f | o | o | b | a | r |
| ------ | -- | - | - | - | - | - | - |
| **\#** | 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|  **f**  | 1 | 0 | 1 | 2| 3 | 4 | 5 |
| **u** | 2 | 1 | 1 | 2 | 3 | 4 | 5 |
| **b** | 3 | 2 | 2 | 2 | 2 | 3 | 4 | 
| **a** | 4 | 3 | 3 | 3 | 3 | 2 | 3 |
| **r** | 5 | 4 | 4 | 4 | 4 | 3 | 2 | 

You start from cell `(0, 0)` and end in cell `(5, 6)`, whose value indicates that the minimum edit distance is 2. we see that the move `(3, 3), (3, 4)` doesn't make sense because it will incur an additional cost of 1, which will not give you the correct minimum edit distance. Thus, you cannot go to `(3, 4)` through `(3, 3)`, but only through `(2, 3)`. Thank you @Miguelvs23 for looking into this. Please let me know if I did not describe my issue clearly or if I made a mistake.

**Comment by tomaarsen** [comment]
If you write out the table like that (as opposed to transposed), then the bottom right-most cell is usually denoted by `(6, 5)`, I believe, instead of `(5, 6)`. I think this is where the confusion comes in. If I'm not mistaken, then `(3, 3)` and `(3, 4)` are the highlighted cells in the following table:
![image](https://user-images.githubusercontent.com/37621491/177868295-1c1fbf62-4db6-4aa0-9c18-760238fa18eb.png)

This would make sense, as the path seems to traverse through these cells (and then diagonally before and afterwards).

**Comment by Miguelvs23** [comment]
Yes @tomaarsen I thought of that too. Both paths end in a minimum distance edit of 2, or is there any reason for the particular minimum distance you picked? @yzhaoinuw

**Comment by yzhaoinuw** [comment]
@tomaarsen but you can't go from `(3, 3)` to `(3, 4)` (the two highlighted cells in your comment) without incurring an additional cost, right? The value in cell `(3, 3)` is already 2. Moving right to cell `(3, 4)` corresponds to inserting a "b", which would incur an additional cost of 1, making the value in cell `(3, 4)` become 3. `(3, 4)` can only be reached diagonally from the cell to its upper left, `(2, 3)`, whose value is 2. Since moving from cell `(3, 4)` to `(2, 3)` corresponds to substituting "b" with "b", ie., no change is needed. Thus, no additional cost is needed. That's the only path that can make the value in cell `(3, 4)` 2.

**Comment by Miguelvs23** [comment]
@yzhaoinuw Okey I think that i understand now, So on the image below, the numbers in yellow correspond to the actual path, and the cell in red you say that is an illegal move because I when going from 3,3 to 3,4 there should be a +1. I am going to check the algorithm for the edit_distance_align and get back to you 
![Captura de pantalla 2022-07-09 194019](https://user-images.githubusercontent.com/88748847/178127067-4103e17c-ad14-451d-9668-bc9a7a5b242e.png)

**Comment by yzhaoinuw** [comment]
Created a pull request #3017 for this issue. Please let me know if it makes sense.

Briefly, the [`_edit_dist_backtrace()`](https://github.com/nltk/nltk/blob/b0e85694107992e00a2f9fb48e6410c50fe1f1f6/nltk/metrics/distance.py#L126) function inside [`edit_distance_align()`](https://github.com/nltk/nltk/blob/b0e85694107992e00a2f9fb48e6410c50fe1f1f6/nltk/metrics/distance.py#L147) has a mistake. Using the table below as an illustration,

<img width="233" alt="Screenshot 2022-07-11 000407" src="https://user-images.githubusercontent.com/22312388/178189456-08a67e43-c05f-4314-b828-13275882adcd.png">

the problem occurs when we back traced to cell `(3, 4)`, red circled in the table. Now, the algorithm in [`_edit_dist_backtrace()`](https://github.com/nltk/nltk/blob/b0e85694107992e00a2f9fb48e6410c50fe1f1f6/nltk/metrics/distance.py#L126) function considers which cell in `[(3, 3), (2, 4), (2, 3)]` (corresponding to left, upper, and diagonally upper left) to add to the path next. The algorithm chooses by picking the first cell in the left, upper, and diagonally upper left cell that has the minimum cost value in the table (Like @tomaarsen pointed out in an earlier comment, the way I set up the table does not necessarily line up with the `i` and `j` index in the code. But it does not affect pointing out the problem here). Cell `(3, 3)`, `(2, 3)` have the same cost value of *2*, which is the lowest of the three cells. Since, cell `(3, 3)` is listed first in the code, it gets picked. However, this algorithm fails to consider the restrictions on the bracktrace path based on the cost values. Moving left or moving up (corresponding to an insertion or deletion) should always incur an additional cost of *1*. Moving diagonally to upper left (corresponding to a substitution), on the other hand, can incur an additional cost of either 0 or a user defined substitution cost (default to *1* in [`edit_distance_align()`](https://github.com/nltk/nltk/blob/b0e85694107992e00a2f9fb48e6410c50fe1f1f6/nltk/metrics/distance.py#L147)). Since the cell to the left, `(3, 3)`, has the same cost value as the current cell `(3, 4)`, it tells us we cannot move left. Thus the only viable path is through the upper left cell, `(2, 3)`.

After identifying the problem, one easy way to fix this is to reorder the list of cells to consider when choosing the next path by putting the diagonally upper left cell first in the list.

**Comment by tomaarsen** [comment]
I'll close this as #3017 has been merged. Thanks all.
