### ISSUE TITLE
integrating conllu with NLTK?

### ISSUE THREAD

**Issue by Geremia** [nltk/nltk#2957]
Can [`conllu`](https://github.com/EmilStenstrom/conllu/) be integrated with [NLTK](https://www.nltk.org/_modules/nltk/corpus/reader/conll)?
NLTK has a [ConllCorpusReader class](https://www.nltk.org/_modules/nltk/corpus/reader/conll), but [it currently doesn't support CoNLL-U](https://stackoverflow.com/q/66563494/1429450).

<sup>cf. [`conllu` issue "Integrating with NLTK?" #58](https://github.com/EmilStenstrom/conllu/)</sup>

**Comment by stevenbird** [comment]
@geremia: we would welcome a pull request, if you'd like to add this support
