### ISSUE TITLE
Broken Links on the FAQ page

### ISSUE THREAD

**Issue by ghost** [nltk/nltk#2967]
On the FAQ page, all links to nltk.org appear broken (they 404). Prefixing `https://www.` solves the issue, so this might be a domain config error. Otherwise just changing the links on the FAQ should also fix this. This occurs on Firefox (desktop and android) and Chrome.

**Comment by Abedq** [comment]
They are working for me on Firefox and Chrome.

**Comment by ghost** [comment]
Also the ones to nltk itself? E.g. 

> 9. How can I install NLTK from the source code repository?
> Most users should install NLTK from a distribution. Please see the [installation instructions](http://nltk.org/install.html).

But if so, I'm not that invested in fixing this, if someone wants to close this as an odd error on my side, I also don't mind.

**Comment by Abedq** [comment]
You are right. I misunderstood your comment. All the links that are http://nltk.org/* in the FAQs are broken. 
In addition to: 
1- https://code.google.com/archive/p/nltk/
2- https://code.google.com/archive/p/nltk/source
3- http://sourceforge.net/mailarchive/forum.php?thread_id=22772&amp;forum_id=960

**Comment by tomaarsen** [comment]
I've updated the [FAQ](https://github.com/nltk/nltk/wiki/FAQ) slightly to try and fix these issues. Let me know if they are indeed resolved now! I only "purposefully" left broken links in `13. How did NLTK start?`, as I'm afraid we don't have backups of those.

**Comment by ghost** [comment]
Nice, seems to be fixed. Cheers!

**Comment by tomaarsen** [comment]
Wonderful! I'll close this then. Let us know if there's more issues. I appreciate it!
