### ISSUE TITLE
how to use wordnet to get antonyms for a Chinese word?

### ISSUE THREAD

**Issue by BoomSky0416** [nltk/nltk#2972]
I tried to use wordnet to get antonyms for a Chinese word like in English, but I failed. Here is the code. Anyone helps?
>>> for synset in wn.synsets('悲伤',lang='cmn'):
...     print('synset:',synset)
...     for synlemma in synset.lemmas('cmn'):
...             print('synlemma:',synlemma)
...             for antonym in synlemma.antonyms():
...                     print('antonym:',antonym.name())
...
synset: Synset('grief.n.01')
synlemma: Lemma('grief.n.01.悲伤')
synlemma: Lemma('grief.n.01.痛苦')
synset: Synset('sorrow.n.02')
synlemma: Lemma('sorrow.n.02.后悔')
synlemma: Lemma('sorrow.n.02.悲伤')
synlemma: Lemma('sorrow.n.02.懊悔')
synlemma: Lemma('sorrow.n.02.遗憾')
synset: Synset('sadness.n.02')
synlemma: Lemma('sadness.n.02.伤心')
synlemma: Lemma('sadness.n.02.悲伤')

**Comment by arademaker** [comment]
Consider using the new wn library from @goodmami. See https://wn.readthedocs.io/en/latest/guides/nltk-migration.html how to integrate with NLTK

**Comment by ekaf** [comment]
@BoomSky0416, there are two problems with your example. First, WordNet knows no antonyms for these lemmas, even in English. Second, antonymy is only defined between English lemmas, so you need to go through English in order to get Chinese antonyms.

For example:
```
import nltk
from nltk.corpus import wordnet as wn

for synset in wn.synsets('大+的', lang='cmn'):
    print('synset:',synset)
    for synlemma in synset.lemmas():
        print('synlemma:',synlemma)
        print(f"cmn lemmas: {synlemma.synset().lemmas(lang='cmn')}")
        antlist = synlemma.antonyms()
        if antlist:
            for antonym in antlist:
                print(f"cmn antonyms: {antonym.synset().lemmas(lang='cmn')}")
        else:
            print(f"antonyms: {antlist}")
    print()

```


```
synset: Synset('large.a.01')
synlemma: Lemma('large.a.01.large')
cmn lemmas: [Lemma('large.a.01.大+的'), Lemma('large.a.01.巨大+的')]
cmn antonyms: [Lemma('small.a.01.小+的'), Lemma('small.a.01.小型+的')]
synlemma: Lemma('large.a.01.big')
cmn lemmas: [Lemma('large.a.01.大+的'), Lemma('large.a.01.巨大+的')]
cmn antonyms: [Lemma('small.a.01.小+的'), Lemma('small.a.01.小型+的')]

synset: Synset('large.s.02')
synlemma: Lemma('large.s.02.large')
cmn lemmas: [Lemma('large.s.02.大+的')]
antonyms: []

synset: Synset('wide.a.05')
synlemma: Lemma('wide.a.05.wide')
cmn lemmas: [Lemma('wide.a.05.大+的')]
cmn antonyms: [Lemma('narrow.a.04.有限+的')]


```

**Comment by ekaf** [comment]
@arademaker wrote:
> Consider using the new wn library from @goodmami. See https://wn.readthedocs.io/en/latest/guides/nltk-migration.html how to integrate with NLTK

Does the new wn library provide a way to handle antonyms yet? From the cited documentation, and the _core.py_ source, my understanding is that the _get_related()_ function is only defined for synsets, not lemmas.

**Comment by goodmami** [comment]
> Does the new wn library provide a way to handle antonyms yet?

Apologies if the documentation wasn't clear, but it does and has since its first release. See [Sense.get_related()](https://wn.readthedocs.io/en/latest/api/wn.html#wn.Sense.get_related). As @ekaf noted, antonyms are only defined between lemmas, not synsets. Wn's API splits Lemmas into Words and Senses, so the relations are defined between 'senses', as shown in this example:

```pycon
>>> import wn
>>> en = wn.Wordnet('omw-en')                                          # limit results to the omw-en lexicon
>>> en.synsets('wide', pos='a')[0].senses()                            # get senses for a synset
[Sense('omw-en-wide-02560548-a'), Sense('omw-en-broad-02560548-a')]
>>> en.synsets('wide', pos='a')[0].senses()[0].get_related('antonym')  # get antonyms for a sense
[Sense('omw-en-narrow-02561888-a')]
```

Second, since the Chinese wordnet does not have any antonyms defined, you can try to rely on the English antonyms, but you may be surprised by the results. Relations between synsets are probably more reliable than between senses as the senses pertain to particular words and not general concepts. Wn therefore does not provide a method to directly translate sense relations, but you can do it yourself:

```pycon
>>> cmn = wn.Wordnet('omw-cmn')
>>> for cmn_ss in cmn.synsets('大+的'):
...   print('cmn synset:', cmn_ss)
...   for cmn_sense in cmn_ss.senses():
...     print('  cmn sense:', cmn_sense)
...     for en_sense in cmn_sense.translate(lexicon='omw-en'):
...       print('    en sense:', en_sense)
...       for en_ant in en_sense.get_related('antonym'):
...         print('      en antonym:', en_ant)
...         for cmn_ant in en_ant.translate(lexicon='omw-cmn'):
...           print('        cmn translated antonym sense', cmn_ant)
... 
cmn synset: Synset('omw-cmn-02163307-a')
  cmn sense: Sense('omw-cmn-大-plus-的-02163307-a')
    en sense: Sense('omw-en-large-02163307-s')
cmn synset: Synset('omw-cmn-02563068-a')
  cmn sense: Sense('omw-cmn-大-plus-的-02563068-a')
    en sense: Sense('omw-en-wide-02563068-a')
      en antonym: Sense('omw-en-narrow-02563310-a')
        cmn translated antonym sense Sense('omw-cmn-有限-plus-的-02563310-a')
cmn synset: Synset('omw-cmn-01382086-a')
  cmn sense: Sense('omw-cmn-大-plus-的-01382086-a')
    en sense: Sense('omw-en-large-01382086-a')
      en antonym: Sense('omw-en-small-01391351-a')
        cmn translated antonym sense Sense('omw-cmn-小-plus-的-01391351-a')
        cmn translated antonym sense Sense('omw-cmn-小型-plus-的-01391351-a')
    en sense: Sense('omw-en-big-01382086-a')
      en antonym: Sense('omw-en-little-01391351-a')
        cmn translated antonym sense Sense('omw-cmn-小-plus-的-01391351-a')
        cmn translated antonym sense Sense('omw-cmn-小型-plus-的-01391351-a')
  cmn sense: Sense('omw-cmn-巨大-plus-的-01382086-a')
    en sense: Sense('omw-en-large-01382086-a')
      en antonym: Sense('omw-en-small-01391351-a')
        cmn translated antonym sense Sense('omw-cmn-小-plus-的-01391351-a')
        cmn translated antonym sense Sense('omw-cmn-小型-plus-的-01391351-a')
    en sense: Sense('omw-en-big-01382086-a')
      en antonym: Sense('omw-en-little-01391351-a')
        cmn translated antonym sense Sense('omw-cmn-小-plus-的-01391351-a')
        cmn translated antonym sense Sense('omw-cmn-小型-plus-的-01391351-a')
```

**Comment by BoomSky0416** [comment]
Got it. Thanks!
