### ISSUE TITLE
Nonexistent OMW offsets

### ISSUE THREAD

**Issue by ekaf** [nltk/nltk#2973]
In a few cases, the Open Multilingual Wordnet refers to synset offsets, which do not actually exist in WordNet. This issue has been known for some time (https://github.com/omwn/omw-data/issues/24#issuecomment-974789720), and it is not clear whether and when the OMW data will be fixed.

But from the point of view of NLTK, the issue is not harmless,
because it leads to fatal errors:
```
from nltk.corpus import wordnet as wn

print(wn.synsets('osim', lang='hrv'))
```
```
File "nltk/corpus/reader/wordnet.py", line 1539, in synset_from_pos_and_offset
    f"No WordNet synset found for pos={pos} at offset={offset}."
nltk.corpus.reader.wordnet.WordNetError: No WordNet synset found for pos=a at offset=2002046.
```

This behaviour is unfortunate, because the Croatian word 'osim' is linked to two synset offsets, where only one is nonexistent, so it would be preferrable to return at least the good synset, instead of aborting the whole processing pipeline.
It doesn't help much to wrap the call in a try-except construct
because, although a batch would be allowed to continue,
the user would still miss the good 'osim' offset.

**Comment by goodmami** [comment]
I think these are mostly bugs in the OMW data that should be fixed. But I also want to live in a world where the non-English wordnets can grow beyond the Princeton WordNet. So, ideally, both changes would happen: fixing the OMW data, and change the code to support synsets not in PWN.

**Comment by ekaf** [comment]
Thanks @goodmami: it is great to hear that you support fixing the OMW data. 
The NLTK library already allows English concepts that were not in Princeton WordNet. For example, the new wordnet2021 package introduces additional English synsets at the end of the new 'data.noun', like 'ruled surface', 'light fitting' and 'chick sexer', which did not have a synset offset in PWN. 
The problem is that the NLTK code does not yet allow OMW synsets that do not have an English counterpart, whatever the provenance of the English data. This restriction will certainly need to be lifted when OMW starts to include synsets that don't have an English translation.
