### ISSUE TITLE
Tree.__delitem__ retrurns a list instead of a tree

### ISSUE THREAD

**Issue by ArztKlein** [nltk/nltk#2975]
What I'm wanting to do is delete an item from a tree (del tree[index]), but this returns a list of Trees instead of a Tree itself.
I'm not sure why this has been decided to be the behaviour, but shouldn't this return the Tree itself?

I'm willing to send a pull request myself so that it returns a Tree, if this is a reasonable thing to change.

If this is not something we should change, then how am I supposed to delete a leaf without the tree collapsing into a hundred seperate trees?

**Comment by tomaarsen** [comment]
If you delete an item from a tree through `del tree[index]`, then `tree` should be correctly updated, regardless of what `Tree.__delitem__` returns. To be honest, I'm not even sure why `Tree.__delitem__` returns anything at all, it seems a bit unnecessary - my intuition tells me that it should just return `None`.

See this for an example:
```python
from nltk.tree import Tree

t = Tree.fromstring("(S (NP (D the) (N dog)) (VP (V chased) (NP (D the) (N cat))))")

print("Initial tree:")
t.pretty_print(unicodelines=True)

print("Deleting the second branch under the root...\n")
del t[1]

print("The resulting tree:")
t.pretty_print(unicodelines=True)
```
Which outputs:
```
Initial tree:
              S
     ┌────────┴─────┐
     │              VP
     │        ┌─────┴───┐
     NP       │         NP
 ┌───┴───┐    │     ┌───┴───┐
 D       N    V     D       N
 │       │    │     │       │
the     dog chased the     cat

Deleting the second branch under the root...

The resulting tree:
     S
     │
     NP
 ┌───┴───┐
 D       N
 │       │
the     dog

```
I hope that clears it up a bit. Let me know if you still think there's an issue, or if something needs changing, as I may have misunderstood this issue a bit.
