### ISSUE TITLE
Which Pointers from WordNet are Used for Synset in NLTK?

### ISSUE THREAD

**Issue by aflah02** [nltk/nltk#2976]
I'm trying to create a custom parser for wordnet and hit a roadblock. I see that there are tons of different pointer_symbols and lots of them seem almost like synonyms but not exactly synonyms. I'm trying to extract the synonyms for each word and I'm not sure which pointers should be considered. 

Any hints or leads through which I can find out what's being used?

**Comment by ekaf** [comment]
Synonyms are not linked by a pointer, but by belonging to the same _synset_ ("synonym set"). You may want to read the fine WordNet documentation at https://wordnet.princeton.edu/documentation .

**Comment by aflah02** [comment]
@ekaf Thanks for the reply
I understand that part however from what I could find relationships are described using pointers which tells whether it's an Antonym or Hypernym etc. ->
_A relation from a source to a target synset is formed by specifying a word from the target synset in the source synset, followed by the pointer_symbol indicating the pointer type._
Source - https://wordnet.princeton.edu/documentation/wninput5wn
So do you mean to say to find synonyms I just need to use relations which fall under these 3 pointers?

- ;c    Domain of synset - TOPIC 
- ;r    Domain of synset - REGION 
- ;u    Domain of synset - USAGE 

This is the part that's troubling me as then there are other pointers which also seem to be like synonyms like-

- -c    Member of this domain - TOPIC 
- -r    Member of this domain - REGION 
- -u    Member of this domain - USAGE

**Comment by ekaf** [comment]
@aflah02, the domain relation has nothing to do with synonymy. Synonyms are found by finding the synset offsets for each synsets that a word belongs to, and then retrieving the other words that belong to each of these synsets.
If you really want to write a WordNet parser, you should expect to spend _a lot of_ time getting familiar with the official documentation, and maybe start with the 'wndb' manual page. Nobody can do it for you.

**Comment by aflah02** [comment]
Thanks @ekaf this clears up a lot of things
