### ISSUE TITLE
maltparser location

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#298]
The maltparser wrapper (parse/malt.py) uses the old style naming convention for malt.jar. Current versions of the parser incorporate the version number.

**Comment by alexrudnick** [comment]
I'll take this one! (unless somebody beats me to it, of course)

**Comment by stevenbird** [comment]
Thanks. Note that find_binary() doesn't support globbing, and we'd presumably want the most recent version of the malt parser.

**Comment by stevenbird** [comment]
I suspect this is no longer current, cf https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py#L58
