### ISSUE TITLE
Avoid fatal wordnet errors

### ISSUE THREAD

**Issue by ekaf** [nltk/nltk#2982]
In the wordnet.py module, there are 12 occasions where a WordNetError can be raised. The WordNetError class is defined as a Python Exception, i. e. a fatal error that aborts any further processing.

This behaviour is unfortunate in the frequent use case where the user wants to process a batch of queries, because if one error occurs, the whole batch is aborted. To avoid that, users can wrap the problematic call in a try-except construct, but this is not always adequate, because it may still lead to losing some correct solutions, as illustrated in #2973.

So it is possible that some, or maybe all of the 12 calls of WordNetError could be replaced by a call of warnings.warn(), as in #2974. Or maybe a more general solution could be to redefine the WordNetError class to just raise non-fatal warnings?

**Comment by tomaarsen** [comment]
I believe it will be unintuitive if we reimplement an error class to effectively not be an error class, but a warning class instead. With other words, that method is only viable if we rename WordNetError to WordNetWarning. That said, this would be a breaking change, as there are certainly people who import WordNetError.

I think the more intuitive solution is to simply call `warning.warn()`.

**Comment by ekaf** [comment]
Ok, thanks @tomaarsen. Initially, this issue is just hypothetical, as long as we don't know if any of the 12 calls of WordNetError need to be fixed. To answer that question, 
problematic errors are those that are raised, directly or indirectly, by a function that can return lists or sets of results, where one result could raise the error while any remaining correct result would be lost when wrapping the function in a try-except construct.

The 12 calls of WordNetError are distributed across 8 functions, and a quick glance at the table below indicates that we probably want to fix at least "synset" and "_load_lang_data":

|**WordNetError** | **Called by**|
|-------------|----------|
|information_content | _lcs_ic|
|lch_similarity | lch_similarity|
|_lcs_ic | jcn_similarity, lin_similarity, res_similarity|
|lemma | add_lemma|
|lemma_from_key | synset_from_sense_key|
|_load_lang_data | all_lemma_names, all_omw_synsets, _doc, lemma_names, lemmas, synsets|
| _load_lemma_pos_offset_map | \_\_init__ |
|synset | add_exomw, add_lemma, closure, digraph, lemma, lowest_common_hypernyms, _related, synset_from_sense_key, synsets, tree|

**Comment by ekaf** [comment]
After going through the 8 functions that ran raise a WordNetError, it appears that most only return one result, and don't really need to be fixed.
Although  "_load_lang_data" is called by "synsets", which can return multiple synsets, these would all be for the same value of "lang", so it seems ok to raise a fatal error if that language does not exist.
This leaves us with only 2 functions where it would be preferrable to replace WordNetError with warnings.warn():
"synset" because it is called by "synsets" (among others), and "lemma" because it is transitively used by "digraph".

**Comment by ekaf** [comment]
The present issue is purely speculative, and seems groundless with the current Wordnet and OMW packages, because no problem occurs with any word included in these packages, apart from #2973, and #2984, which are respectively solved in #2974 and #2985. 
So it seems appropriate to close this issue without further action, and eventually reopen it if any future data should cause actual problems.
