### ISSUE TITLE
All corpora should be returned as unicode

### ISSUE THREAD

**Issue by turicas** [nltk/nltk#299]
As a good practice, we should convert any encoded string (UTF-8, ISO-8859-1 etc.) to Unicode in software input, work on data using Unicode and then, just before outputting data, convert it to some encoding.

I had some problems dealing with encoding in some corpora and discovered it because I speak Portuguese and the corpus `machado` is returned as `unicode`, while others are returned as `str` (I didn't test decoding that corpora, but I suspect they are not in the same encoding -- see #47 for more details).

I've created a script that iterate over all corpora available and print the type of `corpus.raw()` string and type of all words returned by `corpus.words(...)` (for all `corpus.fileids()`). This script is available in [this gist](https://gist.github.com/3801534).

The results (total of 54 corpora analysed):
- 7 corpora returned as `unicode`
- 32 corpora returned as `str`
- 16 corpora can't be tested

The sum is 55 because corpus `rte` return words in both `unicode` and `str`.

Note these 16 corpora that can't be tested: they have some interface problem, in other words, they don't have the methods other corpora have (like `words`) or these methods don't behave like in the majority of corpora (the number of required parameters is different, for example). I reported this problem in issue #296.

I think the solution is to store the original corpus encoding in corpus object and convert it to `unicode` (decode using the stored encoding) just after loading it.

The extensive list of types is:
- `str`: `['abc', 'alpino', 'brown', 'cess_cat', 'cess_esp', 'comtrans', 'conll2000', 'dependency_treebank', 'floresta', 'gazetteers', 'gutenberg', 'inaugural', 'indian', 'movie_reviews', 'names', 'nps_chat', 'pl196x', 'reuters', 'rte', 'semcor', 'shakespeare', 'sinica_treebank', 'state_union', 'stopwords', 'swadesh', 'timit_tagged', 'treebank', 'treebank_chunk', 'treebank_raw', 'verbnet', 'webtext', 'words']`
- `unicode`: `['conll2002', 'genesis', 'jeita', 'knbc', 'mac_morpho', 'machado', 'rte']`
- Interface problem: `['cmudict', 'conll2007', 'ieer', 'ipipan', 'nombank', 'ppattach', 'propbank', 'qc', 'senseval', 'switchboard', 'timit', 'toolbox', 'udhr', 'wordnet', 'wordnet_ic', 'ycoe']`

**Comment by kmike** [comment]
It returns unicode in my Python 3 branch https://github.com/kmike/nltk (under both python 2.x and python 3.x), but does this incorrectly for some corpora. The porting struggled because in order to correctly return unicode the encoding of each corpus must be set explicitly and I didn't have a time to figure out the encoding of each corpus; contributions in this aspect are very welcome; this will speedup the Python 3 port a lot.

**Comment by turicas** [comment]
@kmike do you know [chardet](http://pypi.python.org/pypi/chardet)? Maybe we can automate the process of detecting the encoding just reading all available corpora, using it to discover the encoding and then saving the encoding somehow.

**Comment by turicas** [comment]
I've tried to used chardet (see the code [in this gist](https://gist.github.com/3806469)), but can't detect all encodings correctly (32 corpora are stored as `str`, I can decode 23 correctly from the encoding chardet returned and can't decode 9 of them). The results are:
- brown: ascii
- cess_cat: ISO-8859-2
- cess_esp: ISO-8859-2
- conll2000: ascii
- dependency_treebank: ascii
- floresta: IBM855
- gazetteers: ISO-8859-2
- indian: IBM866
- movie_reviews: ascii
- names: ascii
- nps_chat: ascii
- pl196x: utf-8
- semcor: ascii
- shakespeare: ascii
- sinica_treebank: utf-8
- state_union: ISO-8859-2
- stopwords: utf-8
- swadesh: utf-8
- timit_tagged: ascii
- treebank: ascii
- treebank_chunk: ascii
- verbnet: ascii
- words: ascii

**Comment by kmike** [comment]
@turicas thanks! Using chardet was a nice idea. I've added the encoding information for some corpora in a 2and3 branch. The encoding for indian seems to be simply utf8 - ibm866 is a DOS Russian encoding. I also think floresta text looks better with ISO-8859-15 (Google Translate is able to handle it). Some corpora were XML; they are obtaining the encoding from the XML header. I wrote some tests but didn't check all encodings manually.

**Comment by turicas** [comment]
@kmike, thank you! :-)
Is there any way I can help implementing it in all corpora? I'm new to NLTK development...
Do you have plans in merging it on nltk/nltk?

**Comment by turicas** [comment]
I mean from 2and3 to master...what are the plans on merging?

**Comment by kmike** [comment]
There are unresolved issues that prevent merging 2and3 to master. For example, corpora now returns unicode - but nltk.Text class and many other nltk classes don't support unicode. I'm going to write a post to nltk-dev google group about this branch, unicode support, Python 3.x support and how to help (but didn't had a time to do this yet) - these are big changes and they must be discussed before implementing and merging to master.

**Comment by turicas** [comment]
@kmike, I would like to work on this branch (fixing Unicode problems).

**Comment by kmike** [comment]
This would be great! I tried to narrow down the NLTK unicode issues in a nltk-dev post: https://groups.google.com/forum/?fromgroups=#!topic/nltk-dev/KPBCu-IAjq8 ; feedback is welcome.

**Comment by kmike** [comment]
There are still issues (I broke some corpora readers); see https://gist.github.com/4447068 . I'll take care of encodings.
