### ISSUE TITLE
nltk.draw.pos-concordance(), mentioned on website, does not exist

### ISSUE THREAD

**Issue by alanfgh** [nltk/nltk#3]
From website ( http://nltk.googlecode.com/svn/trunk/doc/howto/corpus.html#tagged-corpora ):

:::
Use nltk.draw.pos-concordance() to access a GUI for searching tagged corpora.

**Comment by stevenbird** [comment]
This should read: nltk.app.pos_concordance().
Fixed in the source tree.

**Comment by alanfgh** [comment]
Not quite sure I understood precisely, since I don't know whether "source tree" includes (web) documentation. Which of the following scenarios holds?

(1) The website gave the wrong command and needs to be changed (if so, it still hasn't been).
(2) The NLTK source code needed to be changed, and has been.
(3) Both of the above.

I still get an error (with version 2.0b9; haven't downloaded anything new) when I type "nltk.app.pos_concordance()" rather than "nltk.draw.pos_concordance()":

In [4]: import nltk.app

## In [5]: nltk.app.pos_concordance()

AttributeError                            Traceback (most recent call last)
C:\Windows\system32<ipython-input-5-19538d4bb016> in <module>()
----> 1 nltk.app.pos_concordance()

AttributeError: 'module' object has no attribute 'pos_concordance'
