### ISSUE TITLE
wordnet_app crashes with TypeError: 'method' object is not iterable

### ISSUE THREAD

**Issue by StephanHasler** [nltk/nltk#3002]
I'm using nltk 3.7 / python 3.8.

Steps to reproduce:
1. I start the wordnet_app
2. I enter a search string in the browser window, e.g. 'help'  
3. I click the 'S;' of the a found entry, .e.g. the first one.

I get:
File "wordnet_app.py", line 352, in lemma_property
    return flattern([func(l) for l in synset.lemmas if l.name == word])
TypeError: 'method' object is not iterable

It is this line:
https://github.com/nltk/nltk/blob/de46911d9ca248c2c6ce95518cd25e3c277208d7/nltk/app/wordnet_app.py#L352
I guess some parentheses are missing, it should be synset.lemmas()

**Comment by ekaf** [comment]
@StephanHasler 
> I guess some parentheses are missing, it should be synset.lemmas()

Yes, this fix is really obvious.
