### ISSUE TITLE
wordnet_app crashes with _pickle.UnpicklingError: invalid load key, 'n'.

### ISSUE THREAD

**Issue by StephanHasler** [nltk/nltk#3003]
I'm using nltk 3.7 / python 3.8.

Steps to reproduce:
1. I start the wordnet_app
2.  I enter a search string in the browser window, e.g. 'help'
3.  I click the 'S;' of the a found entry, .e.g. the first one.
4. I click 'Hyponyms'

Note: This assumes that issue #3002 is solved. Otherwise it will crash earlier.

I get:
File "wordnet_app.py", line 692, in decode
    word, synset_relations = pickle.loads(string)
_pickle.UnpicklingError: invalid load key, 'n'.

This decode function seems to get an input 'string' which is always of type str:
Sometimes the string looks like:
gAWVGgAAAAAAAACMBGhlbHCUfZSMCGFpZC5uLjAylI-Uc4aULg== 
Then is works.
But sometimes the string looks like:
b'gAWVHgAAAAAAAACMBGhlbHCUfZSMCGFpZC5uLjAylI-UKEsAkHOGlC4='
Then it crashes, because the b' ' notation does not make sense for something of type str.
I checked that the type is really str in this case and not bytes.
When I check for the b' ' wrapping and remove it, it works.
But this is more a workaround, maybe there is a more elegant fix.

**Comment by ekaf** [comment]
It is not obvious what to do here: the best would probably be to prevent passing the b' type, rather than removing it afterwards.

**Comment by StephanHasler** [comment]
Along your thinking, I just removed the encode() here:
https://github.com/nltk/nltk/blob/4616bcdf3b045e4c76b724e210f11fd0b8b9a501/nltk/app/wordnet_app.py#L633
This seems to do the trick.
I tried different searches and then randomly clicked on any link over and over again, everything works as expected now.
The question is why this encode was necessary once? Maybe because of the old python 2 behavior. 
Or is it still necessary for some rare case I did not test?

Actually, the line given above is the argument to the function make_lookup_link, which calls encode() for its argument again. So encode() was called twice directly after each other, which does not make sense to me.
make_lookup_link is called several times in the code, always with a not-encoded ref argument, except the one where I fixed it now.

**Comment by ekaf** [comment]
@StephanHasler, your explanation is very convincing.
The input to _make_lookup_link_ can only be a Reference object (with 2 fields), while the output of Reference.encode() is a string, so passing the latter to the former is bound to raise an error, even with older versions of Python.
Then, it is clear that the Reference passed in line 633 must not be encoded, and that your solution is adequate.
Would you consider submitting a Pull Request with your fixes?
