### ISSUE TITLE
NLTK punkt sentence tokenizer for multiple languages

### ISSUE THREAD

**Issue by santha96** [nltk/nltk#3005]
Hi,
My corpus contains text from multiple languages such as Arabic, Persian, Urdu, Armenian, etc... is it possible to train a single tokenizer pickle file for all the above languages. if so, can someone pls suggest the steps to train the single custom sentence tokenizer which works well for all these languages?

**Comment by arademaker** [comment]
can't you simply write your own code that deals with that scenario? It would first call a language detector in the text fragment, and later, based on the result of the language detector, it calls the sentence tokenizer with the appropriate Punkt model.

**Comment by santha96** [comment]
I appreciate your help. Instead of having many Punkt models, is it possible to have one model which works well for the group of languages?

**Comment by arademaker** [comment]
I don’t think so. Punkt is actually best used for a given corpus not for a “language”. Punkt is almost based on the idea of recognize abbreviations, very domain/corpus specific.

**Comment by santha96** [comment]
okay.Thanks a lot @arademaker
