### ISSUE TITLE
TreebankWordDetokenizer consistently positions opening quotation marks incorrectly

### ISSUE THREAD

**Issue by sinking-point** [nltk/nltk#3006]
I am aware that `TreebankWordDetokenizer` can never be 100% accurate, but it should be able to get this right.

```
He was also named 1982 '' Sportsman of the Year '' by Sports Illustrated .
```
```
He was also named 1982" Sportsman of the Year" by Sports Illustrated.
```

```
Alessandro -LRB- '' Sandro '' -RRB- Mazzola -LRB- born 8 November 1942 -RRB- is an Italian former football player .
```
```
Alessandro (" Sandro") Mazzola (born 8 November 1942) is an Italian former football player.
```

And so on. I've encountered no example where it gets this right.

It should be simple enough to fix this by assuming the nth quotation mark in the text is a left quote if n mod 2 == 0 or a right quote if n mod 2 == 1. I'm making the assumptions that nested quotes are uncommon, as are quotes that started before the beginning of the text chunk being detokenised.

**Comment by tomaarsen** [comment]
I understand your frustration here, and your confusion, but I must say that this functionality has a clear reason. You see, the Detokenizer tries to revert the functionality of the Tokenizer, which performs like so on your samples:
```python
>>> from nltk.tokenize import TreebankWordTokenizer, TreebankWordDetokenizer
>>> tokenizer = TreebankWordTokenizer()
>>> detokenizer = TreebankWordDetokenizer()
>>> tokenized = tokenizer.tokenize('He was also named 1982 "Sportsman of the Year" by Sports Illustrated.')
>>> tokenized
['He', 'was', 'also', 'named', '1982', '``', 'Sportsman', 'of', 'the', 'Year', "''", 'by', 'Sports', 'Illustrated', '.']
>>> detokenized = detokenizer.detokenize(tokenized)
'He was also named 1982 "Sportsman of the Year" by Sports Illustrated.'
```
and
```python
>>> from nltk.tokenize import TreebankWordTokenizer, TreebankWordDetokenizer
>>> tokenizer = TreebankWordTokenizer()
>>> detokenizer = TreebankWordDetokenizer()
>>> tokenized = tokenizer.tokenize('Alessandro ("Sandro") Mazzola (born 8 November 1942) is an Italian former football player.')
>>> tokenized
['Alessandro', '(', '``', 'Sandro', "''", ')', 'Mazzola', '(', 'born', '8', 'November', '1942', ')', 'is', 'an', 'Italian', 'former', 'football', 'player', '.']
>>> detokenized = detokenizer.detokenize(tokenized)
'Alessandro ("Sandro") Mazzola (born 8 November 1942) is an Italian former football player.'
```

As you can see, opening quotes are referred to as ``, while closing quotes are ''. This functionality matches e.g. LaTeX:
![image](https://user-images.githubusercontent.com/37621491/171612946-9d00ae45-c144-41b6-884e-9d4e8d65e168.png)

I hope that explains this functionality. If your tokenized text has only `''`, then you might be able to use a simple regex replace to pre-process your text to use `` instead:
```python
import re

raw = "He was also named 1982 '' Sportsman of the Year '' by '' Sports Illustrated '' ."

# Capture '', followed by a lazy match of anything, followed by another ''
pattern = re.compile(r"''(.*?'')")
# Replace the '' by ``, and then append group 1 again
preprocessed = pattern.sub(r'``\1', raw)

print(preprocessed)
# => He was also named 1982 `` Sportsman of the Year '' by `` Sports Illustrated '' .
```

I don't see us changing this functionality soon. I hope you understand the reasoning a bit better now, though!

**Comment by sinking-point** [comment]
I see. I assumed the dataset I'm using (Wikilarge) used standard Treebank tokenisation, but clearly it doesn't. I've managed to clean the data reasonably well though, so never mind. Thanks.
