### ISSUE TITLE
NLTK download() error

### ISSUE THREAD

**Issue by 1092928282** [nltk/nltk#3007]
Hi, I'm trying to load a self-made grammar file and there is a consistent resource error showing up:

---------------------------------------------------------------
Resource [93mC:[0m not found.
 Please use the NLTK Downloader to obtain the resource:

 [31m>>> import nltk
 >>> nltk.download('C:')
 [0m
 For more information see: https://www.nltk.org/data.html

 Attempted to load [93m/C:/nltk.data/grammar.cfg[0m

 Searched in:
    - ''
---------------------------------------------------------------

After this message showed up, I typed 'nltk.download('C:') and yet it presents another error message:
---------------------------------------------------------------
[nltk_data] Error loading C:: Package 'C:' not found in index
False
---------------------------------------------------------------

I already downloaded everything from NLTK, I have no idea why there is a missing resource and how I can download 'C:'.
How can I solve this problem?

**Comment by purificant** [comment]
It looks like you might be using Windows. May I suggest trying to replicate the issue with a Ubuntu app ( something along the lines of https://apps.microsoft.com/store/detail/ubuntu-2204-lts/9PN20MSR04DW ). Or running any other Linux in WSL 2 on Windows.

**Comment by 1092928282** [comment]
Hi, I actually solved the problem. (It was something regarding the file extension.) Thank you for your help!

**Comment by tarikki** [comment]
Hi!

I ran into the exact same issue today: I'm running a linux container on Google Cloud Run, but for some reason when `nltk` goes looking for those directories, it adds those extra characters you also saw. 

How did you solve your issue?
