### ISSUE TITLE
Include Stopwords in Basque and Catalan

### ISSUE THREAD

**Issue by Mikelhoya** [nltk/nltk#3011]
Hi everyone,
I propose you to add these languages to the stopwords list, i leave the source where they can be taken.

https://github.com/Mikelhoya/StopwordsEU/blob/main/StopwordsEU
https://github.com/stopwords-iso/stopwords-ca/blob/master/stopwords-ca.txt

Best regards

**Comment by stevenbird** [comment]
Thanks @Mikelhoya. Resoved in https://github.com/nltk/nltk_data/commit/4d5ecb6077471be3ac9747efcd59b85d6a8d835c
