### ISSUE TITLE
license of punkt in nlt_data

### ISSUE THREAD

**Issue by happyMindHaha** [nltk/nltk#3015]
Hi
Is it possible to use punkt for commercial in nltk_data?
I cannot find out License information.

**Comment by arademaker** [comment]
Indeed, I didn't find any license information in the punkt models provided in https://github.com/nltk/nltk_data/blob/gh-pages/packages/tokenizers/punkt.zip. I guess it will depend on the specific languages you want to use.

**Comment by arademaker** [comment]
At least you have the corpus used to train the models.

**Comment by tomaarsen** [comment]
I must say that I'm not sure about the licensing information for it. Perhaps @stevenbird knows.

**Comment by stevenbird** [comment]
Please see https://github.com/nltk/nltk_data/issues/188
