### ISSUE TITLE
NameError: name 'pycrfsuite' is not defined

### ISSUE THREAD

**Issue by asdoost** [nltk/nltk#3019]
I was trying to train a CRF POS tagger in Google Colab, using the following code:

```python
from nltk.tag import CRFTagger
import pycrfsuite

ct = CRFTagger()
ct.train(X, 'model.crf.tagger')
a = ct.accuracy(y)
```
but I got the following error:
`NameError: name 'pycrfsuite' is not defined`
 despite the fact that I had installed `python-crfsuite`. I even tried `sklearn-pycrfsuite`, but it didn't work either.

I looked in the `crf.py` file and changed the following lines

```python
try:
        import pycrfsuite
except ImportError:
        pass
...

if feature_func is None:
        self._feature_func = self._get_features
else:
        self._feature_func = feature_func
```

to 

```python
import pycrfsuite
...
self._feature_func = self._get_features
```
And it solved the problem. Although I didn't understand what was the problem. I didn't pass any parameter to `CRFTagger()`, as shown in the code.

**Comment by stevenbird** [comment]
Not an NLTK issue
