### ISSUE TITLE
nltk 3.7 requires explicit download of omw-1.4 on Linux

### ISSUE THREAD

**Issue by lanzkron** [nltk/nltk#3024]
Consider the following script:

```
import nltk

nltk.download("wordnet")
nltk.corpus.wordnet.synsets("test")
```

This runs successfully on both Windows and Linux for nltk version 3.5, however for version 3.7 it only succeeds for Windows and produces the following error on Linux:

> [nltk_data] Downloading package wordnet to
> [nltk_data]     [redacted]/nltk_data...
> [nltk_data]   Package wordnet is already up-to-date!
> Traceback (most recent call last):
>   File "[redacted]/.venv/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
>     root = nltk.data.find(f"{self.subdir}/{zip_name}")
>   File "[redacted]/.venv/lib/python3.9/site-packages/nltk/data.py", line 583, in find
>     raise LookupError(resource_not_found)
> LookupError:
> \**********************************************************************
>   Resource omw-1.4 not found.
>   Please use the NLTK Downloader to obtain the resource:
> 
>   \>\>\> import nltk
>   \>\>\> nltk.download('omw-1.4')
>

**Comment by tomaarsen** [comment]
@ekaf Could you have a look at this when you have some time? I know you're familiar with `omw-1.4` and NLTK's wordnet downloading.

**Comment by ekaf** [comment]
Yes, this problem is real. It is caused by the introduction of a "provenances" dictionary (line 1176) to handle the new omw-1.4 directory structure. Building this dictionary requires the presence of the omw-1.4 package, which was not needed in the past. The ideal would be to return to the old situation, where it was possible to load wordnet without omw. I will try to look at how to do this.

**Comment by lanzkron** [comment]
Just another titbit, on my Windows machine the script failed in WSL2 but succeeded in the regular Windows but a colleague of mine says it fails for Windows too.

**Comment by ekaf** [comment]
I think it would fail on any computer that hasn't downloaded the omw package yet.

**Comment by neumann21** [comment]
I face same warning today. And the solution is simply add several sents:
import nltk
nltk.download('omw-1.4')

**Comment by Tejanonymous** [comment]
could we download it through command prompt (eg anaconda prompt)

**Comment by tomaarsen** [comment]
Yes, you can use `python -m nltk.downloader omw-1.4` to download omw-1.4. See all the data that you can download [here](https://www.nltk.org/nltk_data/).

**Comment by Adesoji1** [comment]
This is great
