### ISSUE TITLE
Arabic wordnet help

### ISSUE THREAD

**Issue by IsaacMQ** [nltk/nltk#3053]
I have started to use arabic wordnet in python.what should i do if i want to  see the arabic synsets of an arabic word? when i look for the synsets of an arabic word it shows the synsets as if i have wrote it in english(image below).i want to see the definitions of each one of the arabic synsets as well.

![as](https://user-images.githubusercontent.com/114464335/192442932-39508337-5285-4ff4-8588-e5a258cb25d7.png)

**Comment by tomaarsen** [comment]
Hello!

I believe that Synsets always show the English name, even if foreign names are available and accessible.
```python
>>> from nltk.corpus import wordnet
>>> wordnet.synsets("طرق", lang="arb")
[Synset('record.v.01'), Synset('beat.v.05'), Synset('forge.v.01'), Synset('beat.v.04'), Synset('tap.v.07')]
>>> wordnet.synset("record.v.01").lemma_names("arb")
['استعرض', 'أشار', 'إلتحق_ب', 'انضم', 'باشر', 'حطم_الرقم_القياسي', 'دخل', 'دون', 'دوّن', 'سجل', 'سجّل', 'سجل_رقم_قياسي', 'شارك', 'شلرك_في_المفاوضات', 'طرق', 'قدم_بيانا', 'قيد', 'قيّد', 'كتب', 'وَضَعَ']
>>> wordnet.lemmas("طرق", lang="arb")
[Lemma('record.v.01.طرق'), Lemma('beat.v.05.طرق'), Lemma('forge.v.01.طرق'), Lemma('beat.v.04.طرق'), Lemma('tap.v.07.طرق')]
```

Perhaps the documentation on [Synsets](https://www.nltk.org/api/nltk.corpus.reader.wordnet.html?highlight=synset#nltk.corpus.reader.wordnet.Synset) or [Lemma](https://www.nltk.org/api/nltk.corpus.reader.wordnet.html?highlight=lemma#nltk.corpus.reader.wordnet.Lemma) will be useful. `wordnet` as imported from `nltk.corpus` is an instance of WordNetCorpusReader, so maybe the documentation on [that](https://www.nltk.org/api/nltk.corpus.reader.wordnet.html?highlight=wordnetcorpusreader#nltk.corpus.reader.wordnet.WordNetCorpusReader) is useful too.

**Comment by IsaacMQ** [comment]
I'm new in nltk.I have started to use wordnet in python because I want to see the differences of nuances of arabic synonyms words.That can be done in wordnet?

**Comment by IsaacMQ** [comment]
what about if I want to see the definitions of وضع كتب قيد...etc?

**Comment by tomaarsen** [comment]
The syntax would be:
```python
>>> from nltk.corpus import wordnet
>>> wordnet.synset("record.v.01").definition(lang="arb")
```
However, this relies on Open Multilingual Wordnet, which I believe does not have Arabic definitions, so it just returns nothing I'm afraid.
(Note also that this syntax with `lang="arb"` requires the most recent version of NLTK)

This question may also be better suited for StackOverflow, you might find more useful answers there. I'll close this as a result.

**Comment by IsaacMQ** [comment]
why you said "I believe"? are you not sure?
________________________________
De: Tom Aarsen ***@***.***>
Enviado: jueves, 29 de septiembre de 2022 2:29 a. m.
Para: nltk/nltk ***@***.***>
Cc: IsaacMQ ***@***.***>; Author ***@***.***>
Asunto: Re: [nltk/nltk] Arabic wordnet help (Issue #3053)


The syntax would be:

>>> from nltk.corpus import wordnet
>>> wordnet.synset("record.v.01").definition(lang="arb")

However, this relies on Open Multilingual Wordnet, which I believe does not have Arabic definitions, so it just returns nothing I'm afraid.
(Note also that this syntax with lang="arb" requires the most recent version of NLTK)

This question may also be better suited for StackOverflow, you might find more useful answers there. I'll close this as a result.

**Comment by tomaarsen** [comment]
@IsaacMQ That is correct.

**Comment by IsaacMQ** [comment]
There's someone else that can confirm me that in arabic wordnet don't have arabic definitions of arabic words? If not,then i can't use wordnet to find the differences of nuances of arabic synonyms words.

**Comment by IsaacMQ** [comment]
Can you change the status of this issue to "open" so someone can answer me?

**Comment by tomaarsen** [comment]
I would recommend asking these types of questions on StackOverflow.

**Comment by IsaacMQ** [comment]
I did.but I have not received answers.it seems that it take too long there to get an answer.
