### ISSUE TITLE
Databricks nltk error | <urlopen error [Errno 104] Connection

### ISSUE THREAD

**Issue by rayamoh** [nltk/nltk#3056]
Downloaded nltk_data to /dbfs/FileStore/nltk_data folder and running below code
`nltk.download('punkt',download_dir="/dbfs/FileStore/nltk_data")`

Getting error: 
`[nltk_data] Error loading punkt: <urlopen error [Errno 104] Connection
[nltk_data]     reset by peer>
Out[16]: False`

This is from Azure databricks behind VPN with network blocked to nltk_data website , so uploaded nltk_data and referring to download_dir

Please assist how to troubleshoot and resolve the issue. Thanks!

**Comment by tomaarsen** [comment]
Hello!

The `download_dir` parameter indicates which directory NLTK should download the packages to, i.e. it will still download the packages. However, it is indeed possible to download the packages manually. I would recommend placing the downloaded files in either of the locations indicated by `nltk.data.path`:
```
>>> import nltk
>>> nltk.data.path
['/home/tom/nltk_data', '/usr/nltk_data', '/usr/share/nltk_data', '/usr/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']
```
(These locations will differ for you). 

Then, you can download the package you want, `packt` in this case, from https://github.com/nltk/nltk_data/tree/gh-pages/packages/tokenizers. 
It should then be placed in your chosen `nltk_data` folder like so:
```
.../nltk_data/tokenizers/punkt.zip
.../nltk_data/tokenizers/punkt/english.pickle
.../nltk_data/tokenizers/punkt/...
```
With other words, the punkt zip should be placed in a tokenizers folder still, and should be unzipped. The zip should remain, I believe.

From then onwards, there is no need for `nltk.download("punkt")` anymore. Whenever you use punkt in your project, NLTK will search in the `nltk.data.path` paths to find the `nltk_data` folder, and then try to find punkt in there. It should now be able to, and you should be all set.

I'll close this, as this should fix it, but let me know if it doesn't work, so I can help you further.

**Comment by rayamoh** [comment]
Thank you for getting back. I did manual upload of nltk_data to below highlighted folders in databricks from print(nltk.data.path). 

Still nltk.download('punkt')  is giving error `Error loading punkt: <urlopen error [Errno 104] Connection reset by peer>`
 
`['**/dbfs/databricks/nltk_data/**', '/home/spark-cbd3ef14-237a-4189-a6a4-0e/nltk_data', '/local_disk0/.ephemeral_nfs/envs/pythonEnv-cbd3ef14-237a-4189-a6a4-0e92b9c80898/nltk_data', '/local_disk0/.ephemeral_nfs/envs/pythonEnv-cbd3ef14-237a-4189-a6a4-0e92b9c80898/share/nltk_data', '/local_disk0/.ephemeral_nfs/envs/pythonEnv-cbd3ef14-237a-4189-a6a4-0e92b9c80898/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data', '**/databricks/nltk_data/**']`

**Comment by tomaarsen** [comment]
Indeed, `nltk.download("punkt")` will still try to connect over the internet, and you mentioned that the nltk_data website is inaccessible, hence the error. However, `nltk.download("punkt")` is not necessary if you've followed the manual download and placed them in any of those locations.

**Comment by rayamoh** [comment]
Thanks @tomaarsen , it works as expected now
