### ISSUE TITLE
Translating between language names and iso-639 codes

### ISSUE THREAD

**Issue by ekaf** [nltk/nltk#3058]
Some NLTK libraries (tag, crubadan, wordnet) use iso-639 language codes from the International Organization for Standardization (ISO). Iso-639 represents language names using either a 2-letter or 3-letter code that is not always very obvious: for ex. it may be difficult to guess that  _el_ or _ell_ are the codes for "Modern Greek".

In particular, the OMW data uses iso-639-3, though NLTK does not provide any clue about which languages the codes represent.

Wouldn't it be relevant to have functions available, to translate between language names and the corresponding language codes?

**Comment by ekaf** [comment]
_nltk_data/corpora/crubadan/table.txt_ seems to provide the necessary data in 3 columns, and _crubadan.py_ includes functions to translate between columns 1 and 2 from that file. To solve the present issue, it is easy to implement a translation between columns 2 and 3.
However the iso-639 codes in crubadan's _table.txt_ don't always seem very accurate, since it lists 'fra' as the code for Walloon, which should be 'wln'.

It would be better to use an authoritative source. For ISO 639-3, the registration authority is sil.org, and they make the relevant data package freely available at
https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Code_Tables_20220311.zip
However, they don't allow redistribution of this data.

**Comment by ekaf** [comment]
An alternative could be to extract a table from
https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019)

This yields 7859 unique iso639-3 codes with their corresponding (multiple) language names.

**Comment by stevenbird** [comment]
NB https://iso639-3.sil.org/

**Comment by ekaf** [comment]
@stevenbird, here is the iso639-3.sil.org policy. The last clause clearly means that they don't allow distributing their tables verbatim as a corpus in nltk_data. But the preamble indicates that NLTK might be allowed to incorporate the language codes in a .py file, for ex. as a Python dictionary, though the safest would be to ask them.

```
ISO 639-3 Code Tables Terms of Use

   The ISO 639-3 code set may be downloaded and incorporated into software
   products, web-based systems, digital devices, etc., either commercial
   or non-commercial, provided that:
     * attribution is given www.iso639-3.sil.org as the source of the
       codes;
     * the identifiers of the code set are not modified or extended except
       as may be privately agreed using the Private Use Area (range qaa to
       qtz), and then such extensions shall not be distributed publicly;
     * the product, system, or device does not provide a means to
       redistribute the code set.

```

**Comment by goodmami** [comment]
Also see https://pypi.org/project/langcodes/ which does just about anything you need with language codes (BCP-47), although one notable omission is the ability to map to ISO639-3 (it can map _from_ ISO639-3, and can map to ISO639-2, however).

**Comment by ekaf** [comment]
Thanks @goodmami. Ideally, NLTK would support both iso639-3 and bcp-47. A great advantage with bcp-47 is that the data can be freely redistributed (unlike iso639-3), so it would be possible to have a package in nltk_data, and process it with a CorpusReader. 
But bcp-47 is more difficult to deal with, because it sometimes includes several language  names for the same language code, and the data records don't indicate which one is the preferred name, while iso639-3 offers a neat 1:1 bijective correspondence between codes and names. In particular, it is problematic that bcp-47 overloads the 'ca' code with both "Catalan" and "Valencian", although they are different (though related) languages. 
So, for the moment, iso639-3 appears more linguistically satisfying.

**Comment by goodmami** [comment]
> it is problematic that bcp-47 overloads the 'ca' code with both "Catalan" and "Valencian"

That is not quite right. Whereas both ISO639-1's `ca` and ISO639-3's [`cat`](https://iso639-3.sil.org/code/cat) conflate Catalan and Valencian, BCP-47 (which encompasses both code systems and more with a syntax for assembling tags at various levels of specificity) is able to distinguish them with a subtag: `ca-valencia`.

BCP-47 can be as specific as you want it to be (`ca-Latn-ES-valencia` would be equivalent but redundant), but this open-ended nature can make it less useful when you want a simple and consistent mapping. I'm not advocating for either system. The descriptive power of BCP-47 is offset by its complexity.

**Comment by ekaf** [comment]
Thanks @goodmami, I have often seen those tags that you refer to, where a "territory" is appended to a language code, but I was not aware that they are an inherent part of BCP-47. My first impression was based on the much simpler official BCP-47 subtag registry file at
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

It includes records like:

> %%
> Type: language
> Subtag: ca
> Description: Catalan
> Description: Valencian
> Added: 2005-10-16
> Suppress-Script: Latn
> %%
 
The tag extension mechanism is more complex, but since it is a part of the BCP-47 specification, and very widely used, it could also be nice to support.

**Comment by ekaf** [comment]
An alternative could be to start by supporting the most used bcp47 tag combinations, as in this project:

https://github.com/highfestiva/bcp47.py
