### ISSUE TITLE
Resource stopwords not found.

### ISSUE THREAD

**Issue by mycar98765** [nltk/nltk#3063]
I get the following error:
```
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/Users/name/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.7/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.7/share/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.7/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

I get the above error when using the following code:
`from nltk.corpus import stopwords`

How to fix the error? Any help would be greatly appreciated. Thank you in advance!

**Comment by nlharri** [comment]
Hello,

Did you try to execute the following?

```python
import nltk
nltk.download('stopwords')
```

Does this return an error?

NLTK downloader should download corpora, toy grammars, trained models, etc. as described on https://www.nltk.org/data.html.

**Comment by nlharri** [comment]
> I get the following error:
> 
> ```
> **********************************************************************
>   Resource stopwords not found.
>   Please use the NLTK Downloader to obtain the resource:
> 
>   >>> import nltk
>   >>> nltk.download('stopwords')
>   
>   For more information see: https://www.nltk.org/data.html
> 
>   Attempted to load corpora/stopwords
> 
>   Searched in:
>     - '/Users/name/nltk_data'
>     - '/Library/Frameworks/Python.framework/Versions/3.7/nltk_data'
>     - '/Library/Frameworks/Python.framework/Versions/3.7/share/nltk_data'
>     - '/Library/Frameworks/Python.framework/Versions/3.7/lib/nltk_data'
>     - '/usr/share/nltk_data'
>     - '/usr/local/share/nltk_data'
>     - '/usr/lib/nltk_data'
>     - '/usr/local/lib/nltk_data'
> **********************************************************************
> ```
> 
> I get the above error when using the following code: `from nltk.corpus import stopwords`
> 
> How to fix the error? Any help would be greatly appreciated. Thank you in advance!


Hello,

Did you try to execute the following?

```python
import nltk
nltk.download('stopwords')
```

Does this return an error?

NLTK downloader should download corpora, toy grammars, trained models, etc. as described on https://www.nltk.org/data.html.

**Comment by tomaarsen** [comment]
NLTK's `stopwords` requires the stopwords to be first downloaded via the NLTK Data installer. This is a one-time setup, after which you will be able to freely use `from nltk.corpus import stopwords`.

To download the stopwords, open the Python interpreter with `python` in your terminal of choice, and type:
```python
>>> import nltk
>>> nltk.download("stopwords")
```

Afterwards, you're good to go!

**Comment by TheNewbie05** [comment]
![Screenshot 2023-12-28 101511](https://github.com/nltk/nltk/assets/141109307/9de0c570-b4f7-44d9-99f5-1bf440837f7b)

it is giving me this error

**Comment by lakith-pusarla** [comment]
I am facing the same issue as @TheNewbie05. I tried this in different virtual environment after installling 'nltk' via pip. Could not resolve this issue.

**Comment by Sachin-Deloitte** [comment]
Use the below code to pass the ssl connection:

import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt')
nltk.download('stopwords')

**Comment by mingjun1120** [comment]
> Use the below code to pass the ssl connection:
> 
> import nltk import ssl
> 
> try: _create_unverified_https_context = ssl._create_unverified_context except AttributeError: pass else: ssl._create_default_https_context = _create_unverified_https_context
> 
> nltk.download('punkt') nltk.download('stopwords')

Does this look correct? Is my indentation correct?
```
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt')
nltk.download('stopwords')
```
