### ISSUE TITLE
nltk.classify.maxent.MaxentClassifier.train() fails with scipy > v0.10

### ISSUE THREAD

**Issue by tttthomasssss** [nltk/nltk#307]
The Maximum Entropy Classifier fails with scipy versions newer than 0.10.

NLTK requires scipy.maxentropy which has been deprecated in scipy 0.10 and removed in all versions thereafter (that is from 0.11 onwards) --> see Docu: http://docs.scipy.org/doc/scipy-0.10.0/reference/maxentropy.html#

<b>Steps to reproduce:</b>

install latest scipy release

nltk.classify.maxent.demo() reproduces the error

<b>Setup:</b>

I am using NLTK v. 2.0.2 and scipy v. 0.12.0.dev-ddd617d

**Comment by pfeyz** [comment]
In SciPy's [0.11 release notes](https://github.com/scipy/scipy/blob/master/doc/release/0.11.0-notes.rst#backwards-incompatible-changes) they recommend scikit.learn's [LogisticRegression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression) as an alternative.
