### ISSUE TITLE
Broken URLs in Articles about NLTK

### ISSUE THREAD

**Issue by mohit-marathe** [nltk/nltk#3076]
There are 8 broken links in  this wiki page: https://github.com/nltk/nltk/wiki/Articles-about-NLTK 
I have found 7 working links corresponding to those broken links. 
I am listing down those **fixed URLs** here:
1. <a href="https://aclanthology.org/W09-3712.pdf">An Extensible Toolkit for Computational Semantics</a>
2. <a href="https://aclanthology.org/W08-0208.pdf" rel="nofollow" title="https://aclanthology.org/W08-0208.pdf">Multidisciplinary instruction with the Natural Language Toolkit</a>
3. <a href="https://aclanthology.org/W08-0209.pdf" rel="nofollow" title="https://aclanthology.org/W08-0209.pdf">Combining Open-Source with Research to Re-engineer a Hands-on Introductory NLP Course</a>
4. <a href="https://web.archive.org/web/20170815120825/https://minerva-access.unimelb.edu.au/bitstream/handle/11343/34057/66445_00001453_01_icon-05.pdf?sequence=1" rel="nofollow" title="https://web.archive.org/web/20170815120825/https://minerva-access.unimelb.edu.au/bitstream/handle/11343/34057/66445_00001453_01_icon-05.pdf?sequence=1">NLTK-Lite: Efficient Scripting for Natural Language Processing</a>
5. <a href="https://aclanthology.org/P04-3031.pdf" rel="nofollow" title="https://aclanthology.org/P04-3031.pdf">NLTK: The Natural Language Toolkit</a> (July 2004)
6. <a href="https://dl.acm.org/doi/pdf/10.3115/1118108.1118117" rel="nofollow" title="https://dl.acm.org/doi/pdf/10.3115/1118108.1118117">NLTK: The Natural Language Toolkit</a> (July 2002)
7. <a href="https://gnosis.cx/publish/programming/charming_python_b18.html" rel="nofollow" title="https://gnosis.cx/publish/programming/charming_python_b18.html" >Charming Python: Get started with the Natural Language Toolkit (IBM Developerworks) </a>

I still couldn't find a link to this article : Processing Corpora with Python and the Natural Language Toolkit (Freshmeat)

**Comment by tomaarsen** [comment]
For `NLTK-Lite: Efficient Scripting for Natural Language Processing`, I have also found the following persistent link at the bottom of the wayback-machine link: http://hdl.handle.net/11343/34057. Would you agree that that link is a better fit?

And as for the NLTK: The Natural Language Toolkit (July 2002), I don't believe that link is currently broken. Do you suggest replacing it? The current link is https://arxiv.org/abs/cs/0205028.

**Comment by mohit-marathe** [comment]
For `NLTK-Lite: Efficient Scripting for Natural Language Processing`, I agree with you that the persistent link: http://hdl.handle.net/11343/34057 would be a better fit.

And I just found out that the link for the `NLTK: The Natural Language Toolkit (July 2002)` is working, so there is no need to replace it.

**Comment by tomaarsen** [comment]
Wonderful! I think we're on the same page then. I've made the changes in https://github.com/nltk/nltk/wiki/Articles-about-NLTK/b712bf8ea6e839acc406a65eccc83046b095e192. I think they all work now 🎉

**Comment by mohit-marathe** [comment]
Great! Now that this is resolved, I'm closing this issue.
