### ISSUE TITLE
Texttiling and paragraphs

### ISSUE THREAD

**Issue by markdimi** [nltk/nltk#3084]
Hello. 

I have a block of text that I want to segment. However I found out that the texttiling implementation requires that the input text is split into paragraphs. My questions is why does this happen? Doesn't the algorithm create pseudosentences and blocks on its own? After all, Hearst didn't rely on sentences and paragraphs to segment text.

**Comment by tomaarsen** [comment]
> Doesn't the algorithm create pseudosentences and blocks on its own?

Yes, I believe it does. See the following code from `TextTilingTokenizer.tokenize`:
https://github.com/nltk/nltk/blob/bfb88ced60d34ae93e3075cc82c672199f823734/nltk/tokenize/texttiling.py#L84-L89

This calls `_mark_paragraph_breaks`, which identifies indented text or line breaks as the beginning of paragraphs. As a result, the input text only has to include two consecutive newlines somewhere. Perhaps this example script will help explain it a bit.

```python
from nltk.corpus import brown
from nltk.tokenize import TextTilingTokenizer, TreebankWordDetokenizer
from more_itertools import intersperse

tt = TextTilingTokenizer()
detokenizer = TreebankWordDetokenizer()

# Intersperse double newlines every 100 words in text from the brown corpus
# Normally you would hope to already have this information.
# With brown, you could also put newlines between every element in brown.paras()
words = intersperse("\n\n", brown.words()[:4000], n=100)
# Convert tokenized text back into one string
text = detokenizer.detokenize(words)
# Perform text tiling
segmented_text = tt.tokenize(text)
print(len(segmented_text))
# This outputs: 25
```

**Comment by markdimi** [comment]
> > Doesn't the algorithm create pseudosentences and blocks on its own?
> 
> Yes, I believe it does. See the following code

Well, as per your example, you created gaps ("\n\n") inside the text when in theory the algorithm should create those (with `w` and `k` hyperparameters). I suppose I could come up with a scheme for applying the algorithm correctly, but it should be by default (i.e. remove stopwords, apply lematization, create pseudosentences with length `w` and create paragraphs with `k` pseudosentences by adding line breaks).

**Comment by tomaarsen** [comment]
I'm afraid I'm not familiar enough with the algorithm. I was under the understanding that paragraphs must be included with newlines, and the algorithm simply groups adjacent paragraphs together as long as they are similar enough. Apologies for that.

**Comment by markdimi** [comment]
> the algorithm simply groups adjacent paragraphs together as long as they are similar enough

This is the last of the 3 steps of the algorithm. But i am not sure for the algorithm my self either, because the TT implementation does in fact account for `w` and `k` (according to the [documentation](https://www.nltk.org/api/nltk.tokenize.texttiling.html)), so in theory by giving various amounts of `n` (in your example code) it should return the same segments, but it it doesn't.

**Comment by marco-ve** [comment]
I just ran into the same problem. Maybe I am misunderstanding, but what is the point of a tiling algorithm if it expects pre-chunked text? If I knew where to insert the paragraph breaks, I wouldn't need the algorithm.

**Comment by 13rac1** [comment]
I had this question, so I read the original https://people.ischool.berkeley.edu/~hearst/papers/cl-texttiling97.pdf It is designed to find sub-topics, not paragraphs.
![img](https://github.com/nltk/nltk/assets/195061/e12936d4-e16a-48ab-9def-d8924207d7e0)

**Comment by markdimi** [comment]
So, it turns out I was wrong. TextTiling was created to segment (or identify the subtopic structure) of expository text. This is done first by creating token-sequence (or pseudo-sentences) of fixed length and second by creating gatherings of these token-sequences of fixed size as well, called blocks. Then the algorithm uses these blocks via a sliding window mechanism to find similarities and score each token-sequence gap and then segment the text. The last part is not relevant to the current topic. 

Hearst, didn't use normal sentences for the first part, and for the same reason, normal paragraphs for the second step, because of the irregularity of their length (inside a document) and it possibly leading to unbalanced comparisons. This is stated a few times in the 1997 paper and this is what confused me, when I found out that nltk's implementation of the algorithm used paragraph breaks.

However, examining the part of the algorithm called Boundary Identification (you could read the 1994 paper - Multi-Paragraph Segmentation Expository Text, which is more clear) you will see that Hearst used the paragraph breaks as natural boundaries for the segmentation process. Meaning, that if the Boundary Identification phase identifies a few  boundaries around the document, if they are not on a paragraph break, they would be moved to the closest paragraph break.  Which is pretty logical, given a document which is demarkated by paragraphs. This is actually the title of her seminal paper: Text Tiling: Segmenting Text into Multi-**paragraph** Subtopic Passages. So it turns out, Hearst used the paragraphs in the end.

Now, my issue was that I wanted to segment a transcript, which doesn't have paragraph breaks. That's why I started this issue. The  workaround is to create fake paragraph breaks  in the document. However, you have to make sure that the method you use can be justified, because the topic boundaries will be placed on top of those breaks you impose on the document.

I am closing this issue as solved. 
Thank you
