### ISSUE TITLE
Safe to use on Python 3.11?

### ISSUE THREAD

**Issue by kinghuang** [nltk/nltk#3089]
Is nltk 3.8 safe to use on Python 3.11? The [module's description and classifier tags](https://github.com/nltk/nltk/blob/3.8/setup.py#L68) only go up to Python 3.10.

**Comment by artificialcoder02** [comment]
Hey! 

Technically it should not be an issue to use nltk 3.8 on the newer versions of python.

**Comment by tomaarsen** [comment]
Hello @kinghuang,

I have previously attempted to support Python 3.11 for NLTK officially, but at the time the test suite would fail as one of the dependencies didn't work on Python 3.11 yet. 
However, when re-doing those tests today, everything seems to work as intended.

With other words, feel free to use NLTK 3.8 on Python 3.11. I'll work on adding official support, but that only involves updating the module description, documentation, classifier tags and CI test suite.

- Tom Aarsen

**Comment by tomaarsen** [comment]
It seems like one optional dependency still fails: python-crfsuite. It is only required for the `CRFTagger`. So, Python 3.11 should already work *unless* you are using that tagger.
