### ISSUE TITLE
Divide by zero error in empty probability distribution

### ISSUE THREAD

**Issue by adhiraj** [nltk/nltk#309]
> > > d = DictionaryProbDist(prob_dict={})
> > > [OK]
> > > 
> > > d = DictionaryProbDist(prob_dict={}, normalize=True)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Python/2.7/site-packages/nltk/probability.py", line 690, in **init**
> > >     p = 1.0/len(prob_dict)
> > > ZeroDivisionError: float division by zero

So basically, if the normalize or log parameter of DictionaryProbDist is set to True, an empty dictionary throws a divide-by-zero error because the size is not checked before normalization.

Link to errant line: https://github.com/adhiraj/nltk/blob/master/nltk/probability.py#L666

**Comment by stevenbird** [comment]
Thanks for the bug report. Resolved in https://github.com/nltk/nltk/commit/0afcfe0356682b8112dca8a7833af65c20efeb01
