### ISSUE TITLE
NLTK Download error #10060

### ISSUE THREAD

**Issue by r9922** [nltk/nltk#3093]
i tried from last 2 days , lots time i have spend but no soution found on internet,even when search link its also invalid.please give me the solution.help me.

![link](https://user-images.githubusercontent.com/121342205/209434469-f0ee538f-f810-4822-92a9-f8a0d886d1eb.PNG)
![10060](https://user-images.githubusercontent.com/121342205/209434470-a2244f68-5fb3-4439-8fc2-3adeb47e8843.PNG)

**Comment by tomaarsen** [comment]
Hello!

Thanks for reporting this. I'm struggling to reproduce this. Could you perhaps try to browse to https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml again? I can access this site now. Alternatively, how about https://www.nltk.org/nltk_data/index.xml?

**Comment by r9922** [comment]
in india i used jio wifi but now i chnaged my network to BSNL by mobile hotspot now its working  and also downoading package.
thanks for reply.
