### ISSUE TITLE
Lemmatization problem

### ISSUE THREAD

**Issue by rid181198** [nltk/nltk#3094]
I want to lemmatize the words using the "wordnet" method but I am missing the wordnet dataset because of the issue related to downloading. Does anybody have an issue downloading the "wordnet" dataset from https://www.nltk.org/data.html? Also, 

import nltk 
nltk.download('wordnet') 

is not working in python3.

**Comment by tomaarsen** [comment]
@rid181198 Please see https://github.com/nltk/nltk/issues/3092#issuecomment-1366526151.
