### ISSUE TITLE
Open Multilingual Wordnet support

### ISSUE THREAD

**Issue by JCLengeling** [nltk/nltk#3095]
I just noticed, that the documentation on the NLTK website references Open Multilingual Wordnet, however the link given there seems to be broken (https://www.nltk.org/api/nltk.corpus.reader.wordnet.html). This seems to be a long term known issue in the Open Multilingual Wordnet project  (https://github.com/globalwordnet/OMW/issues/110). Thus, maybe a reference to the OMW GitHub guide documenting how to self-host (https://github.com/globalwordnet/OMW/blob/develop/INSTALL.md) and how to work with the self-host with NLTK in the NLTK dokumentation could be a better approach.

**Comment by arademaker** [comment]
@fcbond, may have better option.
