### ISSUE TITLE
Update corpus metadata files

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#31]
Check that the license and other information in the corpus index files is correct.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=96</p>

**Comment by fcbond** [comment]
It would be nice to have a standard interface to access the license and citation interface, as we do for the readme.

I suggest adding to the API  something like:

``` python
   def license(self):
        """
        Return the contents of the corpus LICENSE file, if it exists.
        """
        if os.path.exist(self._root.join("LICENSE")):
            return self.open("LICENSE").read()
        else:
            return "No LICENSE found for this corpus (maybe check the README)"
```

And the same for '''citation' which would look for "citation.bib".

Then we need to add the LICENSE and citation info for each corpus.  I will do it for the open multilingual wordnet and wordnet.

**Comment by stevenbird** [comment]
Good idea. I've added this, but without the conditional, since I think it's fine let Python generate an error message. I see that there are many corpora containing `README.txt` instead of `README`, so that also needs to be standardized.
