### ISSUE TITLE
Hardcoded NaiveBayes classname on WekaClassifier._batch_classify

### ISSUE THREAD

**Issue by ldubiau** [nltk/nltk#310]
weka.py (line 88)

cmd = ['weka.classifiers.bayes.NaiveBayes', '-l', self._model, '-T', test_filename] + options

Classname should be a parameter as in the training method:

cmd = [javaclass, '-d', model_filename, '-t', train_filename]

**Comment by paulproteus** [comment]
Hi @tibidoh !

Are you interested in submitting your personally fixed version of NLTK as a pull request so that others can benefit?

If so, we would love that. If you need any help with that process, let us know!

**Comment by kmike** [comment]
Hi @paulproteus,

Alexander have submitted a pull request for this (https://github.com/nltk/nltk/pull/410); I think it needs a confirmation that demo doesn't work + small code changes to get merged.

**Comment by tibidoh** [comment]
We can close it as discussed at PR #410

**Comment by kmike** [comment]
Indeed.
