### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by haxkd** [nltk/nltk#3103]
![Capture](https://user-images.githubusercontent.com/33129246/211147608-c216bdd0-c90a-463b-8a80-06de80698aa3.PNG)
Error loading punkt: <urlopen error [WinError 10061] No connection could be made because the target machine  actively refused it>

**Comment by hackerprank03** [comment]
Same Issue whats the solution

**Comment by tomaarsen** [comment]
@hackerprank03 Here are some potential solutions: https://github.com/nltk/nltk/issues/3092#issuecomment-1366526151
Alternatively, others have reported success with a VPN or a mobile hotspot.

**Comment by haxkd** [comment]
@hackerprank03
1. just change your network
2. change your dns setting
3. Turn of vpn/Proxy
It'll help to solve out
