### ISSUE TITLE
Using Mobile Hotspot worked like magic. Thank you @AurekC

### ISSUE THREAD

**Issue by TrinityNe0** [nltk/nltk#3104]
Using Mobile Hotspot worked like magic. Thank you @AurekC

_Originally posted by @ishandutta0098 in https://github.com/nltk/nltk/issues/1981#issuecomment-646984229_
      
yes, hotspot truly does work like magic

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/77468918/winerror-10060-connection-timeout-error-when-downloading-punkt-in-nltk/77469069#77469069
