### ISSUE TITLE
IBM Model 5 nltk

### ISSUE THREAD

**Issue by shavetakhepra** [nltk/nltk#3108]
Can someone help with the following error

<ipython-input-85-d742fad1806b> in <module>
     
 8 from nltk.translate.ibm_model import Counts, longest_target_sentence_length
      9 
---> 10 class IBMModel5(IBMModel):
     11     bitext = []
     12     bitext.append(AlignedSent(['klein', 'ist', 'das', 'haus'], ['the', 'house', 'is', 'small']))

<ipython-input-85-d742fad1806b> in IBMModel5()
     32     print(round(ibm5.p1, 3))
     33     test_sentence = bitext[2]
---> 34     test_sentence.words['das', 'buch', 'ist', 'ja', 'klein']
     35     test_sentence.mots['the', 'book', 'is', 'small']
     36     test_sentence.alignment

TypeError: list indices must be integers or slices, not tuple

**Comment by tomaarsen** [comment]
I think you have made a copy-paste error somewhere. Your code here
```
32 print(round(ibm5.p1, 3))
33 test_sentence = bitext[2]
---> 34 test_sentence.words['das', 'buch', 'ist', 'ja', 'klein']
35 test_sentence.mots['the', 'book', 'is', 'small']
36 test_sentence.alignment
```
seems to match code blocks from [the documentation](https://www.nltk.org/api/nltk.translate.ibm5.html?highlight=ibm5#nltk.translate.ibm5.IBMModel5), with some notable exceptions:
`['das', 'buch', 'ist', 'ja', 'klein']` and `['the', 'book', 'is', 'small']` are outputs of printing `test_sentence.words` and `test_sentence.mots`, respectively. However, you have turned the input and output into one line:
```
test_sentence.words['das', 'buch', 'ist', 'ja', 'klein']
test_sentence.mots['the', 'book', 'is', 'small']
```
Unexpectedly, this does not work. After all, `test_sentence.words` and `test_sentence.mots` are both lists. and with this syntax you are trying to erroneously perform list indexing, as suggested by the error.

Hope that clears it up. I'll close this.

- Tom Aarsen
