### ISSUE TITLE
How to restore the sentence after participle？

### ISSUE THREAD

**Issue by zhanghanweii** [nltk/nltk#3112]
I have a list of sentences after word segmentation["``", "But", "I", "was", "n't", "ready", "for", "a", "career", "at", "that", "time", ".", "''"]，How can I restore them to sentence "But I wasn't ready for a ..."

**Comment by tomaarsen** [comment]
For this, people tend to use the [`TreebankWordDetokenizer`](https://www.nltk.org/api/nltk.tokenize.treebank.html?highlight=treebankworddetokenizer#nltk.tokenize.treebank.TreebankWordDetokenizer):

```python
>>> from nltk.tokenize.treebank import TreebankWordDetokenizer
>>> detokenizer = TreebankWordDetokenizer()
>>> tokenized_text = ["``", "But", "I", "was", "n't", "ready", "for", "a", "career", "at", "that", "time", ".", "''"]
>>> detokenizer.detokenize(tokenized_text)
'"But I wasn\'t ready for a career at that time."'
```

I hope that answers your question. I'll close this in the meantime.

**Comment by zhanghanweii** [comment]
> For this, people tend to use the [`TreebankWordDetokenizer`](https://www.nltk.org/api/nltk.tokenize.treebank.html?highlight=treebankworddetokenizer#nltk.tokenize.treebank.TreebankWordDetokenizer):
> 
> ```python
> >>> from nltk.tokenize.treebank import TreebankWordDetokenizer
> >>> detokenizer = TreebankWordDetokenizer()
> >>> tokenized_text = ["``", "But", "I", "was", "n't", "ready", "for", "a", "career", "at", "that", "time", ".", "''"]
> >>> detokenizer.detokenize(tokenized_text)
> '"But I wasn\'t ready for a career at that time."'
> ```
> 
> I hope that answers your question. I'll close this in the meantime.

Thanks a lot, I managed to solve this problem
