### ISSUE TITLE
'WordNetLemmatizer' object is not callable

### ISSUE THREAD

**Issue by JocelyneYataco99** [nltk/nltk#3121]
https://www.kaggle.com/code/abhijitsingh001/mbti-test-your-personality/notebook

I was following this webpage steps and the lines below were not working in google collab and were giving me an error message which is the title of the post.

In[13] vectorizer=TfidfVectorizer( max_features=5000,stop_words='english',tokenizer=Lemmatizer())
vectorizer.fit(train_data.posts)

**Comment by tomaarsen** [comment]
You're missing the cell at [12] that defines `Lemmatizer` with a `__call__`: 
```python
class Lemmatizer(object):
    def __init__(self):
        self.lemmatizer = WordNetLemmatizer()

    def __call__(self, sentence):
        return [self.lemmatizer.lemmatize(word) for word in sentence.split() if len(word)>2]
```
Note that `WordNetLemmatizer` itself is not callable, i.e. it does not define a `__call__` method. You must use `WordNetLemmatizer().lemmatize(...)`.

I'll close this for now, as I suspect you'll be able to solve it now. Feel free to reopen if you disagree.

- Tom Aarsen
