### ISSUE TITLE
PickleCorpusView (still) raising UnicodeDecodeError when reading file

### ISSUE THREAD

**Issue by Ubadub** [nltk/nltk#3124]
In July 2019, issue #2331 was raised reporting that the `PickleCorpus` view raises a `UnicodeDecodeError`. This issue has not been fixed, though the issue was closed in the March 2020. In that issue, it was claimed that NLTK version 3.5 would fix this bug, but this is apparently not the case, as the buggy code is still in NLTK 3.8.1:

```python
class PickleCorpusView(StreamBackedCorpusView):

    BLOCK_SIZE = 100
    PROTOCOL = -1

    def __init__(self, fileid, delete_on_gc=False):
        self._delete_on_gc = delete_on_gc
        StreamBackedCorpusView.__init__(self, fileid)
```

The call to the `StreamBackedCorpusView` constructor should include the argument `encoding=None`, otherwise, that superclass will attempt to read from the file as if it were utf-8 encoded text.

An example of the error that I am seeing follows. The file `pickle50.out` is a file that I created by manually calling `pickle.dump`:

```python
>>> pcv = PickleCorpusView('scripts/pickle50.out')
>>> pcv[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/reader/util.py", line 265, in __getitem__
    return next(self.iterate_from(i))
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/reader/util.py", line 306, in iterate_from
    tokens = self.read_block(self._stream)
  File "/usr/local/lib/python3.10/site-packages/nltk/corpus/reader/util.py", line 526, in read_block
    result.append(pickle.load(stream))
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 1055, in read
    chars = self._read(size)
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 1353, in _read
    chars, bytes_decoded = self._incr_decode(bytes)
  File "/usr/local/lib/python3.10/site-packages/nltk/data.py", line 1375, in _incr_decode
    return self.decode(bytes, "strict")
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

However, calling `read_block(f)` directly with a file handle already opened in `rb` mode does work, but of course that does not allow us to use the corpus reader object like an iterable or sequence.

I can confirm that creating a subclass of `PickleCorpusView` that overrides `__init__` with the correct logic fixes the bug, e.g:

```python
class MyPickleCorpusView(StreamBackedCorpusView):
    def __init__(self, fileid, delete_on_gc=False):
        self._delete_on_gc = delete_on_gc
        StreamBackedCorpusView.__init__(self, fileid, encoding=None)
```

An object of this class behaves as `PickleCorpusView` is intended to behave.

**Comment by Ubadub** [comment]
@stevenbird Is there any update on this issue? It is really a very simple fix, but without it, this class is borderline useless.

**Comment by Ubadub** [comment]
I have opened a PR for this- #3230.

**Comment by alvations** [comment]
Thank you @Ubadub for the discussion and contribution.

Unfortunately, PickleCorpusView has been remove from NLTK, might be best for everyone to avoid using it too. Closing this issue.
