### ISSUE TITLE
missing word ‒ aegilops

### ISSUE THREAD

**Issue by cronogram** [nltk/nltk#3129]
### nltk-3.8.1. 

I used the following program to create a file with English words. I noticed that the word **AEGILOPS** is missing.

```
import nltk

nltk.download('words')
english_words = set(nltk.corpus.words.words())
with open('english_words.txt', 'w') as f:
    for word in english_words:
        f.write(word + '\n')
```

Aegilops is the longest abecedarian word in the English language.

**Comment by stevenbird** [comment]
Sorry, this wordlist is not maintained by NLTK

**Comment by cronogram** [comment]
I'm sorry. Can you please point me in the right direction? Where should I post this issue?
