### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by edmondium** [nltk/nltk#3136]
Hi,
I'm trying to run a code in Figure 3.4 from NLTK book. In my Jupyter, the code is seen below:
`
# -*- coding: utf-8 -*-

import re
sent = """
Przewiezione przez Niemców pod koniec II wojny światowej na Dolny Śląsk, zostały odnalezione po 1945 r. na terytorium Polski.
"""
u = sent.decode('utf8')
u.lower
`
but the Jupyter returns an error of no attribute 'decode'. Any idea how to fix this?

**Comment by salih482** [comment]
Why are you writing sentence between three  parantheses?

**Comment by freekklein** [comment]
This is not an issue of the NLTK package. And you cannot decode a string object, but only bytes objects.
