### ISSUE TITLE
NLTK 3.8.1 not tagged as release

### ISSUE THREAD

**Issue by ferdnyc** [nltk/nltk#3139]
Hi, I see [from PyPi](https://pypi.org/project/nltk/#history) and the [project website](https://www.nltk.org/news.html) that NLTK 3.8.1 was released in January, but it doesn't seem to have been tagged/released in the GitHub repo.

**Comment by tomaarsen** [comment]
@ferdnyc Thanks for letting me know! I made the tag, but forgot to push it with `git push --tags`. I've done so now.
I think this should be resolved now, so I'll close this :)
