### ISSUE TITLE
Universal part of speech tagset

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#316]
Add mappings from the tagsets of existing NLTK corpora to this universal tagset
http://arxiv.org/pdf/1104.2086.pdf
(possibly replacing the simplify_tags option on corpus readers)

**Comment by nschneid** [comment]
I once wrote a simple interface that might be useful as a starting point: https://gist.github.com/4231292

**Comment by stevenbird** [comment]
This is implemented in NLTK 3.
