### ISSUE TITLE
Broken GitHub Actions' Cache

### ISSUE THREAD

**Issue by zakkie** [nltk/nltk#3163]
I created PR #3161, but it has failed. (also #3158 and #3162)

https://github.com/nltk/nltk/actions/runs/5221162228/jobs/9426112230?pr=3161
> pytest: command not found

But CI succeeded in my repository with the same code:
https://github.com/zakkie/nltk/actions/runs/5234511453

The difference is there is a GitHub Actions' cache or not.

It seems the cache is broken, so I think the cache needs to be deleted.

**Comment by tomaarsen** [comment]
Hello!

I've deleted all caches, and I'll rerun your CI.

**Comment by tomaarsen** [comment]
You're right, that seemed to have resolved it. I'll close this for now! Thanks for notifying us, I thought that perhaps the GitHub action was simply broken with the combination of Mac and Python 3.11.

**Comment by zakkie** [comment]
Hi @tomaarsen,
Thank you for your quick response!
