### ISSUE TITLE
Dear Jan Strunk 

### ISSUE THREAD

**Issue by hiDevman** [nltk/nltk#3166]
I wonder Punkt Tokenizer Models's license.

I read below link: 
https://github.com/nltk/nltk_data/issues/188
https://github.com/nltk/nltk/issues/3015

But No one answer about them.
Jan Strunk, Why don't you reply these questions?
Is it possible to use for commerical use?
Is it possible to redistributable?

**Comment by Higgs32584** [comment]
bro sounds like an investigative reporter

**Comment by rmalouf** [comment]
I'm going to close this. Any updates on the license question can get added to nltk/nltk_data#188
