### ISSUE TITLE
Download somehow blocked

### ISSUE THREAD

**Issue by sjkoelle** [nltk/nltk#3185]
See https://github.com/tailscale/tailscale/issues/9096

Sometimes (e.g. in jupyter), I have to retry nltk.download() several times to make it work.  Is there a more robust downloading system that could be used?

**Comment by tomaarsen** [comment]
Hello! Some users, particularly those who are using the "Jio" internet provider, have experienced this issue. They seemed to have been able to resolve it by connecting to mobile hotspot temporarily while downloading punkt, or by changing some DNS settings.

There's a bit more info here, perhaps it'll help: https://github.com/nltk/nltk/issues/3146
