### ISSUE TITLE
Unable to download Stopwords and also unable to access stopwords zip file manually.

### ISSUE THREAD

**Issue by mdabdulrahman** [nltk/nltk#3194]
Here is error when I try to download stopwords package in terminal
Code :
```
>>import nltk
>>nltk.download("stopwords")
```
Error :
```
[nltk_data] Error loading stopwords: <urlopen error [WinError 10054]
[nltk_data]     An existing connection was forcibly closed by the
[nltk_data]     remote host>
```
Then tried to install it manually but the link is doesn't seems to work
Link :[ stopwords zip link]( https://[raw.githubusercontent.com](https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/stopwords.zip)/nltk/nltk_data/gh-pages/packages/corpora/stopwords.zip)

**Comment by tomaarsen** [comment]
Some users, particularly those who are using the "Jio" internet provider, have experienced this issue. They seemed to have been able to resolve it by connecting to mobile hotspot temporarily while downloading NLTK resources, or by changing some DNS settings.

There's a bit more info here, perhaps it'll help: https://github.com/nltk/nltk/issues/3146

**Comment by mdabdulrahman** [comment]
> Some users, particularly those who are using the "Jio" internet provider, have experienced this issue. They seemed to have been able to resolve it by connecting to mobile hotspot temporarily while downloading NLTK resources, or by changing some DNS settings.
> 
> There's a bit more info here, perhaps it'll help: #3146

Thanks, yes that's the issue.
I have tried it today it works now!!
