### ISSUE TITLE
NLTK is considering "hi"  and "hello" as a noun.

### ISSUE THREAD

**Issue by RishitAtwal** [nltk/nltk#3198]
NLTK is considering "hi"  and "hello" as a noun. Instead , it should be a verb or interjection.

**Comment by tomaarsen** [comment]
The NLTK POS tagging model, like all NLP models, is not perfect. You can also try the spaCy POS tagging models, perhaps they work better for you!

**Comment by arademaker** [comment]
You need to be more specific. Can you share here the minimal code that reproduces the unexpected behavior? 

Also note that many modules in NLTK are not deterministic, so keep in mind that stochastic models my produce errors when training data or context were insufficient.

**Comment by arademaker** [comment]
Sorry, I repeat @tomaarsen, didn’t see his message before writing my own.

**Comment by tomaarsen** [comment]
No worries! We posted about at the same time :)
