### ISSUE TITLE
English NER data

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#32]
What data set would you like to have added to NLTK?  If you have a particular corpus in mind, 
please include information about availability, license, and permission for us to redistribute the 
data.

There should be some English named entity data in the NLTK corpus collection.  We have the 
CoNLL 2002 data for Spanish and Dutch.  The CoNLL 2003 data may be suitable:

&gt; Language-Independent Named Entity Recognition at CoNLL-2003
&gt; Notes: This dataset is a manual annotatation of a subset of RCV1 (Reuters Corpus Volume 1).
&gt; The annotation per se is available free of charge (subject to a licensing agreement) from the
&gt; CoNLL site. The raw text of RCV1 documents must be requested from NIST (also free of charge
&gt; and also subject to a licensing agreement).
&gt; http://www.cnts.ua.ac.be/conll2003/ner

http://www.cs.technion.ac.il/~gabr/resources/data/ne_datasets.html

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=109</p><hr/><h2>earlier comments</h2>
<p><strong>ewan.klein said, at 2008-11-27T09:56:58.000Z:</strong></p>
<p>The CoNLL 2003 data might be a good bet, but I haven't got round to looking at it
since the procedure for merging the annotation and the raw data presupposes you have
the Reuters data available as a CD. 

The MUC34 data doesn't seem to be in a suitable format. It would be really nice if we
could get hold of a portion of MUC7 from LDC, since it is one of the canonical datasets.</p><p><strong>StevenBird1 said, at 2009-02-15T05:10:00.000Z:</strong></p>
<p>We have a trained model for named-entity tagging, so providing a corpus is less
important now.
</p>

**Comment by tgalery** [comment]
Sorry to disagree I think having the data might be interesting for a variety of tasks. Also, topic extraction is moving from text classification to entity linking, so datasets like the ones documented in the first task of  http://www.wise2013.org/wise2013challenge.html and https://code.google.com/p/wiki-link/wiki/ExpandedDataset might be relevant. Providing an easy way to package and this type of corpora in nltk might be very useful.

**Comment by kmike** [comment]
+1 for CoNLL 2003. I think that training data is more important than pre-training models because you learn by training your own models, not by using some prebuilt ones.

**Comment by roopalgarg** [comment]
+1 for CoNLL 2003. Could really use that for NER work.

**Comment by jnothman** [comment]
I think this is a good idea. It might also be interesting to add the entity disambiguation layer annotated by the YAGO-AIDA project (Hoffart et al).

**Comment by stevenbird** [comment]
Closing, as we don't have capacity to take this on.
