### ISSUE TITLE
ToktokTokenizer doesn't call one of the included replacement patterns and thus doesn't tokenize some punctuation, like opening guillemets

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#3202]
Right now, if you do something like:

```lang:python
import nltk
toktok = nltk.tokenize.ToktokTokenizer()
toktok.tokenize("«Sí, por favor.»")
['«Sí', ',', 'por', 'favor', '.', '»']
```
... you can see that the opening punctuation isn't split off from the first word. There's an included pattern in nltk.tokenize.ToktokTokenizer, but it's not invoked! Invoking the pattern gives the appropriate punctuation splitting.

I'm about to send a PR for this; it also removes a redundant call that does the same regex twice, and makes the testing for ToktokTokenizer a bit more robust.

**Comment by tomaarsen** [comment]
Resolved via #3203. Thanks!
