### ISSUE TITLE
`corpus_bleu` function does not catch all the expections when calling `weights[0][0]`

### ISSUE THREAD

**Issue by zhaochenyang20** [nltk/nltk#3204]
In your codes https://github.com/nltk/nltk/blob/e2d368e00ef806121aaa39f6e5f90d9f8243631b/nltk/translate/bleu_score.py#L201

I pass in `weights = array([0.25, 0.25, 0.25, 0.25])` and find this error:

```
File "/home/cyzhao/miniconda3/envs/prompt/lib/python3.11/site-packages/nltk/translate/bleu_score.py", line 200, in corpus_bleu
    weights[0][0]
    ~~~~~~~~~~^^^
IndexError: invalid index to scalar variable.
"""
```

I then find out the reason why.

Not all exceptions are completely caught. The `weights` passed in by the framework are `array([0.25, 0.25, 0.25, 0.25])`, and for `ndarray` the error is `IndexError: invalid index to scalar variable`. Hence, these codes haven't caught all the exceptions, leading to the situation where one must pass a tuple `(0.25, 0.25, 0.25, 0.25)` to be caught by this try-except block.

**Comment by tomaarsen** [comment]
Hello!

> The function's parameter is supposed to be a tuple.

It can also be a list of tuples, as explained in the docstring. I suspect that the author of this piece of code lived by the [EAFP](https://docs.python.org/3/glossary.html#term-EAFP) principle for Python, causing this code to not be so strange at all. Beyond that, NLTK lives by a garbage-in-garbage-out rule, so incorrectly typed inputs can't be expected to work. 
That all said, I'll resolve your issue by replacing `except TypeError` with just `except`, but in the future I would watch your writing tone with these bug reports.

- Tom Aarsen

**Comment by zhaochenyang20** [comment]
@tomaarsen Oops. Sorry for the wrong tone of bug reports and my carelessness. I changed it. Thanks for your support.

**Comment by tomaarsen** [comment]
I appreciate it, no hard feelings 😄
