### ISSUE TITLE
Not able to download the NLTK data module (python as well as manual download)

### ISSUE THREAD

**Issue by subhra-ranjan-padhy** [nltk/nltk#3220]
I am unable to download the NLTK data module files. I have attempted to download the data file using Python and have also tried manual downloading.

As mentioned in the documentation:

**Python:**

import nltk
nltk.download('punkt')

**Manual download:**

I am encountering issues with downloading from https://www.nltk.org/nltk_data/.

**Comment by subhra-ranjan-padhy** [comment]
This issue was due to ISP blocking the site. It got fixed after changing internet connection.

**Comment by tomaarsen** [comment]
Awesome, glad you got it resolved!
