### ISSUE TITLE
Fraction object creation fails with extra kwargs in bleu_score.py

### ISSUE THREAD

**Issue by destroy-lonely** [nltk/nltk#3232]
Hi there,
I ran into an error when trying to use the nltk.translate.bleu_score.sentence_bleu function. It seems to fail when the reference or hypothesis contains a Fraction number with additional keyword arguments.
Here's the error: Fraction.__new__() got an unexpected keyword argument '_normalize'.
After I change  
"Fraction(p_numerators[i], p_denominators[i], _normalize=False)"
into 
"Fraction(p_numerators[i], p_denominators[i])"
Everthing goes well. Could the implementation be updated to check for and handle Fraction instances appropriately?
![issue1](https://github.com/nltk/nltk/assets/124790850/ad267c63-46c8-4498-8131-f5663984b3db)

**Comment by georgerapeanu** [comment]
Can confirm, it also shows the same error for me under python 3.12 on ubuntu, with nltk==3.8.1

Update: manually fixed it by applying the patch from the development branch locally

**Comment by rmalouf** [comment]
This is fixed by #3207.
