### ISSUE TITLE
i want to write python script i have italian text files that who i verify my word in italian dictionery please solve

### ISSUE THREAD

**Issue by imtiaz231** [nltk/nltk#3234]
this error occur
OSError: No such file or directory: 'C:\\Users\\LAPTOP OUTLET\\AppData\\Roaming\\nltk_data\\corpora\\words\\it'

**Comment by rmalouf** [comment]
NLTK doesn't include an Italian word list. Use `nltk.corpora. words.fileids()` to get a list of word lists that are available.
