### ISSUE TITLE
stem accuracy

### ISSUE THREAD

**Issue by Moustafa1Rizk1** [nltk/nltk#3239]
Dears,
     i am trying to use stemmers for some of the words, however, the stemming is not accurate.

example

from nltk.stem import PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

ps = PorterStemmer()
st = LancasterStemmer()

def prepareWord(word):
    print(word, " : ", st.stem(word))
    return st.stem(word)

input  : shelves

result: shelv

expected shelf

i need to know what is the alternative or this is a defect

**Comment by Moustafa1Rizk1** [comment]
Dears.

     is there any update, alternative or workaround?

My Best Regards

**Comment by ryanamannion** [comment]
If you want the output "shelf" you probably want lemmatization, not stemming.

Try [WordNetLemmatizer](https://www.nltk.org/api/nltk.stem.WordNetLemmatizer.html?highlight=wordnet)
