### ISSUE TITLE
Error loading punkt: <urlopen error [SSL: [nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed: [nltk_data]     unable to get local issuer certificate (_ssl.c:1000)>

### ISSUE THREAD

**Issue by slpminn** [nltk/nltk#3254]
Hi,
I am new to python and I am having issues running my code in locahost on a m3 mac.  I am assuming that I need to create a self-signed certificate, but I am stump.  Any help would be great. 

This is my code:

import nltk 
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.downloader import Downloader
try:
  nltk.download('punkt')
except Exception as e:
  print(f"Error downloading punkt resource: {e}")

text = """This is an example text. It has multiple sentences. 
Let's see how NLTK tokenizes them. NLTK also provides functionalities 
for other types of text processing tasks."""

print("Original text:")
print(text)

try:
  sentences = nltk.sent_tokenize(text)
  print("\nSentences after tokenization:")
  for sentence in sentences:
    print(sentence)
except Exception as e:
  print(f"Error during sentence tokenization: {e}")
  # Optionally, you can add logic here to handle the tokenization error.

I keep getting this error message:
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1000)>

**Comment by annumberhocker** [comment]
@slpminn Did you find your answer?  I am having the same issue?

**Comment by annumberhocker** [comment]
This fixed it for me:

```
open /Applications/Python\ 3.12/Install\ Certificates.command
```
See:
https://timonweb.com/python/fixing-certificate_verify_failed-error-when-trying-requests-html-out-on-mac/

**Comment by aragrow** [comment]
Yes, I am using flask and I create a self-signed certificate. and then used that way.
if (__name__) == "__main__":
    app.run(debug=True, port=5003, ssl_context=("/Users/tom/.ssl/cert.pem","/Users/tom/.ssl/key.pem"))
