### ISSUE TITLE
Not able to install nltk on termux, getting the following error:

### ISSUE THREAD

**Issue by divyanshluthra** [nltk/nltk#3255]
~/.../python/build $ pip install nltk
Collecting nltk                                           Using cached nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Collecting click (from nltk)                              Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)                                                   Collecting joblib (from nltk)                             Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)                                                  Collecting regex>=2021.8.3 (from nltk)                    Using cached regex-2024.5.15.tar.gz (394 kB)            Installing build dependencies ... done                  Getting requirements to build wheel ... done
  Installing backend dependencies ... done                Preparing metadata (pyproject.toml) ... done          Collecting tqdm (from nltk)                               Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)                                                    Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)       Using cached click-8.1.7-py3-none-any.whl (97 kB)       Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Building wheels for collected packages: regex
  Building wheel for regex (pyproject.toml) ... error     error: subprocess-exited-with-error
                                                          × Building wheel for regex (pyproject.toml) did not run successfully.
  │ exit code: 1                                          ╰─> [20 lines of output]
      running bdist_wheel                                     running build
      running build_py
      creating build                                          creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/regex
      copying regex_3/__init__.py -> build/lib.linux-aarch64-cpython-311/regex
      copying regex_3/regex.py -> build/lib.linux-aarch64-cpython-311/regex
      copying regex_3/_regex_core.py -> build/lib.linux-aarch64-cpython-311/regex
      copying regex_3/test_regex.py -> build/lib.linux-aarch64-cpython-311/regex
      running build_ext                                       building 'regex._regex' extension
      creating build/temp.linux-aarch64-cpython-311           creating build/temp.linux-aarch64-cpython-311/regex_3                                                           aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.11 -c regex_3/_regex.c -o build/temp.linux-aarch64-cpython-311/regex_3/_regex.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.11 -c regex_3/_regex_unicode.c -o build/temp.linux-aarch64-cpython-311/regex_3/_regex_unicode.o             aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib build/temp.linux-aarch64-cpython-311/regex_3/_regex.o build/temp.linux-aarch64-cpython-311/regex_3/_regex_unicode.o -L/data/data/com.termux/files/usr/lib -lpython3.11 -o build/lib.linux-aarch64-cpython-311/regex/_regex.cpython-311.so
      aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'                              error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1        [end of output]
                                                          note: This error originates from a subprocess, and is likely not a problem with pip.                            ERROR: Failed building wheel for regex
Failed to build regex                                   ERROR: Could not build wheels for regex, which is required to install pyproject.toml-based projects

**Comment by ekaf** [comment]
NLTK can't solve this issue. The problem is most likely your computer platform.
