### ISSUE TITLE
missing delimiter for 'u' glob qualifier

### ISSUE THREAD

**Issue by bijubjs** [nltk/nltk#3263]
I am trying to import nltk but got following error:
ModuleNotFoundError: No module named 'nltk'

Even though I already installed nltk in my Mac using "pip install nltk" (see below as well).

After some research I found that nltk.download() might help. So, I did "nltk.download('punkt')" but got the error "zsh: missing delimiter for 'u' glob qualifier".

How to fix this problem (see below for more detail)?

b@B-MacBook-Pro ~ % pip install nltk --upgrade
Requirement already satisfied: nltk in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (3.8.1)
Requirement already satisfied: click in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nltk) (4.64.1)
b@B-MacBook-Pro ~ % nltk.download('punkt') 

zsh: missing delimiter for 'u' glob qualifier

**Comment by kishan2k2** [comment]
Try doing it in a virtual environment. Or do pip uninstall and then install it all over again.

**Comment by bijubjs** [comment]
Thank you. I was able to fix it by changing Kernel.

**Comment by vision360deg** [comment]
> Thank you. I was able to fix it by changing Kernel.

@bijubjs could you please explain more in detail how you fixed it? --Thank you

**Comment by bijubjs** [comment]
If you are using VS code, there should be a search bar on the top of your screen inside VSCode. There you can select which kernel to use. I have a few kernels installed and I switched between them. Although not a guaranteed solution, sometimes ChatGPT also has an answer.
