### ISSUE TITLE
nltk.metrics.aline feature map missing IPA symbols

### ISSUE THREAD

**Issue by TomerYS** [nltk/nltk#3285]
For nltk.metrics.aline there seem to be missing some IPA vowels like "ʌ" or "ʊ" in the feature map.

**Comment by WilliamPLaCroix** [comment]
Created a pull request adding missing vowels from [Wikipedia IPA vowel chart](https://en.wikipedia.org/wiki/IPA_vowel_chart_with_audio) here in [issue #3323](https://github.com/nltk/nltk/pull/3323)

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/9a5622f8a5b228df9499cd03181d9f8491e39f17
