### ISSUE TITLE
Incomplete Language Support in NLTK for Open Multilingual WordNet

### ISSUE THREAD

**Issue by zarkua** [nltk/nltk#3288]
I've been using NLTK's interface to access the Open Multilingual WordNet (OMW). According to the WordNet website, OMW Version 1 links hand-created wordnets and automatically created wordnets for over 150 languages through the Princeton WordNet of English. However, when I check the available languages using NLTK, I only get the following list:

['als', 'arb', 'bul', 'cat', 'cmn', 'dan', 'ell', 'eng', 'eus', 'fin', 'fra', 'glg', 'heb', 'hrv', 'ind', 'isl', 'ita', 'ita_iwn', 'jpn', 'lit', 'nld', 'nno', 'nob', 'pol', 'por', 'ron', 'slk', 'slv', 'spa', 'swe', 'tha', 'zsm']

It appears that there is a significant discrepancy between the number of languages mentioned on the WordNet website and those available through NLTK.

Questions:

Is there a way to download or access the additional languages that are supposed to be part of OMW Version 1?
Is the limitation of available languages in NLTK a known issue, or is there something I might be doing wrong in my setup?

**Comment by ekaf** [comment]
You need to load the ext_omw package. Please see https://github.com/nltk/nltk/pull/2946
