### ISSUE TITLE
[BUG] punkt_tab breaking change

### ISSUE THREAD

**Issue by robcaulk** [nltk/nltk#3293]
One of the recent updates has broken the ability to obtain punkt with the traditional method:

```
os.system("python3 -m nltk.downloader punkt")
nltk.download('punkt')
```

Instead, apps which have only bumped the patch from 3.8.1 to 3.8.2 are now breaking with:

```
90  Resource [93mpunkt_tab[0m not found.91  Please use the NLTK Downloader to obtain the resource:9293  [31m>>> import nltk94  >>> nltk.download('punkt_tab')95  [0m96  For more information see: https://www.nltk.org/data.html9798  Attempted to load [93mtokenizers/punkt_tab/english/[0m
```

The issue is seen downstream with:

https://github.com/Unstructured-IO/unstructured/issues/3511

And resolved by pinning the version to 3.8.1.

**Comment by ekaf** [comment]
The "punkt" package consists in unsafe pickles, so it is deprecated and not used in NLTK 3.8.2. It is replaced by "punkt_tab". Users should definitively avoid the [highly toxic pickle vulnerability,](https://github.com/nltk/nltk/issues/3266#issuecomment-2284001819) and upgrade to NLTK 3.8.2.

**Comment by ZenBel** [comment]
so one should replace `nltk.download('punkt')` with `nltk.download('punkt_tab')`?

**Comment by ekaf** [comment]
> so one should replace nltk.download('punkt') with nltk.download('punkt_tab')?

Yes, provided you are using NLTK 3.8.2. Earlier versions use the unsafe "punkt" package, and don't include the code to handle the new "punkt_tab" package.

**Comment by robcaulk** [comment]
The “fix” is not acceptable by industry standard dev practices.

If you are planning to make a breaking change, it should be done on the major, not the minor or the patch.

Otherwise, developers following industry standard practices of ^3.8.* will wake up to broken pipelines and applications.

https://semver.org/

**Comment by robcaulk** [comment]
Wouldn’t it be easy enough to modify `download()` to simply catch `punkt` and replace the string with `punkt_tab`?

Can you help us to understand why this needed to be a breaking change instead?

**Comment by 1mpale** [comment]
is it even working on 3.8.2? 

I've changed it to punkt_tab but still see this

```
Exception while executing function: Functions.create-case-embeddings Result: Failure
Exception: LookupError: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
```
    
I am using it via docker. Anyone has an idea on how to specify the previous version there?
    
```
FROM --platform=linux/x86_64 public.ecr.aws/lambda/python:3.11

COPY requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip install \
    -r ${LAMBDA_TASK_ROOT}/requirements.txt -t ${LAMBDA_TASK_ROOT}
    
RUN python3 -m nltk.downloader averaged_perceptron_tagger -d ${LAMBDA_TASK_ROOT}/nltk_data && \
    python3 -m nltk.downloader punkt_tab -d ${LAMBDA_TASK_ROOT}/nltk_data

COPY . ${LAMBDA_TASK_ROOT}

WORKDIR ${LAMBDA_TASK_ROOT}

CMD [ "main.lambda_handler" ]
```

**Comment by ekaf** [comment]
Thanks @robcaulk , yes this will require a major bump. But before that, there seems to be issues to take care of, for ex. regardingWindows   compatibility.

**Comment by gregd33** [comment]
Is there documentation on how to use the new format? I can successfully download it but `nltk.data.load("english")` gives an error because it is expecting a file and not a folder.

**Comment by gregd33** [comment]
Is there info on how to use this (once downloaded, which works fine). `nltk.data.load` seems to be expecting a file but instead of one pickle there are four files?

I'm trying to see how to use with another downstream package, `sumy` - https://github.com/miso-belica/sumy/blob/main/sumy/nlp/tokenizers.py#L203

**Comment by mbanon** [comment]
I am having the same issue as @gregd33 , I have no idea on how to go from this `load('tokenizers/punkt/{0}.pickle'.format(langname))` to something working with the new version.

**Comment by stevenbird** [comment]
Ah, yes, sorry, this should have been a 3.9 beta. Happy to take down 3.8.2 and build 3.9b1 at the end of the week.

**Comment by 1mpale** [comment]
is nltk.downloader updated to make use of the latest update? @stevenbird @ekaf

**Comment by mbanon** [comment]
> Is there info on how to use this (once downloaded, which works fine). `nltk.data.load` seems to be expecting a file but instead of one pickle there are four files?
> 
> I'm trying to see how to use with another downstream package, `sumy` - https://github.com/miso-belica/sumy/blob/main/sumy/nlp/tokenizers.py#L203

Replacing the previous load with PunktTokenizer() as in this commit https://github.com/nltk/nltk/commit/496515efe45b5b708d15153983c7022cb1f32ac7 solved it for me.

**Comment by tomteecezint** [comment]
> > Is there info on how to use this (once downloaded, which works fine). `nltk.data.load` seems to be expecting a file but instead of one pickle there are four files?
> > I'm trying to see how to use with another downstream package, `sumy` - https://github.com/miso-belica/sumy/blob/main/sumy/nlp/tokenizers.py#L203
> 
> Replacing the previous load with PunktTokenizer() as in this commit [496515e](https://github.com/nltk/nltk/commit/496515efe45b5b708d15153983c7022cb1f32ac7) solved it for me.

This also worked for me thanks! I had to override some methods in the Tokenizer class of Sumy.

**Comment by tomteecezint** [comment]
> Ah, yes, sorry, this should have been a 3.9 beta. Happy to take down 3.8.2 and build 3.9b1 at the end of the week.

@stevenbird Could you decide as I don't know wether to deploy fixes now if it is gonna get rolled back!

**Comment by ekaf** [comment]
> is nltk.downloader updated to make use of the latest update?

@1mpale, the downloader handles the new packages as intended, if that was the sense of your question.

**Comment by ekaf** [comment]
@stevenbird, if I understand @robcaulk correctly, the forthcoming major would be a NLTK 4.0.0 series:

> If you are planning to make a breaking change, it should be done on the major, not the minor or the patch. https://semver.org/

**Comment by ekaf** [comment]
@gregd33 and @mbanon, these examples show [how to load the new format](https://github.com/nltk/nltk/pull/3283#issue-2398583029).

And here are [examples of calling the high-level functions](https://github.com/nltk/nltk/pull/3283#issuecomment-2264705572). They have not changed at all, so it would be easier to use those.

**Comment by ekaf** [comment]
> Wouldn’t it be easy enough to modify download() to simply catch punkt and replace the string with punkt_tab?
> 
> Can you help us to understand why this needed to be a breaking change instead?

Thanks @robcaulk, simply replacing the string would not be enough, because 6 different old packages contain pickles, which load different classes, and in the case of "punkt", can instantiate the class with many different languages. So I guess that is why it was not considered  at first.

However, your proposal seems feasible with a slightly more complex compatibility layer, and it might be preferable to a major version bump.

**Comment by stevenbird** [comment]
> > Ah, yes, sorry, this should have been a 3.9 beta. Happy to take down 3.8.2 and build 3.9b1 at the end of the week.
> 
> 
> 
> @stevenbird Could you decide as I don't know wether to deploy fixes now if it is gonna get rolled back!

Yes, I will, in 12 hours.

**Comment by ekaf** [comment]
> Ah, yes, sorry, this should have been a 3.9 beta. Happy to take down 3.8.2 and build 3.9b1 at the end of the week.
> 
> @stevenbird Could you decide as I don't know wether to deploy fixes now if it is gonna get rolled back!
> 
> Yes, I will, in 12 hours.

Meanwhile, I'm looking at how to avoid [avoid a major version bump](https://github.com/nltk/nltk/issues/3293#issuecomment-2287893184), so that 3.8.3 would be sufficient. I cannot do much about it today, but expect it to be feasible by tomorrow friday.

**Comment by hteeyeoh** [comment]
Using latest nltk version 3.9b1. It still bumped into issue and i was tried using punkt_tab.

**Comment by ekaf** [comment]
The only correct solution at this moment is to use NLTK 3.9.1. 

Projects that hardcode their NLTK dependency to version 3.8.1 are severely ill-advised, because they expose their users to the critical pickle vulnerability discussed at length in #3266. Please don't do that.

**Comment by user9747** [comment]
> is it even working on 3.8.2?
> 
> I've changed it to punkt_tab but still see this
> 
> ```
> Exception while executing function: Functions.create-case-embeddings Result: Failure
> Exception: LookupError: 
> **********************************************************************
>   Resource �[93mpunkt_tab�[0m not found.
>   Please use the NLTK Downloader to obtain the resource:
> 
>   �[31m>>> import nltk
>   >>> nltk.download('punkt_tab')
>   �[0m
>   For more information see: https://www.nltk.org/data.html
> 
>   Attempted to load �[93mtokenizers/punkt_tab/english/�[0m
> 
>   Searched in:
>     - '/home/nltk_data'
>     - '/usr/local/nltk_data'
>     - '/usr/local/share/nltk_data'
>     - '/usr/local/lib/nltk_data'
>     - '/usr/share/nltk_data'
>     - '/usr/local/share/nltk_data'
>     - '/usr/lib/nltk_data'
>     - '/usr/local/lib/nltk_data'
> ```
> 
> I am using it via docker. Anyone has an idea on how to specify the previous version there?
> 
> ```
> FROM --platform=linux/x86_64 public.ecr.aws/lambda/python:3.11
> 
> COPY requirements.txt ${LAMBDA_TASK_ROOT}
> 
> RUN pip install \
>     -r ${LAMBDA_TASK_ROOT}/requirements.txt -t ${LAMBDA_TASK_ROOT}
>     
> RUN python3 -m nltk.downloader averaged_perceptron_tagger -d ${LAMBDA_TASK_ROOT}/nltk_data && \
>     python3 -m nltk.downloader punkt_tab -d ${LAMBDA_TASK_ROOT}/nltk_data
> 
> COPY . ${LAMBDA_TASK_ROOT}
> 
> WORKDIR ${LAMBDA_TASK_ROOT}
> 
> CMD [ "main.lambda_handler" ]
> ```

Hi @1mpale we am also facing this same issue that too only on cloud run, where you able to get it working?
