### ISSUE TITLE
[BUG] punkt_tab downloading is taking a lot of time.

### ISSUE THREAD

**Issue by payaljain2003** [nltk/nltk#3297]
nltk.download('punkt_tab') is taking a lot of time, more than 2 minutes.

**Comment by kaiquevalentim** [comment]
Is it downloading for you? There is a bug with the newest version of nltk. I did a downgrade to version 3.8.1 and it solves.

**Comment by ekaf** [comment]
What bug, @kaiquevalentim? The NLTK version number should have no influence on the download speed. 
If you please [read this comment](https://github.com/nltk/nltk/issues/3293#issuecomment-2283807174), maybe you would refrain from spreading dubious info and toxic advice,

**Comment by kaiquevalentim** [comment]
So @ekaf, I'm a programmer who wants to help other people. If you felt offended by my comment, that's not my problem. I went over what I did to solve the problem and also asked if she was able to finish the nltk download, because I couldn't. So before you accuse people of being toxic, re-read your message and see who is really being toxic here

**Comment by ekaf** [comment]
Is punkt_tabstill taking long time to download? Is it only that package? Is it related to the NLTK version number?

**Comment by payaljain2003** [comment]
> Is it downloading for you? There is a bug with the newest version of nltk. I did a downgrade to version 3.8.1 and it solves.
@kaiquevalentim yes it was getting downloaded but it was taking a lot of time.. as on 13th Aug.. 
On Azure VM it was taking more than 2 minutes. and on my local it was taking close to 6 minutes..

**Comment by payaljain2003** [comment]
> Is punkt_tabstill taking long time to download? Is it only that package? Is it related to the NLTK version number?

@ekaf I haven't checked it again. I had to reduce the NLTK version to 3.8.1  from 3.8.2 and use punkt instead of punkt_tab for my release. I will check today and update here.

**Comment by ekaf** [comment]
Any update about this? 
I just downloaded _punkt_tab_, using the latest NLTK version 3.9.1, and did not notice any issue.

**Comment by payaljain2003** [comment]
> Any update about this? I just downloaded _punkt_tab_, using the latest NLTK version 3.9.1, and did not notice any issue.

@ekaf With nltk 3.9.1 the issue is gone.. its not slow anymore..  Thanks for the 3.9.1 version information.

**Comment by rathom10** [comment]
@payaljain2003 with nltk 3.9.1, are you using punkt or punkt_tab ?

**Comment by payaljain2003** [comment]
@rathom10 i am using punk_tab with nltk 3.9.1

**Comment by TJMarie** [comment]
<img width="735" height="415" alt="Image" src="https://github.com/user-attachments/assets/5aca9aaf-2ee1-4521-982e-bd07d4ce695e" />

I am running into the same issue, but I'm on version 3.9.1. I am running it in WSL Ubuntu, if that matters.
