### ISSUE TITLE
Performance regression of `word_tokenize` in NLTK 3.8.2

### ISSUE THREAD

**Issue by juhoinkinen** [nltk/nltk#3299]
NLTK 3.8.2 introduced a performance regression in `nltk.tokenize.word_tokenize()`.

Using this code (taken and modified from #3013) to measure the effect:
```python
n = 7
for length in [10**i for i in range(2, n)]:
    text = "a. " * length
    start_t = time.time()
    # nltk.tokenize.sent_tokenize(text)
    [nltk.tokenize.word_tokenize(word) for word in text.split()]
    print(f"A length of {length*3:<{n}} takes {time.time() - start_t:.2f} s")
```

**Output with NLTK 3.8.1**
```
A length of 300     takes 0.01 s
A length of 3000    takes 0.06 s
A length of 30000   takes 0.55 s
A length of 300000  takes 5.67 s
A length of 3000000 takes 58.67 s
```
**Output with NLTK 3.8.2**
```
A length of 300     takes 2.00 s
A length of 3000    takes 20.77 s
A length of 30000   takes 216.32 s
<Run interrupted at this point.>
```

I did `python3 -m nltk.downloader punkt` and `python3 -m nltk.downloader punkt_tab` for 3.8.1 and 3.8.2, respectively, before running the measurements: the output told that the packages were already up-to-date.

Note that at this time, in contrast to #3013, the performance of `sent_tokenize()` is not affected (or not more than very slightly, 15.29 s vs. 16.81 s for "A length of 3000000").

My system: Python 3.8.10 on Ubuntu 20.04.6 LTS.

**Comment by juhoinkinen** [comment]
Using this code for profiling 300 word tokenization calls:
```python
length = 300
text = "a. " * length
[nltk.tokenize.word_tokenize(word) for word in text.split()]
```

and runnig it with `python -m cProfile word_tokenize.py`

the output is 
```
         18718098 function calls (18711511 primitive calls) in 11.608 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    317/1    0.002    0.000   11.608   11.608 {built-in method builtins.exec}
        1    0.001    0.001   11.608   11.608 word_tokenize.py:1(<module>)
      300    0.169    0.001   11.338    0.038 __init__.py:114(word_tokenize)
      300    0.002    0.000   11.152    0.037 __init__.py:96(sent_tokenize)
      300    0.001    0.000   11.124    0.037 punkt.py:1742(__init__)
      300    0.004    0.000   11.121    0.037 punkt.py:1746(load_lang)
      300    0.008    0.000   11.087    0.037 punkt.py:1757(load_punkt_params)
      300    2.588    0.009   10.973    0.037 tabdata.py:105(tab2intdict)
      600    2.946    0.005    8.410    0.014 tabdata.py:49(tab2tups)
  6120900    2.672    0.000    4.307    0.000 tabdata.py:46(tab2tup)
  6121363    1.635    0.000    1.635    0.000 {method 'split' of 'str' objects}
  6179400    1.140    0.000    1.140    0.000 tabdata.py:10(rm_nl)
       31    0.003    0.000    0.660    0.021 __init__.py:1(<module>)
    382/2    0.002    0.000    0.270    0.135 <frozen importlib._bootstrap>:1349(_find_and_load)
    382/2    0.002    0.000    0.269    0.135 <frozen importlib._bootstrap>:1304(_find_and_load_unlocked)
```

So running the methods `tab2intdict`, `tab2tups` and `tab2tup` from [`tabdata.py`](https://github.com/nltk/nltk/blob/27e49f7b754c66e5583677a48a41b73b351a4fb1/nltk/tabdata.py#L38-L108) take over 2 seconds (tottime). 

Previously there was a method named [`tab2tups`](https://github.com/nltk/nltk/commit/496515efe45b5b708d15153983c7022cb1f32ac7#diff-4e9e96cccffd18678d3ceb3678dc88141348d6a96ccd29aa295af76326c245f3L1740-L1741) that used `removesuffix("\n")`, was that really so much faster than the new approach? Could that method be restored?

**Comment by antoniomika** [comment]
It actually has to do with the `PunktTokenizer` being instantiated for each request to `sent_tokenizer` (and subsequently `word_tokenizer`) here: https://github.com/nltk/nltk/blob/develop/nltk/tokenize/__init__.py#L106
```python
# Standard sentence tokenizer.
def sent_tokenize(text, language="english"):
    """
    Return a sentence-tokenized copy of *text*,
    using NLTK's recommended sentence tokenizer
    (currently :class:`.PunktSentenceTokenizer`
    for the specified language).

    :param text: text to split into sentences
    :param language: the model name in the Punkt corpus
    """
    tokenizer = PunktTokenizer(language)
    return tokenizer.tokenize(text)
```

Because the language is parameterized, we're better off preloading english, or caching the `PunktTokenizer` per language on first request. @stevenbird @ekaf any comments here? I'd be happy to contribute a fix.

**Comment by antoniomika** [comment]
I've gone ahead and added PR #3300 that includes a performance fix. Performance numbers are now better than 3.8.1

**Comment by juhoinkinen** [comment]
BTW, it could be be useful to have unit tests to detect this kind of performance issues, because they seem prone to occur, previously #3013 and #2869.

**Comment by ekaf** [comment]
Thanks a lot @juhoinkinen, your large-scale testing is very helpul.
I had to abandon _removesuffix()_ temporarily, because it is not defined in Python 3.8. But considering your performance figures, I will look at how to restore it, and provide a fallback for Python 3.8.

**Comment by ekaf** [comment]
> Previously there was a method named [tab2tups](https://github.com/nltk/nltk/commit/496515efe45b5b708d15153983c7022cb1f32ac7#diff-4e9e96cccffd18678d3ceb3678dc88141348d6a96ccd29aa295af76326c245f3L1740-L1741) that used removesuffix("\n"), was that really so much faster than the new approach? Could that method be restored?

@juhoinkinen, this is not completely clear, while I also suspect that _removesuffix_ is faster, the difference might not be so big. Did you try to time both approaches? 

According to @antoniomika:
> It actually has to do with the PunktTokenizer being instantiated for each request to sent_tokenizer (and subsequently word_tokenizer) here: https://github.com/nltk/nltk/blob/develop/nltk/tokenize/__init__.py#L106

And the performance of #3300 supports that viewpoint, so I wonder if it is worthwile do restore _removesuffix_ before Python 3.8 gets deprecated.

**Comment by juhoinkinen** [comment]
> > Previously there was a method named [tab2tups](https://github.com/nltk/nltk/commit/496515efe45b5b708d15153983c7022cb1f32ac7#diff-4e9e96cccffd18678d3ceb3678dc88141348d6a96ccd29aa295af76326c245f3L1740-L1741) that used removesuffix("\n"), was that really so much faster than the new approach? Could that method be restored?
> 
> @juhoinkinen, this is not completely clear, while I also suspect that _removesuffix_ is faster, the difference might not be so big. Did you try to time both approaches?
> 
> According to @antoniomika:
> 
> > It actually has to do with the PunktTokenizer being instantiated for each request to sent_tokenizer (and subsequently word_tokenizer) here: https://github.com/nltk/nltk/blob/develop/nltk/tokenize/__init__.py#L106
> 
> And the performance of #3300 supports that viewpoint, so I wonder if it is worthwile do restore _removesuffix_ before Python 3.8 gets deprecated.

Ah sorry @ekaf, `removesuffix` being faster was just a hunch, I did not measure using it or any modifications at all, just 3.8.1 and 3.8.2 releases. The changes in #3300 seem quite enough.
