### ISSUE TITLE
git branching model

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#330]
There is a proposal to adopt a more systematic approach to branches, e.g.

http://nvie.com/posts/a-successful-git-branching-model/
https://docs.google.com/file/d/0B5_-_q4j54cgYjVhYWZjN2UtOTQ4My00N2JjLTk2YWEtODljZWQyYTBkNDEx/edit?hl=en_US#

Please post feedback here.

**Comment by stevenbird** [comment]
I think that separate feature branches are too onerous, except for major extensions.

**Comment by xim** [comment]
The number of branches on the main repo should be kept minimal, I agree. For any individual developer, on their branch, feature branches can be used. (Encouraged, even, IMHO.)

**Comment by turicas** [comment]
I think the main repository should have only these branches:
- master (with only commits related to released software)
- develop (with only commits related to features that will be added in the next release)
- release/x branches (with commits that has bugfixes for released versions)

All feature branches and bugfixes should be in another fork (the fork should be in the account of who is working on this feature/bug). When a feature is finished (or the bug fixed), a pull request should be created in the main repository to merge this feature branch with the main `develop` branch or another (`release/2.1.0`, for example, if it's a bugfix for version 2.1.0). Before merging the pull request, a maintainer of the main repository should review the code and accept or reject it. All the discussion can be made in the pull request-related issue and comments can be made in each line of code.

It's a little compilation of [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) and [fork-pull model](https://help.github.com/articles/using-pull-requests).

**Comment by desilinguist** [comment]
I really like Álvaro's suggested setup below. 
- Nitin

**Comment by turicas** [comment]
Can we close this issue? Maybe before closing we can write down documentation about the branching model used on a `CONTRIBUTING.markdown` file.

**Comment by stevenbird** [comment]
Let's go ahead and adopt this model.

**Comment by stevenxxiu** [comment]
I like Álvaro's model too, gitflow is adopted by many projects.

**Comment by kmike** [comment]
What Álvaro proposes makes sense. Some points:
1. why is master/develop distinction needed? Isn't Álvaro's "master" already in one of release/x branches?
2. If one of NLTK contributors with committ access work on some feature, then I think he may create feature branch in main repo. This way other NLTK contributors with commit access can push commits to the same branch (e.g. to pick up the stalled development) without explicit permissions setup. It is possible to use pull requests between branches of the same repo. So feature branches in main repo can be useful sometimes.

**Comment by turicas** [comment]
@kmike, answers:
- On `master` we put only final releases (usually merge commits from `release/x`
- `release/x` branches are the branches you start off from develop to make commits that will make the next release
- I think the cases where more than one developer should have access to a feature branch on main repository are no the most common, so I prefer the fork + branch + pull request model (this model turns also explicit the fact that **another developer should review the code before it goes to `develop` branch**).

If we want to make these changes happen, we need to replace current `master` with `develop` in the main repository.

**Comment by kmike** [comment]
Why not leave current master as-is (it would be your proposed 'develop') and use tags for marking final releases?

**Comment by turicas** [comment]
@kmike, it's a good solution. @stevenbird, what do you think?

**Comment by stevenbird** [comment]
@turicas, this is what we do at present. Is there an advantage to having a `develop` branch which may have test failures, and a `master` branch which only has green code (no failures)? Or is there some other clear distinction between `develop` and `master` that is useful to have?

**Comment by kmike** [comment]
@stevenbird I think we agreed on a single `master` branch which should be green, feature branches that could be red, `release/x` branches for backporting fixes to older versions and tags for marking release commits.

**Comment by turicas** [comment]
I think everything on `develop` and `master` should always be green. I'm writing a "contributor's guide" to NLTK with more details about we're discussing and will create a pull request to fix this issue, ok?

**Comment by kmike** [comment]
wait, why are 2 branches needed? :)

**Comment by turicas** [comment]
@kmike, not for NLTK! ;) I was talking about the nvie's branching model... in our case, only `master` should be green, because there's no `develop` (but of course preferably every commit should not break any tests).

**Comment by stevenbird** [comment]
We are so close to the git flow model, why not adopt it fully (with the proviso that some feature branches could be done in forks). This means we would separate out the `develop` and `master` branches. We would not have to document the differences between our practice and git flow. We could use the available tool support, e.g. https://github.com/nvie/gitflow/blob/develop/README.mdown

**Comment by turicas** [comment]
@stevenbird, I also prefer to adopt it 100%, but I'll be ok if we don't. So, we need to decide to close this issue. :)

**Comment by stevenbird** [comment]
Some of the reviews of gitflow criticise the split between `develop` and `master` branches as being unnecessary, and talk about limited support for merging after forking. Has anyone experienced these issues?

**Comment by turicas** [comment]
I agree that splitting `develop` and `master` can be unnecessary, but I think it can be handy when creating hotfixes branches and other kind of. The `master` branch will be like a "line" of "stable commits" (as you can see in the graph at [nvie's gitflow](http://nvie.com/posts/a-successful-git-branching-model/)) and I like it.
About the limited support for merging and forking, I don't know about it. Can you explain more?

**Comment by ewan-klein** [comment]
This blog post seems relevant. It describes how to move from a model like our current one to a git flow approach:
http://blog.jessitron.com/2012/07/real-life-git-flow.html
Incidentally, is there any reason why forks should have a `develop` branch as well as feature branches?

**Comment by turicas** [comment]
@ewan-klein, the feature branches should exist on forks. Ideally, in the main repository (nltk/nltk) we should have only `master` (released software) and `develop` (commits merged from feature branches that will be in next release).

**Comment by ewan-klein** [comment]
@turicas: I don't see the git flow model dictating where release branches live. It looks to me as though having release branches in the main repo and allowing developers to push _minor_ bug fixes to them would work OK.

**Comment by stevenbird** [comment]
How about we try the git flow model for three months and then evaluate? Let's expect individuals to make mistakes occasionally, and not be too worried when that happens.

**Comment by turicas** [comment]
@ewan-klein, I prefer to work on local forks and only use main repository for accepting pull requests.

@stevenbird, +1

**Comment by ewan-klein** [comment]
Since we are on the topic of branches again, I suggest that Steven goes ahead with the creation of a `develop` branch in the main repo. My (partial) summary of the rest of the plan is as follows:

From now on, new feature branches should be pulled into `develop`, not `master`, and we leave the latter in limbo for the time being. As a transitional arrangement, minor fixes can be pushed directly to `develop`. Once the functionality required for NLTK 3 has been fixed, Steven should create a 3.0 release branch in the main repo, which will eventually be merged back into `master`. At that point, we should be more or less in conformity with the gitflow model.

**Comment by stevenbird** [comment]
Thanks. I've created a develop branch and set it to be the default on the github web page, and _deleted_ the master branch. (I'll recreate master once we do the NLTK 3.0b release.) This way, anyone who clones the repository will have develop as their default branch. I'll notify nltk-dev next.

**Comment by stevenbird** [comment]
We should keep an eye on our integration testing setup at https://jenkins.shiningpanda.com/nltk/

**Comment by heatherleaf** [comment]
I'm using SourceTree (http://www.sourcetreeapp.com) for my projects, and it has built-in support for gitflow. But I don't know how it works. Does anyone of you know how SourceTree's gitflow mode works, and if it's worthwhile to use it? Or should I just stick to the standard git mode?

**Comment by turicas** [comment]
Since it was discussed and defined, may we close this issue?

**Comment by stevenbird** [comment]
I have followed the gitflow process for the 3.0 release. NLTK-specific versions of the gitflow steps are listed in our RELEASE HOWTO at: https://github.com/nltk/nltk/blob/develop/RELEASE-HOWTO
