### ISSUE TITLE
`load_punkt_params()` loads `PunktParameters.collocations` as list instead of set

### ISSUE THREAD

**Issue by ryanamannion** [nltk/nltk#3310]
The type of `PunktParameters.collocations` as defined in [`PunktParameters.__init__`](https://github.com/nltk/nltk/blob/d0c0e51cc6f317a9daa69e40e2d104ded9ef5de0/nltk/tokenize/punkt.py#L342) should be a set of tuples, though new changes from https://github.com/ekaf/nltk/commit/496515efe45b5b708d15153983c7022cb1f32ac7 via https://github.com/nltk/nltk/pull/3283 change that type to a list. 

![image](https://github.com/user-attachments/assets/b6934ea7-99e1-4543-830e-c1c86c7168f0)
![image](https://github.com/user-attachments/assets/a09cffea-c449-4f17-8fd4-0d1231305b8b)

This doesn't appear to break anything in the nltk codebase that I can find, but it breaks something in my code and contradicts documentation

Is the best way to fix this to coerce the return value tab2tups into a set when setting `colloctions` in `load_punkt_params()`, or to have a new method in TabDecoder that returns a set of tuples? I am happy to put together a fix

**Comment by ekaf** [comment]
Thanks for catching this bug @ryanamannion! #3311 fixes it.
