### ISSUE TITLE
Lookup error issue in nltk even with new version 3.9.1, similar to PR #3308

### ISSUE THREAD

**Issue by kirupang-code** [nltk/nltk#3312]
I'm getting this error, which is similar to the error that caused this [PR](https://github.com/nltk/nltk/issues/3308) except it's with the resource `punkt_tab`. 

  ```
  raise LookupError(resource_not_found)
  LookupError:
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html
```

**Comment by ekaf** [comment]
@kirupang-code have you tried to download punkt_tab as suggested?

**Comment by shamoon** [comment]
So to be clear, this was an intentional breaking change that wasn't documented? This indeed broke our app https://github.com/paperless-ngx/paperless-ngx/issues/7519 so just trying to figure out if this will change again

**Comment by ekaf** [comment]
Nobody should depend on Nltk 3.8.1 because that exposes their users to potentially lethal "sleepy pickle" attacks.
Everybody needs to update their Nltk version to 3.9.1.

**Comment by stumpylog** [comment]
I would say the breaking change is that the code below doesn't work following a 3.8 to 3.9 update and requires changing what is pre-downloaded from `punkt` to `punkt_tab`:

```python
>>> from nltk.tokenize import word_tokenize
>>> s = '''Good muffins cost $3.88\nin New York.  Please buy me
... two of them.\n\nThanks.'''
>>> word_tokenize(s) 
```

The change from #3283 from to require `punkt_tab` instead of `punkt` is [not documented](https://github.com/nltk/nltk/blob/develop/ChangeLog).  I assume it is the line about pickled models, but there is no warning the data name required changed or migration steps.

**Comment by ekaf** [comment]
> raise LookupError(resource_not_found)
> LookupError:
> Resource punkt_tab not found.
> Please use the NLTK Downloader to obtain the resource:
> 
> >>> import nltk
> >>> nltk.download('punkt_tab')
> 
> For more information see: https://www.nltk.org/data.html

@kirupang-code, the message is clear: you need to  download _punkt_tab_:

```
import nltk
nltk.download('punkt_tab')
```

@stumpylog, more documentation could certainly be useful, and you are very welcome to contribute some.
