### ISSUE TITLE
NLTK Tokenizer not working in Latest Tag [ 3.9.1 ]

### ISSUE THREAD

**Issue by anuraged51a** [nltk/nltk#3314]
Hi, 

I have been using NLTK version 3.8.1 for some time without any issues. However, after recently updating to version 3.9.1, I encountered an error when using the word_tokenize function. I would appreciate any assistance in resolving this issue.

Here is the code snippet that is causing the issue:

`import nltk`
`nltk.download('punkt')`
`nltk.word_tokenize('over 25 years ago and 5^"w is her address')`

This is the error I which is shown on execution:

<img width="879" alt="image" src="https://github.com/user-attachments/assets/a06137f9-7997-4632-85ff-a03b65362878">

Thank you for your support.

**Comment by nsheils** [comment]
change to `nltk.download('punkt_tab')` see https://github.com/nltk/nltk/issues/3293
