### ISSUE TITLE
punkt model for Arabic needed

### ISSUE THREAD

**Issue by snoucair** [nltk/nltk#3316]
Is arabic model not supported any more?
the latest punkt packages do not include arabic.
Is there anyway to get arabic back?

**Comment by ekaf** [comment]
@snoucair , when did you see arabic in punkt? The previous package from 2020 did not include any arabic neither.

**Comment by ekaf** [comment]
This is could be a nice addition to the data package, but it doesn't require any modification in the Nltk libraries.
