### ISSUE TITLE
write good documentation for how to make new Punkt sentence tokenizers

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#332]
There have been a few threads already about how to train new sentence segmenters; we should probably have good documentation about it!

What's the right input format for training the segmenter? Is it one-sentence-per-line?

A helpful explanation of how to train a Punkt model is in this old thread from nltk-dev: https://groups.google.com/forum/?fromgroups=#!topic/nltk-dev/y2zYJSOdevQ

**Comment by alvations** [comment]
here's an example: https://github.com/alvations/DLTK/blob/master/dltk/tokenize/tokenizer.py but i agree with better documentation for it
