### ISSUE TITLE
Synsets method giving different results between nltk 3.8.1 and nltk 3.9

### ISSUE THREAD

**Issue by ruhayat** [nltk/nltk#3321]
Hello, 

I have an issue with the wordnet.synsets() method. For the same input word, it gives different results when using nltk 3.8.1 and when using nltk 3.9. 

You can find attached the screenshot. With the input word 'offerings', there are 17 synsets with nltk 3.8.1 and only 4 with nltk 3.9. It is like nltk 3.9 only outputs the nouns because the input word 'offerings' is a noun. 

How can I get please the exact same synsets between nltk 3.8.1 and nltk 3.9 ? 

Kind regards 

![issues_synsets_3_8_1_and_3_9](https://github.com/user-attachments/assets/b5a3f98c-e459-4890-8cfd-559b57d5304a)

**Comment by ekaf** [comment]
No, you can't get those errors anymore. _offerings_ can only be a noun, so now the verb synsets are discarded, as they should.
However, if you try with _offering_, the output correctly includes verbs.

**Comment by ekaf** [comment]
The reason for the change is #3225. Now the morphological processor _morphy_ only strips one suffix at each call. 

So it should be possible to emulate the old behaviour by calling morphy recursively and collecting the set union of the synsets for _offerings_, _offering_ and _offer_.
