### ISSUE TITLE
Inquiry about the commercial use of NLTK corpora.

### ISSUE THREAD

**Issue by windyowl** [nltk/nltk#3333]
I have a question regarding the license for NLTK corpora.

The NLTK README file contains the following statement: 
**Redistributing**
NLTK corpora are provided under the terms given in the README file for each corpus; **all are redistributable and available for non-commercial use.**

Should I determine whether commercial use is allowed by following the individual licenses of the NLTK corpora, or is it restricted to non-commercial use only?

**Comment by ekaf** [comment]
There are already several very old related issues,which are going nowhere, because nobody here seems to know. See for ex. #1756.

A clarification would be nice, but doesn't seem likely to happen. You might use your best judgment, and preferably consult a lawyer.
