### ISSUE TITLE
Missing procedure call in line 417

### ISSUE THREAD

**Issue by drewvid** [nltk/nltk#3334]
Line 417 of the file "nltk/app/wordnet_app.py" should look like this:

    elif synset.pos() == wn.ADJ or synset.pos() == wn.ADJ_SAT:

but instead looks like this:

    elif synset.pos() == wn.ADJ or synset.pos == wn.ADJ_SAT:

which will generate this error (complete with spelling mistake) :

    "Unhandles synset POS type: s"

**Comment by ekaf** [comment]
Thanks @drewvid, would you consider correcting both spelling errors in a PR?

**Comment by drewvid** [comment]
Sure
