### ISSUE TITLE
parsing ambiguous grammars

### ISSUE THREAD

**Issue by cafaro** [nltk/nltk#3339]
I am not sure if this is bug or not, perhaps I am not using NLTK as required.

Given the following ambiguous grammar 

Bool -> Bool 'and' Bool | Bool 'or' Bool | 'not' Bool | Term
Term -> 'true' | 'false'

in which Bool is the start symbol, nonterminals are Bool and Term and terminals are 'and', 'or', 'not', 'true' and 'false',

I wrote the following code to parse the sentence "true and true or false" which should produce two different syntactic parse trees that I am attaching as a picture file.

![parse-trees](https://github.com/user-attachments/assets/4dd55c81-0dd8-4953-9cfa-a85ee453c5de)

The code is as follows:

import nltk
from nltk.grammar import CFG

grammar = nltk.CFG.fromstring("""
Bool -> Bool 'and' Bool | Bool 'or' Bool | 'not' Bool | Term
Term -> 'true' | 'false'
""")

sent = ['true', 'and', 'true', 'or', 'false']
parser = nltk.ChartParser(grammar)
for tree in parser.parse(sent):
    print(tree.pretty_print())

However, running the code I get the following output:

   Bool           
  _______|__________    
 |      Bool        |  
 |    ___|____      |   
 |   |  Bool Bool  Bool
 |   |   |    |     |   
 |   |  Term Term  Term
 |   |   |    |     |   
 or and true true false

None
         Bool           
  ________|____          
 |   |        Bool      
 |   |     ____|_____    
 |  Bool  |   Bool  Bool
 |   |    |    |     |   
 |  Term  |   Term  Term
 |   |    |    |     |   
and true  or  true false

None

Of course, this is not the output I was expecting. 
Can you confirm that this is indeed a bug of NLTK or am I doing something wrong?

Thank you in advance.
With kind regards,

Massimo Cafaro
University of Salento, Italy

**Comment by ekaf** [comment]
I don't know why _tree.pretty_print()_ reorders the output, but you can avoid that by using _tree.pprint()_ instead.

**Comment by cafaro** [comment]
Thanks for the suggestion. However, tree.pretty_print() does exactly what print(tree) does. Which is not what I want. Surprisingly,  tree.pretty_print() works fine with the Groucho Marx grammar when parsing the sentence "I shot an elephant in my pajamas". But it fails miserably with all of the other examples I tried (besides the one reported here).

**Comment by ekaf** [comment]
Nobody is likely to fix the tree prettyprinter, since _pprint()_ works as intended.
