### ISSUE TITLE
nltk.corpus.reader.cmudict looks broken

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#334]
nltk.corpus.reader.cmudic has no tests; 'fileids' variable is undefined in CMUDictCorpusReader.raw (so this method is certainly broken)

**Comment by stevenbird** [comment]
Fixed in https://github.com/nltk/nltk/commit/69eaa14fd57907ff8f292c4c6a8098ebeb6e2789
(There are some tests in test/corpus.doctest.)
