### ISSUE TITLE
nltk.corpus.wordnet.morphy

### ISSUE THREAD

**Issue by DomoticaVirginia** [nltk/nltk#3341]
Good morning,
It seems to me that the method cited is wrong in some cases.

from nltk.corpus import words, wordnet
wordnet.morphy("numbers")
gives: 'numbers'

Thanks very much

**Comment by ekaf** [comment]
This limitation is well known: morphy() only returns one result, while wordnet._morphy('numbers', 'n') yields all results.

**Comment by DomoticaVirginia** [comment]
Thanks very much
