### ISSUE TITLE
childes.py (nltk3-alpha) & a patch for improvement

### ISSUE THREAD

**Issue by tnagano22** [nltk/nltk#347]
I tried some of the basic functions in the nltk3-alpha and it worked okay. Here is my environment.

Machine processor architecture: i386
Kernel system release         : Darwin Kernel Version 11.4.2
Mac OS system name            : Mac OS X
Mac OS system version         : 10.7.5
gcc version                   : i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 
Python version                : Python 3.3

I also tried using the CHILDESCorpusReader (I wrote the childes.py) and noticed that the corpus reader did not read the second part-of-speech tag in the CHILDES corpora. Here is the patch to fix it.
     https://dl.dropbox.com/u/9739273/childes_nltk3.patch

Tomonori

**Comment by stevenbird** [comment]
Adopted in https://github.com/nltk/nltk/commit/8ddd8a42c3f515c3fca27dc91ae9fe13f4e07521

**Comment by stevenbird** [comment]
@tomonori-nagano would you please take a look at this and submit a fix?
