### ISSUE TITLE
Maxent module broken

### ISSUE THREAD

**Issue by gawron** [nltk/nltk#349]
If you do 

> > > from nltk.classify import maxent
> > > maxent.demo()

You get an import error from scipy if you have scipy 0.12 installed .  scipy.maxentropy was deprecated in 0.11 and is gone in 0.12.  So maxent.py should no longer use 'cg' as the
default maxent learner algorithm if scipy is installed, as is done in THIS piece of code:

if algorithm is None:
            try:
                import scipy
                algorithm = 'cg'
            except ImportError:
                algorithm = 'iis'

**Comment by kmike** [comment]
This issue is already fixed in master: see https://github.com/nltk/nltk/issues/321, https://github.com/nltk/nltk/issues/307 and https://github.com/nltk/nltk/blob/master/nltk/classify/maxent.py#L278. Thanks for the report!
