### ISSUE TITLE
Python 3 compatibility issues to run `nltk.download()`

### ISSUE THREAD

**Issue by achimnol** [nltk/nltk#350]
I'm trying 3.0a0 release on Python 3.3 now, and found some fixes after first trial to `ntlk.download()`.
- internals.py:650 - wrong use of `__new__()` method: arguments are automatically passed to `__init__` function.

``` diff
-             return object.__new__(ElementWrapper, etree)
+             return object.__new__(ElementWrapper)
```
- downloader.py:259 - make Package class orderable to prevent error in L453 in the same file

``` diff
      def __repr__(self):
          return '<Package %s>' % self.id

+     def __lt__(self, other):
+         return self.name < other.name
```

After then, I could download all stuffs and execute another program using nltk. I ported it with 2to3.py and small amount of manual fixes.

**Comment by kmike** [comment]
Hi @achimnol, 

Package is already made orderable in master branch, and there are also some XML-related fixes for nltk.download in master. Could you please try nltk.download() using NLTK master? 

If you believe that your first proposed change is still needed, it will be helpful if you explain way - e.g. what errors does it fix?

**Comment by achimnol** [comment]
I'm using the zip file released at http://nltk.org/nltk3-alpha/ . I didn't notice that there were updates in other branches, sorry. I will try the master later.

The first change is required to remove "object.**new**() takes no parameter" error. I have tested if my change does not affect existing behaviour, by calling `ElementWrapper("<test/>")`. The instance had `_etree` property as expected.

**Comment by kmike** [comment]
This make sense. Thanks for the fix and a suggested test case! I believe the other issue should be already resolved so I'm closing this ticket.

**Comment by achimnol** [comment]
Thanks for your quick response! The rest of NLTK looks working fine so far. :)
