### ISSUE TITLE
BigramTagger interface inconsistent

### ISSUE THREAD

**Issue by yanlend** [nltk/nltk#355]
The **init**() method of the BigramTagger has the interface:
   def **init**(self, train, model=None, backoff=None, cutoff=0, verbose=False)

In contrast, other NgramTaggers have 
    def **init**(self, train=None, model=None, backoff=None, cutoff=0, verbose=False)
i.e. it is not necessary to provide an input to train. Of course, it is possible to just pass None to the function manually, but it should be a simple fix.

**Comment by stevenbird** [comment]
Fixed in https://github.com/nltk/nltk/commit/0e4a5f992dbae0627851b30841b554fec3cc25b1
