### ISSUE TITLE
Support Open section of American National Corpus

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#36]
Write a corpus reader to access the content of the OANC:
http://www.anc.org/OANC/OANC-1.0.1-UTF8.zip
It would be good to avoid creating our own distribution of the data.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=137</p><hr/><h2>earlier comments</h2>
<p><strong>edloper said, at 2009-02-08T04:27:30.000Z:</strong></p>

<p>Mostly done with this; will try to get it checked in tomorrow.

</p><p><strong>StevenBird1 said, at 2009-02-21T01:44:59.000Z:</strong></p>

<p>Carried forward to 0.9.9
</p><p><strong>tomonori.nagano said, at 2011-01-27T14:13:29.000Z:</strong></p>

<p>Is it already done? I needed to use OANC and wrote a simple CorpusReader.
     http://language.dyndns.org/research/ANC/

ANC has a tool (ANCTools) that "supports" the NLTK format, but the data keep only POS information after transformation. The better implementation is that NLTK reads their (combined) XML format that has many other information such as utterances, NP/VP chunks, domain etc.</p>

**Comment by alexrudnick** [comment]
Did this ever happen? edloper doesn't seem to be on github; how can we ping him about this? ...

**Comment by stevenbird** [comment]
I recently added OANC data to nltk_data, and we are still waiting for the promised corpus reader:
https://github.com/nltk/nltk_data/commit/1e88413d3a9e234b39ecd8180007c6b0c7309b7d
https://groups.google.com/forum/#!msg/nltk-dev/7PVH4ny9LHc/Xtsj1ZJuW4oJ

**Comment by alvations** [comment]
`nltk.corpus.masc_tagged` is available now. 

**Is the `oanc` in this issue referring to `masc`?** If not, which zip file is OANC residing in the `nltk_data` directory?
