### ISSUE TITLE
Can´t import dispersion_plot in Python 3.2

### ISSUE THREAD

**Issue by sonofmun** [nltk/nltk#366]
When I try 

```
from nltk.draw import dispersion_plot
```

I get:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name dispersion_plot
```

I am using NLTK 3.0a1 with Python 3.2

**Comment by kmike** [comment]
Could you try this with the latest NLTK version from github?

**Comment by sonofmun** [comment]
Sorry but I am a noob with Github.  How do I get to the latest NLTK version on Github?

**Comment by stevenbird** [comment]
The problem exists there too. nltk.draw needs the same treatment that we gave to nltk.app.

**Comment by sonofmun** [comment]
I imported the most recent version and it works now.  Thanks kmike.

**Comment by stevenbird** [comment]
I see, the use of nltk.compat in nltk/draw/**init**.py does the trick.

**Comment by lakinducker** [comment]
I am having a similar problem with Python 3.4.0 on Ubuntu 14.04 LTS (trusty). I am using NLTK version 3.0.0b2. Every time I try "from nltk.draw import dispersion_plot", I get "ImportError: cannot import name 'dispersion_plot'". Do you have any ideas how I can fix this?
