### ISSUE TITLE
ImportError: cannot import name MaxentClassifier

### ISSUE THREAD

**Issue by meunierd** [nltk/nltk#368]
When running

```
>>> nltk.ne_chunker("This is a sentence about A Bug.")
```

**Comment by codeb2cc** [comment]
Are you using the latest source checkout from github? The old MaxentClassifier used a deprecated function in Scipy.

**Comment by opyate** [comment]
I use Python 2.7.3, and get the same error, then tried your suggestion of installing nltk from source (at 3f0c8c97a0e9784086963a94670347d22d6b001a), but now  I get a new error:

```
>>> entities = nltk.chunk.ne_chunk(tagged)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nltk/chunk/__init__.py", line 176, in ne_chunk
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 605, in load
ImportError: No module named named_entity
```

**Comment by opyate** [comment]
Actually, I tried to start over.
I restarted the Python interpreter after installing nltk from source (after removing the previous one I installed with pip), and:

```
>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk.py", line 4, in <module>
    tokens = nltk.word_tokenize(sentence)
AttributeError: 'module' object has no attribute 'word_tokenize'
```

**Comment by opyate** [comment]
I do apologise: I had a scratch file called `nltk.py` in my current directory, and this seemed to confuse the import. It all works now, thank you.

**Comment by niccokunzmann** [comment]
This question refers to that error:

http://stackoverflow.com/questions/15320894/python-importerror-maxentclassifier/15321784#15321784

It would be good to know that numpy should be installed in some cases.

I do not know of wether you resolved it. Just for information.

**Comment by kmike** [comment]
It is the pattern of conditional imports (based e.g. on numpy or svmlight presence) that causes troubles. Since  `nltk.classify.maxent`, `nltk.classify.svm` and `nltk.classify.scikitlearn`  are all now importable without dependencies installed, we should probably just make imports unconditional.

**Comment by stevenbird** [comment]
So if I understand correctly, we now only fail at runtime (not load time) when dependencies are not installed.
