### ISSUE TITLE
Remove HiddenMarkovModelTaggerTransformI and its subclasses

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#374]
I think HiddenMarkovModelTaggerTransformI, HiddenMarkovModelTaggerTransform, LambdaTransform and IdentityTransform are examples of over-engineering, and we should use simple callables instead. Callables:
- are equally powerful;
- are already supported by HiddenMarkovModelTagger.

Dropping HiddenMarkovModelTaggerTransform would allow to remove 50+ lines of code from NLTK (they arguably does nothing). Existing (user) custom HiddenMarkovModelTaggerTransform subclasses can be easily converted to callable just by renaming 'transform' method to `__call__`.

**Comment by stevenbird** [comment]
+1
