### ISSUE TITLE
Better visualization of dependency trees

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#38]
At the moment, we ignore the arc labels on dependency graphs.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=141</p><hr/><h2>earlier comments</h2>
<p><strong>ewan.klein said, at 2009-01-15T20:51:03.000Z:</strong></p>
<p>The only graphical representation of dependency trees that we can automatically
generate is a tree representation, using words rather than grammatical categories as
nodes. However, this doesn't allow arc labels (e.g. modifier, subject-of) to be
represented, which is an important omission. </p><p><strong>StevenBird1 said, at 2009-01-15T21:19:44.000Z:</strong></p>
<p>N.B. nltk_contrib.fst

</p><p><strong>StevenBird1 said, at 2009-02-21T01:44:59.000Z:</strong></p>
<p>Carried forward to 0.9.9
</p>

**Comment by stevenbird** [comment]
Superseded by #816
