### ISSUE TITLE
Remove nltk.probability.GoodTuringProbDist

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#381]
What do you think about removing nltk.probability.GoodTuringProbDist? I'm asking because: 

a) GoodTuring is not useful in practice (especially for high-frequency symbols where Nr(count+1) is often zero and thus probability is zero);
b) if it is for educational purposes, than arguably implementing it by yourself provides more educational value;
c) nltk.probability.GoodTuringProbDist looks broken: e.g. GoodTuringProbDist.prob() method contain a branch for unseen samples that does nothing (it just computes p0 variable which is not used later).

Another way is to fix (a) by mentioning Good-Turing issues in docstring and to fix (c) by fixing GoodTuringProbDist.prob() and adding some tests, but I think it is better to just remove GoodTuringProbDist - it is much easier and it would fix (a), (b) and (c).

**Comment by kmike** [comment]
GoodTuringProbDist could be useful for FreqDist subclasses that implement smoothed Nr() method, but this is not obvious and there is no such FreqDist subclass in NLTK.

**Comment by heatherleaf** [comment]
+1

Since we do have SimpleGoodTuringProbDist, which works, I don't think there's a need to keep this one.  There's already a good explanation in the comments, and we could simply move the class docstring for GoodTuring into the comments (e.g., efter the fist paragraph, on line 1294.

**Comment by stevenbird** [comment]
+1

**Comment by afourney** [comment]
+1

**Comment by kmike** [comment]
Thanks for your support :)
