### ISSUE TITLE
Default value for 'bins' argument in SimpleGoodTuringProbDist and WittenBellProbDist

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#383]
I think the default value for SimpleGoodTuringProbDist.bins is quite unuseful: freqdist.B() + 1 means that probability for unseen samples could be very large (up to several orders of magnitude larger than probability of the most common sample). This caused low performance of SimpleGoodTuringProbDist in NLTK tests: see  https://github.com/kmike/nltk/commit/8d20dc86d8180e61a83e5dc2deeb5b5f30e6071f

WittenBellProbDist also has a non-useful default 'bins' value (see https://github.com/nltk/nltk/issues/110).

Maybe there is a better estimate (e.g. could we somehow take Zipf law into account)?

**Comment by kmike** [comment]
Let bins == fd.B()+1.

Then prob() method would return p = _prob_measure(0) / (1.0 \* self._bins - self._freqdist.B()) == _prob_measure(0), where _prob_measure(0) is 1.0 \* self._freqdist.Nr(1) / self._freqdist.N() - a ratio of samples with frequency 1.

A reasonable guess for self._freqdist.Nr(1) / self._freqdist.N() is 0.05. 

What does it mean: each unseen token gets 0.05 probability; this number is huge - frequent words usually have much lower probability.

**Comment by desilinguist** [comment]
The value of the number of bins was from the original SGT C code reference
implementations. See the issue on google code for more detail.

It may give too high a probability mass to unseen tokens - that's why it's
called SimpleGoodTuring.

On Monday, April 8, 2013, Mikhail Korobov wrote:

> Let bins == fd.B()+1.
> 
> Then prob() method would return p = _prob_measure(0) / (1.0 \* self._bins -
> self._freqdist.B()) == _prob_measure(0), where _prob_measure(0) is 1.0 *
> self._freqdist.Nr(1) / self._freqdist.N() - a ratio of samples with
> frequency 1.
> 
> A reasonable guess for self._freqdist.Nr(1) / self._freqdist.N() is 0.05.
> 
> What does it mean: each unseen token gets 0.05 probability; this number is
> huge - frequent words usually have much lower probability.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/383#issuecomment-16073707
> .

## 

Linguist, Desi Linguist
http://www.desilinguist.org

**Comment by afourney** [comment]
Right. 

Can we extrapolate Nr(0) from the curve that is fit for Simple Good Turing?

This would give the number of species with count 0. In this case, set bins to freqdist.B() + Nr(0)

I'm just guessing here...

**Comment by kmike** [comment]
This extrapolation would result in +inf for Nr(0).

**Comment by afourney** [comment]
Right. That makes sense...

**Comment by kmike** [comment]
I think that this should hold: p(unseen) <= p(seen_once). Another way to say it:

```
p(unseen) = k*p(seen_once), k <= 1
```

Let's solve it for bins.

```
p(unseen) = _prob_measure(0) / (bins-B) = Nr(1) / (N * (bins-B))
p(seen_once) = _prob_measure(1)*renormal

bins = Nr(1) / (N*k*_prob_measure(1)*renormal) + B
_prob_measure(1) = 2*Nr(2)/(Nr(1)*N)

bins = Nr(1)^2 / (2*k*renormal*Nr(2)) + B
```

As far as I can tell, "renormal" doesn't depend on "bins", so the formula above should be OK. 

I checked it manually and it seems that my calculations are correct: for k=1 SimpleGoodTuringProbDist.prob() returned almost the same values for one of hapaxes and for a unseen word (they were not the same because I cast "bins" to an integer), for k=0.5 p(unseen) resulted in p(hapax)*0.5.

What do you think about setting bins to  `Nr(1)^2 / (2*k*renormal*Nr(2)) + B` by default (or maybe  `Nr(1)^2 / (2*k*renormal*Nr(2)) + B + 1` to make it more robust)?

**Comment by kmike** [comment]
@desilinguist SGT may give too high a probability mass to unseen tokens, but it shouldn't assign high probabilities for unseen tokens.

**Comment by afourney** [comment]
That seems reasonable, but setting k=0.5 appears arbitrary (are unseen ngrams really half as likely as ngrams seen once?) 

k = 1.0 is more conservative, as it suggests that the set of singleton ngrams were decided by a coin toss. Though I suppose this is just as arbitrary.

Whatever is decided, I suggest noting in the documentation that one should set nbins = B() + 1 to reproduce the results from the SGT C Code reference implementation -- but note that this is a terrible choice.

**Comment by kmike** [comment]
You're right - any k value appears arbitrary (1 and 0.5 were just examples, I didn't propose any value in `Nr(1)^2 / (2*k*renormal*Nr(2)) + B + 1` formula - "2" is a part of formula). We could just choose some default value (maybe something like 0.9?) and provide "k" as a constructor argument (as an alternative to 'bins' - raise an exception if both are passed).

**Comment by afourney** [comment]
The other option would be to learn k from the training data by withholding say half the data for testing. Once k is learned, I see no reason why we cannot use freqdist as usual... (Ie, including the withheld data)

**Comment by kmike** [comment]
That's an interesting idea. Do you have an exact learning algorithm in mind?

**Comment by afourney** [comment]
I realize now that what I was proposing probably won't work, and at best would just give a lower bound for k. It may not be worth the trouble.

Basically, I was thinking that you would learn a model on half the data, then predict the vocabulary size as above, parameterized by k. Process the remaining half of the data and see how much the vocabulary expanded by. Then solve for k.

ie:

Let  EBins(k; data) = Nr(1)^2 / (2_k_renormal*Nr(2)) + B
be the our estimate of the number of bins (i.e., vocab size)

So we set,

EBins(k; fist half of data) >= B(all data)

Solve for k.

Yeah, the notation is brutal.

The first problem is that, even after processing 2x more data, there will still be unseen ngrams. As such, solving with strict equality would underestimate the number of missing values (Hence the inequality above).

On the other hand, we would expect the rate or % of missing ngrams to drop if the training size is increased. As such, the k we learned from the first half of the training data may over estimate the number of missing ngrams when applied to 2x more training data.

So, maybe this idea should be shelved.

**Comment by kmike** [comment]
I played with a formula a bit, and discovered that:

a) it is only valid when Nr(1) and Nr(2) are not smoothed - it is better not to expand `self._probability_measure(0)` and `self._probability_measure(1)`;

b) 'k' acts badly when SimpleGoodTuringProbDist is passed to  ConditionProbDist as an estimator, because `_bins` becomes different for each SimpleGoodTuringProbDist from ConditionProbDist, and each `SimpleGoodTuringProbDist._bins` value is estimated on a partial FreqDist - this leads to very poor results; in estimators it is better to set 'bins' explicitly.

**Comment by afourney** [comment]
Ah yes. (b) makes a lot of sense. I recently had a similar problem in an unrelated experiment where I was using LidstoneProbDist in a ConditionProbDist and altered the gamma parameter in a similar way.

In that case, I think the only sane thing to do is to place a strong warning in the documentation, or even make bins a required parameter (since no reasonable bins value can be selected automatically)

**Comment by kmike** [comment]
So we have 2 cases:
- SimpleGoodTuringProbDist is used on its own - k=1.0 estimate is quite good (at least it is much better than fd.B()+1);
- SimpleGoodTuringProbDist is used with ConditionProbDist - estimate for bins for k=1.0 is still good, but only if it is computed on a full FreqDist. SimpleGoodTuringProbDist.**init** doesn't have access to full freqdist in this case - this means we should compute a single 'bins' value outside the constructor (e.g. in a class method).

What do you think about the following?

```
# k is optional; it is 1.0 by default
bins = SimpleGoodTuringProbDist.suggest_bins(freqdist, k=0.7) 

# we could make 'bins' required because freqdist.B() + 1 is a very poor estimate;
# I can't think of a case where freqdist.B() + 1 would be OK
sgt = SimpleGoodTuringProbDist(freqdist, bins=bins) 
```

**Comment by kmike** [comment]
Hmm, and now I'm not sure if estimate based on full FreqDist is good for ConditionalProbDist..

**Comment by afourney** [comment]
What's the problem with using the full frequency distribution? Is performance bad?

In any case, this whole issue is currently the status quo, as using SGT in a Conditional distribution will also use a different B() + 1 for each condition... This may be an additional contributor to the poor performance people are seeing.

**Comment by kmike** [comment]
It is late night here and my thinking is not clear now :) I realized that I don't understand how full frequency distribution relates to conditional frequency distribution (that could be totally different) and why it could be a good idea to use estimates drawn from the full distribution for condition distributions.
