### ISSUE TITLE
Cannot unpickle HiddenMarkovModelTagger object

### ISSUE THREAD

**Issue by tyleha** [nltk/nltk#387]
#### Issue

Cannot unpickle a HiddenMarkovModelTagger object, instead get this error raised:

```
C:\Python27\lib\site-packages\nltk-3.0a1-py2.7.egg\nltk\probability.pyc in __init__(self, probdist_dict)
   2171         """
   2172         defaultdict.__init__(self, DictionaryProbDist)
-> 2173         self.update(probdist_dict)
   2174 
   2175 ##//////////////////////////////////////////////////////

TypeError: 'type' object is not iterable
```

If debug inspect the error, probdist_dict contains no keys or values, though honestly I'm not sure if that is the problem or not, but that does seem to be consistent with the `TypeError`
#### Reproduce

``` python
import nltk
import pickle

s = """Your humble writer knows a little bit about a lot of things, but despite writing a fair amount about text processing (a book, for example), linguistic processing is a relatively novel area for me. Forgive me if I stumble through my explanations of the quite remarkable Natural Language Toolkit (NLTK), a wonderful tool for teaching, and working in, computational linguistics using Python. Computational linguistics, moreover, is closely related to the fields of artificial intelligence, language/speech recognition, translation, and grammar checking."""
sentences = s.split('.')[:-1]
seq = [map(lambda x:(x,''), ss.split(' ')) for ss in sentences]
symbols = list(set([ss[0] for sss in seq for ss in sss]))

trainer = nltk.tag.hmm.HiddenMarkovModelTrainer(states=range(5), 
                                           symbols=symbols)
m = trainer.train_unsupervised(seq, max_iterations=5)

s = open('pickle_obj', 'w')
s.write(pickle.dumps(m)) # does not matter if I use dump or dumps
s.close()

o = open('pickle_obj', 'r')
pobj = pickle.loads(o.read()) # where the error will occur
o.close()

print 'Success!'
```
#### Chat

I first encountered this problem trying to parallelize nltk hmm training with IPython's parallel package. However, since IPython uses pickle to serialize objects between kernels/instances, it crashes and raises the same traceback as the above code after finishing training and attempting to return the Trainer object. Interestingly, I could pickle HiddenMarkovModelTagger objects back in nltk v.2.0.4, if that is helpful.

In all honesty, I have very little idea of what could be causing this issue, and hoping @kmike or somebody might swoop in and save the day. Perhaps probdist_dict is not getting pickled along with the rest of the object? Shots in the dark.

**Comment by kmike** [comment]
Hi @tylerhartley,

You're right - it is DictionaryConditionalProbDist who doesn't support pickling; that's because it is inherited from defaultdict and defaultdict defines its own pickling method that is incompatible with DictionaryConditionalProbDist constructor. I fixed this; could you please check if it fixes your issue?

Just curious, how are you parallelizing training?

**Comment by tyleha** [comment]
Well done @kmike! Both pickling and IPython's use of pickle work great now. That was one of those bugs that would have taken me 6 hours to figure out, but someone with a knowledge of the issue can do it with ease.

As for parallelization, I'm using IPython's great [parallel computing package](http://ipython.org/ipython-doc/dev/parallel/index.html). All I'm doing is training many independent HMMs in parallel to later evaluate which one best fits my training corpus. This especially useful for unsupervised BW training, where the discrimination of a given model can greatly vary depending on initial prob distributions, so getting a dozen models in the time it takes to train a single one makes development much faster. IPython, along with the [starcluster](http://star.mit.edu/cluster/) module, even lets you parallelize using amazon ec2 instances when I want more than the 8 kernels my cpu can offer. 

Since I'm focused on getting many models trained quickly, I haven't yet bothered trying to scatter and parallelize a single `train_unsupervised` run (which is what I assume you're interested in). It would be simple to parallelize each `_baum_welch_step` for each `sequence in unlabeled_sequences` across a bunch of kernels...IPython supports quick and dirty [for loop scattering and load balancing](http://ipython.org/ipython-doc/dev/parallel/parallel_task.html)...but I'm not sure how much wall time that would actually save you given the computational cost of moving the sequences between kernels. You could also [break up element-wise computations and parallelize them](http://ipython.org/ipython-doc/dev/parallel/parallel_multiengine.html#remote-function-decorators), if there are any expensive matrix operations being done...hmm...

Sorry, got a little carried away there. Thanks again! Without pickle my whole workflow was busted.

**Comment by kmike** [comment]
Your guess was correct:) I tried to parallelize Baum-Welch by splitting sequence processing into a bunch of processes and then combining the results (it was sklearn.hmm, using concurrent.futures), but the IPC overhead was too big as you said. In my experiment sequences were split between processes in a very suboptimal way though (there was a process pool of fixed size and sentences were sent to the pool one by one).

**Comment by tyleha** [comment]
Yes, I imagine there's minimal acceleration to be gained by parallelizing a single `train_unsupervised` run...but, on the plus side, your move to BW matrix-based operations sped up training incredibly! Now NLTK training is on the same order as Matlab :-D
