### ISSUE TITLE
WordNet: Lowest Common Hypernym

### ISSUE THREAD

**Issue by dabril** [nltk/nltk#395]
I have seen a strange behavior when using the function to find the lowest common hypernym between two synsets. 
For instance, Synset('policeman.n.01') and Synset('firefighter.n.01')
## Example
- wn.synset('policeman.n.01').definition
  - 'a member of a police force'
- wn.synset('chef.n.01').definition
  - 'a professional cook'
- If we compute the lowest common hypernym we get the following synset _wn.synset('policeman.n.01').lowest_common_hypernyms(wn.synset('chef.n.01'))_
  - **[Synset('organism.n.01')]**

However, if we look at the hypernym paths
- _wn.synset('policeman.n.01').hypernym_paths()_
  1. [Synset('entity.n.01'), Synset('physical_entity.n.01'), Synset('object.n.01'), Synset('whole.n.02'), Synset('living_thing.n.01'), Synset('organism.n.01'), _**Synset('person.n.01')**, Synset('preserver.n.03'), Synset('defender.n.01'), Synset('lawman.n.01'), Synset('policeman.n.01')_],
  2. [Synset('entity.n.01'), Synset('physical_entity.n.01'), Synset('causal_agent.n.01'), _**Synset('person.n.01')**, Synset('preserver.n.03'), Synset('defender.n.01'), Synset('lawman.n.01'), Synset('policeman.n.01')_]
- _wn.synset('firemann.04').hypernym_paths()_
  1. [Synset('entity.n.01'), Synset('physical_entity.n.01'), Synset('object.n.01'), Synset('whole.n.02'), Synset('living_thing.n.01'), Synset('organism.n.01'), _**Synset('person.n.01')**, Synset('worker.n.01'), Synset('skilled_worker.n.01'), Synset('cook.n.01'), Synset('chef.n.01')_],
  2. [Synset('entity.n.01'), Synset('physical_entity.n.01'), Synset('causal_agent.n.01'), _**Synset('person.n.01')**, Synset('worker.n.01'), Synset('skilled_worker.n.01'), Synset('cook.n.01'), Synset('chef.n.01')_]

As can be seen in all the hypernym paths the lowest common ancestor should be Synset('person.n.01') instead of Synset('organism.n.01'), which is the immediately ancestor of one of the paths of the Synset('person.n.01').

If I understood well, this is because the code (http://nltk.org/_modules/nltk/corpus/reader/wordnet.html) first compute the minimum depth of all the paths for each common synset and then choose the maximum depth among them.

``` python
synsets = set(s for synsets in self_hypernyms for s in synsets)
others = set(s for synsets in other_hypernyms for s in synsets)
synsets.intersection_update(others)

try:
    max_depth = max(s.min_depth() for s in synsets)
    return [s for s in synsets if s.min_depth() == max_depth]
```

For the Synset('person.n.01') the minimum path is 
`[Synset('entity.n.01'), Synset('physical_entity.n.01'), 
Synset('causal_agent.n.01'), Synset('person.n.01')]` (the other path is ignored because is bigger than that)
and the minimum path for the Synset('organism.n.01') is 
[Synset('entity.n.01'), Synset('physical_entity.n.01'), Synset('object.n.01'), Synset('whole.n.02'), Synset('living_thing.n.01'), Synset('organism.n.01')]. 
Therefore, the algorithm select the Synset('organism.n.01') becauses is bigger than the 'person' path. However, from my point of view this is wrong, because the following synset of the Synset('organism.n.01') is the Synset('person.n.01')....

---
# Python version: **Python 2.7.3**
# WordNet version: **WordNet-InfoContent-3.0**

**Comment by dougalg** [comment]
I agree that it makes more sense to be comparing the `hypernym_paths()` rather than the `min_depth()` for the synsets. I suppose it could get the lowest hypernyms for each possible path intersection.

This would be a major change of behaviour, though, right?

**Comment by kmike** [comment]
@dabril @dougalg is this issue resolved?

**Comment by dougalg** [comment]
Yes this issue appears to be resolved in the current version (tested on Windows, python3 and python27).

**Comment by kmike** [comment]
Thanks!
