### ISSUE TITLE
make some good doctests for nltk.model.NgramModel 

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#396]
I don't think there are any tests for NgramModel at all right now...

But there should be some.

Tests should include the obvious things like creating a model, using some different estimators, sampling from it. And also pickling and loading from a pickle.

**Comment by kmike** [comment]
There is a simple test in `NgramModel.__init__` docstring (it could be executed using runtests.py script), but it only checks that there are no syntax errors and that entropy calculation works; +1 for proper NgramModel tests (esp. given all recently opened NgramModel tickets).

**Comment by iliakur** [comment]
@stevenbird this can also be closed while we're at it!
