### ISSUE TITLE
Add tracing to dependency parsers

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#40]
It would be helpful, and conformant with other NLTK parsers, to add a
tracing facility to the projective and non-projective dependency parsers.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=148</p>

**Comment by alvations** [comment]
@ewan-klein is this issue still valid given the latest code?:
- https://github.com/nltk/nltk/blob/develop/nltk/parse/dependencygraph.py
- https://github.com/nltk/nltk/blob/develop/nltk/parse/nonprojectivedependencyparser.py
- https://github.com/nltk/nltk/blob/develop/nltk/parse/projectivedependencyparser.py
