### ISSUE TITLE
word_tokenizer separates contractions (we'll, I'll) into different words

### ISSUE THREAD

**Issue by liquidscorpio** [nltk/nltk#401]
``` python
from nltk.tokenize import *
sent = "We'll go home tomorrow"
word_tokenize(sent)
['We', "'ll", 'go', 'home', 'tomorrow']
```

Though I am no expert in English/Linguistics, I think the output should have been:

``` python
["We'll", 'go', 'home', 'tomorrow']
```

**Comment by dan-blanchard** [comment]
That is the correct/expected output. For word tokenization contractions are considered two words because meaning-wise they are.

**Comment by kmike** [comment]
I agree with Dan. Obviously for this approach to work further processing units (e.g. a POS tagger) should be aware of such tokens. But it is much easier than processing tokens like `we'll`.

**Comment by liquidscorpio** [comment]
But what when I am indexing the words, I'd much rather have we'll as a single word than 'we' and 'll.

**Comment by kmike** [comment]
There is no universal best tokenizer. If you task requires different tokenization rules then don't use nltk.word_tokenize. In fact, there are tokenizers in NLTK other than nltk.word_tokenize, and NLTK provides helper classes for writing your own tokenizers (or you could just write a regexp). See http://nltk.org/book/ch03.html#sec-tokenization for more information. This link could also be relevant: http://metaoptimize.com/qa/questions/1957/best-word-tokenizer-for-nlp

**Comment by liquidscorpio** [comment]
Thanks! Will go through them and see how can I help myself.
