### ISSUE TITLE
Problem with repeated words and BigramCollocationFinder.from_words()

### ISSUE THREAD

**Issue by rmalouf** [nltk/nltk#403]
BigramCollocationFinder.from_words() in collocations.py does strange things with duplicate words:

```
>>> b = nltk.collocations.BigramCollocationFinder.from_words('this this is is a a test test'.split())
>>> b.ngram_fd.keys()
[('a', 'test'), ('is', 'a'), ('this', 'is')]
>>> b.word_fd.items()
[('a', 2), ('is', 2), ('test', 2), ('this', 2)]
```

and

```
>>> b = nltk.collocations.BigramCollocationFinder.from_words('xx this xx is xx a xx test xx'.split(),4)
>>> b.ngram_fd.items()
[(('a', 'test'), 1), (('a', 'xx'), 1), (('is', 'a'), 1), (('is', 'xx'), 1), (('test', 'xx'), 1), (('this', 'is'), 1), (('this', 'xx'), 1), (('xx', 'a'), 1), (('xx', 'is'), 1), (('xx', 'test'), 1), (('xx', 'this'), 1)]
```

By my count, `('xx','is')` occurs 2 times (not 1) and `('xx','xx')` occurs 4 times (not 0).

The culprit seems to be this bit of code here, which truncates an ngram at the point where a duplicate word occurs:

``` python
            try:
                window = window[:list(window).index(w1, 1)]
            except ValueError:
                pass
```

I see from the history that @jnothman added this... what was the thinking here? Is there something subtle I'm missing?

**Comment by kmike** [comment]
This is the original ticket: https://code.google.com/p/nltk/issues/detail?id=603

**Comment by jnothman** [comment]
Thanks for pulling that out, @kmike. I can't say I would have recalled it... and I agree it's some difficult-to-read code and some worrying behaviour.

It's important that it gets the expected frequencies in the usual no-skip (`window_size == n`) case, and i guess that means fixing duplicate words in that case (important for reduplicating morphology). But it's also essential that we don't get bogus frequencies, as it used to.

I think we need a better approach.

So, let's do this the right way: write tests. What do we expect the correct counts to be for `window_size` from 2 to 8 with `'this this is is a a test test'.split()`?

**Comment by rmalouf** [comment]
Great idea!

For `window_size=2`, it's pretty easy, I think:

```
>>> sent = 'this this is is a a test test'.split()
>>> b = BigramCollocationFinder.from_words(sent)
>>> b.ngram_fd.items()
[(('a', 'a'), 1), (('a', 'test'), 1), (('is', 'a'), 1), (('is', 'is'), 1), (('test', 'test'), 1), (('this', 'is'), 1), (('this', 'this'), 1)]
>>> b.word_fd.items()
[('a', 2), ('is', 2), ('test', 2), ('this', 2)]
```

Going back to the original source ([Church and Hanks 1990](http://acl.ldc.upenn.edu/J/J90/J90-1003.pdf)), they don't do anything special for multiple cooccurrences within a single window.  So, we'd get:

```
>>> b = BigramCollocationFinder.from_words(sent,window_size=3)
>>> b.ngram_fd.items()
[(('a', 'test'), 3), (('is', 'a'), 3), (('this', 'is'), 3), (('a', 'a'), 1), (('is', 'is'), 1), (('test', 'test'), 1), (('this', 'this'), 1)]
>>> b.word_fd.items()
[('a', 2), ('is', 2), ('test', 2), ('this', 2)]
```

And for `window_size=5`:

```
>>> b = BigramCollocationFinder.from_words(sent,window_size=5)
>>> b.ngram_fd.items()
[(('a', 'test'), 4), (('is', 'a'), 4), (('this', 'is'), 4), (('is', 'test'), 3), (('this', 'a'), 3), (('a', 'a'), 1), (('is', 'is'), 1), (('test', 'test'), 1), (('this', 'this'), 1)]
>>> b.word_fd.items()
[('a', 2), ('is', 2), ('test', 2), ('this', 2)]
```

On pg. 24, Church and Hanks admit this is odd: "one might expect f(x,y) <= f(x) and f(x,y) <= f(y), but the way we have been counting, this needn't be the case if x and y happen to appear several times in the window".  They propose to divide the joint frequencies by `window size - 1`, which in the end just changes the bigram scores by a constant.  

They also say we should get sum f(x) = sum f(y) = sum f(x,y) = N, which we don't, quite.  In the `window_size=2` case, the last word in the sentence can't be the first word of a bigram, so we're off by one:

```
>>> b = BigramCollocationFinder.from_words(sent)
>>> len(sent) == sum(b.word_fd.values()) == sum(b.ngram_fd.values()) + 1
True
```

If `window_size=3`, the last word has no words after it and the second to last word only has one, so we'll be off by three:

```
>>> b = BigramCollocationFinder.from_words(sent,window_size=3)
>>> len(sent) == sum(b.word_fd.values()) == (sum(b.ngram_fd.values()) + 2 + 1) / 2.0
```

And for `window_size=5`, we'd expect:

```
>>> b = BigramCollocationFinder.from_words(sent,window_size=5)
>>> len(sent) == sum(b.word_fd.values()) == (sum(b.ngram_fd.values()) + 4 + 3 + 2 + 1) / 4.0
```

Seem plausible?  (Here's an implementation that does this: b034529d89085c5177b2bf6d3d86f0b46260f257)

**Comment by jnothman** [comment]
Right. Going to the source is also a great idea. Dividing seems to be the solution. I'm also not sure why we should expect `f(x) = sum f(y) = sum f(x,y) = N` -- what did they do different??

Your patch looks good, except that I don't think these strange cases should be in the docstring; they should probably be in a separate test file. And for another test, pass in a larger piece of text for many window sizes and check that those count invariances stay true. Also, add a citation of Church and Hanks in the doc. And I guess submit it as a pull request...

Also, I don't get why we use `pad_right=True` and then discard things...

**Comment by rmalouf** [comment]
WIthout `pad_right=True`, we'd lose the partial n-grams at the end:

```
>>> ngrams('abcd',3,pad_right=True)
[('a', 'b', 'c'), ('b', 'c', 'd'), ('c', 'd', None), ('d', None, None)]
>>> ngrams('abcd',3)
[('a', 'b', 'c'), ('b', 'c', 'd')]
```

In the first case, we observe d in the right-context of c but in the second we miss it.  And then discarding the `None`s is what makes our sums different from Church and Hanks's.

Okay, so, if this seems good, I'll clean it up and fire off a pull request.

**Comment by jnothman** [comment]
of course, we just use `pad_right=True` to calculate `wfd` (while iterating once).
