### ISSUE TITLE
sem.relextract demo

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#42]
<b>What steps will reproduce the problem?</b>
1. sem.relextract.demo()

<b>What is the expected output? What do you see instead?</b>
# Dutch CoNLL2002: van(PER, ORG) -- raw rtuples with context:

...'')[PER: &quot;Cornet/V d'Elzius/N&quot;] 'is/V op/Prep dit/Pron ogenblik/N kabinetsadviseur/N van/Prep 
staatssecretaris/N voor/Prep' [ORG: 'Buitenlandse/N Handel/N'](''...
Traceback %28most recent call last%29:
  File &quot;nltk/sem/relextract.py&quot;, line 437, in &lt;module&gt;
    conllned%28%29
  File &quot;nltk/sem/relextract.py&quot;, line 401, in conllned
    for doc in conll2002.chunked_sents%28'ned.train'%29:
  File &quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-
packages/nltk/util.py&quot;, line 869, in iterate_from
    for value in self._lists[0].iterate_from%28index%29:
  File &quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-
packages/nltk/corpus/reader/util.py&quot;, line 275, in iterate_from
    tokens = self.read_block%28self._stream%29
  File &quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-
packages/nltk/corpus/reader/conll.py&quot;, line 189, in _read_grid_block
    % block)
ValueError: Inconsistent number of columns:
U Pron O
mag V O
één V O
keer N O
raden V O

<b>Please use labels and text to provide additional information.</b>

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=158</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2009-09-19T05:25:51.000Z:</strong></p>
<p>The same problem shows up in relextract.doctest
</p>

**Comment by alexrudnick** [comment]
This seems to be stale. relextract now has a main() instead of a demo(), but it works for me!

**Comment by stevenbird** [comment]
Thanks.
