### ISSUE TITLE
remove nltk.corpus.reader.wordnet._lcs_by_depth

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#422]
I may be wrong, but it looks like `_lcs_by_depth` (https://github.com/nltk/nltk/blob/master/nltk/corpus/reader/wordnet.py#L1578) has the same purpose as `lowest_common_hyphernyms` (https://github.com/nltk/nltk/blob/master/nltk/corpus/reader/wordnet.py#L453), but is not used anywhere (unlike lowest_common_hyphernyms). What do you think about removing it?

**Comment by stevenbird** [comment]
I agree, thanks.

**Comment by stevenbird** [comment]
@jskda was `wordnet._lcs_by_depth` inadvertently reinstated in your pull request? I guess that the developers of omw took a copy of wordnet.py before we removed this?
