### ISSUE TITLE
could not download with python3

### ISSUE THREAD

**Issue by chaowu2009** [nltk/nltk#426]
I downloaded the gz files and installed successfully with python3. After that, in python3, I did :
import nltk
nltk.download()

The following errors show up:

Download which package (l=list; x=cancel)?
  Identifier> co
    Error loading co: Package 'co' not found in index

---

```
d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
```

---

Downloader> l

Packages:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/downloader.py", line 645, in download
    self._interactive_download()
  File "nltk/downloader.py", line 961, in _interactive_download
    DownloaderShell(self).run()
  File "nltk/downloader.py", line 990, in run
    more_prompt=True)
  File "nltk/downloader.py", line 453, in list
    for info in sorted(getattr(self, category)()):
TypeError: unorderable types: Package() < Package()

**Comment by alexrudnick** [comment]
Hey @superbwu!

This should be fixed at the tip of the trunk (I just tried it!). Which release were you using? Try checking out from git, or using the new NLTK 3.0a2 release! http://nltk.org/nltk3-alpha/

Going to close this for now, but feel free to reopen if this doesn't fix the problem.
