### ISSUE TITLE
Resolved:error while importing NLTK 3.0 alpha to python 3.3(no module named 'yaml')

### ISSUE THREAD

**Issue by ppathak2107** [nltk/nltk#427]
Resolved by downloading PyYAML from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyyaml

Got the following error while importing NLTK 3.0 alpha to python 3.3. 'yaml' module could not be located.

> > > import nltk
> > > Traceback (most recent call last):
> > >   File "<pyshell#6>", line 1, in <module>
> > >     import nltk
> > >   File "C:\Python33\lib\site-packages\nltk__init__.py", line 111, in <module>
> > >     from .yamltags import *
> > >   File "C:\Python33\lib\site-packages\nltk\yamltags.py", line 10, in <module>
> > >     import yaml
> > > ImportError: No module named 'yaml'

**Comment by kmike** [comment]
NLTK no longer depends on PyYAML, so this is resolved.
