### ISSUE TITLE
Off-the-shelf models

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#43]
Add off-the-shelf machine learning models for a variety of NLP tasks that are trained on a large 
training corpus, and get reasonably good performance.  E.g.:
- POS Tagging
- Tokenization
- Parsing?
- SRL
- Chunking
- NE detection

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=210</p><hr/><h2>earlier comments</h2>
<p><strong>edloper said, at 2009-02-08T04:26:45.000Z:</strong></p>
<p>Status update:
- Tagger & tokenizer: done and checked in.
- NE chunker: done but not checked in.
- NP chunker: still training the model.

</p><p><strong>ewan.klein said, at 2009-02-11T09:49:43.000Z:</strong></p>
<p>Is there a target date for checking in the NE chunker? </p><p><strong>StevenBird1 said, at 2009-02-11T10:51:11.000Z:</strong></p>
<p>please see r7581</p><p><strong>StevenBird1 said, at 2009-02-21T01:44:59.000Z:</strong></p>
<p>Carried forward to 0.9.9
</p><p><strong>StevenBird1 said, at 2010-03-02T08:48:19.000Z:</strong></p>
<p>The code for off-the-shelf models should live in the source repository, so it can be
inspected and updated.  E.g. how was the maxent tagger model used by NLTK's default
POS tagger (nltk.pos_tag) created?
</p>

**Comment by alvations** [comment]
I know this is an old issue but it's nice to keep track of state-of-code:

**POS Tagger**:  `nltk.pos_tag` with https://github.com/nltk/nltk/issues/1063 and http://stackoverflow.com/questions/30821188/python-nltk-pos-tag-not-returning-the-correct-part-of-speech-tag

**Tokenization**: `nltk.word_tokenize` , `nltk.sent_tokenize` (punkt). Support for more languages would be nice, e.g. CJK / Thai / Arabic segmenters. Also, https://github.com/nltk/nltk/issues/181 and 

**NP/NE chunker**:  `nltk.ne_chunk` but more can be done with `nltk.tag.senna`

**Parsing / SRL**: There's quite a few wrappers around `nltk.sem` and `nltk.parse`.
