### ISSUE TITLE
doctest_driver.py failing on OSX, python 2.7

### ISSUE THREAD

**Issue by dougalg** [nltk/nltk#431]
I tried running the doctest_driver.py and got the following results:

```
$ python doctest_driver.py --help
Traceback (most recent call last):
  File "doctest_driver.py", line 75, in <module>
    class _SpoofOut(StringIO):
TypeError: Error when calling the metaclass bases
    cannot create 'builtin_function_or_method' instances
```

Thanks, Dougal

**Comment by kmike** [comment]
I was always wanting to remove doctest_driver, and even removed it once :) In my opinion doctest_driver.py is a cool piece of software, but it is not related directly to NLTK, and it requires maintaining.

If the question is how to run doctests, check https://github.com/nltk/nltk/blob/master/web/dev/local_testing.rst for information about better supported ways for running tests. E.g. for wordnet it could be

```
cd nltk/test/
runtests.py wordnet.doctest
```

or 

```
tox -e py27-nodeps -- wordnet.doctest
```

**Comment by dougalg** [comment]
Thank you!

**Comment by kmike** [comment]
I think this ticket should remain open, because the reported issue (doctest_drivers fails in Python 2.7) is valid.

**Comment by dougalg** [comment]
OK, sorry about that.

**Comment by kmike** [comment]
No problems, thanks for taking time to report this issue!

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/bb0120cc1d0a9beb579f6465d7f1bfce8533c223
