### ISSUE TITLE
Make realign_boundaries=True the default for PunktSentenceTokenizer?

### ISSUE THREAD

**Issue by nschneid** [nltk/nltk#439]
By default, the sentence tokenizer always ends a sentence immediately after an end-of-sentence period, stranding any closing quote/parenthesis/bracket that follows as its own segment. I cannot think of any circumstance in which this would be the desired behavior. This can be corrected for with the `realign_boundaries` argument to `tokenize()`:

``` python
from nltk.tokenize import PunktSentenceTokenizer
sent_tokenizer = PunktSentenceTokenizer()
sents = sent_tokenizer.tokenize(text, realign_boundaries=True)
```

However, `realign_boundaries` is not very discoverable, especially because `nltk.tokenize.sent_tokenize()` does not provide this option.

Why not just make `realign_boundaries=True` the default, in which case it would be the behavior for `nltk.tokenize.sent_tokenize()` as well?

**Comment by jnothman** [comment]
I added this feature to the original port of K&S and left it off for backwards compatibility. I agree that it is useful as a default setting, but it hasn't been evaluated or rigorously tested (to my knowledge).

**Comment by stevenbird** [comment]
I agree that this is a better default setting. So I think we just need to create some tests. The code which does the job is not at all transparent.

**Comment by jnothman** [comment]
> The code which does the job is not at all transparent.

You're welcome :)

**Comment by stevenbird** [comment]
Lol. Sorry :)

**Comment by stevenbird** [comment]
I've reversed the default behavior and added some tests in https://github.com/nltk/nltk/commit/a56dc431d5758a96d03867c46d9d21650ee8ef5a
