### ISSUE TITLE
nltk.download() giving error 110 : Connection timed out

### ISSUE THREAD

**Issue by chaithuzz2** [nltk/nltk#442]
I installed nltk and i typed the following commands
 <code> import nltk <code/>
<code> nltk.download() <code/>

then it takes a lot of time and it says error 110 : connection timed out. the terminal log is below.  

showing info http://nltk.github.com/nltk_data/
True

my internet connection is solid . and i dont have any problems with my python version.  what might be the problem ? please help me.

**Comment by stevenbird** [comment]
I think this must have been a transient issue.
