### ISSUE TITLE
Restore support for open(fp) when fp is FileSystemPathPointer

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#443]
Tests from corpus.doctest and childes.doctest are failing after this change: https://github.com/jskda/nltk/commit/fae1b819cfe46eaa3f81dc0584b8d21f02ad9a36 (which is a part of #441) with TypeErrors, like

```
File "/Users/kmike/svn/nltk/nltk/test/corpus.doctest", line 1924, in corpus.doctest
Failed example:
    l3 = open(f3).read().split()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python3/3.3.2/Frameworks/Python.framework/Versions/3.3/lib/python3.3/doctest.py", line 1287, in __run
        compileflags, 1), test.globs)
      File "<doctest corpus.doctest[366]>", line 1, in <module>
        l3 = open(f3).read().split()
    TypeError: invalid file: FileSystemPathPointer('/Users/kmike/nltk_data/corpora/inaugural/1909-Taft.txt')
```

I agree that we may want to encourage using fp.open instead of open(fp), but this was a documented interface (at least via doctests and docstrings), and it is better not to break it if we can. Yes, ZipFilePathPointer doesn't work, but FileSystemPathPointer worked before and I don't see why we should break user code.

So +1 for deprecating open(fp) and discouraging it (by changing docs and doctests, and putting a note into chengelog), but -1 for just removing it and breaking user code if the only reason was to do a cleanup.

**Comment by stevenbird** [comment]
+1 to @kmike's proposal.

**Comment by stevenxxiu** [comment]
I'm using compat.text_type instead of str in the pull request, as in python 2 they are not the same, and paths can contain unicode.

**Comment by kmike** [comment]
This breaks `__str__` because `__str__` must return byte strings in Python 2.x, and unicode constructor should accept unicode. I think that just deleting `__str__` method would work.

**Comment by kmike** [comment]
I haven't checked it, but `FileSystemPathPointer(u'C:\\test.txt').__str__()` will return unicode, won't it?

**Comment by stevenxxiu** [comment]
You are right, I mistakenly used `str()` not `__str__()` to test.

**Comment by stevenxxiu** [comment]
Deleting `__str__` would work, but would leaving it in, and calling `str()`, make it more clear as to what is going on? Classes such as `ZipFilePathPointer` have a `__str__` method. On that note wouldn't it also be clearer if that method calls `str()` as well?

**Comment by kmike** [comment]
I'm not sure what is clearer, overriding `__str__` method to do exactly the same as parent method, or not having `__str__` methods defined both for ZipFilePathPointer and for FilePathPointer. Previously I've chosen to not override `__str__` and make a comment about that in the source code. But I don't have a strong opinion here, either way would work.

**Comment by stevenbird** [comment]
I prefer @kmike's solution of not overriding the parent method and just adding a comment if that helps readers of the code to see what is going on. Which **str** implementations need to be removed?

**Comment by stevenbird** [comment]
Are there any str methods that need to be removed? Should this issue block nltk3?

**Comment by kmike** [comment]
`FileSystemPathPointer.__str__` is to be removed (with a comment restored from one of the previous commits). This is only a minor style fix; it shouldn't block NLTK3.
