### ISSUE TITLE
Remove Python pickling bug workaround from compat.py

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#444]
See https://github.com/nltk/nltk/pull/441#discussion_r5211682 for more info.

I think the real bug is in pickling, not in unpickling, so it is much better to fix the way models are pickled (by either using fix_imports=False or temporarily patching REVERSE_IMPORT_MAPPING)

**Comment by stevenxxiu** [comment]
I'm going to temporarily patch REVERSE_IMPORT_MAPPING and remove the code from compat. Thanks for pointing this out.

**Comment by kmike** [comment]
Good, thanks!

**Comment by stevenxxiu** [comment]
I've fixed this on my branch

**Comment by stevenxxiu** [comment]
It should be merged now.
