### ISSUE TITLE
nltk.clean_html() hangs

### ISSUE THREAD

**Issue by ghost** [nltk/nltk#448]
The html document that I'm trying to clean is https://gist.github.com/rogerthealien/6055726 and nltk.clean_html() enters an infinite loop. I've tried to look at the trace but can't seem to figure out what's causing the problem. 

This is where it hangs:

 File "_tmp.py", line 7, in <module>
    soup = BeautifulSoup(nltk.clean_html(input_file.read()))
  File "/usr/local/lib/python2.7/dist-packages/nltk/util.py", line 340, in clean_html
    cleaned = re.sub(r"(?is)<(script|style)._?>._?(</\1>)", "", html.strip())
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)

Lines 339-340 of util.py are:
# First we remove inline JavaScript/CSS:

```
cleaned = re.sub(r"(?is)<(script|style).*?>.*?(</\1>)", "", html.strip())
```

**Comment by ghost** [comment]
I modified util.py to use lxml instead of regex to remove style and script tags, which solved the issue for me.

from lxml.html.clean import Cleaner

def clean_script_style(text):
    cleaner = Cleaner(style = True, scripts = True)
    return cleaner.clean_html(text)

# First we remove inline JavaScript/CSS:
   #cleaned = re.sub(r"(?is)<(script|style)._?>._?(</\1>)", "", html.strip())
    cleaned = clean_script_style(html.strip())

**Comment by ghost** [comment]
Apparently, it was entering an infinite loop when trying to resolve the style tags, the regex worked for script tags.

**Comment by stevenxxiu** [comment]
Thanks, I've fixed this on my branch (https://github.com/jskda/nltk) this way:

```
def clean_html(html):
    """
    Remove HTML markup from the given string.

    :param html: the HTML string to be cleaned
    :type html: str
    :rtype: str
    """
    cleaned = ' '.join(lxml.html.document_fromstring(html).itertext())
    # deal with whitespace, including tabs
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned.strip()
```

**Comment by kmike** [comment]
Hmm. I think that's a serious bug (it can be seen as a security bug), but is it possible to fix it without creating lxml dependency?

Lxml parser is fast and robust, but NLTK currently doesn't depend on lxml. Also, parsing html with lxml is completely different, e.g. it could raise an exception if unicode string is passed and there is an encoding declaration in html code, so 'type html: str' is a bad advice in Python 3 where str is unicode. 

`re.sub(r"\s+", " ", cleaned)` - it could be better to pass re.UNICODE flag to make \s aware of unicode whitespaces.

**Comment by stevenxxiu** [comment]
> Lxml parser is fast and robust, but NLTK currently doesn't depend on lxml. Also, parsing html with lxml is completely different, e.g. it could raise an exception if unicode string is passed and there is an encoding declaration in html code, so 'type html: str' is a bad advice in Python 3 where str is unicode. 

Thanks for pointing that out, I wasn't aware of this issue, we could just encode the string first in that case.

> Hmm. I think that's a serious bug (it can be seen as a security bug), but is it possible to fix it without creating lxml dependency?

Some sort of dependency is probably needed if html documents are to be parsed accurately. I don't think parsing them with regex is a good idea. Beautiful soup is another possible library.

> re.sub(r"\s+", " ", cleaned) - it could be better to pass re.UNICODE flag to make \s aware of unicode whitespaces.

I was only thinking of python 3 here, I've fixed the python 2 case in my branch.

**Comment by kmike** [comment]
> Thanks for pointing that out, I wasn't aware of this issue, we could just encode the string first in that case.

We should encode it to correct encoding for this to work properly. This encoding is defined by 'meta' html tag. So in order to encode it to correct encoding we must first parse html (presumably using a simpler approach), extract the encoding name, map it to Python encoding name (they are not exactly the same) and encode unicode to this encoding.

But user probably already had binary HTML at some point, e.g. she could obtain it from urllib or by loading local file.

If the data is obtained from WEB, there is one more clue about the correct encoding: Content-Type header. So even if we pass binary data to clean_html, lxml could do wrong thing if there is no meta tag. I think lxml.html.HtmlParser accepts 'encoding' argument.

**Comment by stevenxxiu** [comment]
> >    Thanks for pointing that out, I wasn't aware of this issue, we could just encode the string first in that case.
> > We should encode it to correct encoding for this to work properly. This encoding is defined by 'meta' html tag. So in order to encode it to correct encoding we must first parse html (presumably using a simpler approach), extract the encoding name, map it to Python encoding name (they are not exactly the same) and encode unicode to this encoding.

What I meant was to just call `.encode()` to encode the string to bytes.

> If the data is obtained from WEB, there is one more clue about the correct encoding: Content-Type header. So even if we pass binary data to clean_html, lxml could do wrong thing if there is no meta tag. I think lxml.html.HtmlParser accepts 'encoding' argument.

Yes it is probably more flexible to add an 'encoding' argument from the encoding the user has detected. Another way to detect encodings is by using bs4 (beautiful soup 4)'s UnicodeDammit class. I've added a bs4-only implementation on my branch.

**Comment by stevenbird** [comment]
clean_html also has the problem that its not a very good solution for stripping HTML. I think it would be more Pythonic to teach users to use Beautiful Soup directly, e.g. with: soup.get_text(). How about we simply deprecate clean_html()?

**Comment by stevenxxiu** [comment]
@stevenbird I support your proposal, as neither clean_html nor clean_url is used in any of the project files.

**Comment by stevenbird** [comment]
clean_html and clean_url are dropped in commit 39a303e5ddc4cdb1a0b00a3be426239b1c24c8bb
