### ISSUE TITLE
Incorrect display non-ascii characters in console using .words function

### ISSUE THREAD

**Issue by GraphGrailAi** [nltk/nltk#449]
Python 2.7.5 on Windows 7  with Winpython pack, NLTK 3.0a1
I am working with russian language

When i try this:

from nltk.stem import SnowballStemmer           #подключение словаря и импорт SnowballStemmer
russian_stemmer = SnowballStemmer('russian')    #выбор русского языка для извлечения корня
print (russian_stemmer.stem(u'приветственный')) #вывод на экран корня слова

i see correct results in Pycharm console:

> > приветствен

But when i try to print a words list from txt file i see incorrect russian text:

agit_corpus_words = agit_corpus.words('agitacia/discreditacia11.txt')
print agit_corpus_words

> > [u'\u041f\u043e\u0447\u0435\u043c\u0443', u'74', u'%', ...]

This txt file consist only russian characters.
What i have tried: resaving that file in Windows Notepad in: UTF-8, Unicode, Unicode Big Endian, ANSI - all this is not solving the problem

**Comment by kmike** [comment]
Is your problem this string: `u'\u041f\u043e\u0447\u0435\u043c\u0443'`? Check this:

```
>>> print u'\u041f\u043e\u0447\u0435\u043c\u0443'
Почему
```

Note that your examples are not the same. In first example you're printing unicode string. In second example you're printing a list with unicode strings. Python 2.x escapes the strings in latter case, this is expected behavior. You can print words one-by-one using a loop:

```
for word in words:
    print word  # should print readable string
```

or join them to a single string (like `' '.join(words)`) and print the result.

Python 3.x doesn't have this problem, but some NLTK pre-built models are not yet available for Python 3.x.

**Comment by kmike** [comment]
.. but these pre-trained models don't work with Russian anyways, so if you only need to work with Russian text you can download NLTK 3.0a2 (or NLTK master) and just use it with Python 3.3 :)

**Comment by GraphGrailAi** [comment]
Thanks, both of your examples prints correct russian. But i afraid this Python 2 issue will cause obstacle later. I am trying to make document classification, such as here http://streamhacker.com/2010/05/10/text-classification-sentiment-analysis-naive-bayes-classifier/  and have to use built-in functions. 

My guess if i will try print 'accuracy:', nltk.classify.util.accuracy(classifier, testfeats)  it will print bad encoded russian, and in this case i will not know how to reproduce it with simple loop (i am new to Python)/ Why not swith to Python 3: i have it, but some examples from book doesn't work and i don't know how to fix.

**Comment by kmike** [comment]
It is not 'bad encoded russian', it is 'escaped russian'. You can usually copy-paste it and print if you really need to. 

Unfortunately there is no way to always have readable container representation in console in Python 2.x. 

We can fix `NaiveBayesClassifier.show_most_informative_features()` which you have troubles with though: it uses %r format specifier while it could be using %s instead. So I'm not closing this ticket.

**Comment by GraphGrailAi** [comment]
Really, with Python 3.3.2 words list looks good. Will continue use it, SnowballStemmer works too. Thanks a lot!

**Comment by petr-tik** [comment]
Is this still open? Looks pretty thoroughly discussed

**Comment by GraphGrailAi** [comment]
No, close please.
From that time i have moved to Python 3.4 so this issue no longer actual
