### ISSUE TITLE
Use scikit-learn for nltk.classify.svm or deprecate/remove nltk.classify.svm

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#450]
I think that nltk.classify.svm does more harm than good currently, mainly because it is based on https://bitbucket.org/wcauchois/pysvmlight. It has the following issues:
- license restrictions (only for non-commercial use) - documentation ("For license information, see LICENSE.TXT") is incorrect regarding this, by the way;
- pysvmlight doesn't install in Python 3.x; another installation issue is reported [here](https://groups.google.com/d/msg/nltk-users/34fjbwCUHTI/kVfimh7xGyIJ);
- it segfaults. This was reported e.g. at https://github.com/nltk/nltk/issues/170, https://github.com/nltk/nltk/issues/261#issuecomment-6861718 and [here](https://groups.google.com/forum/?fromgroups#!topic/nltk-users/qEct8uzpjnY).

What do you think about removing it and suggesting to use nltk.classify.scikitlearn together with LinearSVC (or scikit-learn directly) instead?

Another option would be to support the existing interface, but change the implementation to use nltk.classify.scikitlearn. It looks like more work. They both have feature mapping implemented, but in different ways; I'm not sure it worths it to support the mapping method implemented in nltk.classify.svm.

**Comment by leondz** [comment]
I think this is a good idea. Better integration with scikit-learn has given us many options for SVM classification, compared to the zero we had when I added this module. Pysvmlight appears to be unmaintained, and so the situation is unlikely to improve - on top of the license restrictions. We now have multiple choices for using SVM in NLTK, and this one is sub-optimal.

**Comment by stevenbird** [comment]
+1 yes I think it is a good idea to drop nltk.classify.svm

**Comment by Narts** [comment]
+1  scikit-learn has given us many options for SVM classification

**Comment by larsmans** [comment]
If by feature mapping, you mean taking features with string values and converting them to one-of-K boolean features, that can be added in two ways:
- by adding it to the scikit-learn wrapper directly, or
- by using a scikit-learn `DictVectorizer` in the wrapper.

The latter option means that the scikit-learn wrapper gets an extra dependency: it's currently built in such a way that any object that adheres to the [scikit-learn API](http://staff.science.uva.nl/~buitinck/papers/scikit-learn-api.pdf) should work, without actually requiring scikit-learn (so estimators from [astroML](http://www.astroml.org/), [lightning](https://github.com/mblondel/lightning) or [WiseRF](http://about.wise.io/wiserf/) can also be plugged in -- two of these still require scikit-learn, though).

**Comment by stevenbird** [comment]
@larsmans I think ease of maintenance trumps ease of installation, which means I favour the second option. Is there an issue with translating results back to NLTK's representation, or can scikit-learn's feature representation be entirely hidden.

Given the pedagogical goals of NLTK, would there be a case to expose scikit-learn's feature representations, and document them on the NLTK side? If so, the calling program would do the vectorising. I wonder how messy this gets. I see the following documentation and its not clear...

http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.DictVectorizer.html

**Comment by larsmans** [comment]
@stevenbird The `scipy.sparse` matrices used by scikit-learn are one of the most confusing parts of the toolkit, to users and developers alike. I'm not sure if NLTK users should be bothered with them, although we could offer a public conversion method. I'll see what I can do.

**Comment by stevenbird** [comment]
@larsmans in that case I'm happy if the mapping can be done inside the interface, and for this to involve a new dependency. Can we document the scikit-learn dependency in a docstring, and produce a helpful error message if it's not installed?

**Comment by kmike** [comment]
I'm lost :) Is the plan to deprecate nltk.classify.svm or to reimplement it using nltk.classify.scikitlearn? If the plan is to reimplement it using nltk.classify.scikitlearn then should it remain compatible with the old interface, or maybe simply exposing something like `SklearnClassifier(LinearSVC())` is enough?

**Comment by stevenbird** [comment]
I think we already have a reimplementation of the existing interface, just with a new dependency. So this issue is resolved, right?

**Comment by kmike** [comment]
No, we haven't touched nltk.classify.svm yet. @larsmans simplified and improved implementation of nltk.classify.scikitlearn in #462. 

Interface of nltk.classify.svm.SvmClassifier is not compatible with SklearnClassifier because of different constructor parameters and some extra public methods; constructor parameters are different because of how features are mapped.

I personally think we should just deprecate nltk.classify.svm with a message pointing to nltk.classify.scikitlearn without providing compatibility layer. I don't see a good reason to provide and maintain a shim over SklearnClassifier with a sole purpose of having slightly different interface.

**Comment by stevenbird** [comment]
+1 to deprecating nltk.classify.svm

**Comment by larsmans** [comment]
A `resolve_prediction` method can be implemented for `SklearnClassifier`, although it won't be tremendously useful. A typical scikit-learn implementation of `predict` performs this task internally, and the lower-level `decision_function` that corresponds to `_get_svm_classification` is currently not exported through the wrapper.
