### ISSUE TITLE
Distribute NLTK as .msi 

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#46]
<b>Describe the feature you would like us to add.</b>

The NLTK download page currently lists the following as the Windows
distribution:

http://nltk.googlecode.com/files/nltk-0.9.7.win32.exe 

This was presumably created with something like &quot;python setup.py
bdist_wininst&quot;. As of Python 2.5, you can now instead use &quot;python setup.py
bdist_msi&quot; to get a nice .msi installer (which in my experience is much
nicer than the old .exe installers).

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=219</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2009-01-29T01:36:45.000Z:</strong></p>

<p>The distutils package has a method distutils.command.bdist_msi, however this doesn't appear to be 
accessible from setup.py (see list of supported formats below), nor is it mentioned in the distutils 
documentation section on creating windows installers:

http://docs.python.org/distutils/builtdist.html#creating-windows-installers

python setup.py bdist --help-formats
List of available distribution formats:
  --formats=rpm      RPM distribution
  --formats=gztar    gzip'ed tar file
  --formats=bztar    bzip2'ed tar file
  --formats=ztar     compressed tar file
  --formats=tar      tar file
  --formats=wininst  Windows executable installer
  --formats=zip      ZIP file

(Please reopen this if you discover some way to build an MSI package.)

</p><p><strong>steven.bethard said, at 2009-01-29T03:06:28.000Z:</strong></p>

<p>It works for me. And it's in both the 2.5 and 2.6 documentation:

http://docs.python.org/dev/2.5/dist/module-distutils.command.bdistmsi.html
http://docs.python.org/distutils/apiref.html#module-distutils.command.bdist_msi

Here it is working on NLTK:

$ python setup.py bdist_msi
running bdist_msi
running build
running build_py
...
copying build\lib\nltk\book.py -> build\bdist.win32\msi\Lib\site-packages\nltk
creating build\bdist.win32\msi\Lib\site-packages\nltk\chat
copying build\lib\nltk\chat\eliza.py -> build\bdist.win32\msi\Lib\site-packages\nltk\chat
copying build\lib\nltk\chat\iesha.py -> build\bdist.win32\msi\Lib\site-packages\nltk\chat
...
Writing build\bdist.win32\msi\Lib\site-packages\nltk-0.9.6-py2.6.egg-info
removing 'build\bdist.win32\msi' (and everything under it)

$ dir /B dist
nltk-0.9.6.win32-py2.6.msi

I've filed a Python bug for the missing info in --help-formats:

http://bugs.python.org/issue5095</p><p><strong>StevenBird1 said, at 2009-01-30T02:10:09.000Z:</strong></p>

<p>Thanks for this.  For python 2.5.1 and 2.5.2 running this setup command gives me: "error: invalid command 
'bdist_msi'".  It looks like you're using 2.6, and that distutils.command.bdist_rpm wasn't accessible via setup.py 
before 2.6.

</p><p><strong>steven.bethard said, at 2009-02-01T18:11:55.000Z:</strong></p>

<p>That's pretty odd. I just downloaded 2.5.4 (the most recent 2.5 available), and here
it is working there:

$ C:\Python25\python.exe setup.py bdist_msi
running bdist_msi
running build
running build_py
...

Seems odd that they'd introduce it in a point release. Are you running on a Windows
machine? Maybe .msi can only be created on a Windows machine?</p><p><strong>StevenBird1 said, at 2009-02-21T01:44:59.000Z:</strong></p>

<p>Carried forward to 0.9.9
</p><p><strong>StevenBird1 said, at 2009-06-21T10:46:16.000Z:</strong></p>

<p>Mac Python 2.5.4 won't let me build a .msi package.  Perhaps this is fixed in 2.6. 
Anyway, I'd like to ask your help to post a .msi release for 2.0rc1 next week please.

</p><p><strong>steven.bethard said, at 2009-06-21T14:51:35.000Z:</strong></p>

<p>Sure, no problem.</p>

**Comment by stevenbird** [comment]
The .exe and pip installation methods seem to work fine.
