### ISSUE TITLE
character encoding problem in UDHR corpus

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#47]
For two of the UDHR files, doing list(udhr.words(f)) produces the following decoding errors:

Arabic_Alarabia-Arabic 'charmap' codec can't decode byte 0xde in position 18: character maps to 
&lt;undefined&gt;
Czech_Cesky-UTF8 'utf8' codec can't decode byte 0x8a in position 1: unexpected code byte

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=235</p>

**Comment by alexrudnick** [comment]
If somebody could figure out how to reproduce this, or whether it's still a problem, that would be really helpful!

**Comment by heatherleaf** [comment]
The bug still holds… 

I guess there's an encoding problem in the original corpus material. My suggestion is to replace unicode decode error mode 'strict' to 'ignore' or 'replace'.

**Comment by turicas** [comment]
I'm trying to collect character encoding data from all NLTK corpora and fix the way NLTK stores and retrieve this information (currently at least 32 corpora are stored as string instead of unicode). More information on #299.
