### ISSUE TITLE
Framenet tests are duplicated

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#478]
Framenet tests were not removed from corpus.doctest in https://github.com/nltk/nltk/commit/f3192dd96378f675a622481c7b1e5041adf00c4d , so there are 2 copies of these tests. I think we should remove them from corpus.doctest.

**Comment by nschneid** [comment]
@wooters, is there any reason to have tests duplicated in corpus.doctest?

**Comment by stevenbird** [comment]
@kmike It looks like my modifications to corpus.doctest (replacing the framenet and propbank sections with cross references) were not committed. I'll fix this.
