### ISSUE TITLE
Enabling telugu language into NLTK

### ISSUE THREAD

**Issue by srujan22** [nltk/nltk#481]
Producing Unicode for the telugu text is created in to textual file.How to produce telugu words into NLTK2.0.1rc1

**Comment by robwahl** [comment]
I'm also showing an encoding error in floesta.txt. Lossy encoding floesta.txt file was loaded with wrong encoding being that it is not UTF-8. I have resaved this as UTF-8 and uploaded it in my patch.

**Comment by kmike** [comment]
@srujan22 could you please elaborate? I don't understand your question.

**Comment by stevenbird** [comment]
Closing. This concerns a version of NLTK that is more than two years old.
