### ISSUE TITLE
tkinter problems

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#49]
From issue 201, reported by kostik.vento:

While cfd.plot(cumulative=True) works fine, cfd.plot() takes all the
processor's time (more exactly: the graph appeares, but I can't resize it,
nor even minimize it — the window hangs, and the only thing that helps is
to forcingly close the graph window, causing Python Shell's restart). The
screenshot about the problem is attached as cfd.plot.jpg.

But when I try the same code after Python Shell's restart, cfd.plot() works
correctly, so that I can resize the plot's window or minimize it and so on.
I use Python 2.5 on WinXP SP2, if it matters.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=250</p>

**Comment by stevenbird** [comment]
Closing – too out of date.
