### ISSUE TITLE
Improve sentence tokenizer

### ISSUE THREAD

**Issue by PanderMusubi** [nltk/nltk#494]
I have the following example with nltk 2.0.4:

```
import nltk
text = 'He said: "No!" He said: "No!" and walked away.\nHe said: “No!” and walked away.\n\nHe asked: "Really?" He asked: "Really?" and walked away.\nHe asked: „Really?” and walked away. He asked: „Really?” and walked away.'
paragraphs = nltk.LineTokenizer().tokenize(text)
print 'Total paragraphs:', len(paragraphs)
for paragraph in paragraphs:
    sentences = nltk.tokenize.sent_tokenize(paragraph)
    for sentence in sentences:
        print sentence
```

This is the output:

```
He said: "No!
" He said: "No!
" and walked away.
He said: “No!” and walked away.
He asked: "Really?
" He asked: "Really?
" and walked away.
He asked: „Really?” and walked away.
He asked: „Really?” and walked away.
```

As you can see !" and ?" are not processed well. Can this be improved or fixed or what would be a workaround that will split these sentences according to the following pseudocode regex examples:

split
    ...[?!]" [A-Z]...
into
    ...[?!]"
    [A-Z]...
and not into
    ..[!?]
    " [A-Z]...
as it is doing now

and to _not_ split
    ...[?!]" [a-z]...
because now it splits into
    ..[!?]
    " [a-z]...

**Comment by kmike** [comment]
See also: https://github.com/nltk/nltk/issues/439

Could you try it with latest NLTK master? For me it looks better now:

```
import nltk

In [2]: text = u'He said: "No!" He said: "No!" and walked away.\nHe said: “No!” and walked away.\n\nHe asked: "Really?" He asked: "Really?" and walked away.\nHe asked: „Really?” and walked away. He asked: „Really?” and walked away.'

In [3]: paragraphs = nltk.LineTokenizer().tokenize(text)

In [4]: for para in paragraphs: print nltk.tokenize.sent_tokenize(para)
[u'He said: "No!"', u'He said: "No!"', u'and walked away.']
[u'He said: \u201cNo!\u201d and walked away.']
[u'He asked: "Really?"', u'He asked: "Really?"', u'and walked away.']
[u'He asked: \u201eReally?\u201d and walked away.', u'He asked: \u201eReally?\u201d and walked away.']
```

Please also note that you may be working with unicode incorrectly: 'text' contains non-ascii symbols (unicode quotes), but it is a byte string in your example (unless `from __future__ import unicode_literals` import is in effect).

**Comment by kmike** [comment]
Ah, that was nltk 2.0.4 - I guess you are passing bytestrings to sent_tokenize properly in that case. It is better to encode them explicitly for 2.0.4 though. For NLTK3 all text should be unicode.

**Comment by PanderMusubi** [comment]
Thanks for the replies so far. The Unicode quotes are indeed intended.

```
>>> a=u'“'
>>> a
u'\u201c'
>>> print a
“
```

Would you recommend using 'bla' with from **future** import unicode_literals over u'bla'? I get a bit tired of all the u'...' instead of '...' and the .decode('utf-8') I need to add when I an writing to a file. What do you advise with your previous comment (how would that look in Python code)?

The sentence separation is indeed correct with 3.0a2. Next challenge is the word tokenizer because  “No should be  “ and No and „Really should be „ and Really. See below the bug:

```
>>> for paragraph in paragraphs:
...     sentences = nltk.tokenize.sent_tokenize(paragraph)
...     for sentence in sentences:
...         for word in nltk.tokenize.word_tokenize(sentence):
...             print word
... 
He
said
:
``
No
!
''
He
said
:
``
No
!
''
and
walked
away
.
He
said
:
“No
!
”
and
walked
away
.
He
asked
:
``
Really
?
''
He
asked
:
``
Really
?
''
and
walked
away
.
He
asked
:
„Really
?
”
and
walked
away
.
He
asked
:
„Really
?
”
and
walked
away
.
```

**Comment by PanderMusubi** [comment]
Master now results in

```
>>> for paragraph in paragraphs:
...     sentences = nltk.tokenize.sent_tokenize(paragraph)
...     for sentence in sentences:
...         print(sentence)
... 
He said: "No!"
He said: "No!"
and walked away.
He said: “No!” and walked away.
He asked: "Really?"
He asked: "Really?"
and walked away.
He asked: „Really?” and walked away.
He asked: „Really?” and walked away.
```

so that is fixed but the latter example still results in:

```
He
said
:
``
No
!
''
He
said
:
``
No
!
''
and
walked
away
.
He
said
:
“No
!
”
and
walked
away
.
He
asked
:
``
Really
?
''
He
asked
:
``
Really
?
''
and
walked
away
.
He
asked
:
„Really
?
”
and
walked
away
.
He
asked
:
„Really
?
”
and
walked
away
.
```

As you can see “No and „Really (2x) is incorrect. Could this please be fixed?

**Comment by jnothman** [comment]
That's a nice set of test cases for issues that neither Kiss and Strunk's Punkt algorithm nor the PTB's word tokenizer intended to deal with. Clearly " and ” are being treated differently in both cases, and it would be nice if they were not.

IIRC, Punkt assumes every ! and ? token is a sentence break, and doesn't do any interesting disambiguation. (I guess the reason it's not breaking in `“No!” and` is because the `”` is not split off from the `!` so `!` isn't seen as a separate token.) And quotes aren't handled specially, but probably should be. However, it might be possible to extend the collocation or orthographic heuristics to apply in these cases.

**Comment by PanderMusubi** [comment]
Please let me know if I can help out with this to get this supported.

**Comment by PanderMusubi** [comment]
Could this please be reopened?

**Comment by jnothman** [comment]
Except your issues regarding "„Really" and "“No" are unrelated to the sentence tokenizer. They're issues with the PTB word tokenizer, and should be presented as a separate issue without the confusing history shown here.
