### ISSUE TITLE
Chunk parser nomenclature

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#504]
Change the chunk parser API to use chunk_label and top_label (instead of _node).

**Comment by heatherleaf** [comment]
Why? Then the chunkparser cannot return a Tree, as it currently does.

**Comment by stevenbird** [comment]
I'm only proposing to change the names of some named arguments that refer to the node label. There would be no effect on the return type.

**Comment by stevenbird** [comment]
The chunk parser API now uses root_label and chunk_label instead of top_node and chunk_node, for consistency with naming of tree properties. Resolved in: https://github.com/nltk/nltk/commit/5eb5d62e8481d6bff5e54a9518a5c0b788d0b76c
