### ISSUE TITLE
Global WordNet Grid

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#505]
@fcbond and students have developed interfaces to the Open Multilingual WordNet (aka Global WordNet Grid), along with a consistently-formatted dataset, and has verified that the data can be redistributed. Add the data and one of the interfaces to NLTK.

**Comment by stevenbird** [comment]
Sorry for the delay; I'm planning to add this soon.

**Comment by fcbond** [comment]
Great, we are ready to test it :-).

On Wed, Mar 5, 2014 at 5:05 PM, Steven Bird notifications@github.comwrote:

> Sorry for the delay; I'm planning to add this soon.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/505#issuecomment-36722262
> .

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by stevenbird** [comment]
Sorry for the further delay. The data is now in the NLTK data collection, https://github.com/nltk/nltk_data/commit/fc2919dc43b151deca1d8281cfc4b41bda5c4691.
It appears as item 39 in NLTK's corpus collection, http://www.nltk.org/nltk_data/

**Comment by stevenbird** [comment]
I would like to use the code contributed by @fcbond's students Nasruddin A’aidil Shari, Sim Wei Ying Geraldine, and Soe Lynn. https://gist.github.com/stevenbird/11128654
It adds a language parameter to the existing wordnet methods. When no language is specified, the default should be English (for backwards compatibility).

**Comment by fcbond** [comment]
I think that makes sense.

On Mon, Apr 21, 2014 at 8:10 AM, Steven Bird notifications@github.comwrote:

> I would like to use the code contributed by @fcbondhttps://github.com/fcbond's
> students Nasruddin A’aidil Shari, Sim Wei Ying Geraldine, and Soe Lynn.
> https://gist.github.com/stevenbird/11128654
> It adds a language parameter to the existing wordnet methods. When no
> language is specified, the default should be English (for backwards
> compatibility).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/505#issuecomment-40908593
> .

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by stevenbird** [comment]
Merged code plus some fixes in https://github.com/nltk/nltk/commit/d6b41500bb5f50b60186d0d3496161dd2a622fc0

**Comment by stevenbird** [comment]
Some issues still remain, e.g. `wn.langs()` gives a different list to the one in `ls /usr/share/nltk_data/corpora/omw`. There are also some doctest errors in `test/wordnet.doctest`.

**Comment by fcbond** [comment]
OK, I will fix these this week.  We have also added more languages to OMW
(Greek, Swedish) so I will add them.

On Sat, May 3, 2014 at 6:59 PM, Steven Bird notifications@github.comwrote:

> Some issues still remain, e.g. wn.langs() gives a different list to the
> one in ls /usr/share/nltk_data/corpora/omw. There are also some doctest
> errors in test/wordnet.doctest.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/505#issuecomment-42102164
> .

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by stevenxxiu** [comment]
> Some issues still remain, e.g. wn.langs() gives a different list to the one in ls /usr/share/nltk_data/corpora/omw. There are also some doctest errors in test/wordnet.doctest.

I tried to extract the different languages by globbing the tab files, as I think some directories contain multiple tab files (/usr/share/nltk_data/corpora/omw/mcr, which has Catalán and Spanish). Is this alright?

**Comment by fcbond** [comment]
Yes, that's right.

On Wed, May 14, 2014 at 7:28 PM, jskda notifications@github.com wrote:

> Some issues still remain, e.g. wn.langs() gives a different list to the
> one in ls /usr/share/nltk_data/corpora/omw. There are also some doctest
> errors in test/wordnet.doctest.
> 
> I tried to extract the different languages by globbing the tab files, as I
> think some directories contain multiple tab files
> (/usr/share/nltk_data/corpora/omw/mcr, which has Catalán and Spanish). Is
> this alright?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nltk/nltk/issues/505#issuecomment-43069247
> .

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by stevenbird** [comment]
Commit https://github.com/nltk/nltk/commit/cf3a110208ff0cd07f9bde1c53548f7b62f95877 makes the  interface stable, and is neutral with respect to the possibility of adding this functionality back later (using additional method names, though I don't see a strong case for this).

**Comment by bryant1410** [comment]
Hi. @luischir and UdelaR NLP group have been working in a transformation from MCR database to wordnet usual format: https://github.com/pln-fing-udelar/wn-mcr-transform

Maybe this can be helpful

**Comment by stevenbird** [comment]
We now have support for the Open Multilingual Wordnet, so I'm closing this.
