### ISSUE TITLE
Tag mapping for Treebank

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#508]
> > > from nltk.corpus import treebank
> > > treebank.tagged_words(tagset='universal')
> > >     ...
> > >     tagged_sent = [(w, map_tag(self._tagset, tagset, t)) for (w,t) in tagged_sent]
> > > NameError: global name 'map_tag' is not defined

**Comment by Liechti** [comment]
What's the issue here? Is there anything that still needs to be done?

It seems this was resolved in pull request [#499](https://github.com/nltk/nltk/pull/499).

**Comment by stevenbird** [comment]
Thanks, yes it's resolved.
