### ISSUE TITLE
pickling issues with NaiveBayesClassifier

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#514]
I haven't checked if this ticket is valid, but it was reported in nltk-users group that NaiveBayesClassifier doesn't work well with pickling: https://groups.google.com/forum/?fromgroups#!topic/nltk-users/vijtEvhzhOo

**Comment by AbhilashaRavichander** [comment]
Hey, I'm looking to contribute. Is anyone working on this?

**Comment by stevenbird** [comment]
Please take a look and submit a PR. No one is working on this AFAIK

**Comment by erip** [comment]
I think this is addressed in the Google Group: just need to change the pickling protocol when pickling.

**Comment by accraze** [comment]
yep looks like this works when setting the protocol to 1

```
pickle.dump(classifier, fModel,1) 
```

Is persisting this classifier something that should be added to `util.py`?

**Comment by alvations** [comment]
Is this issue still valid? Would using `dill` work?

**Comment by Dobatymo** [comment]
I have no problems using nltk 3.2.4, python 3.5 /  nltk 3.2.5, python 2.7

```python
>>> import nltk, pickle
>>> clf = nltk.NaiveBayesClassifier.train([({1: 2}, 1)])
>>> clf.classify({1: 2})
1
>>>
>>> s = pickle.dumps(clf)
>>> clf = pickle.loads(s)
>>> clf.classify({1: 2})
1
```

**Comment by alvations** [comment]
Thanks @Dobatymo! Yes, it looks like modern pickle works in python 2.7 and 3.6 as well =)
