### ISSUE TITLE
Code modernizing proposal: using `format` instead of `%`

### ISSUE THREAD

**Issue by stevenxxiu** [nltk/nltk#518]
Python's replaced `%` with `format` some time ago and `%` is now deprecated, so I think switching to `format` could be appropriate.

Some examples:

in nltk.util:

```
raise UnicodeError(
        'Unable to decode input data.  Tried the following encodings: %s.'
        % ', '.join([repr(enc) for enc in encodings if enc]))
```

will be changed to:

```
raise UnicodeError(
        'Unable to decode input data.  Tried the following encodings: {}.'.format(
        ', '.join([repr(enc) for enc in encodings if enc])))
```

another one:

```
'%s.%s' % (selfname, name)
```

will be changed to

```
'{}.{}'.format(selfname, name)
```

**Comment by nschneid** [comment]
Are we maintaining support for Python 2.6? If so, this will unfortunately [not work](http://docs.python.org/2/library/string.html#formatstrings)—an explicit index or name is required, like `'{0}.{1}'.format(selfname, name)`.

**Comment by stevenbird** [comment]
Yes let's continue to support Python 2.6 please.
In the case of repr, can we use the syntax `{0!r}`?

**Comment by stevenbird** [comment]
@jskda it would be good to see some more examples please, e.g. for formatting data from different sources such as dictionaries. We may not want to do the {0} {1} style of format conversion in all cases.

**Comment by kmike** [comment]
1) printf-style formatting is not deprecated; see e.g. docs - there is nothing about that in docs http://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting . There were plans to deprecate `%` formatting in early Python 3.x versions, but then this decision was reverted - `%` is not deprecated and it will stay.

2) `"%s" % ...` and `"{}".format(...)` is not only different syntax, they have different semantics in Python 2.x: printf-style string interpolation promotes binary format string to unicode if one of the arguments is unicode, while `.format()` decodes this unicode argument implicitly using `sys.getdefaultencoding()` in this case. So we can't just use search-replace for this change, it requires checking of what is happening in each case.

**Comment by jnothman** [comment]
The main argument for this change IMO is that `tpl % x` can have unexpected effects if `x` can sometimes be a tuple or a dict.

Yes, Steven, named substitutions are supported, e.g. `'{pre}.{suf}'.format(pre='foo', suf='bar')` or `tpl.format(**locals())`.

> `.format()` decodes this unicode argument implicitly using `sys.getdefaultencoding()` in this case. So we can't just use search-replace for this change, it requires checking of what is happening in each case.

Is this more nuanced than ensuring that wherever we might be working with unicode, we use a unicode template string.

**Comment by jnothman** [comment]
And I recall now that `format` may also perform nested item and attribute getting: `'{0[0].__class__.__name__}'.format(['a'])` will return 'str'.

**Comment by naoyak** [comment]
Should this have been closed by #1512?

**Comment by alvations** [comment]
There are still quite a lot that can be cleaned up for this issue.

Moving from the C-style `%s` , `%d`, `%f` the new [`print_function` from PEP 3105](https://www.python.org/dev/peps/pep-3105/) would be a good thing. 

E.g. 

```
~/git/nltk$ grep '%s' nltk/*
...
Binary file nltk/treeprettyprinter.pyc matches
nltk/treetransforms.py:                parentString = "%s<%s>" % (parentChar, "-".join(parent))
nltk/treetransforms.py:                        newHead = "%s%s<%s>%s" % (originalNode, childChar, "-".join(childNodes[i:min([i+horzMarkov,numChildren])]),parentString) # create new head
nltk/treetransforms.py:                        newHead = "%s%s<%s>%s" % (originalNode, childChar, "-".join(childNodes[max([numChildren-i-horzMarkov,0]):-i]),parentString)
Binary file nltk/treetransforms.pyc matches
grep: nltk/twitter: Is a directory
nltk/util.py:    print('%s supports the following operations:' % obj.__name__)
nltk/util.py:            name = '%s.%s' % (selfname, name)
nltk/util.py:        print(textwrap.fill('%s%s' % (name, argspec),
nltk/util.py:        'Unable to decode input data.  Tried the following encodings: %s.'
```

**Comment by alvations** [comment]
Using "f-strings" might be an alternative too https://www.python.org/dev/peps/pep-0498/ =)

**Comment by nschneid** [comment]
> Using "f-strings" might be an alternative too https://www.python.org/dev/peps/pep-0498/ =)

I fully support this if/when 2.7 support is dropped. Moving to `format()` for now will ease the transition to f-strings.

**Comment by rishabhkumar296** [comment]
Hi, I would like to work on this issue. Is it still open ?

**Comment by purificant** [comment]
There are about a thousand instances of string formatting using the `%s` notation across the codebase.

There are many opportunities to refactor, to either [format()](https://docs.python.org/3/library/stdtypes.html?highlight=format#str.format), or [f-string](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) perhaps using a polyfill, along the lines of https://github.com/asottile/future-fstrings

**Comment by abidahmadq** [comment]
Hello i am looking to contribute to this issue. This would be my first open source contribution. Can anyone explain what needs to be done regarding this issue?

**Comment by alvations** [comment]
@abid1998 if you would like to take up this issue, it's simple but tedious. Basically go to every file listed that contains `%s` and format the strings into f-strings or modern strings:

```
~/git/nltk$ grep '%s' nltk/**/* | cut -f1 -d":" | uniq
```

and 

```
~/git/nltk$ grep '%s' nltk/* | cut -f1 -d":" | uniq
```

P/S: There'll be tricky cases but most of it should be simple. 

Please take a look at https://github.com/nltk/nltk/blob/develop/CONTRIBUTING.md and create a pull-request whenever you're ready, we'll do a review to check through before finalizing a merge.

**Comment by kmike** [comment]
@alvations keep in mind though that f-strings can only be used if NLTK drops support for Python < 3.6. Also, if Python 2.7 is supported, you can't mechanically replace % formatting with .format, because they are not the same when unicode and str types are mixed (see https://github.com/nltk/nltk/issues/518#issuecomment-27180470).

**Comment by kmike** [comment]
I think it can be much easier to solve once Python 2.7 support is dropped; otherwise, there is a high risk of introducing Python 2 specific bugs.

**Comment by abidahmadq** [comment]
@stevenbird are there any plans to make this issue active ?
