### ISSUE TITLE
"import nltk" asks for x11

### ISSUE THREAD

**Issue by ayushjaiswal** [nltk/nltk#519]
On Mac OSX 10.9, import nltk asks for x11 to be installed. This requirement does not exist in the installation documentation. Is there a solution to this (apart from installing x11)?

**Comment by stevenbird** [comment]
This dependency is probably due to Tkinter, and it looks like you can avoid X11 if you install ActiveTcl: http://www.python.org/getit/mac/tcltk/

(I suggest staying away from Python 3.4 until it is clear that numpy is supported.)

**Comment by ayushjaiswal** [comment]
I have tried installing ActiveTcl but that doesn't help. It still asks me to install x11.

**Comment by aht** [comment]
@ayushjaiswal how did you overcome the issue? i'm running into the same problem.

**Comment by ajschumacher** [comment]
Me too! What's up with this?

**Comment by ayushjaiswal** [comment]
For me, it was not an NLTK problem as I had thought it to be. I had IPython installed on my system as well. By default, NLTK was getting installed under IPython, and was using IPython instead of Python. There might be some problem with the IPython libraries because when I removed IPython and reinstalled NLTK, it started working properly.

**Comment by aht** [comment]
This solved the issue for me http://stackoverflow.com/questions/13395409/nltk-without-x11-on-osx-epd-64bit-python

**Comment by ajschumacher** [comment]
Thanks! In the end @csojinb got it to work by uninstalling and then installing the latest Xquartz. Not sure how exactly that's related to nltk really, but the problem is functionally gone at least!

**Comment by hayd** [comment]
Surely this is a bug? (this should fail more gracefully)

**Comment by kmike** [comment]
Let's reopen this issue! @ayushjaiswal resolved his issue, but this shouldn't have failed in first place.
It'll be great if someone who has this problem debug it further and maybe submit a PR to fix it.

**Comment by stevenbird** [comment]
@kmike: do you think this is an issue with NLTK?
