### ISSUE TITLE
iterators in compat.py

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#526]
I think the following functions in compat.py don't belong for Python 3: iterkeys, itervalues, iteritems.

**Comment by stevenxxiu** [comment]
@stevenbird: I think they might be there for python 2 compatibility, as `_iterkeys` is assigned different values depending on python 2 and 3. As per my understanding in python 3, `keys()` returns an iterator like object, while in python 2 it returns a list.

**Comment by stevenbird** [comment]
@jskda yes I see, thanks.
