### ISSUE TITLE
named tuples

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#530]
I would like to consider switching from tuples to namedtuples for certain NLTK data types, such as tagged tokens, and the tuples used for storing dependency trees, and perhaps elsewhere as well. Programs could refer to attributes such as tokens, tags, heads, etc by name instead of position.

E.g. "count the frequency of all words tagged NN":

The first two require knowledge of the order of items in the tagged token:

FreqDist(token for token, tag in tagged_words if tag == 'NN')
FreqDist(tw[0] for tw in tagged_words if tw[1] == 'NN')

I think this is more transparent:

FreqDist(tw.token for tw in tagged_words if tw.tag == 'NN')

Comments welcome.

**Comment by kmike** [comment]
+1 for returning namedtuples where they are not nested.

There is one possible issue with namedtuples - their repr is quite verbose, so instead of `[('dog', 'NN')]` you'll get `[TaggedToken(token='dog', tag='NN')]`; this gets worse if namedtuples contain other namedtuples, because pprint doesn't work in this case and you can only get a long single-line string.

**Comment by heatherleaf** [comment]
+1

**Comment by nschneid** [comment]
I like the goal but share @kmike's concern about printing, because that would make it harder to inspect (say) a tagged sentence. Is it worth creating a namedtuple subclass that is less verbose, e.g. 

``` python
[(tkn='The', tag='DT'), (tkn='quick', tag='JJ'), (tkn='brown', tag='JJ'), (tkn='fox', tag='NN'), ...]
```

as opposed to

``` python
[TaggedToken(token='The', tag='DT'), TaggedToken(token='quick', tag='JJ'), ...]
```

**Comment by heatherleaf** [comment]
I think we should try to follow the standard Python idioms. So no special-made namedtuple subclasses.

Yes, this will mean more verbose printing, but people should use a pretty-printer for tagged sentences anyway.

**Comment by stevenbird** [comment]
@jskda would you please create a named tuple for (token, tag) tuples, called TaggedToken. Let's see what it looks like, and then consider doing it in other cases.

**Comment by stevenxxiu** [comment]
Here's a direct implementation & a subclass implementation (works with str but not pprint):

```
from collections import namedtuple

>>> TaggedToken = namedtuple('TaggedToken', ('token', 'tag'))
>>> TaggedToken('dog', 'NN')
... TaggedToken(token='dog', tag='NN')

>>> class TaggedToken(namedtuple('TaggedToken', ('token', 'tag'))):
...     def __str__(self):
...         return '({0}, {1})'.format(self.token, self.tag)

>>> str(TaggedToken('dog', 'NN'))
... '(dog, NN)'
```

**Comment by jnothman** [comment]
You might want to stick a `__slots__ = ()` to reduce the memory consumption in your subclass implementation.

PS: iirc, a mechanism to extend `pprint` (et al.) for custom types is among the latest changes to Python...

**Comment by stevenbird** [comment]
I'd like to postpone this for consideration for version 3.1, so we can finalize 3.0 without further delay
