### ISSUE TITLE
Corpus reader docstrings

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#532]
Accessing corpus reader docstrings gives different results before and after the corpus reader has been used the first time. On first use, we see the LazyCorpusLoader docstring, which is not helpful for users. Only the relevant corpus reader docstring should be shown.

> > > from nltk.corpus import brown
> > > help(brown)
> > > Help on LazyCorpusLoader in module nltk.corpus.util object:
> > > brown = class LazyCorpusLoader(builtins.object)
> > >  |  A proxy object which is used to stand in for a corpus object
> > >  |  before the corpus is loaded.  This allows NLTK to create an object
> > > 
> > > brown.words()
> > > ['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]
> > > 
> > > help(brown)
> > > Help on CategorizedTaggedCorpusReader in module nltk.corpus.reader.tagged object:
> > > class CategorizedTaggedCorpusReader(nltk.corpus.reader.api.CategorizedCorpusReader, TaggedCorpusReader)

**Comment by stevenbird** [comment]
The docstring for the LazyCorpusLoader should state, near the top, that user documentation can be viewed once the corpus is loaded, e.g. using `corpus.words()`, then typing `help(corpus)` again.

**Comment by kmike** [comment]
Can't we just assign proper `__doc__`? LazyCorpusLoader already knows it because corpus class is passed to `__init__` and accessing its `__doc__` doesn't require creating corpus instance.

**Comment by stevenxxiu** [comment]
@stevenbird I think `LazyCorpusLoader` already has some documentation regarding this:

> To see the API documentation for this lazily loaded corpus, first run corpus.ensure_loaded(), and then run help(this_corpus)

I'll add the `corpus.words()` example.

@kmike: I've created a function here to assign `__doc__`, however `help()` still returns different results as it can't see the methods for the actual class, I don't know of a way to achieve that.

```
#to use this, just replace LazyCorpusLoader with create_lazy_corpus_loader
def create_lazy_corpus_loader(name, reader_cls, *args, **kwargs):
    lazy_name = 'Lazy' + reader_cls.__name__
    lazy_dict = dict(LazyCorpusLoader.__dict__)
    lazy_dict['__doc__'] = reader_cls.__doc__
    return type(lazy_name, (LazyCorpusLoader,) + LazyCorpusLoader.__bases__, lazy_dict)\
        (name, reader_cls, *args, **kwargs)
```
