### ISSUE TITLE
math domain error with TrigramAssocMeasures

### ISSUE THREAD

**Issue by japerk** [nltk/nltk#537]
In nltk 3.0a3, TrigramAssocMeasures._contingency can produce a negative number, and you can't do math.log with a negative number. Here's code to reproduce:

> > > from nltk.collocations import TrigramCollocationFinder
> > > from nltk.metrics import TrigramAssocMeasures
> > > words = [w.lower() for w in webtext.words('singles.txt')]
> > > tcf = TrigramCollocationFinder.from_words(words)
> > > tcf.nbest(TrigramAssocMeasures.likelihood_ratio, 4)

The _contingency numbers in this case are (26, 2, 0, 0, 0, -2, 0, 4841) and the -2 is the cause of the failure.

**Comment by japerk** [comment]
Code works fine with nltk2. When I compared the _contingency method code in both version, it appears to be only syntactically different, so the error could be in TrigramCollocationFinder.

**Comment by iandanforth-alation** [comment]
@alvations I also encountered this going from nltk2 to 3.4.4
