### ISSUE TITLE
Eliminate yaml dependency

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#540]
Use json or pickle instead of yaml for serialisation, to remove the yaml dependency in favour of the built-in libraries. This effects a couple of tagger modules, and data.py and yamltags.py.

**Comment by stevenbird** [comment]
We need to decide which of pickle or json to use.

**Comment by kmike** [comment]
Big +1 for removing YAML dependency.

### JSON

Pros:
- there is no security risk in using json;
- compatibility is not an issue;

Cons:
- it'll require more code than pickle.

### Pickle

Pros:
- pickle support means multiprocessing support;
- less code to write.

Cons:
- there are different pickle protocols;
- pickling/unpickling is different in Python 2/3;
- pickled models disallow changing/moving classes, attributes, etc. - they require the same code to present at unpickling time;
- unpickling allows arbitrary code execution;
- pickled data is not readable without Python.

I vote for JSON even though it is more work.

**Comment by heatherleaf** [comment]
Also +1 for JSON

**Comment by turicas** [comment]
The idea is to remove all YAML support (like not being able to use `nltk.data.load` with a YAML file) or just remove from the official data distribution?

Curently the list of files that have `yaml` in its contents is:
- `ChangeLog`
- `nltk/data.py`
- `nltk/__init__.py`
- `nltk/tag/brill.py`
- `nltk/tag/sequential.py`
- `nltk/test/data.doctest`
- `nltk/yamltags.py`
- `pip-req.txt`
- `setup.py`
- `web/install.rst`

Can you provide more information about which files need to be changed and which not?

**Comment by stevenbird** [comment]
It would be fine to leave yaml support in data.py, and data.py works fine even when yaml is not installed. However, I think yaml can be replaced everywhere else.

**Comment by stevenxxiu** [comment]
Should the classes using yaml have any backwards compatibility for yaml files? I don't think any yaml files exist in the nltk data packages.

**Comment by stevenbird** [comment]
No, we will give up backwards compatibility. We'll just retain yaml support in data.py in case someone wants to use it to load their own yaml files using the data loader.

**Comment by kmike** [comment]
If yaml files don't exist in nltk data packages then we can live without json serialization. Pickle support is still desired because users may want to save models using pickle, and because it is needed for multiprocessing to work. Most of pickle disadvantages doesn't matter if it is user who creates a model and saves it.

**Comment by heatherleaf** [comment]
@kmike I don't understand: Do you mean that we should remove json serialization even when it's implemented? The reason for giving up on yaml is that it's not a standard library, but that's not a problem for json or pickle.

**Comment by kmike** [comment]
I think that json serialization is useful, but not mandatory. Pickle support is much easier to implement and it allows parallelizing code via multiprocessing. Pickle downsides are less important if it is user who creates and saves models.

**Comment by heatherleaf** [comment]
Ok, so your suggestion is that all classes (that needs serialisation) use pickling for saving and loading. But they may additionally implement json serialisation if they want to. Sounds fine to me.

**Comment by kmike** [comment]
Yes, exactly. 

It is still better to use json instead of pickle for data available via nltk.download.
