### ISSUE TITLE
Create a from-scratch documentation about installation

### ISSUE THREAD

**Issue by turicas** [nltk/nltk#541]
If you're in a developer's machine that have everything related to compilers, header files for FORTRAN libraries and such things, `pip install nltk` will work. But unfortunately this is not the case of the majority of (possible) NLTK users.
So, installing NLTK even on Debian-based system is not that easy as [NLTK's doc](http://nltk.org/install.html) says. We need to document the whole process of installation (including things like GCC, BLAS and LAPAC to compile numpy successfully).

**Comment by stevenbird** [comment]
Superseded by https://github.com/nltk/nltk/issues/609
