### ISSUE TITLE
Create a Dockerfile

### ISSUE THREAD

**Issue by turicas** [nltk/nltk#542]
[Docker](http://docker.io) is a software to create and administrate LXC (Linux Containers) easily. With it (and its [Dockerfile](https://www.docker.io/learn/dockerfile/level1/)) we can easily share how to build new container images in a portable way.
Since NLTK depends on numpy, scipy and matplotlib and the process of installing it is really complicated (because depends on headers files, C compiler, FORTRAN compiler and lots of libraries that needs to be installed by the system package manager, not by pip), it'll be easier for beginners to install NLTK on a container (to use it, deploy to production, or use as a development environment to run tests).
The process of creating a Dockerfile will also help to document dependencies and the installation process (related to #541).

**Comment by dimazest** [comment]
On a related note, I've came up with a salt configuration [1], that is supposed to install required software and datasets. The nice point, is that it might be used inside a vagrant instance, docker or any other setup.

[1] https://github.com/dimazest/nltk/tree/vagrant/salt

**Comment by alvations** [comment]
3+ years on... [Anaconda](http://anaconda.org) has done the job of nicely packaging the scientific computing tools/libraries for Python and the new `pip` install instructions should be easy enough =)

**Comment by dimazest** [comment]
I agree, anaconda works universally for me on Linux and Mac.
