### ISSUE TITLE
Method for finding senna executable in senna.py should be improved

### ISSUE THREAD

**Issue by ewan-klein** [nltk/nltk#543]
Code which wraps a 3rd party executable should adopt common methods for locating the executable. Existing wrappers for prover9/mace, malt parser, mallet etc. do a reasonably intelligent (though not optimal) job of doing this. senna.py has a hard-wired path which won't work for people on Windows or who don't have root access.

**Comment by stevenbird** [comment]
Senna.py should probably use `internals.find_binary`

**Comment by stevenbird** [comment]
We can check an environment variable `SENNA`. Also need to update the wiki instructions: https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software

**Comment by stevenbird** [comment]
Some issues with Senna are showing up on the [CI server](https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py26-jenkins/lastCompletedBuild/testReport/)

**Comment by stevenbird** [comment]
Previously, Senna was not installed on the CI server, and so the doctest was being skipped. @longdt219 modified jenkins.sh to download Senna.
