### ISSUE TITLE
RegexpTokenizer introduces extra splits because of grouping parentheses removal

### ISSUE THREAD

**Issue by alexpolozov** [nltk/nltk#545]
### Test case

``` python
>>> from nltk.tokenize.regexp import regexp_tokenize
>>> pat = r'[()]+'
>>> s = '(abc:def)(ghi:jhk)'
>>> regexp_tokenize(s, pat, gaps=True)
['abc', 'def', 'ghi', 'jhk']
```
### Expected output

``` python
['abc:def', 'ghi:jhk']
```
### Reason

NLTK performs automatic conversion of capturing groups into non-capturing in the `RegexpTokenizer` constructor. It does so by converting every non-escaped `(` to `(?:`. However, [regexp syntax](http://www.regular-expressions.info/charclass.html) states that any character inside a character class `[]` (except for `^`, `\`, `]`, and `-`) will be treated verbatim. Therefore, we don't have to escape `(` inside a character class, but NLTK doesn't account for this in the [convert_regexp_to_nongrouping](https://github.com/nltk/nltk/blob/master/nltk/internals.py#L61-66) function. Consequently, it introduces extra `?:` inside my character class, and breaks the entire regex.
### Why is it important

When I want to tokenize text with URLs, which, naturally, have colons and question marks in them, `regexp_tokenize` erroneously breaks an URL into three parts:

``` python
>>> s = "Please read [a reference](https://www.google.com/search?q=regexp+syntax+reference) and don't parse regexes with regexes %)"
>>> pat = r"[][\s()]+"
>>> regexp_tokenize(s, pat, gaps=True)
['Please', 'read', 'a', 'reference', 'https', '//www.google.com/search', 'q=regexp+syntax+reference', 'and', "don't", 'parse', 'regexes', 'with', 'regexes', '%']
```

**Comment by jnothman** [comment]
Perhaps adding `\[[^\]]*\(   |` to the expression would suffice?
