### ISSUE TITLE
nltk_data python package

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#55]
Create a new Python package trunk/nltk/nltk_data, containing modules for
building the models that get distributed from trunk/nltk_data.  This will
make it possible to rebuild models when the associated code is changed. 
Users will also be able to see how the models were trained, and be able to
modify the parameters if necessary.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=301</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2009-02-20T07:25:23.000Z:</strong></p>
<p>I've done this for a new tagsets package.
</p><p><strong>edloper said, at 2009-02-20T18:22:40.000Z:</strong></p>
<p>This seems like a good approach; I'll migrate the code that trains some of the
existing models to this directory.

Some of that code depends on having access to corpora that aren't distributed with
NLTK.  E.g., currently named_entity.py has the very ugly path
"/tmp/ace.old/data/ace.dev/text" hard-coded into it.  I propose that we use
"/usr/share/corpora" as a standard location for corpora that are needed to train the
models, but which we don't distribute with them (such as the ACE corpus, or the
complete treebank).
</p><p><strong>StevenBird1 said, at 2009-02-20T21:48:34.000Z:</strong></p>
<p>"/usr/share/corpora" as the standard place for non-distributed corpora sounds fine.

On the output side, we might want to package up the output files, and have a Makefile
that puts them in the right place in the working copy (cf the "publish" directives in
doc/Makefile).
</p>

**Comment by kmike** [comment]
FYI: there is a limit on maximum pypi distribution size (currently 40MB; it was recently raised from 20MB).

**Comment by turicas** [comment]
What if we create a new package inside `nltk` package? There's a way to do it with setuptools, like [zc.buildout](http://pypi.python.org/pypi/zc.buildout) does. It can be called `nltk.data`. If you install `nltk` you'll get only the code. If you install `nltk.data` it'll require `nltk` and you'll have code + data.

**Comment by kmike** [comment]
It may be very hard to have pip-installable `nltk.data` package because nltk.**init** is not empty (and I don't see practical advantages over the `nltk_data` name). The point is that a single `nltk_data` package will exceed pypi limits.

**Comment by kmike** [comment]
... and https://github.com/nltk/nltk/blob/master/nltk/data.py :)

**Comment by stevenbird** [comment]
This is a great idea but we don't have resources to do it anytime soon, so I'm closing it.
