### ISSUE TITLE
delete 2and3 branch

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#553]
Is everyone ok with that? It causes confusion, see e.g. https://github.com/nltk/nltk/pull/548

**Comment by heatherleaf** [comment]
+1, as well as branches `py25` and `nltk-py3k`

and `fdist`, now that it's merged into master

**Comment by stevenbird** [comment]
+1

**Comment by heatherleaf** [comment]
Could someone please do this? I can't, because I don't have write permission on the main repo.

**Comment by stevenbird** [comment]
This is done. You may need to delete your own local copy of the branch with: git branch -d 2and3

**Comment by heatherleaf** [comment]
Oh sorry, I missed that. But the branch `py25` is still there.

**Comment by stevenbird** [comment]
Yes, the `py25` branch is meant to still be there. It's the version of NLTK that works with Python 2.5, for any bugfixes or essential backports.
