### ISSUE TITLE
Stanford tokenizer

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#558]
Add support for Stanford tokenizer: http://nlp.stanford.edu/downloads/tokenizer.shtml

**Comment by stevenxxiu** [comment]
Should I implement `span_tokenize`? I can't find a way to do this directly on the commandline using `edu.stanford.nlp.process.PTBTokenizer`, so I'll need to add some java code.

**Comment by stevenbird** [comment]
No, this is too low priority.
