### ISSUE TITLE
rst xref warnings

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#56]
rst processing should display a warning when a numbered item (example,
pylisting, figure, table) is not referenced from within the file.  An
approximation would be to find all such items having a manually-defined
symbolic id such as ex-foo or fig-bah, and make sure that this is cited
from within the file.  Note that chapter-external references are irrelevant.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=304</p>

**Comment by stevenbird** [comment]
This is a great idea but we don't have resources to do it anytime soon, so I'm closing it.
