### ISSUE TITLE
batch*

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#561]
Revisit method names containing "batch", e.g. "batch_tag". Is there a more natural name for something which is applied to a sequence. Should we just use map?

**Comment by jnothman** [comment]
I can't tell if "should we just use map" is a question of naming, or whether we should suggest that users just use map. If you mean the latter:
- How often is there substantial startup cost for which `batch_` avoids repetition? This seems the case in a lot of external tool wrappers and some other ML models. So in those cases, asking the user to use `map` is not really an option.
- Should batch instead be the default? Is it often possible to detect that the input is a singular or many?

And if we are to change their name, I suggest `*_many`. Or else make it explicit with `*_sentence`, `*_sentences`, etc.

**Comment by stevenbird** [comment]
I propose not to recommend use of map in place of the batch methods given the possible start-up cost (either in the existing implementation, or else in future implementations). I also propose not to introduce polymorphism. I used `*_sents`, following the naming in the corpus reader methods, except in the classify package where I used `*_many`.

**Comment by stevenbird** [comment]
Any objections to merging https://github.com/nltk/nltk/pull/613?
