### ISSUE TITLE
cannot download some packages

### ISSUE THREAD

**Issue by slcott** [nltk/nltk#565]
Some of the packages are taking a **very long time** to download, i.e. not at all so far for me. Using `>>>nltk.download_shell()` I am currently unable to successfully download package `jeita`. This is really disappointing for me as I have been working my way through the online book.

**Comment by sloria** [comment]
I am having this same problem. Travis-CI has been timing out when trying to download brown and punkt: https://travis-ci.org/sloria/TextBlob/jobs/15500090

**Comment by pedropregueiro** [comment]
I have the same issue downloading wordnet. Running "python -m nltk.downloader -e -d /usr/share/nltk_data wordnet" hangs forever like this:

[nltk_data] Downloading package 'wordnet' to /usr/share/nltk_data...

I noticed that the /usr/share/nltk_data/corpora/wordnet.zip file grows, but then it stalls around 5Mb.

**Comment by stevenbird** [comment]
I'm not able to replicate these problems. @slcott can you show that this is not just a problem with network latency? @sloria can you specify a longer timeout in Travis-CI?

**Comment by slcott** [comment]
I have been able to successfully download all the packages, etc. However, it required repetitive download calls before it was successful. I know for a fact that my internet speed is excellent here (I'm in the Washington DC metro area). It seemed like the server was the bottleneck.

**Comment by pedropregueiro** [comment]
@stevenbird I keep bumping into the same problem. I'm trying to do this from an amazon EC2 instance (oregon - c3.large), not sure if that might matter for some reason.

**Comment by alanshutko** [comment]
I'm experiencing the same problem just downloading via curl or a web browser, on Windows XP and OS X on two separate networks.  About 2MB of a file will be sent from the server, then the server stops transmitting until the client times out.

**Comment by stevenbird** [comment]
Referred to nltk-dev for replication/diagnosis: https://groups.google.com/forum/#!topic/nltk-dev/rdigDIJk6-o

**Comment by alexrudnick** [comment]
I've had similar problems recently, though not every time. This is even on a fast university connection, with no NAT. Not sure how to diagnose it...

**Comment by kmike** [comment]
Where is nltk data served from (the index itself and the data)? Is it stored on github pages?

**Comment by stevenxxiu** [comment]
From what I can see, the downloader parses and uses the url's on the index page which defaults to the github page: `http://nltk.github.com/nltk_data/`. The data is then downloaded directly from the github repository, for example the first package on the index page: `http://nltk.github.com/nltk_data/packages/chunkers/maxent_ne_chunker.zip`

**Comment by kmike** [comment]
could it be related?

```
> curl http://nltk.github.com/nltk_data/packages/chunkers/maxent_ne_chunker.zip
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

**Comment by kmike** [comment]
```
> nslookup nltk.org
Server:         10.0.1.1
Address:        10.0.1.1#53

Non-authoritative answer:
Name:   nltk.org
Address: 204.232.175.78

> nslookup nltk.github.com
Server:         10.0.1.1
Address:        10.0.1.1#53

Non-authoritative answer:
nltk.github.com canonical name = github.map.fastly.net.
Name:   github.map.fastly.net
Address: 185.31.17.133
```

It looks like they are different servers, and NLTK data is not served from Github, it is served from Steven's server.

**Comment by kmike** [comment]
@stevenbird - can you confirm this? If so, what do you think about switching to github pages for serving data?

**Comment by stevenbird** [comment]
It's served from the github pages branch of the nltk_data repository: https://github.com/nltk/nltk_data/tree/gh-pages, which shows up here: http://nltk.github.com/nltk_data

**Comment by kmike** [comment]
Right, but nltk.github.com returns 301 Moved Permanently response and directs client to nltk.org which is hosted on an another server. So it seems that github pages serve only 301 redirects for us.

**Comment by kmike** [comment]
Could you check server logs to confirm this?

**Comment by janstrunk** [comment]
I was also contacted by someone who wasn't able to download the Punkt models from ntlk_data. I managed to finally download the file using a download manager. So downloads do seem to work, albeit very slowly and with interruptions.

**Comment by lliobh** [comment]
I also had a lot of trouble downloading NLTK data using the downloader and downloading from http://nltk.github.com/nltk_data.  However, clicking on Download ZIP on https://github.com/nltk/nltk_data/tree/gh-pages I got everything in one go and quickly.  Strange.

**Comment by stevenbird** [comment]
Do we need to think about relocating the data collection? One option is the Language Commons, though uploading things there is a manual process. https://archive.org/details/LanguageCommons

**Comment by kmike** [comment]
The issue is DNS/repo setup, not github pages reliability, because we're not serving files from github CDN. I don't know the current setup, but here are some docs: https://help.github.com/articles/setting-up-a-custom-domain-with-pages#setting-up-dns

nltk.org is not served from github CDN; it seems there is no CNAME record for nltk.org pointing to nltk.github.io. You were right that nltk.org is served from github pages, but I think it is set up like the following: A record of nltk.org domain points to an old IP of pages.github.com. Docs says that using A records doesn't give benefits of CDN.

If we use github pages then requirements are IMHO the following:
- http://nltk.org/nltk_data/ should remain available because old NLTK versions use it;
- data from the index should be served from CDN.

I haven't wrapped my head around how to setup this yet, but it should be possible :)

**Comment by stevenxxiu** [comment]
@kmike: what do you think about using godaddy's domain forwarding service http://support.godaddy.com/help/article/422/forwarding-or-masking-your-domain-name for the root domain to forward everything to www.nltk.org (I think nltk.org is registered with godaddy)?

But I'm not sure however how well old nltk versions handle http redirects, so maybe it's a better option to just use an A record for the root domain and cname records for the subdomains which hosts the zip files, as github seems to be able to serve `http://nltk.org/nltk_data/` reliably enough.

**Comment by stevenbird** [comment]
I've changed the IP address of the A record. This isn't the recommended solution since it doesn't let us benefit from GitHub's load balancing, but it may be better than before.

**Comment by kmike** [comment]
@jskda I think your idea is good. Downloader uses urllib2.urlopen, and this function handles 301 redirects, so older NLTK versions should be fine. We may add nltk_data repo as a git submodule of nltk.org repo or create an another subdomain for it (like data.nltk.org) and change the index accordingly.

When adding redirects special attention is needed for 2 points:

1) "masking" feature of godaddy seems to use iframes, so it is not what we want; plain http redirect is better;
2) we need to make sure that nltk.org/path is redirected to www.nltk.org/path

**Comment by stevenxxiu** [comment]
I just had an online chat with godaddy support and it seems that they support forwarding without iframes, but only to a fixed url.
But I think github pages support redirecting urls to the www subdomain with relative paths if the CNAME file inside the repository points to the www subdomain.

**Comment by stevenbird** [comment]
I've modified the domain hosting configuration. I think the issue is resolved. Any problem still?

**Comment by kmike** [comment]
Downloading works well for me now. Some packages (brown and sample_grammars) are marked "out of date" and re-downloading them doesn't help, but that looks like an unrelated issue. 

/cc @sloria @pedropregueiro @slcott @alanshutko @janstrunk @lliobh @larsmans does downloading work for you?

**Comment by kmike** [comment]
@stevenbird thanks!

**Comment by sangheestyle** [comment]
@stevenbird It works for me also. Thanks!

**Comment by stevenbird** [comment]
Thanks to everyone for testing this out. @kmike I can't replicate the problem you reported with out-of-date packages.
