### ISSUE TITLE
wordnet functions and Python 3.4b1

### ISSUE THREAD

**Issue by ghost** [nltk/nltk#566]
Hi,

I'm testing the latest Python 3.4b1 version and I found a strange behavior with the wordnet functions, like _lemma_names_:

In Python3.3 this code works fine:

``` python
>>> from nltk.corpus import wordnet as wn
>>> print(wn.synset("car.n.01").lemma_names)
['car', 'auto', 'automobile', 'machine', 'motorcar']
```

Whereas Python3.4 outputs:

``` python
>>> from nltk.corpus import wordnet as wn
>>> print(wn.synset("car.n.01").lemma_names)
<bound method Synset.lemma_names of Synset('car.n.01')>
```

One "workaround" is to use _lemma_names()_ In Python 3.4b1:

``` python
>>> print(wn.synset("car.n.01").lemma_names())
['car', 'auto', 'automobile', 'machine', 'motorcar']
```

But this code is _not_ working under Python 3.3:

``` python
>>> print(wn.synset("car.n.01").lemma_names())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'list' object is not callable
```

Any ideas? I thought that could be relevant for the ongoing nltk development.

**Comment by kmike** [comment]
Are you sure you're using the same NLTK version in both Pythons? The interface has changed not a long time ago (see https://github.com/stevenbird/nltk/commit/ba8ab7e23ea2b8d61029484098fd62d5986acd9c).

**Comment by ghost** [comment]
Thanks for that hint! I used nltk-3.0a2 in combination with Python3.3.

**Comment by kmike** [comment]
Thanks for checking that!
