### ISSUE TITLE
Installation instructions for optional dependencies

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#569]
@jskda would you please add a new section to `nltk/web/install.rst` and start adding instructions for optional dependencies?

I would like to avoid problems such as the following, when a user downloaded the wrong version: https://groups.google.com/forum/#!topic/nltk-users/n4EVbLzuHO0

**Comment by stevenbird** [comment]
Another case: https://groups.google.com/forum/#!topic/nltk-users/L49GXgBAAF8

**Comment by stevenxxiu** [comment]
For boxer, I'm getting an error `candc:models:required option argument is undefined` running `echo 'Every man runs' | bin/candc --models models/boxer --candc-printer boxer` for both the latest c&c and the prebuilt v1.00. Does anyone have this working?

**Comment by stevenbird** [comment]
Please put the instructions at https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software

**Comment by stevenbird** [comment]
@dhgarrette are you able to replicate the problem reported by @jskda above please? We are not able to test the boxer interface. Thanks.

**Comment by wazzzy** [comment]
Installing C&C from subversion is also not helping....
