### ISSUE TITLE
Installing dependencies for integration testing

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#572]
Integration testing at https://jenkins.shiningpanda.com/nltk/job/NLTK-TOX/ depends on dependencies being installed. How are Java dependencies handled, so that inline doctests are passed? Update to support testing of the Stanford tools.

**Comment by stevenxxiu** [comment]
I've added some dependency installation code to jenkins.sh and some environment variables for tox on this branch: https://github.com/jskda/nltk/tree/pull_request.stanford_jenkins

**Comment by stevenbird** [comment]
Merged in https://github.com/nltk/nltk/commit/e037b2c27b0d8345e268b977d519a74a69bbdc23. Let's watch the CI site to make sure things behave as expected.
