### ISSUE TITLE
Use unicode.org/udhr database so that UDHR files are uniformly encoded and accessible

### ISSUE THREAD

**Issue by amundo** [nltk/nltk#592]
There is a version of the Universal Declaration of Human Rights on unicode.org which is uniformly encoded in UTF-8. This would greatly simplify the difficulties involved with looking up translations of the text in a given language. 

> http://unicode.org/udhr/

There are bulk downloads available on this page:

> http://unicode.org/udhr/downloads.html

One of which is a zip file with .txt versions of the whole database. 

The documentation of the current nltk/corpus/reader/udhr.py states that certain languages are not available because Python can’t handle those encodings; using the unicode.org corpus would alleviate this problem.

(There is an accompanying `index.xml` which maps language codes to both file names and language names. )

**Comment by kmike** [comment]
I believe there is already a corpus reader for full unicode version of UDHR, and the data is uploaded to nltk data; corpus reader is called nltk.corpus.udhr2.

**Comment by amundo** [comment]
Thank you, I'm sorry that I didn't see #84. 
I’ll see if I can get the patch to work in my distribution.

**Comment by amundo** [comment]
In case anyone runs across this thread wondering how to get udhr2 to work without patching their nltk installation, the following seems to have worked for me:

First download the `udhr2` corpus if you don't have it, using `nltk.download()` or `nltk.download_gui()`. 
Once it’s been downloaded, I think you can just do this as a quick & dirty way to get udhr2 working:

```
from nltk.corpus import LazyCorpusLoader, PlaintextCorpusReader
udhr2 = LazyCorpusLoader( 'udhr2', PlaintextCorpusReader, r'.*\.txt', encoding='utf8')
```

Then `udhr2` should work more or less like `nltk.corpus.udhr`.
Corrections/better suggestions welcome!
