### ISSUE TITLE
Does NLTK support coreference?

### ISSUE THREAD

**Issue by architagr-cs** [nltk/nltk#595]
Hi,

Does NLTK support coreference resolution and if yes how can I use it. I tried to google it but wasn't able to find anything relevant. What I want to do is to replace a pronoun in a sentence with its antecedent. For e.g "Ram bought a mobile. Now he wants to sell it."

What I want to do in the above sentence is to replace 'he' in the second sentence with 'Ram'. Can this be done?

**Comment by cayorodriguez** [comment]
You should address this issues to the following google group: nltk-users

**Comment by architagr-cs** [comment]
ok cayorodriguez

Thanks, will do that.
