### ISSUE TITLE
List of API changes

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#598]
Identify NLTK's API changes since 2.0.4, in list format, e.g.:
- `util.clean_html()` (dropped, use BeautifulSoup instead)
- `corpus.reader.wordnet.Synset.definition -> definition()`

This will help users port their nltk2 code to nltk3.

**Comment by stevenbird** [comment]
Try using introspection to enumerate all names in NLTK 2.0.4 and 3.0alpha, then sort and use diff or comm.

**Comment by stevenbird** [comment]
Please add them to the wiki page at https://github.com/nltk/nltk/wiki/Porting-your-code-to-NLTK-3.0

**Comment by stevenxxiu** [comment]
I've made a diff using `comm` and now have added everything from the diff results into the wiki.

**Comment by stevenbird** [comment]
I've also added the changes due to https://github.com/nltk/nltk/issues/561. That just leaves https://github.com/nltk/nltk/issues/614.
