### ISSUE TITLE
Treebank Tokenizer buggy

### ISSUE THREAD

**Issue by desilinguist** [nltk/nltk#6]
The NLTK TreebankWordTokenizer appears to have at least two bugs in it: 

(a) It doesn't properly handle sentences with quotes at the end. 

```
 Input:
``If we don't have any further suggestions as to how we should present our case, we should be able to finish this.''

Output:
['`', '`', 'If', 'we', 'do', "n't", 'have', 'any', 'further', 'suggestions', 'as', 'to', 'how', 'we', 'should', 'present', 'our', 'case', ',', 'we', 'should', 'be', 'able', 'to', 'finish', "this.''"]
```

(b) According to the official Penn Treebank Tokenization page at http://www.cis.upenn.edu/~treebank/tokenization.html, double quotes (") should be changed to doubled single forward- and backward- quotes (`` and ''). However, nltk.word_tokenize() (TreebankTokenizer) does not follow this rule. 

```
Input: 
He went to the "Concert for Hope" yesterday.

Output: 
['He',  'went',  'to',  'the',  '"',  'Concert',  'for',  'Hope',  '"',  'yesterday', '.']
```

One of my colleagues, Michael Heilman, took the official Penn Treebank sed script (http://www.cis.upenn.edu/~treebank/tokenizer.sed) and ported it to NLTK using the Tokenizer API. It can be found here: https://gist.github.com/1506443

This script should replicate the sed script and, therefore, should not have either of these issues.

**Comment by stevenbird** [comment]
In this version, CONTRACTIONS2 requires tokens to be space separated, when \b should be used instead (as in the existing implementation).  Thus, it breaks in cases like this:

"This cannot cannot be right!" --> "This can not cannot be right !"
"This   cannot  work." --> "This    cannot  work ."

**Comment by stevenbird** [comment]
Resolved in
https://github.com/nltk/nltk/commit/e660a6827d44e242b4114abba7fc30fef6b0125c

**Comment by desilinguist** [comment]
Thanks steven!
- Nitin

**Comment by aboSamoor** [comment]
In case of numbers that are written in the financial format like 2,700 the current tokenizer split the number to three tokens. That is actually does not comply with the treebank corpus. Moreover, it does not seem reasonable as it changes the meaning of the text.
Here is the output of my personal benchmark for tokenizers.
https://gist.github.com/1748164

**Comment by PanderMusubi** [comment]
Master at the moment results in

```
>>> nltk.word_tokenize('He went to the "Concert for Hope" yesterday.')
['He', 'went', 'to', 'the', '``', 'Concert', 'for', 'Hope', "''", 'yesterday', '.']
>>> nltk.word_tokenize("``If we don't have any further suggestions as to how we should present our case, we should be able to finish this.''")
['``', 'If', 'we', 'do', "n't", 'have', 'any', 'further', 'suggestions', 'as', 'to', 'how', 'we', 'should', 'present', 'our', 'case', ',', 'we', 'should', 'be', 'able', 'to', 'finish', 'this', '.', "''"]
```
