### ISSUE TITLE
Don't use SimpleGoodTuring as a default for NgramModel

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#603]
See https://github.com/nltk/nltk/issues/602#issuecomment-34762070 for motivation. Since this change is backwards-incompatible I think it is better to fix it before NLTK 3 is released.

**Comment by iliakur** [comment]
@stevenbird I think we can close this because the new language model module doesn't really have a "default" model and the underlying problem with SGT can be tracked in #602.
