### ISSUE TITLE
_iter methods by default

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#614]
In the case of any methods having non-iterator and iterator versions, we should drop the non-iterator version, and rename the iterator version (dropping `_iter`).

**Comment by kmike** [comment]
See also: https://github.com/nltk/nltk/issues/509

**Comment by stevenbird** [comment]
@kmike thanks for the pointer; I've collapsed the distinction between `parse` and `parse_iter` in this pull request, and chosen iterator behaviour as the default, though in most cases (but not all), there is no efficiency benefit. I need to look at the cases which produce parse trees incrementally to decide whether this is the best approach overall, or whether I should get `parse` to return a list.

**Comment by stevenbird** [comment]
There's still an issue with parse/chart.py (possibly due to the way I collapsed `apply` and `apply_iter`) which results in some failing tests in test/parse.doctest.

**Comment by heatherleaf** [comment]
fixed in pull request #627

**Comment by stevenbird** [comment]
Most of the parse methods are now iterators (cf https://github.com/nltk/nltk/pull/634), and we need to decide what to do with the remaining ones that still return lists.

**Comment by heatherleaf** [comment]
Are there any that return lists? I must have missed them. As I can tell, it's only MaltParser and StanfordParser that do not return iterators:
- MaltParser.parse() returns a single DependencyGraph
- StanfordParser.parse() returns a single Tree

It's quite easy to change this so that they return an iterator with exactly one result, but do we want that?

**Comment by stevenbird** [comment]
The only outstanding issues here concern the parser interface, which is being dealt with elsewhere, https://github.com/nltk/nltk/issues/620.
