### ISSUE TITLE
TimeBank

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#62]
<b>What data set would you like to have added to NLTK?  If you have a</b>
<b>particular corpus in mind, please include information about availability,</b>
<b>license, and permission for us to redistribute the data.</b>

It would be great if at least a part of the TimeBank corpus...

http://www.cs.brandeis.edu/~jamesp/arda/time/timebank.html

...could be included with NLTK.  (I see that this would require some
negotiation with the owner, though...)

Adam P.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=330</p><hr/><h2>earlier comments</h2>

<p><strong>stfz65 said, at 2011-03-07T17:46:56.000Z:</strong></p>

<p>A corpus reader for timebank files would also be fine.

Stefan</p>

**Comment by ewan-klein** [comment]
The correct link to TimeBank now seems to be: http://www.ldc.upenn.edu/Catalog/CatalogEntry.jsp?catalogId=LDC2006T08

License information from http://www.timeml.org/site/timebank/documentation-1.2.html:

> The annotations in this data collection are copyrighted by Brandeis University. User acknowledges and agrees that: (i) as between User and Brandeis University, Brandeis University owns all the right, title and interest in the Annotated Content, unless expressly stated otherwise; (ii) nothing in this Agreement shall confer in User any right of ownership in the Annotated Content; and (iii) User is granted a non-exclusive, royalty free, worldwide license (with no right to sublicense) to use the Annotated Content solely for academic and research purposes. This Agreement is governed by the law of the Commonwealth of Massachusetts and User agrees to submit to the exclusive jurisdiction of the Massachusetts courts.
> 
> Note: The textual news documents annotated in this corpus have been collected from a wide range of sources and are not copyrighted by Brandeis University. The user acknowledges that the use of these news documents is restricted to research and/or academic purposes only.
