### ISSUE TITLE
Read NE columns off of CoNLL-style files

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#63]
It'd be nice to be able to read the ne columns off of CoNLL-style NER files without using the raw() 
method.

I've attached a patch that allows this by allowing more than word/tag/IOB columns to be returned 
from iob_sents() and iob_words().

E.g. c.iob_words(None, (c.WORDS, c.POS, c.CHUNK, c.NE)) would now return [...,('Electric', 'NNP', 'I-
NP', 'I-ORG'),...] but c.iob_words() returns  [...,('Electric', 'NNP', 'I-NP'),...] as before.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=338</p>

**Comment by alvations** [comment]
There's an answer from @alexis on https://stackoverflow.com/a/46875652/610569
