### ISSUE TITLE
Remove decorators.py?

### ISSUE THREAD

**Issue by heatherleaf** [nltk/nltk#630]
Do we need the `decorators` module for anything? Currently it is not used anywhere.

If we want to keep it, perhaps we should move all decorators there.

**Comment by stevenbird** [comment]
We use `decorators.memoize()` in https://github.com/nltk/nltk_book/blob/master/book/ch04.rst

**Comment by heatherleaf** [comment]
Ok, then perhaps move `memoize()` to `util`?

**Comment by stevenbird** [comment]
Good idea.
