### ISSUE TITLE
Senseval corpus contains irregular formed entries 

### ISSUE THREAD

**Issue by cartisan** [nltk/nltk#638]
I'm iterating over the instances of senseval in order to collect the words but not the POS-tags. Following the how-to in http://www.nltk.org/howto/corpus.html I use `train += [w for (w, _) in instance.context]` .
However eventually I get an ValueError `ValueError: too many values to unpack`
because an instance.context contains the String `FRASL` instead of a tuple. A quick glance into hard.pos showed me around 34 of those. This seems  rather inconvenient because now I have to think of how to deal with non-tuple entries.

Intuitively I'd suggest turning FRASL into a tuple, however I have no clue what it is actually denoting. If you decide against changing it, it would be nice to update  the HOWTO with a working approach for parsing instances. :)

**Comment by miskolc** [comment]
I also encountered this problem 3 years after this issue was open. I also think that using a tuple instead of `FRASL` would be a good make it easier to iterate over the words of senseval instances.
