### ISSUE TITLE
Error in Brill tagger docstrings

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#64]
The docstring for nltk.tag.brill.SymmetricProximateTokensTemplate is not correct:

```
One C{ProximateTokensTemplate} is formed by passing in the
same arguments given to this class's constructor: tuples
representing intervals in which a tag may be found.  The other
C{ProximateTokensTemplate} is constructed with the negative
of all the arguments in reversed order.  For example, a
C{SymmetricProximateTokensTemplate} using the pair (-2,-1) and the
constructor C{SymmetricProximateTokensTemplate} generates the same rules as a
C{SymmetricProximateTokensTemplate} using (-2,-1) plus a second
C{SymmetricProximateTokensTemplate} using (1,2).
```

I think some occurrences of SymmetricProximateTokensTemplate in the text above should be 
replaced, perhaps by ProximateTokensTemplate. Otherwise I don't understand it.

Also, the docstrings of ProximateTagsRule and ProximateWordsRule refer to SymmetricProximateTokensTemplate, but I think they should be referring to ProximateTokensTemplate.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=357</p>

**Comment by stevenbird** [comment]
Resolved, see https://github.com/nltk/nltk/issues/555
