### ISSUE TITLE
Bug with nltk.internals.config_java

### ISSUE THREAD

**Issue by hyangchun** [nltk/nltk#644]
There is a bug when finding java path on Windows 7 64bit system.

I haven't tried with other systems, but it tries to find "%JAVA_HOME%\java" instead of "%JAVA_HOME%\bin\java.exe"

I think it's a simple thing, but some people are having hard time with this when using java libraries from python including myself. Not very much to do to fix this, so I hope other people save their time.

**Comment by stevenxxiu** [comment]
Can you try using the nltk version on the develop branch or nltk 3 alpha? There have been many changes since nltk 2 and the current nltk 3 alpha does search for `java.exe` as well as `java`.

**Comment by alvations** [comment]
@chihoonj @stevenxxiu Do these [instructions on installing NLTK in Windows](https://gist.github.com/alvations/0ed8641d7d2e1941b9f9) help?

**Comment by alvations** [comment]
Conda installation is encouraged on Windows. Additionally, appropriate version of Java should be installed when using the Stanford CoreNLP interface. 

@chihoonj @stevenxxiu please reopen this issue if the problem persists =)

Closing issue in preparation for v3.2.5
