### ISSUE TITLE
WordNet reader UTF-8

### ISSUE THREAD

**Issue by djstrong** [nltk/nltk#646]
Using another language WordNet (e.g. Polish), that has keys in UTF-8 causes KeyError. It is because WordNet reader uses method `lower()`, that do not work with UTF-8. `lemma.decode('utf-8').lower().encode('utf-8')` would work.

Key causing error: `spowodować__DZIAŁANIE_DK_` is lowered to `spowodować__dziaŁanie_dk_` and should be to `spowodować__działanie_dk_`

This bug can be related to issue #299.

**Comment by kmike** [comment]
What NLTK version do you use? 
Could you please paste the exception?

**Comment by djstrong** [comment]
Version 2.0.4

```
from nltk.corpus import wordnet as wn

for synset in wn.all_synsets('v'):
  print synset
```

```
Traceback (most recent call last):
  File "plwordnet.py", line 3, in <module>
    for synset in wn.all_synsets('v'):
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1260, in all_synsets
    synset = from_pos_and_line(pos_tag, line)
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1176, in _synset_from_pos_and_line
    offsets = self._lemma_pos_offset_map[lemma_name][synset.pos]
KeyError: 'v'
```

As I said `lemma_name` in 1176 is `spowodować__dziaŁanie_dk_` and `_lemma_pos_offset_map` has not such key.

**Comment by kmike** [comment]
Could you try it with NLTK development version (from github) or with NLTK 3 alpha (http://www.nltk.org/nltk3-alpha/)? There were numerous changes in unicode handling, but we haven't released a pypi version yet.

**Comment by djstrong** [comment]
This problem does not exist in 3.0a3. Thanks!

**Comment by kmike** [comment]
Thanks for checking that!
