### ISSUE TITLE
wordnet corpora has non-existing pos 's'

### ISSUE THREAD

**Issue by Safadurimo** [nltk/nltk#649]
There are some synset, which habe the pos of 's'. Wordnet has only 4 different kinds of pos, see here: http://wordnet.princeton.edu/wordnet/man/wnstats.7WN.html
However, there seem to be five pos in the nltk interface:
set(s.pos for s in wn.all_synsets()) -> set(['a', 'n', 's', 'r', 'v'])
One example is the synset with name "dense.s.04"

**Comment by nschneid** [comment]
's' stands for 'satellite adjective'. The adjective synsets are organized in clusters consisting of a core member (tagged 'a') and variants called satellites (tagged 's'). I do think this could be better documented.

**Comment by alvations** [comment]
@nschneid Thanks for the explanation!

@Safadurimo The documentation on [Princeton WN page](https://wordnet.princeton.edu/man/wndb.5WN.html). The list of `ss_type` (synset types) as documented:

```
ss_type
One character code indicating the synset type:
    n    NOUN 
    v    VERB 
    a    ADJECTIVE 
    s    ADJECTIVE SATELLITE 
    r    ADVERB 
```

In the `nltk` code: https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L317
