### ISSUE TITLE
Text throws UnicodeEncodeError

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#65]
I understand that the Text class is intended mainly for demo and learning
purposes, but I just spent some time debugging my program which happened to
use it before realizing that as architected it doesn't support unicode
text.  I can work around, but wanted to let you know. Thanks for a great
toolkit!

<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>
0.9.8

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
import nltk
unicode_text = u'\u015bwiatowej'
tokens = nltk.word_tokenize(unicode_text)
text = nltk.Text(tokens)

Traceback (most recent call last):
  File &quot;&lt;console&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/usr/lib/python2.5/site-packages/nltk/text.py&quot;, line 283, in **init**
    self.name = &quot; &quot;.join(map(str, tokens[:8])) + &quot;...&quot;
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015b' in
position 0
: ordinal not in range(128)

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=370</p><hr/><h2>earlier comments</h2>
<p><strong>arthit said, at 2009-05-02T17:36:15.000Z:</strong></p>
<p>this code will work (2nd line added):

unicode_text = u'\u015bwiatowej'
unicode_text = unicode_text.encode("utf-8")
tokens = nltk.word_tokenize(unicode_text)
text = nltk.Text(tokens)
</p><p><strong>StevenBird1 said, at 2009-05-03T09:19:48.000Z:</strong></p>
<p>Thanks for pointing this out; its an instance of a more general issue with NLTK,
namely ensuring that everything works right with Unicode strings.  We probably won't
do this until NLTK 3.0 (to work with Python 3.0).
</p><p><strong>robfelty said, at 2009-11-02T17:31:57.000Z:</strong></p>
<p>The above code by Arthit does not work as I would expect it using 2.0b6. This is what
I get (with python 2.6.2 on Ubuntu):
>>> unicode_text = u'\u015bwiatowej'
>>> unicode_text = unicode_text.encode("utf-8")
>>> tokens = nltk.word_tokenize(unicode_text)
>>> tokens
['\xc5', '\x9b', 'wiatowej']

Getting rid of the encode part, I get:
>>> text = u'\u015bwiatowej'
>>> tokens = nltk.word_tokenize(text)
>>> tokens
[u'\u015b', u'wiatowej']

</p><p><strong>pingelsan said, at 2010-09-25T15:20:18.000Z:</strong></p>
<p>I had a similar problem (with German text).
For your case, this worked for me:

>>> unicode_text = u'\u015bwiatowej'
>>> unicode_text
u'\u015bwiatowej'
>>> unicode_text = unicode_text.encode('utf-8')
>>> unicode_text
'\xc5\x9bwiatowej'
>>> from nltk import PunktWordTokenizer
>>> tokens = PunktWordTokenizer().tokenize(unicode_text)
>>> tokens
['\xc5\x9bwiatowej']
>>> text = nltk.Text(tokens)
>>> text
<Text: światowej...>
>>> 

Is it safe to assume that most thing work in UTF-8, but in some cases - like the tokenizer here - we have to use some kind of drop-in-replacement?
</p>

**Comment by kmike** [comment]
This is fixed in 2and3 branch.

**Comment by sabuncu** [comment]
@alexrudnick You say "I understand that the Text class is intended mainly for demo and learning
purposes..." - could you please indicate where you came across this information?  I had problems as well w/ the Text class, and your trouble ticket here finally clued me in to its shortcomings.  Thank you.

**Comment by stevenbird** [comment]
http://www.nltk.org/api/nltk.html#nltk.text.Text

**Comment by sabuncu** [comment]
@stevenbird Thank you.  So, if I understand correctly, it is the Text() class that is for demo purposes.  The text() class (lowercase) seems, on the other hand, to be where all the production-level functionality is hosted.
