### ISSUE TITLE
nltk.re_show right-strips whitespace

### ISSUE THREAD

**Issue by prpole** [nltk/nltk#650]
The nltk.re_show() method right-strips whitespace. To replicate:

```
phillip = '#awesome '
nltk.re_show('\w+|[^\w]+', phillip)
```

Expected behavior:
`{#}{awesome}{ }`

Current behavior:
`{#}{awesome}`

See [here](http://stackoverflow.com/questions/22924956/does-regex-automatically-ignore-trailing-whitespace) for discussion.

**Comment by stevenbird** [comment]
I don't know why we wanted `re_show` to right-strip whitespace. It's not used elsewhere in the toolkit, and only mentioned in passing in the book. However, what's the use case where right-stripping whitespace is undesirable?

**Comment by heatherleaf** [comment]
I guess it's undesirable if you use `re_show` to teach/learn regular expressions
