### ISSUE TITLE
WordNet++

### ISSUE THREAD

**Issue by orbisvicis** [nltk/nltk#652]
Any thoughts on integrating http://lcl.uniroma1.it/wordnetplusplus/ into `nltk.wordnet`? I don't have the expertise to make the judgement, but it probably shouldn't replace the standard wordnet dataset. Therefore nltk module functionality would need to work with both sources.

What steps would this undertaking require? Could it be accomplished by something without any NLP experience?

**Comment by stevenbird** [comment]
Thanks for this suggestion. I would be happy for this to live alongside the existing wordnet corpus reader, with a maximally similar API. It wouldn't require NLP experience to do this, just a careful look at the existing wordnet code to see what could be re-used.
