### ISSUE TITLE
Rename parse methods

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#656]
Method names that contain `parse` in their name, not used for natural language parsing, should be renamed appropriately. For instance, `Tree.parse()` reads a string and returns a tree object, and can be renamed `Tree._read()`. The same goes for methods in  `sem.logic`, `featstruct`, and `RegexpChunkRule`. Cf https://github.com/nltk/nltk/issues/620

**Comment by stevenbird** [comment]
@dhgarrette would you be happy if we changed the name of `LogicParser` and its `parse` method to to some new name that does not encroach on the use of the "parse" for syntactic parsing of words?

**Comment by stevenbird** [comment]
In the absence of any objection, I'd like us to rename this parse method to `fromstring()`, then update our list of API changes at https://github.com/nltk/nltk/wiki/Porting-your-code-to-NLTK-3.0

**Comment by stevenbird** [comment]
`LogicParser.fromstring` doesn't make sense because we're not creating a LogicParser but an Expression from the string. Instead, I propose that we replace `LogicParser.parse` with `Expression.fromstring`. Also the exception name `ParseException` is too generic and I propose that we replace it with `LogicalExpressionException` instead.

**Comment by stevenbird** [comment]
I've made a start in https://github.com/nltk/nltk/tree/issue/656. I haven't worked out how to deal with `LinearLogicParser` or `DrtParser` yet. @dhgarrette, @ewan-klein what do you think?

**Comment by ewan-klein** [comment]
Apologies for not responding sooner. I'm happy with the changes you've made so far, which seem perfectly sensible. @dhgarrette has primary ownership of the `LinearLogicParser` and `DrtParser` code, and may well have views on how to bring them into line with the current approach.

**Comment by dhgarrette** [comment]
I like the changes.  Feel free to modify other stuff as you see fit.

**Comment by stevenbird** [comment]
I've renamed `AbstractDrs` to be `DrtExpression`, so that what's going on in drt.py parallels logic.py, where the abstract base expression class is just called `Expression`. Now you can initialise any of the DRT expression types like this:

```
>>> from nltk.sem import DrtExpression
>>> DrtExpression.fromstring(r'(\x.([],[walks(x)]))(john)')
<DrtApplicationExpression (\x.([],[walks(x)]))(john)>
```

However, now there's a problem in drt.doctest, which has to import the "private" class. Any ideas for how to use `DrtExpression.fromstring` with `load_parser()`? I'd rather not have to touch `load_parser()`.

```
>>> from nltk.sem.drt import _DrtParser
>>> parser = load_parser('grammars/book_grammars/drt.fcfg', trace=0, logic_parser=_DrtParser())
```

**Comment by stevenbird** [comment]
Now you can initialise a Linear Logic expression like this:

```
>>> from nltk.sem.linearlogic import Expression
>>> Expression.fromstring(r'((g -o G) -o G)((g -o f))')
<ApplicationExpression ((g -o G) -o G)((g -o f))>
>>> Expression.fromstring(r'((g -o G) -o G)((g -o f))').simplify()
<ConstantExpression f>
```

However, there's a naming problem, because both logic.py and linearlogic.py define `Expression`. This wasn't a problem when this abstract class was not being imported by init.py (when `LogicParser` and `LinearLogicParser` were being imported). Now that expressions are being initialised using the `Expression` class in both cases, I've simply dropped the import of `linearlogic.Expression` in init.py. (I guess an alternative is to rename `linearlogic.Expression` as `linearlogic.LlExpression`, to parallel `drt.DrtExpression`, or else `linearlogic.LinearLogicExpression`, and rename all the internal classes too, like `VariableLlExpression` or `VariableLinearLogicExpression`). Is it ok to drop the import in init.py?

**Comment by stevenbird** [comment]
There's a couple of other loose ends:
- logic.py defines `parse_logic()` for processing a file of expressions
- logic.doctest includes an example where custom quote chars are used, and this requires direct access to `_LogicParser`

**Comment by stevenbird** [comment]
I will merge this in preparation for the 3.0b1 release, and we can deal with these outstanding issues for 3.0b2.

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/c2988cc0f5c5a950544f8ef1024f38cea01373d9
