### ISSUE TITLE
PCFG vs WeightedGrammar

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#657]
NLTK's `WeightedGrammar` is actually a PCFG (since weights are normalised). We should consider changing its name to `PCFG` or `PCFGrammar` or `ProbabilisticContextFreeGrammar`.

**Comment by heatherleaf** [comment]
Since CFGs are called `ContextFreeGrammar`, I vote for `ProbabilisticContextFreeGrammar` even though it's looooong.

**Comment by stevenbird** [comment]
I'm still baulking at this. Other names that might be impacted are `FeatureGrammar`, `DependencyGrammar`, and `StatisticalDependencyGrammar`. I think the last of these should be probabilistic not statistical.
- `CFG`, `PCFG`, `DG`, `PDG`, `FG` -- non-starter
- `CFG`, `ProbabilisticCFG`, `DG`, `ProbabilisticDG`, `FG` -- no, seems like grammar must be expanded
- `CFGrammar`, `PCFGrammar`, `DGrammar`, `PDGrammar`, `FGrammar` -- non-starter

Is there any feasible alternative to the ultra-long names?

**Comment by heatherleaf** [comment]
Ultra-long names are fine. Perhaps we could use `Prob` instead of `Probabilistic`, but I prefer the latter.

+1 for renaming `Statistical` to `Probabilistic`

**Comment by heatherleaf** [comment]
There is a chartparser class called `FeatureIncrementalBottomUpLeftCornerChartParser`, and when I get the time to make it probabilistic its name will be… :)

**Comment by heatherleaf** [comment]
Here's a suggestion: define `CFG`, `PCFG`, `FG`, `DG`, ... as aliases for the ultra-long names, but don't export them to nltk by default. Then the following would be equivalent:
- `mygrammar = nltk.ProbabilisticContextFreeGrammar(...)`
- `mygrammar = nltk.grammar.PCFG(...)`
- `from nltk.grammar import PCFG; mygrammar = PCFG(...)`

**Comment by kmike** [comment]
CFG and PCFG are common and easily recognizable abbreviations, I think it is fine to use CFG and PCFG names (unlike DF, FG and PDG). But long names are also fine.

I don't like aliases; they add a confusion, and users can do `from nltk import FeatureGrammar as FG` if they want a short name.

**Comment by stevenbird** [comment]
After some reflection, I'd like to prioritise convenience and readability over consistency. Where the short name is widely used, we should use it (thus: `CFG`, `PCFG`). Otherwise, we need to use the long name (thus: `FeatureGrammar`, `DependencyGrammar`, `ProbabilisticDependencyGrammar`).

**Comment by stevenbird** [comment]
@heatherleaf are you ok with this solution?

**Comment by heatherleaf** [comment]
Sure. It's not my first choice, but I'm fine with it.

**Comment by stevenbird** [comment]
OK, thanks :)
