### ISSUE TITLE
Standardise method for initialisation from strings

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#658]
Several classes now have a `read()` method which can be used for initialising an instance of the class from a string (cf tree.py, featstruct.py, grammar.py chunk/regexp.py). We need to audit the various ways that a string can be used to initialise a class, and try to standardise on using `read()`.

**Comment by kmike** [comment]
Sorry if I'm too late, but I kind of dislike `read()` name: in Python it is usually used for reading data from a stream, and its argument is usually a number of bytes to read. This is the case for file objects, and objects from standard io, urllib, csv, json, configparser, codecs, zipfile and many other libraries. 

What is called `read()` in NLTK can be called `fromstring()` (see array, xml standard modules), `loads()` or `load()` (see json, pickle, cookielib) or `parse` (see ast, robotparser, string) or `parsestr` (email, xml.minidom); there are a few other variants, but it is never called `read()`.

**Comment by heatherleaf** [comment]
Good point. I vote for `fromstring()`, but humbly let @stevenbird make the final decision.

**Comment by stevenbird** [comment]
Yes, good point, and I also prefer `fromstring()` to the alternatives.
