### ISSUE TITLE
Lost commits

### ISSUE THREAD

**Issue by Tahnan** [nltk/nltk#670]
Hey--

If you look at https://github.com/nltk/nltk/commits/develop?page=4, you can see that a pull request I made (commits on Feb. 21) was merged into the develop branch on Feb 24. But the history for the file in question, https://github.com/nltk/nltk/commits/develop/nltk/stem/isri.py, shows its last change on February 16, and the changes I made are missing. They weren't _reverted_, they're just...not there.

Naturally, part of my concern is for my poor, hard-fought changes, but I'm also worried about how many other changes around that time may have also been lost, presumably in some sort of git accident. (On a casual skim, it looks like the previous pull request that was merged, https://github.com/nltk/nltk/commit/160a85d4551b3f629e725d1ee4a9f99666b75b45, also got lost; the one before that, which fixed test/semantics.doctest, also got lost, and was changed again in a later commit last week, https://github.com/nltk/nltk/commit/227c157bd66f0f38a46b241f46f79622769f6acc . I don't know if that'll help narrow anything down....)

EDIT: tracked it down more precisely. The changes are still there in https://github.com/nltk/nltk/commit/ede0f6ae9b86c567649e351e627e44d4e6605cb4 but are gone in the next commit, https://github.com/nltk/nltk/commit/e36392370aefb32576fa17e46957b914e361f741, innocuously named "fixed some merge conflicts". The same is true for alexrudnick's and heatherleaf's commits mentioned above. So that's definitely the source of the problem, though I still don't know how widespread it is, i.e. how much was lost.

**Comment by stevenbird** [comment]
@Tahnan thanks for looking into this. Yes this looks like some sort of git accident as you say. I guess we need to hunt down the original commits and re-apply them. In the case of `isri.py`, it might be a simple matter of you pointing me to the version that existed immediately after that merge, and I can reinstate that one. Would you mind doing this please?

**Comment by Tahnan** [comment]
https://github.com/nltk/nltk/commit/8dc5f5b5fda42ceff08ac7d3d47d1f795b30dfc3 is the commit with the merge itself, which should give you the code post-merge.  https://github.com/nltk/nltk/pull/619 is the pull request for it; https://github.com/nltk/nltk/commit/8cb361957d2dc702009a92838c89f2718df70d94 and https://github.com/nltk/nltk/commit/3ced3e88649ba1ed47e3f7e8c97aad73b41a4e5c are the two particular commits that pull-and-merge encompassed.

(Other pull requests merged that day include 617, 625, 627, and 628; two of those are the ones I mentioned above. Again, I haven't really checked to see how much is missing, or even whether all of those are; it's just a pointer in the right direction.)

**Comment by stevenbird** [comment]
I've added the new `isri.py`, and manually checked pull requests 617, 625, 627, and 628 and reapplied any changes that were missing.
