### ISSUE TITLE
Tree initializer

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#675]
The `Tree` class is unusual in NLTK in allowing initialization from lists or from strings:

```
>>> Tree('dp', [Tree('d', ['the']), Tree('np', ['dog'])]) == Tree('(dp (d the) (np dog))')
True
```

I propose that we drop the string initialization, for consistency with the rest of NLTK. Users can still do this:

```
>>> Tree.fromstring('(dp (d the) (np dog))')]
```

**Comment by SocialfiPanda** [comment]
I totally agree. I think I can take this one.

**Comment by stevenbird** [comment]
Actually, I'm keen to have some more discussion before going ahead with this change.

**Comment by heatherleaf** [comment]
I'm all for consistency. But we need to decide on the behaviour of `Tree("a")`:
- either it's illegal
- or it means the same as `Tree("a", [])`

I think it should be illegal, or the risk will be that people start writing `Tree("(a b c)")` and don't get what they think.

**Comment by SocialfiPanda** [comment]
Yeah, letting `Tree("(a b c)") == Tree("(a b c)", [])` can produce some hard to trace bug for the user, wondering why they do not get the tree structure they intend to get. At least for me, throwing an exception for Tree initialization with only one string argument is a sane way to go.

**Comment by stevenbird** [comment]
In the absence of any objections I'm going to accept this pull request. Thanks @jw2013, @kmike, and @heatherleaf for your helpful work!
