### ISSUE TITLE
After closing a graphics window called from nltk IDLE doen't work anymore

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#68]
The nltk version is 0.9.9

---

To reproduce:

Start IDLE

&gt;&gt;&gt; import nltk
&gt;&gt;&gt; nltk.download()

Ctrl x to close the download window 

---

<b>What is the expected output? What do you see instead?</b>
- The download window appears and closes as expected. However, the Python
  input cursor (&gt;&gt;&gt;) does not appear. Thus, IDLE doen't respond to inputs and
  must be closed. Upon closing IDLE complains that a program is still
  running. The same thing happens with other graphics windows called from
  nltk as well.  

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=379</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2009-05-13T21:32:44.000Z:</strong></p>

<p>What platform and Python version are you using?

If this is a general problem with IDLE, we should probably report it here:
http://bugs.python.org/
</p><p><strong>seliger61 said, at 2009-05-13T21:45:47.000Z:</strong></p>

<p>Platform: Ubuntu 8.10

The problem occurs with both Python 2.6.2, IDLE 2.6.2 and Python 2.5.4, IDLE 1.2.4</p><p><strong>edloper said, at 2010-06-05T01:25:02.000Z:</strong></p>

<p>Search for "in_idle" in the nltk.app modules to find a fix for this bug.
</p><p><strong>vidzup said, at 2011-08-29T05:28:31.000Z:</strong></p>

<p>Even with the fix in in_idle i am experiencing the same problem

Here are the values of the variables that you are examining in in_idle.  

sys.stdin  <idlelib.PyShell.PyShell object at 0xb6ad2dec>
type(sys.stdin)  <class 'idlelib.PyShell.PyShell'>
types.InstanceType  <type 'instance'>
sys.stdin.__class__.__name__ PyShell

I am using nltk on ubuntu 
Python 2.7
IDLE 2.7
nltk 2.0.1rc

However, because i will be using only IDLE, i simply did a return True and it seems to work fine after that.</p>

**Comment by stevenbird** [comment]
Too old, closing.
