### ISSUE TITLE
MaltParser not completely updated to new API

### ISSUE THREAD

**Issue by modi-thorson** [nltk/nltk#682]
Because of API changes, MaltParser objects fail when raw_parse() is called, since MaltParser.raw_parse internally calls parse() with two arguments (in addition to self).

Error occurs in malt.py, line 127, though other issues may exist.

**Comment by stevenbird** [comment]
@heatherleaf are you able to take a look at this please?

**Comment by heatherleaf** [comment]
Note that my fix does not change the basic API for Maltparser, which is different from the other parsers. Should we change Maltparser to adhere to the generic API? This will make `parse()` return an iterator of `DependencyGraph`s, and not a single one, as it is now.

Furthermore, should we add a `verbose` keyword argument to the parser apis?
