### ISSUE TITLE
StanfordParser fails at its own docstring examples

### ISSUE THREAD

**Issue by nickretallack** [nltk/nltk#685]
When I run [this function from the docstring](https://github.com/nltk/nltk/blob/develop/nltk/parse/stanford.py#L32), [this happens](https://gist.github.com/nickretallack/d72c9f668dab9cf1f25d).

```
>>> parser.raw_parse_sents(("the quick brown fox jumps over the lazy dog", "the quick grey wolf jumps over the lazy fox"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/parse/stanford.py", line 176, in raw_parse_sents
    return self._parse_trees_output(self._execute(cmd, '\n'.join(sentences), verbose))
  File "nltk/parse/stanford.py", line 106, in _parse_trees_output
    res.append(Tree('\n'.join(cur_lines)))
  File "nltk/tree.py", line 99, in __init__
    % type(self).__name__)
TypeError: Tree: Expected a node value and child list
```

It seems like it's impossible for it to work, because it [only passes one argument to nltk.tree.Tree](https://github.com/nltk/nltk/blob/develop/nltk/parse/stanford.py#L106), and that class [throws an error if its second argument isn't specified](https://github.com/nltk/nltk/blob/develop/nltk/tree.py#L97).  What should be done?

**Comment by heatherleaf** [comment]
The problem seems to be on line 106 in parse/stanford.py:

```
            res.append(Tree('\n'.join(cur_lines)))
```

And I guess this solves the problem:

```
            res.append(Tree.fromstring('\n'.join(cur_lines)))
```

But I don't have the Stanford parser currently installed on my computer, so I can't double-check. Perhaps @stevenbird, @kmike or someone else can do the necessary changes in the repo?

**Comment by nickretallack** [comment]
Yes, that solves the problem!  Thank you.

**Comment by heatherleaf** [comment]
I've created a pull request for this: #686

**Comment by stevenbird** [comment]
Thanks for the report and bugfix.
