### ISSUE TITLE
Update NLTK in PyPI, fix Python 3 and add Python 3 trove classifiers

### ISSUE THREAD

**Issue by ztane** [nltk/nltk#689]
The NLTK in PyPI is 2.0.4, and not installable on Python 3; I've heard that NLTK is used as yet another example/excuse for not porting to Python 3; provided that Python 3 has vastly better text processing capabilities and less confusion, it would be the better platform for NLP. Perhaps NLTK 3.0 could be uploaded to PyPI already as alpha, or even as its own distribution - nltk-alpha or so, for easy installation.

**Comment by stevenbird** [comment]
Thanks for the suggestion. Once NLTK 3.0b1 is ready in a few days, I will post it on PyPI.
