### ISSUE TITLE
Java binary path

### ISSUE THREAD

**Issue by nournia** [nltk/nltk#690]
I've installed `3.0a4` release and NLTK  can not find Java binary:

```
NLTK was unable to find the java file!
Use software specific configuration paramaters or set the JAVAHOME environment variable.
```

I'm using python 2.7 in Ubuntu. Installing `3.0a3` version, fixed this issue in python2 but python3 still suffers from same error.

**Comment by longdt219** [comment]
Could you be more specific @nournia. Where I can get that NLTK version 3.0a4 ??

**Comment by stevenbird** [comment]
3.0a4 is not a current version. I'll close this issue; @nournia please reopen if it recurs with the current version.
