### ISSUE TITLE
Corpus Reader for Universal Dependency Treebank

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#693]
Add the corpus reader for the Universal Dependency Treebank
https://code.google.com/p/uni-dep-tb/

**Comment by shcherbin** [comment]
I'll try to implement this reader.

**Comment by stevenbird** [comment]
@shcherbin any progress? I'd like to find someone else if you don't have time, thanks.

**Comment by shcherbin** [comment]
I've wrote you an email regarding this, I belive, in August but received no reply.

This corpus is in CONLL format.
By simply inheriting from  ConllCorpusReader (/nltk/corpus/reader/conll.py) and by providing correct columtypes there is no need to override some of the interface methods:

raw()
words()
sents()
tagged_words()
tagged_sents()

They all work as we would expect them to.

**Comment by stevenbird** [comment]
Thanks @shcherbin – I must have missed that email. I can't merge this PR as is, but will adapt it, and add data to the NLTK Data repository.

**Comment by shcherbin** [comment]
There are two versions of Universal Dependency Treebank, do we need to add them both?

**Comment by stevenbird** [comment]
This issue is superseded: https://github.com/nltk/nltk/pull/809

**Comment by ohenrik** [comment]
@shcherbin Any idea about what the correct column types are? could you provide an example?

Here is some test data:

```
# sent_id =  000001
# text = Lam og piggvar på bryllupsmenyen
1	Lam	lam	NOUN	_	Definite=Ind|Gender=Neut|Number=Sing	0	root	_	_
2	og	og	CCONJ	_	_	3	cc	_	_
3	piggvar	piggvar	NOUN	_	Definite=Ind|Gender=Masc|Number=Sing	1	conj	_	_
4	på	på	ADP	_	_	5	mark	_	_
5	bryllupsmenyen	bryllupsmeny	NOUN	_	Definite=Def|Gender=Masc|Number=Sing	1	xcomp	_	_
```
