### ISSUE TITLE
Why does the treebank include *T* tokens?

### ISSUE THREAD

**Issue by bimargulies** [nltk/nltk#707]
Using the script below, I find a significant scattering of tokens of the form:

_T_-1, -NONE

what are these?

```
import json
from nltk.corpus import treebank

class NLTKEncoder(json.JSONEncoder):
    def default(self, o):
        try:
            iterable = iter(o)
        except TypeError:
            pass
        else:
            return list(iterable)
        # Let the base class default method raise the TypeError
        return json.JSONEncoder.default(self, o)


with open("nltk_penn.json", "w") as outfile:
    json.dump(treebank.tagged_sents(), outfile, indent=2, cls=NLTKEncoder)
```

**Comment by alexrudnick** [comment]
Pretty sure those represent traces:
http://en.wikipedia.org/wiki/Trace_(linguistics)

For how traces are used in Penn Treebank, see:
http://www.sfs.uni-tuebingen.de/~dm/07/autumn/795.10/ptb-annotation-guide/root.html

Does that explain it? (closing the issue -- let me know if you're not satisfied!)
