### ISSUE TITLE
Issues/Typos on book web pages

### ISSUE THREAD

**Issue by hyp3rv1p3r** [nltk/nltk#708]
Hi, I found these issues on some documents:

Chap 9: In practice, this is also how the parser interprets slassh categories.
Chap 9.5 Please consult [NLTK-URL]

http://www.nltk.org/howto/featgram.html -> System Message: ERROR/3 (../../../nltk_book/definitions.rst, line 3)

System Message: ERROR/3 (featgram.doctest, line 109); backlink

**Comment by stevenbird** [comment]
Thanks; these problems should be fixed now.

**Comment by hyp3rv1p3r** [comment]
Hi, I don't know if it is legal to post on a closed issue but JIC:
again on page http://www.nltk.org/howto/featgram.html -> ~ row #13  
I read:
"Feature structures in NLTK are ... Atomic feature values can be strings or integers."
Is something missing.

BTW, Thanks for the excellent work with NLTK. :-)
