### ISSUE TITLE
Framenet methods

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#709]
These need to be methods, not attributes, for consistency with NLTK in general, and wordnet in particular, cf https://github.com/nltk/nltk/issues/475, http://www.nltk.org/howto/wordnet.html

```
    >>> from nltk.corpus import framenet as fn
    >>> fn.lu(256).name
    'foresee.v'
    >>> fn.lu(256).definition
    'COD: be aware of beforehand; predict.'
    >>> fn.lu(256).frame.name
    'Expectation'
    >>> fn.lu(256).lexemes[0].name
    'foresee'
```

**Comment by stevenbird** [comment]
Unfortunately this isn't so simple to resolve given the heavy use of `AttrDict` in `framenet.py`. That's a neat innovation but not consistent with the rest of the toolkit. Dropping `AttrDict` would give us code like: `fn.lu(256)['name']` which would be worse. It's probably going to take some work to get `fn.lu(256).name()` for consistency with WordNet. We won't hold up the 3.0 release for this, but wait for 3.1.

@wooters, @nschneid – I would appreciate your thoughts on this.

**Comment by nschneid** [comment]
Agreed that it seems complicated. There may be a way to have `AttrDict` provide its elements as methods, but I think that would require changing things throughout the code.

**Comment by wooters** [comment]
Yeah, sorry. This is my fault. I should have done this in the original implementation.

**Comment by stevenbird** [comment]
I think it's too late to bother with this consistency issue, so I'll close the issue.
