### ISSUE TITLE
Problem with final test in corpus.doctest

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#71]
$ cd trunk/nltk/test; make corpus.errs

File &quot;...nltk/test/corpus.doctest&quot;, line 2118, in corpus.doctest
Failed example:
    for i, string in enumerate(strings):
        print 'String %d: %s' % (i, `string[:45]`[:-1]+'...')
        for encoding in encodings:
            print ('  - test for %-10s [%s]' %
                   (encoding, reader_test(string, encoding)))
Exception raised:
    Traceback (most recent call last):
      File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/doctest.py&quot;,
line 1228, in __run
        compileflags, 1) in test.globs
      File &quot;&lt;doctest corpus.doctest[402]&gt;&quot;, line 5, in &lt;module&gt;
        (encoding, reader_test(string, encoding)))
      File &quot;&lt;doctest corpus.doctest[399]&gt;&quot;, line 35, in reader_test
        size = random.randint(0, strlen/6)
      File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/random.py&quot;, line
215, in randint
        return self.randrange(a, b+1)
      File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/random.py&quot;, line
171, in randrange
        raise ValueError, &quot;non-integer stop for randrange()&quot;
    ValueError: non-integer stop for randrange()

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=406</p>

**Comment by kmike** [comment]
I think this was fixed while ago (e.g. failing line from this ticket is `size = random.randint(0, int(strlen/6))` now)
