### ISSUE TITLE
Fieldworks Language Explorer

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#715]
NLTK includes some support for SIL toolbox (in `nltk.toolbox` and `nltk_contrib.toolbox`). It would be good to update this to support Fieldworks Language Explorer (FLEx).

http://fieldworks.sil.org/flex/
http://craigstips.wikispaces.com/FlexApps

**Comment by pandersity** [comment]
I am most definitely interested in FLEx support added to NLTK!  To my knowledge, there is no existing Python library that has out-of-the-box support for FLEx database manipulation (I could be wrong, but I have looked high and low for one with no luck).  

Best I have been able to find are:

Ken Zook's docs for FLEx with Iron Python
http://tinyurl.com/mt2oo23 -- this links to Word doc that will be downloaded, the most common format of FLEx technical docs...

A 2006 article with a code snippet using Python for .NET
http://wesay.palaso.org/2006/12/29/using-python-to-read-a-fieldworks-lexicon/

If you decide to add FLEx support to NTLK, let me know.  Depending on the timing of it, I may be interested in contributing!

**Comment by rmlockwood** [comment]
I am also interested in FLEx support added to NLTK. This would make FLEx data easily accessible to linguists and programmers of all types. NLTK is a great library of tools! I don't think there is a cross-platform library. Right now I'm using FlexApps on Windows. Of course at the moment FLEx is just available on Windows and Linux. If there is enough interest I think we could get it put on the list of priority SIL projects. I would be willing to be a champion for it. Who else has interest?

**Comment by serapio** [comment]
I would be interested in helping with this. It's tricky to work with FLEx's internal database, but the LIFT exported lexicon is pretty easy to deal with. (Export as LIFT, manipulate the LIFT data, import it again) It would be nice to be able to manipulate the interlinear corpora from NLTK, but FLEx's import and export of corpus data isn't as mature as the lexicon functions.

**Comment by stevenbird** [comment]
@pandersity, @rmdiamondl, @serapio – I'm just getting back to this. Thanks for your interest. I'd like to discuss how we can move forward. Is there consensus in working with LIFT format? Does this include the interlinear text data or can that be accessed via some other export format?

**Comment by serapio** [comment]
The LIFT file just has the lexicon, and the texts are exported as .flextext files. Flextext is also an XML format, so it's not hard to read, but I do not know of any documentation for it, and I don't know how stable it is as a standard.

**Comment by rmlockwood** [comment]
LIFT is just for lexical data. FLExText XML is for texts. It is based on the Electronic Metastructure for Endangered Languages Data (EMELD) and is being used for interchange between ELAN and FLEx.

**Comment by stevenbird** [comment]
@serapio, @pandersity, @rmlockwood – I'm revising [NLTK book chapter 11](http://www.nltk.org/book/ch11.html) and would like to replace the Toolbox section with something about LIFT (to cover FLEx and WeSay lexicons) and FLExText (for interlinear text). I'd like to take stock of what's now available out there, in case we can just refer to external libraries and not have to do anything special in NLTK itself, as @gregaumann did in [toolbox.py](https://github.com/nltk/nltk/blob/develop/nltk/toolbox.py).

I found:
- [LIFT2CSV.py](https://github.com/lukhnos/lift-convert/blob/master/nan-tw-TL-LIFT2CSV.py) by @lukhnos, with some [documentation](http://hackersome.com/p/lukhnos/lift-convert)
- a [detailed report](http://fieldworks.sil.org/wp-content/TechnicalDocs/Export%20options%20in%20Flex.pdf) by @KenZook
- a [blog post](http://wesay.palaso.org/2006/12/29/using-python-to-read-a-fieldworks-lexicon/) by @hatton

Can anyone please tell us what the current recommended approach is for working with FLEx data using Python?

**Comment by serapio** [comment]
I don't know of anything covering flextext, but if you are interested in a LIFT reader in NLTK, I think what I have here https://github.com/serapio/kwaras/blob/master/src/formats/lift.py would be easily adaptable.

**Comment by lukhnos** [comment]
@stevenbird Hi, I saw [lift-convert](https://github.com/lukhnos/lift-convert) being mentioned here. It was some ad hoc code for extracting Taiwanese Hokkien data in LIFT into CSV for an input method project, and is unlikely to be useful in general cases. I think the `lift.py` mentioned above would indeed be a better starting point. Thanks!

**Comment by KenZook** [comment]
For accessing FieldWorks data via Python, I’d recommend using FLExTools, developed by Craig Farrow. This is something he developed around the FDO access code which is core to FieldWorks.

You can get details and downloads of this at https://github.com/cdfarrow/FLExTools/wiki. Craig’s e-mail is craig_farrow@sil.org.

It would be possible working strictly with LIFT, but LIFT really needs some enhancements to fully support Flex data, and I’m not sure when that will be addressed.
