### ISSUE TITLE
FrameNet module fails to load in scripts

### ISSUE THREAD

**Issue by Liontooth** [nltk/nltk#718]
With python-nltk 3.0.0b1 framenet works great in console, but appears to fail to load fully if run in a script. The demo can be called and runs successfully, but most functions fail:
# !/usr/bin/python

from pprint import pprint
from nltk.corpus.reader import framenet as fn
print fn
print dir(fn)
fn.demo()
fn.frame(256)

$ python ftest.py
<module 'nltk.corpus.reader.framenet' from '/usr/lib/python2.7/dist-packages/nltk/corpus/reader/framenet.pyc'>
['AbstractLazySequence', 'AttrDict', 'ElementWrapper', 'FramenetCorpusReader', 'FramenetError', 'Future', 'LazyMap', 'PrettyDict', 'PrettyLazyMap', 'PrettyList', 'XMLCorpusReader', 'XMLCorpusView', '**builtins**', '**doc**', '**docformat**', '**file**', '**name**', '**package**', '_pretty_any', '_pretty_fe', '_pretty_fe_relation', '_pretty_frame', '_pretty_frame_relation', '_pretty_frame_relation_type', '_pretty_longstring', '_pretty_lu', '_pretty_semtype', 'defaultdict', 'demo', 'os', 'pformat', 'pprint', 'print_function', 'python_2_unicode_compatible', 're', 'string_types', 'sys', 'text_type', 'textwrap', 'unicode_literals']
Building the indexes...
Number of Frames: 1019
Number of Lexical Units: 11829
Number of annotated documents: 78
...
Traceback (most recent call last):
  File "./FrameNet-01.py", line 5, in <module>
    fn.frame(256)
AttributeError: 'module' object has no attribute 'frame'

doc(fn) shows in console:

$ python
Python 2.7.7 (default, Jun  3 2014, 16:16:56)
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from nltk.corpus import framenet as fn
> > > dir(fn)
> > > ['_LazyCorpusLoader__args', '_LazyCorpusLoader__kwargs', '_LazyCorpusLoader__name', '_LazyCorpusLoader__reader_cls', '__class__', '**delattr**', '**dict**', '**doc**', '**format**', '**getattribute**', '**hash**', '**init**', '**module**', '**name**', '**new**', '**reduce**', '**reduce_ex**', '**repr**', '**setattr**', '**sizeof**', '**str**', '**subclasshook**', '**unicode**', '**weakref**', '_bad_statuses', '_buildcorpusindex', '_buildframeindex', '_buildluindex', '_buildrelationindex', '_get_root', '_handle_elt', '_handle_fe_elt', '_handle_fecoreset_elt', '_handle_frame_elt', '_handle_framelexunit_elt', '_handle_framerelation_elt', '_handle_framerelationtype_elt', '_handle_fulltext_sentence_elt', '_handle_fulltextannotation_elt', '_handle_fulltextannotationset_elt', '_handle_fulltextindex_elt', '_handle_fulltextlayer_elt', '_handle_lexunit_elt', '_handle_luannotationset_elt', '_handle_lulayer_elt', '_handle_lusentence_elt', '_handle_lusubcorpus_elt', '_handle_semtype_elt', '_load_xml_attributes', '_loadsemtypes', '_lu_file', '_strip_tags', 'abspath', 'abspaths', 'annotated_document', 'buildindexes', 'documents', 'encoding', 'ensure_loaded', 'fe_relations', 'fileids', 'frame', 'frame_by_id', 'frame_by_name', 'frame_ids_and_names', 'frame_relation_types', 'frame_relations', 'frames', 'frames_by_lemma', 'lu', 'lu_basic', 'lu_ids_and_names', 'lus', 'open', 'propagate_semtypes', 'raw', 'readme', 'root', 'semtype', 'semtype_inherits', 'semtypes', 'unicode_repr', 'words', 'xml']

Setting export PYTHONVERBOSE=1 and comparing the console and script logs shows the same files load, which suggests this might be an upstream bug.

Cheers,
David

**Comment by stevenbird** [comment]
I also see this error, `AttributeError: 'module' object has no attribute 'frame'`.

However, I get different behaviour for Python 2.7 and Python 3.4. @Liontooth would you please take a look at the Python 3.4 output?

```
from __future__ import print_function
from pprint import pprint
from nltk.corpus.reader import framenet as fn
print(fn)
print(dir(fn))
fn.demo()
fn.frame(256)
```

**Comment by stevenbird** [comment]
@wooters would you mind looking into this please?

**Comment by Liontooth** [comment]
Thank you, Steven. The problem appears to vanish if I use

  from nltk.corpus import framenet as fn

instead of

  from nltk.corpus.reader import framenet as fn

With "from nltk.corpus import framenet as fn" I get

```
 <FramenetCorpusReader in u'.../corpora/framenet_v15' (not loaded yet)>
```

until a function is called, such as "fn.frame(256)", and then I get

```
  <FramenetCorpusReader in u'/usr/local/share/nltk_data/corpora/framenet_v15'>
```

and everything works. In contrast, with

```
from nltk.corpus.reader import framenet as fn
```

I get

<module 'nltk.corpus.reader.framenet' from '/usr/lib/python2.7/dist-packages/nltk/corpus/reader/framenet.py'>
Traceback (most recent call last):
  File "FrameNet-01.py", line 50, in <module>
    fn.frame(256)
AttributeError: 'module' object has no attribute 'frame'

Since the instructions at http://www.nltk.org/howto/framenet.html say to use "from nltk.corpus import framenet as fn", it looks like this was just my mistake. I apologize for the noise -- and am thrilled this is working!

Cheers,
Dave

```
  from nltk.corpus import framenet as fn
```

**Comment by stevenbird** [comment]
Yes, there's a design problem here, where module names in nltk.corpus.reader coincide with corpus names exported from nltk.corpus.

**Comment by Liontooth** [comment]
Ah, thanks. Quite confusing.
