### ISSUE TITLE
Incomplete FrameNet lexicon?

### ISSUE THREAD

**Issue by Liontooth** [nltk/nltk#719]
Analyzing the sentence "IT WAS LIKELY THESE ARE FIGHTERS, MILITANTS FROM GAZA TELLING US TO GET OUT OF THERE." from the news, I get no hits on two key words, "fighter" and "militant":

> > > fn.lus(r'(?i)fighter')
> > >   []
> > > fn.lus(r'(?i)militant')
> > >   []
> > > However, in FrameNet online, both belong to the frame <a href="https://framenet2.icsi.berkeley.edu/fnReports/data/frameIndex.xml?frame=Irregular_combatants">irregular_combatant</a>. I cannot find it in NLTK FrameNet:
> > > fn.frames(r'(?i)irregular combatants')
> > >   []
> > > Is the FrameNet corpus in NLTK simply an earlier version, or is it a selected subset? The number of frames associated with each word in the sample sentence:

  it 286
  was 110
  likely 1
  these 0
  are 40
  fighter 0
  , 0
  militant 0
  from 6
  gaza 0
  telling 1
  us 636
  to 205
  get 43
  out 87
  of 77
  there 6
  . 894

NLTK makes this information wonderfully accessible, but to characterize a frame we need rare words like militant and fighter; the large number of frames associated with many of the words make them poor candidates for identifying the frame. This is not a bug report but a request for clarification on the corpus; do we have someone currently on the team who can help us with corpus updates?

Cheers
Dave

**Comment by stevenbird** [comment]
@wooters would you please take a look at this one?

**Comment by Liontooth** [comment]
Hi Steven,

I've consulted with FrameNet researchers and they say they are working on releasing version 1.6 with the improvements of the last three years.

David

**Comment by nschneid** [comment]
To add: the FrameNet website has the most current version of the FrameNet data (what will become the 1.6 release). It does have 'fighter' and 'militant', though there are certainly gaps in the vocabulary: see https://framenet.icsi.berkeley.edu/fndrupal/index.php?q=luIndex

**Comment by wooters** [comment]
Sorry for the delayed response. The version of FrameNet that is in NLTK is 1.5. Thanks for adding that info @nschneid
