### ISSUE TITLE
Toolbox test in corpus.doctest is broken

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#72]
It looks like the key intended for use in parsing the toolbox entries is
being passed through to the chunk parser.  Can you take a look at this
please Greg?

&gt;&gt;&gt; river = toolbox.xml('rotokas/river.txt', key='ref')
Traceback (most recent call last):
  File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/nltk/corpus/reader/toolbox.py&quot;,
line 30, in xml
    for (path, enc) in self.abspaths(fileids, True)])
  File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/nltk/toolbox/toolbox.py&quot;,
line 138, in parse
    return self._chunk_parse(grammar=grammar,  **kwargs)
  File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/nltk/toolbox/toolbox.py&quot;,
line 255, in _chunk_parse
    cp = chunk.RegexpParser(grammar, top_node=top_node, trace=trace)
  File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/nltk/chunk/regexp.py&quot;,
line 1111, in __init__
    self._parse_grammar(grammar, top_node, trace)
  File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/nltk/chunk/regexp.py&quot;,
line 1147, in _parse_grammar
    rules.append(RegexpChunkRule.parse(line))
  File
&quot;/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/nltk/chunk/regexp.py&quot;,
line 378, in parse
    raise ValueError('Illegal chunk pattern: %s' % rule)
ValueError: Illegal chunk pattern: ref

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=407</p>

**Comment by kmike** [comment]
This ticket is still valid.

**Comment by stevenbird** [comment]
toolbox.xml() invokes ToolboxData.parse(), which can take this key argument only if a grammar is specified; trying to determine where this use case came from (i.e. why key was specified without a grammar).
