### ISSUE TITLE
FrameNet Frame Elements lost hierarchical structure

### ISSUE THREAD

**Issue by Liontooth** [nltk/nltk#720]
Let's say we examine the lemma "likely":

> > > lemma = "likely"
> > > fn.frames_by_lemma(lemma)
> > >   [<frame ID=114 name=Likelihood>]
> > > ID=114
> > > f   = fn.frame(ID)
> > > fn.frame(114)
> > >   frame (114): Likelihood

  [definition]
  This frame is concerned with the likelihood of a
  Hypothetical_event occurring. The Hypothetical_event is its only
  core frame element.  'It is likely that he'll arrive late.'
  Notice that in the case where a noun phrase is the subject of the
  Support Verb, that NP is also tagged as Hypothetical_event.  'He
  is likely to arrive late.'

  [semTypes] 0 semantic types

  [frameRelations] 5 frame relations
  <Parent=Gradable_attributes -- Inheritance -> Child=Likelihood>
  <Parent=Likelihood -- Inheritance -> Child=Run_risk>
  <Parent=Likelihood -- Using -> Child=Capability>
  <Parent=Likelihood -- Using -> Child=Luck>
  <Source=Certainty -- ReFraming_Mapping -> Target=Likelihood>

  [lexUnit] 27 lexical units
  assured.a (15433), bound.a (3286), can.v (14403), certain.a
  (2277), certainly.adv (13145), certainty.n (2280), chance.n
  (2284), guaranteed.a (13670), impossible.a (2288),
  improbability.n (2289), liable.a (15902), likelihood.n (2279),
  likely.a (2278), likely.adv (11701), long.a (15390), may.v
  (6505), might.v (6506), possibility.n (2282), possible.a (2281),
  possibly.adv (2304), probability.n (2300), probable.a (2286),
  probably.adv (10854), prone.a (2290), sure.a (2293), tend.v
  (2659), unlikely.a (2287)

  [FE] 6 frame elements
            Core: Hypothetical_event (563)
      Peripheral: Degree (676), Place (756), Time (758)
  Extra-Thematic: Circumstances (4795), Reason (639)

  [FEcoreSets] 0 frame element core sets

As we see above, the Frame Elements section has a hierarchical structure, with Core, Peripheral, and Extra-thematic. In the python implementation, this structure is lost:

> > > f.FE
> > >    {'Circumstances': <fe ID=4795 name=Circumstances>, 'Degree': <fe ID=676 name=Degree>,
> > >    'Hypothetical_event': <fe ID=563 name=Hypothetical_event>, 'Place': <fe ID=756 name=Place>,
> > >    'Reason': <fe ID=639 name=Reason>, 'Time': <fe ID=758 name=Time>}

Here the Frame Elements are in alphabetical order. This is a significant loss of important information; is it possible to implement the FE section as tuples that retain the hierarchy?

Cheers,
David

**Comment by Liontooth** [comment]
A workaround is to search for the string; here's a toy implementation -- getting the Frame ID and the Core Frame Elements should really be much easier, but this works:

``` python
# H. Word loop for FrameNet analysis
      try:
          lemmas = MBSP.lemmatize(text.lower(), tokenize = True)
          for sentence in lemmas.splitlines():
              for lemma in sentence.split(" "):
                  try:  
                        frames = fn.frames_by_lemma(lemma)
                        for frame in frames:
                            ID  = str(frame).split(":")[0]
                            ID  = re.sub('[()]', '', ID)
                            ID  = int(ID.split(" ")[1])
                            f   = fn.frame(ID)
                            COR = re.search("Core\:\ [A-Za-z_]*\ \([0-9]{1,9}\)", str(fn.frame(ID)))
                            COR = COR.group()
                            REL = f.frameRelations
                            print "".join([field[0],"|",field[1],"|FRM_01|",lemma,"|",str(COR),"|",str(REL)])
                  except (AttributeError, nltk.corpus.reader.framenet.FramenetError):
                        continue
      except (UnicodeDecodeError, UnicodeEncodeError, IndexError, AssertionError):
          # Tag failed UTF-8 lines NA to enable repair
          print "".join([field[0],"|",field[1],"|FRM_01","|NA"])
          continue
```

**Comment by nschneid** [comment]
This was done intentionally because it makes it easier to access the frame element by name, which is the more common expected use case than (say) retrieving all frame elements sharing the same coreness status. However, it is easy to retrieve the coreness status as an attribute of the FE object:

``` python
>>> fn.frame('Likelihood').FE['Degree']
frame element (676): Degree
    of Likelihood(114)
[definition]
  Degree to which event occurs
[abbrev] Degr
[coreType] Peripheral
[requiresFE] <None>
[excludesFE] <None>
[semType]
  Degree(172)

>>> fn.frame('Likelihood').FE['Degree'].coreType
'Peripheral'
```

Thus if you wanted to group together FEs by coreType (as the frame display does), you could do:

``` python
>>> {ct: [fename for fename,fe in fn.frame('Likelihood').FE.items() if fe.coreType==ct] for ct in ('Core', 'Peripheral', 'Extra-Thematic')}
{'Core': ['Hypothetical_event'], 'Peripheral': ['Degree', 'Place', 'Time'], 'Extra-Thematic': ['Reason', 'Circumstances']}
```

**Comment by Liontooth** [comment]
That's super helpful, thank you. The command "for fename,fe in fn.frame(framename).items()" is useful for revealing which elements can be referenced, so I realized I can simply do this to obtain the frame IDs from a lemma -- for some reason I didn't find this documented anywhere, obviously elegant as it is:

> > > frames = fn.frames_by_lemma(lemma)
> > > for frame in frames:
> > >  ...   ID = frame.ID

I'm having more trouble getting the Core frame element. While

 {ct: [fename for fename,fe in fn.frame('Likelihood').FE.items() if fe.coreType==ct] for ct in ('Core', )} 

pulls out the Core frame element, how do I get the whole line, "Core: Hypothetical_event (563)", in some reasonable compact way? Brute force works --

```
 re.search("Core\:\ \w*\ \(\d*\)", str(fn.frame(ID))).group()
```

David

**Comment by nschneid** [comment]
> I realized I can simply do this to obtain the frame IDs from a lemma -- for some reason I didn't find this documented anywhere

See module documentation here: http://www.nltk.org/api/nltk.corpus.reader.html#module-nltk.corpus.reader.framenet

**Comment by nschneid** [comment]
> how do I get the whole line, "Core: Hypothetical_event (563)", in some reasonable compact way?

Are you saying you want the frame element IDs as well? Those are available via the `ID` attribute on the frame element object:

``` python
>>> [(fename,fe.ID) for fename,fe in fn.frame('Likelihood').FE.items() if fe.coreType=='Core']
[('Hypothetical_event', 563)]
```

**Comment by Liontooth** [comment]
Very cool, thank you!
