### ISSUE TITLE
Stanford POS tagger behavior for empty input

### ISSUE THREAD

**Issue by heatherleaf** [nltk/nltk#722]
[This bug was reported by Tommy Carpenter, but he doesn't have a GitHub account]

My question is related to the NLTK API linked on this page: http://www.nltk.org/api/nltk.tag.html#module-nltk.tag.stanford. The Stanford POS tagger mailing list told me that the API is written by NLTK developers, not Stanford's NLP group. 
# Problem

The function `batch_tag` does not return an output for every input; specifically it has no return value when the input sentence is blank (== "") and silently drops the input. I think this should be fixed, because when using `batch_tag` (which is far faster than calling tag over and over due to Python creating a Java wrapper) the output list size may not match the input list size which then causes problems in many applications that depends on the list of tagged sentences to be the same length as the input list. I think instead of returning a value only when the input is non-blank, it should just return an empty tuple `(,)` if the input is blank so that the input and output lists are of the same size. 

As a temporary fix, I have to iterate over all my input lists and replace any blank instances with "NULL".
# Reproducing code sample:

```
import nltk
from nltk.tag.stanford import POSTagger

StanfordTagger = POSTagger('stanford-postagger-2014-06-16/models/english-left3words-distsim.tagger',
                           'stanford-postagger-2014-06-16/stanford-postagger.jar') 

testlist = ["blah","","blah"]
print(StanfordTagger.batch_tag(testlist))
#prints [[('b', 'NN'), ('l', 'NN'), ('a', 'DT'), ('h', 'NN')], [('b', 'NN'), ('l', 'NN'), ('a', 'DT'), ('h', 'NN')]]
```

**Comment by stevenbird** [comment]
I agree that the output list should be padded with `(,)` to ensure it is the same length as the input list. Note that `batch_tag` has been renamed to `tag_sents`.

**Comment by longdt219** [comment]
We can easily resolve this one by adding 
-outputFormatOptions keepEmptySentences 
as part of the options for stanford POS tagger. 
==>testlist = ["blah","","blah"]
==>print(StanfordTagger.tag_sents(testlist))
[[(u'b', u'NN'), (u'l', u'NN'), (u'a', u'DT'), (u'h', u'NN')], [], [(u'b', u'NN'), (u'l', u'NN'), (u'a', u'DT'), (u'h', u'NN')]]

However, what I'm thinking is the empty token inside the string. For example
==>testlist = [['','yes']]
==>print(StanfordTagger.tag_sents(testlist))
[[(u'yes', u'RB')]]
By default, stanford pos tagger remove all blank tokens. Should we engineering to output something like
[[(,),(u'yes',u'RB')]]
