### ISSUE TITLE
FreqDist.plot doesn't sort 

### ISSUE THREAD

**Issue by richwiss** [nltk/nltk#723]
For example, Ch 1 Section 3 has the code:

fdist1 = FreqDist(text1)
fdist1.plot(50, cumulative=True)

But the plot that comes out is not sorted by most frequent type. It may be in the order of its hash values but I'm unsure. It's definitely not by most frequent which I believe is the intent.

**Comment by amishwins** [comment]
I have the same issue. Here's my environment setup:

Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:38:22) [MSC v.1600 32 bit (Intel)] on win32
nltk-3.0.0b2.win32
matplotlib-1.4.0.win32-py3.4
nltk-3.0.0b2.win32

Here's the link to the docs:
http://www.nltk.org/api/nltk.html#nltk.probability.FreqDist

Specifically:
`plot(*args, **kwargs)[source]
Plot samples from the frequency distribution displaying the most frequent sample first.`

Here's an example: 
![y_no_sorted](https://cloud.githubusercontent.com/assets/3238003/4174026/920d88ac-3574-11e4-9c57-537911fb1cb0.png)

**Comment by stevenbird** [comment]
Thanks for reporting the problem.
