### ISSUE TITLE
AttrDict calls fail

### ISSUE THREAD

**Issue by Liontooth** [nltk/nltk#725]
``` python
 import nltk
 from pprint import pprint
 from nltk.corpus import framenet as fn
 >>> foo = {'a':1, 'b':2, 'c':3}
 >>> bar = AttrDict(foo)
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 NameError: name 'AttrDict' is not defined
```

So the PrettyList and PrettyDict examples in the [FrameNet API](http://www.nltk.org/api/nltk.corpus.reader.html#nltk.corpus.reader.framenet.AttrDict) all fail. What am I missing?

Cheers,
David

**Comment by Liontooth** [comment]
Sorry, git clone https://github.com/bcj/AttrDict -- I thought it was included in NLTK/FrameNet.

**Comment by Liontooth** [comment]
AttrDict was apparently not the answer:

``` python
>>> from attrdict import AttrDict
>>> bar = AttrDict(foo)
>>> pprint(dict(bar))
{'a': 1, 'b': 2, 'c': 3}
>>> PrettyList(fn.frames(r'(?i)medical'), maxReprSize=0, breakLines=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PrettyList' is not defined
```

Where is PrettyDict and PrettyList? I see them only in the [FrameNet source code](http://www.nltk.org/_modules/nltk/corpus/reader/framenet.html) -- so what's the problem?

Dave

**Comment by franquattri** [comment]
Same problem. Any clues?

**Comment by domspad** [comment]
`from nltk.corpus.reader.framenet import AttrDict, PrettyDict, PrettyList`

You can find these classes [here](https://github.com/nltk/nltk/blob/412263afdba4ec6c799bf5e138090d871cbcee15/nltk/corpus/reader/framenet.py)
