### ISSUE TITLE
Twitter and the CorpusReader API

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#728]
@ewan-klein is working on a [TwitterCorpusReader](https://github.com/nltk/nltk/blob/twitter/nltk/corpus/reader/twitter.py) that includes:
- `tweets()` – returns a list of strings, one per tweet
- `full_tweets()` – returns a list of dictionaries, one per tweet
- `tokenized_tweets()` – returns a list of lists of tokens

How can we best align this with the existing [CorpusReader](http://www.nltk.org/howto/corpus.html) methods for text corpora:
- `raw()` – raw contents of corpus files
- `words()`, `chunks()`, `sents()`, `paras()` – a list of (list of (list of)) tokens
- `tagged_words()`, `tagged_sents()`, `tagged_paras()` – a list of (list of (list of)) tagged tokens
- `chunked_sents()`, `parsed_sents()` – a list of trees
- `parsed_docs()` – just exists for IEER

**Comment by stevenbird** [comment]
Notes:
- other text corpora have items that correspond roughly to "sents" above: `posts()` and `xml_posts()` (nps_chat), `utterance()` (timit), `tweets()`. An SMS corpus might need `messages()`. The unit of sentence, post, utterance, tweet, or message is the natural size for many NLP tasks. E.g. ngram POS-tagging should not consider ngrams that cross sentence boundaries. The name of this unit changes with the corpus, but is predictable from the corpus.
- the `words()`, `chunks()`, `sents()`, `paras()` methods implicitly tokenize the data; other method names make the data type more explicit, e.g. `tagged_*()`, `parsed_*()`
- it is not easy to get the raw string corresponding to a sentence, supposing you wanted to tokenize it yourself (NB some corpora such as the Brown Corpus, this is not available, since the data representation is already tokenized and tagged)
- it is not possible to opt for a different tokenizer in `words()` and the other tokenizing methods

**Comment by stevenbird** [comment]
Here is a possible solution. I'm assuming that all text corpora have a default unit size that is approximately at the level of an utterance (sentence, chunk, post, tweet, message). The methods    generally iterate over this unit size.
- `raw()` – returns iter(str)
  - _strings are for the standard unit size_
  - _gives ready access to sentence strings that you might want to tokenize_
- `tokenized()` – returns iter(list(token))
- `tagged()` – returns iter(list(tuple)) where tuples are (token, tag)
  - _you would need to flatten it to get the old `tagged_words()`_
- `parsed()` – returns iter(Tree)
  - _might need to be iter(list(tree)) in the case of messages and tweets that could contain multiple sentences, though they could be parse fragments linked with a dummy root node_
- `tokens()` – returns iter(str)
  - _fixes problem that old `words()` method returns tokens and not just words_
- `dicts()` – returns iter(dict)
  - _e.g. one dictionary per tweet_
- `read()` – returns a string, the whole file contents (was `raw()`)
  - _consistent with Python file objects_
- `xml()` – ElementTree for the file

This proposal does not cover the case where there are multiple unit sizes (paragraphs, documents) and where we want to group the    output for many of the above methods into extra levels of list nesting.

**Comment by nschneid** [comment]
Some collaborators and I will soon release a dependency corpus of tweets whose syntactic annotations are at the level of sub-tweet "utterances" (omitting punctuation and some metadata tokens). This could be handled by `parsed()` as discussed above; however, I believe the Foster et al. 2011 dataset fully segments each tweet into sentences that are then individually parsed. So it might be good to have a clear distinction between whole tweets and subtweet units that more closely resemble linguistic utterances or sentences.

**Comment by stevenbird** [comment]
@nschneid's point would justify `parsed()` returning iter(list(Tree)). Several other corpora have document-level units:
- `brown`, `treebank` have news stories (one per file)
- `switchboard` has discourses (several per file)
- `state_union` and `inaugural` have speech transcripts (one per file)
- `twitter` could have sentences (several per tweet), though we don't want to force tweets to be sentence-segmented

We've also been requested to support document-level processing of corpora (https://github.com/nltk/nltk/issues/66).

Are there any significant text corpora in NLTK which lack document structure?

One solution is for all text corpus methods to return an additional level of structure, and users could optionally remove it using a simple list comprehension `[sent for doc in corpus for sent in doc]`.

**Comment by ewan-klein** [comment]
@nschneid: I'm interested to know what file structure you plan to use for your corpus. Could you clarify?

**Comment by nschneid** [comment]
For our corpus, each document will be a tweet. Within each tweet, the parse annotation (a) does not necessarily include all tokens, and (b) may have multiple utterance roots—so essentially, there is a segmentation of the _included_ tokens into multiple utterances (I don't believe there is any interleaving of utterances with respect to the original token order). But tokens omitted from the parse are not really assigned to any utterance.

We could alternatively have decided to fully segment the original tweet into utterances, then provide a partial parse for each. I'm suggesting that the API make it clear which is the case, which would mean:
- tweets are **documents**
- each document may contain **metadata** such as author, date, and Twitter ID
- each document may contain one or more **utterances**
- each document may contain one or more **parses**
- for each document, if multiple utterances and multiple parses are returned, then there is an implied 1-to-1 correspondence between them; there should be a dummy entry (such as `None`) for each utterance lacking a parse in the data

There are further issues to consider with regard to tokenization: Is the number of leaf nodes in the parse (ignoring empty categories) required to be equal to the number of tokens in the utterance? Is the concatenation of the tokenized utterances required to exactly match the full tokenized tweet? Assuming the corpus also includes the raw (untokenized) version of the tweet, how should that be made available by the API, and should there be a place to store alignments between the tokenized and untokenized versions?

**Comment by ewan-klein** [comment]
Thanks, this is useful. However, when you say 

> documents are tweets / tweets are documents

do you mean _tweet_ in the sense of _status['text']_ in the JSON returned by Twitter? If not, does _status['text']_ exist as a unit in your proposal? I guess I would be inclined to say the whole Tweet object is a document, and that the user should just access this document via the keys that are made available in the default dictionary representation.

Are you planning to actually distribute the corpus, containing the full tweets? If so, how do you plan to deal with the prohibition against this in the Twitter ToS?

**Comment by stevenbird** [comment]
Some naming issues have arisen in my conversations with @ewan-klein:
- `raw()` – possible confusion with people's understanding of "raw" in `raw_string()`
- `tokens()` – unhelpfully similar to `tokenized()`
- `dicts()` – name is not semantic like the others, so consider `properties()` or `docs()` (where it can be used for document-level metadata)

**Comment by nschneid** [comment]
> do you mean tweet in the sense of `status['text']` in the JSON returned by Twitter? If not, does `status['text']` exist as a unit in your proposal?

I have not meant to propose any particular API, just a conceptual organization of tweets (including metadata) as documents, and that the relationship between syntactic parses and the tweet text string may be indirect due to tokenization, explicit utterance segmentation, and/or multiple parses.

> Are you planning to actually distribute the corpus, containing the full tweets? If so, how do you plan to deal with the prohibition against this in the Twitter ToS?

I don't know if we have made an official decision, but people I have talked to are under the impression that releasing a small corpus of randomly sampled tweets is unlikely to raise objections.

For larger Twitter datasets I know that people have released lists of IDs. Will there be an NLTK API for downloading the corresponding tweets directly from Twitter?

**Comment by ewan-klein** [comment]
> Will there be an NLTK API for downloading the corresponding tweets directly from Twitter?

Yes. It's pretty straightforward using the 'statuses/lookup' endpoint. If you're interested, checkout the twitter branch of the main NLTK github repo (though the code on this branch is still unstable). I'll post to the dev list about it soon.

**Comment by stevenbird** [comment]
Here is a new solution that has grown out of my conversations with @ewan-klein.  We'll assume that all text corpora consist of documents, e.g. books, speeches, news stories, posts, tweets. There is also a lower level of linguistic unit corresponding to the utterance or sentence. When you ask for these lower units, you get iter(iter(item)), an iterator over documents, where each document is an iterator of items, where items have a type that is predictable from the method name.
- `docs()` – returns iter(dict)
  - _contains document-level metadata_
  - _often corresponds to a file in the original corpus_
  - _has a key `string` which contains a str value_
  - _this string is the unprocessed string contents for sentence segmentation or tokenization_
  - _may have a key `xml` which contains an ElementTree value_
- `string()` – returns iter(iter(sentence-string))
  - _segmentation might have been provided in the corpus or done automatically with a sentence segmenter
  - _useful for manual tokenisation_
- `tokenized()` – returns iter(iter(list(token)))
  - _flatten this to get the old `words()`_
- `tagged()` – returns iter(iter(list(token-tag-tuples)))
  - _flatten this to get the old `tagged_words()`_
- `parsed()` – returns iter(iter(Tree))
- `chunked()` – returns iter(iter(list(string-or-tree)))

The old flat list results for `words()` and `tagged_words()` would require flattening to remove two levels of structure, i.e. `[word for doc in docs for sent in doc for word in sent]`

File level operations are not supported directly, but you can use `fileids()` to get the list of files, and then get the contents of a file like this: `open(brown.abspath('cp29')).read()`

Implications for the textbook: The `Text` object and the `nltk.book` module would know about the nested structure of these corpus access methods and still permit iteration over the tokens of a corpus without any of that structure, so chapter 1 of the book wouldn't need to change. The methods would be introduced in chapter 2.

**Comment by nschneid** [comment]
I think the above proposal makes sense. Some questions:
1. What are the formal requirements (or recommendations) about the relationships between the output of the above methods? E.g., is the tokenization expected to be identical for `tokenized()`, `tagged()`, `parsed()`, and `chunked()`?
2. Is a particular corpus reader free to add optional arguments for methods? E.g., for the Penn Treebank, `tokenized()` and `tagged()` could accept an argument specifying whether empty elements should be included (cf. #707).
3. Would the flattening be implemented for `words()`, `tagged_words()`, `sents()`, etc. in the corpus reader base classes for backward compatibility? 
4. `semcor` currently has `tagged_chunks()` for chunks that contain labels. Presumably the non-flattened version of this would be `tagged_chunked()`?
5. Suppose I want to access multiple views (e.g., original string and parsed) for each document. Assuming one file per document, `zip(docs(),parsed())` would be unnecessarily slow because each file would have to be read twice. Will the API provide a better way? `next(docs())['parsed']`?
6. To decouple the results of sentence segmentation and word tokenization, perhaps `next(docs())['strings']` should be an iterator over segmented but untokenized sentence-strings (for corpora where this is applicable)?

**Comment by stevenbird** [comment]
Thanks for the feedback @nschneid. Here's my current thinking; I'd welcome your thoughts.
1. It would be recommended that the various methods use compatible segmentations of the source string. However, it's conceivable that a particular corpus will leave out key details (e.g. a corpus that provides sentence-segmented and parsed tweets may not provide the sentence strings, and our own sentence segmenter might break them up differently; the parse trees may leave out punctuation making it impossible to reconstruct sentence strings from the trees). Are there other requirements or recommendations to consider other than compatible segmentations?
2. Yes, additional named arguments would be permitted.
3. Yes, we would provide these methods for backwards compatibility, though I propose that they would be deprecated, and eventually removed. It just takes a line of code to do the flattening, and it is good for people to be reminded that they are doing this (e.g. avoid creating an n-gram tagger than blindly considers contexts that cross document boundaries).
4. I'd prefer to avoid too many methods for semcor if possible. A single `parsed()` method might be adequate, just requiring the programmer to extract the necessary pieces.
5. I don't have a solution here.
6. I'm not sure why this would be necessary when `strings()` and `tokenized()` already do the work. There's no stipulation that the implementation of tokenization involves sentence segmentation as a first step.

**Comment by nschneid** [comment]
> I'm not sure why this would be necessary when `strings()` and `tokenized()` already do the work. There's no stipulation that the implementation of tokenization involves sentence segmentation as a first step.

Oh I think I must have misinterpreted the former (it is called `string()` in the earlier post). It provides each sentence prior to tokenization, correct? And if the corpus does not include pre-tokenized sentences, should it return `None`?

**Comment by stevenbird** [comment]
That's correct. If the corpus doesn't include pre-segmented sentences, I propose that we use a sentence segmenter (by analogy with our use of a tokenizer for corpora that are not tokenized). We could return a `NotImplementedError` if the sentence segmenter does not support the language. Perhaps the method should be called `strings()` given that we get an iterator.

**Comment by nschneid** [comment]
Yeah I think `strings()` is more intuitive.

> If the corpus doesn't include pre-segmented sentences, I propose that we use a sentence segmenter (by analogy with our use of a tokenizer for corpora that are not tokenized).

Provided there's a way to check whether the segmentation was gold standard, or from NLTK's segmenter.

**Comment by RahulRavindren** [comment]
@nschneid @stevenbird  I would like to help out with the API for this. Would be wonderful if you would let me know.

**Comment by stevenbird** [comment]
It looks like this issue is resolved. Please re-open if I'm wrong, thanks.
