### ISSUE TITLE
ViterbiParser

### ISSUE THREAD

**Issue by mohammadsadeghzadeh** [nltk/nltk#729]
i install python 3.4.1 32 bit version and nltk3.
when i use:
grammar = nltk.induce_pcfg(S, productions)
parser = ViterbiParser(grammar)
tree=parser.parse(toks);
print(tree)

then python instead of printing tree, prints "generator object parse at 0x054CBB48"

why??

**Comment by stevenbird** [comment]
The `parse()` methods return generators. Iterate over these to access the trees. E.g. `for tree in parser.parse(toks): print tree`.

We need to update the parse package docstring to explain this.

**Comment by mohammadsadeghzadeh** [comment]
How can i get the best tree? 
Is it parse_one()?

**Comment by mohammadsadeghzadeh** [comment]
My productions contain  1200 rules. and when i use this grammar it takes long time (3 or 5 minutes on average) to parse a sentence with 25 words in ViterbiParser. 
I don't think that Viterbi algorithm is slow in nature, because Stanford Parse that implemented this algorithm in java is fast. 
What do you think?
for parsing 50 sentences i have to wait at least 2 hour. what's wrong with it?

**Comment by heatherleaf** [comment]
The current implementation of Viterbi parsing in NLTK is not the most efficient one. It is more useful as a tool for experimenting with probabilistic parsing and not for "real" work.

If you look at the source code, in the file nltk/parse/viterbi.py, you see that it's not optimized for large grammars: e.g., on lines 242-243 you can see that it loops through all grammar productions and tries to match them one by one. There are other approaches that work better, especially if you optimize your data structures. 

You are very welcome to experiment with different Viterbi implementations and suggest improvements to the current one.

**Comment by mohammadsadeghzadeh** [comment]
It is very very very very slow . You don't believe how it is slow.
Stanford parser with java does this stuff only in 1 sec. But nltk takes 1 hour. That's very very bad.

**Comment by stevenbird** [comment]
Remember that NLTK's goal is pedagogical. We've provided a wrapper for the Stanford Parser, so you can easily combine the two.
