### ISSUE TITLE
Stanford tokenizer -- request to add -outputFormat inlineXML

### ISSUE THREAD

**Issue by Liontooth** [nltk/nltk#735]
The NLTK.tokenize.stanford class provides access to the stanford-postagger, with these options:

class nltk.tokenize.stanford.StanfordTokenizer(path_to_jar=None, encoding='UTF-8', options=None, verbose=False, java_options='-mx1000m')

``` python```
 >>> from nltk.tokenize.stanford import StanfordTokenizer
 >>> st = StanfordTokenizer(
 '/software/java/stanford-POS/stanford-postagger-2014-06-16/stanford-postagger.jar', 'utf-8')
 >>> st.tokenize(s)
 [u'Good', u'muffins', u'cost', u'$', u'3.88', u'in', u'New', u'York', u'.', u'Please', u'buy', u'me', u'two',
 u'of', u'them', u'.', u'Thanks', u'.']
```

This works, but there is no explicit sentence divider in this slashTags format. However, in -outputFormat  inlineXML, sentence boundaries are explicit. Is there a way to pass this option to the postagger?

It would seem the options= switch should work, but alas:

``` python
>>> st = StanfordTokenizer('/software/java/stanford-POS/stanford-postagger-2014-06-16/stanford-postagger.jar', 'utf-8', java_options='-mx300m', options='-outputFormat inlineXML')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/nltk/tokenize/stanford.py", line 50, in __init__
    self._options_cmd = ','.join('{0}={1}'.format(key, json.dumps(val)) for key, val in options.items())
AttributeError: 'str' object has no attribute 'items'
```

Cheers,
Dave

**Comment by longdt219** [comment]
Please note that -outputFormat inlineXML is not the correct option for stanford tokenizer. It is the option for POS MaxEnt tagger.

Here is the list of valid options : 
https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/process/PTBTokenizer.java

For the purpose of keeping the newline we should do 
==> st = StanfordTokenizer('/software/java/stanford-POS/stanford-postagger-2014-06-16/stanford-postagger.jar', 'utf-8', java_options='-mx300m', options={"tokenizeNLs": True})
==> st.tokenize(s) 
[u'Good', u'muffins', u'cost', u'$', u'3.88', u'*NL*', u'in', u'New', u'York', u'.', u'Please', u'buy', u'me', u'*NL*', u'two', u'of', u'them', u'.', u'*NL*', u'Thanks', u'.']

I will modify the code for doing this.

**Comment by longdt219** [comment]
I created a pull request, could you check and close this issue @stevenbird

**Comment by stevenbird** [comment]
Resolved by https://github.com/nltk/nltk/commit/66c9292603e73e6c7ea1ef8c093421d6e068b3a7
