### ISSUE TITLE
object has no attribute 'batch_ne_chunk'

### ISSUE THREAD

**Issue by rajbala** [nltk/nltk#739]
When I execute this code I get an error:

```
import nltk

corpus = "This is a sentence."
sentences = nltk.sent_tokenize(corpus)
tokenized = [nltk.word_tokenize(sentence) for sentence in sentences]
pos_tags  = [nltk.pos_tag(sentence) for sentence in tokenized]
nltk.batch_ne_chunk(pos_tags, binary=True)
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'batch_ne_chunk'

I'm using nltk 3.0.0b2 on Python 2.7.5 on OSX, but the same thing happens on Ubuntu.  

Am I missing something obvious?

**Comment by stevenbird** [comment]
Please see the last of API changes for NLTK 3.

**Comment by kmike** [comment]
To be fair, batch_ne_chunk change is not documented at https://github.com/nltk/nltk/wiki/Porting-your-code-to-NLTK-3.0

**Comment by rajbala** [comment]
@kmike Can you point me to what I should be using instead of batch_ne_chunk() considering the API changes?

**Comment by kmike** [comment]
@rajbala sorry for not telling you earlier! It was renamed to `nltk.ne_chunk_sents`.

**Comment by rajbala** [comment]
@kmike Thank you kindly!

**Comment by sourcedexter** [comment]
But, with ne_chunk_sents , the output is not a tree output. It just says
generator object <genexpr> at ... 
what can I do ?

**Comment by stevenbird** [comment]
Iterate over it.

**Comment by rsingh2083** [comment]
Iterate over what ? It doesnt have any thing which could be iterated over. .close/.throw.gi_running.... all these arent iterable

**Comment by nschneid** [comment]
Like this:

``` python
for chunk in nltk.ne_chunk_sents(pos_tags, binary=True):
    print(chunk)
```

Generators are a Python language feature that can act like lazy sequences: they can be iterated over to give you the next item on demand. http://www.dabeaz.com/generators/ is a nice in-depth tutorial.
