### ISSUE TITLE
lambda abstract in chat80.doctest gives wrong value

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#74]
This line currently fails because lambda expressions evaluate to giving the
whole dictionary. 

   &gt;&gt;&gt; m.evaluate(r'\x .population_of(jakarta, x)', g)
   {'533': True}

It would be preferable to have the value be:

   [('533',)] 

like other one-place predicates but I'm still not sure how to achieve this.
In the interim, I'm removing this line from the doctest.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=421</p>

**Comment by kmike** [comment]
This is already fixed: see https://github.com/nltk/nltk/commit/8e6dc042048152090f2a14c70a22e5c1f3ffbbaa
