### ISSUE TITLE
nltk in Python 3.4 pos_tag issue?

### ISSUE THREAD

**Issue by will3784** [nltk/nltk#741]
I'm trying to brush up on NLTK because I'm going to need some of its functions when I'm working on my senior thesis this fall. I figured that starting with a POS tagger would be fine, but whenever I try to tag something I get this error:

Traceback (most recent call last):
  File "<pyshell#22>", line 1, in <module>
    pos_tag_sents(sents)
  File "C:\Python34\lib\site-packages\nltk\tag__init__.py", line 108, in pos_tag_sents
    tagger = load(_POS_TAGGER)
  File "C:\Python34\lib\site-packages\nltk\data.py", line 779, in load
    resource_val = pickle.load(opened_resource)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 0: ordinal not in range(128)

I tried Googling it, and went to the files that it's talking about to see if anything is wonky, but I couldn't find anything. I was doing exactly what the NLTK book (NLP With Python) said, but it wouldn't work. Whether I accidentally messed something up or it's a problem with the NLTK stuff in Python 3.4, I would really appreciate it if someone could help me out.

**Comment by kmike** [comment]
Hi @will3784,

Do you use latest NLTK beta, and is nltk data up to date?

**Comment by will3784** [comment]
I downloaded the version of nltk that was on the "installing nltk" page on the website. I have it installed for python 2.7 too (the 3.2+ version wasn't ready when I was using it before) and it works fine there. When I go to try to install the book data, etc., it says it's out of date but I am unsure how to update it.

**Comment by stevenbird** [comment]
Please see the instructions here for installing (updating) the NLTK data:
http://www.nltk.org/data.html

**Comment by JosephHickey** [comment]
I have the same problem mentioned by will3784 on 2014-08-30. 

On 2014-09-26, I installed Python 3.4.1. On the same day, I installed NLTK 3.0.0 (by downloading and executing the file nltk-3.0.0.win32.exe from the following link: https://pypi.python.org/pypi/nltk

I successfully installed "all", "all-corpora", and "book" using nltk.download(). 

I am able to use word_tokenize to tokenize a string, but when I attempt to use pos_tag, I receive the same error that will3784 has entered above. 

Would appreciate assistance.

**Comment by brightsmall** [comment]
Hello,

I have the same configuration and issue as JosephHickey.  I'm running NLTK 3.0.0 on Python 3.4.1 on Windows 7.  I also updated my data as suggested by stevenbird

My code is:

import nltk
text = nltk.word_tokenize("the man jumped over the white fence")
nltk.pos_tag(text)

Results is:

UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-8-204972655b93> in <module>()
      1 text = nltk.word_tokenize("the man jumped over the white fence")
----> 2 nltk.pos_tag(text)

C:\Users\bsmal725\AppData\Local\Continuum\Anaconda3\lib\site-packages\nltk-3.0.0-py3.4.egg\nltk\tag__init__.py in pos_tag(tokens)
     98     :rtype: list(tuple(str, str))
     99     """
--> 100     tagger = load(_POS_TAGGER)
    101     return tagger.tag(tokens)
    102 

C:\Users\bsmal725\AppData\Local\Continuum\Anaconda3\lib\site-packages\nltk-3.0.0-py3.4.egg\nltk\data.py in load(resource_url, format, cache, verbose, logic_parser, fstruct_reader, encoding)
    777         resource_val = opened_resource.read()
    778     elif format == 'pickle':
--> 779         resource_val = pickle.load(opened_resource)
    780     elif format == 'json':
    781         import json

UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 0: ordinal not in range(128)

**Comment by stevenbird** [comment]
I can't replicate this on mac osx with python 3.4.2:

```
>>> import nltk
>>> text = nltk.word_tokenize("the man jumped over the white fence")
>>> nltk.pos_tag(text)
[('the', 'DT'), ('man', 'NN'), ('jumped', 'VBD'), ('over', 'IN'), ('the', 'DT'), ('white', 'JJ'), ('fence', 'NN')]
```

**Comment by brightsmall** [comment]
Okay, Thanks for taking a look.  I'll try upgrading to python 3.4.2.

**Comment by zultuta** [comment]
Hello,
I am facing the same problem. I have python 3.4.2 installed on my windows 8 and i installed and updated all nltk data. However, when i tried to perform the pos tagging example as specified in the nltk book, i get this error 

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    tagged = nltk.pos_tag(tokens)
  File "C:\Python32\lib\site-packages\nltk\tag__init__.py", line 100, in pos_tag
    tagger = load(_POS_TAGGER)
  File "C:\Python32\lib\site-packages\nltk\data.py", line 779, in load
    resource_val = pickle.load(opened_resource)
ImportError: No module named numpy.core.multiarray

I removed python 3.4.2 and tried it again with python 3.4.1 and with python 3.2.5, and am still getting the error, i couldn't tag anything. Help on this would be very much appreciated. Please!

**Comment by brightsmall** [comment]
Zultuta, 

This apparently has to do with encoding.  I used the fix suggested on this link: 
http://stackoverflow.com/questions/25590089/nltk-3-pos-tag-throws-unicodedecodeerror

The fix is to go into data.py and edit line 779 to use a different encoding.  I changed my encoding to latin1 and it started working.

**Comment by JosephHickey** [comment]
Following up from my comment of 2014-09-28, I installed the win32.exe file at the following site, and it worked for me: http://www.nltk.org/nltk3-alpha/

**Comment by zultuta** [comment]
brightsmall, JosephHickey

Thank you so much. I changed the encoding and now its working

**Comment by sandeepcd** [comment]
where can i find data.py file?
i also getting same error as above
