### ISSUE TITLE
nltk.clean_html()  probably going into an infinite loop.

### ISSUE THREAD

**Issue by harshil93** [nltk/nltk#744]
I tried nltk.clean_html() with this file and it never exits. I waited for around 420 mins. The file contains a lot of span tags and new lines. I also found that html2text (aaronsw) also crashes on this file.
I am using python-nltk 2.0~b9-0ubuntu4 installed from the ubuntu's official repo.

https://dl.dropboxusercontent.com/u/32632425/170594

My code : 

import nltk
inp = open("170594","r").read()
cleaned = nltk.clean_html(inp) #hangs here

This is what I get when i press Ctrl + C.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/nltk/util.py", line 332, in clean_html
    cleaned = re.sub(r"(?is)<(script|style)._?>._?(</\1>)", "", html.strip())
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)

**Comment by stevenbird** [comment]
`clean_html` was dropped in NLTK 3. Please use  use BeautifulSoup's get_text() function instead.

**Comment by harshil93** [comment]
@stevenbird - Thanks for pointing out this. I am wondering whether get_text() is as fast as clean_html is? If not I will probably see lxml.
