### ISSUE TITLE
Pushing latest stable version of NLTK into apt-get repos

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#747]
Is there any plan to update the `apt-get` repos for NLTK installation? 

There are some users that don't rely on `pip` to install python tools, e.g. http://askubuntu.com/questions/527388/python-nltk-on-ubuntu-12-04-lts-nltk-downloadbrown-results-in-html-error-40

Does anyone know how to resolve the 401 Error when downloading NLTK corpus?

**Comment by alvations** [comment]
While the version from apt-get is not updated, the current "hack" is to change the URL in download.py

**Comment by PanderMusubi** [comment]
NLTK 3.0.4 is scheduled for Ubuntu 15.10, see https://launchpad.net/ubuntu/+source/nltk and 3.0.0 is currently distributed via apt-get. If this issue has been fixed, can it be closed?

**Comment by alvations** [comment]
@PanderMusubi , Cool, now `sudo apt-get python-nltk` get NLTK v3.1!

**Comment by stevenbird** [comment]
Thanks @PanderMusubi
