### ISSUE TITLE
Update sourceforge links

### ISSUE THREAD

**Issue by he7d3r** [nltk/nltk#753]
On [stem/porter.py](https://github.com/nltk/nltk/blob/master/nltk/stem/porter.py#L86) there is a comment which says:
"The nltk version of this module is maintained by the NLTK developers, and is available from http://nltk.sourceforge.net"

The same link is present in [other parts of the code](https://github.com/nltk/nltk/search?utf8=%E2%9C%93&q=%22nltk.sourceforge.net%22&type=Code).

Shouldn't thes links point to GitHub instead? (https://github.com/nltk/nltk)

**Comment by stevenbird** [comment]
@ewan-klein does the [examples directory](https://github.com/nltk/nltk/search?utf8=%E2%9C%93&q=%22nltk.sourceforge.net%22&type=Code) belong in the source tree?

**Comment by he7d3r** [comment]
But shouldn't the links be updated to point to the GitHub repository?

**Comment by stevenbird** [comment]
@he7d3r please see my earlier commit above. Or are you referring to some other sourceforge link?

**Comment by he7d3r** [comment]
If I understood correctly, the code was moved to the nltk_teach repo, but since the links were not changed, we still have [21 code results on nltk_teach](https://github.com/nltk/nltk_teach/search?utf8=%E2%9C%93&q=nltk.sourceforge.net) and the [14 code results on nltk repo](https://github.com/nltk/nltk/search?utf8=%E2%9C%93&q=%22nltk.sourceforge.net%22&type=Code).
