### ISSUE TITLE
Replace Spanish suffixes by Portuguese suffixes in the Portuguese snowball stemmer

### ISSUE THREAD

**Issue by he7d3r** [nltk/nltk#754]
On [stem/snowball.py](https://github.com/nltk/nltk/blob/c23c18de204961b513947e5c593a196d06fdd6ee/nltk/stem/snowball.py#L2433-L2438), there are a few suffixes in the PortugueseStemmer which I believe were copied by mistake from SpanishStemmer:
- `'log\xEDas'` should be `'logias'`
- `'log\xEDa'` should be `'logia'`
- `'uciones'` should be `'uções'`
- `'uci\xF3n'` should be `'ução'`

Indeed, there isn't a single word containing the strings "logía", "uciones" or "ución" in the vocabulary provided on
[snowballstem/snowball-data/master/portuguese/voc.txt](https://raw.githubusercontent.com/snowballstem/snowball-data/master/portuguese/voc.txt)
(and, as one could expect, these are common on
[snowballstem/snowball-data/master/spanish/voc.txt](https://raw.githubusercontent.com/snowballstem/snowball-data/master/spanish/voc.txt))

The error is also present in the original [description of the Portuguese stemming algorithm](http://snowball.tartarus.org/algorithms/portuguese/stemmer.html), but it is unlikely that the site will be updated, since the authors decided to freeze their SVN:
http://thread.gmane.org/gmane.comp.search.snowball/1531

**Comment by stevenbird** [comment]
Thanks!

**Comment by he7d3r** [comment]
It seems the patch introduced unwanted changes to the Spanish stemmer (see comments on 986d103). I reported this as issue #773.

**Comment by stevenbird** [comment]
Oops, thanks for fixing my mistakes here.

**Comment by he7d3r** [comment]
For the record, I reported it on snowballstem/snowball-website#1 too, just in case.
