### ISSUE TITLE
Treat "ü" as "u" in the Portuguese stemmer

### ISSUE THREAD

**Issue by he7d3r** [nltk/nltk#755]
I believe the accented letter "ü" should be treated as "u" in some cases. For example, the stem of the following words should be the same (i.e. "aguent"):
- aguenta
- agüenta
- aguentam
- aguentamos
- aguentar
- aguentava
- agüentava
- aguente
- agüente
- aguento
- agüento
- aguentou
- agüentou

However, the ones with "ü" are being converted to "agüent".

**Comment by stevenbird** [comment]
Is there any reference to support this? Isn't it a separate and more general step to normalise forms across different versions of [Portuguese orthography](http://en.wikipedia.org/wiki/Reforms_of_Portuguese_orthography)?

**Comment by he7d3r** [comment]
Consider for example this:
https://github.com/apache/lucene.net/blob/master/src/contrib/Analyzers/BR/BrazilianStemmer.cs#L306-L310

Is there a normalization step like the one you mentioned for some other language with different orthographies?
