### ISSUE TITLE
Remove word suffixes consistently (and only once) on snowball stemmers

### ISSUE THREAD

**Issue by he7d3r** [nltk/nltk#756]
While comparing the Portuguese and Spanish stemmers I noticed they use different methods to remove the suffixes. For example:
- [SpanishStemmer](https://github.com/nltk/nltk/blob/c23c18de204961b513947e5c593a196d06fdd6ee/nltk/stem/snowball.py#L3479-L3487) uses `word = word.replace(suffix, ...)`
- PortugueseStemmer, FrenchStemmer and others uses `word = "".join((word[:-len(suffix)], ...))`

I believe the code should use only the second form, both for consistency and because the first form can potentially replace more than one occurrence of the suffix (although that should not happen in practice).

**Comment by stevenbird** [comment]
I agree, @he7d3r . Additionally, it would be good to refactor the code slightly, and provide a `suffix_replace` function. Is this something you could do, and submit a PR please?
