### ISSUE TITLE
Portuguese snowball stemmer should remove suffixes "ança" and "anças"

### ISSUE THREAD

**Issue by he7d3r** [nltk/nltk#757]
If we compare the snowball code of the Portuguese and Spanish stemmers, we see that the Spanish suffixes "anza" and "anzas" were changed to "eza" and "ezas". However, the Portuguese equivalent of words such as "esperanza", "venganza", etc are "esperança", "vingança", etc.

So, in the Portuguese stemmer, we are missing the suffixes "ança" and "anças" which are found in many words. This does not need to **replace** the suffixes "eza" and "ezas" (i.e, these can be kept), because they also appear in many words.

This would make the stem of "esperança" to be "esper" instead of "esperanc" (which matches the behavior in Spanish: "esperanza" -> "esper").

**Comment by stevenbird** [comment]
@he7d3r should "ança" and "anças" be step 1 suffixes?

**Comment by he7d3r** [comment]
Yeah, I think so.
