### ISSUE TITLE
from compat import * breaks on Python 2.6.2

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#77]
What version of NLTK are you using? 

Python version: 
Python 2.6.2 (r262:71600, Aug 31 2009, 11:32:13) 
[GCC 4.0.1 (Apple Inc. build 5465)] on darwin

NLTK version is: 2.0b5

What steps will reproduce the problem?

I did a fresh checkout of NLTK from SVN. In the NLTK directory that
contains the **init**.py and compat.py doing:

&gt;&gt;&gt; from compat import *
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
AttributeError: 'module' object has no attribute 'all'

The problem seems to be that compat.py defines **all** as:
**all** = ['ElementTree', 'defaultdict', 'all']

Since Python 2.6 has the 'all' function the function definition is skipped
in the compat module. Thus importing compat.all fails.

A way to fix this is to add the following line before the definition of
**all**:
all = all 

The attached patch file does exactly that.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=437</p>

**Comment by kmike** [comment]
compat.py was gone (and re-introduced again in 2and3 branch). I think this ticket no longer applies.

**Comment by alexrudnick** [comment]
Yep, compat.py is gone. Stale issue, closing!
