### ISSUE TITLE
Missing parse_cfg

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#771]
Does anyone know where has the `parse_cfg` function been shifted to? Has it been deleted?
Some of my example scripts that uses `nltk.parse_cfg()` can no longer work.

It couldn't be found in `parse` module in the `dev` branch too:

```
alvas@ubi:~/git/nltk/nltk/parse$ grep "parse_cfg" *
alvas@ubi:~/git/nltk/nltk/parse$
```

Related SO post:
http://stackoverflow.com/questions/26415163/python-nltk-cant-import-parse-cfg

**Comment by stevenbird** [comment]
Please see the documentation for [NLTK 3 API changes](https://github.com/nltk/nltk/wiki/Porting-your-code-to-NLTK-3.0)

**Comment by alvations** [comment]
Thank you for the note of the updated API. 

In the case of `grammar.parse_cfg()`, it should have been, the API update refers to `ContextFreeGrammar.fromstring()` instead of `CFG.fromstring()`

`grammar.parse_cfg()` -> `CFG.fromstring()` 

because 

`grammar`: `ContextFreeGrammar` → `CFG`

**Comment by stevenbird** [comment]
Sorry about that; I've fixed the mistake.
