### ISSUE TITLE
BLEU score returns 1 (perfect match) instead of zero

### ISSUE THREAD

**Issue by karpathy** [nltk/nltk#775]
Hi, taken from bleu implementation:

``` python
    @staticmethod
     def compute(candidate, references, weights):
        candidate = [c.lower() for c in candidate]
        references = [[r.lower() for r in reference] for reference in references]

        p_ns = (BLEU.modified_precision(candidate, references, i) for i, _ in enumerate(weights, start=1))
        s = math.fsum(w * math.log(p_n) for w, p_n in zip(weights, p_ns) if p_n)

        bp = BLEU.brevity_penalty(candidate, references)
        return bp * math.exp(s)
```

This function incorrectly returns BLEU score 1 when the candidate has no alignment to any of the references. In this case, `p_ns` will be all zeros because there is no overlap for any n-grams, which will make `s` zero, which will return `1` at the end.

There should be a special case check for the case when there is zero alignment and return zero correctly.

**Comment by dimazest** [comment]
@karpathy could you have a look to my fix.

**Comment by karpathy** [comment]
Yep, that's very similar to how I fixed it in my own implementation. Thanks!
