### ISSUE TITLE
SpanishStemmer error with certain terms

### ISSUE THREAD

**Issue by gcapiel** [nltk/nltk#778]
All these terms:
['tgue','argue', 'lgue', 'ungue', 'igue' ]

Give this error when you try to stem any of them:
warning: range error for conversion to character value
Traceback (most recent call last):
  File "./spanishstemmer.py", line 13, in <module>
    singles.append(stemmer.stem(words.decode('utf-8')))
  File "/usr/local/lib/python2.7/dist-packages/nltk/stem/snowball.py", line 3554, in stem
    if word[-2:] == "gu" and rv[-1] == "u":
IndexError: string index out of range

**Comment by stevenbird** [comment]
@he7d3r would you mind taking a look at this please?

**Comment by he7d3r** [comment]
I confirmed this problem using Python 3.4

``` python
>>> from nltk.stem.snowball import SnowballStemmer
>>> SnowballStemmer('spanish').stem('tgue')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/lib/python3.4/site-packages/nltk/stem/snowball.py", line 3554, in stem
    if word[-2:] == "gu" and rv[-1] == "u":
IndexError: string index out of range
```

At that point of the code, `rv` is the empty string (in all 5 examples), so `rv[-1]` causes the error.

**Comment by stevenbird** [comment]
Thanks @he7d3r. Can you suggest a fix please?

**Comment by he7d3r** [comment]
Looks like replacing `rv[-1] == "u"` by any of these should work:
- `rv[-1:] == "u"`
- `rv.endswith("u")`
- `rv and rv[-1] == "u"`

(I don't know which one is more "Pythonic")

**Comment by he7d3r** [comment]
BTW: it seems [that if/else block](https://github.com/nltk/nltk/blob/f422e337313b81581a5c13345f6803f3510c2adc/nltk/stem/snowball.py#L3550-L3557) can be simplified a little, since `word = word[:-len(suffix)]` is executed in both cases.
