### ISSUE TITLE
BNC corpus reader slowness

### ISSUE THREAD

**Issue by dimazest** [nltk/nltk#781]
In my experience BNC corpus reader is too slow. I would like it to be faster to use it in NLP related workshops.

It seems that [BNCCorpusWordView](https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/bnc.py#L155) is slow because it's a subclass of [XMLCorpusView](https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/xmldocs.py#L86) which has a rather complicated logic because it's meant to handle any XML based corpus.

I suppose that most of the people are using this [BNC distribution](http://www.ota.ox.ac.uk/desc/2554) (and if they don't, they really should!). So, most of generality of XMLCorpusView is not needed, for example, encoding detection.

To speed up BNC corpus reader and make it's code simple to comprehend, I suggest to base it on CorpusReader and use xml.sax module to parse xml files.

Is there a documentation that specify what methods a corpus reader must/should provide? Maybe in a narrative form? If not, I'm also willing to start writing. it.

**Comment by rmalouf** [comment]
You're right that replacing the XMLCorpusView implementation with a standard XML parser would be a big improvement, but in the short term there's a way to bypass most of nltk's extra overhead.  If you set `lazy=False` when you open the corpus, it uses ElementTree to parse the xml files directly rather than nltk's incremental XML parser.  This speeds things up dramatically:

```
In [27]: bnc = nltk.corpus.BNCCorpusReader('/opt/corpora/bnc_xml/',
   ....:                                   fileids=r'[A-K]/\w*/\w*\.xml', 
   ....:                                   lazy=True)

In [28]: %time len(bnc.tagged_sents(bnc.fileids()[:20]))
CPU times: user 7.57 s, sys: 53 ms, total: 7.63 s
Wall time: 7.63 s
Out[28]: 34192

In [29]: %time len(bnc.words(bnc.fileids()[:20]))
CPU times: user 11.6 s, sys: 29 ms, total: 11.6 s
Wall time: 11.6 s
Out[29]: 636258

In [30]: bnc = nltk.corpus.BNCCorpusReader('/opt/corpora/bnc_xml/',
   ....:                                   fileids=r'[A-K]/\w*/\w*\.xml', 
   ....:                                   lazy=False)

In [31]: %time len(bnc.tagged_sents(bnc.fileids()[:20]))
CPU times: user 2.74 s, sys: 19 ms, total: 2.76 s
Wall time: 2.76 s
Out[31]: 34192

In [32]: %time len(bnc.words(bnc.fileids()[:20]))
CPU times: user 2.2 s, sys: 5 ms, total: 2.2 s
Wall time: 2.2 s
Out[32]: 636258
```

**Comment by dimazest** [comment]
Good to know, maybe this should be documented.

**Comment by alvations** [comment]
@stevenbird I think the modern day machines can handle the XML file size, should we set the default value for `lazy` should be set to False.
