### ISSUE TITLE
paths in compat.py

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#783]
Use `os.path.join()` to concatenate paths, in `compat.py`, cf https://github.com/nltk/nltk/pull/777

**Comment by Dobatymo** [comment]
was fixed here https://github.com/nltk/nltk/pull/1226 wasn't it?

**Comment by alvations** [comment]
Yes, it resolved in #1226. Thanks for catching this! 

And also thank you for spotting the other lingering issues on the tracker that should have been resolved =)

**Comment by stevenbird** [comment]
Yes, thanks @Dobatymo
