### ISSUE TITLE
Problem when pickling Tokenizers

### ISSUE THREAD

**Issue by bruno-vollino** [nltk/nltk#784]
Hi, 

I've had problems when trying to dump tokenizer classes using pickle. I'm not very experienced in Python, so I don't know how to solve this. You may reproduce the errors using the following code.

import nltk
import pickle
import dill
from dill import detect

to_dump = nltk.tokenize.regexp.WordPunctTokenizer()

print("Bad types:")
print(detect.badtypes(to_dump))
print("Bad items:")
print(detect.baditems(to_dump))
print("Bad objects:")
print(detect.badobjects(to_dump))
print("Errors:")
print(detect.errors(to_dump))
with(open('example.pickle', 'w')) as file:
    pickle.dump(to_dump, file)

$ python nltk_pickle.py 

Bad types:
<class 'nltk.tokenize.regexp.WordPunctTokenizer'>
Bad items:
[WordPunctTokenizer(pattern=u'\w+|[^\w\s]+', gaps=False, discard_empty=True, flags=56)]
Bad objects:
WordPunctTokenizer(pattern=u'\w+|[^\w\s]+', gaps=False, discard_empty=True, flags=56)
Errors:
first argument must be string or compiled pattern

**Comment by stevenbird** [comment]
I think this error is produced by re.compile when we attempt to reload the pickled object. I don't understand why re.compile is being called, since [when a class instance is unpickled, its **init**() method is usually not invoked](https://docs.python.org/3/library/pickle.html#pickle-inst).

**Comment by stevenbird** [comment]
This was resolved in #839.
