### ISSUE TITLE
NLTK WSD with adjective POS tag as parameter

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#785]
The word "able" has adjective but `nlkt.wsd.lesk` is not returning the sense:

```
>>> from nltk.corpus import wordnet as wn
>>> wn.synsets('able')
[Synset('able.a.01'), Synset('able.s.02'), Synset('able.s.03'), Synset('able.s.04')]
>>> sent = "people should be able to marry a person of their choice"
>>> nltk.wsd.lesk(sent, 'able')
Synset('able.s.04')
>>> nltk.wsd.lesk(sent, 'able', pos='a')
>>> 
```

see https://groups.google.com/forum/#!topic/nltk-users/KPcL2iUZ0u0

(self-assign)

**Comment by dimazest** [comment]
Try passing the context sentence as a list of tokens:

```
nltk.wsd.lesk(sent.split(), 'able')
```

Another option would be to checkout nltk from the repo and use development branch.

**Comment by alvations** [comment]
@dimazest , thanks for the fix!! Unpacking the messed up generator comprehension was a good idea. 

Does anyone know whether the original lesk algorithm from 1986 filters out the POS? I sort of remember that the original lesk didn't have the POS specification. Nevertheless, it would be good to have that feature in NLTK. I've left it out in the `pywsd` repo.

**Comment by alvations** [comment]
I did a quick check on the original lesk algorithm, it didn't have the POS specific. Added the note in the docstring. http://dl.acm.org/citation.cfm?id=318728
