### ISSUE TITLE
app.chunkparser() malfunctioning

### ISSUE THREAD

**Issue by peter-wood** [nltk/nltk#787]
chunkparser.app() does not work in the current python 2 and python 3 versions. Exceptions are thrown in lines 1072 and 1038 of the application which has the effect that chunk rules are not applied and the application is unresponsive and does not update the highlighting, or success rate. 
Fix:  replace the 3 occurrences of 
RegexpChunkRule.parse(line)
to 
RegexpChunkRule.fromstring(line)
This should be fixed as the application is important to work through chapter 7 of the textbook.

**Comment by stevenbird** [comment]
Thanks for the bug report.
