### ISSUE TITLE
Critical bug in BLEU score evaluation

### ISSUE THREAD

**Issue by karpathy** [nltk/nltk#789]
The BLEU score, as computed [here](https://github.com/nltk/nltk/blob/develop/nltk/align/bleu.py), returns extremely broken results

It's currently implemented as:

``` python
p_ns = (BLEU.modified_precision(candidate, references, i)
                for i, _ in enumerate(weights, start=1))
p_ns_nonzero = list(filter(None, p_ns))
if p_ns_nonzero:
  s = math.fsum(w * math.log(p_n) for w, p_n in zip(weights, p_ns_nonzero))
  bp = BLEU.brevity_penalty(candidate, references)
   return bp * math.exp(s)
else: # no alignments
  return 0
```

Now, what the `s =` part is doing is it's trying to compute a weighted **geometric average**, meaning the product of the individual modified precisions, to get the final precision across ngrams. Therefore, you cannot simply take out the `p_ns` that are zero by doing the filtering. If any one of the `p_ns` is zero, that should make the entire score zero.

I suggest something like the following:

``` python
p_ns = [BLEU.modified_precision(candidate, references, i) for i, _ in enumerate(weights, start=1)]
if all([x > 0 for x in p_ns]):
    s = math.fsum(w * math.log(p_n) for w, p_n in zip(weights, p_ns))
    bp = BLEU.brevity_penalty(candidate, references)
    return bp * math.exp(s)
else: # bad
    return 0
```

The paper reference on BLEU score where all of this is discussed is here:
http://www.aclweb.org/anthology/P02-1040.pdf

**Comment by stevenbird** [comment]
Thanks @karpathy. @dimazest would you please look into this?

**Comment by dimazest** [comment]
ahh, i see. i'll also try to come up with a test for this situation.

btw, do you think it will be useful to remove the BLEU class and make its static methods just functions?

**Comment by stevenbird** [comment]
Good idea, please remove the BLEU class. Note that names within subpackages must be meaningful without their module name, because we import all names directly in `__init__.py`. So the evaluation function name(s) should include `bleu`. Names for internal use would generally be preceded by underscore.
