### ISSUE TITLE
Lookup error when using stanford ner  in nltk

### ISSUE THREAD

**Issue by RahulKulhari** [nltk/nltk#792]
LookupError: 
# 

NLTK was unable to find the java file!
Use software specific configuration paramaters or set the JAVAHOME environment variable.

and when i am doing echo $JAVA_HOME

it is telling me path correctly

**Comment by stevenbird** [comment]
Please give a small code sample that produces this error, thanks.

**Comment by RahulKulhari** [comment]
This Error is happening only in nltk 3.0 but i replace nltk 3.0 to nltk 2.0.4 so now its working.

**Comment by stevenbird** [comment]
Please give a small code sample that produces this error, thanks.

**Comment by AlexYoung757** [comment]
when i use stanford word segmenter ,  here is code :
import nltk
from nltk.tokenize.stanford_segmenter import StanfordSegmenter

segmenter = StanfordSegmenter(
	path_to_jar = "./stanford_segmenter/stanford-segmenter-3.6.0.jar", 
	path_to_sihan_corpora_dict = "./stanford_segmenter/data", 
	path_to_model = "./stanford_segmenter/data/pku.gz", 
	path_to_dict = "./stanford_segmenter/data/dict-chris6.ser.gz")

sentence = u"这里是斯坦福分词器测试"

result = segmenter.segment(sentence)
print result

the error as follows :
NLTK was unable to find the java file!
Use software specific configuration paramaters or set the JAVAHOME environment variable.

i have set the javehome enviroment , but it also doesn't work
