### ISSUE TITLE
problem installing ntlk

### ISSUE THREAD

**Issue by nadaa** [nltk/nltk#793]
Hi,

I'm trying to install NLTK3 on ubuntu that has python2.7- When I first installed steuptools I got the following bug!

![nltk-prob](https://cloud.githubusercontent.com/assets/1457075/4967102/2e5110e8-67f8-11e4-9492-d99f2d1108b5.png)

Thanks a lot in advance!

**Comment by stevenbird** [comment]
This is not a bug in NLTK. If you search on your error message, you can see that the advice is to download and install setuptools manually.
