### ISSUE TITLE
Missing wn.ADJ_SAT key when accessing wn.synsets()

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#795]
see http://stackoverflow.com/questions/26900954/why-cant-i-pass-wn-adj-sat-as-a-pos-when-requesting-synsets for details.

Can we add the following line after line 1609 of the wordnet corpus reader, https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L1609 ?

```
MORPHOLOGICAL_SUBSTITUTIONS[ADJ_SAT] = MORPHOLOGICAL_SUBSTITUTIONS[ADJ]
```

**Comment by stevenbird** [comment]
Thanks. Resolved in https://github.com/nltk/nltk/commit/21fd0c538b0144c5f722e4f643c9ced1deb1f15e
