### ISSUE TITLE
TreebankWordTokenizer with unicode characters

### ISSUE THREAD

**Issue by aboSamoor** [nltk/nltk#8]
It seems there is a problem in the TreebankWordTokenizer when it comes to unicode characters as it split any non English word depending on the non ASCII characters! here is an example
**Statement**
In Düsseldorf I took my hat off. But I can't put it back on.

**NLTK**
In D ü sseldorf I took my hat off .
But I ca n't put it back on .

**Stanford (PennTreebank) PTBLexer**
[In, Düsseldorf, I, took, my, hat, off, .]
[But, I, ca, n't, put, it, back, on, .]

**http://www.cis.upenn.edu/~treebank/tokenizer.sed**
In Düsseldorf I took my hat off .
But I ca n't put it back on .

**Comment by jnothman** [comment]
It looks like all the regular expressions should have the re.UNICODE flag. Otherwise, non-ASCII characters may be captured by the [^\w] used to split punctuation.

**Comment by aboSamoor** [comment]
@jnothman 
I agree. Actually, I already made this patch.
https://github.com/aboSamoor/nltk/compare/master...ptb_word_tokenizer

**Comment by stevenbird** [comment]
Thanks.  This is adopted.  https://github.com/nltk/nltk/commit/4dc1d889bddeea6d6ea65661af2d43df4a078e82
