### ISSUE TITLE
Consistent naming of pretty-print methods

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#804]
Following the naming decision in #794, modify the names of other pretty-printing methods, including `FreqDist.pprint()`, `sem.drt.DrtExpression.pretty()`, and `parse.chart.Chart.pp()`.

**Comment by heatherleaf** [comment]
More methods (including the ones mentioned by @stevenbird ): 
- `classify.decisiontree.DecisionTreeClassifier.pp()`: returns a string
- `metrics.confusionmatrix.ConfusionMatrix.pp()`: returns a string
- `Tree.pprint()`: returns a string
- `Tree.pretty_print()`: prints on stdout
- `FreqDist.pprint()`: returns a string
- `sem.lfg.FStructure.pprint()`: returns a string
- `sem.drt.DrtExpression.pprint()`: prints on stdout
- `sem.drt.DrtExpression.pretty()`: returns a string
- `parse.chart.Chart.pp()`: returns a string

Python "standard":
- `pprint.pprint()`: prints on stdout
- `pprint.pformat()`: returns a string

**Comment by heatherleaf** [comment]
Some things to discuss first:
1. Sometimes `pprint()` prints the object (e.g., `DrtExpression`), and sometimes it returns a string (e.g. `FStructure`)
2. `Tree` currently has both `pprint` and `pretty_print`, which do different things.

**Comment by dimazest** [comment]
i like the "standard" Python behavior:  `pformat` to get a pretty string, `pprint` to print it.

The naming might be a bit confusing in the beginning, it's not crystal clear wht 'p' stands for, but this can be explained in the documentation.

**Comment by stevenbird** [comment]
I think that we should use `pprint` in a way that is consistent with the standard library's `pprint.pprint`, i.e. it should print a formatted version of the object on stdout or to the specified stream, [in a form which can be used as input to the interpreter](https://docs.python.org/3/library/pprint.html). Similarly, `pformat` would return the same string.

I suggest that we use `pretty_print` to print a human readable version that is too pretty to be usable as input to the interpreter.

By analogy with `pprint.pprint`, I think it would be nice to provide an optional stream argument for our own `pprint` method.

Shall we also provide `pretty_format` wherever there is a `pretty_print`, and add a stream argument to `pretty_print`?

**Comment by dimazest** [comment]
`pretty_format` is a good idea. I'm for these 4 methods.

**Comment by stevenbird** [comment]
By the way, it looks like the [pprint module](https://docs.python.org/3/library/pprint.html) is designed to support subclassing. However, [it might be too tedious to use](http://stackoverflow.com/questions/3258072/best-way-to-implement-custom-pretty-printers). For now I suggest that we don't bother with it and have our own custom `pprint` methods, and only come back to this if we find that we want to pretty-print standard Python objects that contain NLTK objects, or vice versa.

**Comment by stevenbird** [comment]
So, to summarise:
- `pprint` will print a formatted version of the object, in a form that can be used as input to the interpreter
- `pprint` will take an optional stream argument
- `pformat` just returns this string
- wherever `pprint` is available, `pformat` will also be available (in fact, `pprint` will just call `pformat`)
- `pretty_print` and `pretty_format` are parallel methods, less often provided, not expected to be provide output that can be used by the interpreter
- `pprint` is intended to be at least as aesthetically pleasing as `__str__` while still being usable by the interpreter (unlike `__str__`)

Does this match everyone's expectations?

Does the requirement to be usable by the interpreter sound reasonable? Are our existing pretty print methods (identified by @heatherleaf) usable as input by the interpreter?

**Comment by heatherleaf** [comment]
Ok, here's my interpretation of the summary. Apparently only Tree can pretty-print something that is readable by the interpreter. FreqDist comes close. 

The following should be renamed to `pretty_format`:
- `classify.decisiontree.DecisionTreeClassifier.pp()`
- `metrics.confusionmatrix.ConfusionMatrix.pp()`
- `sem.lfg.FStructure.pprint()`
- `sem.drt.DrtExpression.pretty()`
- `parse.chart.Chart.pp()`

The following to `pretty_print`:
- `sem.drt.DrtExpression.pprint()`

The following to `pformat`:
- `Tree.pprint()`
- `FreqDist.pprint()` (but this only includes the top 10 items appended by "...", which is not directly readable by the interpreter)

The following to `pprint`:
- `Tree.pretty_print()`

**Comment by stevenbird** [comment]
I've documented these changes in the wiki page [Porting your code to NLTK 3.0](https://github.com/nltk/nltk/wiki/Porting-your-code-to-NLTK-3.0)

**Comment by stevenbird** [comment]
Thanks for the significant help, @heatherleaf
