### ISSUE TITLE
Dependency parsing evaluation

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#805]
Implement labeled and unlabeled attachment scores, possibly porting the algorithms implemented in http://ilk.uvt.nl/conll/software.html

**Comment by longdt219** [comment]
We will try to replicate the official conll 06 eval software from http://ilk.uvt.nl/conll/software.html and evaluate on English and non-English treebank using malt parser.

**Comment by longdt219** [comment]
I created a pull request, could you check and close this issue @stevenbird

**Comment by jnothman** [comment]
You should probably note in the evaluation implementation which other
implementation it is trying to replicate, as I gather there are a few
quirks in this space across dependency evaluator implementations.
