### ISSUE TITLE
the parser example apps cannot handle unicode

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#81]
In the parser apps (chartparser_app, rdparser_app, srparser_app), non-ascii characters in terminals 
are not allowed - when editing the grammar, an 'ä' becomes red, and it's not possible to parse. At 
least not on a Mac. 

When I edit the grammar again, the 'ä' has been translated to '\xc3\xa4'. But if I write an 'ä' in the 
example Text, it translated to u'\xe4' in the parser window.

So there's probably some en-/decoding issues here.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=441</p>

**Comment by alexrudnick** [comment]
Is this still a problem?

**Comment by heatherleaf** [comment]
Yes, it's still a problem. 

The same problem if I edit the grammar in a text editor, and then do "File -> Load Grammar". Regardless of whether I save the grammar in utf-8 or latin-1.

If I enter "häst" as the text to parse, it gets shown as u'h\xe4st' in the parser window. So the Text gets translated to Unicode, but the Grammar apparently does not.
