### ISSUE TITLE
Augmented Wordnets (Stanford) through NLTK seems not working

### ISSUE THREAD

**Issue by marcoippolito** [nltk/nltk#810]
Hi,
I found that Stanford University's NLP Group has extended WordNet:http://ai.stanford.edu/~rion/swn/index.html

as suggested in the webpage, I downloaded wn400k_cropped.tgz (http://ai.stanford.edu/~rion/swn/wn400k_cropped.tgz), unzipped the folder and put the files in the folder of the pre-existing installation of wordnet:
marco@pc:~/nltk_data/corpora/wordnet$ ls -a
.  ..  adj.exc  adv.exc  cntlist.rev  data.adj  data.adv  data.noun  data.verb  index.adj  index.adv  index.noun  index.sense  index.verb  lexnames  noun.exc  verb.exc  wn400k_cropped.tgz

But now, diffently to before doing this, wordnet through NLTK seems not working anymore:

> > > import nltk
> > > from nltk.corpus import wordnet
> > > parola = 'bass'
> > > syn = wordnet.synsets(parola)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1414, in synsets
> > >     for offset in index[form].get(p, [])]
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1268, in _synset_from_pos_and_offset
> > >     synset = self._synset_from_pos_and_line(pos, data_file_line)
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1301, in _synset_from_pos_and_line
> > >     synset._lexname = self._lexnames[lexname_index]
> > > IndexError: list index out of range
> > > parola = 'people'
> > > syn = wordnet.synsets(parola)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1414, in synsets
> > >     for offset in index[form].get(p, [])]
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1268, in _synset_from_pos_and_offset
> > >     synset = self._synset_from_pos_and_line(pos, data_file_line)
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/wordnet.py", line 1301, in _synset_from_pos_and_line
> > >     synset._lexname = self._lexnames[lexname_index]
> > > IndexError: list index out of range

Any suggestions to improve the situation?

Looking forward to your helpfull hints.
Kind regards.
Marco

**Comment by stevenbird** [comment]
NLTK's interface is for the current Princeton WordNet format, not an extension of the older 2.1 format. Has anyone converted Snow et al's work to use the current WordNet format? If so, there would be a case for developing an NLTK corpus reader specifically for that. If someone would like to work on it, please open a new issue.
