### ISSUE TITLE
Floating point division

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#815]
Audit the codebase and replace old idioms for getting floating point division, e.g.:

```
z = x / float(y)
z = x / (1.0 * y)
```

with:

```
from __future__ import division
...
z = x / y
```

**Comment by erip** [comment]
Note: anywhere you use `__future__.division`, you'll need to convert the existing integer division to `//`. Fret not, this also works in python 2. This should be the first step in the refactor.

Alternatively you could cast the quotient to `int`, but I think this is less idiomatic.

**Comment by stevenbird** [comment]
Good point, thanks @erip.
