### ISSUE TITLE
Visualizing dependency trees

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#816]
Extend NLTK's [tree drawing module](https://github.com/nltk/nltk/blob/develop/nltk/draw/tree.py) to support the display of dependency trees. Include the methods used by IPython Notebook, cf #684.

NB http://nlp.stanford.edu/software/stanford-dependencies.shtml

**Comment by nournia** [comment]
[dependency-parse-tree](https://github.com/sobhe/dependency-parse-tree) project may help. Actually I prepared this for RightToLeft languages (e.g. Persian) but supporting LeftToRight is not that hard.

**Comment by ewan-klein** [comment]
Hi Nourian,

I haven’t looked into your code, but the idea of using D3.js seems sensible, and the output is impressive. Would you consider trying to interface your approach with the existing treatment of dependency grammars in NLTK?

> On 20 Dec 2014, at 13:06, Alireza Nourian notifications@github.com wrote:
> 
> dependency-parse-tree project may help. Actually I prepared this for RightToLeft languages (e.g. Persian) but supporting LeftToRight is not that hard.

Regards,

Ewan

**Comment by nournia** [comment]
Actually, that piece of code is compatible with current DependencyGraph implementation and you only need to convert `dependency_tree` object to `CONLL` format:

```
dependency_tree.to_conll(10)
```

But I think this resulted figure only can be shown in browser engine, e.g. visualizing trees in IPython notebooks.

[dependency-parse-tree](https://github.com/sobhe/dependency-parse-tree) finds minimum required tree height based on its arc formation. I hope to see this feature in final dependency tree visualization.

**Comment by stevenbird** [comment]
@gmonce we would very much like to integrate your work on visualising dependency trees.

**Comment by gmonce** [comment]
It will be a pleasure, just let me know what I can do to help. What I have mostly done is to generate dot representations from the dependency parse structure of NLTK

**Comment by stevenbird** [comment]
Thanks. So, would the next step be to add `dot` and `_repr_svg` methods to `Tree` and `DependencyGraph`? @oplatek might be able to contribute.

**Comment by oplatek** [comment]
Actually, since dot is format, you can create `_repr_dot_` function which would be used in `_repr_svg_`, `_repr_png_`, etc together with graphviz library to create svg and png images.
Let me know when/if I can help.

**Comment by oplatek** [comment]
I created PR https://github.com/nltk/nltk/pull/891

**Comment by stevenbird** [comment]
Resolved by #891.
