### ISSUE TITLE
Absolute to Relative imports

### ISSUE THREAD

**Issue by pratapvardhan** [nltk/nltk#821]
As of now, most or may be all of the src code uses absolute imports like 
`from nltk.probability import FreqDist, MLEProbDist, entropy`
would it be better to chnage them to relative imports like 
`from ..probability import FreqDist, MLEProbDist, entropy`

Presently, it is highly likely, we would be importing global nltk installations..

What do you think?

**Comment by kmike** [comment]
Do you have practical issues with these imports? I don't understand when could absolute imports cause problems; the only case I can think of is a renamed top-level "nltk" folder, and I don't think this is an use case we should worry about. 

Consider the following: there is `from nltk.probability import FreqDist` import in `nltk.collocations`. If you import `nltk.collocations` then `collocations` is relative to the same `nltk` package as `probability`. So changing absolute import to a relative import changes nothing.

**Comment by stevenbird** [comment]
Also, we follow PEP-8 which recommends the use of relative imports.

**Comment by ewan-klein** [comment]
You mean ‘absolute’ not ‘relative':

>   Absolute imports are recommended, as they are usually more readable…
