### ISSUE TITLE
ANN for text clasification

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#83]
Hi, right now I’m studying my Master Degree in Computing Systems on the 
Universidad Autonoma de Chihuahua (Mexico). One of my courses was about 
artificial neural networks and as a final project I implement a text 
classifier that’s build and train an ANN using then nltk.  If there’s any 
project about include an ANN based text classifier in the tool kit, I would 
be glad to help in the project.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=446</p>

**Comment by stevenbird** [comment]
This is probably superseded by deep learning and gensim.
