### ISSUE TITLE
Use of sparse in maxent classifier 

### ISSUE THREAD

**Issue by pratapvardhan** [nltk/nltk#834]
It seems like `sparse` argument is not used anywhere in the [train function](../blob/develop/nltk/classify/maxent.py#L227) of Maximum Entropy Classifiers? So, remove the argument or am I missing something?

**Comment by stevenbird** [comment]
Yes, and `sparse` is not defined in the docstring either.

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/b647b2a3c51de6cee609277070dd17958e83455a
