### ISSUE TITLE
Wrong release/codebase of the 3.0.1 version on pypi

### ISSUE THREAD

**Issue by tukan** [nltk/nltk#842]
Current version of nltk on pypi is 3.0.1, but I believe that both archives nltk-3.0.1.tar.gz (md5: c4f4b7be66d19dd5faf3c8336bb4cec4; https://pypi.python.org/packages/source/n/nltk/nltk-3.0.1.tar.gz#md5=c4f4b7be66d19dd5faf3c8336bb4cec4) and nltk-3.0.1.zip (md5: c46021ba97c4451234f05cd62973b94f; https://pypi.python.org/packages/source/n/nltk/nltk-3.0.1.zip#md5=c46021ba97c4451234f05cd62973b94f) were created from some different (older) code to what was supposed to be released in a 3.0.1 version.

At first I need to mention that right now on github the latest release is 3.0.0 (released on Sep 7, 2014), which is quite confusing, because the latest version on pypi (according to nltk pypi page and nltk/VERSION file) is 3.0.1 (uploaded to pypi on 2015-01-12).

However on github instead of 3.0.1 release there is a release-3.0.1 branch and its code differs from the code in the pypi distribution and pypi distribution has bugs that were fixed in the release-3.0.1 branch. 

For example in the https://github.com/nltk/nltk/commit/0c2c43a8cad11c03d852b51761998803592c7a5b commit AbstractDrs was renamed to DrtExpression inconsistently (can't find an issue for that bug here on github, but it was somehow reported in the [nltk-users] google group and accepted/admitted there: https://groups.google.com/d/msg/nltk-users/G1xlYuDq4OU/Fc4BZfIfJXcJ). The problem was in nltk/sem/glue.py in a line 583 (https://github.com/nltk/nltk/blob/0c2c43a8cad11c03d852b51761998803592c7a5b/nltk/sem/glue.py#L583) where `drt.AbstractDrs` wasn't renamed. This bug was fixed later in the https://github.com/nltk/nltk/commit/c92ad3822788093fdd4394480060f0498db07d8d commit on Oct 28, 2014 and this fix exists in the release-3.0.1 branch, but in the source code in the mentioned above pypi nltk distribution of the version 3.0.1 this nasty line at a number 583 in the nltk/sem/glue.py file with broken and not renamed `drt.AbstractDrs` still exists. 🐼

**Comment by stevenbird** [comment]
Sorry for the confusion. I released 3.0.1 which differs from 3.0.0 by a single commit (see #824) in order to fix some urgent integration issues. The 3.0.1 release branch is stale and I'll remove it and shortly begin a new release branch for 3.0.2 which will include the fixes you listed.

**Comment by tukan** [comment]
Thank you very much. Mostly I was confused because you wrote in the google-group that AbstractDrs bugfix will be included in 3.0.1 and then I discovered the 3.0.1 release branch with the fix and at the same time I didn't find the 3.0.1 release in the releases on github, so I thought maybe something went wrong while you were releasing 3.0.1. Glad to hear that actually everything is ok. It's not a big deal to fix it locally while the upstream bug fix is waiting for being released.
