### ISSUE TITLE
syntax colouring gone wrong

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#85]
I am reading the online version of the book,
http://nltk.googlecode.com/svn/trunk/doc/book/ch04.html

In chapter 4, example 4.5. it looks as if the colours got messed up.
Half of the docstring is green and the rest displays in blue.

Kind regards

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=450</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2010-03-12T10:42:05.000Z:</strong></p>
<p>(Thanks for the report, and sorry for the delay.)  The problem must be caused by the
inclusion of a doctest block inside the function docstring.   We need to fix this,
but I'm not sure how soon its going to happen, sorry.
</p>

**Comment by kmike** [comment]
migrated to https://github.com/nltk/nltk_book/issues/3
