### ISSUE TITLE
Cannot import NLTK in Python 3.4.2: AttributeError: 'module' object has no attribute 'isclass'

### ISSUE THREAD

**Issue by andrecunha** [nltk/nltk#856]
Hello,

I cannot import NLTK 3.0.1 in Python 3.4.2. When I create a virtualenv, install nltk with pip, open a python interpreter, and do `import nltk`, I get this error message right away:

```
>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andre/.virtualenvs/test/lib/python3.4/site-packages/nltk/__init__.py", line 104, in <module>
    from nltk.decorators import decorator, memoize
  File "/home/andre/.virtualenvs/test/lib/python3.4/site-packages/nltk/decorators.py", line 183, in <module>
    @decorator
  File "/home/andre/.virtualenvs/test/lib/python3.4/site-packages/nltk/decorators.py", line 161, in decorator
    if inspect.isclass(caller):
AttributeError: 'module' object has no attribute 'isclass'
```

Curiously, if I install ipython (2.3.1) inside the virtualenv, and import nltk inside ipython, it works.

**Comment by stevenbird** [comment]
@kmike do you have any advice here?

**Comment by kmike** [comment]
I've created a new Python 3.4 environment, executed 'pip install nltk' and then imported NLTK from standard `python` REPL, it worked. So I can't reproduce it. 

But there is some suspicious code in decorators.py module:

```
# Hack to keep NLTK's "tokenize" module from colliding with the "tokenize" in
# the Python standard library.
old_sys_path = sys.path[:]
sys.path = [p for p in sys.path if "nltk" not in p]
```

I think the proper way to distinguish nltk.tokenize from tokenize is to use `from __future__ import absolute_imports`. Modifying sys.path on import in a completely unrelated module (decorators.py) doesn't look good. ~~I don't like `if "nltk" not in p` check either, it could remove valid paths from sys.path. Maybe this is what causes the error.~~

**Comment by kmike** [comment]
What do you think about dropping nltk.decorators altogether? 

It is an outdated bundled version of an external package, and it is not used by NLTK itself. Comment says that this moduleis `Included in NLTK for its support of a nice memoization decorator.`, but this decorator is not used by NLTK, and there are similar decorators available as external packages for users who need them.

**Comment by andrecunha** [comment]
I've just realized that this error only happens when I import nltk from a particular directory, which is a Python project I'm currently working on, and it has a file called `inspect.py`. This file was shadowing the standard `inspect` module. I've renamed the file, and everything is now working fine. I'm really sorry. :(

**Comment by kmike** [comment]
@andrecunha it is still a bug in NLTK - have it used `absolute_imports` this wouldn't happen. So thanks for reporting it and for finding a reason!

**Comment by kmike** [comment]
Hmm, I'm wrong - it does't depend on absolute_imports.

**Comment by zainulabidin302** [comment]
If you remove `inspect.py` keep in mind to remove `inspect.pyc` too
