### ISSUE TITLE
Optional stream argument for pprint

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#859]
Add an optional stream argument to any `pprint` methods, for consistency with pprint.pprint, cf #804.

**Comment by Dobatymo** [comment]
http://www.nltk.org/_modules/nltk/tree.html#Tree.pprint done
http://www.nltk.org/_modules/nltk/tree.html#Tree.pretty_print done
http://www.nltk.org/_modules/nltk/probability.html#FreqDist.pprint done
http://www.nltk.org/_modules/nltk/corpus/reader/verbnet.html#VerbnetCorpusReader.pprint returns string
http://www.nltk.org/_modules/nltk/corpus/reader/conll.html#ConllSRLInstance.pprint returns string
http://www.nltk.org/_modules/nltk/corpus/reader/conll.html#ConllSRLInstanceList.pprint returns string
http://www.nltk.org/_modules/nltk/sem/drt.html#DrtExpression.pretty_print todo

**Comment by alvations** [comment]
@Dobatymo actually I think there's still quite some work that needs to done to make `pprint` consistently prints to stdout and `pformat` return a string.

From [docs](https://docs.python.org/3/library/pprint.html#pprint.pformat):

> 
> pprint.pformat(object, indent=1, width=80, depth=None, *, compact=False)
> Return the formatted representation of object as a string. indent, width, depth and compact will be passed to the PrettyPrinter constructor as formatting parameters.
> 
> pprint.pprint(object, stream=None, indent=1, width=80, depth=None, *, compact=False)
> Prints the formatted representation of object on stream, followed by a newline. If stream is None, sys.stdout is used. This may be used in the interactive interpreter instead of the print() function for inspecting values (you can even reassign print = pprint.pprint for use within a scope). indent, width, depth and compact will be passed to the PrettyPrinter constructor as formatting parameters.
> 

There's also quite some `pretty_print()` in NLTK that does various things =(
