### ISSUE TITLE
Percentages in FreqDist.plot()

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#87]
Figure 1-4 displays percentages, even though this was dropped in r6689. 
Reinstate this functionality somewhere (e.g. as a flag for FreqDist.plot(),
or perhaps in ProbDist; though its not clear how to plot smoothed probdists).

http://groups.google.com/group/nltk-users/browse_thread/thread/8f3e3f2b531836a4
http://groups.google.com/group/nltk-users/browse_thread/thread/85ba122d808147c

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=457</p><hr/><h2>earlier comments</h2>
<p><strong>StevenBird1 said, at 2009-12-10T23:48:08.000Z:</strong></p>

<p>The figure has been corrected not to display percentages.
</p><p><strong>StevenBird1 said, at 2009-12-11T06:35:18.000Z:</strong></p>

<p>Deleting "Book" tag</p><p><strong>zhai-run@163.com said, at 2010-01-15T10:14:57.000Z:</strong></p>

<p>But how to change it back to percentage (now it is count, and different from the 
example in the book). More over, while running FreqDist.plot, a warning prompts:
Warning (from warnings module):
  File "C:\Python26\lib\site-packages\matplotlib\dates.py", line 91
    import pytz.zoneinfo
ImportWarning: Not importing directory 'C:\Python26\lib\site-packages\pytz
\zoneinfo': missing __init__.py

Why</p>

**Comment by stevenbird** [comment]
Closing, as we don't have capacity to take this on.
