### ISSUE TITLE
ParserI inconsistencies

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#876]
In spite of the modifications in #620, there are still inconsistencies in the ParserI interface:
1. the dependency parsers do not inherit ParserI
   - the dependency parsers implement raw and tagged methods
   - the ParserI methods implemented by the dependency parsers do not return iterators
2. `parse_all` never needs to be defined 
   - the stanford and malt parsers redundantly define `parse_all()`, when inheriting it from `ParserI` gives the same behaviour
   - `chart.parse_all` can be replaced by an iterator, returned by `chart.parse`

**Comment by longdt219** [comment]
Hi @stevenbird 
Could you close this one as it is merged.

**Comment by stevenbird** [comment]
Thanks @longdt219
