### ISSUE TITLE
Setting all encoding for Stanford tools to UTF8 as default

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#877]
Is there a reason to set [`StanfordTagger._encoding`](https://github.com/alvations/nltk/blob/develop/nltk/tag/stanford.py#L39) as 'ascii' ?

To be consistent with python3, can we change the default to UTF8?

**Comment by stevenbird** [comment]
This is also consistent with the encoding specified in `tokenize/stanford.py` and `parse/stanford.py`.

**Comment by alvations** [comment]
@stevenbird thanks for the change to `utf8` =)
