### ISSUE TITLE
NLTK import error

### ISSUE THREAD

**Issue by chenbouyea** [nltk/nltk#885]
I'm new to Python and NLTK. I've been trying to find a solution to my problem but have not found one yet and was hoping someone could help me.

I'm currently running 64bit Windows 8. I've followed the instruction in the NLTK website (http://www.nltk.org/install.html). I might have installed a 64bit version Python in the first place but have removed it and reinstall 32bit version Python. Now I'm having the following problem:
![nltk](https://cloud.githubusercontent.com/assets/8059495/6198713/9bc7d102-b40b-11e4-99f8-767e5fbce794.png)

Any idea on how to solve this?

**Comment by stevenbird** [comment]
Would you please try using a more recent version of Python? We converted various trained models to Unicode in order to fix problems like this, but it only works in Python 3 (cf #169).

**Comment by chenbouyea** [comment]
Thank you Steven. This problem did not occurred anymore after using Python 3.
