### ISSUE TITLE
Collocations and Twitter feeds problem

### ISSUE THREAD

**Issue by Amanda-Clark** [nltk/nltk#888]
I've been trying to use collocations with Twitter feeds, and have run into a bit of an issue. When I download someone's Tweets with the Twitter API, and run nltk.collcations(), instead of common phrases and words, I get mostly Twitter handles. "@whosits @soandso; @bob @sam", etc. People often phrase Tweets in that way-"@Bob @Blah How did you like the movie?" and so collocations seems to be returning Twitter handles instead of common phrases and combos of words, like _I_ expected. Should there be a built in method to strip Twitter handles from a Twitter feed, so you don't have to regex them out of a text editor? On the other hand, finding the most commonly mentioned Twitter handles in a feed is something very NLTK worthy, but the current collocations module seems not well suited for Twitter.

**Comment by stevenbird** [comment]
@ewan-klein do you have any thoughts on this?

**Comment by ewan-klein** [comment]
@Amanda-Clark There is some ongoing work on the `twitter` branch of NLTK to provide better treatment of tweets. If you change to that branch, you'll find a tweet-aware tokeniser `https://github.com/nltk/nltk/blob/twitter/nltk/tokenize/casual.py`. In principle, we could define a method `normalize()` that strips out Twitter handles and URLs from a tweet text. However, looking at the demo at the end of `https://github.com/nltk/nltk/blob/develop/nltk/collocations.py`, it seems that the obvious thing to try, at least in the first instance, would be to apply a `word_filter` which returns `True` for any string that starts with `@`.

**Comment by Amanda-Clark** [comment]
@ewan-klein Is there someone working on doing that? Sorry I'm not used to how (open source) projects are done in GitHub, or in general.

**Comment by nschneid** [comment]
Regarding tokenization for Twitter: This would be nice to have in NLTK. In case you haven't seen it, [Twokenizer](http://www.ark.cs.cmu.edu/TweetNLP/) does a lot of processing for emoticons, etc. (But unlike PTB-style tokenizers it does not attempt to separate clitics.)

**Comment by ewan-klein** [comment]
@Amanda-Clark Can you clarify what you mean by 'doing that'?

**Comment by Amanda-Clark** [comment]
@ewan-klein Sorry I was referring to what you said here: "However, looking at the demo at the end of https://github.com/nltk/nltk/blob/develop/nltk/collocations.py, it seems that the obvious thing to try, at least in the first instance, would be to apply a word_filter which returns True for any string that starts with @." Is there someone working on adding that to NLTK?
