### ISSUE TITLE
multi-word concordance search

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#90]
Extend the Text.concordance() method to support multi-word search.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=469</p>

**Comment by Besitypanacea** [comment]
i also have the same problem when replacing words. Nltk can only change two words or one word like bday: to birthday.

**Comment by tylerjryan** [comment]
Was this ever implemented? Having trouble finding more information on it and came across this old thread in a search for multi-word concordances. I've been enjoying using nltk, and this feature would be great. Thanks!

**Comment by stevenbird** [comment]
@tylerjryan: yes, multi-word search expressions are supported, please see:

```
>>> from nltk.app import concordance
>>> concordance()
```

**Comment by stevenbird** [comment]
Oh, but this is in our graphical concordance app. The command-line version in Text.concordance doesn't support multi-word searches.

**Comment by tylerjryan** [comment]
Thanks for the quick response! I'll look into it and see if it can be adapted for the command line interface. Is there anything preventing this?

**Comment by stevenbird** [comment]
@tylerjryan: feel free to submit a pull request to extend the functionality of `Text.concordance` in this way. That would be a welcome contribution. Note that `app.concordance` also searches POS tags, so you'll need to drop that functionality.

**Comment by tylerjryan** [comment]
I'll see what I can do, thanks for the info!

**Comment by kamaunyrroh** [comment]
So stevenbird your saying that it can search for multiple words in a paragraph and replace them? I was forced to abandon nltk because on complete project has ever been implemented. After coding for three months and dead roads by asking nltk questions on their google groups to answer they did not answer.

**Comment by kamaunyrroh** [comment]
I see that you have provided this code: 
>>> from nltk.app import concordance
>>> concordance()

but how does it work when you implement it on the web or commandline? Do you have a complete code for this?

**Comment by KCIV** [comment]
Has there been any update on this?

I found a listed function that I am currently testing but the output has some issues

https://stackoverflow.com/questions/33813405/concordance-for-a-phrase-using-nltk-in-python

**Comment by vishooj** [comment]
Hi, is there any update on it, once available will be very useful.
