### ISSUE TITLE
Implement Turkish stemmer

### ISSUE THREAD

**Issue by he7d3r** [nltk/nltk#901]
There is a snowball implementation of a stemmer for Turkish at
http://snowball.tartarus.org/algorithms/turkish/stem_Unicode.sbl
but this is not yet available in NLTK for usage with Python.

**Comment by stevenbird** [comment]
Thanks @he7d3r. I see that someone would need to port it first, so I can't do anything until there's a PR.

**Comment by pembeci** [comment]
May be I can help with porting but couldn't find documentation on how this can be done. I am checking the .sbl file but it seems like it is using some other techniques compared to other nltk Stemmers (i.e. nowhere I can find the r1, r2 indices or how they are progressed).

**Comment by he7d3r** [comment]
I don't know if this helps (maybe you already found this) but there is a description of the algorithm at
http://snowball.tartarus.org/algorithms/turkish/stemmer.html
(or more precisely, on this [accompanying_paper.doc](http://snowball.tartarus.org/algorithms/turkish/accompanying_paper.doc))

**Comment by pembeci** [comment]
Thanks @he7d3r. I found that but I wasn't sure how to translate that into nltk. I guess I need to check an existing snowball stemmer and its corresponding nltk code to understand what is going on. I was asking for that kind of documentation but I don't think it exists yet.
