### ISSUE TITLE
window_size parameter of collocations() seems to be not working

### ISSUE THREAD

**Issue by joyofdata** [nltk/nltk#907]
Dear NLTK-Team!

As far as I understand the `window_size` argument of the `collocations()` method, it should control the N for the N-grams being evaluated.

```
raffael@raffael-GT60 /m/V/g/b/d/p/B/txt> python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import nltk                                                                                                                       
>>> from nltk.book import *
*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
text1: Moby Dick by Herman Melville 1851
[...]
text9: The Man Who Was Thursday by G . K . Chesterton 1908

>>> text1.collocations()
Sperm Whale; Moby Dick; White Whale; old man; Captain Ahab; sperm
whale; Right Whale; Captain Peleg; New Bedford; Cape Horn; cried Ahab;
years ago; lower jaw; never mind; Father Mapple; cried Stubb; chief
mate; white whale; ivory leg; one hand

>>> text1.collocations(window_size=3)                                                                                                 
Sperm Whale; Moby Dick; White Whale; old man; Captain Ahab; Right
Whale; sperm whale; mast heads; mast head; Aye aye; Captain Peleg;
quarter deck; New Bedford; Dough Boy; chief mate; Cape Horn; Fast
Fish; Mrs Hussey; Loose Fish; try works
```

Hence, I assume for `window_size=3` the output should feature 3-grams. 

Is this a bug or do I misunderstand something here.

Thanks in advance

Raffael

**Comment by stevenbird** [comment]
`window_size` is the number of words to look at when searching bigrams. "When window_size > 2, count non-contiguous bigrams". http://www.nltk.org/api/nltk.html?highlight=window_size

**Comment by jnothman** [comment]
To be sure, there is a `TrigramCollocationFinder` and a `QuadGramCollocationFinder` incase you want 3- and 4-grams.

**Comment by joyofdata** [comment]
Sorry for the confusion and thanks for the information!

**Comment by NandiniNuthalapati** [comment]
The window_size argument is the distance to be used by the function to capture bigrams. For example, if window_size=3, then the function will search for bigrams until 3 words on each side of the word and enters every word pair as a bigram before it returns the collocations.

**Ex:** Here is an example of a three-word collocational window
**Sentence:** So no one told you life was gonna be this way
**Bigrams:**
<img width="806" alt="window_size" src="https://user-images.githubusercontent.com/33079914/47581937-e04b1d00-d920-11e8-8042-4e326dde65d2.png">
**Reference:** Foundations of Statistical Natural Language Processing
