### ISSUE TITLE
Fix CI failing tests

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#910]
https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/testReport/

**Comment by stevenbird** [comment]
It looks like the corpora are not being downloaded to the CI server.

**Comment by longdt219** [comment]
Hi @stevenbird,
Why do you think the corpora are not being downloaded ? It said 
`[nltk_data]  Done downloading collection all` from the console output 
https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py26-jenkins,jdk=jdk8latestOnlineInstall/251/console

**Comment by stevenbird** [comment]
Only because a previous test result gave an error for every corpus access. However, these errors have gone now.

**Comment by stevenbird** [comment]
@copper-head – there are some errors in probability.py reported by our [CI server](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/testReport/), that might have arisen since I merged your work (see https://github.com/nltk/nltk/commit/8dcae605a91a9f18fc02b75eda0b95fde4e71820#diff-100d02c6ef23dc5d864fec05084fe72d). I haven't checked to confirm this. But since you were most recently in the code, would you mind taking a look at these errors please?

**Comment by stevenbird** [comment]
Resolved by https://github.com/nltk/nltk/commit/89a08d4e295e953aad3d4efd195cc739dc5b52bc
