### ISSUE TITLE
Dead code int pl196x - it is impossible to execute since always occuring exception?

### ISSUE THREAD

**Issue by ChameleonRed** [nltk/nltk#911]
This code is not possible to be executed:

```
def xml(self, fileids=None, categories=None):
    fileids, _ = self._resolve(fileids, categories)
    if len(fileids) == 1: return XMLCorpusReader.xml(self, fileids[0])
    else: raise TypeError('Expected a single file')
```

Why because always `_resolve(*, **) == None, None`.

```
def _resolve(self, fileids, categories, textids=None):
    tmp = None
    if fileids is not None:
        if not tmp:
            tmp = fileids, None
        else:
            raise ValueError('Specify only fileids, categories or textids')
    if categories is not None:
        if not tmp:
            tmp = self.fileids(categories), None
        else:
            raise ValueError('Specify only fileids, categories or textids')
    if textids is not None:
        if not tmp:
            if isinstance(textids, compat.string_types): textids = [textids]
            files = sum((self._t2f[t] for t in textids), [])
            tdict = dict()
            for f in files:
                tdict[f] = (set(self._f2t[f]) & set(textids))
            tmp = files, tdict
        else:
            raise ValueError('Specify only fileids, categories or textids')
    return None, None
```

**Comment by ChameleonRed** [comment]
File "C:\root\Python27\lib\site-packages\nltk\corpus\reader\pl196x.py", line 270, in xml
    if len(fileids) == 1: return XMLCorpusReader.xml(self, fileids[0])
TypeError: object of type 'NoneType' has no len()

**Comment by rmalouf** [comment]
This is pretty weird.  My guess would be that the last line of `_resolve` should be `return tmp`.  The comments say this was contributed by Piotr Kasprzyk... is that you, @kwadrat?

**Comment by pkasprzyk** [comment]
@rmalouf it's me. And on a side note: wow, that's some code I'm not proud I've written. Created a PR that should fix the immediate bug, though the whole file begs some heavy rewrite...

**Comment by kwadrat** [comment]
@rmalouf  The correct "Piotr Kasprzyk" is @piotrkasprzyk   I mainly write programs in Python programming language :)

**Comment by rmalouf** [comment]
Thanks @kwadrat  and @piotrkasprzyk!

**Comment by stevenbird** [comment]
Thanks all – I've closed this since it looks like it has been satisfactorily resolved.
