### ISSUE TITLE
ipipan module looks like dead since not data for corpus in internet

### ISSUE THREAD

**Issue by ChameleonRed** [nltk/nltk#913]
I tried download data for ipipan module but not found on http://korpus.pl/index.php?page=download or http://clip.ipipan.waw.pl/NationalCorpusOfPolish.

This data looks as suitable (similar file names) but not loads http://korpus.pl/download/frek.bin.tar.bz2 some functions not works like `.readme()` and there is not `.words()`, `.sents()`, `.paras()`.

**Comment by ChameleonRed** [comment]
I was prepared such test code:

```
from nltk import corpus
pl = corpus.ipipan

print 'dir', dir(pl)

print 'root', pl.root
print 'fileids', pl.fileids()[0:5]
print 'categories', pl.categories()
print 'channels', pl.channels()
print 'domains', pl.domains()
print 'words', corpus.ipipan.words()
print 'tagged words', corpus.ipipan.tagged_words()
```

Gives such result - something wrong with loading data from http://korpus.pl/download/frek.bin.tar.bz2:

```
dir ['_LazyCorpusLoader__args', '_LazyCorpusLoader__kwargs', '_LazyCorpusLoader__name', '_LazyCorpusLoader__reader_cls', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__name__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '__weakref__', '_get_root', '_get_tag', '_list_header_files', '_list_morph_files', '_list_morph_files_by', '_map_category', '_parse_header', '_view', 'abspath', 'abspaths', 'categories', 'channels', 'domains', 'encoding', 'ensure_loaded', 'fileids', 'open', 'paras', 'raw', 'readme', 'root', 'sents', 'tagged_paras', 'tagged_sents', 'tagged_words', 'unicode_repr', 'words']
root C:\Users\Crezary Wagner\AppData\Roaming\nltk_data\corpora\ipipan
fileids [u'A/A0001/morph.xml', u'A/A0002/morph.xml', u'A/A0003/morph.xml', u'A/A0004/morph.xml', u'A/A0005/morph.xml']
categories []
channels []
domains []
words []
tagged words []
```

**Comment by stevenbird** [comment]
Is this it? I'm thinking about adding this to the NLTK corpus collection, for use with `corpus.reader.nkjp`.
http://clip.ipipan.waw.pl/NationalCorpusOfPolish?action=AttachFile&do=get&target=NKJP-PodkorpusMilionowy-1.2.tar.bz2

**Comment by ChameleonRed** [comment]
**ipipan module** is dead but **ipipan corpus** is not dead - whetever you can not download parsable data for ipipan module - author of module can not help with it - I will ask him again but still not response. 

nkjp is very good direction I am waiting for nltk 3.0.1+ with nkjp. nkjp looks very good and is prepared with more modern tagging methods. Please realease nkjp ASAP.

You can ask author of ipipan module if he will be supporting data for module. I meet today some friend of ipi pan people PAN (Polish Academy of Science) - I am not science man now and I am Polish. Polish language is very difficult to do natural language processing (and learn too) so nltk nkjp will be great step forward (10-40 years forward++).

Try this to learn more state of art tools and resources http://clip.ipipan.waw.pl/LRT.
And also think about this tool for identification of Polish words lemmas, verbs, objectives, aspects (impossible in English) and so on ... http://sgjp.pl/morfeusz/index.html.en.

Polish words are ambiguous and depend on context and inflection - one word can belong to many meaning and have same letters.

**Comment by stevenbird** [comment]
So once I add nkjp (https://github.com/nltk/nltk/pull/844), what still needs to happen?

**Comment by ChameleonRed** [comment]
I think https://pypi.python.org/pypi publication is need I will test nkjp. Next thing is inflection for Polish without it there will be no lemmanization - **nkjp contains some morfeusz/manual lemmatization**. 

**Inflection/lemmatization is very important** in Polish since multi gender, multi inflection, and nice, normal, hard forms of objectives (you will say "old cat" "stary kocur" rather than "stary kot" - you will say "young cat" "mały kotek" rather than "mały kot" - there is much more nuance but hard to express it). It is need to do lemmatization to understand semantic meaning.

Consider that simple singular "cat" has three genders "kot", "kocica", "kocię" and some variants "kotek", "kotka", "kociątko", "kocur", "kocie", "kocurzysko", "kocisko", "kocio" ... it is still one word "cat" - each can have 7 inflections or more male singular "kot", "kota", "kota", "kotu", "kotem", "kocie", "kocie". Some people says that same is possible in English.

See this inflection of one word "cat" in Polish all is one word.
http://pl.wiktionary.org/wiki/kot, http://pl.wiktionary.org/wiki/kotka, ...

Here is morfeusz and "kotka" == female cat.
https://www.dropbox.com/s/q2huz97s433s79m/Zrzut%20ekranu%202015-03-12%2022.33.17.png?dl=0

I put some questions because I do not know how to get word class and lemmatization - lack of knowledge nltk can be also reason.
http://stackoverflow.com/questions/28920787/how-to-take-word-class-in-ntlk
http://stackoverflow.com/questions/28930165/how-can-i-extract-lemma-with-pl196x-from-nltk-for-polish-in-python

**Comment by ChameleonRed** [comment]
You can try http://nkjp.pl/poliqarp/nkjp1M/query/ and "kot", "kotka", "kocię" - all is cat - he, she, it:
 [kot:subst:sg:nom:m2] singular:nominative:male-inflection-2 (can be about one of 150 inflections)
 [kotek:subst:sg:acc:m2] OR  "[kotka:subst:sg:nom:f]" (accusative male or nominative female - context need to determine)
 "[kocię:subst:sg:nom:n]" (nominative neutral) (morfeusz tagged 300 mln corpus not 1 milion manual)
