### ISSUE TITLE
Add stopwords for Azerbaijani

### ISSUE THREAD

**Issue by he7d3r** [nltk/nltk#914]
Currently, the stopwords corpora available in NLTK data only includes these languages: danish, dutch, english, finnish, french, german, hungarian, italian, norwegian, portuguese, russian, spanish, swedish and turkish.

This is a feature request for a similar list of stopwords for the _Azerbaijani_ language (az). Something like 100--150 words should be a good start, and would be enough for our purposes.

**Comment by stevenbird** [comment]
Sure, that would be welcome.

**Comment by domspad** [comment]
Looks like there's no resource out there for this language yet. I managed to aggregate the texts of [63 "Good Articles" from the Azerbaijani wikipedia](https://az.wikipedia.org/wiki/Vikipediya:Yax%C5%9F%C4%B1_m%C9%99qal%C9%99l%C9%99r) and calculate what seems to be a plausible set of stopwords. [Here's a link](https://github.com/domspad/azerbaijani_stop_words) to a repo with the data and computations. *Note the English translations are according to Google

| Azer | Eng |
| --- | --- |
| və | and |
| bir | a |
| ilə | with |
| ci | th |
| bu | this |
| ildə | in |
| of | of |
| isə | and |
| sonra | after |
| ki | that |
| üçün | for |
| da | also |
| də | also |
| olan | being |
| az | little |
| kimi | as |
| edir | is |
| çox | many |
| tərəfindən | by |
| the | the |
| ə | the |
| görə | according to |
| xan | khan |
| onun | his |
| idi | It was |
| ən | most |
| il | year |
| olaraq | in |
| cü | th |
| and | oath |
| s | s |
| haqqında | about |
| o | he |
| ilk | first |
| zaman | time |
| öz | her |
| cu | th |
| daha | more |
| cı | th |
| edən | the |
| yaxşı | good |
| olur | is |
| in | s |
| bütün | all |
| istifadə | use |
| onu | it |
| etmək | do |
| qədər | to |
| arasında | between |
| biri | one of |
| ona | her |
| hər | each |
| etmişdir | has |
| a | a |
| olmuşdur | was |
| var | there |

**Comment by domspad** [comment]
Wow finally came across [this](http://www.lexiteria.com/word_frequency/azerbaijani_word_frequency_list.html) as well, will take a closer look at the words later

**Comment by limpapud** [comment]
Well, maybe it is time for closer look @domspad ? 
What can I do to make it happen? (Despite I am new to GH, I want this issue to resolve)

**Comment by stevenbird** [comment]
Words like "little", "year", and "oath" are stopwords?

**Comment by limpapud** [comment]
Well, "little" and "year" are, but probably "oath" is translation typo, 
"oath" in Azeri is "and" and it is not stop word, but english word 'and' is. 
Added 165 words and pushed. Please check :)

**Comment by limpapud** [comment]
@domapad @stevenbird please check my PR, if it is OK. Thanksl
