### ISSUE TITLE
nltk 3.0.2 + Python 3.4 -> Resource 'help/tagsets/PY3/upenn_tagset.pickle' not found.

### ISSUE THREAD

**Issue by hyp3rv1p3r** [nltk/nltk#919]
Hi all,
just installed nltk 3.0.2 and I found this issue:

> > > import nltk
> > > nltk.help.upenn_tagset()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk-3.0.2-py3.4.egg/nltk/help.py", line 25, in upenn_tagset
> > >     _format_tagset("upenn_tagset", tagpattern)
> > >   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk-3.0.2-py3.4.egg/nltk/help.py", line 39, in _format_tagset
> > >     tagdict = load("help/tagsets/" + tagset + ".pickle")
> > >   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk-3.0.2-py3.4.egg/nltk/data.py", line 781, in load
> > >     opened_resource = _open(resource_url)
> > >   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk-3.0.2-py3.4.egg/nltk/data.py", line 895, in _open
> > >     return find(path_, path + ['']).open()
> > >   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk-3.0.2-py3.4.egg/nltk/data.py", line 624, in find
> > >     raise LookupError(resource_not_found)
> > > LookupError: 
> > > ---
> > > 
> > >   Resource 'help/tagsets/PY3/upenn_tagset.pickle' not found.
> > >   Please use the NLTK Downloader to obtain the resource:  >>>
> > >   nltk.download()
> > >   Searched in:
> > >     - '/Users/user/nltk_data'
> > >     - '/usr/share/nltk_data'
> > >     - '/usr/local/share/nltk_data'
> > >     - '/usr/lib/nltk_data'
> > >     - '/usr/local/lib/nltk_data'
> > >     - ''
> > > ---

**Comment by stevenbird** [comment]
Thanks for reporting this problem. Resolved in https://github.com/nltk/nltk_data/commit/3e786aba2c708d61868fb44f23acca9ea69b5d0e; the tagsets file needs to be unzipped. Please unzip the file manually, or else re-download it (e.g. with `sudo python -m nltk.downloader tagsets`.

**Comment by Anujay-Saraf** [comment]
not working
