### ISSUE TITLE
BLEU score brevity penalty does not follow definition

### ISSUE THREAD

**Issue by kylebgorman** [nltk/nltk#922]
Papineni et al. (2002), if I understand correctly, define the BLEU brevity penalty as follows:
- let _c_ be the length of the candidate
- let _r_ be the length of the reference which is closest in length to the candidate

Then, BP = 1 if c > r, and BP = exp(1 - r / c) otherwise.

(There are some details about doing this at the corpus level, but they're not relevant to the point at hand.) 

But this not what `nltk.align.bleu_score._brevity_penalty` (called by `nltk.align.bleu_score`) computes. Rather, it computes _r_ as follows:

```
c = len(candidate)
r = min(abs(len(r) - c) for r in references)
```

So if _c_ is 12 and _r_ under Papineni et al.'s definition is 28, then this function will set `r` to 16, not 28.

However, it is possible I have misunderstood the original paper. And it would be ideal to test this against a canonical implementation. But if I have understood correctly, the fix would be something like:

```
c = len(candidate)
ref_lens = [len(ref) for ref in references]
r = min(ref_lens, key=lambda ref_len: abs(ref_len - c))
```

**Comment by dimazest** [comment]
Hi,

Thank you for the report.

I might be overseeing some small details in the snippets you provided, but your solution does exactly the same as the current in NLTK.

> So if c is 12 and r under Papineni et al.'s definition is 28, then this function will set r to 16, not 28.

If c (12) is less then r (28) then the function returns 1, because c is less then r.

I'll check the paper, but first I need to have a cup of coffee :)

**Comment by kylebgorman** [comment]
> I might be overseeing some small details in the snippets you provided, but your solution does exactly the same as the current in NLTK.

I respectively disagree. A worked example follows:

```
from math import exp
candidate = "MANY WILL LOSE THEIR RIGHT TO A PENSION IN THEIR OWN NAME".split()
ref0 = "MANY WILL LOSE THEIR RIGHT TO A PENSION IN THEIR OWN NAME BECAUSE OF THEIR HUSBAND 'S INCOME , WHILE MANY OTHERS WILL SEE THEIR PENSIONS REDUCED .".split()
ref1 = "MANY WILL LOSE THEIR RIGHT TO A PENSION IN THEIR OWN NAME BECAUSE OF THEIR HUSBANDS ' INCOME WHILE OTHERS WILL REDUCE THE AMOUNT OF THEIR PENSION .".split()
references = [ref0, ref1]
c = len(candidate)
ref_lens = [len(ref) for ref in references]
r = min(ref_lens, key=lambda ref_len: abs(ref_len - c))
BP = 1. if c > r else exp(1. - r / c)
print "c:\t{}".format(c)
print "r:\t{}".format(r)
print "BP:\t{:.4f}".format(BP)
```

This prints:

```
c:  12
r:  28
BP: 0.3679
```

Compare the following (with the same initializations):

```
from nltk.align.bleu_score import _brevity_penalty
print "BP:\t{:.4f}".format(_brevity_penalty(candidate, references))
```

which prints:

```
BP: 0.7165
```

Even intuitively, this is wrong. The candidate is far, far too short, and so an exponential brevity penalty should penalize it aggressively.

> If c (12) is less then r (28) then the function returns 1, because c is less then r.

I believe you have that backwards. The brevity penalty is always _less than_ 1 if c is less than r, because it is intended to penalize candidates that are too short; the brevity penalty is 1 only if c is _greater than_ or equal to r. The NLTK implementation agrees:

```
    if c > r:
        return 1
    else:
        return math.exp(1 - r / c)
```

**Comment by dimazest** [comment]
I've finally got it. Thanks for the explanation. (I should not try to read code early in the morning)

Running the example on python 3, I get 0.2636, not 0.3679 (but that's because of true division)

```
c:  12
r:  28
BP: 0.2636
```

Another question, just to be sure. For `c = 12` and the reference lengths of `13` and `2` the brevity penalty should be 0.92, not 1.

``` python
>>> c = 12
>>> ref_lens = [2, 13]
>>> r = min(ref_lens, key=lambda ref_len: abs(ref_len - c))
>>> r
13
>>> 1. if c > r else exp(1. - r / c)
0.92...
```

**Comment by dimazest** [comment]
What should be done in this case (assuming the implementation in https://github.com/dimazest/nltk/blob/bleu_another_fix/nltk/align/bleu_score.py#L206 )?

``` python
    >>> references = [['a'] * 13, ['a'] * 11]
    >>> candidate = ['a'] * 12
    >>> _brevity_penalty(candidate, references)
    0.92...
    >>> _brevity_penalty(candidate, reversed(references))
    1
```

**Comment by kylebgorman** [comment]
Oops on true division. I work in Python 3 99% of the time, so I forgot to import future-division.

Good point, the brevity penalty equation should have sane behavior in the presence of ties in `abs(ref_len - c)`. The paper does not say, but the official `mteval.pl` script from NIST has a (reasonable) opinion. Their examples are for c = 7:

```
brevity_penalty_closest( 11, 8, 7 ) returns 8, since abs( 8 - 7 ) < abs( 11 - 7 )
brevity_penalty_closest( 8, 6, 7 ) returns 6, since abs( 8 - 7 ) == abs( 6 - 7 ) AND 6 < 8
brevity_penalty_closest( 7, 6, 7 ) returns 7, since abs( 7 - 7 ) < abs( 6 - 7 )
```

So, you want to choose the lower of the two when there's a tie, apparently. This seems reasonable.

```
c = len(candidate)
ref_lens = [len(ref) for ref in references]
mindiff = min(abs(ref_len - c) for ref_len in ref_lens)
# if there's a tie, choose r < c rather than c < r
r = c - mindiff
if r not in ref_lens:
    r = c + mindiff
```

K

(edited for a bug i found)

**Comment by dimazest** [comment]
#926 is supposed to fix this

**Comment by kylebgorman** [comment]
if those tests pass then i think it's right!

**Comment by stevenbird** [comment]
Thanks for checking @kylebgorman.

**Comment by stevenbird** [comment]
Thanks @dimazest
