### ISSUE TITLE
unicodedecodeerror at StanfordParser on windows command prompt

### ISSUE THREAD

**Issue by cy-goh** [nltk/nltk#929]
nltk.parse.stanford throws a unicodedecodeerror when processing inputs with utf-8 characters.

```
        stdout, stderr = java(cmd, classpath=(self._stanford_jar, self._model_jar),
                              stdout=PIPE, stderr=PIPE)
        stdout = stdout.decode(encoding)
```

This happens in windows command prompt, when java outputs the parse tree in window's default encoding. I find that the adding "-Dfile.encoding=UTF-8" into cmd arguments in internals.py circumvents this problem.

Shouldn't StanfordParser provide an argument to remedy this?

**Comment by manning** [comment]
The Stanford parser does provide its own command-line flag for `-encoding utf-8` or whatever, but if you don't provide one, then the platform default encoding is used, and that's what you're overriding with the "-Dfile.encoding=UTF-8" flag to Java.

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools.
