### ISSUE TITLE
Snowball Stemmer error on Hungarian

### ISSUE THREAD

**Issue by Stophface** [nltk/nltk#939]
That came up already a couple of times when I try to stem Hungarian text:

`Traceback (most recent call last):
  File "ranking_tags_dynamic.py", line 40, in <module>
    wordStemmed = stemmer.stem(j)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/nltk/stem/snowball.py", line 1912, in stem
    r1 = self.__r1_hungarian(word, self.__vowels, self.__digraphs)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/nltk/stem/snowball.py", line 2072, in __r1_hungarian
    if word[0] in vowels:`

**Comment by stevenbird** [comment]
@Stophface: did you submit the complete error message? I think there might be something missing.

**Comment by Stophface** [comment]
@stevenbird yep, I have
    IndexError: string index out of range was missing.

**Comment by stevenbird** [comment]
Thanks. That line would only generate an IndexError if `word` was an empty string. Can you please check your code to see if `j` can be empty in `stemmer.stem(j)`?

**Comment by Stophface** [comment]
It is very likely that `j` is empty! 
I have an empty `j` all the time. It only raises an exeption with the hungarian stemmer though. With the others it works just fine...
