### ISSUE TITLE
Chapter 6 bad choice of variable name

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#94]
Which version of the book are you using? Online

Please specify the chapter and section number(s) 6

<b>Please describe any problems in as much detail as possible, and feel free</b>
<b>to suggest fixes.</b>

In the section, Gender Identification the following example:

&gt;&gt;&gt; from nltk.corpus import names
&gt;&gt;&gt; import random
&gt;&gt;&gt; names = ([(name, 'male') for name in names.words('male.txt')] +
...          [(name, 'female') for name in names.words('female.txt')])
&gt;&gt;&gt; import random
&gt;&gt;&gt; random.shuffle(names)

While it works, as it is, it might be a better example to use a different
variable name than &quot;names&quot; for the list of male and female names after just
importing a &quot;names&quot; module. <p>Migrated from http://code.google.com/p/nltk/issues/detail?id=494</p><hr/><h2>earlier comments</h2>

<p><strong>StevenBird1 said, at 2009-12-07T01:11:44.000Z:</strong></p>

<p>Thanks for pointing out this problem.  Unfortunately there are many references to
"names" that would have to be fixed -- we need to decide if this is feasible for the
reprinting.
</p>

**Comment by alvations** [comment]
This should have been resolved.  The current book uses `labelled_names` as the variable instead of `names: https://github.com/nltk/nltk_book/blob/master/book/ch06.rst
