### ISSUE TITLE
treebank tokenizer leaves commas at the end of sentences 

### ISSUE THREAD

**Issue by helmanofer** [nltk/nltk#948]
when trying to tokenize the following sentence:

```
print(nltk.word_tokenize("hi, my name can't hello,"))
```

the output is:

```
['hi', 'my', ',', 'name', 'ca', "n't", 'hello,']
```

which means that there is a new feature, 'hello,'
I am not too good with regex but my suggestion is in treebank.py +67

```
  text = re.sub(r'([:,])([^\d])', r' \1 \2', text)
+ text = re.sub(r'([:,])$', r' \1 ', text)
  text = re.sub(r'\.\.\.', r' ... ', text)
```

**Comment by alvations** [comment]
@helmanofer is it still happening with the fixes on #996 and #1000 ?
