### ISSUE TITLE
Distributing tweet collections as corpora in NLTK

### ISSUE THREAD

**Issue by ewan-klein** [nltk/nltk#955]
According to https://dev.twitter.com/overview/terms/policy#6._Be_a_Good_Partner_to_Twitter:

> If you provide Content to third parties, including downloadable datasets of Content or an API that returns Content, you will only distribute or allow download of Tweet IDs and/or User IDs.
> - You may, however, provide export via non-automated means (e.g., download of spreadsheets or PDF files, or use of a “save as” button) of up to 50,000 public Tweets and/or User Objects per user of your Service, per day.

I've had confirmation from Twitter that the bulleted clause **would** allow us to make a collection of up to 50k full tweets available as part of the NLTK data distribution. I believe that the relevant license would be the [Twitter Developer Agreement](https://dev.twitter.com/overview/terms/agreement), and it seems to me that this would not limit in any significant way the rights of NLTK users to process the tweets. However, note that NIST placed specific restrictions on the usage of tweet content recovered from IDs in [this license agreement](http://trec.nist.gov/data/tweets/tweets2011-agreement.pdf).

We also have the option of distributing Tweet IDs and leaving it to the user to recover the full tweets via the Twitter API. It would be up to the user to abide by Twitter's terms and conditions but I don't think we would be responsible for that, other than drawing the user's attention to the Twitter Developer Agreement.  It's unclear what the copyright/license status of a list of Tweet IDs is, but it seems reasonable to suppose that the list would be in the public domain, since it's unlikely that either the Tweet IDs themselves or the particular selection and sequence of IDs would be copyrightable.

However, it is all relatively uncharted territory. Any thoughts on how we should proceed?

**Comment by lrnzcig** [comment]
@ewan-klein,

Please take into account that the second solution, distributing tweet id's and let the user recover them, is constraint by [twitter rate limits](https://dev.twitter.com/rest/public/rate-limits). The fastest way to fetch the tweets would be using [GET statuses/lookup](https://dev.twitter.com/rest/reference/get/statuses/lookup), which accepts 100 id's per request, and 60 requests per 15 minutes window, equals to 2400 tweets/hour.

It is doable, but a bit annoying, even if automated. I would use it only if the 50K full tweets in the NLTK distribution are not enough (well, it also depends on the actual meaning of "... Twitter clause **would** allow us...").

Thanks!

**Comment by ewan-klein** [comment]
Added first tranche of 20k tweets to nltk_data in e042f682b270a1536306298631074a59109e6566
