### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size, try recompiling

### ISSUE THREAD

**Issue by andrewyang96** [nltk/nltk#959]
I installed nltk on my 64-bit Windows 8 using the 32-bit MS Windows installer, because I have 32-bit Python 2.7.9 installed. I also have Numpy version 1.7.0 installed. However when I type `import nltk` into the Python interpreter, I get this:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Tools\Python279\lib\site-packages\nltk__init__.py", line 117, in <mo
> dule>
>     from nltk.align import *
>   File "C:\Tools\Python279\lib\site-packages\nltk\align__init__.py", line 15, i
> n <module>
>     from nltk.align.ibm1 import IBMModel1
>   File "C:\Tools\Python279\lib\site-packages\nltk\align\ibm1.py", line 18, in <m
> odule>
>     from nltk.corpus import comtrans
>   File "C:\Tools\Python279\lib\site-packages\nltk\corpus__init__.py", line 66,
> in <module>
>     from nltk.corpus.reader import *
>   File "C:\Tools\Python279\lib\site-packages\nltk\corpus\reader__init__.py", li
> ne 59, in <module>
>     from nltk.corpus.reader.tagged import *
>   File "C:\Tools\Python279\lib\site-packages\nltk\corpus\reader\tagged.py", line
>  17, in <module>
>     from nltk.tag import str2tuple, map_tag
>   File "C:\Tools\Python279\lib\site-packages\nltk\tag__init__.py", line 65, in
> <module>
>     from nltk.tag.sequential    import (SequentialBackoffTagger, ContextTagger,
>   File "C:\Tools\Python279\lib\site-packages\nltk\tag\sequential.py", line 25, i
> n <module>
>    from nltk.classify.naivebayes import NaiveBayesClassifier
>   File "C:\Tools\Python279\lib\site-packages\nltk\classify__init__.py", line 93
> , in <module>
>     from nltk.classify.scikitlearn import SklearnClassifier
>   File "C:\Tools\Python279\lib\site-packages\nltk\classify\scikitlearn.py", line
>  40, in <module>
>     from sklearn.feature_extraction import DictVectorizer
>   File "C:\Tools\Python279\lib\site-packages\sklearn\feature_extraction__init__
> .py", line 7, in <module>
>     from .dict_vectorizer import DictVectorizer
>   File "C:\Tools\Python279\lib\site-packages\sklearn\feature_extraction\dict_vec
> torizer.py", line 14, in <module>
>     from ..utils import atleast2d_or_csr, tosequence
>   File "C:\Tools\Python279\lib\site-packages\sklearn\utils__init__.py", line 10
> , in <module>
>     from .murmurhash import murmurhash3_32
>   File "numpy.pxd", line 861, in init sklearn.utils.murmurhash (sklearn\utils\mu
> rmurhash.c:5033)
> ValueError: numpy.ufunc has the wrong size, try recompiling

**Comment by stevenbird** [comment]
Is this an NLTK issue?

**Comment by andrewyang96** [comment]
I'm not sure, however I can import numpy and use numpy in my programs just fine.

**Comment by jnothman** [comment]
Can you import sklearn just fine? Try `pip install -U sklearn`.

**Comment by andrewyang96** [comment]
Yes I can import sklearn just fine.

**Comment by andrewyang96** [comment]
I found the problem! I was running an old version of numpy (1.7.2). I upgraded it to 1.9.2 and now I can import nltk!

**Comment by jnothman** [comment]
It's an issue caused by discrepancy in numpy version
between scikit-learn's compile- and run-time.

**Comment by jnothman** [comment]
(I think!)
