### ISSUE TITLE
MT visualization

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#960]
Support visualisation of [word-aligned sentences](https://github.com/nltk/nltk/blob/develop/nltk/align/api.py#L16) following the method of using dot and svg from the [dependency tree visualization](https://github.com/nltk/nltk/blob/develop/nltk/parse/dependencygraph.py#L160).

**Comment by longdt219** [comment]
Hi @stevenbird 
This is merged, could you please close the issue.
