### ISSUE TITLE
nltk.sem.relextract.ne_chunked() error, needs update

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#97]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>

2.0b7

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
import nltk
nltk.sem.relextract.ne_chunked()

Produces no output.

<b>What is the expected output? What do you see instead?</b>

I expect to see the relationships printed.  Instead I just see &quot;[]&quot; 100 times.

<b>Please use labels and text to provide additional information.</b>
Line 461 in nltk/sem/relextract.py is:
        print extract_rels('ORG', 'LOC', sent, corpus='ace', pattern = IN)

However, the documentation for extract_rels reads
   &quot;The parameters C{subjclass} and C{objclass} can be used to restrict the
    Named Entities to particular types (any of 'LOCATION', 'ORGANIZATION',
    'PERSON', 'DURATION', 'DATE', 'CARDINAL', 'PERCENT', 'MONEY',
    'MEASURE').&quot;

So this line should be:
        print extract_rels('ORGANIZATION', 'LOCATION', sent, corpus='ace',
pattern = IN)

However, even after fixing the line it still just prints 100 &quot;[]&quot; lines.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=507</p><hr/><h2>earlier comments</h2>

<p><strong>StevenBird1 said, at 2010-02-03T10:19:10.000Z:</strong></p>

<p>Referring this to Ewan for review</p>

**Comment by ewan-klein** [comment]
Fixed in d566f23c6341c2c9263ac0da7d778a38100b0a64
