### ISSUE TITLE
Issue importing pylab (object has no attribute 'grid')

### ISSUE THREAD

**Issue by aoldoni** [nltk/nltk#970]
Hi All,

This is my first request, hope not to be doing it in the wrong place.

When trying to print the frequency distribution from "3.1", Chapter 1 - I would have the following error:

```
  File "./tests.py", line 30, in main
    fdist1.plot(50, cumulative=True)
  File "/usr/local/lib/python3.4/site-packages/nltk/probability.py", line 247, in plot
    pylab.grid(True, color="silver")
AttributeError: 'module' object has no attribute 'grid'
```

I was able to fix the problem by changing all `import pylab` directives to `import matplotlib.pylab as pylab` in the probability.py file.

Does this makes sense? Can I create a pull request for this?

I am using:
- python3 in macos yosemite, installed via brew
- installed nltk via pip
- installed matplotlib via pip

Thanks!

**Comment by stevenbird** [comment]
Thanks for reporting the problem @aoldoni. I can't replicate it. Pylab just imports matplotlib.pylab. The only explanation I can think of is that you might get a different version of matplotlib.pylab depending on which version of the import statement you use.

**Comment by aoldoni** [comment]
Thanks @stevenbird - that's fine, I couldn't find exactly why I had to do this modification.

Just some extra information: When I do `import pylab` I believe it resolves to the pylab package folder, which for me contains only empty files.

```
ComputerName:pylab user$ pwd
/usr/local/lib/python3.4/site-packages/pylab
ComputerName:pylab user$ cat __init__.py 
# -*- coding: utf-8 -*-

__author__ = 'Javi Palanca'
__email__ = 'jpalanca@gmail.com'
__version__ = '0.1.0'

ComputerName:pylab user$ cat pylab.py 
# -*- coding: utf-8 -*-
```

I am not sure what the contents here should be. Anyhow, I would propose that maybe having `import matplotlib.pylab as pylab` could potentially work in more situations.

Please let me know if this is something that would help. I would be happy to do a pull request for this simple change.

Otherwise, I will investigate more - but looks like something local to my environment, and maybe this can be closed.

Thanks.

**Comment by stevenbird** [comment]
Done, thanks @aoldoni

**Comment by aoldoni** [comment]
Great, thank you @stevenbird - glad I helped somehow.
