### ISSUE TITLE
nltk.wsd missing from documentation

### ISSUE THREAD

**Issue by davechallis** [nltk/nltk#976]
The nltk.wsd module is part of NLTK 3.x, but doesn't appear in the online documentation (e.g. http://www.nltk.org/py-modindex.html).

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/4df9ff00bccf0ee6d78ddac261c09a58f7d00ab1 and deployed, cf http://www.nltk.org/api/nltk.html?highlight=wsd#module-nltk.wsd

**Comment by stevenbird** [comment]
Thanks @davechallis
