### ISSUE TITLE
formula TF is not canonical

### ISSUE THREAD

**Issue by ermakovpetr** [nltk/nltk#978]
nltk/nltk/text.py

``` python
def tf(self, term, text, method=None):
    """ The frequency of the term in text. """
    return text.count(term) / len(text)
```

http://en.wikipedia.org/wiki/Tf–idf
Real TF is only the number of occurrences of words in text

And there is also a variation of the "normalization":
1. Boolean "frequencies": tf(t,d) = 1 if t occurs in d and 0 otherwise;
2. Logarithmically scaled frequency: tf(t,d) = 1 + log f(t,d), or zero if f(t, d) is zero;
3. Augmented frequency, to prevent a bias towards longer documents, e.g. raw frequency divided by the maximum raw frequency of any term in the document:
![5cc18acd4dbd9be636047fc2a7a10105](https://cloud.githubusercontent.com/assets/454655/7628683/f5e1a168-fa2e-11e4-9ddd-5791855edcec.png)
4. Normalization of the number of all words
![afcade8c6e040203a292c8ca784fa3f3](https://cloud.githubusercontent.com/assets/454655/7628719/5597925c-fa2f-11e4-812c-c7aeb6d4e48d.png)

Source: wiki, Introduction to information retrieval, ...

But before that code, I have not seen anywhere else the normalization of the length of the text.

**Comment by ermakovpetr** [comment]
see pull request https://github.com/nltk/nltk/pull/979

**Comment by jnothman** [comment]
I agree that this is non-standard, although I have heard of it elsewhere (no citation). Also, something akin to length normalisation occurs with the l2-normalisation of cosine similarity, although that would take the idf into account.

**Comment by serapio** [comment]
Length normalization is included in Lucene's tf-idf, as well as in
alternative relevance measures like BM25. That said, neither of those
length normalizations are linear with the length itself. Lucene's tf-idf
uses 1/sqrt(len(text)), and in BM25 it is 1/(constants + len(text)).

On Thu, May 14, 2015 at 8:05 PM, jnothman notifications@github.com wrote:

> I agree that this is non-standard, although I have heard of it elsewhere
> (no citation). Also, something akin to length normalisation occurs with the
> l2-normalisation of cosine similarity, although that would take the idf
> into account.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nltk/nltk/issues/978#issuecomment-102239131.

## 

Lucien S. Carroll
Graduate Student
UCSD Linguistics
http://ling.ucsd.edu/~lucien

**Comment by alexisdimi** [comment]
Wikipedia actually includes linear TF. The section on TF starts with _"In the case of the term frequency tf(t,d), the simplest choice is to use the raw frequency of a term in a document, i.e. the number of times that term t occurs in document d."_ Also, whoever took out the domain http://tfidf.com specifies linear scaling for TF. 

But both definitions refer to the number of "terms" in the document, which I've always interpreted as the number of words, i.e. excluding punctuation tokens. Linearity aside, it makes sense that non-words should be irrelevant to the prominence of a term in a document.

**Comment by stevenbird** [comment]
@ermakovpetr – what do you think about supporting all definitions of tf listed in the Stanford IR book, with an optional `method` flag, defaulting to raw frequency (`method='natural'`), and drop the existing one (since it's not even listed in the English Wikipedia entry for tf.idf)? And likewise for idf?
