### ISSUE TITLE
tgrep doctests

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#981]
Lots of tgrep doctests are failing. @wroberts would you mind taking a look please? It might just be a matter of converting a generator into a list in various places.

https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/testReport/

**Comment by sahutd** [comment]
Hi, I have trouble running doctest for tgrep. I see that there are no .doctest file for tgrep module in nltk/test. Would you please explain how I should run the doctests for tgrep module?

**Comment by wroberts** [comment]
Hi @sahutd !  You can run the doctests and unit tests with:

```
nltk/test/runtests.py -v nltk.tgrep
nltk/test/runtests.py -v nltk.test.unit.test_tgrep
```

**Comment by nltk-webdeploy** [comment]
I think the failing doctests occur because a generator is returned instead
of a list, or vice versa.

**Comment by sahutd** [comment]
Thanks. Will work on it now.

**Comment by wroberts** [comment]
Hi @stevenbird I've fixed up some issues in pull request #990.  There's something quite wrong with tgrep though; the search functions return very long lists of empty list items.  Could be confusion between generators and lists, which can also be confused with tgrep trees (which are also a kind of list!).  I'll try looking through the history to see if I can figure out where things went wrong.

**Comment by sahutd** [comment]
@wroberts  : I saw your pull request, and it overlaps with what I worked on just now. I will wait for your PR to be merged. Then depending on whats failing, I will work on that. For now, I will look for other issues to work on.

**Comment by wroberts** [comment]
OK, got it. I hadn't realised the order of the arguments to tgrep_nodes and tgrep_positions had changed. Should be good to go now.

**Comment by wroberts** [comment]
@sahutd Sorry to step on your toes!

**Comment by sahutd** [comment]
@wroberts No issues! Learnt something :)
