### ISSUE TITLE
crubadan doctests

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#982]
Some of the Crubadan tests are failing. @avitalp would you mind having a look please?
https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py26-jenkins,jdk=jdk8latestOnlineInstall/lastCompletedBuild/testReport/(root)/crubadan_doctest/crubadan_doctest/

**Comment by avitalp** [comment]
@stevenbird I've submitted a PR with updated doctest as well as a small corpus reader check for lang support (https://github.com/nltk/nltk/pull/984)

**Comment by stevenbird** [comment]
Thanks @avitalp.
