### ISSUE TITLE
PanLex interface

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#983]
@kamholz, @leksilo and I have agreed on a simplified schema and API for [PanLex](http://panlex.org/), and @kamholz has created an sqlite dump and a Python wrapper for inclusion in NLTK. The wrapper needs to be made into a corpus reader, documented, and added to NLTK.

**Comment by longdt219** [comment]
Hi @stevenbird , 
The datafile for Panlex is quite big. It is more than 800 mb for the dump that contains these common languages: 

(u'arb-000', 34, u'arb')
(u'ben-000', 67, u'ben')
(u'cmn-002', 128, u'cmn')
(u'deu-000', 157, u'deu')
(u'eng-000', 187, u'eng')
(u'fra-000', 211, u'fra')
(u'hin-000', 275, u'hin')
(u'ind-000', 298, u'ind')
(u'ita-000', 304, u'ita')
(u'jav-000', 309, u'jav')
(u'jpn-000', 315, u'jpn')
(u'kan-000', 320, u'kan')
(u'kor-000', 357, u'kor')
(u'mar-000', 411, u'mar')
(u'zsm-000', 444, u'zsm')
(u'pan-000', 554, u'pan')
(u'por-000', 579, u'por')
(u'rus-000', 620, u'rus')
(u'spa-000', 666, u'spa')
(u'tam-000', 698, u'tam')
(u'tel-000', 706, u'tel')
(u'tur-000', 738, u'tur')
(u'urd-000', 757, u'urd')
(u'vie-000', 764, u'vie')
(u'wuu-000', 790, u'wuu')
(u'yue-000', 820, u'yue')
(u'zlm-000', 1240, u'zlm')
(u'cmn-000', 1627, u'cmn')
(u'cmn-001', 1628, u'cmn')
(u'cmn-003', 1835, u'cmn')
(u'pnb-000', 2042, u'pnb')
(u'jpn-001', 5590, u'jpn')
(u'kor-001', 6850, u'kor')

**Comment by stevenbird** [comment]
The complete dataset is even bigger. But the size is not a problem, so long as performance of sqlite is adequate. Can you report some performance results on a desktop machine with large RAM, for queries to get the translations of words between specific language pairs?

**Comment by longdt219** [comment]
Hi @stevenbird , 
Getting translation for a word between languages is acceptable. 
Running with the full dump db4.sqlite (4.2 G), on my computer UbuntuX64, 8Gb ram, Core i7 3.4, the translation from English -> German takes 
14s for cat (>50 results) 
11s for garden (~50 results)
7s for kite (20 results) 

My query is 
SELECT ex.tt,ex2.tt
FROM mn
JOIN ex ON (ex.ex = mn.ex)
JOIN mn mn2 ON (mn2.mn = mn.mn)
JOIN ex ex2 ON (ex2.ex = mn2.ex)
WHERE mn.ex != mn2.ex AND ex.lv = ? AND ex2.lv = ? AND ex.tt = ?

**Comment by stevenbird** [comment]
This is resolved

**Comment by lingling91** [comment]
Hi, I have problem in unzipping the panlex_life,zip, the status is still unzipping the panlex_life.zip after 8 hours
