### ISSUE TITLE
PlaintextCorpusReader (or dependency?) confused by BOM

### ISSUE THREAD

**Issue by alexisdimi** [nltk/nltk#985]
I've come across a rather perplexing bug in PlaintextCorpusReader with python 3: If an input file begins with a UTF-8 BOM and the file contains two adjacent newlines anywhere (or if some other conditions are met), the corpus reader will crash with a mysterious assertion error from the guts of corpus/reader/util.py:

```
...python3.4/site-packages/nltk/corpus/reader/util.py in iterate_from(self, start_tok)
    294                 self.read_block.__name__)
    295             num_toks = len(tokens)
--> 296             new_filepos = self._stream.tell()
    297             assert new_filepos > filepos, (
    298                 'block reader %s() should consume at least 1 byte (filepos=%d)' %

/Applications/Experimental/anaconda/lib/python3.4/site-packages/nltk/data.py in tell(self)
   1294             check1 = self._incr_decode(self.stream.read(50))[0]
   1295             check2 = ''.join(self.linebuffer)
-> 1296             assert check1.startswith(check2) or check2.startswith(check1)
   1297 
   1298         # Return to our original filepos (so we don't have to throw

AssertionError: [...]
```

The error occurs when using the output of `sents()`, and only when we get to the problem file. It does not occur with `words()`, so of course I suspect the paragraph (or sentence?) tokenizer.

The problem does not arise with Python 2.7 and either NLTK 2.0b4 or NLTK 3: The BOM is simply treated as regular text (and split into two odd-looking tokens).

Very short inputs do not always trigger the bug, because in addition to the BOM certain other conditions must be met. Two adjacent newlines internal to the file seem to be sufficient (though the bug can also arise without them), so the conditions are usually satisfied by long-ish plain text files. (But the Reuters corpus, which has an idiosyncratic format without blank lines, does not trigger it.) Here are some byte strings that exercise the error:

Non-final \n\n: Reader fails. Non-blank text needed before \n\n, but a blank suffices after

```
--> FAILS: b'\xef\xbb\xbf Some text \n\n '
   WORKED! b'\xef\xbb\xbf \n\n \n'
   WORKED! b'\xef\xbb\xbf Some text \n \n\n'   # The \n\n cannot be final
```

Three or more \r\n fail, even when final:

```
--> FAILS: b'\xef\xbb\xbf Some text \r\n\r\n\r\n'
   WORKED! b'\xef\xbb\xbf Some text \r\n\r\n'
   WORKED! b'\xef\xbb\xbf Some text \n\n\n\n\n\n\n\n'
```

Just to confirm: the BOM must be present to trigger the error.

```
   WORKED! b'Something here\n\n\n\n\n and more, but still works\n\n etc.'
```

I'm doing this on OS X with Mountain Lion and Anaconda, in case it makes a difference.

Alexis

**Comment by jsstoroz** [comment]
I'm having a similar issue with the TaggedCorpusReader using Python 3 and NLTK 3. Any advice for how to fix/circumvent it?

**Comment by alexisdimi** [comment]
@jsstoroz: A good work-around is to pre-process your corpus to remove the BOM.

UTF-8 does not need a BOM and should not, in principle, have one; but Windows likes to add it anyway. So by removing it you're also improving your files, in a sense. To clear the BOM, read in a file with encoding `utf_8_sig` and write it out with encoding `utf_8`.
