### ISSUE TITLE
Integer division

### ISSUE THREAD

**Issue by djstrong** [nltk/nltk#989]
In nltk/align/bleu_score.py, in `_modified_precision(candidate, references, n)` the last line is:
`return sum(clipped_counts.values()) / sum(counts.values())`
I think there should be float division:
`return float(sum(clipped_counts.values())) / sum(counts.values())`

It influences BLEU score.

**Comment by stevenbird** [comment]
@djstrong we have `from __future__ import division` at the top of the module.

**Comment by djstrong** [comment]
Oh, sorry. I used nltk code to implement smoothed BLUE without imports...
