### ISSUE TITLE
UDHR corpus fileid 'Kazakh-UTF8' has letters not from Kazakh alphabet

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#99]
<b>What version of NLTK are you using?  (See nltk.**version**).  Please only</b>
<b>submit bug reports for the current version.</b>
NLTK version: 2.0b2
Python version: 2.5

<b>What steps will reproduce the problem?  (e.g. include Python source code)</b>
import nltk
from nltk.corpus import udhr
print udhr.raw(fileids='Kazakh-UTF8')

<b>What is the expected output? What do you see instead?</b>
The expected output is:
АДАМ ҚҰҚЫҚТАРЫНЫҢ ЖАЛПЫҒА БІРДЕЙ ДЕКЛАРАЦИЯСЫ 
ПРЕАМБУЛА
Адам баласы үйелменінің барлық мүшелеріне тән қадір‐қасиетін, құқықтарының 
теңдігі мен тартып алынбайтындығын тану, бостандық пен әділдіктің және 
жалпыға бірдей бейбітшіліктің негізі болып табылатынына назар аудара 
отырып,

But instead, it outputs:
АДАМ ЌЂЌЫЌТАРЫНЫЊ ЖАЛПЫЃА БІРДЕЙ ДЕКЛАРАЦИЯСЫ
ПРЕАМБУЛА
Адам баласы џйелменініњ барлыќ мџшелеріне тѕн ќадір-ќасиетін, ќђќыќтарыныњ 
тењдігі мен тартып алынбайтындыѓын тану, бостандыќ пен ѕділдіктіњ жѕне 
жалпыѓа бірдей бейбітшіліктіњ негізі болып табылатынына назар аудара 
отырып,

<b>Please use labels and text to provide additional information.</b>
The correct text can be found here: 
http://www.lexilogos.com/declaration/kazakh.htm

As it appears, only the letters which are not in Russian Cyrillic alphabet 
have been misspelled.<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=510</p>

**Comment by stevenbird** [comment]
This will be resolved in the new UDHR corpus.

**Comment by salamatin** [comment]
@stevenbird 'Kazakh-UTF8' file still contains incorrect characters. There is a proper Kazakh text in the **udhr2** corpus, but it doesn't rectify the issue with **udhr**. Should the incorrect file be changed?

**Comment by kmike** [comment]
@salamatin there is no reason to use "udhr" corpus; it is kept for backwards compatibility. Maybe we should have a deprecation warning or something like this.

**Comment by salamatin** [comment]
@kmike Thanks — didn't know about it being deprecated. The book still refers to "udhr" at the moment.
