### ISSUE TITLE
nltk.probability.FreqDist.plot() throws "AttributeError: 'module' object has no attribute 'grid'" in Python 3.4

### ISSUE THREAD

**Issue by shpigunov** [nltk/nltk#991]
Whenever I try to plot a frequency distribution object, I get this. I tried doing `import matplotlib.pylab as pylab` as suggested in Issue #970, but it didn't help.

Here is a traceback:

`>>> myFreq.plot(100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk/probability.py", line 247, in plot
    pylab.grid(True, color="silver")
AttributeError: 'module' object has no attribute 'grid'`

**Comment by shpigunov** [comment]
The same code works as expected in Python 2.7, by the way.

**Comment by stevethecollier** [comment]
not sure if this is will help, but I had the same issue with 2.7
I think I installed matplotlib with easy_install initially 
so I uninstalled it
and re-installed it with pip
works for me now

**Comment by alvations** [comment]
@shpigunov are you still having the problem?

If yes, what is the output for the following on your machine?

```
>>> import matplotlib
>>> matplotlib.__version__
'2.0.2'
>>> import matplotlib.pylab as pylab
>>> pylab.grid
<function grid at 0x7f9d79c657d0>
```

In any case, try @stevethecollier suggestion, that should resolve the issue:

```
pip install -U matplotlib
```
