### ISSUE TITLE
nltk.Text.collocations() throws `TypeError: slice indices must be integers or None or have an __index__ method`, Python 3.4 on Mac

### ISSUE THREAD

**Issue by shpigunov** [nltk/nltk#992]
Here is a traceback:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk/text.py", line 357, in collocations
    self._collocations = finder.nbest(bigram_measures.likelihood_ratio, num)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk/collocations.py", line 112, in nbest
    return [p for p, s in self.score_ngrams(score_fn)[:n]]
TypeError: slice indices must be integers or None or have an __index__ method`

Again, this used to work OK in Python 2.7.

**Comment by shpigunov** [comment]
It may have something to do with the way Python 3 handles math operations. 
Quite possibly, the `n` passed to `nltk.collocations.nbest()` used to be an integer in Python 2 but it's not anymore in Python 3.

**Comment by zariuq** [comment]
Btw, if so, they changed Python 2 to do the same thing as Python 3 there. As I get a similar error.

**Comment by jnothman** [comment]
Looking at the code in both those modules, that is surprising, to say the least... Nor can I replicate it on 3.0a4. But then again, I'm not sure what Text instance you're using, as you haven't given us an example of code that triggers the error.

**Comment by jnothman** [comment]
Btw, at first I thought the sort of thing that changes numeric types between Py2 and 3 is integer division. I still don't see how that applies here. `num` is passed and it is a direct argument of `collocations()` with default value 20.

**Comment by zariuq** [comment]
Well, I get the same TypeError when trying to run http://www.nltk.org/book_1ed/ch03.html#code-stemmer-indexing (example 3.6). In Python 2 though.

>>> text.concordance('lie')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 17, in concordance
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 242, in __getitem__
    return self._cache[2][start-offset:stop-offset]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by jnothman** [comment]
what does that have to do with Text.collocations()?

**Comment by DGrutt** [comment]
I am having the same issue with Python 3.5 on Windows. The code I'm running is this tutorial. http://streamhacker.com/2010/05/10/text-classification-sentiment-analysis-naive-bayes-classifier/

**Comment by nschneid** [comment]
> I am having the same issue with Python 3.5 on Windows. The code I'm running is this tutorial. http://streamhacker.com/2010/05/10/text-classification-sentiment-analysis-naive-bayes-classifier/

The code on that page includes:

``` py
negcutoff = len(negfeats)*3/4
poscutoff = len(posfeats)*3/4
```

Which will return a float in Python 3.x. Changing each `/` to `//` will result in integer division.

**Comment by nschneid** [comment]
Regarding the original bug report, I am able to run `python -m nltk.text` without a problem on Python 3.5.2 (Anaconda 4.1.1) on OS X. Closing the issue absent code that triggers the error.
