### ISSUE TITLE
Offline install?

### ISSUE THREAD

**Issue by adnelson** [nltk/nltk#997]
Is there a way to install nltk without needing access to the internet? Running `python setup.py build` starts immediately by attempting to download stuff from pypi, but I need to be able to control what it's downloading -- more accurately, I want to have something with which I can install nltk in an environment without internet access at all.

**Comment by stevenbird** [comment]
@adnelson this is not strictly an NLTK issue, but a setuptools issue, and so I think you need to look into the documentation for setuptools to see if there's a solution. You can't be the first person to have this requirement. One thought I had was for you to do an install on an untouched python distribution, note all the dependencies, then create a collection of packages that need to be installed before attempting to install NLTK (by which time there will be no unsatisfied dependencies).

**Comment by ewan-klein** [comment]
@adnelson @stevenbird There are a number of Docker images for NLTK, e.g., https://registry.hub.docker.com/u/horkfnado/python-nltk/. One of these might be the way to go. Maybe we should think about producing an official NLTK Docker image.
